### ISSUE TITLE
Save the requests/collections in the project folder

### ISSUE THREAD

**Issue by drivesmoothly** [rangav/thunder-client-support#10]
**Is your feature request related to a problem? Please describe.**
To keep the test requests in sync with the project.
When the project's endpoints change (new fields, new requests, new version), the Thunder Client requests need to change as well. When debugging an older version of the project, deployed somewhere, it would be great to use the matching Thunder Client requests.

**Describe the solution you'd like**
There could be something like a thunder_client.config file within the project folder, that contains all the requests and the environments. So it would be version controlled together with the project. It would need to be some text based file, so it can be easily merged when multiple team members add/change requests.

**Describe alternatives you've considered**

**Implementation:**

**Comment by drivesmoothly** [comment]
Sorry, I saw this was already requested by somebody else and there is a ticket on this:
https://github.com/rangav/thunder-client-support/issues/9

Since I haven't seen this option and I saw another comment on the issue, maybe it would be good to default on that :)
Thanks for the good work!

**Comment by rangav** [comment]
ref - #2
