### ISSUE TITLE
`Collection` `Run All` order does not match defined order.

### ISSUE THREAD

**Issue by tvalladon** [rangav/thunder-client-support#100]
**Describe the bug**

`Collection` `Run All` tests not running in order defined.

**To Reproduce**

Create some tests for requests, go to collection and attempt to `run all`. 

Collection tests will not appear or run in the order defined.

This makes full testing impossible as create calls that return required data may need to run before query tests on the same id (using set env from payload return value)

In the attached screen shot I need things to run in the order defined. I have linked them with lines to show the issues.

In this case I need Register to run before any of the System or Account calls to verify created records are being retrieved properly.

![run_all_order_issues](https://user-images.githubusercontent.com/50340/116782049-c469ea00-aa3b-11eb-8296-4fddfe70c870.PNG)

**Expected behavior**

The the tests will appear and run in the same order defined in the collection.

**Platform:** 
 - OS: Windows10 WSL2 Ubuntu 20.04 Container

**Solution:**

**Comment by rangav** [comment]
Hi @tvalladon i will look into the issue, thanks for reporting.

**Comment by Gustavonobreza** [comment]
### In the last update this affected my VSCode too.
### I needed to downgrade to get back up and running

**Comment by rangav** [comment]
This is now fixed in v1.2.0, please update. 

Release details here 
https://github.com/rangav/thunder-client-support/releases/tag/1.2.0

**Comment by tvalladon** [comment]
Hello.

Thank you for all the work you are doing on this. This is set to be my preferred client when developing REST API's.

The order is better, some are still out of order compared to the Collections.

Would it be better to re-open this ticket or do you want me to create a new ticket?

Sorry it took so long to test, I am testing this on a weekend project and my weeks are pretty busy.

Current version: 1.2.1

I am attaching a screen-shot showing the issue. 

![image_2021-05-06_194614](https://user-images.githubusercontent.com/50340/117390847-b7b61d80-aea3-11eb-9878-3997244d6f77.png)

**Comment by rangav** [comment]
Hi @tvalladon, you can re-open no problem.

can you close vscode and reopen and test again. Let me know if the issue still there.

I will once test once meanwhile

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed.
