### ISSUE TITLE
Is there option to save activities in a different local temp file and ignore it for repo commit?

### ISSUE THREAD

**Issue by mssanjay** [rangav/thunder-client-support#1002]
**Your Team Size Using TC:**

3
**Question:**
Hi, I love the fact that ThunderClient artifacts are part of source repo. But as we test the requests, the activity / request history can grow large. Is there option to ignore these during repo checkin? Can we keep these activity files in a dot file and have it ignored by git?

Thanks
Sanjay

**Comment by rangav** [comment]
Hi @mssanjay you can add `thunder-activity.json` to .gitignore then it will be ignored from git.
