### ISSUE TITLE
Add documentation to folders

### ISSUE THREAD

**Issue by pfaustinopt** [rangav/thunder-client-support#1003]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I want to be able to add documentation to a group of request. I'm grouping requests into folders in order to create different test cases and I'd like to be able to add a summary to each test case. At the moment we're only allowed to add documentation to collections.

**Describe alternatives you've considered**

The current alternative is to either create a collection per test cases (this doesn't allow to create an hierarchy of folders) or add documentation to the first request of the folder. 

**Your Team Size Using TC:**

18

**Comment by rangav** [comment]
Thanks @pfaustinopt for creating this. Will review and add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.4.3

Please let me know your feedback.
