### ISSUE TITLE
Save pre-request variables in main request environment

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#1006]
**Is your feature request related to a problem? Please describe.**

I have two collections, let's say A and B. A request 1 on collection A has a pre-request 2 from collection B. Request 2 from collection B saves a variable that the request 1 needs but if each collection has its own environment, request 1 has no way of accessing that variable.

Currently the only way to achieve this is to share the same environment for the two collections.

**Describe the solution you'd like**

I would like for the saved variables from request 2 to be saved to collection A if the request 2 is a pre-request. Additionally, if request 2 has pre-requests, those should remain in the environment for collection B.

**Describe alternatives you've considered**

Like I said, currently the way of achieving this is to share the environment between collections, which decreases security for things like credentials.

**Your Team Size Using TC:**

just me

**Comment by rangav** [comment]
Thanks @andresatierf for the feedback, will review it.

**Comment by rangav** [comment]
I think request 2 can save variable value to local or global env then request 1 can access it.  e.g {{variable, local}}

or You can save it to current active environment e.g: {{variable, active}}

Just to keep it simple, otherwise it gets complicated.

**Comment by andresatierf** [comment]
I was not aware of that feature, I think that will solve my problem. thanks

**Comment by rangav** [comment]
Here is docs for Set Env Variable 
https://github.com/rangav/thunder-client-support#setenv
