### ISSUE TITLE
Cannot use Cookie in request headers

### ISSUE THREAD

**Issue by gweill-guigops** [rangav/thunder-client-support#1008]
**Describe the bug**
Any request with a Cookie in Header with = generates an error before the request is sent. 
The message "Error when sending request: Cannot read properties of undefined (reading 'loose')" appeares on the right side and Output tab is empty

**To Reproduce**
Add Cookie in Headers tab with a=b; as value.

**Expected behavior**
Cookie sent to the server without error
Funny thing, the Curl code is correctly generated and run as expected. 
 
![image](https://user-images.githubusercontent.com/122821276/217566885-9c51a603-312b-4d3c-be9e-95c630045634.png)
![image](https://user-images.githubusercontent.com/122821276/217569152-0edee91b-cf43-49d9-b93f-150c5d3da4f8.png)

**Platform:** 
 - OS: ubuntu 22.04
 - vscode version: 1.74.3
 - extension version: v2.4.0

**Comment by rangav** [comment]
Thanks @gweill-guigops for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
@gweill-guigops I have fixed the bug, please update to `v2.4.1`

**Comment by gweill-guigops** [comment]
Tested and approved ! Thank you !
