### ISSUE TITLE
If filter execution fails, variables are not replaced at all. No error message

### ISSUE THREAD

**Issue by dmitryduda** [rangav/thunder-client-support#1010]
**Describe the bug**
If filter execution fails, for example I try to decode non B64 string with atob, no error message is prompted, and all of the variables {{value}} are are kept as is

**To Reproduce**

set environment variable any non B64 string
variable = "hello"
url = "http://anyhost.com"

create request with url {{url}} and body
{
"parameter":{{variable|atob}}
}

send request and see than your url is http://%7B%7Burl%7D%7D

**Expected behavior**
Any kind of error message like "executing atob with parameter 'hello' ended with error"
Also do not interrupt other variables substitution, the "{{url}}" must be substituted to "http://anyhost.com" unlike "parameter" keeps as '{{variable|atob}}'

**Platform:** 
 - OS: windows
 - vscode version: 1.75.0
 - extension version: 2.4.1

**Your Team Size Using TC:**

0

**Comment by rangav** [comment]
Hi @dmitryduda the logs are display in output window, please check let and let me know If there is any

**Comment by dmitryduda** [comment]
Yes, it sais "Couldn't resolve the hostname to an IP address, Verify Url: http://%7B%7Burl%7D%7D/ele....."

**Comment by rangav** [comment]
Thanks for sharing, Can you screenshot of the request?

**Comment by dmitryduda** [comment]
![image](https://user-images.githubusercontent.com/1625448/217814828-70256362-f0cb-46f9-91c9-cc2306e1eeb0.png)

**Comment by dmitryduda** [comment]
![image](https://user-images.githubusercontent.com/1625448/217814967-f847f7ea-6fc7-4d70-92ad-8c9eaf54462c.png)

**Comment by dmitryduda** [comment]
I think it is important "data" is JSON

**Comment by rangav** [comment]
Thanks for sharing will look into it.

**Comment by rangav** [comment]
I think you should use `btoa` filter to encode the value

<img width="1437" alt="Screenshot 2023-02-09 at 16 20 32" src="https://user-images.githubusercontent.com/8637550/217872466-47adfd8e-8011-4664-b9e1-249550f57440.png">

**Comment by rangav** [comment]
<img width="640" alt="Screenshot 2023-02-09 at 16 21 51" src="https://user-images.githubusercontent.com/8637550/217872694-58d085aa-57a2-4eca-9379-a15023e571b6.png">

**Comment by dmitryduda** [comment]
Yes, absolutely, the point is when the execution fails, non of the variables is replaced, and also there is no message that can help identify the error. There will be great if only "parameter" keep raw but not other variables like url (or other ones you can have in request)

**Comment by rangav** [comment]
Thanks for the feedback, I think the url value is resolved and executed properly and but log is not correctly displayed.

will review and improve it

**Comment by rangav** [comment]
> Yes, absolutely, the point is when the execution fails, non of the variables is replaced, and also there is no message that can help identify the error. There will be great if only "parameter" keep raw but not other variables like url (or other ones you can have in request)

I am seeing proper logs 
<img width="1076" alt="Screenshot 2023-02-14 at 13 40 55" src="https://user-images.githubusercontent.com/8637550/218755581-660a11ef-5906-40bb-9052-493332c99575.png">

**Comment by dmitryduda** [comment]
The log is about the URL parameter, which is correct. 

The actual problem is when "atob" fails, for example is value is not B64. There is no log about it.

Try put in body 

{
"parameter":{{data|atob}}
}

and then feel the log

**Comment by dmitryduda** [comment]
Yout output is distinct from mine
![image](https://user-images.githubusercontent.com/1625448/218773709-19e7a008-06cd-4024-9877-11a0250bafbf.png)

**Comment by dmitryduda** [comment]
your output is distinct from mine
![image](https://user-images.githubusercontent.com/1625448/218773992-f4efd106-4911-449f-8c52-b6d3cd244d2e.png)

**Comment by dmitryduda** [comment]
But which token? Now I know is "data|btoa", but first time I couldn know exactly what is wrong. In example I put only 2 parameters, but in my real project there are about 10. No log like "filter at body line 2 executed with error"

**Comment by rangav** [comment]
I have tested on windows now, `atob ` filter is not throwing error.

**Comment by rangav** [comment]
I am closing this issue due inactivity
