### ISSUE TITLE
Filter (multiply) has confusing syntax and doesn't work 

### ISSUE THREAD

**Issue by dhiegomaga** [rangav/thunder-client-support#1011]
**Describe the bug**

Using filter for a simple multiply operation won't work. 

**To Reproduce**

Set a variable within a test using `Set Env Variable`
![image](https://user-images.githubusercontent.com/25873377/217826387-ff3a2b6f-7821-4d33-b128-0e08dd1e05e2.png)

Within a second test, try to multiply using any of the possible permutations of the syntax for multiplacation:
(remember: `The syntax is {{number | multiply(5)}} or {{number | multiply("variableName")}}` )
 
![image](https://user-images.githubusercontent.com/25873377/217828125-cb917cee-757e-4faf-9a5c-d4cdd231ac9e.png)

Result: `Query: json.my.path equal to 0 => Actual: 1234` 

1234 is the return of `json.my.path`, `{{myVar | multiply(1)}}` **is always evaluating to 0** (or eg. `{{"myVar" | multiply(1)}}` but I guess that's because the syntax is wrong.) 

Also tried using different quote spacing, etc. because for some reason that seems to affect the result.  

**Expected behavior**

That the test would pass with `{{myVar | multiply(1)}} = 1234`

**Platform:** 
 - OS: Linux
 - vscode version: 1.75.0
 - extension version: v2.4.1

**Your Team Size Using TC:**

0

**Comment by rangav** [comment]
Thanks for reporting the issue.

can you share screenshot of full `Tests tab` of the request?

**Comment by dhiegomaga** [comment]
I can't share because there is sensitive information, but I can answer questions about it. 

It's 2 different requests. One sets the env variable, the second does the multiplication. 

It's a simple test really. I am able to do eg `{{myVar}}` and it returns the correct value for it. So for instance, this test passes: 

`json.my.path equal {{myVar}}`

**Comment by rangav** [comment]
Ok got it thanks. What is value of `myVar` variable value in Environment view. Can you confirm this?

**Comment by dhiegomaga** [comment]
The value of `myVar` in the `Environment Variables` tab is `1234`

**Comment by rangav** [comment]
Thanks for sharing will verify and get back to you.

**Comment by rangav** [comment]
Its working for me, Did you make that `environment active`?

<img width="1135" alt="Screenshot 2023-02-09 at 15 54 54" src="https://user-images.githubusercontent.com/8637550/217866218-de7b322c-ea67-475a-88f1-3e57fa861c54.png">



Tests
<img width="546" alt="Screenshot 2023-02-09 at 15 55 57" src="https://user-images.githubusercontent.com/8637550/217866296-e52a3777-7c77-4536-b2bb-1a73bf7ef3dd.png">


Env
<img width="809" alt="Screenshot 2023-02-09 at 15 56 28" src="https://user-images.githubusercontent.com/8637550/217866321-cea34288-c044-48ed-9934-3cd9d3d9cbe3.png">

**Comment by rangav** [comment]
Multiply syntax: I know when you use it for first time it may seem odd the syntax. But you will get used to it as you use it frequently.

**Filters are reusable functions.**

The way you call syntax is similar to normal functions.

example:
```js
function multiply(input:string|number){
    .....
    return finalValue
}

// calling
multiply(4)
multiple("variable")
```

All the filters follow same syntax `{{variable | filter1 | filter2...}}`, so it will be difficult to change syntax for one operation like multiply.

See details here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md

**Comment by dhiegomaga** [comment]
Yeah, it makes sense.

By the way, most testing frameworks allow you to write custom code as a test. For instance, for Javascript you can use Mocha, and write something like: 

```js
let arr = ['a', 'b', 'c']
expect(arr).to.include('a') // test succeeds

for(let element of arr) {
  expect(element).to.be.a('string'); // test succeeds
}
```

Postman also has this kind of testing scriptn functionality: https://learning.postman.com/docs/writing-scripts/test-scripts/

Is this possible with ThunderClient? Or is there an intention to add this feature in the future?

**Comment by rangav** [comment]
You can write your own custom script filters

see details here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
