### ISSUE TITLE
Keep last scroll position when response loads

### ISSUE THREAD

**Issue by Yawan-1** [rangav/thunder-client-support#1015]
**Is your feature request related to a problem? Please describe.**
When I scroll the returned response and click "Send" again then the scrolled position resets to top right after response loads. But I don't want it to scroll to top when response loads, it should be same at least for same response as last though.

**Describe the solution you'd like**
I want scroll position to stay the same it was before previous response. Yeah... It can change if the response is different from previous response but if it is the same then It should not scroll to top.

Suppose, If I am checking if the field changes or updates so I left the scroll position pointing at that field but when I make a call to api then field lost. I will need to find that field again.

**Comment by rangav** [comment]
Thanks @Yawan-1 for the feedback, will review it.
