### ISSUE TITLE
Code verifier and code challenge issue

### ISSUE THREAD

**Issue by minnocenti901** [rangav/thunder-client-support#1017]
**Your Team Size Using TC:**
3

**Question:**
Hello, I'm trying to use OAuth2 but I'm facing a strange issue:
I'm using code verifier with S256 
the code is: 191bdcd41d8e6343ca234f81b0b6e5bb248085cbce03faf11ea9e807
the thunder client sends a code_challenge = vkjd78C6qd23Q7T23PJVBnt4gwT6pFcLy4mRVr5O7eg
i dont understand how is it created

**Comment by rangav** [comment]
The code will be SHA256 encoded and set to `code_challenge`

Here is details
https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow-with-pkce#javascript-sample

**Comment by rangav** [comment]
let me double check and get back to you

**Comment by rangav** [comment]
This code challenge will be - `vkjd78C6qd23Q7T23PJVBnt4gwT6pFcLy4mRVr5O7eg`
```js
var crypto = require("crypto");

function base64URLEncode(str) {
    return str.toString('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=/g, '');
}

 function sha256(buffer) {
        return crypto.createHash('sha256').update(buffer).digest();
    }

var code = "191bdcd41d8e6343ca234f81b0b6e5bb248085cbce03faf11ea9e807"
var verifier = base64URLEncode(sha256(code));
console.log(verifier)
```

**Comment by rangav** [comment]
This is correct link - https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow-with-pkce#create-code-challenge

**Comment by minnocenti901** [comment]
Thanks for the clarification.
