### ISSUE TITLE
Ability to run Pre Filters before Pre Requests

### ISSUE THREAD

**Issue by wavveen** [rangav/thunder-client-support#1018]
**Is your feature request related to a problem? Please describe.**
I would like to be able to run some code, and depending on the outcome run a Pre Request.

**Describe the solution you'd like**
Being able to run Pre Filters before Pre Requests

**Describe alternatives you've considered**
Currently we are executing a dummy requests as Pre Request1, this dummy requests has a Pre Filter that executes a piece of code. And depending on the outcome of this Pre Filter, Pre Request2 gets executed (or not). By realizing this feature we wouldn't need to execute this dummy request as pre request anymore

**Your Team Size Using TC:**
20

**Comment by rangav** [comment]
Thanks @wavveen for creating feature request. Will review it.

Alternatively you can add pre-filter first pre-request.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.
