### ISSUE TITLE
How to manage secrets

### ISSUE THREAD

**Issue by bhoudebert** [rangav/thunder-client-support#1019]
**Your Team Size Using TC:** I am the first, trying to qualify if we could go further with the tool or not.

**Question:**

Let's say I have a peculiar header `x-api-token`, which is different from environment, you could definitely see it as a secret.

It is fine for the `localhost` environment to have such value as a variable but for the others, at no point we would want to store in other environment any secrets.

Point is, if we do not create any variable and use a plain value in the requests headers, fine but it is still harmful as someone change its environment, call let's say UAT or even PROD, put in the header a secret, save it ... and boom it is going into the source code.

Sure PR are there, blet & seatbelt too, but in the end I found it quite inconvenient in our situation.

**Idea:**

Would it be possible to have a list of `never save this variable` in request/payload/path (not sure this is a nice thing btw)

Not sure I would have the right solution but would it be possible to create some kind of variable `ask on demand`.

Let's take this example, using the path for more convenience here: `http://mydomain/users/{{popup:user_id}}`. When hitting the `Send` button, the extension would present a popup asking to complete expected fields (there could be many dy design).

Maybe not an easy thing to do but no tools currently are addressing this correctly. Either you have to duplicate the collection locally either you save the secrets on the tools which would be security advisement a very bad thing.

Another possibility would be to allow some environment variable to be encrypted using a `master password`. Not sure this is better but could be a quick win too.

Anyway let me know if you think of something else or if I miss something somewhere that we could use already.

NB: local environment does not match the behavior as we could have several different remote env

**Comment by bhoudebert** [comment]
Just found the notion filter so definitely would be nice to have {{ x-api-token | popup("Please provide the api token") }}

**Comment by rangav** [comment]
Thanks @bhoudebert for trying out Thunder Client. 

In this API client all the data is stored locally on your device. so more secure than any other API client.

- Git Sync: You can also save data to git to your current workspace - [details here](https://github.com/rangav/thunder-client-support#git-sync)
- Secrets: To manage secrets you can save data in local environment and these values are not saved to git. They are stored locally specific to user. and use then `{{x-api-token}}`

Docs for environments here
https://github.com/rangav/thunder-client-support#environments

<img width="307" alt="Screenshot 2023-02-18 at 17 37 58" src="https://user-images.githubusercontent.com/8637550/219880241-eab00a3b-dec9-42a0-9622-d54e05f92b33.png">

**Comment by bhoudebert** [comment]
Ah great it was not totally clear to me that local is read also when another is active.

Thanks
