### ISSUE TITLE
How to use Custom paths from settings

### ISSUE THREAD

**Issue by harshlodhi82** [rangav/thunder-client-support#102]
Hi, I want to save the API collection on my project so my teammates can load it. I think there is support to load the collection from project and thunder client can do it automatically. I added the path to collection (.json file) in settings but I don't know why it is not working. Please help me to resolve this thing. Thanks in advance.

**Comment by rangav** [comment]
Hi @harshlodhi82 
1. **custom location** is the folder path where you like save the data. its a folder path not json file
2. Load from project: select this it will automatically save data in the current open project in vscode

See team features section on documentation.

**Comment by harshlodhi82** [comment]
Yeah got it, Thanks @rangav
