### ISSUE TITLE
Tests: override schema validation

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#1020]
**Is your feature request related to a problem? Please describe.**

There is no way to override a schema test for a request that does not return anything.
I have a folder with a schema test. inside the folder I have a bunch of requests that pass the validation. There is one test that does not return anything, therefore fails the schema test.

**Describe the solution you'd like**

Ability to create an override test like: `Response Body | schema | undefined` and the schema validation does not run for that request

**Describe alternatives you've considered**

Assigning `undefined`, `null`, `none` or something similar to override a schema validation from a parent folder.
I believe using one of these options is better than an empty test, because this way we can still use the empty one in the parent folder to force any tests without a schema to fail.

For now I've removed the test from the parent folder.

**Your Team Size Using TC:**

Just me

**Comment by rangav** [comment]
Thanks @andresatierf for the feedback, will review it.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.5.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.

**Comment by andresatierf** [comment]
Works as intended. Thank you :heart:
