### ISSUE TITLE
Filter input for Environment variables

### ISSUE THREAD

**Issue by StephaneAdeso** [rangav/thunder-client-support#1022]
I have an Environment of 400 variables that i use in my job. Some times i have to scroll up and down to find the correct variable.

Would be awsome to have a filter input on the top of the window that only show you the variables that match with the typed text.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.5.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.
