### ISSUE TITLE
Add support to have full scripting on the Pre Request and Test tabs instead of the filters

### ISSUE THREAD

**Issue by jasoncaunt73** [rangav/thunder-client-support#1026]
Add support to have full scripting on the Pre Request and Test tabs instead of the filters. We use our own scripts in Postman.

We are considering moving away from Postman due to licensing costs and limitations being introduced.

So when we import our collections everything is perfect, except the Pre Request and Test tabs.

Even having a filter option that allows an inline script that could pull in the exec value from the postman collection file.

**Comment by rangav** [comment]
Thanks @jasoncaunt73 for the feedback. Will review it.

Currently you can use `pre-filter` to write your own custom script similar to postman and others.

Custom Filters Docs here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

Let me know if you any further questions

<img width="788" alt="Screenshot 2023-02-23 at 16 04 52" src="https://user-images.githubusercontent.com/8637550/220963336-1c132833-b2e7-4dec-8f9b-c749ee5fd4ac.png">

**Comment by rangav** [comment]
> Even having a filter option that allows an inline script that could pull in the exec value from the postman collection file.

Can you please provide a sample example to understand more about this

**Comment by jasoncaunt73** [comment]
Thanks for getting back so quick. So Postman has a inline pane to write the scripts in. So basically its just a large test box. The value that sits inside those tabs is in the collection json under the event like below. (This has a script exec section for each listen type of Test and prerequest.)

									"event": [
										{
											"listen": "test",
											"script": {
												"exec": [
													"<SOME JAVA SCRIPT>"
												],
												"type": "text/javascript"
											}
										},
										{
											"listen": "prerequest",
											"script": {
												"exec": [
													"<SOME JAVA SCRIPT>"
												],
												"type": "text/javascript"
											}
										}

It would be nice if when you imported the Postman collection if any text existed in the exec block it would pick a filter type of something like "Inline Script" and then the value box was the value from the exec block. So it would just be like an inline script. That you could also edit if need be.

This would then make a Postman collection fully work in this application and no need for the Postman Bloatware.

This would need to be on request level and also on the collection level also as you can have pre request and tests that sit right at the top level.

Hope this answers your question. If you need more info just nudge me back

thanks

Jason

**Comment by rangav** [comment]
Thanks Jason, its clear now. Will review it.

**Comment by rancheng518** [comment]
I'm also very interested in this feature as without it, it makes it very challenging to convert existing Postman Collections to Thunder Client.

**Comment by nippsh** [comment]
This is the only thing that keeps us from moving from postman to thunder client. Would love to see this implemented.

**Comment by rangav** [comment]
Thanks everyone for the feedback, Will add this feature to roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.14.0`

https://github.com/rangav/thunder-client-support/releases/tag/v2.14.0

Please test and let me know your feedback.

**Comment by robnick-obbe** [comment]
You have a typo in your doco:

```
const chai = require("chai");
var expect = chai.expect;
var assert = **chair**.assert;

```

chair instead of chai

**Comment by rangav** [comment]
Thanks fixed the typo
