### ISSUE TITLE
Storing sensitive environment variables outside of `thunderEnvironment.json`.

### ISSUE THREAD

**Issue by kb-ig** [rangav/thunder-client-support#1029]
**Your Team Size Using TC:**
Potentially ~20

**Question:** 

I'm looking for a way to store sensitive environment variables outside of `thunderEnvironment.json`. I plan on having a single repository with all my API requests, and this will be shared with the rest of my team. I have various pieces of sensitive information (username & password for pre-request authorisation) that should not be shared with anyone else. I can store these in a .env file, however...

I have a pre-request script that gets my username & password, authenticates me, and writes my auth token as an environment variable. Setting it as an environment variable with `tc.setVar` results in this being added to `thunderEnvironment.json`, and would end up being checked in to my repo, so this is no good. I _could_ avoid writing the token as a env var, however this means I'd need to authenticate before every single request, which is not ideal - I want to only fetch a token when I dont already have one or it has expired.

- Is there any way for a custom filter to store a variable somewhere other than `thunderEnvironment.json`? 
- Perhaps writing to `.env` could be an option?
- Perhaps an option to mark environment variables as sensitive, and be stored somewhere else instead of `thunderEnvironment.json` (which can be excluded from git)

(Worth mentioning I have I have `Thunder-client: Save To Workspace = true`)

**Comment by rangav** [comment]
Hi @kb-ig 

You can save sensitive data in `local environment`, where the values are not stored in main `thunderEnvironment.json`.

- From custom scripts you can use `local` scope `tc.setVar(varName, value, "local")`
- To save to local env from `Tests` tab, you can use this format `{{variable, local}}`

**References**
- Set Env in Custom scripts - https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js#L43
- Set env with scope in Tests Tab - https://github.com/rangav/thunder-client-support#set-env-with-scope

Let me know if you have any further questions.

**Comment by kb-ig** [comment]
@rangav Thanks for a quick response! This seems like what I'm looking for, but I think I'm still missing a piece of the puzzle.

If I have multiple environments (say `Dev` and `Staging`), they would have the same variables with different sensitive values, e.g.

- Dev
  - `Username`: `kb-ig.dev`
  - `Password`: `dev-password`
- Staging
  - `Username`: `kb-ig.staging`
  - `Password`: `staging-password`

I can have two different .env files for each of these, so that's fine. However in my pre-request script, if I save the token to Local Environment with `tc.setVar('MyToken', token, 'local');`, the wrong token will be used if I switch environments. 

Is it possible to get the name of the current environment in a custom filter (sorry if I've missed this on the docs)? If so, then I could include that in my token name when I save it to local, e.g.
```js
const env = tc.currentEnvironment;
tc.setVar(`${env}-MyToken`, token, 'local');
```
I dont see anything similar on the [`tc-types`](https://github.com/rangav/thunder-client-support/blob/master/docs/tc-types.d.ts), but maybe there's a built in environment variable that gives me the name of the current environment, e.g. `tc.getVar('CurrentEnvironment)`?

Or if there's any other approach that you'd recommend I use to cater for Local Environment variable values being different for different Environments, I'd appreciate the advice. Thanks!

**Comment by rangav** [comment]
Thanks for the feedback.

Currently not possible to get name of current active env in Custom Scripts.

But here is alternative solution:
- You can create new variable called `envName` in both environments and assign value `Dev` and `Staging`.
- Then in custom scripts you can get that value using `tc.getVar("envName")`

I will provide new api in the next update to get env name

**Comment by rangav** [comment]
One more question when you save with `tc.setVar(`${env}-MyToken`, token, 'local');`, 

how will you use these variables then again in other requests?

**Comment by kb-ig** [comment]
Good question on accessing this variable in requests, though. I overlooked this detail. Maybe it wont be possible. I'd probably need to access it with nested environment variable syntax, like:
```
{{{{CurrentEnvironment}}-MyToken}}
```
Which would resolve to looking for:
```
{{Dev-MyToken}}
```
Which would resolve to whatever token was saved by the custom script.

Which I can already tell is not currently supported. Not sure if there would be enough need from the community for this kind of feature.

I'm struggling to think of any alternative approach. I'm totally new to Thunder Client (as you can probably tell), so I'll try to get more familiar with it over the next day or two and see if I can find another solution to this problem.

Kudos on this, btw - so far I'm very optimistic about this extension. Great work :grinning:

**Comment by rangav** [comment]
Thanks @kb-ig glad you like it. 

I actually think, you don't need to save separate variables in local env for environment.

You can think of variables as temp local disposable values.

For example, let say current env is `Dev`

1. you generate some token and save it to Local Env.
2. you will use these in following requests.
3. when you change env also , steps 1 and 2 will repeated. so you will always have correct value

You can also clear local env variable value in the pre-request filter or tests tab

Let me know your feedback

**Comment by joaonunogomes** [comment]
Hi! I kind of have the same issue. I need to have several instances of the same variable to be able to quickly change it based in the current environment.
Currently I'm doing that using several `.env` files and adding them to `.gitignore`.
Something that would work for my case is the possibility to have several `Local Environment` and have them work as the "other" environments work, by having a way to set as active or not active.
Is this something planned ahead?

**Comment by rangav** [comment]
Hi @joaonunogomes thanks for the feedback. 

Currently multiple `Local Environments` is not planned

**Comment by kb-ig** [comment]
For my use case, I have managed to make it work by:
- Storing the "current environment" as a var in each of my non-local environments 
- Storing the "previous enviornment" as a var in my local environment
- pre-run filter that checks if the "current environment" is different to "previous environment," and if so, clears certain vars from local environment (such as scoped API tokens), and updates the "previous environment" in local environment with the value of "current environment".

The next time my auth pre-run script runs, it will see that I no longer have my auth token stored and will re-authenticate me, then store the token in local env until the environment changes. Hopefully that makes sense.

@rangav  One further question; is it possible to have multiple pre-run filters? Based on [the docs](https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#run-custom-filter-directly) it seems not, but I just want to double check. If not, perhaps this is something that might be worth adding in a future version? In the meantime, the work around is fairly straight forward - I can just create a single script that calls all of the other scripts that you want to run pre-request.

**Comment by rangav** [comment]
@kb-ig good you got it working.

Multiple Pre filters:
- The workaround you mentioned is best way do this.

Your Main Pre-filter will call all the other functions or filters needed to run.

Don't we need separate functionality for multiple filters.

**Comment by kb-ig** [comment]
Thanks for your help with this, happy to close the issue

**Comment by rangav** [comment]
You are welcome :)
