### ISSUE TITLE
Hide password with '*' in Auth -> Basic auth

### ISSUE THREAD

**Issue by guillaume-houioux** [rangav/thunder-client-support#103]
**Is your feature request related to a problem? Please describe.**

Password is not hidden when we type the input

**Describe the solution you'd like**

Change the input field to hide password with '*' character

**Comment by rangav** [comment]
Hi @guillaume-houioux i will fix this in next update

**Comment by rangav** [comment]
this is fixed in v1.2.1 details here https://github.com/rangav/thunder-client-support/releases/tag/1.2.1
