### ISSUE TITLE
Preserve request editor selection (Body, Query, etc.)

### ISSUE THREAD

**Issue by glenncarr** [rangav/thunder-client-support#1030]
When sending and editing requests, I would like the "Body" to be displayed initially, either by remembering the selection or being able to set "Body" as the default instead of "Query".

Thanks for a great tool!

**Comment by rangav** [comment]
Thanks @glenncarr for the feedback. Will add to roadmap.

Currently when you open post request with body, the body tab will be active instead of query.

**Comment by glenncarr** [comment]
Ah, thanks @rangav.  I had only used GET (I just learned about this extension yesterday).

Thank you very much.

**Comment by rangav** [comment]
Now I enabled for all methods, If the is body value present, then body tab will be active automatically when you open request. 

Dont think we need new setting for this.

I am closing this issue, feel free to re-open if needed

**Comment by glenncarr** [comment]
thank you!
