### ISSUE TITLE
Possible to convert and display base64-encoded data from response as an image?

### ISSUE THREAD

**Issue by glenncarr** [rangav/thunder-client-support#1031]
Is there a way to perform a conversion on data in the response?  Specifically, I'd like to convert base64-encoded png data and display the png as an image.

Thanks again for a great tool.

**Comment by rangav** [comment]
Hi @glenncarr currently not possible. You have to return image binary data with proper content type for image to display in response.

**Comment by glenncarr** [comment]
Thank you @rangav.  Could an action be performed that knew where to find the encoded data within the response and decode the encoded data, then subsequently display it with `data:image/png;base64,`?  Sorry, I'm new to this.

**Comment by rangav** [comment]
Sure will look into it.

can you share a sample base 64 encoded image data for testing?

**Comment by glenncarr** [comment]
Sure:

Here's a sample response:
https://gist.github.com/glenncarr/76ebf2edd8c1c7b78491fcd4024bf87e

Thanks!

**Comment by rangav** [comment]
Thanks @glenncarr for sharing 

this could be difficult to display I think 

Does any API client do this?

Is it possible to output just the image data directly in response?

**Comment by glenncarr** [comment]
We have a custom API client that knows the XPath of the data in the response.  It's a pretty big stretch to expect a generic API client to do this, but I thought custom scripting might be able to handle it.

Don't spend any more time looking into it - I thought it might simply be something that had an easy solution that I wasn't aware of.  Thanks for considering it.

Thanks again for a nice lightweight VS option.

**Comment by rangav** [comment]
You are welcome. Closing the issue.
