### ISSUE TITLE
Run collection file in custom tests

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#1033]
**Your Team Size Using TC:**

just me

**Question:**
Is there a way to access the variables from the `Run Collection` file inside a custom script in the tests tab? I already know that `tc.setEnv()` exists.
I want to login multiple users and save their respective tokens in different env variables. Currently what I have is the same folder copied over and over. Is there a way that I can use the `Run Collection` file to define the logins and the variable names that I want to set for each user?
Something like:
```json
[
  { "username": "user1", "password": "user1", "varName": "user1Token" },
  { "username": "user2", "password": "user2", "varName": "user2Token" },
]
```

**Comment by rangav** [comment]
Hi @andresatierf 

You can use data file input in Run Collection view
<img width="1043" alt="Screenshot 2023-02-27 at 12 59 55" src="https://user-images.githubusercontent.com/8637550/221570387-5ac1d496-084a-4702-afb2-078c2b1ccbcc.png">

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by andresatierf** [comment]
yeah, my bad. I managed to make it work. I had nested variables and that does not seem to be possible. Thanks
