### ISSUE TITLE
Refactor broken body

### ISSUE THREAD

**Issue by Mmartos13** [rangav/thunder-client-support#1034]
**Describe the bug**
There's a error when I try to push format on body, if there exits ' symbol it takes it as " and the body is broken, withouth possibility of undo changes of format.
**To Reproduce**
Request--> Body --> Format
**Expected behavior**
I would like of having there a json well formatted, but doesn't miss ' string due to format.
**Platform:** 
 - OS: Linux Ubuntu 22
 - vscode version: v1.72.2
 - extension version: v2.5.0

**Your Team Size Using TC:**
10 people

**Comment by rangav** [comment]
Thanks @Mmartos13 for reporting the bug will look into it.

**Comment by Mmartos13** [comment]
Thank you for take it into accout @rangav !

**Comment by rangav** [comment]
This bug is now fixed, please update to v2.5.1

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.1

Please let me know your feedback.
