### ISSUE TITLE
Dissapeared requests when merge between two branches

### ISSUE THREAD

**Issue by Mmartos13** [rangav/thunder-client-support#1035]
**Your Team Size Using TC:**
10 
**Question:**
How can we manage multiple branches and avoid to collision pre-request?
Sometimes when we merge 2 branches, some request dissapear and we can't recover it.

**Comment by rangav** [comment]
Hi @Mmartos13 

Was there a merge conflict when you try to merge it?

You can view the history of the file and recover it manually.

**Comment by Mmartos13** [comment]
Hello. 
Yes I can see merge conflict, that modify id, then it is the reason to collide. I can guess that the way is taking care when merging, but I would like to know is there's another way.

**Comment by rangav** [comment]
You can open conflict in the new 2 way merge editor, we have to be careful here in selecting the items. 

Try using the history of file to recover the missing parts?

**Comment by Mmartos13** [comment]
Thank you @rangav ! I will do it like that on the next merge.

**Comment by rangav** [comment]
related to #574

**Comment by rangav** [comment]
We are planning for `splitting collection` into multiple request files to reduce merge conflicts - https://github.com/thunderclient/thunder-client-support/issues/1507

Can you please let me know your feedback
