### ISSUE TITLE
Retry logic possible?

### ISSUE THREAD

**Issue by koenmetsu** [rangav/thunder-client-support#1036]
**Your Team Size Using TC:**
5

**Question:**
Is there a way to implement retry logic? Either simple `retry x times with backoff of x seconds` or more advanced `if response code = xxx retry x times with exponential backoff`.

**Comment by rangav** [comment]
Hi @koenmetsu 

Simple retry should be possible easily.

Can you share more details of your use-case where is useful? 

Do you want it part of collection runner?

**Comment by koenmetsu** [comment]
Exactly. 

Our apis are eventually consistent. Flow goes like:
POST -> 202 Accepted
GET detail -> 412 (when not consistent yet)
GET detail -> 200 (when finally consistent)

We want to run tests to verify this flow.

**Comment by rangav** [comment]
Sure will add to roadmap. 

Planning to add it only when you run from CLI? Is that good enough? Or you want from extension UI runner also?

**Comment by koenmetsu** [comment]
I think I saw this more as a pre-request filter. Like: retry this 5 times until you get status 200, otherwise fail.

**Comment by rangav** [comment]
Dont think this will work as pre-request filter. The current filters implementation is different, might be difficult to achieve this.

**Comment by koenmetsu** [comment]
How would you see that logic work? Configurable retry for certain http codes?

**Comment by rangav** [comment]
`tc --col 'colName' --retry 3,5,412-404`

Rough idea above - 3 = retry time, 5 secs wait time ( could be exponential ), retry for for codes 412 and 404

Let me know what you think?

CLI documentation
https://medium.com/p/d91eb5c71d8e

**Comment by programatix** [comment]
Can you also add repeat from variable? The variable can be a true/false value. We have some tests, where we may need to repeat the PUT request several times, updating the data in stages.

I suggest adding a "Repeat Condition" where it takes a variable name, in the Tests tab. 

For example, the GET request has a pre-filter run. It will load the required data from a data file. After Tests, it will determine whether it need to re-run (I'm using some filter hack to determine that) and update a variable whether to repeat or not (true/false). The thunder check the repeat condition variable and repeat if it is true.

**Comment by rangav** [comment]
HI All, You can use the following inline script in Tests scripting section
- this is sample code, please modify as per your requirements.

```js
let incrementCount = tc.getVar('incrementCount') || 0;
let code = tc.response.status;

if(incrementCount < 20 && code !== 200)
{
      incrementCount = incrementCount + 1
      tc.setVar( 'incrementCount', incrementCount)
      console.log(incrementCount)
     // acting as if i didnt get the desired response so would like to retry
      tc.runRequest(tc.request.id) // <<--------------
}
```

**Comment by rangav** [comment]
I am closing this issue, as its better to use above js code for retry logic
