### ISSUE TITLE
thunderclient.json is not working as expected with Git

### ISSUE THREAD

**Issue by RafaelDiazAnguita** [rangav/thunder-client-support#1037]
Hi, we are using thunderclient in a team of 4,5 developers and we have activated the "Save to workspace" setting in the extension options.

The problem is when we are creating, eliminating, updating tests, etc.. the file thunderclient.json that saves all the requests is not working well when pushing changes to git. Git doesn't recognizes well the changes and sometimes the resultant json is bad formed or the requests very similar are mixed up.

There will be great if the requests of this file got his own json file inside folders following the same structure as the UI.

**Comment by rangav** [comment]
Hi @RafaelDiazAnguita thanks for the feedback. 

Are you having issues with git merge? or git is not detecting file changes properly?

**Comment by RafaelDiazAnguita** [comment]
Hi @rangav thank you for the reply, the issues are with git merge.

**Comment by rangav** [comment]
When you are doing merge you should be careful in selecting changes and also make sure the final json is valid?

I will also do additional research to reduce merge conflicts.

**Comment by RafaelDiazAnguita** [comment]
Yes, we select the changes manually of course. We have many similar requests and sometimes thunderclient changes the requests order inside the json and we don't know where exactly the changes come from. I will attach screenshots when it happens again so you have more information. Thank you again.

**Comment by rangav** [comment]
How many collections and requests you have? will help for research.

**Comment by rangav** [comment]
There is existing issue for this #1035, Closing this, please add any further comments there.

**Comment by rangav** [comment]
We now split the Collections and Environments into separate files to reduce merge conflicts in `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.

**Comment by rangav** [comment]
We have a feature request for splitting collection into multiple request files to reduce merge conflicts - https://github.com/rangav/thunder-client-support/issues/1507

Can you please let me know your feedback
