### ISSUE TITLE
How to access request body in Tests?

### ISSUE THREAD

**Issue by mssanjay** [rangav/thunder-client-support#1038]
Hi,
I like to access Request Body in Tests and set an Environment Variable. I need this value for other requests that I would like to use it for. I am unable to find request object. Let me know.

Thanks
Sanjay

**Comment by rangav** [comment]
Hi @mssanjay 

see docs here
https://github.com/rangav/thunder-client-support#setenv

let me know if you have any further questions

**Comment by rangav** [comment]
Can you share your tests tab screenshot and let me know which test did not work

**Comment by rangav** [comment]
Only works with env variables not system variables 

`{{guid, global}}` - remove hash

**Comment by rangav** [comment]
If you share screenshot then I can tell you where you doing wrong

**Comment by rangav** [comment]
You can use pre-filter via custom scripting.

Docs here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

Scripting
![image](https://user-images.githubusercontent.com/8637550/222988491-7d55961a-dcb1-4c07-a6fe-ef687447edc9.png)

Pre-filter
![image](https://user-images.githubusercontent.com/8637550/222988476-24c6993b-741b-43ae-9e60-c93b7bedc8ac.png)

**Comment by rangav** [comment]
Good you got it working.

Sorry code I shared is wrong, see below the correct one.  
- To access request body json use - `tc.request.body.raw`

![image](https://user-images.githubusercontent.com/8637550/223169017-6ddfd7c7-eb42-4875-a681-b0f985b5ac4b.png)


### One more correction:
- Filters in tests are used in format - `json.kocid | setObjectId` dont need () braces

**Comment by rangav** [comment]
closing this issue feel free to reopen if needed
