### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by anonymous-sys19** [rangav/thunder-client-support#1039]
- Issue Type: `Performance`
- Extension Name: `vscode-thunder-client`
- Extension Version: `2.5.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ADMINI~1/AppData/Local/Temp/rangav.vscode-thunder-client-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rangav** [comment]
Hi @anonymous-sys19 thanks for reporting the issue.

what caused the high cpu load?

Is it while running a request or running collection?
