### ISSUE TITLE
Add support for HTTP/2

### ISSUE THREAD

**Issue by cmatskas** [rangav/thunder-client-support#104]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please provide support for the HTTP/2 protocol

**Describe alternatives you've considered**
There are no alternatives

**Implementation:**
This is the RFC implementation for HTTP/2 https://tools.ietf.org/html/rfc7540
Thanks

**Comment by rangav** [comment]
Hi @cmatskas will add to roadmap and notify you when it’s done.

**Comment by cmatskas** [comment]
@rangav thanks for the quick response. Great work on the extension! My new favorite tool in VS Code :)

**Comment by rangav** [comment]
Thanks @cmatskas glad to know you like it. so far very response from all users.

**Comment by cmatskas** [comment]
Maybe because of this? https://www.tiktok.com/@christosmatskas/video/6957336849304096006?

**Comment by rangav** [comment]
That great to know there is tiktok video now.

Actually this tool was first discovered by James Quick, his YouTube video made us instantly popular 

https://youtu.be/AbCTlemwZ1k

**Comment by rangav** [comment]
Hi @cmatskas, This feature will be part of next update. 

Do you need proxy support as well for http2?

**Comment by rangav** [comment]
This feature is now implemented in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
