### ISSUE TITLE
Pre-request: more conditions

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#1043]
**Please describe feature/problem details and solution you'd like.**

Ability to set conditions like `When variable X > 5`

**Describe alternatives you've considered**

**Your Team Size Using TC:**

1

**Comment by rangav** [comment]
Hi @andresatierf will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.9.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please let me know your feedback.
