### ISSUE TITLE
Unable to import Local Env after exporting

### ISSUE THREAD

**Issue by joaonunogomes** [rangav/thunder-client-support#1044]
**Describe the bug**
I've been using `Local Env` to store credentials and avoid staging it into the git repository. Since these credentials need to be shared internally in my team, I've exported my `Local Env` so other team members could import it into their computers.

when importing the exported `Local Env` nothing happens and we end up having to write each one of the variables of the exported file, by hand.
 
**To Reproduce**
1. Create a few variables on `Local Env`
2. Export the `Local Env`
3. Delete `Local Env`
4. Import `Local Env`

**Expected behavior**
The previously exported `Local Env` should be imported with all variables

**Platform:** 
 - OS: Windows
 - vscode version: 1.76.0
 - extension version: v2.5.0 - (2023-02-27)

**Your Team Size Using TC:**
3

**Comment by rangav** [comment]
Thanks @joaonunogomes for the feedback, will add to roadmap.

**Comment by rangav** [comment]
One Question: There is couple different use cases here

1.  Team member has no current local env - import will create new `(Local Env)`
2. Team member has current local env -  then import variables to current Local Env **or** Replace all the values?

Can you let me know your feedback on use-case 2?

**Comment by joaonunogomes** [comment]
I would say that append the current local env with the one being imported, should be the best behavior. So use-case 2 would be the preferred one for our use case :)

**Comment by rangav** [comment]
Thanks @joaonunogomes for clarification

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to v2.5.1

Now You can Import both `Local or Global` Env.

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.1

Please let me know your feedback.

**Comment by rc23** [comment]
Hi,
Not sure if it was a UI bug but when importing the local env from a file I got a message saying that there was an error but then when I navigated to the local env the data was there.
Any clue what might have happened?
Thanks

**Comment by rangav** [comment]
Hi @rc23 can you share a sample Local env, I will verify it.

**Comment by joaonunogomes** [comment]
Hi :) I've tested this, and it seems the issue is the following:

When a shared project already contains a Local Env on `thunderEnvironment.json`, the import of the Local Env fails.
If you go to `thunderEnvironment.json` and delete the following entry:
```
  {
    "_id": "fe90b93d-b82d-4807-b141-0367d2ea45dc",
    "name": "(Local Env)",
    "default": false,
    "global": true,
    "local": true,
    "sortNum": -1,
    "created": "2023-02-27T12:29:42.311Z",
    "modified": "2023-02-27T12:29:42.311Z",
    "data": []
  }
```

After that, the import will work as expected

**Comment by rangav** [comment]
@joaonunogomes the import should work if there is already existing one.

might be bug, Will verify and confirm you later today

**Comment by rangav** [comment]
I just now tested, I dont get any error.

- Tested with no existing Local Env - working 
- Tested with existing Local Env - working

Can you share any sample local env where we can re-produce the error, will be useful for testing?
