### ISSUE TITLE
Thunder doesn't recognize script file exports

### ISSUE THREAD

**Issue by RafaelDiazAnguita** [rangav/thunder-client-support#1045]
**Describe the bug**
Hi, currently in my collection I have configured a script file where are coded the filters:

![image](https://user-images.githubusercontent.com/55484240/223726860-720a97a3-3985-4ca4-a10c-bd5278e37f2a.png)

The problem is when you change exports line. The thunder client UI only recognizes the filters if my exports look like this:

![image](https://user-images.githubusercontent.com/55484240/223727212-9ee0ffd4-e514-4855-9a3d-384f4dd4144a.png)

![image](https://user-images.githubusercontent.com/55484240/223727330-358f025a-5d5a-4b80-8cc0-b20d98691421.png)

But when i try to organize the exports like this, the thunder UI doesnt recognize well the exports:
![image](https://user-images.githubusercontent.com/55484240/223727513-9a04c10e-0c36-4484-a188-17d87c9888d1.png)

![image](https://user-images.githubusercontent.com/55484240/223727732-9d0e1be4-8abf-4581-b865-29570d23757b.png)

**Platform:** 
 - OS: Windows
 - vscode version: 1.76.0
 - extension version: v.2.5.0

**Comment by rangav** [comment]
Thanks @RafaelDiazAnguita  for reporting the bug, will look into it.

**Comment by rangav** [comment]
This bug is now fixed, please update to `v2.5.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.1

Please let me know your feedback.
