### ISSUE TITLE
client_secret is not sent to token endpoint

### ISSUE THREAD

**Issue by mzimdars-gms-online-de** [rangav/thunder-client-support#1046]
Hi,

when using OAuth 2 we connect to an OpenID compatible auth server.
We use authorization code that is sent to the token endpoint to retrieve the refresh and access token.

In this request, the client_id is sent, but not the client_secret. The OpenID spec states, that if a client secret was issues when registering the client it should be sent in requests. because of this, our authentication server rejects the token call.

Could you adopt the plugin to include the client_secret (if configured) in the token call as well?

thanks!
mz

**Comment by rangav** [comment]
Hi @mzimdars-gms-online-de I checked the logs, the client_secret is also sent for token request.

Please check your logs and let me know

<img width="1297" alt="Screenshot 2023-03-08 at 20 35 46" src="https://user-images.githubusercontent.com/8637550/223844141-cd38404b-d0d5-49ee-969c-81804627672d.png">

**Comment by rangav** [comment]
Are you sending data in header or body?

<img width="631" alt="Screenshot 2023-03-08 at 20 39 26" src="https://user-images.githubusercontent.com/8637550/223845683-3c2a9322-083f-4b7e-ae0b-250831fa424e.png">

**Comment by rangav** [comment]
You can verify the logs and let me know

<img width="1252" alt="Screenshot 2023-03-08 at 20 45 53" src="https://user-images.githubusercontent.com/8637550/223845962-d1081fe5-b1c3-4dab-adca-e6800db60542.png">

**Comment by mzimdars-gms-online-de** [comment]
Hi @rangav 

Thanks for your super fast response.

A classic case of user error; I though that the 'Send Auth' is related to how the token will be sent later in requests and not related to the client secret. When I set it to 'send in body' it works as expected.

Thank you very much!
mz

**Comment by rangav** [comment]
You are welcome :)
