### ISSUE TITLE
Collections created under windows not visible under wsl

### ISSUE THREAD

**Issue by csaket** [rangav/thunder-client-support#1047]
I was using Thunder Client in windows without wsl initially and had numerous collections.
I recently started using wsl and have enabled Thunder Client under it as well.
I do not see my collections when connected to wsl from vs code.

I am on Windows 11 using code insiders and on wsl2 I have ubuntu 22.04

Any suggestions?

**Comment by rangav** [comment]
Hi @csaket 

Try the solution in the below comment 
https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by csaket** [comment]
That works!
Thanks for a great extension!

**Comment by rangav** [comment]
You are welcome :)
