### ISSUE TITLE
paste doubled

### ISSUE THREAD

**Issue by koanvi** [rangav/thunder-client-support#1048]
**Describe the bug**
text doubled on paste to JSON content area

**To Reproduce**
paste to JSON content area

**Expected behavior**
paste text

**Platform:** 
 - OS: ubuntu 22.04.2
 - vscode version: 1.76.0
 - extension version: v2.5.0

**Your Team Size Using TC:**
-1

**Comment by rangav** [comment]
Thanks @koanvi reporting the issue, will look into it.

**Comment by MilesVII** [comment]
Occurs on Windows too, not only JSON content area, but any input as well.
It's hard to reproduce, but I'll let know if I manage to figure out the steps.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.15.0`

See all features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
