### ISSUE TITLE
ThunderClient keeps loading without showing the UI

### ISSUE THREAD

**Issue by TheShagwell** [rangav/thunder-client-support#1049]
![thunder client not working](https://user-images.githubusercontent.com/71180613/224089310-3d35bb85-313b-48e9-b89f-9363d9240656.png)

**** Am having issues loading thunderclient from my vscode directly. it keeps loading(on the sidebar) without showing the UI. My twin and I encountered same problem 
* Whenever I launch Vscode it keeps loading over and over again. I tried downgrade to pervious versions but still shows same issues. Now am using the latest version of it as of today 8/3/2023  2.5.1 and am still having same problems. Above its the attached screenshot of my problem
*  How can I fix these issues????

**Comment by TheShagwell** [comment]
Hi @rangav 
Its now working fine as expected.
God bless you, keep up the good work...

**Comment by rangav** [comment]
Thats good to know.

- The issue could be the data files might corrupted or other issue.
- `Save to workspace` setting will save requests data to your current workspace

You can clear old data in default location (make a copy first)

Data file location:
https://github.com/rangav/thunder-client-support#storage

after that you can uncheck Save to workspace setting 

Let me know if you have any further questions

**Comment by rangav** [comment]
Closing this issue, feel free to re-open if needed
