### ISSUE TITLE
use customLocation relative to project to workspaceFolder

### ISSUE THREAD

**Issue by ianmaciel** [rangav/thunder-client-support#105]
I'm not sure if this should be a feature request - it might be misuse.

Is is possible to specify relative path on `customLocation` property?

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have several projects (backend, frontend, app) on the same repository, and one of these projects will hold the API and the collection saved by Thunder Client.
The others projects should be able to access the same configuration, as they use the same API. 

I could solve this be always opening on the root folder and enable the `loadFromProject` option, but then all users will have to load the entire repository even if they will work on specifics projects.

If I was able to use relative paths on `customLocation`, I would be able to achieve that, by using relative path to `${workspaceFolder}`

**Describe alternatives you've considered**
Instead of expecting an absolute path on `customLocation`, also allow relative paths or the `${workspaceFolder}` variable.

**Implementation:**
I'm not familiar with vscode extensions.

**Comment by rangav** [comment]
Hi @ianmaciel thanks for suggestion, I will think of about what is best way to do solve this.

**Comment by rangav** [comment]
Hi @ianmaciel one question when you open child project in vscode, the workspace folder will be current open folder right? Not the parent.

is there a fixed config for workspace folder path.

another user suggested about $HOME And relative path.

**Comment by rangav** [comment]
Hi @ianmaciel 
This is implemented now in v1.3.0, see Team Features section in doc.
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
