### ISSUE TITLE
Location for custom scripts file for filters

### ISSUE THREAD

**Issue by csaket** [rangav/thunder-client-support#1050]
I want to use filters and custom scripts.
Can this file be saved to whichever default folder thunder client uses to save the requests/collections/etc?
How can I do this?

**Comment by rangav** [comment]
Hi @csaket 

- where are you saving requests data currently?
- You using the extension alone or part of a team?

**Comment by csaket** [comment]
Hi. I was initially using thunder client only on windows and had imported a postman collection.
I do not recall saving the requests in a custom location and can see they are present in the AppData folder similar to the one in your docs.
I am using this by myself only.
I am not familiar with the save to workspace setting you are referring to, but I don't want to mix my collections with my vscode workspaces.

**Comment by rangav** [comment]
Thanks for sharing info.

you can save js filters file in default location or any custom location you prefer.

default data location paths
https://github.com/rangav/thunder-client-support#storage

**Comment by csaket** [comment]
Thank you, will do that
