### ISSUE TITLE
I am unable to use thunderclient with an Microsoft Azure AD protected api

### ISSUE THREAD

**Issue by francotiveron** [rangav/thunder-client-support#1052]
I have an API that I test with thunder client. I have introduced authentication using Azure and followed
https://blog.jongallant.com/2021/04/azure-rest-apis-vscode-thunder-client/
On how to configure it. 
Unfortunately when I run a request I get the following error:

Bearer error="invalid_token", error_description="The audience 'https://management.azure.com' is invalid"

These are my OAuth settings:

![image](https://user-images.githubusercontent.com/8280970/224235732-4b7e8ee6-ee4f-43dd-9347-d9c59563615f.png)

**Comment by rangav** [comment]
Hi @francotiveron 

the error is saying the audience field value is invalid, please check documentation and try another value

**Comment by francotiveron** [comment]
@rangav What documentation? There is nothing about the audience in [the ](https://blog.jongallant.com/2021/04/azure-rest-apis-vscode-thunder-client/), and I did not set the audience anywhere.
As far as I know, the audience is put into the token by azure when the token is required by the client (in this case by thunderclient), so I guess something has to be changed in the request parameters or in the service principal created for thunderclient.

Is there an example/walkthrough for this case (calling a protected API) different from https://blog.jongallant.com/2021/04/azure-rest-apis-vscode-thunder-client/?

**Comment by francotiveron** [comment]
@rangav After further investigation, apparently the example in the post was explicitly for Azure REST API. 
To call my API it appears I need to specify in Scope as follows (myAPIUriID/.default)

![image](https://user-images.githubusercontent.com/8280970/224466638-b88041b8-e36c-45f0-aa85-234e8ead7256.png)

However what I get now is simply a different error
![image](https://user-images.githubusercontent.com/8280970/224466682-4cf6ded6-a1f2-4942-8219-f86718b7dd6e.png)

**Comment by rangav** [comment]
Hi @francotiveron I haven't used Azure api, so not familiar with it.

see if this link is useful
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

**Comment by rangav** [comment]
also verify the `token url` is correct or not for your use-case?

**Comment by francotiveron** [comment]
I was able to make it work finally, but it hasn't been easy or intuitive. A documentation walkthrough for such a common case would be very useful

**Comment by rangav** [comment]
Sure will include in documentation or feel free to submit PR

How you got it working or what was the issue?

**Comment by francotiveron** [comment]
The original article uses Azure Rest Api as server. In my case, I was using my own API, so I had to configure a permission in the Api itself (in azure), for the thunderclient service principal
