### ISSUE TITLE
Custom filters in Tests

### ISSUE THREAD

**Issue by mcgiany** [rangav/thunder-client-support#1053]
Hi, i read documentation for testing back and forth but i cannot figure out, how to use custom filter in Tests tab.
I wanted to set env variable after getting the response. But i need use custom script, not the build in filters.
it looks, the support for runnig custom filter in Tests is missing.

**Comment by mcgiany** [comment]
Yes, i read this. But its only shows usage in Headers and Pre-Run. But i want to use it in Tests. But i cant.

**Comment by rangav** [comment]
Usage is same as built in filters
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#filters-in-tests

**Comment by mcgiany** [comment]
Ok, my situation is, that i have request, that ends with redirect (HTTP 302). I dont want to be redirected so i turn off follow redirects in settings. And i want to read value from response headers. But if i use custom filter, i get error "Set Env Var with Json Query is supported for only Json or Xml response".

**Comment by mcgiany** [comment]
I finally get it works. Its little bit tricky, but result is OK. It would be better to get also option to just run custom code instead of fixed options. Thx for your help :)

**Comment by rangav** [comment]
> Set Env Var with Json Query is supported for only Json or Xml response

Can you let me know more about this error, is in when using custom script.

Screenshot below, how to use set env from headers
![image](https://user-images.githubusercontent.com/8637550/224481026-339335e7-71bd-49e5-b91d-ffd211547df2.png)

**Comment by jmtt89** [comment]
ohh very thanks by that screen, on [doc's](https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md) is wrong.

![IMAGE](https://user-images.githubusercontent.com/8637550/202415862-5e6d3712-a7c8-466b-8c7c-f91452ee4464.png)

when use json.headers.{atts} instead header.{atts} show the error "Set Env Var with Json Query is supported for only Json or Xml response"

**Comment by rangav** [comment]
Hi @jmtt89 did not understood the question?

**Comment by rangav** [comment]
Ok got it 👍
