### ISSUE TITLE
The Dark High Contrast Theme cannot distinguish check box activation well.

### ISSUE THREAD

**Issue by babpulss** [rangav/thunder-client-support#1054]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/47218965/224882373-98d8ee19-5982-433e-b104-f0adb35e77bb.png">

Thanks for your hard work.
int the Dark High Contrast Theme cannot distinguish check box activation well.

**Comment by rangav** [comment]
Thanks @babpulss for reporting the issue. Will fix it in the next update

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.5.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.3

Please let me know your feedback.
