### ISSUE TITLE
import cURL Text Failed

### ISSUE THREAD

**Issue by isecret** [rangav/thunder-client-support#1055]
**Describe the bug**
Hi, i used Postman code generator get a code, like this:

```
curl --location -g https://github.com
```

I tried to import the text into the Thunder Client, but it failed. And the request URL is converted to `true`.

**To Reproduce**

import this code into the Thunder Client:

```
curl --location -g https://github.com
```

The URL address will be converted to `true`

**Expected behavior**
The URL address should be converted `https://github.com`  and other parameters are converted correctly.

**Platform:** 
 - OS: macOS 13.2.1
 - vscode version:  1.76.1
 - extension version: 2.5.1

**Your Team Size Using TC:**
1

**Comment by isecret** [comment]
I found the problem, which is caused by the parameter `-g`. Why?

**Comment by rangav** [comment]
Thanks @isecret for reporting the issue, will look into it.

**Comment by rangav** [comment]
@isecret I used postman code generator there is no `-g`

```
curl --location 'https://httpbin.org/anything'
```

**Comment by rangav** [comment]
can you share postman screenshot?

**Comment by isecret** [comment]
> 

I used postman code generator to reproduce the problem.

This URL must contain a Query String in JSON format. like this:

```
https://github.com?foo=[{"foo":"bar"}]
```

And i got the the text from code generator.

```
curl --location -g 'https://github.com?foo=[{%22foo%22%3A%22bar%22}]'
```

I tried to import the text into the Thunder Client, The URL address is still `true`.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/15724152/225176944-f6d0ed61-b96c-4cd6-a5b1-558eb6ba890f.png">

**Comment by rangav** [comment]
got It, thanks for clarification

**Comment by rangav** [comment]
The bug is fixed now.

I am uploading the new VSIX file, if you like to test now and give feedback.

Will publish to VS Code marketplace next week

[vscode-thunder-client-2.5.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/10983924/vscode-thunder-client-2.5.2.vsix.zip)

**Comment by isecret** [comment]
@rangav That's great! thanks for respond.
