### ISSUE TITLE
Add a one-click "Authorize" option on the collection context menu

### ISSUE THREAD

**Issue by metamoof** [rangav/thunder-client-support#1057]
**Please describe feature/problem details and solution you'd like.**
I work on a number of APIs that are behind an OAuth2 gateway. I've configured the Auth on the collection, but I'd like to be able to right click on the collection name and have an "Authorize" option that will generate and save the session token.

**Describe alternatives you've considered**
The alternative is to right click, choose settings, choose the auth tab, scroll down, and click the generate button, and then finally close the tab. I'm hoping for a one-click version of that button.

**Your Team Size Using TC:**
3

**Comment by rangav** [comment]
Hi @metamoof 

We have auto-renew token after expiry feature? what Auth type are you using?

You dont need to manually renew token

**Comment by daniel-frank-bayer** [comment]
@rangav I believe he means that if you have auth settings for a folder, and an initial token has not yet been generated, then you need to go into the folder's settings and manually generate a token before it will automatically generate a new one when making a request. Otherwise the requests will fail because they don't have a token yet.

**Comment by metamoof** [comment]
@rangav .... wow, I hadn't realised that feature was added (about 5 months ago it seems). I've been entering the settings for my folders every time. I've just tested the auto-refresh feature, and it works great, even between restarts days apart from the last request.

So, yeah, no need to do anything more with it.

**Comment by rangav** [comment]
Thanks @metamoof for the confirmation 👍
