### ISSUE TITLE
save token

### ISSUE THREAD

**Issue by FanyuanCode** [rangav/thunder-client-support#1058]
Excuse me, I need to save the token to the environment after logging in, but I need to add 'Bearer' before the token, how should I do it?
For example, the returned token is 'abc', I need to add 'c' after saving it to the environment, so that it should be 'cabc' when I use it in other places

**Comment by rangav** [comment]
Hi @FanyuanCode 

You can save token from response to env variables from tests and then use it anywhere with variable name {{tokenName}}

https://github.com/rangav/thunder-client-support#setenv

You can use auth tab -> bearer tab

**Comment by FanyuanCode** [comment]
Thanks ! I will use it
