### ISSUE TITLE
Export all data

### ISSUE THREAD

**Issue by csaket** [rangav/thunder-client-support#1059]
Is it possible to export all data including every collection and environments etc?
I see a per collection export menu item but nothing that is for all.

**Comment by rangav** [comment]
Hi @csaket why you like to export all the data? Like to know your use-case.

**Comment by csaket** [comment]
I want to back up data completely and start from scratch by importing a Postman dump.
In case that fails, I would like to go back to the data I had working fine.

**Comment by rangav** [comment]
Thanks for feedback, will review it.

alternatively you back raw data files from storage folder 
https://github.com/rangav/thunder-client-support#storage

**Comment by rangav** [comment]
Safe option is save data to git
https://github.com/rangav/thunder-client-support#git-sync

**Comment by csaket** [comment]
Are these the files that I should copy?
![image](https://user-images.githubusercontent.com/1216526/225053777-d657f911-f8cd-4b4a-8599-988c32300eba.png)

**Comment by rangav** [comment]
4 files
- thunderActivity.json
- thunderCollection.json
- thunderEnvironment.json
- thunderclient.json

**Comment by csaket** [comment]
thanks

**Comment by yogithesymbian** [comment]
my case need going back to vscode stable instead of insider version have critical bug about copy paste just create a new line on vscode v1.79 .
