### ISSUE TITLE
A way to save the request without running

### ISSUE THREAD

**Issue by felipedelta0** [rangav/thunder-client-support#106]
**Is your feature request related to a problem? Please describe.**
Not exactly. When I'm creating a new request, if I switch to another without running it first, than it loses the request I made, sometimes when working on a really big request, it can be a problem.

**Describe the solution you'd like**
A "save" button, or something like this to save the request anytime I need, without the need to running it fist.

**Describe alternatives you've considered**
Maybe a button somewhere, maybe "CTRL + S" to save it.

**Comment by rangav** [comment]
Hi @felipedelta0 see this for solution https://github.com/rangav/thunder-client-support/issues/7#issuecomment-829806034

**Comment by rangav** [comment]
Hi, `Cmd/Ctrl + s` keyboard shortcut to save request without running is implemented in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
