### ISSUE TITLE
Cannot set a global variable type integer in the payload

### ISSUE THREAD

**Issue by mljavierarz** [rangav/thunder-client-support#1061]
**Describe the bug**

It isn't able to set the value of a variable if it is a number

**To Reproduce**

For example, in the Tests tab, if you can do something like:
`json.client_id` **setTo** `{{clientId, global}}`
if client_id is a numeric (for example integer, decimal, etc), the request where you try to put it will mark the field with and error, with this message :  `Bad string`  and the request will fail

**Expected behavior**

The value must be set, for example :

if we have :
"my_client": {{clientId, global}},
it should become ...
"my_client": 123456,

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Your Team Size Using TC:**

For now, just me

**Comment by rangav** [comment]
Hi @mljavierarz Thanks for reporting the bug. Will look into it.

Can you please screenshot of the response and Tests tab if possible

**Comment by rangav** [comment]
This bug is fixed I think.

I am closing this issue, feel free to re-open it if needed.
