### ISSUE TITLE
xml-query test feature

### ISSUE THREAD

**Issue by RafaelDiazAnguita** [rangav/thunder-client-support#1063]
**Please describe feature/problem details and solution you'd like.**
 
Hi, it would be awesome to add a test like json-query but for xml. For example to test values of xml received or set env variables.

**Comment by RafaelDiazAnguita** [comment]
Okey, but in my test case there is not working for some reason:

test: json['soap:Envelope']['soap:Body']['c:replyMessage']['c:payerAuthSetupReply']['c:referenceID'] setTo {{authSetupReferenceId}}

Response XML:

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">   
<soap:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
            <wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Timestamp-1713856512">
                <wsu:Created>2023-03-15T12:10:52.659Z</wsu:Created>
            </wsu:Timestamp>
        </wsse:Security>
</soap:Header>
<soap:Body>
        <c:replyMessage xmlns:c="urn:schemas-cybersource-com:transaction-data-1.207">
            <c:payerAuthSetupReply>
                <c:reasonCode>100</c:reasonCode>
                <c:referenceID>237e83f3-62af-4aac-bf46-a02433166518</c:referenceID>                           
            </c:payerAuthSetupReply>
        </c:replyMessage>
</soap:Body>
</soap:Envelope>
```

The variable authSetupReferenceId should be: 237e83f3-62af-4aac-bf46-a02433166518

But instead I'm getting:
![image](https://user-images.githubusercontent.com/55484240/225306128-d733d884-a45c-4e85-8fe2-d92721f94304.png)

**Comment by rangav** [comment]
I dont have access my laptop now, Will verify and get back to you later

**Comment by rangav** [comment]
Look like there is a bug, will fix and publish new update later today.

**Comment by rangav** [comment]
The bug is fixed now.

I am uploading the new VSIX file, if you like to test now and give feedback.

Will publish to VS Code marketplace next week

[vscode-thunder-client-2.5.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/10983924/vscode-thunder-client-2.5.2.vsix.zip)

**Comment by RafaelDiazAnguita** [comment]
I have tested it and works perfectly. Thank you

**Comment by rangav** [comment]
Thanks for confirmation
