### ISSUE TITLE
Tests not working (failing) if response in not displayable (bigger than 2MB)

### ISSUE THREAD

**Issue by guandalf** [rangav/thunder-client-support#1065]
**Describe the bug**
If the response body is bigger than the size thunder is able to display, the tests are all failing not being able to access to values.

**To Reproduce**
Create one succeeding test on a API response that is displayed in the response tab
Artificially grow the response size in a way that's not breaking the test itself
The test is going to fail

**Expected behavior**
Test sholud keep on passing

**Platform:** 
 - OS: macOS
 - vscode version: 1.76.2
 - extension version: 2.5.1

**Your Team Size Using TC:**
1 (me)

**Comment by rangav** [comment]
Thanks @guandalf for the feedback, will look into it.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.

**Comment by guandalf** [comment]
Works, thank you very much.
