### ISSUE TITLE
Test not working for string equals

### ISSUE THREAD

**Issue by CharlieSnowCode** [rangav/thunder-client-support#1068]
First of all, I have several instances of this case that do work.  The case where the string is 2 sentences is the one that does not.
I have a Response that returns a string for one attribute.  I use the 'equal' action and the test fails with this error:
Query: json.message equal to Successful request. See ResponseCode and Zip_Info for further details. => Actual: Successful request. See ResponseCode and Zip_Info for further details.
The only way to get the test to pass is to switch the action to 'contains' and use a part of the value.
Here is a snip of the Test:
![image](https://user-images.githubusercontent.com/67278867/225909213-1135a6d0-4fcc-47a6-a4e4-662e92e421d1.png)

**Platform:** 
 - OS: Windows
 - vscode version: 1.76.1
 - extension version: 2.5.1

**Your Team Size Using TC:**
3

**Comment by rangav** [comment]
Hi @CharlieSnowCode thanks for reporting the issue,

can you please a sample response text, will investigate the issue

**Comment by CharlieSnowCode** [comment]
{
  "zip_Info": {
    "zipGuid": "d8b2d638-8590-42bb-b874-c4af1322bfb5",
    "zipMediaCount_int": -1,
    "zipMediaCountAnnotated_int": -1,
    "zipProcessStartUTC_dte": "2023-03-16T20:59:58.53",
    "zipStatus": "LoadingMedia",
    "zipStatusUpdatedUTC_dte": "2023-03-16T20:59:58.647",
    "zipSasUrl_str": "",
    "zipSasExpireUTC_dte": "1900-01-01T00:00:00",
    "zipFileSizeKb": -1,
    "zipErrorMsg_str": null,
    "zipStatusUpdateLocation": "MediaDatabaseOnly"
  },
  "requestGuid": "fd9cb9c7-61eb-4aab-8ba5-8c222e56d2e5",
  "responseCode": "Success",
  "message": "Successful request.  See ResponseCode and Zip_Info for further details.",
  "message_Detailed": null
}

**Comment by rangav** [comment]
I have tested now, its working for me. Am I missing anyting?

<img width="1786" alt="Screenshot 2023-03-20 at 10 30 58" src="https://user-images.githubusercontent.com/8637550/226315526-acca94ea-d531-4c57-99b7-0882f8e0b546.png">

**Comment by CharlieSnowCode** [comment]
It's still a bug for our particular case.  But if I break it into 2 tests, they both pass.
json.message **contains** Successful request.
json.message **contains** See ResponseCode and Zip_Info for further details.
We're satisfied using this work-around.  Thanks for looking into it.

**Comment by rangav** [comment]
Good to know the workaround works for you.

Closing this issue.

let me know if you have any further questions
