### ISSUE TITLE
CLI: New argument for "notify on fail"

### ISSUE THREAD

**Issue by CharlieSnowCode** [rangav/thunder-client-support#1069]
We have an Azure pipeline that utilizes the TC CLI to execute over 30 Requests in a Collection.  If we use the argument
**--stop-on-fail**  and there is a failure, the subsequent Requests are skipped.  But if we don't include this argument, the pipeline reports that the Task succeeded, even if there was a failed test.

Could you add an argument like
**--notify-on-fail**  that gives a failure code but still continues to execute the whole Collection?
Many thanks!

**Your Team Size Using TC:**
3

**Comment by rangav** [comment]
Thanks @CharlieSnowCode for the feedback, will include in the next update. ETA this week.

**Comment by CharlieSnowCode** [comment]
Works like a charm, thank you so much.

**Comment by rangav** [comment]
You are welcome 🙂
