### ISSUE TITLE
"Load From Project"  secret environment variables

### ISSUE THREAD

**Issue by timker** [rangav/thunder-client-support#107]
"Load From Project" should not always save the environment variables values in thunderEnviroment.db

I want to check in my thunder-tests folder.
However some environment variables may be private, e.g username/password 

Make it like postmans "Initial Value" , "Current Value"

Where CurrentValue is only saved in some user space

This would make it harder for accidental commits of private data.

**Comment by rangav** [comment]
Hi @timker, thanks for the suggestion, 

the files are complete json db file, they are not exported files where you can ignore values.

For now you can ignore the complete file using gitignore from checkin.

Some users suggested about connecting environment on thunder to .env file in your workspace/pc.

Similar issues https://github.com/rangav/thunder-client-support/issues/79 https://github.com/rangav/thunder-client-support/issues/74

**Comment by timker** [comment]
yeah sorry, 100% a duplicate issue.

**Comment by rangav** [comment]
you can add your suggestions there, i am closing this
