### ISSUE TITLE
Log feature not working when running "col", "fol" or "reqlist" requests with TC CLI 

### ISSUE THREAD

**Issue by wavveen** [rangav/thunder-client-support#1070]
**Describe the bug**
The logging (--log) feature is not working when using the TC CLI in combination with the --col, --fol or --reqlist arguments. To me it seems it only works when using the --req argument. But when using the -req argument the reporting feature is not working.

**To Reproduce**
Just execute some request with TC like:
tc --fol "Add Administration (1)" --report json,html --log 1,2,7

**Expected behavior**
We would really like to have the combination of output logs and reporting, as we would also want to see the exact request we've send during a test for troubleshooting purposes.

**Comment by rangav** [comment]
Thanks @wavveen for the feedback, will add to roadmap.

Current `--log` argument only works with running single request using `tc 'requestName'`

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.9.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please let me know your feedback.
