### ISSUE TITLE
Cookies sent with request when they shouldn't

### ISSUE THREAD

**Issue by tscelsi** [rangav/thunder-client-support#1072]
**Describe the bug**
I am making a request using ThunderClient and need to pass some authentication cookie through with the request. I do this by adding the 'Cookie' header and attaching the required value to it like: 
![image](https://user-images.githubusercontent.com/19143370/226595958-20778655-f75d-44d9-97f2-8c8f8e0aa527.png)

This works great and my request returns the protected information. However then I remove the cookie header and my protected route information is still returned!! Somewhere behind the scenes it looks like the Cookie is persisted and attached to any request to that domain regardless of whether the Cookie header is present or not.

This is even the case when i start a 'New Request' and try the same request with no Cookie header. It _still_ implicitly attaches it somewhere because the protected route returns the protected data.

**To Reproduce**

I am attaching a minimum reproducible example using fastapi:

```from fastapi import FastAPI, Cookie
from typing import Annotated, Union

app = FastAPI()


@app.get("/")
def get(auth: Annotated[Union[str, None], Cookie()] = None):
    if auth is None:
        return {"error": "this cannot be!"}
    return {"success": "protected information"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app)
```

A simple endpoint that takes in a cookie and returns an error if not authenticated and the protected info if it finds a cookie with an auth property.

1. Call the endpoint with no Cookie header after clearing cookies -> should see error unathed
![image](https://user-images.githubusercontent.com/19143370/226598215-5c62dcde-d35f-43d9-ba52-9fa9761f06fc.png)
2. Add Cookie header with auth
![image](https://user-images.githubusercontent.com/19143370/226598370-fa8a6286-e11c-48c2-83bf-70864490675d.png)
3. Remove Cookie header and call again. **Note here we see the protected info again with no Cookie header i.e. no auth**
![image](https://user-images.githubusercontent.com/19143370/226598422-df850845-9485-4c67-b15c-8db2ecc9b513.png)

**Expected behavior**
**If there is no Cookie header, don't send cookies!**

**Platform:** 
 - OS: Windows (WSL2)
 - vscode version: 1.76.2
 - extension version: v2.5.1

**Your Team Size Using TC:**
5

**Comment by rangav** [comment]
Hi @tscelsi when you can create a cookie, it will be stored in cookie store and passed on to other requests matching the domain name.

you can clear existing cookie in response `Cookie Tab`

This is the normal expected behaviour 

let me know if you have any additional questions

**Comment by ttktatakai** [comment]
> Hi @tscelsi when you can create a cookie, it will be stored in cookie store and passed on to other requests matching the domain name.
> 
> you can clear existing cookies in response `Cookie Tab`
> 
> This is the normal expected behaviour
> 
> let me know if you have any additional questions

Is there a way to set to not store the cookie by default? @rangav

**Comment by rangav** [comment]
You can use the below setting, to clear cookies before sending request.

<img width="762" alt="Screenshot 2023-12-19 at 17 21 15" src="https://github.com/rangav/thunder-client-support/assets/8637550/0855e86e-d2b3-475a-b24d-cdd573d3f8dd">
