### ISSUE TITLE
how to use oauth2 beaer accesss token

### ISSUE THREAD

**Issue by copdips** [rangav/thunder-client-support#1074]
**Your Team Size Using TC:**

1

**Question:**

Hello,

I'm using Oauth flow, I configured the OAuth2 in thunder:
![image](https://user-images.githubusercontent.com/13083856/227158933-71f089b6-9a17-442d-9bf1-b5f245d25b48.png)

and click on the Generate Token, I got a successful response:
![image](https://user-images.githubusercontent.com/13083856/227158693-7702443b-dae4-4a7c-86ca-1b132af4781a.png)

When I tried the api call by clicking on the Send button in Thunder, I got a 401 Unauthorized, and I can find that in the headers, there's no Authorization Bearer inside.

![image](https://user-images.githubusercontent.com/13083856/227159855-1bc2250f-cb2d-46a6-9406-4b22bc79f8c3.png)

Could you please provide an example how to add this header in the request ?

**Comment by rangav** [comment]
Hi @copdips Is the access code generated for you?

I tested its working for me

<img width="1278" alt="Screenshot 2023-03-23 at 09 51 47" src="https://user-images.githubusercontent.com/8637550/227166520-d0a2f1eb-03a0-4a8b-aa01-ef9b82c25b32.png">

**Comment by rangav** [comment]
can you share oAuth2 tab screenshot with access token field value masked?

**Comment by copdips** [comment]
OK, I found in your screenhsot, the access token is auto filled, but not for the mine, although I got success response from the generate token button.

![image](https://user-images.githubusercontent.com/13083856/227171055-ddfdb6b4-6850-4503-8e49-3319a009d2cd.png)

And from the vscode output tab, I can see that thunder client got the auth code, but didn't request the access token
![image](https://user-images.githubusercontent.com/13083856/227171730-99792cf4-6abf-41be-a36d-f777a7975e63.png)

**Comment by rangav** [comment]
If access code is not generated then try both these options and see which one generates token.

<img width="763" alt="Screenshot 2023-03-23 at 10 21 41" src="https://user-images.githubusercontent.com/8637550/227174361-a70d392f-ecf4-44b8-a4ee-f2ab02f49f2e.png">

**Comment by copdips** [comment]
none of them works...

**Comment by rangav** [comment]
Are you seeing any errors in the logs? when the 2nd request is sent for access token?

**Comment by copdips** [comment]
as shown in my previous screenhot, nothing after the second request to oauth2/v2.0/token to get the access token, maybe this is why the access token field is empty for me

**Comment by copdips** [comment]
![image](https://user-images.githubusercontent.com/13083856/227183500-097cb452-df45-4766-bc88-5cc88693317c.png)

![image](https://user-images.githubusercontent.com/13083856/227183410-5f65b94f-448e-49ff-97d0-b9a77af06a65.png)

**Comment by rangav** [comment]
Why are you using Auth Code with PKCE? is there any documentation link?

See this link
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by rangav** [comment]
Sure will output the errors

**Comment by copdips** [comment]
yeah, it's better
![image](https://user-images.githubusercontent.com/13083856/227248937-fa9a667c-045b-4888-9192-1488c3c08a85.png)

**Comment by copdips** [comment]
output windows remains the same as my previous screenshot

**Comment by copdips** [comment]
I got it working, in azure, previously I added the thunderclient callback url in the `SPA` part, now putting the callback in `Mobile and desktop applicaitons` fixed the issue.
![image](https://user-images.githubusercontent.com/13083856/227504080-a7ae0832-cd30-4a77-84b5-ac0593df5ff8.png)

It would be really nice if we can see detail errors in output, I resolved the issue by setting up the same thing in postman, and got the error message from there.

**Comment by rangav** [comment]
Good you got it working finally, will update the documentation

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.

**Comment by rangav** [comment]
Thanks @copdips for the confirmation
