### ISSUE TITLE
Test json[0].someProperty equals undefined

### ISSUE THREAD

**Issue by alejandrofdez-us** [rangav/thunder-client-support#1077]
**Describe the bug**
Testing that a json query over an array element property is not present
**To Reproduce**
For instance, make a GET request to: https://jsonplaceholder.typicode.com/users
Include the following test:
Json query:
json[0].password EQUAL undefined
(you want to check that password is not returned in the public api, even if it is encrypted)

I also tried doing EQUAL null, same behaviour.

The test FAILS
<img width="761" alt="Captura de pantalla 2023-03-23 a las 18 58 10" src="https://user-images.githubusercontent.com/19324988/227302469-b944d210-9e13-4547-aa87-697ce7c69ccd.png">

**Expected behavior**
Expect to success the test if the password property does not exists.

**Platform:** 
 - OS: Macos
 - vscode version: 1.76.2
 - extension version: v2.5.1

**Your Team Size Using TC:**
300 students every year + 7 lecturers

**Comment by rangav** [comment]
Thanks @alejandrofdez-us for reporting the bug, Will verify and fix it.

**Comment by rangav** [comment]
I have fixed the bug, please find the updated `VSIX` file for testing. Will publish to marketplace next week.

[vscode-thunder-client-2.5.4.vsix.zip](https://github.com/rangav/thunder-client-support/files/11069477/vscode-thunder-client-2.5.4.vsix.zip)

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.
