### ISSUE TITLE
Body is not included in the request

### ISSUE THREAD

**Issue by juanidiaz** [rangav/thunder-client-support#108]
**Describe the bug**
First time using the extension. I tried to make some calls and everything worked well testing some GET endpoints until I had to include some information in the **body**. I am not able to send information in the body of the request no matter the format. I am able to send as a parameter but not as body.

I am testing the same RESTfull call using Postman and I can see the content of the body.

I've already tried:
- restarting vs code
- restarting computer
- uninstall/reinstall extension

**To Reproduce**
This is the way to reproduce in my computer, note that the URL I use just logs into the console the value of "req.body"
1. Make a new request
2. Leave method as GET
3. Enter the URL
4. Open the "Body" menu and select Json
5. Enter any values, for example:
```
{
  "test": "Value"
}
```
6. Send request

**Expected behavior**
The console should show the `{ "test": "Value" }`.

**Platform:** 
 - OS: BigSur 11.3 (20E232)
 - MacBook Pro (16-inch, 2019)
 - VS Code: Version: 1.55.2

**Comment by rangav** [comment]
Hi @juanidiaz please use POST method to send body, GET is only for using url query parameters.

why you want to use GET to send body, any reason?

**Comment by m9aertner** [comment]
I second this request. It is not optimal to disallow body content with GET. A developer-level tool should not be unnecessarily opinionated about what services the user uses, or how. It is a misconception that HTTP GET requests cannot have a body.

As an example, [Elasticsearch](https://www.elastic.co/elasticsearch/) regularly uses GET requests **with a body**: the JSON query is sent in the body.

This is in fully accordance with with HTTP semantics: it is a _query_ operation, fully read-only, that does not modify the underlying resource. Please also consider when the body content length (query JSON including the query conditions, selections, processing script sources, script parameters, ...) exceeds the (allowed/practical) length of URL parameters. In the case of Elasticsearch, it is not even possible to supply the query (JSON) in an URL parameter, as there is no need for that they have not provided one.

Can POST be used in this specific case? Technically yes, as Elasticsearch accepts search requests in POST queries in addition to GET queries. But this can easily break as soon as security measures come into play: It is a widely accepted best practice to limit permissions to read-only clients by way of network-level proxies that only allow GET to pass through, but block POST, DELETE and/or other HTTP verbs (cf. AWS security).

So, please consider removing that limitation.

**Comment by rangav** [comment]
ok got it @m9aertner, will enable in next update

**Comment by rangav** [comment]
This feature is released in v1.2.1 for details https://github.com/rangav/thunder-client-support/releases/tag/1.2.1
