### ISSUE TITLE
add generate oauth token in the context menu

### ISSUE THREAD

**Issue by copdips** [rangav/thunder-client-support#1081]
**Please describe feature/problem details and solution you'd like.**

I set the Oauth settings at collection or folder level, and all the requests inheirt the token generated from there.
Before using the token, I have to open the settings menu of collection or folder, and scroll down to the bottom of the Oauth settings page, and click on the generate token button.

For a better user experience, Is it possible to add the `generate token`  to the context menu of collection and folder directly ?

![image](https://user-images.githubusercontent.com/13083856/227724245-32efa8cc-eced-4c45-90f7-735452c0f717.png)

**Describe alternatives you've considered**

**Your Team Size Using TC:**

**Comment by rangav** [comment]
Hi @copdips once you generate the token, the extension will auto-renew the token and you dont have to manually generate token.

So there is no need to add option to context menu.

**Comment by copdips** [comment]
hello @rangav , even for the first token generation, it would be nice if we can do it quickly with a context menu, support we have multiple collections, it is a time consuming operation.

**Comment by rangav** [comment]
How can you generate token without filling the values?

**Comment by copdips** [comment]
i fill the values only for the first time.
- day 1, i want to test the API, I should go to `settings`->`auth` tab, scroll down to botton, click on the `generate token` button
- day 2, i want to retest the API, I should repeat the same steps as day 1
- day n., same thing.
Tthat's why I said it's time consuming, if we could have directly the `generate token` in the context menu as shown below, it would be great:
![image](https://user-images.githubusercontent.com/13083856/227742593-054acf56-8057-4ed1-aa4b-d151a5efe7c2.png)

**Comment by rangav** [comment]
You don't need to repeat what you did on day 1, the token is auto renewed after expiry. So there is not dedicated menu item for token.

**Comment by copdips** [comment]
not the case for me, but maybe the refresh token is not sent by azure aad, I remember that this could be an optional option, which is not default. and the extension output doesn't say if it received the refresh token or not
![image](https://user-images.githubusercontent.com/13083856/227746231-7d52ffd4-5177-474c-bc25-0672440df730.png)

**Comment by rangav** [comment]
Please check logs in output window

**Comment by copdips** [comment]
I'll check it tomorrow as my token is just renewed manually by me, cannot test the refresh scenario for now.

**Comment by copdips** [comment]
here's the output:

```
---------------- Running Request: ----------------
Environment Used: xxx (Active)

OAuth2 Refresh Token Request: https://login.microsoftonline.com/933c9cbe-35d3-4416-abbd-ddd1bca5879c/oauth2/v2.0/token
Request Method: POST
Request Headers:
{
  "Content-Type": "application/x-www-form-urlencoded"
}
Request Body:
grant_type=refresh_token&refresh_token=undefined&scope=api%3A%2F%2Fxxx%2Ftest&client_id=4xxx&client_secret=

ERROR Refresh Token - Response code 400 (Bad Request) 
Request Url: https://xxx.azurewebsites.net/
Method: GET
Request Headers:
{
  "Accept": "*/*",
  "User-Agent": "Thunder Client (https://www.thunderclient.com)",
  "Authorization": "Bearer redacted."
}
```
