### ISSUE TITLE
display linked env name beside collection name and add in context menu the options to chose linked env

### ISSUE THREAD

**Issue by copdips** [rangav/thunder-client-support#1082]
**Please describe feature/problem details and solution you'd like.**
I have a local env and a prod env, one the few difference between is the base URL, so I should switch the env to test in both cases.
currently, the env swithing must open the settings, go to env tab, and switch.
I see two pain points:
1. time consuming operation
2. cannot visually figure out directly which env I'm in.

I suggest to:
1. add in collection's context menu the option to switch env
2. display linked env name besides the collection name (the yellow block) => this one is very important to prevent from doing some test operations in a prod env.

![image](https://user-images.githubusercontent.com/13083856/227727342-5cf7f9c2-c4d1-4321-a121-c60d5f9d39e7.png)

**Describe alternatives you've considered**

**Your Team Size Using TC:**

**Comment by rangav** [comment]
@copdips you can change env very easily see below screenshot

<img width="1354" alt="Screenshot 2023-03-25 at 15 57 43" src="https://user-images.githubusercontent.com/8637550/227728273-352da77b-7e46-46a5-8a71-bd14c3a8d516.png">

**Comment by copdips** [comment]
thx for the tips, I just tested it, but it seems that it doesn't work.
already in the status bar, it says i'm in env B, but in fact, i'm still in env A, so as in the settings->environment tab.

the only working method is to change in the settings->environment.

I'm using the lastest version of VSCode on windows 10 by remote WSL

**Comment by rangav** [comment]
Wsl is different issue

Try the solution in the below comment 
https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by copdips** [comment]
after setting the extension as `ui` in `settings.json`,  I need to restart vscode and recreate a test collection. because all the config are lost, but the test still fails.
