### ISSUE TITLE
Add possibility to configure "Origin" header  for OAuth2 token generator

### ISSUE THREAD

**Issue by diasCr** [rangav/thunder-client-support#1084]
**Please describe feature/problem details and solution you'd like.**
If you try to get a token from Azure AD using the extension and grant type "Authorization Code with PKCE" you end up with a 400 Bad Request because of a cross site issue. See exception description:
error_description=AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.
The solution is to add the header and it works.

**Describe alternatives you've considered**
It must be possible to configure this header if necessary (possibly also other headers). 

**Your Team Size Using TC:**
I'm trying to introduce the extension because it is well integrated into VSCode. I'm architect of a value stream with 4 teams. More than 30 developers.

**Comment by rangav** [comment]
Thanks @diasCr for the feedback, Will look into it.

**Comment by rangav** [comment]
Did you add callback url to your authorised list?

https://www.thunderclient.com/oauth/callback

**Comment by copdips** [comment]
the thunder client redirect url should not be added into SPA, but instead into mobile and desktop application

**Comment by diasCr** [comment]
Hi @rangav ... yes a did... the redirect url is configured in my App registration... if I call the /token url direct with Origin header then it works... the extension for "Authorization Code wiht PKCE" is calling /token without this header.

**Comment by rangav** [comment]
@diasCr will add Origin field in the next update.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.

**Comment by copdips** [comment]
@diasCr 
could you please share what you'll put in the `Origin` header ?

**Comment by rangav** [comment]
@copdips I think callback url

https://www.thunderclient.com/oauth/callback

**Comment by copdips** [comment]
@rangav 
indeed, by adding the callback to SPA , and set the callback in the Origin header works too. thx for the quick fix!

**Comment by diasCr** [comment]
@rangav  
thx for the quick fix... I appreciate it. Now it is working as expected.

**Comment by rangav** [comment]
Thanks @diasCr for confirmation
