### ISSUE TITLE
Run Collections Asynchronously

### ISSUE THREAD

**Issue by zlajson** [rangav/thunder-client-support#1088]
**Please describe feature/problem details and solution you'd like.**
Right now clicking on "Collection Name -> Run All" will run all requests in a synchronous way (one request after another), which doesn't fit well neither for huge collections nor for requests which are slow by design and nature and take 10+ seconds.

It would be extremely benefitial to be able to run all collection requests asynchronously.

**Describe alternatives you've considered**
Tried to leverage CLI but the result was the same.

**Your Team Size Using TC:**
We are a team of 5 devs.

**Comment by rangav** [comment]
Thanks @zlajson for the feedback, will add to roadmap.

**Comment by zlajson** [comment]
Thanks @rangav, looking forward to it.

Keep up the good work!

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to v2.15.0

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
