### ISSUE TITLE
Set environment variable only when this variable is not empty

### ISSUE THREAD

**Issue by ibrahim-brumate** [rangav/thunder-client-support#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
On postman, when we made a script test, I can make one if and set a environment
data only if the data is not empty. I want one option to set environment data only when
this data is not empty

**Describe alternatives you've considered**
I tryed to put the setenvironment after other test, thinking, if the first test failed the data was not will be set, but
the data was seted

**Comment by rangav** [comment]
Hi @ibrahim-brumate i will provide an option in settings tab for this

**Comment by rangav** [comment]
Hi @ibrahim-brumate i was thinking may be special syntax in value field would work, like OR symbol before variable name

normal = **{{variable}}**
set only if null = **||{{variable}}**

Let me know your feedback.

**Comment by ibrahim-brumate** [comment]
Hi @rangav. First off, thanks a lot for the quick response.
I guess the ifNull idea works when we have a static data.
In this specifc case, I always want to renew the environment variable, of course, if the json.value is not empty.
In cases when the endpoint call fail, we will not have json.value because it's undefined, empty or something like that.
And right now, when it happens, the data was seted empty because json.value was empty too.

I guess one action named notNullSetTo can be one idea, to set the value only if json.value was not empty.

I don't know if my idea it's clear enough, but please let me know if doesn't.

I don't know too how many effort you need to do these things, but I guess one good approach is if you have one way to allow us make a script if we need.

Perhaps for a first view, looks like against the principle of simplicity. But when we talk about have that power inside vscode, I guess can be a great advantage.

Something like "Scriptless" to make your life easy but, if you are a advanced user, you can use on scrap option to make your own scripts.

This way can avoid you need to implement a new action everytime somebody needs to make one thing different.

Of course this is up to you, is just a suggestion.

Thanks a lot again for the response. This is a great job. Congrats.

**Comment by rangav** [comment]
Hi @ibrahim-brumate Scriptless testing is the differentiating feature from other api clients, initial focus will be try to improve it cover most common use cases, i know it wont cover everything but atleast around 90%. If we start doing the same as other tools then people think we are building clone, hope you understand.

One more thing I find myself postman scripting very complicated unless you learn and use it regularly.

May be in distant future we might enable scripting for advanced use cases.

In your case I can provide function wrappers also for example:

SetIfNull({{variable}}) - set if variable value is null
SetIfValue({{variable}}) - set if json has value only
SetIfValueAndNull({{variable}}) - set if json has value and variable null

Let me know your feedback.

**Comment by ibrahim-brumate** [comment]
@rangav for sure I completely understand. Like I said before, was just a suggestion.

About these 3 options, looks great for me. Will help a lot.

Thanks you so much 👍

**Comment by rangav** [comment]
Thanks @ibrahim-brumate for confirmation, will notify when its done.

**Comment by rangav** [comment]
Hi @ibrahim-brumate 
Small update: Now i have changed the default behaviour to set env variable value only when the json query has a value.

**Comment by ibrahim-brumate** [comment]
Nice @rangav, this change help me a lot. Thank you so much. It's worked pretty.
Do you still continue with the plan to have the other options? If not, you can close the issue.

**Comment by rangav** [comment]
Thanks @ibrahim-brumate for Confirmation.
Dont think we need the other options now, i will close the issue. if there is any other specific use-cases arise in future we can discuss then.

**Comment by rangav** [comment]
We add filters feature in v2.0.0

Now you can use `setIfValue` filter for this usecase

see docs here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#setIfValue
