### ISSUE TITLE
Context menu not working

### ISSUE THREAD

**Issue by Fortinbra** [rangav/thunder-client-support#1092]
**Describe the bug**
The context menu on Right click, does not copy, cut, or paste

**To Reproduce**
Highlight text -> right click -> go to cut -> nothing
put cursor on input box -> right click -> go to paste -> nothing

**Expected behavior**
right click -> paste -> pastes items from clipboard
right click->copy -> copies items to clipboard
right click->cut -> removes items from current selection, adds them to clipboard.

**Platform:** 
 - OS: Windows 10 Enterprise
 - vscode version: 1.77.0
 - extension version: 2.5.3

**Your Team Size Using TC:**
9 - With more teams in my org wanting to join in.

**Comment by Fortinbra** [comment]
Additional Notes:
I can reproduce this on my personal computer, using Windows 10 Professional, and the same VS Code and TC versions.

**Comment by rangav** [comment]
Hi @Fortinbra 

The right click context menu for copy, paste & paste is provided by vscode editor. Please report to vscode team.

The extension has no control over that menu.

**Comment by Fortinbra** [comment]
I only reported here, because it only happens in the extension, all other extensions and the editor are functional in this regard.

**Comment by rangav** [comment]
The other extensions may not use webviews. 

Can you please try in the extensions view and try cut text and paste in search box in the left
<img width="1049" alt="Screenshot 2023-03-30 at 21 10 18" src="https://user-images.githubusercontent.com/8637550/228953109-97a75426-7ee8-417c-9032-9543089b09d5.png">

**Comment by rangav** [comment]
No problem, please report to vscode team.
