### ISSUE TITLE
The `excludeProxyHostList` doesn't work

### ISSUE THREAD

**Issue by klesh** [rangav/thunder-client-support#1094]
**Describe the bug**
My target api server can only be accessed via VPN without going through the PROXY

If I comment out my proxy settings

![image](https://user-images.githubusercontent.com/61080/229086651-eebba155-fc92-4507-a9fa-2791bd3bed31.png)

ThunderClient can access the server correctly
![image](https://user-images.githubusercontent.com/61080/229086903-67b86c7f-5d44-4bf0-8e0d-a6e30eecaef7.png)

However, when I uncomment those two line,

![image](https://user-images.githubusercontent.com/61080/229087116-c273b909-b06b-4e1b-94f2-8d29e9cfb4c2.png)

It would fail
![image](https://user-images.githubusercontent.com/61080/229088788-a27a7e4e-636c-452e-8830-347cf100c1ed.png)

**To Reproduce**
As described above

**Expected behavior**
Domains listed in `excludeProxyHostList` should not be proxied

**Platform:** 
 - OS: Windows 11 22H2
 - vscode version: 1.77.0
 - extension version: 2.5.3

**Comment by rangav** [comment]
Thanks @klesh for reporting the big, will look into it.

**Comment by rangav** [comment]
Vscode has changed the proxy settings, see new docs
https://code.visualstudio.com/docs/setup/network#_proxy-server-support
