### ISSUE TITLE
Stop on fail for pre-requests

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#1095]
**Describe the bug**

Stop on fail does not stop a collection if a pre-request fails

![image](https://user-images.githubusercontent.com/29847057/229128455-c3a275f5-3686-45ec-8eb8-a29ccee02e81.png)

**To Reproduce**

Add a request that will fail as a pre-run of a collection. Run collection

**Expected behavior**

I expected stop on fail to also apply to pre-requests. this way, i can make a request to `/health` or `/version` to make sure the server is up

**Platform:** 
 - OS: Manjaro Linux
 - vscode version: 1.76.2
 - extension version: v2.5.3

**Your Team Size Using TC:**

1

**Comment by rangav** [comment]
Thanks @andresatierf for the feedback, Will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.6.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.0

Please let me know your feedback.
