### ISSUE TITLE
Add streaming of response

### ISSUE THREAD

**Issue by Smyja** [rangav/thunder-client-support#1096]
I'd like to see the output as its coming.

**Comment by rangav** [comment]
Thanks @Smyja for the feedback. 

Duplicate of #3

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.19.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test it and let me know your feedback
