### ISSUE TITLE
Unable to save variables to a Local Environment using `setTo`

### ISSUE THREAD

**Issue by miriti** [rangav/thunder-client-support#1099]
**Your Team Size Using TC:** 5

**Question:**
It seems that I can't use a Local Environment to store variable using `setTo`?

- I've created a Local Environment in the Env tab and assigned a `.env` file to it. `.env` file contains an email and password used for authorization.
![image](https://user-images.githubusercontent.com/1500502/229632973-1e9a8ea9-0cce-42c8-818d-03c7c22a3b82.png)
![image](https://user-images.githubusercontent.com/1500502/229633024-88bebdfb-6504-464f-9032-2fe89622e255.png)

- I'm making a sign-in request to an API using variables from the `.env` file and I have tests that should save `access_token` and `refresh_token` from the JSON response to an environment.
![image](https://user-images.githubusercontent.com/1500502/229633738-6d7bc9c7-8046-4f73-8fa1-7d46ab8ed81f.png)
![image](https://user-images.githubusercontent.com/1500502/229632732-b6a44f9e-8962-42e2-9605-b7d216f41f9d.png)
- Request is successful meaning that the variables from the `.env` file are used, however I see two failed tests stating that I need to create an Environment first:
![image](https://user-images.githubusercontent.com/1500502/229632603-6fd9f0a7-36b1-49ee-a81e-574ef5cd834f.png)
- If I create a regular environment then the variables are stored there even if I didn't assign it to the collection. But I don't want this as these values are also being stored in a json file which is under version control

Is it possible to use local environment to store variables using `setTo`? It seems that it's impossible to assign a local/global environment to a collection and I don't see any other was to "tell" the collection to use the local one and it doesn't store the variable there by default.

I'm using version v2.6.0

**Comment by rangav** [comment]
Hi @miriti 

The variable format is wrong in `Tests` tab. the correct value is `{{access_token, local}}`

See docs
https://github.com/rangav/thunder-client-support#set-env-with-scope

**Comment by miriti** [comment]
Hi @rangav 
Thank you for such a quick response!
Indeed I somehow missed this part in the doc. It did the trick. Thank you!
