### ISSUE TITLE
Import request as cURL

### ISSUE THREAD

**Issue by Aurelioolive** [rangav/thunder-client-support#11]
Hi. morning. A feature that I use a lot on Postman is "import as cURL". So I can copy a request made in Chrome and replicate it for analysis in Postman. I think it would be interesting to have the same functionality.

A solution that import the cURL request and replicates as a new request.

**Implementation:**
I can help to implements a translator, but I dont't have a code example now.

**Comment by rangav** [comment]
Hi @Aurelioolive should it work when a user paste curl request into the url input field? or it should import curl requests from a file?

If you can work on translator then i will integrate faster into main project, 
you can create simple html file with input field and use javascript for parsing

**Comment by Aurelioolive** [comment]
I think that is better if have a button "import" and the user can paste the content. Because on the future you can put others features on this section.

I will do later (after work) a translator for get cURL request and parse to Javascript objects.

### cURL example:
`curl 'http://localhost:3000/api/v1/auth/login' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json' \
  -H 'DNT: 1' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Accept-Language: en-US,en;q=0.9,pt;q=0.8' \
  --data-raw '{"userLogin":"test@test.com.br","userPassword":"test123"}' \
  --compressed \
  --insecure`

**Comment by Aurelioolive** [comment]
I think that maybe this package helps: https://www.npmjs.com/package/parse-curl-js

**Comment by rangav** [comment]
We already have import option in the collections tab, but it will open explorer for file selection.

**Comment by Aurelioolive** [comment]
Hi @rangav , I was making searchings to start the code but I found this repository: https://github.com/kigiri/fetch
Is basically what we're talking about,

**Comment by jsjain** [comment]
This is very important and most used feature in my workflow, I mostly use import via curl when debugging the APIs locally

**Comment by HernanGH** [comment]
Yes, that is a important feature!

**Comment by rangav** [comment]
Hi all, proposed solution - **Import Curl** dropdown option in Collection tab, then will it open an input where you paste curl text, then it opens a request after parsing it

Is this ok for all? any suggestions?

**Comment by Aurelioolive** [comment]
Hi @rangav. For me it's amazing.

**Comment by jsjain** [comment]
As long as i can assign a keyboard shortcut like `cmd + O`, either tab is fine by me.

**Comment by rangav** [comment]
Hi All , start working on this.

The keyboard shortcut will be `Cmd/Ctrl + u`  as `cmd + o` is open file command

let me know your feedback

**Comment by jsjain** [comment]
Can we have `i` for import else u is also fine ?

**Comment by ipumpkin17** [comment]
I think Insomnia implementation is convenient. You can import Curl command into Insomnia by pasting it into the URL bar.

**Comment by rangav** [comment]
This feature implemented in v1.3.0, see import/export section
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.

**Comment by rangav** [comment]
hi guys sorry delay to replying to your questions above, was busy doing release and updating documentation.

Hi @jsjain we have now 3 separate import menus for curl, collection and environment 

so using shortcut `i` for only curl may confuse users

Hi @ipumpkin17 current implementation needs to request to be saved before it can open in request window. So its more work to do that way.

anyway keyboard shortcut is faster way to import curl.

**Comment by BIwamoto-Kartazi** [comment]
I am unable to import cURL text. When I try to paste the cURL absolutely nothing happens, but I can type anything else. It seems to me that this is a copy and paste problem in the cURL text input window.

`curl -X GET \
  'https://www.thunderclient.io/welcome' \
  -H 'Accept: */*' \
  -H 'User-Agent: Thunder Client (https://www.thunderclient.io)'`

**Comment by rangav** [comment]
Hi @BIwamoto-Kartazi i noticed too some issues with paste, don't know whether it's a vscode bug or thunder client

was it working before?

**Comment by BIwamoto-Kartazi** [comment]
Hi @rangav. So, this is my first contact with Thunder Client. I did a simple test of copying and pasting the cURL text. I can't tell you if this feature previously worked.

**Comment by rangav** [comment]
Thanks @BIwamoto-Kartazi for confirming. I will look into it. 

Alternatively you can use Edit Menu and Paste option. This will work
![Screenshot 2021-07-06 at 22 17 03](https://user-images.githubusercontent.com/8637550/124667895-fb2f0700-dea7-11eb-978f-afeea8d7995f.png)

**Comment by BIwamoto-Kartazi** [comment]
@rangav, I believe I have figured out how to simulate the bug. I tried to paste the cURL text again and the attempt was successful. What I did was: I opened the Thunder Client extension, but without any request tab open, I ran the shortcut Ctrl+U and pasted it, but when I tried to perform the procedure again, with a Thunder Client request tab already open, I didn't managed to paste the cURL text.

Here is the link to the video I recorded simulating the bug: https://www.loom.com/share/b175aaa8ebff4ed7a9f150e235a29a72

**Comment by rangav** [comment]
Hi @BIwamoto-Kartazi i created a separate bug for this, we can discuss there https://github.com/rangav/thunder-client-support/issues/254

**Comment by lavahasif** [comment]
![image](https://user-images.githubusercontent.com/22430922/181609361-3f71cc12-c153-46ce-a029-6f0f21c7081b.png)

**Comment by rangav** [comment]
Hi, We added 2 new features for `Curl` in `v1.17.0`

1. Now you enter `Curl Text or Url` in the same input ( shortcut `Ctrl/Cmd + u` )
<img width="755" alt="Screenshot 2022-08-01 at 14 06 06" src="https://user-images.githubusercontent.com/8637550/182155125-46e13863-2001-40a1-8bb5-714cc360061d.png">

2. Added a new command `Thunder Client: Import Curl` to command palette, just search `curl`, which is helpful to run a  request from any view. Here also you enter Curl text or Url
<img width="740" alt="Screenshot 2022-08-01 at 14 07 47" src="https://user-images.githubusercontent.com/8637550/182155373-e0798210-8e2f-4dd7-86d1-9b643343a0f5.png">


see all feature release in `v1.17.0`
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

**Comment by yunyuyuan** [comment]
> 

Maybe you can add it to the dropdown menu🙏
![image](https://user-images.githubusercontent.com/45785585/203885606-a27dbfce-1042-446c-84ab-8671e8d940e7.png)

**Comment by rangav** [comment]
@yunyuyuan its already available in activity tab menu

**Comment by yunyuyuan** [comment]
> 

Found it,thanks!

**Comment by ariesy** [comment]
Hi, I can see there's an import from cURL menu, is there any way to export single request to cURL?

**Comment by rangav** [comment]
Hi @ariesy 

Use code snippet feature and select Curl
https://github.com/rangav/thunder-client-support#codegen

**Comment by Sandeep7OnShell** [comment]
What about exporting as cUrl? It does not look like possible in Thunder Client?

**Comment by rangav** [comment]
@Sandeep7OnShell see this comment -  https://github.com/rangav/thunder-client-support/issues/11#issuecomment-1657752231

**Comment by singhkunal2050** [comment]
This Feature seems to be a paid feature now! 

Such a bummer! 

![Image](https://github.com/user-attachments/assets/43c4f877-308a-46cc-8908-6d9cc969b274)
