### ISSUE TITLE
Plugin hangs on Processing

### ISSUE THREAD

**Issue by pawelmiechowiecki** [rangav/thunder-client-support#110]
**Describe the bug**

During "Run" command - no mater if it is a single REST call, or bulk Test run - plugin hangs on "Processing" without any information why. Some requests are sent to backend, but other not. 

**To Reproduce**

This is how I got to the error:
1) Create "New Request" (ie GET /pets/1) 
2) Add to "Tests" of a single record request a "test": rewrite json.id to variable.
3) Duplicate the Request
4) In duplicated request remove "1" from path (GET /pets)
5) Run
Plugin tries to assign json.id to variable on a collection returned (collection has no json.id, the single record has)

**Expected behavior**

Some warning: There was a try to assign attribute to variable, but instead of attribute the service returned a collection. 

**Platform:** 
 - OS: windows
 - Saving: enabled
 - Loading from project: enabled

**Solution:**

Workaround: edit the Request and hit Save or hit the Save button on Env tab

**Comment by rangav** [comment]
Hi @pawelmiechowiecki thanks for reporting,

can you use any https://httpbin.org/ url and reproduce the issue. and write the steps here. so i can test it.

**Comment by rangav** [comment]
This is fixed in v1.2.1 please check and let me know
https://github.com/rangav/thunder-client-support/releases/tag/1.2.1
