### ISSUE TITLE
Please rename Json as JSON

### ISSUE THREAD

**Issue by faceair** [rangav/thunder-client-support#1101]
**Describe the bug**

JSON is short for JavaScript Object Notation, which is a proper noun and does not have a lowercase form of Json.

**To Reproduce**

<img width="488" alt="image" src="https://user-images.githubusercontent.com/3659110/229816036-99f70acc-0934-47ce-a7da-b9ff94edcb7f.png">

**Expected behavior**

Json -> JSON

**Comment by faceair** [comment]
Similar words include:
Http -> HTTP
Xml -> XML
Graphql -> GraphQL
Url -> URL
Aws -> AWS/aws

**Comment by rangav** [comment]
This Bug is fixed now, please update to `v2.6.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.1

Please let me know your feedback.
