### ISSUE TITLE
Expected value in test does not accept two consecutive spaces

### ISSUE THREAD

**Issue by vasansr** [rangav/thunder-client-support#1103]
**Describe the bug**

In Tests, the value input replaces two spaces with one space.

**To Reproduce**

1. Go to the "Tests" section in any request
2. Try to type an expected value such as "Two   Spaces" (note: two or more spaces between the words).
3. You will find that after the first space, you cannot type any more spaces, the typed spaces are killed.    

**Expected behavior**

I'd like to preserve the expected value as typed, including multiple spaces. Some of my responses are indeed returning a value with multiple spaces in them, and I am unable to test for the exact value. I am having to resort to a regex instead.

**Platform:** 
 - OS: MacOS
 - vscode version: 1.77.0
 - extension version: v2.6.0

**Your Team Size Using TC:**

20

**Comment by rangav** [comment]
Hi @vasansr thanks for reporting the bug, will look into it.

**Comment by rangav** [comment]
This Bug is fixed now, please update to `v2.6.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.1

Please let me know your feedback.

**Comment by vasansr** [comment]
Verified as working. Thank you!
