### ISSUE TITLE
Value of  Env Variable updated in Pre Request is not used in "actual" Request

### ISSUE THREAD

**Issue by wavveen** [rangav/thunder-client-support#1104]
**Describe the bug**
If the value of an environment variable is updated with the "setTo" feature of a Pre Request, this new value is not being used by the "actual" request that follows. Instead the old value is being used. It seems this issue is intruduced in the latest release (v2.6.0) as our automated tests are failing since.

**To Reproduce**
Create a request that uses a env variable, and set-up a Pre-Request that updates this value. Check the value of the env variable during the "actual" request.

**Expected behavior**
The request followed by the pre-request should use the updated value.

**Comment by rangav** [comment]
Thanks @wavveen for reporting the bug, Will look into it.

**Comment by rangav** [comment]
This bud is fixed now, will publish new Update tomorrow.

**Comment by rangav** [comment]
This Bug is fixed now, please update to `v2.6.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.1

Please let me know your feedback.

**Comment by wavveen** [comment]
Thanks! Automated tests are running with the latest version again!

**Comment by rangav** [comment]
Thanks @wavveen for the confirmation
