### ISSUE TITLE
Add support for generating types for Golang

### ISSUE THREAD

**Issue by K0ng2** [rangav/thunder-client-support#1108]
I would like to request that Thunder Client add support for generating types for Golang. This would greatly improve the experience for Golang developers who use Thunder Client for API testing and development.

Thank you for your consideration.

**Comment by rangav** [comment]
Thanks @K0ng2 for the feedback, Will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to v2.6.1

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.6.1

Please let me know your feedback.
