### ISSUE TITLE
How to save response body as access_token variable?

### ISSUE THREAD

**Issue by julesm007** [rangav/thunder-client-support#111]
In Postman, I have a POST that returns an access token and saves it in a variable called {{access_token}}. In "Tests" I have the following to do this:

`var data = pm.response.text();
postman.setGlobalVariable("access_token", data);`

In Thunder Client, I created an environment variable in the environments I am using with the same variable name set to nothing. 

When I execute the POST, I get the following error message:
_Set Env Variable not supported for Content-type: text/plain; charset=utf-8_

Could you please let me know how to do this in Thunder Client?

**Comment by rangav** [comment]
Hi @julesm007 currently not possible i will think of it how to implement.

**Comment by julesm007** [comment]
> Hi @julesm007 currently not possible i will think of it how to implement.

Thanks for the quick reply!!!

**Comment by rangav** [comment]
This feature is released in v1.2.1 for details https://github.com/rangav/thunder-client-support/releases/tag/1.2.1

See documentation how to use

**Comment by julesm007** [comment]
Thanks a lot!

Quick question, in my scenario mentioned above, the entire response body is the token with no json parameters at all. I'm having trouble saving this token into a variable because of that.

For example:

Response body actual text:
@4a12n35356abc==

**Comment by rangav** [comment]
What is response context type?

for plain text use **text** keyboard 
For json use **json** keyword
