### ISSUE TITLE
XML Attributes Testing

### ISSUE THREAD

**Issue by ssuriya1** [rangav/thunder-client-support#1113]
**Type:** Feature/Suggestion

**Feature reason with Description:** I have faced some problems while testing with the XML. While I tried to convert the XML to JSON, I see only the tag name was available. But the attributes are not being converted in the JSON. I would suggest that if this is implemented it would be more helpful for my work.

**Comment by rangav** [comment]
Hi @ssuriya1 thanks for the feedback, can you please share sample XML with attributes

**Comment by rangav** [comment]
Thanks for sharing, will implement this feature in the next update.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.7.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.7.4

Please let me know your feedback.

### Xml Testing Docs
https://github.com/rangav/thunder-client-support/blob/master/docs/testing.md#xml-testing
