### ISSUE TITLE
Support Importing OpenAI Collections

### ISSUE THREAD

**Issue by ooobii** [rangav/thunder-client-support#1114]
**Please describe feature/problem details and solution you'd like.**
Hi there! It would be awesome if we could import collections from OpenAI-formatted endpoints (e.g. ones rendered by Swagger interfaces).

**Describe alternatives you've considered**
Currently, I can import the file into Postman, then export as a Postman collection, allowing import into Thunder client.

**Your Team Size Using TC:**
~15 engineers

**Comment by rangav** [comment]
Hi @ooobii OpenAPI Import is already supported 

docs
https://github.com/rangav/thunder-client-support/blob/master/README.md#import

**Comment by ooobii** [comment]
LOL, maybe if I RTFM, I would have seen that!!

Sorry for the disruption, and thank you for pointing me in the right spot 😄

**Comment by myfonj** [comment]
What exact version and features of the Openapi JSON files are supported?
I've been unable to import json that identifies itself as `"openapi": "3.0.1"` and the only error I see in the output log pane is:

    The following imports of Collections and Envs are supported - Postman 2.1.0, Insomnia v4 json, Open API v3 json or yaml files, Thunder Client

Before digging deeper to indentify what exactly causes the bailout and producing MRE, isn't there any more retailed description of the capabilities or debugging procedure I could follow?

(I've tried minimal openapi definition without any $refs and components and whatnot and that worked OK.)

**Comment by rangav** [comment]
@myfonj Currently supports OpenAPI 3.0

Can you please create a new issue for this and share sample OpenAPI file which can reproduce the issue will look into it.

**Comment by rangav** [comment]
@rsindall 

I have tested the yaml file and it works fine.

**How to import**

1. Open TC extension and select Collections Tab
2. From the menu select Import and select yaml file attached
