### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by fairking** [rangav/thunder-client-support#1115]
**Your Team Size Using TC:**
3

**Question:**
Could not find in docs.
v.2.6.2
Consuming the local api with self signed certificate I am having the following error: "unable to verify the first certificate".
Is there any way to make it working?

**Comment by rangav** [comment]
Hi @fairking did it work before with the previous version of the extension?

Docs here
https://github.com/rangav/thunder-client-support#manual-ssl-certificates
