### ISSUE TITLE
Other two typos

### ISSUE THREAD

**Issue by faceair** [rangav/thunder-client-support#1116]
**Describe the bug**
<img width="415" alt="image" src="https://user-images.githubusercontent.com/3659110/231541005-4f7e8cc3-857e-4033-955c-98e6c6f73ea2.png">

<img width="337" alt="image" src="https://user-images.githubusercontent.com/3659110/231541043-9023861a-3e4d-4ee1-a990-113b0ea60c3a.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/3659110/231543013-27517a6f-9d3f-447f-81ea-27b02609a9b7.png">

**Expected behavior**

Curl -> curl/cURL https://en.wikipedia.org/wiki/CURL
Url -> url/URL https://en.wikipedia.org/wiki/URL

**Comment by rangav** [comment]
Thanks @faceair for the feedback, Will fix in next update

**Comment by faceair** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/3659110/231625685-ca4c72aa-5054-4f75-844a-8b13a004427b.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/3659110/231625758-8bb4dd5c-d2f9-4ea8-84e6-d332b9c3447e.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/3659110/231625784-7834677d-e9cc-4f38-8cdd-f505ab59aa9a.png">

<img width="497" alt="image" src="https://user-images.githubusercontent.com/3659110/231625825-363f614a-72ec-42a5-872b-5facd894c80f.png">

Update some typos in the settings.

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.9.2`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.2

Please let me know your feedback.
