### ISSUE TITLE
The JSON validator cannot correctly check template variables

### ISSUE THREAD

**Issue by faceair** [rangav/thunder-client-support#1117]
**Describe the bug**

<img width="513" alt="image" src="https://user-images.githubusercontent.com/3659110/231543286-c406a4b1-2996-4a82-a98d-fcbdc1ad652a.png">

**To Reproduce**

```
{
  "query": "",
  "max_point": 90,
  "time_range": [
    {{#date, {hour: -1}}},
    {{#date}}
  ]
}
```

**Expected behavior**

No error.

Perhaps we can have the validator check the rendered template variables in the backend after they have been processed, rather than passing the raw text from the input field to the validator.

**Comment by rangav** [comment]
Thanks @faceair for the suggestion, will look into it.

**Comment by rangav** [comment]
We have fixed the JSON validation syntax error for environment variables in `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
