### ISSUE TITLE
the body of the get request in undefined 

### ISSUE THREAD

**Issue by Houssem12-ai** [rangav/thunder-client-support#112]
**Describe the bug**
when i try to get the GET request body in nodejs with req.body it shows that the json object that i received is undefined while it works well in in POSTMAN 

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 

**Solution:**

**Comment by rangav** [comment]
Hi @Houssem12-ai duplicate of https://github.com/rangav/thunder-client-support/issues/112
