### ISSUE TITLE
Array Filter with IP Addresses

### ISSUE THREAD

**Issue by alirandali87** [rangav/thunder-client-support#1123]
**Describe the bug**
When you define a JSON Path Array Filter with dots in it. It does not work: ERROR undefined

**To Reproduce**
json.item[value="192.168.2.0"].name

**Expected behavior**
It should be possible to search for any type of value inside an array filter

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.77
 - extension version: 2.62

**Your Team Size Using TC:**
not relevant

**Comment by rangav** [comment]
Thanks @alirandali87 reporting the bug, Will verify and fix it asap

**Comment by alirandali87** [comment]
Thanks.  Same is I think if you check a URL with equal or contains
json.item.href equal http://test.com  Starts with till http I get a Pass when I ad ":" it is a fail

**Comment by rangav** [comment]
re-opened this issue, as the bug is not fixed yet, but will fix it in the next update.

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
