### ISSUE TITLE
the converted base64 is not what I need

### ISSUE THREAD

**Issue by WudiJoey** [rangav/thunder-client-support#1125]
**Describe the bug**
i using filter in body like "{{img | readFile | btoa}}".
but it can't product the same base64 string like python code:
```
img_ = open(img, 'rb').read()
img_ = str(base64.b64encode(img_), encoding='utf-8')
```

**Expected behavior**
what should i do to write the correct filter for image file encoding?

**Comment by rangav** [comment]
Thanks @WudiJoey for reporting the issue, Will look into it.

**Comment by WudiJoey** [comment]
您好，您的来信我已经收到，会尽快回复。
