### ISSUE TITLE
Html request and response report in thunderclient CLI

### ISSUE THREAD

**Issue by AmulHaradCoreCard** [rangav/thunder-client-support#1126]
**Your Team Size Using TC:**
10

**Question:**
When we run thunderclient collection(using excel/json upload) using CLI then we are not able to get Request and Response
For Ex - If we are uploading 10 records using excel/json, in HTML report not able to get for each request and response.

**Comment by rangav** [comment]
Hi @AmulHaradCoreCard you  need to use the slider to move to different iteration of the collection

**Comment by AmulHaradCoreCard** [comment]
Hi, Thanks for the reply, we are getting responses using the slider option but no requests.
we only get the URL for the request, not the request body,
like  - Request Url: http://localhost:9600/projectName/entity/Add

**Comment by AmulHaradCoreCard** [comment]
Where I will get the requests body, I am using request like below 
{
  "Name": "{{Name}}",
  "PhoneNumber": "{{PhoneNumber}}",
  "Active": "{{Active}}",
  "Id": "{{Id}}"
}

**Comment by rangav** [comment]
You can see in logs in `Output` window when you run single request

**Comment by AmulHaradCoreCard** [comment]
I am getting it for single requests, but for JSON upload for multiple requests where can I get ?

**Comment by rangav** [comment]
body is not display for run collection in logs. 

Will display body in logs in next update for Run collection.

**Comment by AmulHaradCoreCard** [comment]
Hi Ranga,

When we will be able to use this feature?

**Comment by rangav** [comment]
@AmulHaradCoreCard  Could be early next week.

**Comment by AmulHaradCoreCard** [comment]
Thanks

**Comment by rangav** [comment]
@AmulHaradCoreCard Run Collection logs improved when run from extension UI

https://github.com/rangav/thunder-client-support/issues/1162

**Comment by rangav** [comment]
Hi @AmulHaradCoreCard this feature will be part of the next update.

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.9.0`

- Now the **Html report** has request and response details
- Update CLI to `v1.4.0`


See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please let me know your feedback.
