### ISSUE TITLE
How to get name of Thunder client CLI's report file

### ISSUE THREAD

**Issue by broccolism** [rangav/thunder-client-support#1128]
**Your Team Size Using TC: 30**

**Question: Can I get the name of report file name using thunder client CLI's `--report` option?**
I guess the report file name is based on timestamp that I started the `tc` command...
I'm using github CI/CD and I wanna know the name of generated file name and share it with my team members.
But I cannot check the file name because it will be stored in github action runner.
Is it possible in current version?

Or if there's another way to share the report file in the github action runner, please let me know.

**Comment by rangav** [comment]
Hi @broccolism

- The reports will be saved to `thunder-reports` folder, you can share this folder
- The file name will be of the format `thunder-report_{collection_name}_{timestamp}.html`, you can also share this file

You can see the sample github actions yaml file 
https://github.com/rangav/thunder-client-support/blob/master/docs/main.yaml#L47

**Comment by broccolism** [comment]
Hi @rangav ! Thanks for quick reply. But I need to know the exact timestamp.
For example I cannot identify which file is created by my command when my teammates run the same command on the same server at the same time.
Is there any way to know the exact file name? Such as to get file name in stdout as the result of the command..

**Comment by rangav** [comment]
The sample report file name - `thunder-report_User_2023-03-06T18-24-34-726Z.html`

You can read all the files in the` thunder-reports` folder and you can sort the files by date and take recently modified file.

**Comment by broccolism** [comment]
I haven't been using other API clients before.. but I expected getting the file name in stdout after running the command.
Is it possible now?

**Comment by broccolism** [comment]
@rangav I haven't been using other API clients before.. but I expected getting the file name in stdout after running the command. Is it possible now?

**Comment by rangav** [comment]
Where is the request data stored for thunder Client?

**Comment by broccolism** [comment]
It's under the github project folder, in `thunder-tests`. Is this a problem?

**Comment by rangav** [comment]
ok got it. Then there wont be conflict with other users. As the timespamp has millisecs in the name.

Then this suggestion will work.
https://github.com/rangav/thunder-client-support/issues/1128#issuecomment-1523649995

**Comment by broccolism** [comment]
But our team shares that folder.
What if I run command at `2023-04-30 00:00:00.000` and my teammate at `2023-04-30 00:00:00.001` ?
I know there will be 2 files with those timestamps, but I cannot know that mine is the one with `2023-04-30 00:00:00.000`.
This code won't be working since the timestamp will be different, isn't it?

```js
 - name: Get Timestamp
    uses: actions/github-script@v6
    with:
      script: |
          const time = new Date.now() // ===========> this might give me before '2023-04-30 00:00:00.000'
 - name: Run Thunder Client collection
    run: |
      tc --fol '(folder id)' --report html // ==========> ... if this command is executed at '2023-04-30 00:00:00.000'
```

**Comment by rangav** [comment]
You can use upload artifacts in the GitHub Actions and name the folder as you require it

see example below ( `RunReports `)
https://github.com/rangav/thunder-client-support/blob/956f1ab840961d058f0dffcc9c550390591bce52/docs/main.yaml#L51

**Comment by rangav** [comment]
you can also use email notifications in Github Actions

**Comment by broccolism** [comment]
Alright, I'm gonna try that way. Thanks for replies.
