### ISSUE TITLE
How to set a env value with two json point value to another env with format?

### ISSUE THREAD

**Issue by Suprock** [rangav/thunder-client-support#1129]
**Your Team Size Using TC:**

**Question:**
In the test , I want to use a env value and two json point value set to another env , but when i use  {{env_name}} |format("{0}{1}{2}", "value1", "value2") setto env_name_1, only the env_name's value set to env_name_1. how can i set the fomat value to env_name_1?
tx.

**Comment by rangav** [comment]
Hi @Suprock 

Currently you can use only one json value in format filter like below

![image](https://user-images.githubusercontent.com/8637550/234218494-759b5e82-ed2e-46ee-b2af-7b7673c353a5.png)


But you can use Custom filter like below

Custom filter docs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters
![image](https://user-images.githubusercontent.com/8637550/234218948-8545e43a-e57e-4af9-97c8-c5fb063d0387.png)

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed

**Comment by Suprock** [comment]
OK,thx
