### ISSUE TITLE
Pre and Post request scripting

### ISSUE THREAD

**Issue by dannywalk** [rangav/thunder-client-support#113]
**Is your feature request related to a problem? Please describe.**

I often need to extract data from a response for making another post, eg a custom auth token or some such.  

**Describe the solution you'd like**

It would be cool if you mimicked Postman's Pre-req script tab, but if you can think of something simpler that would be cool too.  It would also be cool to have a dedicated post-req script tab (postman supports scripts in 'Tests' tab which is where you can add these sorts of scripts)

**Describe alternatives you've considered**
Postman is the only alternative really.

**Implementation:**

**Comment by rangav** [comment]
Hi @dannywalk we already support this set env from response, see GitHub page scriptless testing section.

I am closing this, feel free to re-open if needed.
