### ISSUE TITLE
Import Swagger.json doesn't work

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [rangav/thunder-client-support#1130]
**Describe the bug**
I tried to import the OpenAPI json from Argo Workflow but it failed.
https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json

However, if I use Postman to import it and export to OpenAPI 2.1 and Import it to Thunder Client. And it works. 

**To Reproduce**

import from Url https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json

**Expected behavior**
It should work

**Platform:** 

Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
Thunder-client: 2.6.1

**Your Team Size Using TC:**
2

**Comment by rangav** [comment]
Hi @Sam-Lin-MillersLab 

Currently only supports Open API 3.0 format for import

see details here
https://github.com/rangav/thunder-client-support#import

**Comment by Sam-Lin-MillersLab** [comment]
Thanks for the fast response.

**Comment by Sam-Lin-MillersLab** [comment]
Small suggestion on this, maybe we can have some error messages for OpenAPI version. I was checking log and there was no error message.

**Comment by rangav** [comment]
Thanks @Sam-Lin-MillersLab for the feedback, will update logs
