### ISSUE TITLE
thunderclient.json should break into smaller files

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [rangav/thunder-client-support#1131]
**Please describe feature/problem details and solution you'd like.**

It will be great if we have thunderclient.json per collection. Currently I have like 5K loc in this file. 

Overall I think breaking it up will be much easier to do code merge in a monorepo.

**Describe alternatives you've considered**

none

**Your Team Size Using TC:**
2

**Comment by rangav** [comment]
Hi @Sam-Lin-MillersLab thanks for the feedback, 

There is an existing issue related to this. Can you please add comments there, so we can track in one place.

#574

**Comment by Sam-Lin-MillersLab** [comment]
ah.. sorry, I did a quick search and didn't see that one.

**Comment by rangav** [comment]
We now split the Collections and Environments into separate files to reduce merge conflicts in `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
