### ISSUE TITLE
Thunder Client isn't in the extensions of VS

### ISSUE THREAD

**Issue by JoseAlayonGo** [rangav/thunder-client-support#1133]
I don't find Thunder Client extension in VS, so I can't install it (windows 11)

![image](https://user-images.githubusercontent.com/131894687/234627212-7d6033a8-ba8b-459b-95b0-22b927bcc0c7.png)

**Comment by rangav** [comment]
Hi @JoseAlayonGo 

The extension is only available for `VS Code` and not available for Visual Studio.
