### ISSUE TITLE
Testing : loop in a list of possible values for a given parameter

### ISSUE THREAD

**Issue by EricAubinSTLA** [rangav/thunder-client-support#1134]
Hello,

Is it possible to declare a list of values for a paramater and after run the query for each possibe parameter values ?
And after run the query for each possibe parameter values ?

If it is possible in Thunder Client can you explain how to do that ?

Best regards

**Comment by EricAubinSTLA** [comment]
Hello @rangav , thanks for your reply.

I specify my scenario :

Here is the query :
mybaseUrl/mypath?myParmeter=<myValueX>

For myParmeter , I have an array of possible values for example [Value1,Value2,Value3....]

The test would consist of : 

step 1 : Set myValueX = Value1 
step 2 : Then run with  Value1 the query mybaseUrl/mypath?myParmeter=Value1 
Step 3 : Read the body response (decide if good or not)
Step 4 : Loop go to Step 1 with the next value (Value2 will be set for <myValueX>)

Is it possible to do this with your thunder client :) ?

Best regards,

Eric

**Comment by rangav** [comment]
yes you can do that.

input data format 

```
[{
"myValueX":"Value1"
},
{
"myValueX":"Value2"
},
{
"myValueX":"Value3"
}]
```

And in Tests tab you can verify the response body as required.

**Comment by EricAubinSTLA** [comment]
@rangav 

Thanks a lot, I've just tested a simple example and it works :)

**Comment by rangav** [comment]
Thanks @EricAubinSTLA for the confirmation.
