### ISSUE TITLE
Thunder Client is not reading files from custom directory

### ISSUE THREAD

**Issue by CookieMonster70** [rangav/thunder-client-support#1135]
**Team Size Using TC: >5**

**Question:**
Find Thunder Client very good tool and we now wanted to use this tool in the team. So I wrote a few example tests and pushed them to GIT.
Now a colleague has pulled these sources and everything ran without issue. He just installed the VS code and plugin without changing anything in the settings.
Another colleague has exactly the same setting as described above. The files are visible in VS Code workspace, but they are not loaded in Thunder Client.
Unfortunately we have no error message and do not know how to get the whole thing to work.
Do you have any idea how we can figure it out to solve this issue?

**Comment by rangav** [comment]
Hi @CookieMonster70 

You need to enable vscode setting `Save to Workspace`

more details for git sync
https://github.com/rangav/thunder-client-support#git-sync

**Comment by CookieMonster70** [comment]
Thanks! Works like charm :)

**Comment by rangav** [comment]
You are welcome 👍
