### ISSUE TITLE
Is there a way to export all my collections to Postman or Swagger yml file?

### ISSUE THREAD

**Issue by vysogot** [rangav/thunder-client-support#1136]
I know I can export collections one by one. Can I do a bulk export?

**Comment by rangav** [comment]
Hi @vysogot 

Currently, you have to export each collection individually.

You can export to Postman format
https://github.com/rangav/thunder-client-support#how-to-convert-to-postman-format

**Comment by vysogot** [comment]
1. Is it done on purpose that you can import all formats in bulk but can't export in bulk? 
2. So that when our team starts using your product they can't escape easily? 
3. I wonder ironically, as your product is very nice and done in modern times, what is the cognitive work behind asymmetrical functionality of import & export? 
4. And of course, would you mind adding this as your feature?

**Comment by rangav** [comment]
Hi @vysogot 

Bulk import is implemented because someone has requested the feature.

Till now no one requested for bulk export feature 

And also we don't force users stay with Thunder Client, users can choose any API client that suits their use case.

Sure will add this feature request to roadmap.

**Comment by rangav** [comment]
Also you didn't answer the question how many team members using TC?

**Comment by vysogot** [comment]
Thanks! I'm glad to hear that!
