### ISSUE TITLE
CI/CD on ThunderClient

### ISSUE THREAD

**Issue by Mmartos13** [rangav/thunder-client-support#1138]
**Your Team Size Using TC:**
10

**Question:**

Our team wants to develop a solution based on tc cli. We are trying to make a request from CLI as in this image and following the tutorial on Medium

![imagen](https://user-images.githubusercontent.com/73356168/235619481-38917217-840e-4ce6-a641-0fd561127dc0.png)

But i can't never see any output, it only works when requesting from cli. 
Versions: 

tc -V --> tc utility, iproute2-ss200127
node -v --> v16.16.0

I would like to know what we are doing bad. Thank you in advance.

**Comment by rangav** [comment]
Hi @Mmartos13 Will verify and get back to you

**Comment by Mmartos13** [comment]
Thank you @rangav!
I am looking forward to reciving your reply

**Comment by rangav** [comment]
Hi @Mmartos13 did you install CLI?

If you have conflict with tc name you can also use `tc2`

1. Install using `npm i -g @thunderclient/cli`
2. try `tc2 welcome`

**Comment by Mmartos13** [comment]
Hello @rangav ! 
Solved using tc2, we were trying with tc and it doesn't work
