### ISSUE TITLE
Code snippet generation

### ISSUE THREAD

**Issue by gopinath-manickam** [rangav/thunder-client-support#114]
**Describe the solution you'd like**
I would like to have a feature of generating a code snippet of a request in various programming languages like  curl, bash, PowerShell, python .

**Comment by rangav** [comment]
Hi @gopinath-manickam will add this to the roadmap.

**Comment by rangav** [comment]
Hi @gopinath-manickam this feature will be in the next update v1.5.0

**Comment by rangav** [comment]
Code Snippet Generation initial support in v1.5.0

- Curl
- C# HttpClient
- Javascript Fetch & Axios
- Python requests & http.client

Click on icon `{ }` to see Code tab

https://github.com/rangav/thunder-client-support/releases/tag/1.5.0

Let me know your feedback

**Comment by rangav** [comment]
I have now created a separate project this code snippet, its open for contribution.

https://github.com/rangav/thunder-codegen

**Comment by gopinath-manickam** [comment]
> Code Snippet Generation initial support in v1.5.0
> 
> * Curl
> * C# HttpClient
> * Javascript Fetch & Axios
> * Python requests & http.client
> 
> Click on icon `{ }` to see Code tab
> 
> https://github.com/rangav/thunder-client-support/releases/tag/1.5.0
> 
> Let me know your feedback
> 
> I will also publish codegen as separate library in the next release and it will be open for contribution.

Thank you so much for this feature.

**Comment by rangav** [comment]
@gopinath-manickam you are welcome 👍

**Comment by rangav** [comment]
**PowerShell** added to Code Snippet in v1.9.0

https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0
