### ISSUE TITLE
Run Collection using csv file

### ISSUE THREAD

**Issue by CookieMonster70** [rangav/thunder-client-support#1140]
**Question:**
I have rest call like delete: https://abc.com/v1/api/bb6a3628-2e02-4e64-9c94-4f2c6fae3a38
Now I wan't do the same call over run collection and using a csv like:
and link the external_uuid with a variable and use it in the url
like https://abc.com/v1/api/{{external_uuid}}

475b6558-f1b3-4927-b90d-c71d76e83f7c
e48d6b38-a5f9-433c-865b-82747a263968
9a9a3af8-519b-42d1-a64f-d6fbf6601cc4

but the console always returns me:
ttps://abc.com/v1/api/%7B%7Bexternal_uuid%7D%7D

What I'm doing wrong?

Regards,
Daniele

**Comment by rangav** [comment]
Hi @CookieMonster70 

The CSV file format first line should be name of variable

see example csv
```
external_uuid
475b6558-f1b3-4927-b90d-c71d76e83f7c
e48d6b38-a5f9-433c-865b-82747a263968
9a9a3af8-519b-42d1-a64f-d6fbf6601cc4
```

**Comment by CookieMonster70** [comment]
I have done this, but I doesn't load it.

**Comment by rangav** [comment]
See images below

![image](https://user-images.githubusercontent.com/8637550/235921201-051cb5d6-ae3c-46e3-86a7-da87ce9cf103.png)

Data file
![image](https://user-images.githubusercontent.com/8637550/235921365-bce18347-e543-4605-a2e6-8b6d16933c42.png)

Request
![image](https://user-images.githubusercontent.com/8637550/235921585-fe9b1b32-2c14-401e-a7ba-9a833f80470c.png)

Run Collection
![image](https://user-images.githubusercontent.com/8637550/235921777-1473678a-fdae-4658-b76a-ee45059e47cf.png)

**Comment by CookieMonster70** [comment]
Somehow it's not working.

![image](https://user-images.githubusercontent.com/25148194/235944574-3c7f14e4-4db4-4d15-bd80-6bc37c172cd2.png)
![image](https://user-images.githubusercontent.com/25148194/235944676-897a2a1f-a656-4fd0-a2dd-ac3266d198d3.png)

**Comment by rangav** [comment]
if you run the request directly it will not work. The variables data is sourced from environments in this case.

The input data file will only work when you perform `Run Collection`

**Comment by rangav** [comment]
Click on the `Request `in the `Run Collection` view
![image](https://user-images.githubusercontent.com/8637550/235952314-1e3a8f3b-7076-4513-a8a1-177b2f6329cc.png)

**Comment by CookieMonster70** [comment]
Same behavior
![image](https://user-images.githubusercontent.com/25148194/235953702-89de9e62-41f9-4132-abfe-8f59b489d4b8.png)
![image](https://user-images.githubusercontent.com/25148194/235953957-c48345d4-cc98-4235-a61e-027ca6ed8a55.png)

**Comment by rangav** [comment]
Can you share your csv file data?

**Comment by CookieMonster70** [comment]
[test.csv](https://github.com/rangav/thunder-client-support/files/11384042/test.csv)

**Comment by CookieMonster70** [comment]
Hi I found the issue, it working now!
It was the encoding! 
If the encoding is UTF-8 with BOM it doesn't work and with UTF-8 only it works like you discribed!
Thanks for your help!

**Comment by rangav** [comment]
Thats great, you found the issue.
