### ISSUE TITLE
Merge problem with thunder client.json

### ISSUE THREAD

**Issue by alc86** [rangav/thunder-client-support#1145]
**Your Team Size Using TC:**
6 team members

Hi,

Out team always struggles with merging thunder client json files when there are many collection changes. I think the main problem is that thunder client does not store the new items at the and of the file. Today  I had this problem/issue because some of the new collection items were at the middle of the thunderclient.json and so git reports changes at the middle but with mixing up the items. Please explain us how thunder client store the data and hopefully we can find an improvement.

![Screenshot 2023-05-05 at 11 00 25](https://user-images.githubusercontent.com/29775093/236417642-a60b3096-0761-4732-a66e-ecf71923c7d3.png)

**Comment by rangav** [comment]
Hi @alc86 

New requests data is added at the end of `thunderclient.json`

**Comment by rangav** [comment]
related to https://github.com/rangav/thunder-client-support/issues/574

**Comment by rangav** [comment]
I am closing this issue, you can add any comments here #574

**Comment by rangav** [comment]
We now split the Collections and Environments into separate files to reduce merge conflicts in `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.

**Comment by rangav** [comment]
We have a feature request for splitting collection into multiple request files to reduce merge conflicts - https://github.com/rangav/thunder-client-support/issues/1507

Can you please let me know your feedback
