### ISSUE TITLE
Formatting the body of a request (ex. JSON) with a formatter like Prettier

### ISSUE THREAD

**Issue by vysogot** [rangav/thunder-client-support#1146]
**Please describe feature/problem details and solution you'd like.**
Currently when I paste an unformatted JSON, ex. from dev tools, I can't format it nicely like in Postman.

**Describe alternatives you've considered**
I need to have a JSON file handy, paste it there and then format using Prettier, then paste it to the request body editor in Thunder Client.

**Your Team Size Using TC:**
10

**Comment by rangav** [comment]
Hi @vysogot 

Can you please share a sample json, will look into it.

**Comment by vysogot** [comment]
I guess I missed the "format" button above the json body on the right hand side. Sorry! Now I see it and it formats well.
