### ISSUE TITLE
Github sync

### ISSUE THREAD

**Issue by hughsheehy** [rangav/thunder-client-support#1147]
**Your Team Size Using TC:** 1 today....maybe a dozen if i can get it working!

**Question:**
The instructions for how to do sync with Github don't match what's in the menu/command structure for me in Visual Studio Code. 

I imported a collection from Postman (which worked perfectly), then tested the APIs (worked perfectly) and then tried to figure out how to sync with Github. Stuck. 

The commands in the readme.md and what appear in VSCode (Win 11, latest version) don't match. 

H

**Comment by rangav** [comment]
Hi @hughsheehy 

you need to first enable Git sync VSCode setting first then import

git sync
https://github.com/rangav/thunder-client-support#git-sync

**Comment by rangav** [comment]
Which Menu in VsCode, can you please share screenshot?

**Comment by rangav** [comment]
I am closing the issue, feel free re-open if needed
