### ISSUE TITLE
Respect Editor Panel Location for New Requests

### ISSUE THREAD

**Issue by gaurangrshah** [rangav/thunder-client-support#115]
By default Thunderclient opens a new editor panel when creating a new request in the same location every time (top-left) and doesn't respect the vscode convention of opening new panels in the current active panel.

**To Reproduce**
![thunderclient-panel-issue](https://user-images.githubusercontent.com/1086269/117193119-7b55c500-adb0-11eb-8c2c-6bd8e2eadf0b.gif)

1. Open an existing request
2. move the panel location from the default position
3. now click "New Request"
4. panel will have opened in the default position again.

**Expected behavior**
I think it makes sense to either respect the current-panel behavior that is default in vscode when opening new files where they open in the active editor panel or to allow a boolean optional setting that let's us achieve this. 

**Platform:** 
 - OS: osx 10.13.6

**Solution:**

**Comment by rangav** [comment]
Hi @gaurangrshah i will look into it.

**Comment by rangav** [comment]
This is now fixed in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
