### ISSUE TITLE
CLI: run tests with headers dynamically

### ISSUE THREAD

**Issue by broccolism** [rangav/thunder-client-support#1150]
**Your Team Size Using TC:**
30

**Question:**
Hi, thanks for quick and kind replies before.
I have one more question about thunder client CLI.

I wanna run tests which need access token using CLI and github action CI/CD.
But the access token expires in an hour, so I need to re-generate it every hours and put it into the request header unless I'll get 401 error even though the request is valid.
Is it possible to set request header dynamically?

**Comment by rangav** [comment]
Hi @broccolism thanks for the feedback.

Is Access token based on OAuth 2 logic or Custom Javascript logic?

You can use Custom Scripting using filters
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by broccolism** [comment]
@rangav Thanks! I'm using OAuth but I found that I can set authorization header for each call after calling the API for getting access token from server.
