### ISSUE TITLE
Can we have variables with object support in data file / env file?

### ISSUE THREAD

**Issue by programatix** [rangav/thunder-client-support#1154]
Currently, the supported format for data file (and env file) is as such,
```
[
  {
    "period": 1,
    "asset": "BTC"
  },
  {
    "period": 1,
    "asset": "ETH"
  }
]
```

Can we have something like this?
```
[
  {
    "period": 1,
    "asset": {
      "name": "BTC",
      "desc": "The description",
      "parts": [
        {
          "id": "123"
        },
        {
          "id": "234"
        }
      ]
    }
  }
]
```

**Comment by rangav** [comment]
Thanks @programatix for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.7.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.7.4

Please let me know your feedback.

**Comment by programatix** [comment]
Thanks for the great update.

**Comment by rangav** [comment]
You are welcome
