### ISSUE TITLE
Change default for Auto run curl

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#1155]
Currently, when I import CURL - Thunder Client automatically runs it.

I know there is a setting I can change for that, but I think that the default should be different.

When ever I use import curl, its because I want to change it before I run - and I think that most people do the same.

Also on postman , the default is not to auto run.

**Comment by rangav** [comment]
Thanks @noam-honig for the feedback, will review it

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.7.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.7.4

Please let me know your feedback.
