### ISSUE TITLE
envFile does not work with workspace subfolders

### ISSUE THREAD

**Issue by andez2000** [rangav/thunder-client-support#1156]
When linking to an environment file, this only works when the environment file is in the root folder - not a subfolder.

For example, the thunder test configuration is local and the `thunderEnvironment.json` is:

```json
    "envFile": "../dev.env",
```

In contrast to a `thunderEnvironment.json` that does not work:

```json
    "envFile": "../asubfolder/dev.env",
```

This causes the environment variable key/values not to be replaced with the corresponding values.

# **To Reproduce**
See the repo here - open each sub folder in VSCode and look at the URL in the `ThunderClient->Collections->My Collection`.  Repo: https://github.com/andez2000/thunder-client-env-issue

### Working

![image](https://github.com/rangav/thunder-client-support/assets/16876524/a0b27fdc-e207-4c49-8838-528e7198bb53)

Resolved as shown in green.  This works when calling the URL.

### Not Working

![image](https://github.com/rangav/thunder-client-support/assets/16876524/ba1c763a-ad6d-4fa4-8dea-c201d5d83305)

Not resolved - shown in grey (normal) colour text.  This will add the following to the Thunder Client output:

```
Environment Used: Test Environment (Active)
Request Url: http://%7B%7BSOME_URL%7D%7D
Method: POST
Request Headers:
{
  "Accept": "*/*"
}
```

# **Expected behavior**
I would expect no matter where the environment file resided - it should load and resolve the key/values.

# **Platform:** 
 - OS: Windows 10
 - vscode version: 1.78.1
 - extension version: 2.6.2

**Your Team Size Using TC:**
3 at the moment - expect it to grow.

**Comment by rangav** [comment]
Thanks @andez2000 for reporting the bug, will verify and fix it

**Comment by andez2000** [comment]
It does work.

I have tracked the issue down to encoding on the .env file - although that sample repo I setup incorrectly.

Apologies
