### ISSUE TITLE
Add result to existing array variable.

### ISSUE THREAD

**Issue by programatix** [rangav/thunder-client-support#1157]
**Your Team Size Using TC:**
2

**Question:**
Is there a way to add the result into existing array variable. Say, I have the response with ```json.id```. I want to add/append it to existing (or create new array) for example ```{{my_ids}}```.

**Comment by rangav** [comment]
Hi, @programatix 

you can write custom JavaScript using filters
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by programatix** [comment]
I came up with this filter to add a result into an array.
```
function addToArray (value, name) {
    let data = tc.getVar(name);
    if (data != null) {
        try {
            data = JSON.parse(data);
        } catch {
            data = null;
        }
    }
    if (!Array.isArray(data)) {
        data = [];
    }
    data.push(value);
    return data;
}
```

To use,
- Left side:
  ```json.prop | addToArray("my_array")```
- Rifht side:
  ```{{my_array}}```

Looks a bit ugly but it works.

However, I also want to remove item, say after a DELETE request. In my case, the DELETE request has No Content in the response, so it become a bit problematic due to the way the Tests setTo works. So have to do something like this,

- Left side:
  ```text | removeFromArray("my_current_var", "my_array")```
- Right side:
  ```{{my_array}}```

and the function is something like this,
```
function removeFromArray (dummy, varValueName, varArrayName) {
    let value = tc.getVar(varValueName);
    let data = tc.getVar(varArrayName);
    if (data != null) {
        try {
            data = JSON.parse(data);
        } catch {
            data = null;
        }
    }
    if (isResponseSuccess(tc.response.status))
    {
        if (!Array.isArray(data)) {
            data = [];
        } else {
            let i = data.findIndex((x) => x == value);
            console.log(i);
            if (i >= 0) {
                data.splice(i, 1);
            }
            if (data.length > 0) {
                tc.setVar(varValueName, data[0], "local");
            } else {
                tc.setVar(varValueName, null, "local");
            }
        }
    }
    return data;
}

function isResponseSuccess(statusCode) {
    return (statusCode >= 200 && statusCode < 300)
}
```

Is it possible to allow usage of variable or user value on the left side, for example
- Left side:
  ```{{my_current_var | removeFromArray("my_array")}}```
- Right side:
  ```{{my_array}}```

**Comment by rangav** [comment]
Currently not possible to use variable in the left side directly. 

In future we will enable to run a function directly as Post Filter similar to existing `Pre-Filter`

**Comment by rangav** [comment]
Currently not planning to implement this.
