### ISSUE TITLE
How to run a filter/script after Tests performed?

### ISSUE THREAD

**Issue by programatix** [rangav/thunder-client-support#1158]
**Your Team Size Using TC:**
2

**Question:**
I would like to do some clean-up tasks after a request has been executed and Tests has completed. How to I run a filter/script after that (something like the Pre Run to filter before a request)?

**Comment by rangav** [comment]
Hi @programatix 

You can use custom filter in the `last` Test and perform any logic required
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#filters-in-tests

**Comment by rangav** [comment]
Will provide option to run a filter/script after request execution in the near future.

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.9.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please let me know your feedback.
