### ISSUE TITLE
Get Parameters when actioned need to be url encoded (space is %20 etc)

### ISSUE THREAD

**Issue by SuperRoach** [rangav/thunder-client-support#116]
**Is your feature request related to a problem? Please describe.**

When using parameters via a GET request, they are required to be URL encoded, to correctly be recognised by the browser, without it, the resulting request may be missing parts of the parameters. The most common one is spaces not being changed to %20 .
**Describe the solution you'd like**

Using javascript, you could run encodeURIComponent() if you know that it is a get request that is occuring.
You could run this on the output url so the user entering in data does not have it messed up (so they can change a name with spaces without it being encoded in the params window)

**Describe alternatives you've considered**

When you click send, all fields are url encoded before being sent off.

**Implementation:**

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by rangav** [comment]
Hi @SuperRoach Thanks for reporting, will fix it ASAP.

**Comment by rangav** [comment]
This is fixed in v1.2.1 - https://github.com/rangav/thunder-client-support/releases/tag/1.2.1

**Comment by zipzit** [comment]
How does this work?  I want to send a phone number ("+11235555555") but the plus sign isn't making it there...   The hack is to replace the plus sign with "%2B"   

With the fixed listed above, are all characters EncodeURIComponent() modified?
