### ISSUE TITLE
Support Variable in Password for Basic Auth

### ISSUE THREAD

**Issue by jandreaucodes** [rangav/thunder-client-support#1160]
**Please describe feature/problem details and solution you'd like.**
In Postman, you can use a variable for a Basic Auth password, meaning you can make saved APi calls dynamic per Environment. 

Thunder Client does not support that, and requires a password to be manually input into the Basic Auth settings for each API call.

**Your Team Size Using TC:**
13

**Comment by rangav** [comment]
Thanks @jandreaucodes for the feedback, will add to roadmap

**Comment by rangav** [comment]
You can use Env Variables in Basic Auth, it's already supported.

![image](https://github.com/rangav/thunder-client-support/assets/8637550/cb2367a3-c449-4304-a0fe-64568b03d19b)

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by jandreaucodes** [comment]
Oh. Are you saying if I click the Lock to unlock it, I can use a variable there?

I didn’t know. That’s perfect. Thank you.

**Comment by rangav** [comment]
Yes that's right
