### ISSUE TITLE
Run All is writing poor logs to console, which makes debugging really hard

### ISSUE THREAD

**Issue by CookieMonster70** [rangav/thunder-client-support#1162]
**Poor logging on console**
I really like the tool, also my teammates are starting using it. So we tried run a parameterized test with approx 1000 datasets.
Therefore we have prepared a csv file with the data in it.  Of course we started just with 3-4 dataset to figure it out, if it works or not and if there is a problem and where it could be.

The csv dataset was feeding in the request Body a parameterized JSON structure and of course we had typos and so on. But to figure it out where exactly the problem is, it was hard.
Because if you use Run All, you only see the URL called, but not the body you are sending with data. Also you don't have the possibility to run a single request, with a dataset (at least I don't know how to do it). 
On a single request at least you know what are you doing wrong, because its been logged on the console.

What I would like is:
- give the possibility to run a single request with csv dataset feeded (if better logging possibility is not possible over Run All) or
- give the possibility to run a "Run all" with debug information, that you can see the request you made, with the body and...

**Your Team Size Using TC:**
At the moment 2-8 and if tool is really good we are going to promote this in our company. Approx: >30 User

**Comment by rangav** [comment]
Thanks @CookieMonster70 for the feedback, Will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.7.4`

All the logs enabled now for Run Collection also.

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.7.4

Please let me know your feedback.
