### ISSUE TITLE
why not open-source ?

### ISSUE THREAD

**Issue by samon12321** [rangav/thunder-client-support#1163]
since it's free and non-profit , so why not making it open-source  ?

**Comment by rangav** [comment]
Hi @samon12321 

Currently it free, but we are planning to charge users soon.

We are a startup company for profit.

**Comment by gextenbt** [comment]
@rangav, I am going to switch to Thunder Client, because chained request running here is free. Can I be sure that the basic functionality will remain free?

**Comment by rangav** [comment]
All features will be free - except Git-Sync, which allows you to save requests data to Workspace.
