### ISSUE TITLE
Parameters input inside any called function from custom filters return 0 or empty string ("")

### ISSUE THREAD

**Issue by gextenbt** [rangav/thunder-client-support#1164]
**Describe the bug**
Parameters input inside any called function from custom filters return 0 or empty string ("")

**To Reproduce**
1. Download the custom-filters.txt and set for the collection
2. Assure that "test" function is present in the script
3. Input header in a request (key - value):
- executeCommand - {{@ | test(125)}}
4. Run request

**Actual result**

- Parameters input inside any function return 0 or empty string ("") (not depending on the input value is ("val") or (val))
- Even functions from sample script return 0

![image](https://github.com/rangav/thunder-client-support/assets/97358085/be5617d4-0bc6-4854-ad60-7b7f768303ea)
![image](https://github.com/rangav/thunder-client-support/assets/97358085/bdd8bc44-178f-4824-8dde-5f4f46c1949b)

**Expected result**
Value inside the brackets of function remains as input and is used for a function

**Platform:** 
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Your Team Size Using TC:**
1-2

**Attachments**
[custom-filters.txt](https://github.com/rangav/thunder-client-support/files/11476113/custom-filters.txt)
[tc-types.d.txt](https://github.com/rangav/thunder-client-support/files/11476114/tc-types.d.txt)
[oitchau-integrations-api.postman_collection.txt](https://github.com/rangav/thunder-client-support/files/11476115/oitchau-integrations-api.postman_collection.txt)
[Output.txt](https://github.com/rangav/thunder-client-support/files/11476116/Output.txt)

**Comment by gextenbt** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/97358085/5c0c1dae-d606-4826-b0de-92ebff352a37)

**Comment by rangav** [comment]
Hi @gextenbt 

The filter syntax should be in the below format. the first parameter `input` is result of the previous filter, in this case it is empty.

```js
function test(input, x) {
    console.log("test", x);
    return 2;
}
```

**Comment by gextenbt** [comment]
@rangav, thank you very much! Didn't know I need to use it with input, now everything works perfectly 
Is it written somewhere in doc or is it related specifically to the syntax of JS? I am beginner in JS, so sorry if the question is dull

**Comment by rangav** [comment]
You are welcome.

Here are docs or samples
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by gextenbt** [comment]
@rangav, the problem is that I read it, but at first I've understood from documentation  that it is enough just to use only "input", then I tried to use different parameter, which of course didn't help me.
Maybe it is better to add clarification so others don't get confused

**Comment by rangav** [comment]
Thanks the for the feedback, Will update it.

Or feel free to update any documentation and submit PR.

**Comment by gextenbt** [comment]
I will try to participate )
