### ISSUE TITLE
Thunder Client CLI Log is not working

### ISSUE THREAD

**Issue by CookieMonster70** [rangav/thunder-client-support#1165]
**Describe the bug**
You describe in the help text:
 --log           Log options for request: 0: All Data,  1=ReqHeaders,
                      2=ReqBody, 6=ResHeaders, 7=ResBody, 8=Tests
                      e.g: --log 1,2,7
                     
I tried this now several times, but I get always the same output.

**To Reproduce**
 For e.g. if I start a collection with command:
tc --col mytestcollection
or with the command:
tc --col mytestcollection --log 0
tc --col mytestcollection --log 0,1,7

![image](https://github.com/rangav/thunder-client-support/assets/25148194/3134962e-80cc-4adf-b380-4e12e6a9ef84)

**Expected behavior**
That I see difference in the logs.

**Platform:** 
 - OS: Windows 10
 ` - vscode version: Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
 - extension version: 2.6.1`
- tc cli client: 1.21.0
**Your Team Size Using TC:**
2-10 at the moment

**Comment by rangav** [comment]
Hi @CookieMonster70 Currenly the `log` only works for a single request using `tc reqName` or not for collection.

**Comment by CookieMonster70** [comment]
@rangav are there plans to enhance it?

**Comment by rangav** [comment]
Sure will improve logs and add to roadmap.

As an alternative you can use extension UI to run collection.

**Comment by rangav** [comment]
similar to #1070

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.9.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please let me know your feedback.
