### ISSUE TITLE
Run Collenction only once, but single folder in the collection multiple times

### ISSUE THREAD

**Issue by CookieMonster70** [rangav/thunder-client-support#1167]
**Your Team Size Using TC:**
2-10

**Question:**
For example I have Collection with n tests and this tests are separated with folders. The folders are separated in steps like, post "Upload", get "Verify", delete "Delete Upload". Now I would like to run this single folder several times, with diffrent input, when I run the complete collection.
 
Let say I have the following JSON:
{ 
   description: {{my_input}}
}
and I would like to feed my_input variable form outside. For e.g text with russian chars, chinese chars, numbers, special chars. So that mean this folder has to interate 4 times.

Is this somehow possible?

**Comment by rangav** [comment]
Hi @CookieMonster70 

- Right click on a folder and select `Run All`
- Then you can select input data file and number of iterations
- Now you can run all the request in that folder

Let me know if you have any further questions.

**Comment by CookieMonster70** [comment]
May I you have misunderstood me.
I want to run the main collection and in this collection are, let say 10 folders with request in it. 
Now I would like to run the collection once, but there is one folder with CSV attached and this folder should run multiple times.

For e.g in JUnit you can achive this with 
   @ValueSource(strings = {"Выходные в Санкт-Петербурге", "范例文字 请取代此段落文字"})
    void create_with_differnt_charachters(String description) {
    
  If I let run the collection every test is execute once but this test 2 times.
