### ISSUE TITLE
Operation not Permitted when I use a large csv file after ~ 200 iterations

### ISSUE THREAD

**Issue by CookieMonster70** [rangav/thunder-client-support#1168]
**Describe the bug**
Error in Set Env: EPERM: operation not permitted, rename 'c:\Users\Public\my-tests\thunder-tests\.thunderEnvironment.json.tmp' -> 'c:\Users\Public\my-tests\thunder-tests\thunderEnvironment.json' 

**To Reproduce**
We did run a larger test with one request but with a large csv file. approx 300 datasets (lines) and 15 columns. 
The first run with 300 datasets stop at around 180 execution.
The second run did run smoothly.
The third run did stop at 210 exection. With the error above.

Means it is not alway reproducible :(

**Expected behavior**
A bit mor information would help, do identify the problem :)

**Platform:** 
 - OS: Windows 10 
 - vscode version:  `Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes`
 - extension version: v2.6.1

**Your Team Size Using TC:**
2-10

**Comment by nickidw** [comment]
This seems fixed with VSCode 1.78.2 and extension version 2.7.4, can you test and confirm @CookieMonster70 ?

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
