### ISSUE TITLE
support opening workspace with `*.code-workspace`

### ISSUE THREAD

**Issue by stefaanMLB** [rangav/thunder-client-support#1169]
Use of [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) is not well supported
In [this](https://github.com/stefaanv/fullstack-starter) example project when opening vscode from the root folder, thunder client finds its data files, however when opening the project by double-clicking `fullstack-starter.code-workspace` (as should be done for multi-root support), thunderclient can't find the data files even though the relative location is the same.

**Comment by rangav** [comment]
Thanks @stefaanMLB for the feedback, Will add to roadmap

**Comment by rangav** [comment]
In the next update, we will add support for Multi-root workspaces.

As an alternative solution till then, you can use this setting
https://github.com/rangav/thunder-client-support/blob/master/README.md#2-custom-location

**Comment by rangav** [comment]
- You can load request data from different workspace easily.

<img width="621" alt="Screenshot 2023-07-07 at 17 38 01" src="https://github.com/rangav/thunder-client-support/assets/8637550/b359bd26-8206-47c4-bde2-58de0104d204">
