### ISSUE TITLE
Support NTLM authentication

### ISSUE THREAD

**Issue by heatonnobu** [rangav/thunder-client-support#117]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Could you consider to support NTLM authentication like postman?
![image](https://user-images.githubusercontent.com/2224892/117234003-bdd1dd00-ae56-11eb-9846-eb4e72666d13.png)

**Comment by rangav** [comment]
Hi @heatonnobu will add to roadmap.

**Comment by zornic84** [comment]
Is there an update here?

**Comment by rangav** [comment]
Hi @zornic84, this feature not yet prioritized, Will work on it when I get time, May be next month.

**Comment by rangav** [comment]
I am planning to start development on this, do you have sample `ntlm` url for testing

**Comment by zornic84** [comment]
Hi, no sorry. I've installed only my private windows domain controller

**Comment by rangav** [comment]
Hi All, The feature is now implemented, will be part of next update

**Comment by zornic84** [comment]
Nice, when will the next update come?

**Comment by rangav** [comment]
it will be next week.

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0, The feature is still in BETA, so let me know if you have any issues
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Comment by zornic84** [comment]
Hi rangav,

good work, I just tested it successfully. now it would be cool to be able to import the requests from Postman :-D

Many greetings

**Comment by rangav** [comment]
Thanks @zornic84 for confirming 👍

The extension now also imports the ntlm auth details from Postman exported json file.

**Comment by samgao001** [comment]
NTLM doesn't seem to work for me. I got `401 - Unauthorized: Access is denied due to invalid credentials.`

This same credential works fine in Chrome and Postman.

**Comment by samgao001** [comment]
@rangav 
I can't share that screenshot. (confidentiality issue) 
response from the request comes with 

```
header: Server Error
Content: 401 - Unauthorized: Access is denied due to invalid credentials. You do not have permission to view this directory or page using the credentials that your supplied.
```

Request is sent with default headers and NTLM authentication with username and password that worked in Chrome and Postman.

**Comment by rangav** [comment]
are you using the the `domain` and `workstation` values also?

**Comment by samgao001** [comment]
@rangav those are left blank (did the same with Postman request)

**Comment by rangav** [comment]
I will check if there is anything can be done in the code, if there is a way to re-produce this issue, then it will be easy for me to test.

Are you sending GET or POST request?

**Comment by samgao001** [comment]
it was GET request
