### ISSUE TITLE
Collections: drag and drop

### ISSUE THREAD

**Issue by ewan-chalmers** [rangav/thunder-client-support#1174]
This is two feature requests

1. Multi-select of requests in collections, to allow move of multiple items at once (e.g. to another folder)
2. Drag and drop of folder into folder
  - This doesn't seem to be allowed currently
  - You can create folder within folder, but not drag folder into folder

**Comment by rangav** [comment]
Hi @ewan-chalmers Thanks for the feedback. Will review about feature request 1

The drag and drop folder to another folder is already supported. Please try again

**Comment by rangav** [comment]
Not planning this feature
