### ISSUE TITLE
Activity Not Updated When Using APIs from Collections

### ISSUE THREAD

**Issue by mikebuchanon** [rangav/thunder-client-support#1176]
I may be misunderstanding what the Activity tab is for, but when I run a query from a collection the fact that I ran a query is not showing up on the Activity tab.   This makes it harder to get back to what I was doing if I have to step away/switch context.  Which in turn makes it harder to build new collections to run tests with by using the "save/add to collection" option only available on the Activity tab.

To reproduce:
1) create a collection
2) setup an environment
3) run API queries from the collection
4) view activity tab --- see nothing you've run from #3 on the tab

This is with Thunder Client v 2.7.0 in VS Code.

Thanks!

PS: Love Thunder Client!  Thanks for all your hard work and for sharing with the VS Code community!

**Comment by rangav** [comment]
Hi @mikebuchanon, you need to enable below vscode setting

![image](https://github.com/rangav/thunder-client-support/assets/8637550/f354d379-288d-4506-b0fa-aef5c28249a2)

**Comment by mikebuchanon** [comment]
Well now I feel extra special for not seeing that in the settings.   Thank you again!

**Comment by rangav** [comment]
You are welcome
