### ISSUE TITLE
Setting Date Variables via Custom Script

### ISSUE THREAD

**Issue by jandreaucodes** [rangav/thunder-client-support#1178]
**Your Team Size Using TC:**
1
**Question:**
I'm trying to use a custom Script to set some variables upon execution.

The script is 
`function generateDates() {
    var moment = await tc.loadModule("moment");
    tc.setVar("timestamp_5_mins_ago", moment().utc().subtract(5, 'minute'));
    tc.setVar("plus_one_day", moment().utc().add(1, 'day').format('YYYY-MM-DD'));
    tc.setVar("plus_three_days", moment().utc().add(3, 'day').format('YYYY-MM-DD'));
    tc.setVar("same_day", moment().utc().format('YYYY-MM-DD'));
    tc.setVar("minus_one_day", moment().utc().subtract(1, 'day'));
    tc.setVar("minus_two_days", moment().utc().subtract(2, 'day'));
    tc.setVar("minus_three_days", moment().utc().subtract(3, 'day'));
}

module.exports = [generateDates]`

Then, in the Collection settings I have the Pre Option set to that Filter (generateDates), but the variables never get set.

**Comment by rangav** [comment]
Thanks @jandreaucodes for reporting the bug, will look into it.

**Comment by rangav** [comment]
The issue could be function is missing `async` keyword

`async function generateDates()`

**Comment by jandreaucodes** [comment]
Added `async`, but still not working.

It should be updating the variable on the environment currently set, right?
