### ISSUE TITLE
GUI for adding a certificate

### ISSUE THREAD

**Issue by TWEagle** [rangav/thunder-client-support#1179]
**Your Team Size Using TC:**
10

**Question:**
We are using the API calls for the Signing Hub

But we have a datapower infrastructure between the systems.

So we need to add a certificate to connect to the service.

But I don't kinda understand the information, that is why I wanted to ask if it is possible to add it in the setting from VS code itself with a simpel drag drop or select file thing?

**Comment by rangav** [comment]
Hi @TWEagle we already have a vscode setting for this.

Please see the details below
https://github.com/rangav/thunder-client-support#manual-ssl-certificates

**Comment by TWEagle** [comment]
Dear @rangav 

I have this setting in postman:
![image](https://github.com/rangav/thunder-client-support/assets/6324797/2baa673b-7f46-4c2f-9dd6-a2eea6c7ad69)

And I have setup this in the settingspage:

    "thunder-client.certificates": [
    
        {
            "host": "https://handtekenmapapi.vlaanderen.be/",
            "pfxPath": "/C:/cert/dhm-prod.p12",
            "passphrase": ""
        },
        {
            "host": "https://handtekenmapapi-ti.vlaanderen.be/",
            "pfxPath": "/cert/dhm-ti.p12",
            "passphrase": ""
        },
        {
            "host": "https://handtekenmapapi-ti.vlaanderen.be/",
            "pfxPath": "/cert/ilvo.crt",
            "passphrase": ""
        }
    ],

What do I do wrong :S

**Comment by rangav** [comment]
Currently not planning to implement this
