### ISSUE TITLE
Segregate the postman imported collection into folders

### ISSUE THREAD

**Issue by avinash-tiwari** [rangav/thunder-client-support#118]
A nice extension to use while getting rid of Postman completely. Just One feature is missing, I am not able to have the Postman collection imported into a folder structure. I have imported a Postman collection with almost 400 requests and they are organized in folders, When imported in thunder client, all of them were separate requests.

**Comment by rangav** [comment]
Hi please update the extension to v1.2.0. It should work.

this is duplicate issue of #96, please add your comments there.
