### ISSUE TITLE
Precedence of environment variables

### ISSUE THREAD

**Issue by CharlieSnowCode** [rangav/thunder-client-support#1180]
In the documentation, it states that the precedence of environments is (lowest to highest):
Environment
Global
Local
.env file
I have created a variable with the same name at each level and see the value and where it's coming from when I hover over it in this context {{newValue}}. But it is using the "active environment" first (I expected .env or local).
I remove that variable from the active environment and see it's now using the local version (not what I expected either).

Also, when I retrieve the variable from a custom script like
let newValue = tc.getVar('newValue'); console.log("## newValue: " + newValue);
I see it using the 'local' version when it's defined at all 4 levels.
If I remove the local value, it uses the 'global' one.

Also for these experiments, the .env file is linked to the Global Env.

Thank you.

 - OS: windows 10
 - vscode version: 1.78.2
 - extension version: 2.7.3

**Your Team Size Using TC:**
4

**Comment by rangav** [comment]
Hi @CharlieSnowCode The active environment will take precedence over `.env` file as mentioned in documentation.

> ![image](https://github.com/rangav/thunder-client-support/assets/8637550/e836742e-2cb9-4532-937b-af998d4183f0)

**Comment by rangav** [comment]
It shouldn't be working like that. Could be a bug, Will verify and get back to you.

**Comment by rangav** [comment]
I just now tested it, the value is coming from `Active` environment.

Can you check names and make sure the `active` env correctly set

**Comment by rangav** [comment]
Are you still having issue?

I am closing this, feel free to reopen if the issue still not resolved
