### ISSUE TITLE
Multiple request with same name

### ISSUE THREAD

**Issue by Mmartos13** [rangav/thunder-client-support#1183]
**Your Team Size Using TC:**
10

**Question:**

Hello @rangav 
Our team have a question about how to manage the cli. We need to run 2 requests with the same name that are located on different folders. Is there any way of made it using tc2 cli?

![image](https://github.com/rangav/thunder-client-support/assets/73356168/0f9dfce5-4f08-4be7-bbe0-2780e913da96)

Here you have an example of our thunder client structure, we would like to run both 'get entities' requests.

**Comment by rangav** [comment]
Hi @Mmartos13 You can use `id's` of both requests

To see ids of requests in collection 
- `tc list 'colName'`

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
