### ISSUE TITLE
Send Multiple payloads for testing all together instead of creating multiple requests

### ISSUE THREAD

**Issue by saibhaskerraju** [rangav/thunder-client-support#1185]
As of now, we have to create separate requests for testing the same API with different payloads. Is it possible for us to send different payloads as batch or something so that all tests written are applied at one go.

**Comment by rangav** [comment]
Hi @saibhaskerraju 

you can use Run Collection and select input data file with different values for variables.

**Comment by manohjRM** [comment]
Hi @rangav, I tried to add csv file to run multiple payloads using Collections. Still my APIs are fetching data from environmental variables. Can you please help me with the steps to proceed further?

**Comment by rangav** [comment]
Hi @manohjRM 

can you share a sample csv file to verify its in correct format.

the first row should be exact names of variables

**Comment by rangav** [comment]
I am closing this issue feel free reopen if needed.
