### ISSUE TITLE
NTLM Auth does not add --ntlm flag to curl request

### ISSUE THREAD

**Issue by marc-wittwer** [rangav/thunder-client-support#1186]
**Describe the bug**
When setting up a request using NTLM Auth, the generated curl request does not add the NTLM Auth flag `--ntlm`.

The following flag should be added to the curl command:
`--ntlm -u "domain\\username:password"`

**To Reproduce**
1. Add request with NTLM Auth (Domain, Username, Password)
2. Open the curl request exporter of the thunder client
3. The curl request has no `--ntlm` flag

**Expected behavior**
3. The curl request should have a `--ntlm` flag

**Platform:** 
 - OS: Mac
 - vscode version: 1.78.2 (Universal)
 - extension version: v2.7.3

**Your Team Size Using TC:**
Our team is currently looking for a new http client for testing. Teamsize: 10

**Comment by rangav** [comment]
Thanks @marc-wittwer for the feedback, will fix it asap.

**Comment by marc-wittwer** [comment]
Perfect it works, thanks.

**Comment by rangav** [comment]
Thanks for confirmation 👍
