### ISSUE TITLE
CLI not working against workspace with Git sync

### ISSUE THREAD

**Issue by norelina** [rangav/thunder-client-support#1188]
**Describe the bug**
Although Git Sync is configured and working as expected, the CLI seems to be pointing to the local files (as if workspace scope is not set)

**To Reproduce**

1. Configure VS Code settings to enable Thunder Client Git sync: 
     ```
      {
        "thunder-client.saveToWorkspace": true,
        "thunder-client.workspaceRelativePath": "src/thunder-client"
      }
     ``` 
2. Create a Collection and Env 
3. Confirm Git sync works and that the thunder-tests directory and thunder client files are created under the specified relative path
4. Install the CLI
     `npm i -g @thunderclient/cli`
5. Execute
     `tc --col all`

**Expected behavior**
To list all the requests from all my collections in my repo

**Actual behavior**
Instead, all the requests from all my collections in my local (%APPDATA%\Code\User\globalStorage\rangav.vscode-thunder-client

**Platform:** 
 - OS: Windows
 - vscode version: 1.78.2
 - extension version: latest

**Your Team Size Using TC:**
5 to be extended across teams if can confirm we can use the CLI in our CICD pipelines

**Comment by rangav** [comment]
Thanks @norelina for reporting the bug, will look into it.

**Few questions:**

- Can you make sure the TC settings are added to `.vscode/settings.json` file in your project
- The cli command should run from root of the project?


Can you please confirm above 2 points?

**Comment by norelina** [comment]
@rangav thank you so much for your prompt response. That was it! When I ran the cli command **from the root of the project** I was able to get the workspace collections! Thank you so much!! (did I miss that in the docs/medium blog?)

**Comment by rangav** [comment]
Thanks @norelina for confirmation.

I don't think it is mentioned in the docs here
https://rangav.medium.com/thunder-client-cli-a-new-way-to-test-apis-inside-vscode-d91eb5c71d8e

Will add this point clearly to the docs now

let me know if you have any further questions

**Comment by norelina** [comment]
Thank you @rangav!

**Comment by rangav** [comment]
@norelina 

FYI - We have another argument/flag that is useful in some use cases 

If you need to run commands from a different directory instead of root directory then you use `--ws` argument to specify the path to the root direct.

- `--ws 'fullpathToGitWorkspace'`

**Comment by norelina** [comment]
> @norelina
> 
> FYI - We have another argument/flag that is useful in some use cases
> 
> If you need to run commands from a different directory instead of root directory then you use `--ws` argument to specify the path to the root direct.
> 
> * `--ws 'fullpathToGitWorkspace'`

Thank you @rangav! This is what we need. We will test and use this argument.
