### ISSUE TITLE
Display query parameters, headers, and body at the same time

### ISSUE THREAD

**Issue by aoyama-val** [rangav/thunder-client-support#1189]
**Please describe feature/problem details and solution you'd like.**
Currently, we need to switch `Query` `Headers` `Body` panes to set them. This is a bit bother when dealing with an API which requires both parameters and request body. It would be great if the three panes are displayed at the same time like this:

![layout](https://github.com/rangav/thunder-client-support/assets/13144822/dbbbf175-052b-452b-b01a-25e921883ab8)

We would be able to check the content of the request at a glance.
It would be better if the heights of the panes could be changed with dragging.
Today a lot of us are using large enough display, so they will benefit. 

**Describe alternatives you've considered**

**Your Team Size Using TC:**
1

**Comment by rangav** [comment]
Thanks @aoyama-val for the feedback, Will review it.

**Comment by rangav** [comment]
Hi @aoyama-val 

I'm sorry I have to decline this feature, won't implement it because it will complicate the UI.
