### ISSUE TITLE
Unable to import from postman

### ISSUE THREAD

**Issue by castrix** [rangav/thunder-client-support#119]
**Describe the bug**
following to the issue #96, I tried to reproduce the error, here is the postman collection that result in the same problem

**To Reproduce**
import this collection
[reproduce.postman_collection.zip](https://github.com/rangav/thunder-client-support/files/6431859/reproduce.postman_collection.zip)

**Expected behavior**
the collection imported

**Platform:** 
 - OS: Debian 10

**Comment by rangav** [comment]
Hi @castrix  please use the previous issue to continue discussion, no need of separate issue.
