### ISSUE TITLE
 Enhanced History Storage for Recent URLs/Endpoints in Thunder Client

### ISSUE THREAD

**Issue by inavinprince** [rangav/thunder-client-support#1192]
Feature Request: Enhanced History Storage for Recent URLs/Endpoints in Thunder Client

Description:
As an avid user of Thunder Client, I would like to suggest a valuable feature that could significantly improve my workflow and productivity. Currently, Thunder Client provides a powerful platform for testing APIs and making HTTP requests, which has proven to be immensely helpful. However, I often find myself needing to recall and reuse previously tested URLs or endpoints, which becomes cumbersome when there is no built-in history storage mechanism.

To address this issue, I propose the implementation of an enhanced history storage feature in Thunder Client. This feature would aim to store a record of the most recently used URLs or endpoints, allowing users to easily access and reuse them without the need for manual copying or pasting.

The benefits of this feature would be manifold. Firstly, it would save considerable time and effort by eliminating the need to type or search for previously tested URLs or endpoints, particularly when working on complex API projects that involve numerous requests. Additionally, it would reduce the chances of human error that may arise from manual input, ensuring the accuracy and consistency of the URLs or endpoints used in subsequent tests.

Ideally, the enhanced history storage feature would function seamlessly within the Thunder Client interface. It could be incorporated as a collapsible sidebar panel, prominently displaying a chronological list of the most recently used URLs or endpoints. Each entry in the list could include the full URL or endpoint, along with an optional user-defined label or description for easier identification. Clicking on an entry would automatically populate the request field with the selected URL or endpoint, ready for further modifications or testing.

To further enhance the user experience, it would be advantageous to include additional functionality within the history storage feature. Users could be provided with the ability to star or bookmark specific entries, marking them as favorites for quick access in the future. Furthermore, a search functionality could be implemented, enabling users to swiftly locate specific URLs or endpoints within the extensive history.

Overall, the inclusion of an enhanced history storage feature in Thunder Client would greatly streamline API testing workflows and improve efficiency for developers and testers alike. By eliminating the need to manually remember, search, or copy previously tested URLs or endpoints, users can focus more on the task at hand and deliver high-quality API implementations.

**Describe alternatives you've considered**
or you might just include notes section where I can just keep multiple endpoints to copy or to switch between them

**Your Team Size Using TC:**
for now 5-10

**Comment by rangav** [comment]
Thanks @inavinprince for taking time to provide detailed feedback, thats a very good suggestion.

Will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
