### ISSUE TITLE
Can't refer to {{message}} in headers

### ISSUE THREAD

**Issue by dshahin** [rangav/thunder-client-support#1193]
**Describe the bug**
The doc screenshots show filter syntax like `{{message|customHmac}}` but {{message}} does not seem to be referenced.

**To Reproduce**
add a filter `{{message}}`
the header does not turn green indicating a successful reference, and when I send, it is just `{{message}`

**Expected behavior**
I would like to be able to pipe the message body through a custom filter (MD5sum of secret token + message body) to generate a  signature in a header

**Platform:** 
 - OS: MacOS
 - vscode version:1.78.2
 - extension version:2.7.5

**Your Team Size Using TC:**
1

**Comment by rangav** [comment]
Hi @dshahin thanks for reporting the bug.

did you create custom filter first as described in the docs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
