### ISSUE TITLE
Autofill option for environment variables when creating requests

### ISSUE THREAD

**Issue by harjoben** [rangav/thunder-client-support#1194]
**Please describe feature/problem details and solution you'd like.**
It would be great if there could be a way to select environment variable in a request without having to type the full name. This would be great for environments with a huge number of variables that may or not be used in a regular basis. Instead of trying to find the variable in the environment's page and copy pasting it in, maybe there can be an option to search for it in the request page itself. 

For example, Postman achieves this by showing a drop-down of available variables once you type `{{`. The list searches dynamically as you type

**Describe alternatives you've considered**
I tried to find any documentation and previous issues around this, but couldn't find any. 

**Your Team Size Using TC:**
Roughly around 50

**Comment by rangav** [comment]
similar to #151
