### ISSUE TITLE
Feature: Import curl request

### ISSUE THREAD

**Issue by Rishang** [rangav/thunder-client-support#1195]
**Please describe feature/problem details and solution you'd like.**
There can be an option added like import from curl request.

This is because let say, we do some debuging via browser, we do copy request as curl from, then simly import that request to thunder, and it will cofigure paramaters of request accordingly

**Comment by rangav** [comment]
Hi @Rishang 

This feature is already available 

see details 
https://github.com/rangav/thunder-client-support#import-curl

**Comment by Rishang** [comment]
Thanks sorry i was not able to find it, thankyou anyway for making this tool :)

**Comment by Rishang** [comment]
Closing it
