### ISSUE TITLE
Ignore TLS Errors?

### ISSUE THREAD

**Issue by coreyogburn** [rangav/thunder-client-support#1196]
**Your Team Size Using TC:**
1

**Question:**
I want to test my API that's running over HTTPS and running with a self signed certificate. However every request, regardless of content or endpoint, results in the following output in the response window and my API shows no signs of receiving a request:

```
write EPROTO 66142498327176:error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT:../../third_party/boringssl/src/ssl/ssl_cert.cc:607:
```

I've tried adding the cert and key but don't see any change. Is there a way to ignore this error and continue with the request?

**Comment by rangav** [comment]
Hi @coreyogburn we already enabled ignore ssl errors.

- Are you using latest version of extension?
- Is it localhost url?

you can also change request library to `axios` in TC settings and test?

**Comment by coreyogburn** [comment]
1. I'm running v2.7.6 of the extension.
2. I'm using a hostname with an /etc/hosts entry that directs it to 127.0.0.1 (necessary for my tech stack)
3. Switching to axios prints the same error output.

**Comment by rangav** [comment]
Good you got it working.

I am closing this issue, feel free to re-open it if needed

**Comment by coreyogburn** [comment]
But the issue is still open? What if I was in a situation where I couldn't modify the server config? Is the bug not to ignore TLS errors?

**Comment by rangav** [comment]
I have already enabled Axios to ignore the SSL error, not sure what is causing this error.

You may try to create a sample node project and use Axios and test yourself.

Let me know the result.

Here sample axios code
```js
const agent = new https.Agent({  
  rejectUnauthorized: false
});
axios.get('https://something.com/foo', { httpsAgent: agent });
```

**Comment by rangav** [comment]
Are you still facing this issue in version `2.10.2`?
