### ISSUE TITLE
Allow manual rezising of columns

### ISSUE THREAD

**Issue by dk5ax** [rangav/thunder-client-support#1197]
**Please describe feature/problem details and solution you'd like.**

As shown in the picture below, you could think of some better choice of column widths. 
However, it is not possible to resize them. 
<img width="490" alt="image" src="https://github.com/rangav/thunder-client-support/assets/28004762/b5a5f4e9-abd7-4cc9-aa1e-9eab393abec5">

**Describe alternatives you've considered**

Clicking in the field to entirely access it or changing the overall windows size.....

**Your Team Size Using TC:**

5-10

**Comment by rangav** [comment]
Alternative solution

You can reduce the width of response section
![image](https://github.com/rangav/thunder-client-support/assets/8637550/2d2a6714-5ee7-41a3-bc18-98383aa07fd9)

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to v2.7.7

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.7.7

Please let me know your feedback.
