### ISSUE TITLE
Request keeps spinning

### ISSUE THREAD

**Issue by sathishk3** [rangav/thunder-client-support#120]
**Describe the bug**

I am initiating the Post https call with api key auth header, but the request is keeps spinning and the cancel request is not working. Its happing for all my request. Any specific VSCode settings required?

Here is the screenshot

![image](https://user-images.githubusercontent.com/47175460/117251798-bfa19d80-ae62-11eb-81a9-7fecfd50d421.png)

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 

**Solution:**

**Comment by rangav** [comment]
Hi @sathishk3 thanks for reporting. May there is some error I am not catching, I am trying to fix this in the next update, that I will be released today.

**Comment by oherik** [comment]
I have the same issue. I think it happened because I stopped the server while the request was being sent, but I am not sure. Now no request can be sent, at least not to my local server, even if I restart my computer.

OS:  MacOS Big Sur 11.2.3 
VSCode version: 1.56

**Comment by rangav** [comment]
Hi @oherik can try closing and re-open vscode and try this url https://www.thunderclient.io/welcome

**Comment by oherik** [comment]
@rangav Still the same issue, I'm afraid. "Cancel Request" is not responding.

![Screenshot 2021-05-06 at 09 53 06](https://user-images.githubusercontent.com/10709871/117261815-ddfe9d80-ae50-11eb-91d8-42c86661c514.png)

**Comment by rangav** [comment]
did you update vscode to latest and extension to latest and try

**Comment by oherik** [comment]
Yes, I have the latest version of both. I also tried uninstalling the extension and installing it again, but I got the same issue (I assume since all my settings were still there after reinstalling).

**Comment by rangav** [comment]
thats strange, i am releasing a new update today, let see if that will fix the issue or not.

**Comment by rangav** [comment]
this is fixed in v1.2.1 details here https://github.com/rangav/thunder-client-support/releases/tag/1.2.1

Feel free to re-open if issue still persists.

**Comment by oherik** [comment]
Yes, now it seems to work again. Thanks @rangav for the quick fix, and for creating this extension! 🙏
