### ISSUE TITLE
Not abel to sync the thunder client requests in the shared repo

### ISSUE THREAD

**Issue by myishay** [rangav/thunder-client-support#1200]
**Your Team Size Using TC:**
7

**Question:**
We have been using Thunder Client for quite a while now, and lately we had some issues with syncing the requests in our shared repo.
Any tips regarding this issue?

**Comment by rangav** [comment]
Hi @myishay 

We launched subscriptions for businesses to use the [Team Features](https://github.com/rangav/thunder-client-support#git-sync).

You should still be able to sync with the git repo till `August 18th, 2023` without a subscription.

Read Announcement here
https://github.com/rangav/thunder-client-support/releases/tag/v2.7.0
