### ISSUE TITLE
Add a "sync UI to source code" button

### ISSUE THREAD

**Issue by royhadad** [rangav/thunder-client-support#1201]
**Please describe feature/problem details and solution you'd like.**
I'm experiencing a diff between my source code requests and the Thunder client UI, clicking the "Git Sync" button or the "reload" button does not help with that.
I'm currently fixing it by re-opening my VS code, which is cumbersome.
The solution I'm suggesting is adding a "Sync UI to source code" button, that will reset Thunder client UI to the state of my code.

**Describe alternatives you've considered**
There can also be a request-scoped button for this functionality, I feel the 1 global button will be sufficient though. 

**Your Team Size Using TC:**
7

**Comment by rangav** [comment]
Thanks @royhadad for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.9.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

### How it works
- When you pull changes from git, all the UI request views are reloaded with new data automatically.
- You can click also reload icon on the top of the sidebar ( No need for this generally)

Please let me know your feedback.
