### ISSUE TITLE
Auth: Include origin in 'refresh' request Header

### ISSUE THREAD

**Issue by Ztarbox** [rangav/thunder-client-support#1203]
**Please describe feature/problem details and solution you'd like.**
To authenticate against Azure AD when using SPA-Settings for redrect uri, it is required to include "origin" in the request header.
For getting the token, this is already implemented.
But for the refresh flow, the origin setting is ignored.

This results in my case in a `AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests` error.

To verify this, I copied the refresh request from the output into a new request and added the origin header and it worked. Without it, I get the same error as reported in the output.

**Describe alternatives you've considered**
None

**Your Team Size Using TC:**
7 People, but I assume, everyone using Azure AD with the same configuration.

**Comment by rangav** [comment]
Hi @Ztarbox 

We already support this, please see image below
<img width="768" alt="Screenshot 2023-06-19 at 10 48 41" src="https://github.com/rangav/thunder-client-support/assets/8637550/554e8051-fc9c-443a-a80f-6f8f2bfb45f1">

**Comment by Ztarbox** [comment]
Hi @rangav ,
yeah but in my case it isn't used in the refresh flow, just for getting the access_token.

So it is probably a bug?

**Comment by rangav** [comment]
Ok maybe a bug, Do you want the origin to be included in the refresh_token request too?

**Comment by Ztarbox** [comment]
To show my output:

get the token:
```
OAuth2 TokenUrl Request: https://login.microsoftonline.com/[...]/oauth2/v2.0/token
Request Method: POST
Request Headers:
{
  "Accept": "application/json",
  "Content-Type": "application/x-www-form-urlencoded",
  "Origin": "https://www.thunderclient.com"
}
Request Body:
grant_type=authorization_code&code=[...]&redirect_uri=https%3A%2F%2Fwww.thunderclient.com%2Foauth%2Fcallback&client_id=[...]&code_verifier=[...]&audience=[...]

OAuth Response:
{
  "token_type": "Bearer",
  "scope": "[...]",
  "expires_in": 4685,
  "ext_expires_in": 4685,
  "access_token": "[...]"
}

```
refresh:
```
OAuth2 Refresh Token Request: https://login.microsoftonline.com/[...]/oauth2/v2.0/token
Request Method: POST
Request Headers:
{
  "Content-Type": "application/x-www-form-urlencoded"
}
Request Body:
grant_type=refresh_token&refresh_token=[...]&audience=[...]&scope=[...]&client_id=[...]&client_secret=

OAuth Response:
{
  "error": "invalid_request",
  "error_description": "AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\nTrace ID: ...\r\nCorrelation ID: ...\r\nTimestamp: 2023-06-19 09:29:28Z",
  "error_codes": [
    9002327
  ],
  "timestamp": "2023-06-19 09:29:28Z",
  "trace_id": "...",
  "correlation_id": "..."
}
```

**Comment by Ztarbox** [comment]
> Ok, Do you want the origin to be included in the refresh_token request too?

yes, that would be greate!

**Comment by rangav** [comment]
Ok, I got it, I'll include it in the refresh request too in the next update.

**Comment by Ztarbox** [comment]
Thanks!

**Comment by rangav** [comment]
This feature is now implemented and published to the marketplace, please update to `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.

**Comment by Ztarbox** [comment]
works perfectly.
Thanks!

**Comment by rangav** [comment]
Thanks for confirmation 👍
