### ISSUE TITLE
Clear Activity button doesn't work

### ISSUE THREAD

**Issue by TRENWAR** [rangav/thunder-client-support#1204]
**Describe the bug**
Clear activity button doesnt do its job

**To Reproduce**
Click Clear Activity button

**Expected behavior**
Clear activies

**Platform:** 
 - OS: Linux Mint
 - vscode version: v1.79.2
 - extension version: v2.7.7

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
