### ISSUE TITLE
How to pass a JSON property from Request A to Request B

### ISSUE THREAD

**Issue by vvazdeveloper** [rangav/thunder-client-support#1207]
I have a sequence of 4 requests. Req_A, Req_B, Req_C, and Req_D. All 4 requests have a JSON format on their request body.
How can I pass the same value from the property called  "TransactionTraceNumber" from the Req_A, generated randomly as shown below, to the Req_B ?

The examples below, **Req_A** and **Req_B** are for Payload "**Request**" Body and not for the "**Response**" Body.

"Req_A" -  Request Body:
{
    "TransferAccountFrom": "123456",
    "TransferAccountTo": "78910",
    "TransferAmount": "20.00",
    "TransactionTraceNumber": "18948561315"
}

"Req_B" - Request Body:
{
    "DebtorAccount": "123456",
    "CreditorAccount": "78910",
    "TransferAmount": "20.00",
    "TransactionTraceNumber": "TransactionTraceNumber from Req_A"
}

**Comment by rangav** [comment]
Hi @vvazdeveloper 

- From the Tests tab select `Set Env Variable` option
- then you save the response data variable to the environment variable
- Then use the env variable value in other requests using `{{traceNumber}}`

<img width="1205" alt="Screenshot 2023-06-23 at 05 58 50" src="https://github.com/rangav/thunder-client-support/assets/8637550/b97b4a48-5f7b-42ef-b4b7-ec5d8784f421">

**Comment by vvazdeveloper** [comment]
Hi @rangav,
That's the problem that I am facing now. My **response** body from Req_A does not have the property called  "TransactionTraceNumber" available at all. The property "TransactionTraceNumber" is only available in the **Request Body** for the Req_A. I am trying to pass the property value "TransactionTraceNumber" from the payload request body available in the "Req_A" over to the payload request body in the "Req_B". 
If I try to consume in the "Req_B" the same variable, {{transactionTraceNumber}}, that was previously created to generate a randon number for the "Req_A", it is giving me an empty string.

**Comment by rangav** [comment]
Sorry, I misunderstood the question.

How do you generate the random value of `TransactionTraceNumber` for request A?

**Comment by rangav** [comment]
You can use scripting to generate random value and also save to env variable.
- Scripting docs here https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

example:
```json
{
"TransferAccountFrom": "123456",
"TransferAccountTo": "78910",
"TransferAmount": "20.00",
"TransactionTraceNumber": "{{traceNumber}}"
}
```

**Comment by vvazdeveloper** [comment]
No, let me get it clarified.

Once I generate a random value for the property called  "TransactionTraceNumber" on the "Req_A" and save into the env variable called {{traceNumber}}, how can I get the same value used on the variable {{traceNumber}} on the step "Req_A", so that I can use this same value on the next request, Req_B?
My "Req_B" also requires "TransactionTraceNumber" but it needs to be the "same value" that was generated and provided in the previous request which is the "Req_A". Does it make sense?

**Comment by rangav** [comment]
If you run the script using Pre Req Script, then saving the data to the env variable is also available to request A and all other subsequent requests.

<img width="781" alt="Screenshot 2023-06-23 at 14 27 51" src="https://github.com/rangav/thunder-client-support/assets/8637550/eb3bd91b-5b55-4197-a6b9-3946cf9fdead">

- Then you can use the below in the body of request A
```json
{
"TransferAccountFrom": "123456",
"TransferAccountTo": "78910",
"TransferAmount": "20.00",
"TransactionTraceNumber": "{{traceNumber}}"
}
```

**Comment by vvazdeveloper** [comment]
Thank you so much for your quick answer. Much appreciated!
I already tried this way and it did not work for me. Let me try it again and I will let you know in a few.

**Comment by rangav** [comment]
You can use the echo endpoint to test data - https://www.thunderclient.com/t/echo

<img width="1285" alt="Screenshot 2023-06-23 at 14 43 28" src="https://github.com/rangav/thunder-client-support/assets/8637550/862554d2-8080-4d83-86ab-5b8e8f286fe4">

**Comment by vvazdeveloper** [comment]
@rangav,
I tried the way you had mentioned above; however, after I submitted the "Req A", it does not save the value of {{tarceNumber}} generated in the "Req A" that I can use it same value in the request "Req B".

1- I have an environemnt called "Test"
2- In the environment called "Test" I have an empty variable called "traceNumber"
3- In my "Req_A" payload request body JSON, I set as shown below: 
    
    "TransactionTraceNumber": "{{traceNumber | transactionTraceNumber}}"

Where:   

"traceNumber" is located under Env Test
"transactionTraceNumber" is my function poiting to the scpript.js file available under my collection folder.

4- Under the "Req_A" Pre Run tab I don't have anything setup.

5- Under the "Req_B" Pre Run tab I do have the following:

Pre requests:  "Req_A" / Condition = Run Always
Pre Options:  Select Pre Filter = transactionTraceNumber

But once I run "Req_A" it generates a random traceNumber; however, when I run the "Req_B" it generates a second random number completely different than the first one that I need to provide in the "Req_B".

**Comment by rangav** [comment]
`{{traceNumber | transactionTraceNumber}}` using this format will not save the value to the env variable.

You need to use Pre Req filter, see example in image below
<img width="1392" alt="Screenshot 2023-06-23 at 17 30 50" src="https://github.com/rangav/thunder-client-support/assets/8637550/220596c3-a8a2-4a76-be7f-162ba3e44744">

In Body use below
```json
{
"TransferAccountFrom": "123456",
"TransferAccountTo": "78910",
"TransferAmount": "20.00",
"TransactionTraceNumber": "{{traceNumber}}"
}
```

**Comment by rangav** [comment]
Can you share your sample script file here, I will verify the script. you can remove any sensitive code

**Comment by rangav** [comment]
I just now tested its working for me. 

Did you set `Test` environment as **Active**?

**Comment by vvazdeveloper** [comment]
> I just now tested its working for me.
> 
> Did you set `Test` environment as **Active**?

Yes, I did.

**Comment by rangav** [comment]
can you use this simple script in your js file and attach it to a collection? Can you test with below script and let me know

```js
function transactionTraceNumber() {
    var randonValue = "57675677";
    tc.setVar("traceNumber", randonValue);
}


module.exports = [transactionTraceNumber];
```

**Comment by vvazdeveloper** [comment]
I got this issue resolved. It is working now as expected.
Thank you very much!

**Comment by rangav** [comment]
Thanks for confirmation 👍
