### ISSUE TITLE
Thunder Client - Not loading collections

### ISSUE THREAD

**Issue by vvazdeveloper** [rangav/thunder-client-support#1210]
**Describe the bug**
The Thunder Client is not loading all my collections that I was working on. 
I closed Visual Studio Code and re-opened and cannot get the collections that I was working on loaded.
I checked for any existing updates and everything is currently updated. 
I got Thunder Client uninstalled and re-installed but the issue is still on going.
I contacted my manager and he is experiencing the same issue. 
We are running it on Windows 11 Pro and no updates are pending. Neither Visual Studio Code.
My machine was re-booted and the issue is still going on.

Any idea?

**Comment by rangav** [comment]
Hi @vvazdeveloper 

we will help in resolving the issue.

where is your data saved? Is it in current workspace or default location?

**Comment by vvazdeveloper** [comment]
I had it saved locally on my machine and when I attempt to go to File/Open Workspace from file... and point to the folder where the following files reside, I select "thunder-tests.code-workspace" but nothing gets loaded.
Follow below the files available within the folder:

- thunder-tests.code-workspace  ( I am selecting this one)
- thunderEnvironment.json
- thunderCollection.json
- thunderclient.json
- thunderActivity.json

**Comment by rangav** [comment]
You did not answer question clearly?

is it saved in default location or in your git project?

**Comment by vvazdeveloper** [comment]
In the default location , Sir.

**Comment by rangav** [comment]
Thanks for confirmation.

then could some setting issue.

Are you using `Workspace relative path` setting, may be this setting value is not set properly.

**Comment by vvazdeveloper** [comment]
We got it fixed. Somehow, it was pointing to the wrong workspace folder. How it got switched to the incorrect folder is unknown. But now it is working as expected.

**Comment by rangav** [comment]
Good you got it working finally 👍
