### ISSUE TITLE
OpenAPI import does not support .yml file extension

### ISSUE THREAD

**Issue by theoutsider24** [rangav/thunder-client-support#1212]
**Describe the bug**
Importing an openAPI with a .yml extension does not work but importing the same file renamed to .yaml does work
These extensions should be considered interchangeable

**To Reproduce**
Rename a valid .yaml openAPI file to .yml and attempt to import

**Expected behavior**
The file is imported successfully

**Platform:** 
 - OS: MacOS
 - vscode version: 1.79.2
 - extension version: 2.8.3

**Your Team Size Using TC:**
7

**Comment by rangav** [comment]
Thanks @theoutsider24 for the feedback, Will fix in the next update.

**Comment by rangav** [comment]
This Bug is fixed now and published to the marketplace, please update to `v2.9.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please let me know your feedback.
