### ISSUE TITLE
Protocol HTTPS not supported. Expected HTTP

### ISSUE THREAD

**Issue by ninjavis** [rangav/thunder-client-support#1213]
**Describe the bug**
A brand new install of VSCode + Thunderclient on Windows 11. 
I am trying to POST to an HTTPS endpoint that definitely works ( works on my other laptop, same wifi connection, Windows 10, Node 18.15.0 ), but I get the error "Protocol HTTPS not supported. Expected HTTP" after sending the POST request in Thunder Client.
I completely disabled Windows Defender Firewall just to test if that had any influence.

**To Reproduce**
Same as above. Unfortunately, I am unable to provide the specific https endpoint due to a NDA. 

**Expected behavior**
The POST should work as per normal.

**Platform:** 
 - OS: Windows 11, Node 18.16.1
 - vscode version: 
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22000
 - extension version: v2.8.3

**Your Team Size Using TC:**
1

Many thanks in Advance

**Comment by rangav** [comment]
Hi @ninjavis thanks for reporting the bug, 

- did you enable proxy or vpn?
- The url endpoint is localhost or published url?

Can you please test with both http library `axios` and `got` and let me know which one is working?

<img width="638" alt="Screenshot 2023-04-11 at 15 18 10" src="https://user-images.githubusercontent.com/8637550/231192462-1d27be75-a95e-4ccb-b847-02154e136063.png">

**Comment by ninjavis** [comment]
@rangav thank you for your quick response!

- I don't have a proxy or vpn. 
- url is published yes
- testing your provided https url works fine.
- using axios gives me a different error "unable to verify the first certificate"

This is really strange...
As I mentioned, it works fine on my Windows 10 laptop - nothing special on there either.

Any other ideas?
Thank you for your time, I appreciate it

**Comment by ninjavis** [comment]
@rangav I tested using http 1.1 this morning, and it works :)
Interesting. That obviously means one of our servers doesn't support http 2 yet.

Thanks again, appreciate it!

**Comment by ninjavis** [comment]
@rangav no wait, I spoke too soon. It doesn't actually work. A POST merely returns some HTML response instead of the expected JSON. Sigh...

**Comment by rangav** [comment]
@ninjavis if you are getting html, then I think you should add `Accept` header with value `application/json`

**Comment by ninjavis** [comment]
@rangav nope, that still didn't help.

I matched my Windows 10 Thunder Client settings to my Windows 11 one as well. It seems like http 1.1 also is the only option that works on Windows 10 for our staging server.

**Comment by rangav** [comment]
Can you share screenshot of header tab? Masking any sensitive data

**Comment by ninjavis** [comment]
@rangav oh my soul, just spoke with my colleague, I made a typo in the url. I feel so dumb.

Apologies! Sorry for wasting your time, but thank you @rangav

**Comment by rangav** [comment]
No problem 👍
