### ISSUE TITLE
Variable issue

### ISSUE THREAD

**Issue by vvazdeveloper** [rangav/thunder-client-support#1214]
**Your Team Size Using TC:**

**Question:**

I am passing the parameters, as shown on the picture below, however, the second parameter - {{balance_After_CreditTransfer}) -  is reading the same value as the first parameter - {{balance_Before_CreditTransfer}.

When I look at the Environemnt variables, both variables, {{balance_Before_CreditTransfer} and {{balance_After_CreditTransfer}, have different values.

![Variable_Issue_2023-07-06_11-13-53](https://github.com/rangav/thunder-client-support/assets/77992296/ae9e2b41-4653-4ad3-847f-a67def3a9c04)

Just FYI, below is the function that I am using on my script.js file that I am calling through my Test Tab

![image](https://github.com/rangav/thunder-client-support/assets/77992296/9af92e78-8768-4c62-abb8-06afb735fef4)

Honestly, I don't know why these values are the same for both variables since they have different values in the Environment Variables Tab. This is causing my test to fail. Pleasse help me to identify what I am doing wrong!

**Comment by vvazdeveloper** [comment]
Just an update to get it simplified, if I execute "Run Collection", I am getting 1 test failing because the value that are being read from both variable have the same value as shown below:

![image](https://github.com/rangav/thunder-client-support/assets/77992296/65abedc1-b596-4a0a-a20f-641cb2d6fff0)

However, if I send only this request again, it will pass, as shown below, because on the second time when I submit the same request, it gets the variables updated as expected.

![image](https://github.com/rangav/thunder-client-support/assets/77992296/98f5ef48-21f5-4847-a380-513c2f02508a)

**Comment by rangav** [comment]
May be this one is causing the issue?
<img width="1127" alt="Screenshot 2023-07-06 at 17 33 02" src="https://github.com/rangav/thunder-client-support/assets/8637550/af1b9383-42dd-408c-8e02-a22770b3c490">

Can you remove the above `Set Env Variable` and set different values for `{{balance_Before_CreditTransfer}` and `{{balance_After_CreditTransfer}}` in environment and test again?

**Comment by vvazdeveloper** [comment]
This is what I am doing...
I have 3 requests as shown below:

![image](https://github.com/rangav/thunder-client-support/assets/77992296/2c2c8d20-5e1d-4e47-b43b-306efa4203f0)

1- I submit the request#: 1,  collect from the response body the value for the balance, and save into the environment variable called {{balance_Before_CreditTransfer}}. The value is being saved correctly after this Request#: 1 has been sent.

![image](https://github.com/rangav/thunder-client-support/assets/77992296/f7d83a17-52c0-4c64-bce7-8072ae312516)

2- I submit the Credit Transaction of $50.00

3- I check the balance using the request#: 3, collect collect from the response body the value for the balance, and save into the environment variable called {{balance_After_CreditTransfer}}. Again, the value has been saved correctly after Request#: 3 has been sent.

![image](https://github.com/rangav/thunder-client-support/assets/77992296/e5c6d238-9ea7-4ef3-8f9f-bdf267ccee4f)


![image](https://github.com/rangav/thunder-client-support/assets/77992296/32623446-c80a-4944-ab79-8c6acd75b8ff)


Keep in mind:

 A- The requests 1 and 3 are doing the same thing but Step 3 was not copied from Step 1.
 B- Before I submit all these 3 requests, either manually or running all collections, I am going to the Environment that I had set and got their values cleared, as shown below, and save it :
 
![image](https://github.com/rangav/thunder-client-support/assets/77992296/e9c05dc7-779a-4500-9fa5-f55842be5ee5)

 C- I close the Environment Tab

But on my test within Request#: 3, is failing as shown below:

![image](https://github.com/rangav/thunder-client-support/assets/77992296/740cc53e-6ef7-460c-b627-c36c70826386)

**Comment by vvazdeveloper** [comment]
If I run my collection, Step 1 all the way to Step 3, it keeps failing because of the value of the variable {{balance_After_CreditTransfer}} is not being passed correctly somehow and as shown below:

![image](https://github.com/rangav/thunder-client-support/assets/77992296/265b07a3-da95-4888-b380-8f0d573afdf7)

But, when I check the Environment variable, their values are correct, as shown below:

![image](https://github.com/rangav/thunder-client-support/assets/77992296/39626b16-2f29-40d9-9fbb-519f2ffdf1be)

Basicaly my test is not passing because is not reading the correct value that I was expectig to be collected from {{balance_After_CreditTransfer}}.

Does it make sense?

**Comment by rangav** [comment]
I am currently away from my computer will test in the morning and get back to you.

**Comment by vvazdeveloper** [comment]
I found something but I am still experiecing the same issue...

My test keeps failing on Step#: 3. However, if I run, only the Step# 3 again, the test will pass. It seems like the root cause is the fact that the variable {{balance_After_CreditTransfer}} is not getting updated when I run the Step#: 3. To get it passed, I need to run the Step#: 3 twice at the end which is not good.

**Comment by rangav** [comment]
I understood the problem.

- You are setting the variable in the first test
- and using the same variable again in the next test, which is not updated.

In the 2nd test, the env value is updated.

Will fix it in the next update

**Comment by vvazdeveloper** [comment]
Thats what I have in my Tests Tab...

For the Step#: 1

![image](https://github.com/rangav/thunder-client-support/assets/77992296/3cf2e681-8007-4d46-968c-4b6a4b959e69)

For the Step#: 2

![image](https://github.com/rangav/thunder-client-support/assets/77992296/a23888cd-61b9-409c-ae86-5edb756358f7)

For the Step#: 3

![image](https://github.com/rangav/thunder-client-support/assets/77992296/e1df1d1c-f9b8-4ef0-a210-15b71e4384ba)

For the Step#: 4

![image](https://github.com/rangav/thunder-client-support/assets/77992296/e12bb712-22a4-4369-9dd2-c4f7fd333ada)

**Comment by rangav** [comment]
In Step 4 - you are setting value and using it using `{{balance_After_CreditTransfer}}` format. This is the issue.

Solution
So I think the solution is to use - tc.getVar("balance_After_CreditTransfer") in the Compare_AccountBalances filter instead of passing it as a parameter.

Change your test to - `json | Compare_AccountBalances({{balance_After_CreditTransfer}}, {{pacs008....}})` remove the var `balance_After_CreditTransfer`

**Comment by vvazdeveloper** [comment]
After I had followed your instruction to get my test updated, it is still failing as shown below:

![image](https://github.com/rangav/thunder-client-support/assets/77992296/11cdd37e-dcaa-4c79-89ce-e8b7e4281118)

**Comment by rangav** [comment]
Will test again and get back to you.

**Comment by vvazdeveloper** [comment]
> Will test again and get back to you.

Thank you very much, Sir!

**Comment by vvazdeveloper** [comment]
Just a quick clarification...
I should have only 3 steps. 
Everything should be verified on the Step#: 3 and I will be done as soon as the verification passes.
I just added the Step#: 4 because I have to have the Step#: 3, in this case scenario, to allow the Step#: 4 to pass. However, the ideal scenario is only having 3 steps and all these verifications should occur in the Step#: 3

**Comment by rangav** [comment]
Delete this test also in step 4 
<img width="395" alt="Screenshot 2023-07-07 at 19 25 33" src="https://github.com/rangav/thunder-client-support/assets/8637550/c46ebfb4-84da-424b-b759-21bc62f15cba">

and in the function - remove `balanceAfter parameter`
```js
function Compare_AccountBalances(messageBody, balanceBefore, transactionAmount)
{
      var balanceAfter = messageBody.accountInquiryResult.currentBalance;
     
     // save to env variable here
      tc.setvar("balance_After_CreditTransfer", balanceAfter);

    console.log(balanceAfter, balanceBefore, transactionAmount);

     return balanceAfter - balanceBefore == transactionAmount;
}
```

can you test the above and let me know? check for any typo mistakes.

also please share see output window for log messages

**Comment by vvazdeveloper** [comment]
> Hi @vvazdeveloper did you resolve this issue?

Hi rangav,
Yes, I did. Thank you very much!
Sorry fo rthe late answer. Very busy

**Comment by rangav** [comment]
No problem thanks for confirmation 👍
