### ISSUE TITLE
Load Module @faker-js/faker from Custom Filters

### ISSUE THREAD

**Issue by sebaxtian** [rangav/thunder-client-support#1216]
**Your Team Size Using TC:**
Single use, open-source project.

**Question:**
Hello, I'm trying to use the @faker-js/faker module from custom-filters.js as you mention here:
[Custom Filters](https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js)
```
// ---- To load any additional node modules from npm
// await tc.loadModule("moduleName");  see example below.
```

**Is it already working to load @faker-js/faker module?**

I'm doing this:
```
var faker = await tc.loadModule("@faker-js/faker");
console.log("Person Name: ", faker.person.firstName());
```

But, it doesnt works, I get the error:

```
Running Iteration 1 of 1 
vm.js:23
    tc.log("Person Name: ", faker.person.firstName());
                                         ^

TypeError: Cannot read properties of undefined (reading 'firstName')
    at createComunas (vm.js:23:42)

Node.js v18.16.1

```

**How can I use the @faker-js/faker module from Custom Filters?**
[@faker-js/faker](https://fakerjs.dev/guide/usage.html#node-js)

I already have installed:
```
tc2 -v -> Version: 1.4.0
Thunder Client Extension -> v2.9.1
VSCode -> Version: 1.80.0
Linux -> Ubuntu 22.04.2 LTS
npm -> 9.7.1
node -> v18.16.0
```

**Comment by rangav** [comment]
Hi @sebaxtian I haven't tested with faker library, will test and get back to you

**Comment by rangav** [comment]
Hi @sebaxtian currently loading is faker is not supported, there is error loading it.

You can use the alternative package chance

```js
async function reqFilter() {
    console.log("filter");
    var Chance = await tc.loadModule("chance");
    var chance = new Chance();
    console.log("Person Name: ", chance.name());
    console.log("Person Number: ", chance.integer());
}
```

Docs here
https://chancejs.com/person/name.html

**Comment by sebaxtian** [comment]
Hi @rangav,

It works now as you mention:

```javascript
const { faker } = await tc.loadModule("@faker-js/faker");
console.log("Person Name: ", faker.person.fullName());
```

Thank you !!

👍🏽

**Comment by sebaxtian** [comment]
I going to close this thread.

💯
