### ISSUE TITLE
Cannot import collections and envs

### ISSUE THREAD

**Issue by george-kuanli-peng** [rangav/thunder-client-support#1217]
**Describe the bug**
I cannot import collections and envs after TC upgraded to v2.9.0.
The same thing worked last week.
Error message: *Failed to Import: 1 files - xxx.json*
![image](https://github.com/rangav/thunder-client-support/assets/12026360/8f42e95a-410f-4d82-baf1-96ca834eb565)

**To Reproduce**

For importing a collection:
1. Switch to the *Collections* tab.
2. Click *Import*.
3. Select a collection json file.

For importing an env:
1. Switch to the *Env* tab.
2. Click *Import*.
3. Select an env json file.

**Expected behavior**

A new collection / env should be imported successfully and visible in the TC panel.

**Platform:** 
 - OS: (Host) Windows 11 (Remote SSH) Ubuntu 20.04
 - vscode version: 1.80.0
 - extension version: 2.9.0

**Your Team Size Using TC:**
About 5

**Comment by rangav** [comment]
Hi @george-kuanli-peng 

did you export the collection to a json file first?

Can you please confirm above?

**Comment by george-kuanli-peng** [comment]
> Hi @george-kuanli-peng
> 
> did you export the collection to a json file first?
> 
> Can you please confirm above?

Hi, @rangav but I previously made a mistake. There's no such a bug.
I mistakenly chose a native TC json file rather than an exported json file.
Importing a json file for collection / env with the correct json format works as usual.

Thanks for your information.

**Comment by rangav** [comment]
No problem, Thanks for confirmation 👍

**Comment by ajaydwarkani** [comment]
@rangav, now that the app is subscription based, I cannot use my global workspace. So I have tried to import my collection or env stored in global workspace, I am getting below error. I am seeing this issue with all my collections. can you please help me resolve this?

```
Failed to Import: 1 files - tc_col_my-workflow-sanity.json
``` 

TC Version: v2.10.2 - (2023-08-06)

**Comment by rangav** [comment]
Hi @ajaydwarkani 

the json files you are importing are raw db files. So import not supported 

you need move those to global location 

see details here
https://github.com/rangav/thunder-client-support/discussions/1286

**Comment by ajaydwarkani** [comment]
Thanks @rangav
