### ISSUE TITLE
importing from postman is not importing headers

### ISSUE THREAD

**Issue by amiroooo** [rangav/thunder-client-support#122]
as title suggest, currently importing collections (v2.1.0) from postman does not import headers as well.

**Comment by rangav** [comment]
can you attach a sample file that has the issue, i will verify it
without any sensitive info.

**Comment by amiroooo** [comment]
I think its because in postman we can store multiple examples of usages for api calls they get stored inside response originalRequest field, while the import probably imports only request field data
example:
`{
	"info": {
		"_postman_id": "xxx",
		"name": "CI-BackEnd",
		"description": "This collection contains all API resuests from CI-backend.",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "providers",
			"item": [
				{
					"name": "providers",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n  \"provider_name\": \"bcom\",\r\n  \"scan_trigger_options\": {\r\n    \"scan_system\": \"LUDM\",\r\n    \"scan_method\": \"web\",\r\n    \"scan_level\": \"allrooms\",\r\n    \"name\": \"brand\"\r\n  },\r\n  \"display_name\": \"Brand.com\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{API-URL-COMMON}}/providers",
							"host": [
								"{{API-URL-COMMON}}"
							],
							"path": [
								"providers"
							]
						}
					},
					"response": [
						{
							"name": "providers",
							"originalRequest": {
								"method": "POST",
								"header": [
									{
										"key": "Authorization",
										"value": "{{system-token}}",
										"type": "text"
									}
								],
								"body": {
									"mode": "raw",
									"raw": "{\r\n  \"provider_name\": \"test\",\r\n  \"scan_trigger_options\": {\r\n    \"scan_system\": \"LUDM\",\r\n    \"scan_method\": \"web\",\r\n    \"scan_level\": \"allrooms\",\r\n    \"name\": \"test\"\r\n  },\r\n  \"display_name\": \"Test.com\"\r\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": {
									"raw": "{{API-URL-COMMON}}/providers",
									"host": [
										"{{API-URL-COMMON}}"
									],
									"path": [
										"providers"
									]
								}
							},
							"status": "Created",
							"code": 201,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "x-powered-by",
									"value": "Express"
								},
								{
									"key": "Access-Control-Allow-Origin",
									"value": "*"
								},
								{
									"key": "content-type",
									"value": "application/json; charset=utf-8"
								},
								{
									"key": "content-length",
									"value": "195"
								},
								{
									"key": "etag",
									"value": "W/\"c3-ozlCWIqA5AGDtGz5vcF3TzQrzU4\""
								},
								{
									"key": "Vary",
									"value": "Accept-Encoding"
								},
								{
									"key": "date",
									"value": "Sun, 07 Mar 2021 15:23:14 GMT"
								},
								{
									"key": "Via",
									"value": "1.1 google"
								},
								{
									"key": "Alt-Svc",
									"value": "clear"
								}
							],
							"cookie": [],
							"body": "{\n    \"_id\": \"6044efe284bb11001360cb63\",\n    \"provider_name\": \"test\",\n    \"scan_trigger_options\": {\n        \"scan_system\": \"LUDM\",\n        \"scan_method\": \"web\",\n        \"scan_level\": \"allrooms\",\n        \"name\": \"test\"\n    },\n    \"display_name\": \"Test.com\",\n    \"__v\": 0\n}"
						},
						{
							"name": "providers",
							"originalRequest": {
								"method": "POST",
								"header": [
									{
										"key": "Authorization",
										"value": "{{system-token}}",
										"type": "text"
									}
								],
								"body": {
									"mode": "raw",
									"raw": "{\r\n  \"provider_name\": \"bcom\",\r\n  \"scan_trigger_options\": {\r\n    \"scan_system\": \"LUDM\",\r\n    \"scan_method\": \"web\",\r\n    \"scan_level\": \"allrooms\",\r\n    \"name\": \"brand\"\r\n  },\r\n  \"display_name\": \"Brand.com\"\r\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": {
									"raw": "{{API-URL-COMMON}}/providers",
									"host": [
										"{{API-URL-COMMON}}"
									],
									"path": [
										"providers"
									]
								}
							},
							"status": "Failed Dependency",
							"code": 424,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "x-powered-by",
									"value": "Express"
								},
								{
									"key": "Access-Control-Allow-Origin",
									"value": "*"
								},
								{
									"key": "content-type",
									"value": "application/json; charset=utf-8"
								},
								{
									"key": "content-length",
									"value": "94"
								},
								{
									"key": "etag",
									"value": "W/\"5e-y5q62VPHBBi1x+MP9E7H9PR4zpE\""
								},
								{
									"key": "Vary",
									"value": "Accept-Encoding"
								},
								{
									"key": "date",
									"value": "Sun, 07 Mar 2021 15:22:28 GMT"
								},
								{
									"key": "Via",
									"value": "1.1 google"
								},
								{
									"key": "Alt-Svc",
									"value": "clear"
								}
							],
							"cookie": [],
							"body": "{\n    \"error\": {\n        \"driver\": true,\n        \"name\": \"MongoError\",\n        \"index\": 0,\n        \"code\": 11000,\n        \"codeName\": \"DuplicateKey\"\n    }\n}"
						}
					]
				},
				{
					"name": "providers(update)",
					"request": {
						"method": "PUT",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"provider_name\": \"ctrip\",\r\n    \"scan_configs_override\": {\r\n        \"pos\": [\r\n            \"CN\"\r\n        ],\r\n        \"daily_scans_limit\": 90,\r\n        \"weekly_scans_limit\": 30,\r\n        \"monthly_scans_limit\": 30\r\n    }\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "{{API-URL-COMMON}}/providers",
							"host": [
								"{{API-URL-COMMON}}"
							],
							"path": [
								"providers"
							]
						}
					},
					"response": [
						{
							"name": "providers",
							"originalRequest": {
								"method": "PUT",
								"header": [
									{
										"key": "Authorization",
										"value": "{{system-token}}",
										"type": "text"
									}
								],
								"body": {
									"mode": "raw",
									"raw": "{\r\n  \"provider_name\": \"test\",\r\n  \"scan_trigger_options\": {\r\n    \"scan_system\": \"LUDM\",\r\n    \"scan_method\": \"web\",\r\n    \"scan_level\": \"allrooms\",\r\n    \"name\": \"test\"\r\n  },\r\n  \"display_name\": \"Test.com\"\r\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": {
									"raw": "{{API-URL-COMMON}}/providers",
									"host": [
										"{{API-URL-COMMON}}"
									],
									"path": [
										"providers"
									]
								}
							},
							"status": "Created",
							"code": 201,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "x-powered-by",
									"value": "Express"
								},
								{
									"key": "Access-Control-Allow-Origin",
									"value": "*"
								},
								{
									"key": "content-type",
									"value": "application/json; charset=utf-8"
								},
								{
									"key": "content-length",
									"value": "195"
								},
								{
									"key": "etag",
									"value": "W/\"c3-ozlCWIqA5AGDtGz5vcF3TzQrzU4\""
								},
								{
									"key": "Vary",
									"value": "Accept-Encoding"
								},
								{
									"key": "date",
									"value": "Sun, 07 Mar 2021 15:23:14 GMT"
								},
								{
									"key": "Via",
									"value": "1.1 google"
								},
								{
									"key": "Alt-Svc",
									"value": "clear"
								}
							],
							"cookie": [],
							"body": "{\n    \"provider_name\" : \"ctrip\",\n    \"scan_configs_override\" : {\n\t\t\"pos\" : [\n\t\t\t\"CN\"\n\t\t],\n\t\t\"daily_scans_limit\" : 30,\n\t\t\"weekly_scans_limit\" : 30,\n\t\t\"monthly_scans_limit\" : 30\n\t}\n}"
						}
					]
				}
			],
			"auth": {
				"type": "bearer",
				"bearer": [
					{
						"key": "token",
						"value": "{{system-token}}",
						"type": "string"
					}
				]
			},
			"event": [
				{
					"listen": "prerequest",
					"script": {
						"type": "text/javascript",
						"exec": [
							""
						]
					}
				},
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							""
						]
					}
				}
			]
		}	
	],
	"auth": {
		"type": "bearer",
		"bearer": [
			{
				"key": "token",
				"value": "{{user-token}}",
				"type": "string"
			}
		]
	},
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	]
}`
I think that is related to the other feature request I made since the extension does not support examples yet, it doesn't support importing this data either.

**Comment by rangav** [comment]
ok got it dont think we will support that in near future

**Comment by rangav** [comment]
HI @amiroooo I am closing this issue as we are not implementing this.
