### ISSUE TITLE
Single report for test run with multiple collections

### ISSUE THREAD

**Issue by HartleSeb** [rangav/thunder-client-support#1221]
### Discussed in https://github.com/rangav/thunder-client-support/discussions/1220

**Description**
As a end user I want to have a single report of a test run with multiple collection to validate all results in one html file (better to have the option for each file tye - json, csv and xml) if 

**Use Case**
We are testing some REST functionalities on a daily base via CLI and publish our report in the GitHub page of our repository. After we switched to a approach with multiple collections we get many reports which need to be checked. It would be much easier to get a full report of all collections instead of multiple reports for each one.

**Alternatives**
At the moment we are planning to write a script to collect the numbers out of the single reports, but it would be much easier to have some options directly within the CLI call.

**Your Team Size Using TC:**
Our team size is round about 20 people.

**Comment by rangav** [comment]
Thanks @HartleSeb for creating feature request.

**Comment by dprajap** [comment]
This is nice feature to have

**Comment by HartleSeb** [comment]
Hello @rangav,
having at least the JSON format would be helpful for our reporting! On long term the html part would be better, but the first step sounds good! 👍

**Comment by rangav** [comment]
This feature is implemented. Please update CLI to `v1.4.6`.

- JSON and CSV reports will also generate combined reports now.

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0

Please let me know your feedback.

**Comment by franky1964** [comment]
Hi @rangav,
we are running multiple collections and expecting single html reports to be linked in a central location as result for the last pipeline run.
Could you add to your roadmap to get optional a single report for html as well?

**Comment by rangav** [comment]
Sure - reopened the issue

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.14.0`

see release notes
https://github.com/rangav/thunder-client-support/releases/tag/v2.14.0

Please test and let me know your feedback.
