### ISSUE TITLE
Subtract built-in filter not working correctly

### ISSUE THREAD

**Issue by DeltaUser121** [rangav/thunder-client-support#1225]
I am using the below in my json query
`{{num1 | subtract(Amount)}}`

where if below are defined in env variables as-
num1=123.43
Amount=2.00

the result I get is 121 but it should be 121.43. How to get the accurate result here?

#1224

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.9.2`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.2

Please let me know your feedback.
