### ISSUE TITLE
Duration report for collection-wide tests

### ISSUE THREAD

**Issue by M-Gonzalo** [rangav/thunder-client-support#1226]
**Please describe feature/problem details and solution you'd like.**

I sometimes use the 'Run All' feature from collections to test how much a change impacts performance on my servers. I'd like to see a timer showing the total duration of the test sequence to that end.

**Describe alternatives you've considered**

I currently use a stopwatch or similar device

**Your Team Size Using TC:**

**Comment by rangav** [comment]
Hi @M-Gonzalo Thanks for the feedback, Will implement it in the next update.

**Comment by M-Gonzalo** [comment]
I see it! Lovely. Thanks for being so quick to implement it

**Comment by rangav** [comment]
You are welcome :)
