### ISSUE TITLE
content-length calculate inconsistent with the cURL import one

### ISSUE THREAD

**Issue by cxOrz** [rangav/thunder-client-support#1228]
**Describe the bug**
as the title

**To Reproduce**
1. Import cURL
2. Send request
3. Booom! `unexpected EOF`
4. Delete `content-length`, or paste raw json string in Text.
5. Everything works again.

![image](https://github.com/rangav/thunder-client-support/assets/32982052/e3266cad-d487-43e2-abb1-3235fcab58b6)
![image](https://github.com/rangav/thunder-client-support/assets/32982052/3094b3af-15a4-45c0-b11c-2431de9e582d)

**Expected behavior**
It's could be better to auto remove `content-length` header after import cURL, or adjust the length and overwite.

**Platform:** 
 - OS: MacOS
 - vscode version: 1.80.1
 - extension version: 2.9.2

**Your Team Size Using TC:**
2

**Comment by rangav** [comment]
Thanks @cxOrz for reporting the bug, will fix it in the next update

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.9.3`
