### ISSUE TITLE
Can thunderclient.json be divided into multiple files? 

### ISSUE THREAD

**Issue by ArturMarekNowak** [rangav/thunder-client-support#1229]
**Your Team Size Using TC:**

5
**Question:**
Hello, 

my team is working with an API written in microservice architecture. Maintnance of a single `thunderclient.json` is beginning to be time-consuming and prone to merge-conflicts. Is there a way to split this file into multiple ones? 

Thank you for your answers,
Artur

**Comment by ArturMarekNowak** [comment]
I am sorry, I have left work for today, but judging by release date of the version you are mentioning I assume we didn't update TC since. However is there a documentation which describes this feature? I took a look at https://github.com/rangav/thunder-client-support/tree/master/docs but couldn't find anything about it. How to use this feature?

**Comment by rangav** [comment]
No documentation is needed. 

After upgrade everything works normally.

The collections and environments are separated into individual json files.

you checkin the new files to git.

**Comment by ArturMarekNowak** [comment]
We will upgrade the version and we will split the files, thank you for your fast answer :D

**Comment by rangav** [comment]
We have a feature request for splitting collection into multiple request files to reduce merge conflicts - https://github.com/rangav/thunder-client-support/issues/1507

Can you please let me know your feedback

**Comment by ArturMarekNowak** [comment]
> We have a feature request for splitting collection into multiple request files to reduce merge conflicts - #1507
> 
> Can you please let me know your feedback

@AlekStyk could you share your opinion? I don't feel compotent enough

**Comment by rangav** [comment]
@bombillazo 

We have implemented a **new database design** to reduce merge conflicts. 

Update extension to [v2.23.0](https://github.com/thunderclient/thunder-client-support/releases/tag/v2.23.0) and follow the instructions in the below link

https://github.com/thunderclient/thunder-client-support/releases/tag/v2.23.0

Please upgrade to the new format and let us know your feedback.
