### ISSUE TITLE
add examples to same route

### ISSUE THREAD

**Issue by amiroooo** [rangav/thunder-client-support#123]
to support having for each API call multiple instance examples of usage.
sometimes some api calls could be used in different manners, and it would be great if you will add support to store multiple examples so we can select any of the available examples to Send

**Comment by rangav** [comment]
Hi @amiroooo your request is not clear to me, can you provide clear example or more details.

**Comment by amiroooo** [comment]
for each defined rest call, to have multiple examples of it stored that we can send.
[example](https://i.ibb.co/1ZF571V/2021-05-06-12-42-44-Postman.png)

**Comment by rangav** [comment]
Dont know whether we will have such a feature or not, will look into at a later stage.

**Comment by rangav** [comment]
HI @amiroooo I am closing this issue as we are not implementing this.
