### ISSUE TITLE
The API request works on Thunderclient, but not in Postman(or Axios)

### ISSUE THREAD

**Issue by chen-rn** [rangav/thunder-client-support#1230]
I'm trying to reverse engineer Douyin(chinese Tiktok)'s video API.

For some reason, by sending a get request to this endpoint with no headers/cookies works in Thunderclient.
https://www.douyin.com/aweme/v1/web/aweme/post/?aid=6383&sec_user_id=MS4wLjABAAAA6MgkojtAI7ZEK-vcJIly157umW6ANrtsAvk9QUar98XntKAYsFHO3WxCFLUYFWYI&max_cursor=1692358723000&count=5

I found that endpoint looking at the Network tab [here](https://www.douyin.com/user/MS4wLjABAAAA6MgkojtAI7ZEK-vcJIly157umW6ANrtsAvk9QUar98XntKAYsFHO3WxCFLUYFWYI)

To be honest, it shouldn't work. I think the API requires some sorts of cookies from completing a Captcha on their website.
However, for some reason, it works in Thunderclient. I originally suspected that it was sending using Chrome somehow, but it still works even after I clear my cookies in Chrome, which really baffles me now.

Obviously, this does not work in Postman or Axios/Fetch. 

Any idea what ThunderClient might be doing under the hood?

**Comment by rangav** [comment]
Hi @chen-rn will verify and get back to you

**Comment by chen-rn** [comment]
![Screenshot 2023-07-19 at 11 46 32 PM](https://github.com/rangav/thunder-client-support/assets/36214945/44989681-63af-438b-a28f-50c7f164756a)
I noticed that if I include the default Accept */*, then it returns nothing in the data.
But if I uncheck it, then it returns the correct data(which, I feel like it shouldn't, since I'm not including any cookies)

**Comment by chen-rn** [comment]
Honestly, this seems more like an issue with the API endpoint trying to detect bots and scrapers and less so ThunderClient, so I'm going to close it!
