### ISSUE TITLE
Import from Postman loses Authentication details for folders

### ISSUE THREAD

**Issue by shille** [rangav/thunder-client-support#1232]
When you import v1.2 collection from Postman that has folders that also have authentication credentials, these do not import to Thunder Client folders, instead auth is empty or inherit from parent.  The credential import works for the top level of the collection only.

**Comment by rangav** [comment]
Hi @shille thanks for reporting the bug, Will fix in the next update 

can you share any sample postman collection file to reproduce the issue

**Comment by shille** [comment]
Here is a zip of a sample Postman collection with basic auth creds at the various levels.  Note the data is fake, you cant run the requests.  However I put the Basic Auth cred that should be delivered in a custom header X-Requested-With for comparison.
Actually too bad Thunder Client does not show the implied headers that go in the post like "Authorization" to compare with.
[Test PostMan Collection for Credential inheritance.postman_collection.json.zip](https://github.com/rangav/thunder-client-support/files/12156809/Test.PostMan.Collection.for.Credential.inheritance.postman_collection.json.zip)
This folder "Folder has its own cred {{folder_username}}" should have a Basic credential:
![image](https://github.com/rangav/thunder-client-support/assets/5077705/ac4b8a38-c004-413c-ad16-4290ccaa148a)

**Comment by rangav** [comment]
Thanks for sharing Will look into it.

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.9.3`
