### ISSUE TITLE
CLI: Add switch to get names of generated reports

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1233]
**Please describe feature/problem details and solution you'd like.**  
I'm using the CLI to run parts of my Thunder-Client collections using the switch _"--report xml,html"_ to get some reports after execution. The idea is to have an additional option for the switch _"--log"_ with number _"9"_ for _"reports"_.
I would expect to have an additional section named _"Reports"_, following a list (each item in a new line) with the complete path of all generated reports.

**Describe alternatives you've considered**  
With additional code executed before and after the CLI run it would be possible to get the names of the generated reports.
But it would be something like a "dirty" workaround.

**Your Team Size Using TC:**  
I'm working in a large project evaluating tools for Rest-API testing. Our favorite candidate was Postman, but since scratch path is deprecated we are looking for an alternative ...

**Comment by rangav** [comment]
Thanks @franky1964 for the feedback, will add in the next update.

**Comment by rangav** [comment]
I will include the report paths without the need to use --log

**Comment by franky1964** [comment]
Hi @rangav,
of course it can be done as default.
Brgds
Frank

**Comment by rangav** [comment]
Hi @franky1964 

I am implementing this feature - it will display the following in CLI

```
Reports
 
json report -  <base-path>/thunder-reports/thunder-report_User_2023-07-30T12-44-27-494Z.json
html report -  <base-path>/thunder-reports/thunder-report_User_2023-07-30T12-44-27-501Z.html
```

Let me know your feedback. This is not published yet

**Comment by franky1964** [comment]
Hi @rangav,
I would prefer to have no prefix, just the names of the reports with full path.
I is easier to detect the type of report by checking the file extension.

Brgds
Frank

**Comment by rangav** [comment]
Ok got it, thanks for the feedback. Will update it

**Comment by rangav** [comment]
This feature is implemented. Please update CLI to `v1.4.6`.

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0

Please let me know your feedback.

**Comment by franky1964** [comment]
Hi @rangav,
it looks great but there seems to be a bug if more than one single report type should be created:
![image](https://github.com/rangav/thunder-client-support/assets/58699432/7cdfd572-ecb3-4913-abc3-2284538f4c86)
The "reports" section is empty ...

**Comment by rangav** [comment]
Thanks for reporting the bug, let me verify again and get back to you

**Comment by rangav** [comment]
Found the issue, you need to put quotes around report formats `--report "html,json"`. 
- On Mac it is working without quotes
- On Window this does not work without quotes.
