### ISSUE TITLE
No report generation in case of: tc 'requestNameOrId' --report html

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1234]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
I found a confusing behavior concerning report generation functionality:

**1. Command: tc --fol ThunderClient_01 --report html**
Report is generated

**2. Command: tc --reqlist 10829209-5bf0-4d24-aab3-0061d6462d7e --report xml,html**
Reports are generated

**3.  Command: tc getAllVersion_1 --report html**
No report is generated
(I would expect the reports to be generated as well)

Is this a bug?
(if it is a missunderstanding from my side would it be possible to implement this as new feature)

**Comment by rangav** [comment]
Hi @franky1964 reports are only available for collection or folder only. So not available for individual requests.

It's not a bug.

**Comment by franky1964** [comment]
Hi @rangav,
ok, my workaround would be to use the switch "--reqlist" with a single  'reqId' but unfortunately I dont know these ids.
Automatic or manual scanning the output of "tc list" is not my favorite solution.
Do you have any other proposal?

**Comment by rangav** [comment]
`tc list 'colName'` will list all the request ids

what is your suggestion?

**Comment by rangav** [comment]
I can change to **reqid or name** for `--reqlist` also if that helps?

**Comment by franky1964** [comment]
My proposal would be to support 'requestNameOrId' in option "--reqlist"

**Comment by rangav** [comment]
good, will make a change in the next update.

**Comment by rangav** [comment]
ETA this week.

**Comment by franky1964** [comment]
I just found out that the report in case of using option "--reqlist" contains lines for the whole collection.
Would it be possible to reduce the content to the executed ones?

**Comment by rangav** [comment]
This feature is implemented. Please update CLI to `v1.4.6`.

New Features
- `--reqlist` will now accept name or id of the request
- The HTML report will only show executed requests for `--reqlist`


See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0

Please let me know your feedback.

**Comment by franky1964** [comment]
Hi @rangav,
great, this works as expected.

Brgds
Frank

**Comment by rangav** [comment]
Thanks @franky1964 for confirmation
