### ISSUE TITLE
Thunderclient Oauth call opens browser instead of following the redirect

### ISSUE THREAD

**Issue by RobertRacklBMW** [rangav/thunder-client-support#1238]
**Your Team Size Using TC:**
> 10.000 in a worldwide company

**Question:**
We are trying to use the Oauth flow in thunderclient. With the following parameters. 

Here we use grant_type Authorization Code    

![image](https://github.com/rangav/thunder-client-support/assets/20704070/6c39fd8e-6a45-413c-8e74-1ad862521b0d)

Visual Studio Console Shows the correct first Oauth request:

````
OAuth2 AuthUrl Request:
https://auth.XXXXX.intranet/auth/oauth2/realms/root/authorize?response_type=code&state=&client_id=f5600a01-XXXX&scope=profile&redirect_uri=https%3A%2F%2XXXXXXX.intranet%2Fauth%2Fcallback
Request Method: GET
````
The redirect_uri seems to be correctly encoded in the URL. The request also correctly returns a 302 to that redirect URL. 

Response: 302 redirect to:
````
https://XXXXXX/auth/callback?code=cOwzkrXXXXXX&iss=https%3A%2F%2Fauth.XXXXX%3A443%2Fauth%2Foauth2%2Frealms%2Froot%2x&state=&client_id=f5600a01XXXXXX
````

*What actually happens*
Then a browser opens. It shows the correct URL that the correct URL that we are redirected to.

*What SHOULD happen*
Thunderclient should catch the redirect URL and extrat the "code" and send a second Oauth request to fetch the `access_token`

*Remark*
Visual Studio Thunderclient configuration follow_redirects is at the default value true.

**Comment by rangav** [comment]
Hi @RobertRacklBMW for the callback to work correctly. you should the following URL

- You can use default url `https://www.thunderclient.com/oauth/callback`
- Or You can use the localhost version `http://localhost:6789/callback`

Or if you use your own callback URL then your server URL should redirect to `http://localhost:6789/callback?code=xyz....` to forward the code back to the extension.

Reference
https://github.com/rangav/thunder-client-support#oauth-20-callback-url

The extension cannot read the code of your server URL.

Let me know if you have any questions.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
