### ISSUE TITLE
Using System Variables in Environment with validity check

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1245]
**Please describe feature/problem details and solution you'd like.**
I want to use [System Variables](![image](https://github.com/rangav/thunder-client-support/assets/58699432/18a2711e-9b4f-4837-8f02-a09604ef067d)) in variable definition of my environment like:
startDate       {{#date,'YYYY-MM-DD',{day: 1}}}

In difference to using them in collection itself there is now "green" response in case of valid definition.
But nevertheless it is already working, so it is potentially a small bug...

**Describe alternatives you've considered**
Ignore the missing green color

**Your Team Size Using TC:**
Expected team size is: 10-15

**Comment by rangav** [comment]
Hi @franky1964 Thanks for the feedback.

The color highlighting feature is not yet implemented in environment views.

Will add it to the roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.13.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.
