### ISSUE TITLE
Consideration of Pre Request Scripts on collection/folder level

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1247]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
I created a single request for getting an authentification token and configured it as "Pre Request" in "Pre Run" tab of a folder.
I would expect (comparable to postman) that every request placed as child node below the folder would have this as "Pre Request" in execution as well. This behavior already exits for "Tests".
I tried it by clicking on button "Send" (on request level) and by using the TC command with option --reqlist "nameOrId".
In both cases the configured "Pre Request" on folder level is ignored.

Is this a bug or a new feature?

**Comment by rangav** [comment]
@franky1964 how do you know it is ignored? ( pre request logs are not displayed in CLI i think )

Can you run in extension UI and see logs in `Output` window.

**Comment by franky1964** [comment]
Ok, i will check this an give you feedack

**Comment by franky1964** [comment]
Hi @rangav,
this is working as expected, sorry for causing confusion.

Brgds
Frank

**Comment by rangav** [comment]
No problem thanks for confirmation 👍
