### ISSUE TITLE
Thunderclient does not load

### ISSUE THREAD

**Issue by priyankt68** [rangav/thunder-client-support#1248]
Type: <b>Bug</b>

I had shutdown the system for the first time after running and installing thunderclient.

After that, it's not loading at all. 

Extension version: 2.10.0
VS Code version: Code - Insiders 1.78.0-insider (Universal) (657bb89984f37b810b250955570593cde0cd62eb, 2023-05-02T11:25:59.772Z)
OS version: Darwin x64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.43GB free)|
|Process Argv|--crash-reporter-id d7324edb-10c1-4921-99a9-8f2cdfa60c20|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
2i9eh265:30646982
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
gsofa:30797620
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30792099
asynctokenver:30799129
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206

```

</details>

**Comment by rangav** [comment]
Hi @priyankt68 

Can you please try installing the previous version of the extension e.g - 2.9.3 or 2.9.2

**Comment by priyankt68** [comment]
Hi @rangav , I tried 2.9.3 and 2.9.2.

It worked fine on 2.9.2 and was able to render all my existing collections.

Thanks for your quick response. Let me know if more details are required from my side.

**Comment by rangav** [comment]
Thanks for the confirmation 

Can you please do below steps to help understand the issue.

- you can delete the extension folder v2.10.0 from below location 
https://code.visualstudio.com/docs/editor/extension-marketplace#_common-questions

- And reinstall extension v2.10.0
- If you still have issues, can you open developer tools from command palette and let me if there is any in console tab
