### ISSUE TITLE
Support of '--var-data' for  option '--req-list' to overwrite environment variables

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1249]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
Not sure if this should be already supported but it would be needed for future usage of TC in our environment:
Using the option "--req-list" should allow to overwrite some environment variables as well.

Working:
tc getAllVersion_TC --var-data "url=http://localhost:8088" --log 0  

Not working (url is not overwritten, default value of environment is used):
tc --reqlist getAllVersion_TC --var-data "url=http://localhost:8088" --log 0

**Comment by rangav** [comment]
Hi @franky1964 I think it should work, will verify and get back to you

**Comment by rangav** [comment]
Thanks @franky1964 for reporting the bug, I have fixed and published a new version - `v1.4.7`

Please update and let me know your feedback.

**Comment by franky1964** [comment]
Hi @rangav,
now it works as expected.
This rapid implementation is very helpful for our plan to replace postman.

Brgds
Frank

**Comment by rangav** [comment]
Thanks @franky1964 for the confirmation.
