### ISSUE TITLE
Shortcut to send request

### ISSUE THREAD

**Issue by akshatsoni64** [rangav/thunder-client-support#125]
**Describe the solution you'd like**
A shortcut key must be assigned to send the request, it is very annoying to click the send button multiple times.

**Describe alternatives you've considered**
Ctrl + <Some Key>

**Implementation:**
Handle a key event for the same, it would work the best.

**Comment by rangav** [comment]
Hi @akshatsoni64 the shortcut is `Cmd/ctrl + Enter`, I will update the documentation.
