### ISSUE TITLE
Active Environment selection changes creating Source Control activity

### ISSUE THREAD

**Issue by cw1934** [rangav/thunder-client-support#1250]
Every time the active Environment is changed, it results in 2 files showing as having changes in Source Control; the one that used to be active, and the new one that is active.  This creates extraneous source control activity and review, and our users' use cases all vary for which Environment they'll be using.

Proposed Solution:
Can the Active Environment selection be moved to somewhere in a local file, just referencing the _id of the Active Environment?

**Comment by rangav** [comment]
Thanks @cw1934 for the feedback, Will review it

**Comment by rangav** [comment]
Implementing a solution is the easy part, But I have to make sure it won't confuse other users who don't have this problem

**Few Questions:**
- How does the user know when changing the active environment locally without changing git files? Is it the same way currently with a star icon
- How to provide the user the options in the UI to change active Env locally or real change of active env that modies git
- How to implement this without confusing existing users.

**Comment by cw1934** [comment]
1. "How does the user know when changing the active environment locally without changing git files? Is it the same way currently with a star icon"
   1. Ideally, I would prefer to have a dropdown that's visible at all times.  This is two-fold; so I can see what environment I have selected, and so I can easily change it, both without having to go into an area that's meant more for editing an environment.
1. "How to provide the user the options in the UI to change active Env locally or real change of active env that modies git"
   1. I can't think of any use-cases where a user _would_ want the change of the Active Environment committed to Git.
1. "How to implement this without confusing existing users."
   1. If implemented as described in # 1.i, I don't see it as being confusing.  
   1. It would help if the environment in the current/old implementation marked as active would be persisted upon update, but I don't think it's crucial.
1. "This should work for all the team members?"
    1. I'm not sure I understand the question, but think the active environment should always be left to each individual to choose, and not something set team-wide.

**Comment by rangav** [comment]
@cw1934 

Thanks for the feedback.

Will make this feature request a priority and implement it in around 1 week.

**Comment by cw1934** [comment]
@rangav Sounds great, thanks very much.  We'll keep an eye out for the release and take a closer look once it's available.

**Comment by rangav** [comment]
@cw1934 Proposed solution - We added a new setting `Active Environment Change`, if you set to `Save To Local Memory`, then no changes will be made to JSON files

Please let me know your feedback. I am planning to publish new update later today.

<img width="875" alt="Screenshot 2024-02-21 at 14 31 47" src="https://github.com/rangav/thunder-client-support/assets/8637550/1ac9c7aa-5163-4fa3-939b-777a24e7a621">

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.18.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.18.0

Please test and let me know your feedback.
