### ISSUE TITLE
Doesn´t work with localhost

### ISSUE THREAD

**Issue by M-Gonzalo** [rangav/thunder-client-support#1251]
**Describe the bug**

I'm trying to work with my local version of a program and Thunder Client hangs in the "Processing" screen.
It's been happening since the last few hours, I'm guessing an update either of TC or VS-Code itself
**To Reproduce**

Bring up any server locally and try to request anything to it
**Expected behavior**

**Platform:** 
 - OS:  Linux x86-64
 - vscode version: Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:36:11.334Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.7-arch1-2 snap
 - extension version:
v2.10.0 - (2023-07-31)
**Your Team Size Using TC:**

**Comment by M-Gonzalo** [comment]
If I make an ssh tunnel to my server to give it an address, it works, but I can't go on editing hundreds of saved queries.
I also tried prepending http:// and replacing localhost with 127.0.0.1, none of it works

**Comment by M-Gonzalo** [comment]
I downgraded 3 versions and it keeps happening. So it's not a problem introduced in T.C. per se; it must be a reaction to some external change, maybe in the IDE itself or some external dependency.

**Comment by M-Gonzalo** [comment]
I managed to downgrade VS-Code to the previous version (1.80.2) manually, and now TC is working again. Not an ideal solution, but it might help you to know about it so as to better track the issue.

Please let me know when you fix it so I can upgrade again my editor. Thanks

**Comment by setsukanaomi** [comment]
U should change this on Settings too so it doesn't auto update 
![image](https://github.com/rangav/thunder-client-support/assets/69606147/503dc429-36fe-4ed2-be03-e59150d8bf62)

**Comment by rangav** [comment]
Hi thanks for reporting the bug, Will look into it.

Please see this comment for possible solution 
https://github.com/rangav/thunder-client-support/issues/1086#issuecomment-1664276140

**Comment by DonatoRM** [comment]
Hello. Exactly the same thing happens to me. Thank you very much.

**Comment by mauro-andre** [comment]
Hi, same problem over here. I also downgraded vscode to version 1.80.2 to get it working again.

**Comment by rangav** [comment]
So then it could be vscode issue, please report to vscode github page also.

**Comment by Rebkas68** [comment]
I replaced localhost with the IP address, which works. Not very nice, but ok for now. At least I don't have to downgrade.

**Comment by Esked-chan** [comment]
It seems like it's a VSCode issue, the new update broke it. As @Rebkas68 said, replacing localhost with the IP address fixes the problem. Downgrading to VSCode 1.80.2 also works.

**Comment by putnam120** [comment]
I'm unable to get it to work even when using the ip address (`127.0.0.1`).

**Comment by mauro-d** [comment]
> I'm unable to get it to work even when using the ip address (`127.0.0.1`).

try to use `0.0.0.0`

**Comment by Srfigie** [comment]
same issue with our team as well..

**Comment by putnam120** [comment]
> > I'm unable to get it to work even when using the ip address (`127.0.0.1`).
> 
> try to use `0.0.0.0`

Thanks that worked.

**Comment by harshbhange0** [comment]
Same issue i tried uninstalling and disabling TC  


![Extension_ Thunder Client - test_six - Visual Studio Code 04-08-2023 11 23 48 PM](https://github.com/rangav/thunder-client-support/assets/120706512/74d5942f-5c05-43bb-a7b6-7cd6a89dfaf1)

**Comment by rangav** [comment]
Hi @harshbhange0 

Please downgrade vscode to previous version 1.80.2

**Comment by zaid50015** [comment]
Thanks mate for the solution I was literally banging my head why was this happening

**Comment by bmarinb** [comment]
I'm having the same problem. Using 0.0.0.0 solved it.

**Comment by bmarinb** [comment]
I've been presenting the same issue, and using 0.0.0.0 solved it.

**Comment by rangav** [comment]
Hi All

I Just rebuild the extension and latest vscode version and vscode CLI, let me if this fixes the issue.

Can you please install it manually and test it on the latest vs code version?

[vscode-thunder-client-2.10.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/12266503/vscode-thunder-client-2.10.1.vsix.zip)

**Comment by DonatoRM** [comment]
Hello. I still have the same problem. It is left on hold when the request is made with localhost.
Thanks for everything.

**Comment by rangav** [comment]
@DonatoRM thanks for testing, then it could be vscode issue.

Either downgrade vscode to `1.80.2` or use this solution https://github.com/rangav/thunder-client-support/issues/1086#issuecomment-1664276140

**Comment by rangav** [comment]
Can anyone also test with our `CLI` to check the issue. As the CLI runs outside of vscode context so it will be a good test to find the source of problem

Thunder Client CLI Docs
https://rangav.medium.com/d91eb5c71d8e

**Comment by joseescoli** [comment]
Hey, all! Tested ThunderClient version 2.5.3 and works fine. Any version past 2.5.3 does not work anymore in Visual Studio Code.

**Comment by sharma-dushyant** [comment]
Thank You

**Comment by M-Gonzalo** [comment]
I know it's probably not related, but something similar happened to me while updating the MongoDB driver for NodeJS from 3.x. It stopped resolving `localhost`. I'll leave this here just in case it can help track the bug somehow.

**Comment by rangav** [comment]
Hi @danchaseCTS 

We just now published a new version to fix this issue.

Please update the extension to version - `v2.10.2`

Thanks to @joseescoli for pointing to the version that works, looks like a proxy library issue.

Let me know if this works or not

**Comment by srisrinu1** [comment]
The new version is working as expected. I have tested it with multiple API calls and have not found any problems.
