### ISSUE TITLE
Stuck on processing stage.

### ISSUE THREAD

**Issue by CoderJaez** [rangav/thunder-client-support#1253]
**Describe the bug**
When trying to make a request from local api server. It stock on processing stage.
**To Reproduce**

**Expected behavior**
Creating new request either post, get, put or delete from local api server
Entering localhost:3000/api/v1/instructors
**Platform:** 
 - OS: Windows 10 Pro
 - vscode version: 1.81.0
 - extension version: 2.10.0

**Comment by boykebn** [comment]
the same thing happened to me, since yesterday I always stuck at the processing stage, hoping that soon there may be a solution that can be obtained

**Comment by rangav** [comment]
Hi, there is a bug with VSCODE latest version please downgrade to v1.80.2

see comment here
https://github.com/rangav/thunder-client-support/issues/1251#issuecomment-1664852581

**Comment by boykebn** [comment]
I just downgraded my VSCODE version, and ya it worked, not an ideal solution, but it did work. Thank you for the advice, and hope to be able to fix it soon. Thanks

**Comment by rangav** [comment]
Hi @boykebn thanks for confirmation 

it's a bug with vscode so they have to fix it. 
But I will research more on it

vscode bug link
https://github.com/microsoft/vscode/issues/189629

**Comment by rangav** [comment]
Hi All

I Just rebuild the extension and latest vscode version and vscode CLI, let me if this fixes the issue.

Can you please install manually and test it on latest vs code version

[vscode-thunder-client-2.10.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/12266503/vscode-thunder-client-2.10.1.vsix.zip)

**Comment by rangav** [comment]
Can any also test with our `CLI` to check the issue. As the CLI runs outside of vscode context so it will be a good test to find the source of problem

Thunder Client CLI Docs
https://rangav.medium.com/d91eb5c71d8e

**Comment by boykebn** [comment]
Hallo @rangav,
I just tried to run the latest TC you provided and manually install on the latest version of vscode, but it still stuck on processing stage.

**Comment by rangav** [comment]
@boykebn thanks for testing, then it could be vscode issue. 

- https://github.com/microsoft/vscode/issues/189686
- https://github.com/microsoft/vscode/issues/189629

### Solution
Either downgrade vscode to `1.80.2` or use this up address  https://github.com/rangav/thunder-client-support/issues/1086#issuecomment-1664276140

**Comment by jspencer-analytics** [comment]
I'm having the same issue and glad to have seen it here. I will downgrade vscode. thanks!

**Comment by rangav** [comment]
Hi All,

We just now published a new version to fix this issue.

Please update the extension to version - `v2.10.2`

Let me know if this works or not

**Comment by boykebn** [comment]
Hi @rangav,
I just updated my vscode back to 1.81.0, and tried the latest version of TC that you told me about, it works fine, thanks for the hard work

**Comment by jspencer-analytics** [comment]
> Hi All,
> 
> We just now published a new version to fix this issue.
> 
> Please update the extension to version - `v2.10.2`
> 
> Let me know if this works or not

hi @rangav 
Should this be available in VS code? It is still saying `v2.10.0` for me with no update available. Thanks

**Comment by jspencer-analytics** [comment]
> Hi All,
> 
> We just now published a new version to fix this issue.
> 
> Please update the extension to version - `v2.10.2`
> 
> Let me know if this works or not

Initially vscode was not updating the extension. But now I have `v2.10.2` and its working again. Thanks a lot for the fix, I am only new to VS Code but this extension is amazing!

**Comment by azvyae** [comment]
Can confirm it already solved on `v2.10.2`. I guess you guys can close this issue

**Comment by rangav** [comment]
Thank you guys for the confirmation

**Comment by Daksh-Maru** [comment]
I am still facing the same issue with the current version 2.17.7. Why I am supposed to downgrade my vscode version

**Comment by Daksh-Maru** [comment]
vs code version is 1.86.1
