### ISSUE TITLE
Checking for Certificate even with Http

### ISSUE THREAD

**Issue by danchaseCTS** [rangav/thunder-client-support#1254]
**Your Team Size Using TC:**
1

**Question:**
Trying out Thunder Client, seems that when I go to http://0.0.0.0:5215, I get "Unable to verify first certificate", but http does not support using certificates. I would have normally used localhost but there is a bug logged for it, does the 0.0.0.0 affect this, or is there something I need to check to tell it http other than the protocol indicator in the URL? Or does it just not support HTTP?

**Comment by rangav** [comment]
Hi @danchaseCTS 

We just now published a new version to fix this issue.

Please update the extension to version - `v2.10.2`

Let me know if this works or not

**Comment by danchaseCTS** [comment]
@rangav Thank you!!
