### ISSUE TITLE
How to specify the collection name to be used with option "--reqlist"?

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1258]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
I have multipe collections and it cannot be ensured that all request names are unique. Nevertheless we want to use the option "-reqlist" to run a single or some requests from a dedicated collection. If there is nothing found there should be an error.
**Is it possible to get an additional option like "--col" or "--collist" to specify the collection name(s) used for searching the requests given behind the option "--reqlist"?**
This wold increase the performance as well since only the named collections have to be checked...

**Comment by rangav** [comment]
Hi @franky1964 you can use `--col` switch to restrict the search

**Comment by rangav** [comment]
Closing this issue, feel free to reopen if needed
