### ISSUE TITLE
when grant type is set as "Client Credential" , click "generate token" doesn't seem do anything.

### ISSUE THREAD

**Issue by jackchenwork** [rangav/thunder-client-support#1259]
**Your Team Size Using TC:**
1
**Question:**

I am trying to use Thunder Client extension in VSCode to test client App to Azure Function App authentication with oauth2.

I have two Azure App registrations created :

client app: d6904cde-d467-xxxx

Azure function App 's AAD authentication app id:  3abdb8e0-fe24-xxx

A App role is created for 3abdb8e0-fe24- and d6904cde- has requested application level api permission to 3abdb8e0 , and admin consent is done.

I am trying to use "Client Credential" grant type, but when I click "generate token", I only see a green "Saved Successfully" and nothing else happened, access token is not filled, doesn't look like token url is called at all. I am using Windows 10 machine. 

Any suggestion where to troubleshoot? 

![image](https://github.com/rangav/thunder-client-support/assets/28953194/d7fdd004-d303-4328-8efb-51c828a8c011)

**Comment by rangav** [comment]
Hi @jackchenwork, please see `output`  window for all the logs

**Comment by jackchenwork** [comment]
For what ever reason, there isn't anything in output window, when I have wrong and correct scope:

![image](https://github.com/rangav/thunder-client-support/assets/28953194/92719a5a-0736-43c6-a479-469338d2cd02)

**Comment by rangav** [comment]
Just want to confirm did you select **Thunder Client** filter in `Output` window, there is shortcut also in the menu for logs
<img width="1074" alt="Screenshot 2023-08-09 at 18 41 39" src="https://github.com/rangav/thunder-client-support/assets/8637550/5a7cf827-f315-41dd-9140-b0d7e3c9a964">

**Comment by jackchenwork** [comment]
LOL thanks so much for the quick response. yeah the right side menu was in "terminal" by default and once I switched to thunder client, I see all the request and response !

**Comment by jackchenwork** [comment]
Apologize, should read the manual!

**Comment by rangav** [comment]
Non problem, feel free to reach out if you have any other questions.

**Comment by rangav** [comment]
Is this issue resolved?
