### ISSUE TITLE
Thunder Client not using the editor font

### ISSUE THREAD

**Issue by nicopicchio** [rangav/thunder-client-support#1260]
**Describe the bug**
When sending a request, the json response received is rendered with a serif font.

**To Reproduce**
Click on send button and check response tab

**Expected behavior**
Response body to be rendered with the same font as the text editor

**Platform:** 
 - OS: MacOS Ventura 13.4.1
 - vscode version: 1.81.0 (Universal)
 - extension version: v2.10.2

**Your Team Size Using TC:**
7

![Screenshot 2023-08-09 at 16 10 05](https://github.com/rangav/thunder-client-support/assets/70696511/35486902-bf52-4f57-a2b3-852e89cf067f)

**Comment by rangav** [comment]
Thanks @nicopicchio for the feedback, Will verify it.

**Comment by nicopicchio** [comment]
Apologies @rangav, I only just realised the font was not installed on my work machine, so it was not available for TC to use. Since VSCode was using it I wrongly assumed it was already installed.

![Screenshot 2023-08-18 at 16 31 55](https://github.com/rangav/thunder-client-support/assets/70696511/c1edf95b-164a-4795-8ffc-8623b6ad1e0c)

**Comment by rangav** [comment]
No Problem, Thanks @nicopicchio for the confirmation.
