### ISSUE TITLE
Use Thundler Client with "tc --..." in GitLab pipeline

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1261]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
We are evaluating the  CLI & CI/CD Integration in a GitLab pipeline and I would expect to have a fitting return code in case of any failures.
Currently my job is always pass, even if some requests failed...

**Comment by rangav** [comment]
Hi @franky1964 what command are you running is it `--col` or `--reqlist` 

I Will verify and get back to you.

**Comment by rangav** [comment]
you can see the image below when failed you will see `red` circle and `blue` circle when all tests passed
<img width="540" alt="Screenshot 2023-08-09 at 19 28 06" src="https://github.com/rangav/thunder-client-support/assets/8637550/fe679dbc-6540-4008-a9a0-c383a5e0c8af">

**Comment by franky1964** [comment]
Hi @rangav,
there seems to be a bug if nothing was found (e.g. a wrong name for the request) to be executed:
![image](https://github.com/rangav/thunder-client-support/assets/58699432/8d24ef8d-aad1-4cfa-88fe-924d18d74802)

**Comment by rangav** [comment]
Thanks,  now I understood the issue. Will fix it later today.

**Comment by rangav** [comment]
Hi @franky1964 the bug is fixed now and published. Please update CLI to `v1.4.9`.

Let me know your feedback.
