### ISSUE TITLE
How to save sent request body?

### ISSUE THREAD

**Issue by Danny-ouo** [rangav/thunder-client-support#1262]
**Your Team Size Using TC:**

**Question:**

I want save some parameters or full json from request body.
Can I save parameter from request body? (Not from response)
In postman, I use "JSON.parse(request.data)" this sentence in test script for access to request body.

**Comment by rangav** [comment]
Hi @Danny-ouo 

You can use `tc.request.raw`

details here
https://github.com/rangav/thunder-client-support/blob/master/docs/tc-types.d.ts#L96

**Comment by rangav** [comment]
Closing this issue feel free to reopen if needed

**Comment by Danny-ouo** [comment]
thank you~!
