### ISSUE TITLE
Thunder Client not loading on my VS Code Insider

### ISSUE THREAD

**Issue by danilocecilia** [rangav/thunder-client-support#1265]
**Your Team Size Using TC:**

**Question:**
Can't get the thunder client plugin to work on my VS Code Insider anymore, the panel keeps loading forever and I see a message on the bottom where it says "command 'thunder-client-account' not found.

![image](https://github.com/rangav/thunder-client-support/assets/2642530/42532d82-652f-4a28-9bb7-e86576009f8b)

**Comment by danilocecilia** [comment]
Hi @rangav !

Version: 1.79.0-insider (Universal)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:20:35.044Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

List of extensions I'm using on my vscode-insider:

cev.overnight
dbaeumer.vscode-eslint
donjayamanne.githistory
dracula-theme.theme-dracula
dsznajder.es7-react-js-snippets
eamodio.gitlens
esbenp.prettier-vscode
formulahendry.vscode-mysql
GitHub.copilot
GitHub.copilot-labs
glenn2223.live-sass
kleber-swf.unity-code-snippets
mblode.twig-language-2
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-mssql.mssql
rangav.vscode-thunder-client
redhat.vscode-yaml
ritwickdey.LiveServer
shd101wyy.markdown-preview-enhanced
sibiraj-s.vscode-scss-formatter
Tobiah.unity-tools
vscode-icons-team.vscode-icons
whatwedo.twig

**Comment by rangav** [comment]
Thunder Client extension version?

**Comment by danilocecilia** [comment]
@rangav the Thunder Client  extension versions can be seen on the printscreen I sent on my first post, which is v2.10.2

I've done the suggestions you mentioned and the problem persists, can't open it on the vs code insider, I had it working fine till last week.

**Comment by danilocecilia** [comment]
It turns out it was something on my network. So I'm closing this ticket as there is no more issue.

Thanks for the support @rangav !!
