### ISSUE TITLE
When response is not JSON, unable to set environment variables

### ISSUE THREAD

**Issue by utkutekalmaz** [rangav/thunder-client-support#1267]
When response is not JSON, unable to set environment variables.  setTo is only available for json. Something like this would be helpful really:
`ResponseBody  - setTo - {{variable}}.split("request-token/")[1]`

**Describe alternatives you've considered**
in postman you have option to make this:
```javascript
const rq = responseBody.split("request-token/")[1]
pm.environment.set("sessionId", rq);
```

and thanks for this great product really! :rocket:

**Comment by rangav** [comment]
Hi @utkutekalmaz you can use `filters`

see docs here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#built-in-filters

Use below
- `text | split("request-token/") | first` - SetTo -  `{{sessionId}}`

**Comment by utkutekalmaz** [comment]
Ty very much @rangav !!! :)
