### ISSUE TITLE
Offline Activation feature feedback 

### ISSUE THREAD

**Issue by rangav** [rangav/thunder-client-support#1270]
### Offline Activation feature
The offline activation feature allows users to enter an activation code in the extension to activate premium features. The extension will not communicate with our servers to validate the subscription status. When a user activates the offline activation feature the admin cannot remove this user for 6 months period or till the end of the subscription period.

**#Stage:** Under Review

**#Price Plan:** Enterprise

**Please let us know your feedback:**

- How useful is this feature?

Based on the feedback and the number of users interested in this feature, we will add it to the roadmap.

**Comment by rangav** [comment]
This feature is now implemented and available in Enterprise plan.

If you have any questions, please contact using below link
https://www.thunderclient.com/contact

**Comment by sandeepspd123** [comment]
Good
