### ISSUE TITLE
Save response to a variable replacing spaces

### ISSUE THREAD

**Issue by camilomet** [rangav/thunder-client-support#1271]
**Your Team Size Using TC:**

**Question:**
Hi,
First, thank you, thunder is really cool, I need to migrate from postman but I dont know how to save the response from this api call 
https://generator.avris.it/api/DE/tin that gives something like "31 298 356 035", a string, to a variable called "tin" with the response and without spaces 31298356035

My postman code is this one and works fine but not sure how to do it in thunder
```
var jsonDataResponse = JSON.parse(responseBody);
pm.environment.set("tin", jsonDataResponse.replace(/\s/g, ''));
```

And second

I have an API that response is

```
{
    "positions": [
        "1",
        "3",
        "4",
        "6"
    ],
    "d": "xxx="
}
```
And I have this code that saves two variables

```
var jsonData = JSON.parse(responseBody);
positionstring=""+jsonData.positions;

onestring=positionstring.replace(new RegExp(",", "g"), "");
twostring=positionstring.replace(new RegExp(",", "g"), "\",\"");

positionstring ="\[\""+positionstring+"\"\]";
pm.environment.set("positions", twostring);
pm.environment.set("pwd", onestring);
```

that saves these:
```
onestring= 1346
twostring= ["1","3","4","6"]
```
And same thing, not sure how to do it in thunder, can you please give me an idea of how to start? 
I tried some combinations in the test tab but without success

Thanks in advance for your time

**Comment by rangav** [comment]
Hi @camilomet 

You can use custom scripting and use `Post Request Script` feature.

https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by camilomet** [comment]
Hi, 
I just solved it, here it is
Create a JavaScript file with the function like this

```
function positions() {	

// Parse the JSON text into an object
const jsonObject = tc.response.json;

// Create the positions array using the values from the JSON object
const twostring = jsonObject.positions.map(value => value);

// Create the pwd variable
const onestring= jsonObject.positions.map(Number).join('');

tc.setVar("onestring",onestring);	
tc.setVar("twostring",twostring);

}

module.exports = [positions]
```	
Then in the request fo to Tests tab, Post Request Script and select function, in this case "positions"
(In order functions appear there, in collection options file should be listed in Script Files)
