### ISSUE TITLE
Thunder client save file didn't use the filename in content-disposition

### ISSUE THREAD

**Issue by babashark** [rangav/thunder-client-support#1272]
<img width="822" alt="image" src="https://github.com/rangav/thunder-client-support/assets/127459243/55442e76-729a-4b1a-80a9-c8aa2cd1b749">
<img width="931" alt="image" src="https://github.com/rangav/thunder-client-support/assets/127459243/b3303619-3786-4057-bb1f-b501870d28ad">

**Comment by babashark** [comment]
Please also support UTF8 file name, e.g. filename*=utf-8''%E6%AA%94%E6%A1%88%E5%90%8D%E7%A8%B1.txt

https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

**Comment by rangav** [comment]
Thanks @babashark for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.17.2`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.2

Please test and let me know your feedback.
