### ISSUE TITLE
comma and single quate 

### ISSUE THREAD

**Issue by Gavitchetan** [rangav/thunder-client-support#1273]
Trailing Comma Issue:
When sending JSON payloads, if I accidentally include a comma after the last key-value pair, the Thunderbolt extension generates an error. JSON specifications do not permit trailing commas, and it would be helpful if the extension could handle this more gracefully.

Example of the problematic JSON:

json

{
    "productId": "64db8d0857257abd74d041c5",
    "comment": "I m just API testing",
    "rating": 4,
}

Handling Single Quotes within Double Quotes:
If I use a single quote (') within a JSON string enclosed by double quotes ("), the Thunderbolt extension raises an error. JSON standards allow for single quotes within double-quoted strings, and it would be beneficial if the extension could properly manage this scenario.

Example of the problematic JSON:

json

    {
        "message": "Hello, I'm experiencing an issue."
    }

I greatly appreciate the utility that the Thunderbolt extension brings to API testing and want to contribute to its improvement. Addressing these issues could enhance the extension's usability and overall experience for users like me.

Thank you for your hard work on this extension. I look forward to seeing future updates and improvements , if you are agree with this isue please notify me on cgavit141@gmail.com

**Comment by rangav** [comment]
Thanks @Gavitchetan for the feedback, will review and add to roadmap.
