### ISSUE TITLE
Make auth headers appear in "headers" tab of request

### ISSUE THREAD

**Issue by hyzerki** [rangav/thunder-client-support#1275]
When you add authorization to a request, the authorization header is not displayed in the headers section. Thus, as a beginner who is not completely familiar with authorization, it was not clear to me how authorization is sent in the request. In the postman, when you add authorization, it is displayed in the headers. And you immediately see what headers will be sent.

**Here is an example of what I mean**
![image](https://github.com/rangav/thunder-client-support/assets/72630085/f92f94ac-a79a-492f-bd99-d05d6afef82f)
![image](https://github.com/rangav/thunder-client-support/assets/72630085/ab507647-f919-438f-8233-9b89613372b0)

And this is how it looks in thunder client
![image](https://github.com/rangav/thunder-client-support/assets/72630085/ed792b16-63e3-4ddb-8feb-a813e91a3049)
![image](https://github.com/rangav/thunder-client-support/assets/72630085/a8de5e66-a5ad-4b95-9a8c-ab086ed68501)

No headers even in raw
![image](https://github.com/rangav/thunder-client-support/assets/72630085/79f94688-b691-4fff-a228-424520d2317c)

**Comment by rangav** [comment]
Hi @hyzerki all the request headers sent with the request is displayed in the logs

You can view logs
https://github.com/rangav/thunder-client-support#logs

Sorry not planning to implement this feature.
