### ISSUE TITLE
How to save sent request body? - 2

### ISSUE THREAD

**Issue by Danny-ouo** [rangav/thunder-client-support#1276]
**Your Team Size Using TC:**

**Question:**

Few days ago, I asked "How to save sent request body?" (https://github.com/rangav/thunder-client-support/issues/1262)
So I tried like this 
`
function saveCreateCustomerRequestBody(){
    console.log("body: " + tc.request.raw);
    tc.setVar("createCustomerRquestBody", tc.request.raw, "local");
}
`
And I add this function in Post Reauest Script.
But I got this log `body: undefined` and there is nothing in "createCustomerRquestBody".

What is wrong with my code?
How can I use `tc.request.raw`?

**Comment by rangav** [comment]
Hi @Danny-ouo 

I will verify and get back to you

**Comment by Danny-ouo** [comment]
Thanks.

**Comment by rangav** [comment]
The correct api is - `tc.request.body.raw`

**Comment by Danny-ouo** [comment]
Okay. I'll try again. Thnak you!

**Comment by Danny-ouo** [comment]
Oh! It works! Have a nice weekend! 😄
