### ISSUE TITLE
XML-report: Add timing information (xunit conform)

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1277]
**Please describe feature/problem details and solution you'd like.**
We plan to use TC in our GiLab pipelines and want to use the "Tests" overview in GitLab.
I already works but the listet testsuites/testcases have no duration time.
Please add duration information for testsuites and tests to xml report format.

**Example:**
testsuite name="xyz" tests="3" errors="0" failures="1" time="5.215" timestamp="2023-08-16T10:45:44.897000"

**Describe alternatives you've considered**
no alternative

**Your Team Size Using TC:**
Expected team size is: 10-15

**Comment by rangav** [comment]
Hi @franky1964 thanks for the feedback, Will add time field.

Reminder:
Companies require subscription to to use thunder client from this Friday.

Compare Plans
https://www.thunderclient.com/pricing#compare

Not sure when your company is planning to buy subscription. But just want to remind about dates.

**Comment by rangav** [comment]
This feature is implemented in CLI. Please update CLI to version `v1.5.1`.

Please test and let me know if you need any further changes.

**Comment by franky1964** [comment]
Hi @rangav,

we plan to use the xml output for generating test coverage report and therefore the format has to be very close to junit standard.
Normaly "folders" are documented as testsuites as well, this is currently not the case in your xml generation code.
In addition these testsuites on folder level should have the timing and statistic information as calculated sum of all subsequent testcases.
We plan to use max 4 level of folders to group our requests.

Brgds
Frank

**Comment by rangav** [comment]
Thanks @franky1964 for the feedback.

I am not too familiar with JUnit standard. Can you share sample xml file format for a collection with folders and request. So we can implement it.

**Comment by franky1964** [comment]
Hi @rangav,
we dont need any special implementation, just an xml report close to the standard.
Please check this side for mor details:
[https://github.com/testmoapp/junitxml](https://github.com/testmoapp/junitxml)
Example:
<?xml version="1.0" encoding="UTF-8"?>
<testsuites time="15.682687">
    <testsuite name="Tests.Registration" time="6.605871">
        <testcase name="testCase1" classname="Tests.Registration" time="2.113871" />
        <testcase name="testCase2" classname="Tests.Registration" time="1.051" />
        <testcase name="testCase3" classname="Tests.Registration" time="3.441" />
    </testsuite>
    <testsuite name="Tests.Authentication" time="9.076816">
        <testsuite name="Tests.Authentication.Login" time="4.356">
            <testcase name="testCase4" classname="Tests.Authentication.Login" time="2.244" />
            <testcase name="testCase5" classname="Tests.Authentication.Login" time="0.781" />
            <testcase name="testCase6" classname="Tests.Authentication.Login" time="1.331" />
        </testsuite>
        <testcase name="testCase7" classname="Tests.Authentication" time="2.508" />
        <testcase name="testCase8" classname="Tests.Authentication" time="1.230816" />
        <testcase name="testCase9" classname="Tests.Authentication" time="0.982">
            <failure message="Assertion error message" type="AssertionError">
                
            </failure>            
        </testcase>
    </testsuite>
</testsuites>

**Comment by rangav** [comment]
Just to clarify I tool the below example from link

How to differentiate between folder and collection when both have `testsuites` as xml node name?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites time="15.682687">
    <testsuite name="Tests.Registration" time="6.605871">
        <testcase name="testCase1" classname="Tests.Registration" time="2.113871" />
        <testcase name="testCase2" classname="Tests.Registration" time="1.051" />
        <testcase name="testCase3" classname="Tests.Registration" time="3.441" />
    </testsuite>
    <testsuite name="Tests.Authentication" time="9.076816">
        <testsuite name="Tests.Authentication.Login" time="4.356">
            <testcase name="testCase4" classname="Tests.Authentication.Login" time="2.244" />
            <testcase name="testCase5" classname="Tests.Authentication.Login" time="0.781" />
            <testcase name="testCase6" classname="Tests.Authentication.Login" time="1.331" />
        </testsuite>
        <testcase name="testCase7" classname="Tests.Authentication" time="2.508" />
        <testcase name="testCase8" classname="Tests.Authentication" time="1.230816" />
        <testcase name="testCase9" classname="Tests.Authentication" time="0.982">
            <failure message="Assertion error message" type="AssertionError">
                <!-- Call stack printed here -->
            </failure>            
        </testcase>
    </testsuite>
</testsuites>
```

**Comment by franky1964** [comment]
As here described "testsuites" is an optional element:
<?xml version="1.0" encoding="UTF-8"?>
<!-- <testsuites> Usually the root element of a JUnit XML file. Some tools leave out 
the <testsuites> element if there is only a single top-level <testsuite> element (which
is then used as the root element).

So I would propose to use the "testsuites" root element only if a list of cllections was executed, then you should create a name for it by yourself.
In other cases the root node is a testsuite with the name of the collection and all folders will be represented as subnodes of type testsuite as well.
 The "testcase" should have a property "classname" with the full path information <colName>.<folderName>..-<folderName>

**Comment by rangav** [comment]
See the proposed solution, let me know if its good.

### Sample Collection
<img width="470" alt="Screenshot 2023-10-20 at 13 41 03" src="https://github.com/rangav/thunder-client-support/assets/8637550/da622451-3cd7-4efa-bc52-4e34d059e681">

### Current Report
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="ColA" tests="5" time="0.479">
  <testsuite id="7dd4314e-4d2f-4277-a2a7-e35cc7550827" name="Req1" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.120">
    <testcase name="Response Code equal to 200 " classname="Req1"/>
  </testsuite>
  <testsuite id="4314d8ec-2c7c-4c7d-bbe7-9b0670ea0402" name="Req2" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.077">
    <testcase name="Response Code equal to 200 " classname="Req2"/>
  </testsuite>
  <testsuite id="25eaf1d8-a3c0-4230-ac90-b425398ebba5" name="Req3" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.144">
    <testcase name="Response Code equal to 200 " classname="Req3"/>
  </testsuite>
  <testsuite id="368dcdb8-6b1d-4768-9a9e-7fbbfabf863b" name="Req4" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.067">
    <testcase name="Response Code equal to 200 " classname="Req4"/>
  </testsuite>
  <testsuite id="c4a70df3-54c2-43c5-a8a2-daff56c3f899" name="Req5" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.070">
    <testcase name="Response Code equal to 200 " classname="Req5"/>
  </testsuite>
</testsuites>
```

### New Format
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="ColA" tests="5" time="0.479">
  <testsuites name="Folder1" tests="2" time="0.197">
    <testsuite id="7dd4314e-4d2f-4277-a2a7-e35cc7550827" name="Req1" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.120">
      <testcase name="Response Code equal to 200 " classname="Req1"/>
    </testsuite>
    <testsuite id="4314d8ec-2c7c-4c7d-bbe7-9b0670ea0402" name="Req2" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.077">
      <testcase name="Response Code equal to 200 " classname="Req2"/>
    </testsuite>
  </testsuites>
  <testsuites name="Folder2" tests="2" time="0.211">
    <testsuite id="25eaf1d8-a3c0-4230-ac90-b425398ebba5" name="Req3" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.144">
      <testcase name="Response Code equal to 200 " classname="Req3"/>
    </testsuite>
    <testsuite id="368dcdb8-6b1d-4768-9a9e-7fbbfabf863b" name="Req4" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.067">
      <testcase name="Response Code equal to 200 " classname="Req4"/>
    </testsuite>
  </testsuites>
  <testsuite id="c4a70df3-54c2-43c5-a8a2-daff56c3f899" name="Req5" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.070">
    <testcase name="Response Code equal to 200 " classname="Req5"/>
  </testsuite>
</testsuites>
```

**Comment by franky1964** [comment]
Please see comment above

**Comment by rangav** [comment]
Ok based on your comments I have modified the proposed xml. is it good?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ColA" tests="5" time="0.479">
  <testsuite name="Folder1" classname="ColA.Folder1" tests="2" time="0.197">
    <testsuite id="7dd4314e-4d2f-4277-a2a7-e35cc7550827" name="Req1" classname="ColA.Folder1.Req1" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.120">
      <testcase name="Response Code equal to 200 " classname="ColA.Folder1.Req1"/>
    </testsuite>
    <testsuite id="4314d8ec-2c7c-4c7d-bbe7-9b0670ea0402" name="Req2" classname="ColA.Folder1.Req2" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.077">
      <testcase name="Response Code equal to 200 " classname="ColA.Folder1.Req2"/>
    </testsuite>
  </testsuite>
  <testsuite name="Folder2" classname="ColA.Folder2" tests="2" time="0.211">
    <testsuite id="25eaf1d8-a3c0-4230-ac90-b425398ebba5" name="Req3" classname="ColA.Folder2.Req3" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.144">
      <testcase name="Response Code equal to 200 " classname="ColA.Folder2.Req3" classname="Req3"/>
    </testsuite>
    <testsuite id="368dcdb8-6b1d-4768-9a9e-7fbbfabf863b" name="Req4" classname="ColA.Folder2.Req4" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.067">
      <testcase name="Response Code equal to 200 " classname="ColA.Folder2.Req4" classname="Req4"/>
    </testsuite>
  </testsuite>
  <testsuite id="c4a70df3-54c2-43c5-a8a2-daff56c3f899" name="Req5" classname="ColA.Req5" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.070">
    <testcase name="Response Code equal to 200 " classname="ColA.Req5"/>
  </testsuite>
</testsuite>
```

**Comment by rangav** [comment]
Also the comment says - no need to use `testsuites` when there only one `testsuite` child root node is there

> <testsuites> Usually the root element of a JUnit XML file. Some tools leave out 
> the <testsuites> element if there is only a single top-level <testsuite> element (which
> is then used as the root element).

**Comment by franky1964** [comment]
It looks quite good, could you please add the "assertions" property on "testcase" level?
And please provide an example with an error, since "failure type="AssertionError" hat to be changed as well:
 
![image](https://github.com/rangav/thunder-client-support/assets/58699432/2885c37b-1295-4804-8958-cb29f0e714d2)

**Comment by rangav** [comment]
Thanks for feedback. 

what are the values for `assertions` on `testcase` node? is it always 1

**Comment by franky1964** [comment]
You're right.
Set it to "1" and always sum up to above testusite level

**Comment by rangav** [comment]
Thanks for the clarification.

**Comment by franky1964** [comment]
**Sorry, one more idea:**
Could you add the full used URL for the request on the latest testsuite level:

property name="url" value="https:\\..."

**Comment by rangav** [comment]
sure will include url property also

**Comment by rangav** [comment]
Hi @franky1964 

I have published new version, please update CLI to `v1.8.2`

Please test and let me know what additional changes needed in xml report

**Comment by franky1964** [comment]
Hi @rangav, 
sorry for my late response, here some details to be corrected in the next version:

1. Only the root element can be "testsuites", all subnodes (the folder names and the request itself) are "testsuite" nodes
2. The property "url" has to be the filled with the real url for the request, means there should not be any variable listed anymore

![image](https://github.com/rangav/thunder-client-support/assets/58699432/8862e279-c043-4bf6-b68c-1530b1568d98)

**Comment by rangav** [comment]
Thanks @franky1964 for the feedback. Will fix in the next update.

Let me know if you need any other changes

**Comment by franky1964** [comment]
Hi @rangav,
there is indeed another enhancement which would be helpful to calculate a test coverage for our Rest API tests:

Could you please add on request level the property "method" and fill it with the used operaten, like "get, post, put, delete,..."

**Comment by rangav** [comment]
Sure will include. you want method name lowercase or uppercase?

Please confirm below format is good?

```xml
<testsuite method="GET" name="Req4"  id="368dcdb8-6b1d-4768-9a9e-7fbbfabf863b" classname="ColB.Folder2.Req4" timestamp="2023-10-20T12:37:48.885Z" tests="1" failures="0" time="0.067">
        <testcase name="Response Code equal to 200 " classname="ColB.Folder2.Req4" classname="Req4"/>
  </testsuite>
```

**Comment by franky1964** [comment]
I would propose lowercase as in Open API specs

**Comment by rangav** [comment]
One more clarification you want method name as child `property node` or `attribute` on testcase?

See the below format and please confirm

```xml
 <testsuite name="Req1" id="c288f51e-a621-4aba-bf36-fbe088143a07" tests="3" failures="1" assertions="3" time="0.198" timestamp="2023-11-01T08:32:09.127Z">
     <property name="url" value="https://www.thunderclient.com/welcome"/>
     <property name="method" value="get"/>
     <testcase name="Response Code equal to 200" classname="ColB.Folder1" assertions="1"/>
</testsuite>
```

**Comment by franky1964** [comment]
It should be a property

**Comment by rangav** [comment]
We have published a new version with all the changes requested. Please update CLI to v1.9.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

**Comment by franky1964** [comment]
I will give you feedback as soon as possible

**Comment by franky1964** [comment]
Hi @rangav,
everything works now as expected, if we need any further enhancements I will create a new feature request.

Brgds
Frank

**Comment by rangav** [comment]
Thanks @franky1964 for the confirmation.

We also added `skipped` attribute for number of skipped requests. Skip Request feature is released in [2.15.0](https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0)

**Comment by rangav** [comment]
Hi @franky1964 

looks like there is an issue with new format for nested xml report https://github.com/rangav/thunder-client-support/issues/1393

May be I have to revert back to non-nested format for xml report

How does the report look for you for nested folders?

**Comment by rangav** [comment]
<img width="735" alt="Screenshot 2023-11-07 at 18 42 30" src="https://github.com/rangav/thunder-client-support/assets/8637550/686b4705-a7bc-4324-9a95-94104ab6564e">

The issue is with classname value

The junit spec says the value should be same as testsuite name?
