### ISSUE TITLE
Export request to code feature

### ISSUE THREAD

**Issue by SpiffGreen** [rangav/thunder-client-support#1280]
**Please describe feature/problem details and solution you'd like.**
Most of the time one has made a request and will want it to be exported to a different programming language or something, so I'd like if its possible we can export code directly like for bash(curl), javascript, nodejs, c#, Java, python, etc

**Describe alternatives you've considered**
Currently I have to export to postman, and use its feature

**Your Team Size Using TC:**
3

**Comment by rangav** [comment]
Hi @SpiffGreen 

This feature is supported already

https://github.com/rangav/thunder-client-support#codegen
