### ISSUE TITLE
New subscription model breaks individual use case

### ISSUE THREAD

**Issue by MelGrubb** [rangav/thunder-client-support#1283]
**Describe the bug**
Starting today, it seems that the ability to use requests and environments from the thunder-tests folder is now locked behind a subscription model. I used this pretty extensively to keep requests isolated to the branches where the code they call lives, or to version my requests as the codebase evolves. I'm the only developer on my team that uses it, so this is hardly a "team edition" problem here. I've completely lost the ability to keep my queries on the branches where they're being developed.

More importantly. All my stuff is gone. All my requests and environments are now trapped in the thunder-tests folder with no way to retrieve them. I suppose I can copy/paste them back into wherever they'd normally go, but that's a huge miss on Thunder's part. Some kind of "want me to migrate that for ya?" would have taken some of the sting away, at least.

I came to Thunder because of the Postman's subscription model. And now Thunder has implemented one of its own. I am disappoint. 

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Your Team Size Using TC:**

**Comment by sindivegapps** [comment]
+ one

**Comment by rangav** [comment]
Hi @MelGrubb 

We announced subscriptions 90 days ago, If you don't like to pay for the subscription. You could have migrated to some other tool by now that suits your use case.

Complaining now does not seem to be fair. 

You can copy the collections and environments into the default location and everything will work.
https://github.com/rangav/thunder-client-support#storage

From September 20th free plan will have limited features. You can migrate to another tool before that.
https://www.thunderclient.com/pricing#compare

Let me know if you have any questions.

**Comment by MelGrubb** [comment]
https://hitchhikersguidetothegalaxy.wordpress.com/2006/04/09/beware-of-the-leopard/
