### ISSUE TITLE
Export Failing

### ISSUE THREAD

**Issue by MAliL1** [rangav/thunder-client-support#1288]
**Describe the bug**
Receive Error: **Failed to Export** when trying to export Collection or Env.

**To Reproduce**
1. Create a Collection or Env
2. Populate with request and/or Environment Settings
3. Select 3 dots beside collection or env, and select "Export"
4. Choose where to store exported collection or env and save
5. Receive Error: **Failed to Export**

**Expected behavior**
Expect export to save file at desired location without failing. This is so that this collection/env can be shared between others

**Platform:** 
 - OS: Windows 10 Enterprise
 - vscode version: 1.81
 - extension version: 2.10.2

**Your Team Size Using TC:**
Currently just me

**Comment by rangav** [comment]
Hi @MAliL1 Thanks for reporting the issue. Will look into it.

Can you try restarting vscode and export again?

**Comment by MAliL1** [comment]
Ah, it seems to be only happening when I save to my Documents Folder, If I save somewhere else, then export seems to work.

**Comment by rangav** [comment]
May be Documents folder has restrictions or access permissions issue

**Comment by MAliL1** [comment]
Yes, that is probably the case as I am using a company laptop. Thanks anyways
