### ISSUE TITLE
Input Problem typing Korean language 

### ISSUE THREAD

**Issue by bumjin** [rangav/thunder-client-support#129]
**Describe the bug**

Input Problem typing Korean language 
consnants duplicated
for example typing 'ㄱ' + 'ㅏ'  => 'ㄱ가' 
'ㄱ' is duplicated

**To Reproduce**

typing 'ㄱ' + 'ㅏ' => expected result  '가'
but 'ㄱ' + 'ㅏ' => 'ㄱ가' 

animated gif 
https://i.imgur.com/qLb5VTQ.gif

**Expected behavior**

typing 'ㄱ' + 'ㅏ' => expected result  '가'
but 'ㄱ' + 'ㅏ' => 'ㄱ가' 

**Platform:** 
 - OS: 
Window10, mac all same result
**Solution:**

**Comment by rangav** [comment]
Hi @bumjin thanks for reporting, will look into it.

**Comment by rangav** [comment]
I am closing this, as we already have a existing issue for this https://github.com/rangav/thunder-client-support/issues/161

You can add comments in the above issue.

**Comment by rangav** [comment]
I got it -` R and J ` letters right?

**Comment by bumjin** [comment]
i know other language support is difficult 
so thanks for attention whether this problem solved or not

there are some links  about korean alphabet

https://www.branah.com/korean  online korean keyboard
https://www.youtube.com/watch?v=19zJ5mKPaho&t=151s  how to type korean keyboard
https://rcneira.weebly.com/learn/reading-the-korean-alphabet-hangul  Combing the Alphabet to Form Syllables/Words

**Comment by bumjin** [comment]
bug not fixed. 
same result

typing  "중복"
=> 
result
"ㅈ주중ㅂ보복"

https://imgur.com/a/ZX41TFi

**Comment by rangav** [comment]
I will attach a new version in a minute

**Comment by bumjin** [comment]
Thanks very much.
Bug was Fixed!!

![image](https://user-images.githubusercontent.com/859787/162900677-741e2535-370e-4aee-bc53-8d65ccb97f45.png)

**Comment by rangav** [comment]
super thanks for confirming.

the update also also fixes below issues
- undo and redo issue #146
- inputs scroll issue #526

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
