### ISSUE TITLE
Selection not working as expected 

### ISSUE THREAD

**Issue by sidati** [rangav/thunder-client-support#1290]
**Describe the bug**
Something wrong the way selection works on JSON body

**To Reproduce**
Check the recording

https://github.com/rangav/thunder-client-support/assets/4185345/8c48d745-5efd-43c7-92d4-c701f8bf315f

**Expected behavior**
Normal Selection 

**Platform:** 
 - OS: MacBook Pro Apple M1 Pro
 - vscode version: 1.81.1 (Universal)
 - extension version: v2.10.2

**Your Team Size Using TC:**
1 (Startup Plan)

**Comment by rangav** [comment]
Hi @sidati Thanks for reporting the bug. Could be a font issue.

Did you change vscode font settings?

**Comment by lamula21** [comment]
I have the same issue. The issue is that the extension is not rendering well the fonts. Maybe could fix it by adding a feature to change the extension font family. I only see the font size to be changed

**Comment by rangav** [comment]
Can you share a screenshot of the editor font family below?

<img width="686" alt="Screenshot 2023-08-27 at 09 07 21" src="https://github.com/rangav/thunder-client-support/assets/8637550/7e93c710-e070-41d5-bea2-4e1b5e70ace5">

Thunder Client editor uses the vs code editor font family settings

**Comment by sidati** [comment]
> Can you share a screenshot of the editor font family below?
> 
> <img alt="Screenshot 2023-08-27 at 09 07 21" width="686" src="https://user-images.githubusercontent.com/8637550/263515907-7e93c710-e070-41d5-bea2-4e1b5e70ace5.png">
> Thunder Client editor uses the vs code editor font family settings
> 
> #### Try these solutions
> * [Offet inside the vscode thunderclient tab #1075 (comment)](https://github.com/rangav/thunder-client-support/issues/1075#issuecomment-1480943275)
> * [Error Copying Token from response body #1223 (comment)](https://github.com/rangav/thunder-client-support/issues/1223#issuecomment-1637231331)
> * [CURSOR ISSUE IN THE REQ BODY JSON FORMAT #888 (comment)](https://github.com/rangav/thunder-client-support/issues/888#issuecomment-1321970690)

I'm using **MesloLGS NF** font

**Comment by rangav** [comment]
Try use the default font or font that works with TC Editor and VS Code Editor

**Comment by sidati** [comment]
Can you make thunder use the configured font 🙏 ? that would be more convenient solution for me 😉

**Comment by rangav** [comment]
its already trying to configured font. Not all fonts work in both editors. Both are different editors.

**Comment by sidati** [comment]
Why not use VS Code editor engine 🤔 ?
