### ISSUE TITLE
"$" dollar sign in variable cuts of the rest of the string

### ISSUE THREAD

**Issue by ra100** [rangav/thunder-client-support#1291]
**Describe the bug**

When using `$` in a variable in .env file, it's not loaded correctly, string is cut before the `$`sign.

```env
# this is my env file
SOME_VARIABLE='abc$123'
```

When it's loaded as variable it's just `abc`. From `{{SOME_VARIABLE}}` will be in the request just `abc`.

**To Reproduce**

- Create env file as above
- add it to "Link to .env file"
- use the variable in some request - query, auth, headers...
- see it's cut off

**Expected behavior**

Whole string to be used.

**Platform:** 
 - OS: MacOS Ventura 13.5
 - vscode version: Thunder Client
 - extension version: v2.10.2

**Your Team Size Using TC:** 7

**Comment by rangav** [comment]
Hi @ra100 

you need escape the dollar sign - https://github.com/bkeepers/dotenv/issues/214#issuecomment-144181101

**Comment by ra100** [comment]
🤦🏼  it should have been obvious, to use `"` and escape instead of using `'` and not escape.

**Comment by rangav** [comment]
Closing this issue.
