### ISSUE TITLE
Cannot see my collections anymore

### ISSUE THREAD

**Issue by stefanstranger** [rangav/thunder-client-support#1292]
**Your Team Size Using TC:**
1

**Question:**
When I now go to my locally stored collections I don't see them anymore. It shows a message 'Subscription is required to use Git sync'

I've all my requests stored locally. How can I use my local collections again?

Do I also need a Subscription when have a custom location configured? 

After not using a custom location the subscription required was removed but how do I now import my old collections?

/Stefan

**Comment by rangav** [comment]
Hi @stefanstranger 

If you want to save in a custom location or git repo you need a subscription.

If you want to migrate to the **free version**, please follow the steps below
https://github.com/rangav/thunder-client-support/discussions/1286

If you want to **buy a subscription** - see plans
https://www.thunderclient.com/pricing#compare

**Comment by stefanstranger** [comment]
Ok I copied my thunderclient files from my custom location to the default location and now I see my collections again. Not completely sure why this requires a Subscription change. Is using a custom location to store your Thunderclient requests a feature that requires a Subscription fee? But still happy to continue using Thunderclient but the current license costs are bit too much for the times I use Thunderclient.

**Comment by rangav** [comment]
Please see the **free version limits** - https://www.thunderclient.com/pricing#compare

The subscription fee required to use all the premium features
- CLI
- Collections & Envs
- Collection Runner
- Git-Sync

**Comment by ddeepeshkumar** [comment]
I've create a basic script to migrate my Thunder-Client test-cases as `.http` files to be used with REST Client.
https://github.com/ddeepeshkumar/thunder-client-to-rest-client

**Comment by JohnCampionJr** [comment]
Yeah, I think your decision to put core functionality of locally stored test collections behind a paywall will be the end of your tool's popularity.   Not being able to include the collections data in open source projects and have anybody able to use it to test an API without the cost and hassle of a subscription is a total deal breaker.

**Comment by Sam-Lin-MillersLab** [comment]
I think it is fair to ask for support. However, $7 for business is a bit much IMO. This is not like you have to pay for cloud service. Github changes like $5 monthly. I have a hard time to sell it to my boss. I did try tho. Good luck with your project. There is nothing wrong to ask for support. There are other OSS like moq and core-js having the same issue. I hope everything works out for you. I think I will move to httpYac or Rest client. Sorry mate.

**Comment by andremacola** [comment]
At least one option to perform the migration more easily within the project. For those who have multiple projects on the machine, this is a problem. It's okay to charge for the extension, but do it responsibly.

**Comment by rangav** [comment]
Free Version Limits
https://www.thunderclient.com/pricing#compare

Also, see the link above to see what features are available in the paid version.
