### ISSUE TITLE
URGENT: Error loading webview on Thunder client v2.10.3

### ISSUE THREAD

**Issue by azvyae** [rangav/thunder-client-support#1293]
**Your Team Size Using TC:** 15

**Question:**

When running this extension on latest version `v2.10.3` it appears showing error on the vscode:

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by rangav** [comment]
Hi @azvyae Please restart vs code and try again.

If an error is still there, please downgrade to v2.10.2

**Comment by azvyae** [comment]
Ok, sorry for the attention. I though by just reloading the window can help to reload the extension. I guess we have to fully restart the vscode by closing the app first

**Comment by rangav** [comment]
no problem, thanks for confirmation.
