### ISSUE TITLE
Execution Sequence of Scripts and Tests in Runner is wrong

### ISSUE THREAD

**Issue by MarSu64** [rangav/thunder-client-support#1294]
I'm trying to set up a sequence of REST-Requests.
1. Request to retrieve a list of IDs
2. and 3.: For every ID get different details and list them

So far i got this working by setting up the following:
Collection
-> Folder1
---> Request1 (getIdList)
---> Folder2
------> Request2 (getDetails1)
------> Request3 (getDetails2)
      
For every Request I wrote a Pre_Request Script to set up some variables and
a Test Script to evaluate the Response Body.

If I use the "Run All" on Folder2 and set up Request1 as Pre Request with 
Condition "Run Only Once" it works nearly perfect.
Except the execution sequence of the different scripts.
1.  "Request2 Pre-Request script"
2.  "Request1 Pre-Request script"
3.  "Request1"
4.  "Request1 Test script"
5.  "Request2"
6.  "Request2 Test script"
7.  "Request3 Pre-Request script"
8.  "Request3"
9.  "Request3 Test script"
10. "Request2 Pre-Request script"
11. "Request2"
12. "Request2 Test script"
13. "Request3 Pre-Request script"
14. "Request3"
15. "Request3 Test script"
16. and so on beginning by 10. for every iteration.      

I'm wondering, why "Request2 Pre-Request script" is executetd first. I did not expect that.

Bonus: If I define a Pre-Request script for a Folder, regardless where I put it (Folder1
or Folder2) it is executed in front of every iteration. I do not expect that either.

Can you please give me a hint on how to build a correct Sequence of Requests. Or is this
impossible in TC.

Feature Request: It would be nice to set the number of iterations for a 
                 Folder/Collection Run via a Pre-Request Scipt.

**Comment by rangav** [comment]
Hi @MarSu64  Will verify and get back to you.

**Comment by rangav** [comment]
Hi @MarSu64 

Since you are running `Folder2`

- The first request in `Folder2` is `Request2`
- First It will execute `pre-request script`
- Then it will execute `Pre Requests`
- So you will see `Request 2` `Pre Request Script` first

Hope the above clarification is useful.

**Comment by MarSu64** [comment]
Hi @rangav ,
thanks for the clarification and the link to the feature request. Other people have other demands ;-).  Therfore I have to look for another solution to my problem.
On the other issue (set iterations): Is there an elegant way to stop a "Run all" on a folder on any other conditions than "all iterations are done" or "Stop on Fail"? Then IO could set the iteration to a high number and stop the Runner depending on a condition like "no more IDs".

Best regards
Martin

**Comment by rangav** [comment]
Sure, Can you please create a new feature request, Will add to roadmap.

**Comment by rangav** [comment]
Hi @MarSu64 

I think you can stop the Folder/Collection runner now.

Please follow the below steps:

- Select `Stop On Fail` on Run Folder
- Add a Test Assertion that Fails using code based on your custom condition - https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0
- Add the above Test filter in `Post Request Script `

Example Test
```js
function testFilter() {
    var condition = "<custom condition>";
    if(condition) {
         tc.test("Stop the collection runner", false);
    }
}

module.exports = [testFilter]
```

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
