### ISSUE TITLE
Including RequestId in tc object

### ISSUE THREAD

**Issue by Elitek6** [rangav/thunder-client-support#1298]
**Please describe feature/problem details and solution you'd like.**
For some of our scripts we need to get the request ID. 

Please include the request ID in the tc object. 
See also here: https://github.com/rangav/thunder-client-support/discussions/1297

**Describe alternatives you've considered**
Can't use an alternative. 

**Your Team Size Using TC:**
~20

**Comment by rangav** [comment]
Thanks, @Elitek6 for creating the feature request, Will add it to the roadmap.

**Comment by rangav** [comment]
Is it possible to know your company name?

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.11.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.11.0

Please let me know your feedback.

**Comment by erwinmoretz** [comment]
Hi @rangav, 

i have a question to this implementation. 

i got an id from my request and try to use it in customFilter with tc.runRequest("id"). 

<img width="352" alt="image" src="https://github.com/rangav/thunder-client-support/assets/112586589/1e147824-7231-400f-8994-74731a187caa">

<img width="347" alt="image" src="https://github.com/rangav/thunder-client-support/assets/112586589/e14bbeb1-a2c4-4a37-b9bb-d881a21e7328">


But its not working for me in Collection Runner and CI/CD. 

Could you give me an example, how to use it, and is it possible to get the request id without the method tc.request.id?

**Comment by rangav** [comment]
did you use `await `keyword - `await tc.runRequest("id")`

**Comment by erwinmoretz** [comment]
No, i didnt. :o I'll try it and will give you feedback.
