### ISSUE TITLE
typed url text coverts to html symbol

### ISSUE THREAD

**Issue by scott-scott** [rangav/thunder-client-support#13]
**Describe the bug**
I was typing in a filtering argument on my url, and it was automatically converted to the equivalent HTML symbol. 

**To Reproduce**
in the URL box, I started with https://example.tld:1234/endpoint, then added ?order=timestamp&timestamp.gt...
except that as soon as I complete typing &times it converts it to × and jumps to the beginning of the url string.
I also tested this with other valid html symbol codes and see the same behavior, for example &aring 
see https://www.htmlsymbol.com/html-entities/ for more examples

**Expected behavior**
let me type my argument without converting and moving the cursor

**Platform:** 
 - OS: Win10

**Solution:**
I don't see the code available, but I assume something is parsing the url string and trying to keep it safe. It should probably ignore &codes

**Comment by rangav** [comment]
Hi @scott-scott i was able to reproduce the bug, will look into it.

**Comment by bwf-git** [comment]
I have a similar problem when adding a query parameter.  Adding for example &para=true converts the &para to the html symbol for paragraph.

**Comment by rangav** [comment]
Hi @scott-scott and @bwf-git this is now fixed, will be part of next update v1.1.0, more details here - #14

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14
