### ISSUE TITLE
Support for adding client certificate when using mutual TLS

### ISSUE THREAD

**Issue by bhavesh4898** [rangav/thunder-client-support#130]
**Is your feature request related to a problem? Please describe.**
I don't seem to find a way to specify client certificate and private key which is needed to establish TLS handshake with my server that requires mutual SSL.

**Describe the solution you'd like**
A settings page/tab that allows to add cert and pk in any standard format (PEM, DER, PKC12 anything would be fine)

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @bhavesh4898 will add to roadmap.

**Comment by jhon-conner** [comment]
@rangav 
That's ok. Thanks.   
Postman can do this, but i can't find where the option is. First time when accessing api without client certification, postman poped up an dialogue with a hint. After choosing 'ignore', api can be accessed successfully.
Maybe domain level option is a good idea.

**Comment by rangav** [comment]
HI @jhon-conner  I am using got.js for http request, i already set the option `rejectUnauthorized: false,` so it should ignore the ssl errors already.

https://github.com/sindresorhus/got

**Comment by ANANDHAKUMARS** [comment]
I cant get where to add client certificate. can anyone give the steps ?

**Comment by rangav** [comment]
Hi @ANANDHAKUMARS this feature is not implemented yet, is in the roadmap. May be include this for next update

**Comment by ghokun** [comment]
Is the following error in scope of this issue ? I have self signed oauth2.0 server that I can not get bearer tokens with thunderclient.
> Error: self signed certificate in certificate chain

**Comment by rangav** [comment]
Hi @ghokun can you please create a new issue and provide more details I will look into it. Thanks

**Comment by rangav** [comment]
Hi all, this feature will be part of next update v1.7.0

**Comment by rangav** [comment]
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

Still documentation update is pending.
