### ISSUE TITLE
How to handle optional query parameters in endpoint url

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1303]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
What would be the best way to handle optional query parameters in an endpoint url?

With postman it was very easy by scripting in a "Pre-request Script":
**if (pm.variables.get('begin')) pm.request.url.query.add({key: 'from', value: pm.variables.get('begin')});**

**Comment by rangav** [comment]
Try using the env variable in value e.g `beginQuery` and the initial value to empty or any other value as required.

then in the code
```js
let begin = tc.getVar("begin");
if(begin)
{
   tc.setVar("beginQuery", begin);
}

**Comment by rangav** [comment]
We can provide additional API if that helps

proposal - updates or add query param with value
```js
tc.setParam("name", value);
```

**Comment by franky1964** [comment]
Hi @rangav,
I did not succceed in using your proposed solution, since the variable cannot be added as a fix query param in request definition.
Therefore I would agree to get an additional API calls for adding a query parameter dynamically...

**Comment by rangav** [comment]
Sure will add to the roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.11.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.11.0

Please let me know your feedback.

**Comment by franky1964** [comment]
Hi @rangav,
I checked the new function but the URL isn't enhanced with my dynamically added query params.

I used this code in prescript:

    if(status && status !== 'None') {
        tc.setParam("status", status);
        console.log("Set param 'status' to: ", status);
    }
    
 Code was executed (as seen in console log) but the Request URL does not have the param 'status' included...

**Comment by rangav** [comment]
Let me verify and get back to you.

**Comment by rangav** [comment]
There was a bug, Fixed it now.

Please update extension to - **v2.11.1**
Update CLI to - **v1.4.13** - `npm i -g @thunderclient/cli`
