### ISSUE TITLE
How to specify path to external scripts in a CI/CD Pipeline?

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1308]
**Your Team Size Using TC:**
Expected team size is: 10-15

**Question:**
How to specify path to external scripts in a CI/CD Pipeline?

We are working in a CI/CD Pipeline with tc and our external scripts are not found...

![image](https://github.com/rangav/thunder-client-support/assets/58699432/0305fc21-c27e-432f-9e85-d0c556eb17c4)

Our scripts are located in a subfolder "scripts" parallel to the folder "collections"
![image](https://github.com/rangav/thunder-client-support/assets/58699432/8eeb95d1-6ae0-451e-ba16-0a39d88fbe47)

In the collections itself we are using a relative path:
![image](https://github.com/rangav/thunder-client-support/assets/58699432/85467ecb-9015-4423-adac-24434eddfc38)

Problem: No exported module is found!

**Comment by rangav** [comment]
Hi @franky1964 

You need to enable the `save to workspace` setting. This is a paid feature.

Once you enable this setting, the extension will calculate the correct relative path for scripts.

**Comment by rangav** [comment]
Can you please confirm - whether is your company using a paid version or a free version?

**Comment by franky1964** [comment]
Hi @rangav,
yes since 2 days we have paid version.

**Comment by rangav** [comment]
Thanks @franky1964 got your email.

**Comment by rangav** [comment]
Please try this solution https://github.com/rangav/thunder-client-support/issues/1308#issuecomment-1699115945

let me know your feedback

**Comment by franky1964** [comment]
Hi @rangav,
it works as expected.

**Comment by rangav** [comment]
Thanks @franky1964 for confirmation.
