### ISSUE TITLE
Requests should not be executed on failure of pre request script

### ISSUE THREAD

**Issue by azplanlos** [rangav/thunder-client-support#1309]
**Please describe feature/problem details and solution you'd like.**
Requests should not be sent if there is an exception or failure of the corresponding pre request script. This could easily lead to unpredictable responses and inconsistencies on the API side. In my point of view it would be better to show an error rather than executing the request with wrong data if the pre request script didn't run till the end. Also looking up the debug information only shown in the log output is not obvious enough if the request is still executed.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.13.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.
