### ISSUE TITLE
bug while requesting query  

### ISSUE THREAD

**Issue by rizwan777** [rangav/thunder-client-support#131]
**Describe the bug**

In VScode i'm trying to query request with parameters its not working correctly.
for example if i want to pass username and password on API using query parameter
if password contains "#" its omitting part after # which is totally wrong.

example : password ==> admin#12345
its just sent password value in request "admin". part after "#" was skipped.

**To Reproduce**

request with any method (GET,POST,PUT,etc)
**Expected behavior**

While Requesting any url; its should need to encode query string values if its found some spacial characters in query parameter.
**Platform:** 
 - OS:  Windows 10 license version.

**Solution:**

encode query parameter values if special character are mention in actually request.

**Comment by rangav** [comment]
Hi @rizwan777 thanks for reporting i will look into it.

**Comment by rangav** [comment]
Hi @rizwan777  use `%23` to escape in the meanwhile, i will fix this in the next update.

**Comment by rangav** [comment]
This is now fixed in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
