### ISSUE TITLE
How to use Custom Filter readFile in CI/CD

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1310]
**Your Team Size Using TC:**
10-15

**Question:**
Hi @rangav, 

i've tried the custom filter readFile for schemavalidation in lokal tests. afterward i've tried this test in CI/CD Pipeline and its not working for me. 

if i save the schema direct in the env-variable it works. if i reference a file as a schema the test wont work. i tryed it with an absolute path & a relative path. 

Screenshot from working schemavalidation with schema as a variable. 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/224d626d-92eb-40ac-88f4-3258a9cb211d)

im using a paid license.

**Comment by rangav** [comment]
Hi @erwinmoretz will share an example screenshot in a few minutes.

Can you share your company name using the below link? The info is useful internally.
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
Env Variable: path should be relative to root of the project
<img width="530" alt="Screenshot 2023-08-31 at 11 12 25" src="https://github.com/rangav/thunder-client-support/assets/8637550/26eaf6d4-29a9-4a34-ac1d-86a2abb1fdbc">

<img width="1255" alt="Screenshot 2023-08-31 at 11 13 16" src="https://github.com/rangav/thunder-client-support/assets/8637550/2d6c7e56-4ade-4800-af2a-5c1ab35532d9">

**Comment by erwinmoretz** [comment]
The setting "save to workspace" is active. We share and work in one repo. 

the file is saved in the same root and the relative path i copied from VSCode. Here is a Screenshot how the Variable is saved: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/19c6413b-f6a1-46a5-9680-d6c70fed9bdb)

**Comment by rangav** [comment]
Are you on windows or mac?

**Comment by rangav** [comment]
When you run the same request in Extension UI you will see below [logs](https://github.com/rangav/thunder-client-support#logs)

<img width="704" alt="Screenshot 2023-08-31 at 12 10 49" src="https://github.com/rangav/thunder-client-support/assets/8637550/1521cf77-2539-4d8e-8423-c3b99cac3b57">

**Comment by erwinmoretz** [comment]
im using a windows. 

The Schemavalidation with readFile and (absolute or relative) path works in local test runs. The problem is in the ci/cd pipeline test run. 

Screenshot of the log: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/3a03aeb8-e772-4b8d-b26e-410a2d55e193)

**Comment by rangav** [comment]
Look like validation failed, but the validation errors are not displayed in CLI.

**Comment by rangav** [comment]
Will test here on my CI/CD and get back to you later today.

**Comment by rangav** [comment]
One Clarification: Do you have `comments` in schema json file? From the error you shared seems like JSON parse error

**Comment by erwinmoretz** [comment]
There are no comments in the json schema file.

**Comment by rangav** [comment]
Thanks for confirmation

**Comment by rangav** [comment]
Can you also verify is this related multi root workspace issue - https://github.com/rangav/thunder-client-support/issues/1312#issuecomment-1702446393

**Comment by rangav** [comment]
I have tested in the CI/CD, The paths are working on Mac but not on Windows. I will fix it later today.

**Comment by rangav** [comment]
Actually its not a bug - You need to enable `Save To Workspace` in  .vscode/settings.json setting then it works.

- Follow this steps for multi-root workspace - https://github.com/rangav/thunder-client-support/issues/1312#issuecomment-1702446393

run command - `tc --debug` then you should see below

<img width="491" alt="Screenshot 2023-09-04 at 10 10 25" src="https://github.com/rangav/thunder-client-support/assets/8637550/8ca0d361-b5be-43ad-b436-b78b1f877a96">
