### ISSUE TITLE
Unable to access/open the extension

### ISSUE THREAD

**Issue by Digital-Ishan** [rangav/thunder-client-support#1311]
Type: <b>Bug</b>

Unable to import or create new request on thunder client. Nothing is working, just able to see 

Extension version: 2.10.5
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.70GB free)|
|Process Argv|--crash-reporter-id 02afc286-8d7b-48cc-9a01-1bfd63e3cd0e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571

```

</details>

**Comment by rangav** [comment]
Hi @Digital-Ishan 

Are you seeing this screenshot below?
<img width="282" alt="Screenshot 2023-08-31 at 11 21 48" src="https://github.com/rangav/thunder-client-support/assets/8637550/7586501a-1286-49cd-9326-75c12d19b796">

**Comment by Digital-Ishan** [comment]
Yes

**Comment by rangav** [comment]
Git-Sync is a paid feature now. You can purchase a subscription to use this feature or migrate to free version.
- Announcement Link - https://github.com/rangav/thunder-client-support/releases/tag/v2.7.0

**Migrate to the free version guide**
- https://github.com/rangav/thunder-client-support/blob/master/docs/free-version.md

Let me know if you have any questions

**Comment by Digital-Ishan** [comment]
In the below image do I enter the local location in all 4 locations and restart but still not working...
![image](https://github.com/rangav/thunder-client-support/assets/142867862/4d999ed0-0afc-4c9a-afaf-586963bddf72)
 Local location:- %APPDATA%\Code\User\globalStorage\ankit.vscode-thunder-client

**Comment by rangav** [comment]
If you want to move to the free version and stop using git-sync feature please follow the below steps

Step1: Move the collections and environments folders to the [default location](https://github.com/rangav/thunder-client-support#storage)

Step2: **Disable/Remove** - git sync settings in vs code ( see below image )

Step3: Restart vs code and you should see all the data.

**Comment by rangav** [comment]
You should disable or remove all the vscode settings in this image - https://github.com/rangav/thunder-client-support/issues/1311#issuecomment-1700825955

**Comment by AaronLayton** [comment]
Whilst I see the need to generate income, this is such a poor step back to draw people in and then lock down previously free features 😑

Is there a way to just install the version just before this release?

**Comment by rangav** [comment]
@AaronLayton our terms prohibit installing the previous version
