### ISSUE TITLE
Customize the response limit in CI/CD

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1312]
**Please describe feature/problem details and solution you'd like.**
In our tests we have Responses that are bigger than the actual limit allows. There is a limit for the tc.report set on 100kb. 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/ccdb2257-bd29-4e3c-b61c-fba801fc0eb4)

in one response we expect a size of 860 kb. There are are even bigger responses for other tests. 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/cd334289-c6bd-48c8-bcbf-0a2ac032de4c)

Could you implement a feature, where we can set the limit for our own?

**Describe alternatives you've considered**
For runs in the pipeline we have to save the response in a file, to analyse the response if there are errors. 

**Your Team Size Using TC:**
10-15

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.11.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.11.0

Please let me know your feedback.

Please use the setting - `Html Report Response Limit`

**Comment by rangav** [comment]
The above setting is published in Extension, Will publish new release shortly in CLI

**Comment by erwinmoretz** [comment]
I'll give you feedback, when i tried it out :-)

**Comment by rangav** [comment]
I have published CLI, Please update CLI to `v1.4.11`

The `Html Report Response Limit` should be `workspace` scope

Let me know your feedback.

**Comment by erwinmoretz** [comment]
Could you give me an example how i adjust the size of the limit? 
I've downloaded the new Version and in the cli there is not documentation for this feature. 

in the extension i found the option.

**Comment by rangav** [comment]
Open VS Code settings and search `Thunder Client Html` - see image below
<img width="801" alt="Screenshot 2023-09-01 at 09 49 17" src="https://github.com/rangav/thunder-client-support/assets/8637550/8fa4fb1f-0fb1-454c-b155-86dcfc005421">

**Comment by erwinmoretz** [comment]
i explained wrong, sorry. 

My Setting in the extension is working. I set the limit on 2000kb. But in the CI/CD the Result is the following: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/3c6b31dd-cdd5-4973-b212-45ef64e241bd)


So my thoughts were, that i have to set the limit on a higher value in the CI configuration. Like the log level. 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/2df0281c-4b6c-4af9-be97-d446e3a82b33)

**Comment by rangav** [comment]
- Please update CLI to `v1.4.12`
- and run `tc --debug` and share screenshot

**Comment by erwinmoretz** [comment]
i found out, that the update function is not working. 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/6ca21e86-5d12-4bf9-824d-899aaff44319)


earlier i just typed tc in the cli and it updated. Now its like in the screenshot: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/9057699f-f823-4c9f-9d34-b69048adb476)

**Comment by rangav** [comment]
run this - `npm i -g @thunderclient/cli` to update

**Comment by erwinmoretz** [comment]
Screenshot from debug: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/37d6d348-4511-443e-b2c0-1af2bf79212e)

Screenshot from extension settings:
![image](https://github.com/rangav/thunder-client-support/assets/112586589/187c9b6d-71bb-4373-b42e-a4227ea84daa)

**Comment by rangav** [comment]
you can see from screenshot - `Html Report Response Limit` setting not set correctly

**Comment by erwinmoretz** [comment]
the setting in extension:
![image](https://github.com/rangav/thunder-client-support/assets/112586589/8715ae1d-8070-4e0c-9d43-198af8d43c00)

**Comment by rangav** [comment]
is it workspace scope?

**Comment by erwinmoretz** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/112586589/ebf42866-e0b6-429e-87e0-c52176aae5da)
![image](https://github.com/rangav/thunder-client-support/assets/112586589/06313669-029a-4034-9439-8b8cec64fe6f)
![image](https://github.com/rangav/thunder-client-support/assets/112586589/3f41cabb-533e-4df3-8863-d7aebc175098)

**Comment by rangav** [comment]
still missing something

can you share the values in `tc_evaluation/.vscode/settings.json`

<img width="482" alt="Screenshot 2023-09-01 at 10 16 41" src="https://github.com/rangav/thunder-client-support/assets/8637550/18c2eb4a-5b47-46eb-bf02-e57bb37f34d0">

**Comment by erwinmoretz** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/112586589/c902001a-58dc-4167-930b-b1950235e973)

**Comment by rangav** [comment]
Oh ok, you have multi root workspace.
Multiroot workspace **will not work in CI/CD**, This concept is relevant to VS Code only.

- I think you need to open `D:/VS Code/tc_evaluation` project in vscode
- Then set the `htmlReportResponseLimit` for this workspace again
- And try CLI gain

**Comment by erwinmoretz** [comment]
Hi Rangav, 

it worked for me. 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/77afd80f-c449-4753-bbd9-0ee7f08b13c6)

**Comment by rangav** [comment]
Thanks @erwinmoretz for confirmation.

We fixed another bug:
- Update Extension to v2.11.1
- Update CLI again to v1.4.13

**Comment by erwinmoretz** [comment]
Good Morning Ranga,

i have a Problem with the Response Size: 
- Settings in Workspace and Folder are the same. 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/ca36e78f-e05b-4ae4-8bed-4f2956ae92a4)

- CI accepts the configuration
![image](https://github.com/rangav/thunder-client-support/assets/112586589/e89efb9a-1497-403a-bade-bf5a1ff83d2d)

- Report gives me an other Result for Response
![image](https://github.com/rangav/thunder-client-support/assets/112586589/4e0f825e-309f-447d-ba39-eff0c4d1c055)

Do you have an idea, what am i doing wrong?

**Comment by rangav** [comment]
The response is displayed only for the first 10 iterations. Do you have iterations?

**Comment by erwinmoretz** [comment]
there is only 1 iteration: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/e588b5eb-d191-4981-a522-c02e799054a1)

i think its just a wrong error message. the response size is >2mb: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/51958f6b-a089-4b86-8c64-9588f845962f)


is it possible to overwrite the response limit in the setting.json?

**Comment by rangav** [comment]
Oh, your API response size as 9MB, Currently the max limit is 2MB.

What could be the max response Limit for your APIs? I will increase the limit

**Comment by erwinmoretz** [comment]
actuall the max response Limit is about 20mb. 

thanks for your help!

**Comment by rangav** [comment]
I published a new version now - `v2.12.0`.

- We have increased the limit option to 20MB. 

Dont know if it will work for large response size limits. Please test and let me know your feedback.

**Comment by erwinmoretz** [comment]
With 10mb its working. it just need some time to load the full TC Report. 

Thanks!
