### ISSUE TITLE
Using chai module in CI/CD

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1313]
**Your Team Size Using TC:**
10-15

**Question:**
Hello @rangav, 

for our tests we use the module chai to expand our tests in the testscripts/filter. 

for local tests we load the module and we can use it.
![image](https://github.com/rangav/thunder-client-support/assets/112586589/7d4f9023-3d8d-473d-a0f6-0aa277e77204)

we would like to use this module in ci/cd but there is a problem for us. 
In gitlab-ci.yml we define the installation of the module: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/6e50aa57-dfcc-4f39-8d0b-8c548adaa25a)

But when we try to execute some tests, it wont work. We found out that in the local cli it works perfect: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/b513c272-7d44-492a-aad9-4ebb0282dea4)

in the ci/cd pipeline we dont get a such a response like in the screenshot before: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/3b499002-a91a-43cd-827e-65150a2614c4)

Do you have any suggestions how we can use the module properly?

**Comment by Artem0ne** [comment]
The installation of Chai in Pipeline is here:
![image](https://github.com/rangav/thunder-client-support/assets/59470703/1997b807-80e9-498a-8cc5-ff9f3fc8dc3b)

**Comment by erwinmoretz** [comment]
i tried ur suggestions, but without success :/ 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/326377e4-0def-4590-ab91-e692be743a14)

it wont create the test: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/95f5e209-30de-4d5c-a6ad-08f4c665571d)

**Comment by rangav** [comment]
I have tested in the CI/CD, and The Chai tests are working for me on GitHub Actions.

**Comment by erwinmoretz** [comment]
hmm, then i have to search, where the issue is. 

have you loaded the Chai module while starting the Pipeline or do you load the module in function. :-)

Loading via gitlab-ci.yml: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/c6f22ad0-9859-4009-a9ad-597daa319c0e)


or loading the module in function/filter: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/e313b10a-cf85-4d44-830d-aca7c7408623)


both Variants does not create a Test in the run for me :/

**Comment by rangav** [comment]
Dont need to install the node module separately.

you should only use the tc.loadModule in the function. And Thunder Client will take care of downloading and installing the module

**Comment by erwinmoretz** [comment]
i'll try it later and will give you a feedback. Thanks for your help!

**Comment by erwinmoretz** [comment]
So i tried your suggestion: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/be228010-7a91-4f13-aa9e-0b30b7c0ea58)

Testcase in TC Client: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/7df977fa-63d8-4161-b9eb-4a92cda77d5a)

Filter: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/eaad123b-ac0a-4aa0-b505-9ac59351392b)

Testresult: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/adf514cf-f060-4866-bdff-611648f06a67)

other defined functions/filter in the same script are working... I cant get a simple testcase with chai in ci :/

**Comment by rangav** [comment]
I will share a sample collection file that is working for me. You can test it in your CI/CD and let me know.

**Comment by rangav** [comment]
Can you testing without chai library first whether its working or not.

```js
function testFilter() {
    let success = tc.response.status == 200;
    let json = tc.response.json;
    let containsThunder = json.message?.includes("thunder");

    tc.test("Response code is 200", success);
    tc.test("Response contains thunder word", containsThunder);
}
```

**Comment by erwinmoretz** [comment]
you can see how i created the test in these screenshots: https://github.com/rangav/thunder-client-support/issues/1313#issuecomment-1705060208

**Comment by rangav** [comment]
```js
async function customFilter() {
    console.log("Loading node module - moment");

    var moment = await tc.loadModule("moment");

    console.log(`Date - ${moment().format()}`);
}
```

can you test whether you can load moment module?

**Comment by erwinmoretz** [comment]
soo i changed a bit in my async function and i think the problem is anywhere in this red box: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/136fee4c-5a09-4b8d-8946-89f1c27d5238)


The Console.log was earlier after the loadModule and didnt appeared in the ci logs. After I changed them, the showed up in log:

![image](https://github.com/rangav/thunder-client-support/assets/112586589/008565d3-040b-4b85-b131-2e73804519fd)

**Comment by rangav** [comment]
can you add another console log after this line - `let expect = chai.expect`

**Comment by rangav** [comment]
also can you test with `assert` function in chai 
```js
async function testChaiFilter() {

    // loading external chai module
    var chai = await tc.loadModule("chai");
    let assert = chai.assert;
    tc.test("Response code is 200", function () {
        assert.equal(tc.response.status, 200)
    })
}
```

**Comment by erwinmoretz** [comment]
Ok, i added the log and added the function of loading moment module in other test: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/8bdaa1a8-3468-4401-83ef-0fea46ccbbc8)

Result in Logs: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/bcb4e8c0-ae4b-4c03-b578-8cc8db034d8e)


the log for chai module is missing

**Comment by rangav** [comment]
looks like you have an issue with the load Module. 

can you please confirm the below

1. loadModule working from extension - yes/no?
2. loadModule working from local CLI - yes/no?
3. loadModule working from CI/CD - yes/no?

**Comment by rangav** [comment]
`console.log(`Date - ${moment().format()}`);` this log is missing?

**Comment by erwinmoretz** [comment]
No its showing up: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/a611a8f7-1af8-48d9-874e-394d504e3d9d)

**Comment by erwinmoretz** [comment]
The problem is with loading the Chai Module. Moment Module loading works.

**Comment by rangav** [comment]
That is first console log in moment and there is 2nd console log that is missing?

**Comment by rangav** [comment]
Are you available tomorrow to schedule a call to investigate further?

**Comment by erwinmoretz** [comment]
yes, you are right. the second log is not showing up.

The missing console log is: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/40af584a-a538-4d27-836f-ffec1ad3bd87)

and:

![image](https://github.com/rangav/thunder-client-support/assets/112586589/e70defe9-724a-4bc4-9e44-5414cb6cd43a)

**Comment by rangav** [comment]
Yes i am available that time.

can you send calendar invite with time that suits you to my previous email.

**Comment by erwinmoretz** [comment]
I've send you the invite. Thanks for your help!

**Comment by rangav** [comment]
We will use this test collection, env and script file.

[thunder_client_test_cli.zip](https://github.com/rangav/thunder-client-support/files/12524074/thunder_client_test_cli.zip)

**Comment by rangav** [comment]
Hi @erwinmoretz 

The `chai library` is now built into the extension in new update
- Update Extension to **v2.11.4**
- Update CLI to **v1.5.2**


New example code to use `chai` module
```js
var chai = require("chai");
var expect = chai.expect;
var assert = chai.assert;

async function testChaiFilter() {

    tc.test("Response code is 200", function () {
        assert.equal(tc.response.status, 200)
    })

    tc.test("Response code expect to be 200", function () {
        expect(tc.response.status).to.equal(200);
    })
}

module.exports = [testChaiFilter]
```

Please test and let me know your feedback

**Comment by erwinmoretz** [comment]
Hi @rangav, 

thanks for your implementation and for your Support! 
We tested the new CLI in our CI/CD and the new solution worked for us.

**Comment by rangav** [comment]
Thanks @erwinmoretz for confirmation.
