### ISSUE TITLE
Problems saving request

### ISSUE THREAD

**Issue by jsantos74** [rangav/thunder-client-support#1314]
Saving requests is random some times it save the changes sometimes it doesn't. 
If you make a mistake in the body there is no undo button and the changes made are permanent due to a random save.
 
Can't find a way to reproduce the behavior.

An option to save the request when the user wants will be awesome.

 - OS: Windows  11
 - vscode version: 1.81.1
 - extension version: 2.11.0

**Comment by rangav** [comment]
Hi @jsantos74 

Uncheck this setting and then you save when ever you by using `Crl/Cmd+s`

<img width="936" alt="Screenshot 2023-09-01 at 10 32 02" src="https://github.com/rangav/thunder-client-support/assets/8637550/d42621d3-4911-4a36-8940-210c802559ff">

**Comment by rangav** [comment]
Did you use the above setting and try?
