### ISSUE TITLE
How to do console log in thunder client 

### ISSUE THREAD

**Issue by samir-ware** [rangav/thunder-client-support#1315]
Hey team 
I am using thunder client to fire bunch of APIs through collection and it works absolutly well. 
I just have one question , how can I flush out certain API details on console or in test UI in thrunder. 
e.g. After firing bunch of APIs in sequence I get a a request token and I want to log it somewhere so that users of my collection can grab it and use it during development . In postman I used console.log in test and it got printed on console. How can I do same in Thunder client

**Comment by rangav** [comment]
Hi @samir-ware 

- The logs will be displayed in `Output` window - https://github.com/rangav/thunder-client-support#logs
- Check logs to see if that has the info you ae looking for.
- You can use scripting and use console.log - https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by m3dbedb** [comment]
I use 2.19.2 and don't see any data in output when a sens request with 
`console.log("delayed for 5 seconds");`
in scripting tab

**Comment by rangav** [comment]
@m3dbedb see screenshot below

<img width="743" alt="Screenshot 2024-03-05 at 13 44 32" src="https://github.com/rangav/thunder-client-support/assets/8637550/9029f022-416f-4bc9-9649-cd1d11be0f28">
