### ISSUE TITLE
How to use post script

### ISSUE THREAD

**Issue by craftzneko** [rangav/thunder-client-support#1316]
**Your Team Size Using TC:**

**Question:**
Really struggling to understand how a script takes input. Using this JS code

```js
function writeNameToFile(responseBody) {
    const fs = require('fs');
    const responseJson = JSON.parse(responseBody);
    const name = responseJson.name;
    fs.writeFileSync('C:\Drop\names.txt', name);
}
```

But the responseBody appears empty.

**Comment by rangav** [comment]
Hi @craftzneko where are you using this code? Is it pre-request or post-request or in Env Variables?

**Comment by craftzneko** [comment]
@rangav cheers for advice, still getting an error

Error in Custom Filter: writeNameToFile - The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

are there any examples using this tc object and how to manipulate? Cheers

**Comment by rangav** [comment]
Where are you using this filter/script? can you share screenshot?

**Comment by craftzneko** [comment]
Just got it working now using this

function writeNameToFile() {
  const fs = require('fs');
  const responseJson = tc.response.json;
  const names = responseJson['access-layers'].map(layer => layer.name);
  const namesString = names.join('\n');
  fs.writeFileSync('C:\\Drop\\names.txt', namesString);
}

This is new to me, so taking a bit of time to understand, my ultimate goal is to take every "name" (about 50 returned) and then run another request for each name with that name as part of the body of the next request. just trying to figure out the next step now, if you have any ideas where to start :-)

**Comment by rangav** [comment]
- Update Request Body - using Env Variable Value with the name you received
-  Create a for loop
- Run the request using `tc.runRequest` in the loop
- Set this script as post Request Script

 https://github.com/rangav/thunder-client-support/blob/56769e17fe8905c3f138a94582ac4a291073c0ed/docs/tc-types.d.ts#L73

**Comment by craftzneko** [comment]
Amazing, thanks @rangav will try now

**Comment by craftzneko** [comment]
@rangav sorry can you explain a bit more, is this what i do?

I have an api request called "get access layers" that returns 50 names. A post request script runs a for loop, it will set an env variable that sets the current name, then runs a second post request called "get rulebase" that uses that env variable.

**Comment by rangav** [comment]
From the collection json file 

<img width="547" alt="Screenshot 2023-09-04 at 11 40 01" src="https://github.com/rangav/thunder-client-support/assets/8637550/2a498643-e129-4313-93cf-7c1b06e5f306">

**Comment by rangav** [comment]
Are you a paid version or using free version?

**Comment by craftzneko** [comment]
@rangav we are free although we previously used postman and since their move to cloud only we have been looking for a way to use collections locally as we are obliged to keep data local and this project is more of a test to see if we can achieve all we used to in postman. We would be happy to purchase a team license if thunderclient can achieve what we need, so far it seems like it could work for us :-)

**Comment by rangav** [comment]
Hi @craftzneko We can provide a free trial that provides team features and CLI. Let me know if you are interested in using the free trial.

**Comment by craftzneko** [comment]
@rangav Hi i am still really unsure of how to this should be accomplished. If you need to rurun a request multiple times using elements from a prior request and then build up a response. Ideally when someone opens the collection and clicks send for that request it should then do the work and return the collected results, but not really sure this can be acomplished that way. I can see how i can script it and save the results elsewhere.

**Comment by rangav** [comment]
I think it tc.response be updated. Will verify and get back to you later

**Comment by craftzneko** [comment]
Any ideas @rangav when i have a post script set and that post script calls tc.runrequest, the tc.response is still the response from the first request not the second request.

**Comment by rangav** [comment]
I just now tested it. The `tc.response.json` is updated with `tc.runRequest` response.

**Comment by craftzneko** [comment]
It is probably me then missing something but this code

async function writeNameToFile2() {
    const responseJson = tc.response.json;
    const names = responseJson['access-layers'].map(layer => layer.name);
    const fs = require('fs');
    const responseJsonRerun = [];

    for (let i = 0; i < names.length; i++) {
        const name = names[i];
        console.log(name);
        tc.setVar('name', name);
        tc.runRequest('5b955812-4928-4256-a90d-f88308adab00');
        responseJsonRerun.push(tc.response);
    }

    const responseString = JSON.stringify(responseJsonRerun);
    fs.writeFileSync('C:\\Drop\\Responses.txt', responseString);
}

Creates a file that just writes the response from the actual Post request that calls this as a post request script x number of times (45 as there are 45 names in the first request), so the tc.request that gets set doesnt seem to update here

**Comment by rangav** [comment]
you can also use the **response** returned from `tc.runRequest`,  Please try the below code.

```js
let response = tc.runRequest('5b955812-4928-4256-a90d-f88308adab00');
console.log(response.json);
responseJsonRerun.push(response);
```

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
