### ISSUE TITLE
Improve Save to Collection feature workflow

### ISSUE THREAD

**Issue by srisrinu1** [rangav/thunder-client-support#1317]
**Please describe feature/problem details and solution you'd like.**

I hope Thunder Client will consider implementing an alternative to the current behavior of the Collections tab. Either the form tab could close automatically after the collection is saved, or it could redirect to the route that was created. Currently, the creation form stays open after the collection is saved, which can be confusing and make it seem like the collection has not been created.

**Your Team Size Using TC:**

I'm an individual user.I use it for my Personal projects.

**Comment by rangav** [comment]
Hi @srisrinu1 

I did not understand which collection tab you are referring to?

can you please share screenshot

**Comment by srisrinu1** [comment]
I refer to this.

**Comment by rangav** [comment]
There is message displayed at the bottom that successfully added to collection right?

**Comment by srisrinu1** [comment]
Yeah

**Comment by rangav** [comment]
That message is clear right, saved successfully and close.

what change you want?

**Comment by srisrinu1** [comment]
Sometimes I have confusion.Unless i scroll down after saving of collection.I don't understand whether it was saved.I hope you can consider something for this.

**Comment by rangav** [comment]
Ok got it. Thanks for the feedback.

Will review it.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.13.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.
