### ISSUE TITLE
Is it possible to alter data set in the environment variable ? 

### ISSUE THREAD

**Issue by samir-ware** [rangav/thunder-client-support#1319]
**Question:**
Is it possible to alter data stored in environment variable. 
For e.g. If I store response in an environment variable named **foo** as below 
`
   {{ foo }} = { "key-1" : "value-1" , "key-2" : "value-2" } 
`

Is there a possibility that I can change 

`
 {{ foo }}.key-2 = "value-3" 
`

**Comment by rangav** [comment]
Hi @samir-ware 

you need to update will the full value gain - `{{ foo }} = { "key-1" : "value-1" , "key-2" : "value-3" } `

**Comment by samir-ware** [comment]
Thanks @rangav 
I am still little unclear where and how can I set value to an environment variable ? Is it in the"Tests" tab ? Or somewhere else ?

**Comment by samir-ware** [comment]
I believe in test tab we can assign values to environment variables and not other way round . Is that correct ?

**Comment by rangav** [comment]
You can use Tests tab or using scripting 

- Tests tab - select `Set Env Variable`
- Scripting - `tc.setVar` function

**Comment by samir-ware** [comment]
- Tests tab - select Set Env Variable
This will set the value **TO** environment variable . I am looking for a way to update the value already set in environment variable .

**Comment by rangav** [comment]
`Set env variable` will replace existing value also.

or you can use scripting
