### ISSUE TITLE
add copy request

### ISSUE THREAD

**Issue by Ali7med** [rangav/thunder-client-support#132]
**request for add new feature .**

**Comment by Ali7med** [comment]
thanks for replay .
when i set setting to request (birrior token , etc ..) , the easier way to create another request have the same setting is copy it and rename it and change the path URL , not re config it again .
then second i see the way of create request so long , it can simplify by click on collection and create request .

**Comment by rangav** [comment]
Hi @Ali7med we have duplicate request option on the collection tab, click option icon on **any request**, you will duplicate option in the dropdown.

**Comment by Ali7med** [comment]
thanks for fast replay
