### ISSUE TITLE
Importing collection returns Failed to Import

### ISSUE THREAD

**Issue by daunce** [rangav/thunder-client-support#1320]
**Describe the bug**
Using VS Code 1.81.1 & Thunder Client v2.11.4, attempting to add a collection either by file import, or URL, it attempts to process the file, but soon after returns "Failed to import"

**To Reproduce**
Within Thunder Client / Collections, choose "Import from URL", paste URL, ie: https://vdc-download.vmware.com/vmwb-repository/dcr-public/2449c89d-a83b-4a99-83ec-e08d7819309b/2bc06b4b-96f3-451d-9a46-9b2711afa870/nsx_policy_api.json, hit enter.

It shows "Processing, please wait", but then shows "Failed to import"

For more OpenAPI Spec JSON/XML see main download page: https://developer.vmware.com/apis/1248/#doc

**Expected behavior**
Collection to be added successfully.

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.81.1
 - extension version: v2.11.4

**Your Team Size Using TC:**
Just me, but potentially any VMware NSX user.

**Comment by rangav** [comment]
Hi @daunce is it working in previous version of the extension?

**Comment by daunce** [comment]
> Hi @daunce is it working in previous version of the extension?

I feel bad to say this is the first time I’ve used Thunder Client, even though it’s been on my todo list for ages.

**Comment by rangav** [comment]
Ok no problem Will verify and get back to you later

**Comment by rangav** [comment]
FYI - upcoming free version limits and terms 
https://www.thunderclient.com/pricing

**Comment by rangav** [comment]
Just verified - This open API spec version is 2.0 which is not supported.

You need to convert to Open API 3.0 and Try import again.

Import docs
https://github.com/rangav/thunder-client-support#import

Convert to Open API 3.0
https://stackoverflow.com/a/59749691/4035948

**Comment by daunce** [comment]
ahh.. Thanks @rangav. Yes confirmed converting it with the link in the stackoverflow post (https://converter.swagger.io/api/convert?url=OAS2_YAML_OR_JSON_URL) works. 

Thanks for looking into it. Jumped on a plan to show support. I'm glad I finally got onto Thunder Client!

Closing issue.

**Comment by rangav** [comment]
Thanks @daunce  for confirmation. Thanks for your support.

I appreciate it if you could write a review 
https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client
