### ISSUE TITLE
Test for text responseData

### ISSUE THREAD

**Issue by KaczorowskiLukasz** [rangav/thunder-client-support#1322]
Is it possible to writing tests for ResponseBody in text format? 

I can parse it with js custom function but functions does not work for ResponseBody field in tests.

**Comment by rangav** [comment]
Hi @KaczorowskiLukasz  can you please answer below questions 

Are you using the free version/paid version/evaluating:

Your Team Size Using TC:

**Comment by KaczorowskiLukasz** [comment]
I use paid version. A count number: KY4872047117

**Comment by rangav** [comment]
Thanks for sharing info. Will get back to you on your question.

**Comment by rangav** [comment]
Looks like a bug, will fix it later today.

**Comment by rangav** [comment]
I have fixed this issue, Can you please install the VSIX extension file and let me know your feedback?

- I will publish it to `marketplace` on Monday.

[vscode-thunder-client-2.11.5.vsix.zip](https://github.com/rangav/thunder-client-support/files/12562200/vscode-thunder-client-2.11.5.vsix.zip)

**Comment by KaczorowskiLukasz** [comment]
It works great:
![image](https://github.com/rangav/thunder-client-support/assets/121296565/c6eb7351-8c98-4b63-ae3f-0af3af2b2cee)

TYVM

**Comment by rangav** [comment]
Thanks @KaczorowskiLukasz for confirmation.

I appreciate it if you could write a review, if you like our support.
https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

**Comment by rangav** [comment]
I published it to the marketplace with version - `v2.12.0`.
