### ISSUE TITLE
Free and term limits

### ISSUE THREAD

**Issue by m-maq2** [rangav/thunder-client-support#1325]
**Question:**

**Are you using the free version/paid version/evaluating:**
I am using free version download via vscode marketplace.

**Your Team Size Using TC:**

n/a

Question: I am looking at https://www.thunderclient.com/pricing#compare.  Just checking to make sure, that if I use the extension from the marketplace I am going to run into the 15 request limit per collection.  Is this the case?

Thanks

**Comment by rangav** [comment]
Hi @m-maq2 yes for the free version

**Comment by volcanie** [comment]
It's disappointing to see this service abandon its open-source roots to become paid, especially considering the community's many contributions. This feels unfair to those who supported its free-use ideology.

I suggest checking out Postman as an alternative, it has a VSCode extension. It might take around 30 minutes to switch (use the 'Convert to Postman' function), but it ensures freedom from this service's new paid structure.

**Comment by rangav** [comment]
Hi @volcanie 

our code is never open source and its a commercial software license from day one.
