### ISSUE TITLE
Cursor issues when typing

### ISSUE THREAD

**Issue by hellomengxing** [rangav/thunder-client-support#1326]
Hello, the cursor is misaligned when typing JSON. This leads to the illusion of mistyping every time you enter.

version: v2.12.0
![demo](https://github.com/rangav/thunder-client-support/assets/101499070/df19230e-71d8-420e-ae68-0ab4288fdcc6)

**Comment by hellomengxing** [comment]
Oh, thank you, it's for that. Because I installed other fonts on another computer and none on this computer. Sorry for the duplicate question.

**Comment by Charles4500** [comment]
I had the same issue. Now it is resolved,thank you
