### ISSUE TITLE
Problem with Response from GET-Request on Localstack/S3

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1327]
**Describe the bug**
Hi @rangav, 

i have a problem to get a response, when i send a GET Request to a Localstack/S3-Bucket.

![image](https://github.com/rangav/thunder-client-support/assets/112586589/8472f089-a2cf-414d-bdd8-52369bdb6e07)

our request url looks like: http://[myhost]-local.s3.localhost:[port]/[object]
-> Response looks like my screenshot

we have also tried a url like this: http://[myhost]-local.s3.localhost.com
-> No Result like the above (couldnt resolve hostname)
->Response Screenshot:
![image](https://github.com/rangav/thunder-client-support/assets/112586589/cebfbec3-80f2-46bd-89c8-4c810108a50e)

We suppose that Problem is on parsing, because of missing domain-name for example ".com"

Your suggestion from [https://github.com/rangav/thunder-client-support/issues/1086#issuecomment-1664276140](url)

I tried all three solutions [127.0.0.1 | ::1 | 0.0.0.0]. They dont work for me :/

I used them instead of my localhost.

http://[myhost]-local.s3.localhost:[port]/[object]

We use this solution for mocking it. 
https://docs.localstack.cloud/user-guide/aws/s3/

**To Reproduce**

**Expected behavior**
Get a valid response

**Platform:** 
 - OS: Windows
 - vscode version: 1.82.0
 - extension version: 2.12.0

**Are you using the free version/paid version/evaluating:**
paid version

**Your Team Size Using TC:**
10-15

**Comment by rangav** [comment]
also please try using `axios` http library setting

<img width="605" alt="Screenshot 2023-09-12 at 11 17 02" src="https://github.com/rangav/thunder-client-support/assets/8637550/055e9f4a-686d-4a26-b068-b0fb4f031a4d">

**Comment by rangav** [comment]
From the screenshot, I think the API key is missing.

![image](https://github.com/rangav/thunder-client-support/assets/8637550/a46c4003-d754-49a6-80cd-5e1171e7d07f)

**Comment by rangav** [comment]
another option is to open in browser and see what `local IP` is used in the network tab

![image](https://github.com/rangav/thunder-client-support/assets/8637550/f13c9180-f24f-4812-b051-59ef61d730f5)

**Comment by erwinmoretz** [comment]
> also please try using `axios` http library setting
> 
> <img alt="Screenshot 2023-09-12 at 11 17 02" width="605" src="https://user-images.githubusercontent.com/8637550/267296441-055e9f4a-686d-4a26-b068-b0fb4f031a4d.png">

Hi @rangav, 

this solution helped for local test. Thank you!

**Comment by erwinmoretz** [comment]
> another option is to open URL in the browser and see what `local IP` is used in the network tab
> 
> ![image](https://user-images.githubusercontent.com/8637550/267989151-f13c9180-f24f-4812-b051-59ef61d730f5.png)

i tried this solution without the axios and it didnt work. Just for the protocol.
