### ISSUE TITLE
Set a global variable programmatically

### ISSUE THREAD

**Issue by Artem0ne** [rangav/thunder-client-support#1328]
**Question:**
Is there any way to set global variable programmatically ?

We use via Thunder Client:
![image](https://github.com/rangav/thunder-client-support/assets/59470703/fcac4c15-ff60-4258-ad5e-92bf61e036ba)
However, it does not work in CI/CD Pipeline (The variable accessToken is not being changed in global environment)

**Is it possible to extract the variable and set it in Pre Request Script in global variable?**
Somehow like: 
tc.setVariableInGlobalEnvironment(var, "var");

![image](https://github.com/rangav/thunder-client-support/assets/59470703/e9d57794-93d0-4957-933b-beef0405a471)

**Are you using the free version/paid version/evaluating:**
paid version
**Your Team Size Using TC:**
12

**Comment by rangav** [comment]
Thanks for the confirmation.
