### ISSUE TITLE
Redirects for a response cause the same request to be made 2 times in a loop. However, Postman works correct

### ISSUE THREAD

**Issue by turturmurmur** [rangav/thunder-client-support#1329]
**Describe the bug**

Redirects for a response cause the same request to be made 2 times in a loop, first one writes second one gives the error as there's a duplicate. However, Postman works correct without duplicating.

**To Reproduce**

Create a database table write to it  and do a res.redirect('/') to get the all items 

**Expected behavior**

Added item and all others return

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.82.0
 - extension version: v2.12.0

Code snips:
Code implementation:
route for monsters doing a post to / inside monsters route
![image](https://github.com/rangav/thunder-client-support/assets/89113207/284a5b52-2c43-4181-ab53-b35ddaffc36b)
TC does not work:
![image](https://github.com/rangav/thunder-client-support/assets/89113207/f321afe5-7adc-461f-95e9-343fed0c42b4)
Postman works:
![image](https://github.com/rangav/thunder-client-support/assets/89113207/a4b0f8af-7cd2-4e06-aced-d1081ecc4985)

**Comment by rangav** [comment]
Hi @turturmurmur 

can you please confirm below

Are you using free version or paid version?
Team size?
Did you read free version terms: https://www.thunderclient.com/terms#free-plan

**Comment by turturmurmur** [comment]
Hi, 
Free version,
No team this is for my personal use,
Read it after you posted

**Comment by rangav** [comment]
Thanks for sharing 

there is setting `follow redirects`, try disabling it

**Comment by turturmurmur** [comment]
Follow redirects did not work, it was returning found. redirecting to /monster path 
So, I suspected the library TC makes a request with and changed got to axios
That fixed it:
![image](https://github.com/rangav/thunder-client-support/assets/89113207/2ae1675c-856a-4337-b55b-75420ca35843)
![image](https://github.com/rangav/thunder-client-support/assets/89113207/55416e1b-c07c-4f87-aae5-664cdff285a7)
Should default be axios?

**Comment by rangav** [comment]
Thanks for confirmation

If we change to axios as default, it might break functionality for some users.

so we let users choose the library that works for them.
