### ISSUE TITLE
Variable expansion in Environment Variables expands only one level deep.

### ISSUE THREAD

**Issue by djdole** [rangav/thunder-client-support#133]
If a user creates a series of Environment Variables, each depending on the previous,
the final expansion of the values stops at the first replacement.

Steps to reproduce:
1. In Thunder Client, Create variable VAR1 = A
2. In Thunder Client, Create variable VAR2 = {{VAR1}}B
3. In Thunder Client, Create variable VAR3 = {{VAR2}}C
4. In Thunder Client, Create variable VAR4 = {{VAR3}}D
5. Visit https://webhook.site/ and copy unique URL.
6. In Thunder Client, Create new request, and paste copied URL as the request URL
7. In Thunder Client, Add a query parameter: var1 = {{VAR1}}
8. In Thunder Client, Add a query parameter: var2 = {{VAR2}}
9. In Thunder Client, Add a query parameter: var3 = {{VAR3}}
10. In Thunder Client, Add a query parameter: var4 = {{VAR4}}
11. In Thunder Client, Send request
12. Visit copied URL, and check request received by webhook.site

Expected "Query strings" values:
- var1 = A
- var2 = AB
- var3 = ABC
- var4 = ABCD

Actual "Query strings" values:
- var1 = A
- var2 = AB
- var3 = {{VAR1}}BC
- var4 = {{VAR2}}CD

**Comment by rangav** [comment]
This is implemented now in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
