### ISSUE TITLE
Thunder Client Loads 40% of the Time

### ISSUE THREAD

**Issue by mwainwri** [rangav/thunder-client-support#1331]
**Describe the bug**

Thunder Client loads when I start vscode about %40 percent of the time.  When it does load at times I cannot create a folder or a new request.

This error message appears in vscode when it does load which may or may not be related:

"Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.. "

![image](https://github.com/rangav/thunder-client-support/assets/23614312/30315894-b57c-4297-a3b3-68a8a15a8892)

**To Reproduce**
It happens when I start the plugin.

**Expected behavior**

The plugin should load each time I run it, new folders and new requests should not halt and the new request form should open every time.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.82.2
 - extension version: 2.12.0

**Are you using the free version/paid version/evaluating:**
I am using the paid version'

**Your Team Size Using TC:**
N/A

**Comment by rangav** [comment]
Thanks @mwainwri for reporting 

Please try below solutions 

- Uninstall and reinstall extension 
- Install previous version 2.11.4

let me know if above solutions work?

**Comment by mwainwri** [comment]
Hello @rangav, I went back to version 2.11.4 and it still seems to be more or less hit-and-miss.  Perhaps it's a conflict with another plugin I have installed, not sure.  I do still however get this error message each time it doesn't load, again may just be a coincidence.

![image](https://github.com/rangav/thunder-client-support/assets/23614312/1e167c10-d7d9-47cd-bf46-ea0ca555d5d8)

**Comment by rangav** [comment]
Did it work properly before and did you install any other extensions recently

**Comment by rangav** [comment]
Or downgrade vscode to 1.81 and test it

**Comment by mwainwri** [comment]
Thunder Client worked well previously, I haven't coded any new API routes lately so I can't be sure when this started.  I recently downgraded Windows from Windows 11 to Windows 10 because of a conflict with some other software I use, as a result, I had to re-install vscode and it synced my plugins.

I will try downgrading vscode to 1.81.

**Comment by bendera** [comment]
Hi,

I have the same issue with my extension. There is an open issue about this in the VSCode repo:
https://github.com/microsoft/vscode/issues/192965

**Comment by Guo-Chenxu** [comment]
> Thunder Client worked well previously, I haven't coded any new API routes lately so I can't be sure when this started. I recently downgraded Windows from Windows 11 to Windows 10 because of a conflict with some other software I use, as a result, I had to re-install vscode and it synced my plugins.Thunder Client 以前工作得很好，我最近没有编写任何新的 API 路由，所以我不能确定这是什么时候开始的。我最近将 Windows 从 Windows 11 降级到 Windows 10，因为与我使用的其他一些软件发生冲突，因此我不得不重新安装 vscode 并且它同步了我的插件。
> 
> I will try downgrading vscode to 1.81.我会尝试将 vscode 降级到 1.81。

Hello, do you solve the problem after downgrading to 1.81?

**Comment by rangav** [comment]
Hi @mwainwri is the problem solved?

**Comment by rangav** [comment]
Closing this issue feel free to reopen it if needed
