### ISSUE TITLE
Using the Convert to Json on xml in custom filter

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1332]
**Question:**
Hi @rangav,

i haven't figured out how to use your convert to json (xml or html response Body) in custom filter. 

In the extension i know i can use this and then a json query: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/febaad2d-4707-4ba0-8883-c557469d5a34)
But in this case, i need to use the custom filter. 

in our ci/cd i cant used my earlier solution with loading the xml2json module, to navigate to an attribute for tests

Could you explain how to use your convert to json feature/module?? 

**Are you using the free version/paid version/evaluating:**

paid

**Your Team Size Using TC:**
10-15

**Comment by rangav** [comment]
@erwinmoretz 

docs below for xml testing 
- https://github.com/rangav/thunder-client-support/blob/master/docs/xml-testing.md

**Comment by erwinmoretz** [comment]
@rangav 

i don't need the Solution for the Testing Tab in Thunder Client. I need the convert 2 json in my Script.

if i want to see whats in the tc.request.body i get this: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/4f68a868-189c-48c6-855b-cd93c511f528)

with tc.response.text ill get the Response in txt format. But i cant parse it, because it has xml structure. 

Could you please explain how to use ur module in custom filter scripting? 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/b0e708ab-a916-4291-a5fa-cc570f1c2ac2)

**Comment by rangav** [comment]
We use the internal xml to json library `fast-xml-parser`, if you like you can use it.

All internal modules
https://github.com/rangav/thunder-client-support/blob/b50003f0225faa100b4275bb4115610e73c5cc7f/docs/custom-filters.js#L10

You can load any Node module
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#import-node-module

**Comment by erwinmoretz** [comment]
thank you for your support. the fast-xml-parser works for me!
