### ISSUE TITLE
fix nerd fonts usage

### ISSUE THREAD

**Issue by gabrielSantos1101** [rangav/thunder-client-support#1337]
**Describe the bug**
how I use nerd fonts everything gets really weird when I start typing [Demonstration](https://youtu.be/ytHv_n601i0)

**To Reproduce**

**Expected behavior**
The type cursor should be exactly where I'm typing

**Platform:** 
 - OS: win 11
 - vscode version: 1.82
 - extension version: v2.12.0

**Comment by rangav** [comment]
See existing issue - https://github.com/rangav/thunder-client-support/issues/1326#issuecomment-1714123998
