### ISSUE TITLE
Put Method Update Happens But Returns HTTP 404 Response

### ISSUE THREAD

**Issue by turturmurmur** [rangav/thunder-client-support#1338]
**Describe the bug**

When I update an object, the update happens, however I get the error http 404. I tried the same with postman and it works as it should.

**To Reproduce**

![image](https://github.com/rangav/thunder-client-support/assets/89113207/58ca2b1f-f0b9-47d2-9bd3-82a7f07d2eee)
![image](https://github.com/rangav/thunder-client-support/assets/89113207/0767b925-deca-4990-986a-f8b86886ad52)

**Expected behavior**

Get HTTP 200 with the redirect response from the get call internally.

Note: both http client libraries got and axios have the same issue

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.82.2
 - extension version: v2.12.0

**Comment by rangav** [comment]
Hi @turturmurmur 

Can you share any sample collection and env that can reproduce the error

**Comment by turturmurmur** [comment]
If you want I can add you to the repo and you can spin it up in your local, I have not deployed this to anywhere. Instead of a collection the call I have shared has the problem.

**Comment by rangav** [comment]
You can see request headers in postman and thunder client and whats the difference.

**Comment by rangav** [comment]
I am closing the issue, feel free to reopen if needed
