### ISSUE TITLE
Testing Schema: Value Message to big to display

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1339]
**Question:**

Hi @rangav, 

im testing a response with the extension and ci. Both gave me the error-message "Response Body schema is valid => Actual value is too big to display". How can i see the "value" which is to big? 

Testing with Schema in value: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/3e501648-508f-405d-98fd-cfbdae6d45b5)

testing with Schema as readFile: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/4c0cf4b3-038b-4851-b9ce-10d97149d409)

testing in ci with readFile: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/77ce4ab4-0546-47d4-8109-a55165f492f7)
![image](https://github.com/rangav/thunder-client-support/assets/112586589/88e31546-b8e5-4548-80fa-0a0c1b89503d)

The Response Size is 6.37kb. 

**Are you using the free version/paid version/evaluating:**
paid

**Your Team Size Using TC:**
10 - 15

**Comment by rangav** [comment]
Ok will verify and get back to you asap.

**Comment by rangav** [comment]
I unable to find the issue, its working for me here.

Can you try to reproduce the error using the test URL and some Test data

https://www.thunderclient.com/t/echo

sample body
```js
{
  "data": {
    "fraction": "0.0",
    "balance": 56.684848939345678,
    "bignumber": 6395775853609427517,
    "isNumber": null
  }
}
```

<img width="1557" alt="Screenshot 2023-09-20 at 10 53 33" src="https://github.com/rangav/thunder-client-support/assets/8637550/ae02ce55-8d34-4079-9a38-c60f8a436c3a">

**Comment by erwinmoretz** [comment]
Could you show me your test schema value? 

addtional to my case: 
In all other tests i can use the schema validation fine, but in this case it wont give me the error message. 
First i had some strict errors, which i corrected in the schema.json. After that it gave me the message: Response Body schema is valid => Actual value is too big to display. 


if you have time tomorrow, i can show my problem via teams call.

**Comment by rangav** [comment]
schema
```js
{
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "fraction": {
            "type": "number"
        },
        "balance": {
            "type": "number"
        },
        "bignumber": {
            "type": "integer"
        },
        "isNumber": {
            "type": "null"
        }
    },
    "required": [
        "balance",
        "bignumber",
        "fraction",
        "isNumber"
    ],
    "title": "Welcome4"
}
```

Can you clear the Logs in Output window and run the request again

**Comment by erwinmoretz** [comment]
Your Example Works.

**Comment by erwinmoretz** [comment]
in this case its another error message then mine.

**Comment by rangav** [comment]
Can you `clear the Logs in Output window` and run your request again

**Comment by erwinmoretz** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/112586589/6a527d1d-abc5-4be6-bf69-54dea2fdb4ac)

**Comment by rangav** [comment]
thanks for sharing

**Comment by rangav** [comment]
I have made few changes to logs in schema, Can you install the extension manually and test it

[vscode-thunder-client-2.12.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/12672191/vscode-thunder-client-2.12.1.vsix.zip)

**Comment by erwinmoretz** [comment]
thanks for the update. This gave me more information: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/04120d9f-4e29-4ba5-b0b2-0b1dbc9ee46a)

**Comment by rangav** [comment]
Thats good, Is the error info useful to resolve your test case?

**Comment by erwinmoretz** [comment]
Yes its useful. After deleting the "additional items", i got more information about the schema errors in my response. Thanks! 

ill check the rest and will give you feedback. If there are no problems, ill close this issue!
