### ISSUE TITLE
Connection was forcibly closed by a peer. 

### ISSUE THREAD

**Issue by digi1010** [rangav/thunder-client-support#1341]
**Describe the bug**
I see Connection was forcibly closed by a peer. Endpoint works with certificates, I placed expected certificates in extension settings but still I see this issue. 

**To Reproduce**
i've installed, imperted collection from postman and use

**Expected behavior**

**Platform:** 
 - OS: Windows
 - vscode version: 1.80.1
 - extension version:2.10.5

**Are you using the free version/paid version/trial:** free version

**Comment by rangav** [comment]
Please search existing issues

**Comment by digi1010** [comment]
Hi Rangav,

I've reviewed the existing issues related to this problem, but it appears that most of them reference 'localhost' URLs. My issue, however, involves non-localhost URLs. Could you please provide guidance or assistance specific to this scenario?

**Comment by rangav** [comment]
Try the solution here
https://github.com/rangav/thunder-client-support/blob/master/docs/common-issues.md

**Comment by okbutsowhat** [comment]
> Try the solution here https://github.com/rangav/thunder-client-support/blob/master/docs/common-issues.md

Absolutely working
