### ISSUE TITLE
New Request is not working at all

### ISSUE THREAD

**Issue by istarkov** [rangav/thunder-client-support#1342]
**Describe the bug**
Every time I click on New Request nothing happened, in output I see "please login"

<img width="673" alt="image" src="https://github.com/rangav/thunder-client-support/assets/5077042/0f076733-51cc-4716-91b0-0552f1b9525d">

Every time Im trying to login I see 

<img width="804" alt="image" src="https://github.com/rangav/thunder-client-support/assets/5077042/94865faa-216b-44ac-a21d-276fc41c1984">

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Hi @istarkov 

You need buy subscription to use git sync and other features 

You can migrate to free version to access your collections
https://github.com/rangav/thunder-client-support/blob/master/docs/free-version.md

**Comment by istarkov** [comment]
I don't even know what is git sync is, and why newly installed extension is not working

**Comment by rangav** [comment]
Can you share screenshot of logs
https://github.com/rangav/thunder-client-support#logs

**Comment by rangav** [comment]
You might have enabled these settings 
https://github.com/rangav/thunder-client-support#git-sync

**Comment by istarkov** [comment]
Yep, found that it was enabled seems like few years ago, thank you! Probably should me more descriptive message as non working button looks like a bug.

**Comment by rangav** [comment]
Thanks for confirmation
