### ISSUE TITLE
ENOENT no such file or directory

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#1343]
**Describe the bug**
I often install thunder client to developers I support and run into issue when I use it (without restarting vscode)

I now installed it on a windows server 2016, imported CURL and got the following error:
![image](https://github.com/rangav/thunder-client-support/assets/16635859/e78e208a-acb1-421c-98f7-30f372c403e1)

the `.th-client` is missing

Fun part - if i try to create the folder from windows explorer - it screams that I need to set the file name - I created it eventually through cmd

Of course, I'll create the folder - but I  prefer not to need to do that myself :)

After that I often get the following error:
Connection was refused by the server.
![image](https://github.com/rangav/thunder-client-support/assets/16635859/4005070e-3459-4983-a8a7-aa3e5c3203fa)

For a server that works (since I can call it with postman)

Plesase help

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: Windows server 2016
 - vscode version: 1.76.2
 - extension version:2.10.0

**Are you using the free version/paid version/trial:**
free

**Comment by rangav** [comment]
Thanks @noam-honig reporting the bug, will look into it.

**Comment by rangav** [comment]
Are you using localhost url?

**Comment by rangav** [comment]
Try this solution for localhost
https://github.com/rangav/thunder-client-support/blob/master/docs/common-issues.md

**Comment by noam-honig** [comment]
I will next time - thanks for that.

Can you look into the issue I had with the  `.th-client`  folder not
being created, I had it in two separate cases?

**Comment by rangav** [comment]
Sure will verify and get back to you

**Comment by rangav** [comment]
@noam-honig I have fixed the issue with `.th-client` folder is missing in `v2.12.3`.

Can you please delete the folder `.th-client` and try again. The extension should create the folder automatically.
