### ISSUE TITLE
The json response containing the xml with \" in place of " (double quotes) are not set correctly in env variables

### ISSUE THREAD

**Issue by DeltaUser121** [rangav/thunder-client-support#1344]
**Question:**

**Are you using the free version/paid version/trial:**
Paid version
Sample response obtained below:

```json
{
  "transactionCount": 1,
  "transactions": [
    {
           "message": "<?xml version=\"1.0\" encoding=\"us-ascii\"?><Message xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns=\"urn:ipcloud\"><AppHdr><CharSet xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\">utf-8</CharSet><Fr xmlns=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\"></Message>"
      "totalAmount": 2.0
    }
  ]
}
```
Above sample obtained in the json response

<img width="464" alt="image" src="https://github.com/rangav/thunder-client-support/assets/139353595/280f9f79-448c-4983-8921-58dd87195f74">

I am trying to set the json.transactions[0].message to a variable eg XMLMessageBody but the variable content when viewed ignores the \" and is set to something as below replacing \" with " only

<?xml version="1.0" encoding="us-ascii"?><Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:ipcloud"><AppHdr><CharSet xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01">utf-8</CharSet><Fr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01"></Message>

<img width="537" alt="image" src="https://github.com/rangav/thunder-client-support/assets/139353595/e8ec77ae-0359-4c70-ada1-c39fa1f34ce0">

We need to reuse the exact same property ( as obtained in the json message) in the next steps but the tests are failing due to the formats being incorrect and replaced.

**Comment by rangav** [comment]
Hi @DeltaUser121 we need to verify subscription for support priority 

Can you confirm your name and email using below form
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
Thanks for confirmation, Will verify and get back to you

**Comment by rangav** [comment]
I tested it, the following data is saved to `XMLMessageBody`.  Is it not the expected value?

```xml
<?xml version="1.0" encoding="us-ascii"?><Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:ipcloud"><AppHdr><CharSet xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01">utf-8</CharSet><Fr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01"></Message>
```

**Comment by DeltaUser121** [comment]
The expected is backslash then quotes \" wherever we see a double quote " as the same is obtained in the response from the api which is the   acceptable formats of the xml when used in the jsons here.
Kindly review

**Comment by DeltaUser121** [comment]
Expected is below : backslash and a double quote
xml version=\"1.0\"
Current behaviour : It is removing the backslash and having only double quote included 
xml version="1.0"

**Comment by rangav** [comment]
Ok got it. Where are you using this variable in the following request.

can you share a screenshot

**Comment by DeltaUser121** [comment]
<img width="446" alt="image" src="https://github.com/rangav/thunder-client-support/assets/139353595/439e51ca-6846-4f15-9f6c-db233f37be85">

It is used in the next request as placed above

When the above request is run using this variable, we get 500 server error as the xml format is not supported. Here is the snapshot from the o/p console for the request that is being sent out
<img width="526" alt="image" src="https://github.com/rangav/thunder-client-support/assets/139353595/773b7a70-cb60-469e-947d-d12585fd16e1">



Expected Request snapshot that must be sent out is below ( as should get saved in the env variable including the backslash and then quotes)

<img width="528" alt="image" src="https://github.com/rangav/thunder-client-support/assets/139353595/2751512e-bf03-48d4-a9f5-a396dbf878d1">

Please let me know for any additional details

**Comment by rangav** [comment]
thanks for sharing, will verify and get back to you

**Comment by rangav** [comment]
You can use custom scripting to escape XML when saving to variable

```js
function escapeXml(input) {
    // regex escape double quote
    input = input.replace(/"/g, "\\\"");
    console.log(input);
    return input;
}

module.exports = [escapeXml];
```

<img width="759" alt="Screenshot 2023-09-22 at 06 11 37" src="https://github.com/rangav/thunder-client-support/assets/8637550/2ff5ce04-6a1f-4dfd-bd71-4dfa4f9373b0">

Custom filters docs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by DeltaUser121** [comment]
That works, thanks for looking into the issue.

**Comment by DeltaUser121** [comment]
Marking as close

**Comment by rangav** [comment]
Thanks for confirmation
