### ISSUE TITLE
ThunderClient performance issue.

### ISSUE THREAD

**Issue by mubeentajss** [rangav/thunder-client-support#1346]
### Discussed in https://github.com/rangav/thunder-client-support/discussions/1345

<div type='discussions-op-text'>

<sup>Originally posted by **mubeentajss** September 21, 2023</sup>
Hello All,

I installed thunder client extension to Vscode, but I encounter performance issue it takes few seconds to click on each tab for every API request field and its not loading the payload data in few seconds, it takes time to see the output response as well, kindly help on this issue i tried to re-install thunder client to new version, I disabled all the extension from Vscode, I checked the memory usage as well it all seems to be normal but I still face this issue when I click on each tab of header ,auth, body from thunderClient it takes few seconds to load and respond this makes my work delayed, Please suggest on this & thanks in advance.</div>

**Comment by rangav** [comment]
Please answer all the questions in template
