### ISSUE TITLE
Set-Cookie is not working

### ISSUE THREAD

**Issue by Hero-codes** [rangav/thunder-client-support#1349]
**Describe the bug**
It randomly sets the cookie.
Whenever I try to set a custom cookie using set-cookie, it does not accept that cookie.

**To Reproduce**
Create a middleware using JWT and make a protected route
Try to CREATE something in which the user should be authenticated, means the route should be protected route.
Applies to GET routes too.

**Expected behavior**
It should have used the cookie that I had set manually.

**Platform:** 
 - OS: Windows
 - vscode version: 1.82.2
 - extension version: v2.12.0 - (2023-09-11)

**Are you using the free version/paid version/trial:**
Free Version

**Comment by rangav** [comment]
Hi @Hero-codes Can you share screenshots will verify it

**Comment by Hero-codes** [comment]
**First Case:**
![image](https://github.com/rangav/thunder-client-support/assets/98174971/9a80b7fa-4122-4767-878b-9b34b61c104c)
It is a protected route, I have not set any cookies but then also it is assuming a random user

**Second Case:**
![image](https://github.com/rangav/thunder-client-support/assets/98174971/88dc9e54-ce41-4e21-9e57-7cd3dbdbce4e)
No cookies are set, so the error is natural
But when I set the cookies manually, the same error comes again.

![image](https://github.com/rangav/thunder-client-support/assets/98174971/00b9b234-f2db-436a-9416-39c3b0bb9b49)
![image](https://github.com/rangav/thunder-client-support/assets/98174971/5ab6a04b-9af4-47d7-9c22-c321b82556d9)

**Third Case:**
![image](https://github.com/rangav/thunder-client-support/assets/98174971/01a1d156-1f07-437c-832b-63b5eb858574)
Here, as you can see, I need to first trigger the SignIn route, after which it automatically sets the cookie.
Now if I will set the cookie manually, it won't accept that patricular cookie.
@rangav

**Comment by rangav** [comment]
You are setting cookie wrongly 

follow this
https://github.com/rangav/thunder-client-support#cookies

**Comment by Hero-codes** [comment]
Ok, thank you for the help 😊
