### ISSUE TITLE
Support Variable Expansion in URL bar

### ISSUE THREAD

**Issue by harleybl** [rangav/thunder-client-support#135]
I'd like to be able to use a collection of requests in different environments where the API URL changes per environment.
For example, let's say that I have an API deployed to DEV, UAT, and PROD environments:
https://dev.my-api.com
https://uat.my-api.com
https://prod.my-api.com

Right now, I would need to define separate requests for each of them or have separate collections. 
If variable expansion were supported on the URL bar then I could just make a variable in Env called "EnvName" and set it to DEV, UAT, or PROD and set the URL for the request to:
https://{{envName}}.my-api.com use one request definition to submit to different environments.

**Comment by rangav** [comment]
Hi @harleybl we support variable expansion, it's already supported with env variables. Is it something different your requesting?

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.
