### ISSUE TITLE
request no longer recognizes any environment variables

### ISSUE THREAD

**Issue by acoxe** [rangav/thunder-client-support#1350]
**Describe the bug**
This feature worked great until after v2.12.3 was installed on my PC today. The request no longer recognizes any environment variables in the url or in the header. This is a show stopper. 

**To Reproduce**

1) define env variable called baseUrl
2) define env variable called accessToken
3) use baseUrl in url of request, for example: {{baseUrl}}/tenants
4) define header of request to add new item that passes in {{accessToken}}

**Expected behavior**
1) I expect the placeholder {{baseUrl}} to be replaced with the value of the env.baseUrl variable but I get this error response instead: 
"Couldn't resolve the hostname to an IP address, Verify Url: http://%7B%7BbaseUrl%7D%7D/tenants".
2) I expect the placeholder {{accessToken}} to be replaced with the value of env.accessToken, but the literal string `{{accessToken}}' is used instead.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.82.2
 - extension version: v2.12.3 

**Are you using the free version/paid version/trial:** free

**Comment by rangav** [comment]
Hi @acoxe 

The env variables are working for me, 
 
can you test with https://www.thunderclient.com/t/echo URL and share screenshots

<img width="1067" alt="Screenshot 2023-09-26 at 12 34 55" src="https://github.com/rangav/thunder-client-support/assets/8637550/db8e36e5-3e27-49ab-85f0-a599f3894371">

**Comment by acoxe** [comment]
This is not a bug.
Thank you for your quick feedback. Thank you for the way to test it. 
Sorry, it must be a user error on my end. I was reusing the same collection and variables and it suddenly stopped working, I am not sure what I did wrong, perhaps I accidentally changed the variable names. 
The important thing is there is no bug and I can continue.
![envirpnment](https://github.com/rangav/thunder-client-support/assets/9397346/594ef42b-ba4d-4c47-9600-8889d2a601d1)
![request](https://github.com/rangav/thunder-client-support/assets/9397346/425e75f2-7b93-4769-8d0c-40c708b9501a)

**Comment by rangav** [comment]
Thanks for confirmation,
Closing issue
