### ISSUE TITLE
Convert querystring format to form encoded

### ISSUE THREAD

**Issue by bombillazo** [rangav/thunder-client-support#1354]
**Please describe feature/problem details and the solution you'd like.**

We would like to be able to paste a querystring formatted string and for TC to automatically populate the data as a form-encode

![image](https://github.com/rangav/thunder-client-support/assets/44002321/d3896ef1-51cb-497a-9300-a97e705afdf3)

**Describe alternatives you've considered**

We currently have to manually set up each field , not fun.

![image](https://github.com/rangav/thunder-client-support/assets/44002321/a7f2ba40-78a3-47eb-9021-5bc544c4f104)

**Are you using the free version/paid version/trial:**

Paid subscription

**Comment by rangav** [comment]
Thanks @bombillazo for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.13.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.3

Please let me know your feedback.

**Comment by mfeke** [comment]
how can i upload file or image on thunder client and i'm using node.js

**Comment by rangav** [comment]
@mfeke you can use form tab or Binary tab depending upon your needs.
