### ISSUE TITLE
OAuth 2 error with PKCE and optional client_secret

### ISSUE THREAD

**Issue by maksd** [rangav/thunder-client-support#1357]
**Describe the bug**
When using oauth2 with `Authorization Code with PKCE` flow it still pass the client secret, and the token request call fail. 
According to PKCE protocol flow, it should use the code_verifier instead of client secret. https://tools.ietf.org/html/rfc7636

```
OAuth2 TokenUrl Request: https://<REDACTED>/oauth2/token
Request Method: POST
Request Headers:
{
  "Accept": "application/json",
  "Content-Type": "application/x-www-form-urlencoded"
}
Request Body:
grant_type=authorization_code&code=<REDACTED>&redirect_uri=http%3A%2F%2Flocalhost%3A6789%2Fcallback&client_id=<REDACTED>&code_verifier=<REDACTED>&client_secret=

OAuth Response:
{
  "error": "invalid_client",
  "error_description": "Client authentication failed"
}
```

**Expected behavior**
Do not pass `client_secret` in the request body if it is empty.

**Platform:** 
 - OS: Darwin Kernel Version 22.6.0 arm64
 - vscode version: 1.82.2
 - extension version: v2.12.4

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
This Bug is fixed now and published to the marketplace, please update to `v2.13.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.
