### ISSUE TITLE
Authentication details on Environment

### ISSUE THREAD

**Issue by bensonrlee** [rangav/thunder-client-support#1358]
**Please describe feature/problem details and the solution you'd like.**
Right now, authentication details (username and password, etc), can be linked at the collection level.  Is it possible to link authentication details based on the environment.

For example, I can have same API endpoints (except for base URL) on dev and prod, but the credentials in dev and prod would not be the same.

**Describe alternatives you've considered**
1. Update the authentication details depending on the environment being tested.
2. Duplicate the collection and link the second collection to the second environment.

**Comment by rangav** [comment]
Hi @bensonrlee 

You can use env variables in authentication fields, e.g {{username}} and {{password}}

and having different values in Staging, and production environments. When you change the active environment, it will change values accordingly.

**Comment by metamoof** [comment]
Hi
Is it possible to change from Basic to OAuth depending on the evironment?
