### ISSUE TITLE
Support for generating random strings and integers in request body

### ISSUE THREAD

**Issue by joekaiser** [rangav/thunder-client-support#136]
**Is your feature request related to a problem? Please describe.**
Assume testing the CRUD lifecycle of a rest API. You need to be able to create/update/fetch/delete an entity. It would be nice if Thunder Client could generate random strings and integers to use in the request body.

**Describe the solution you'd like**
Let's take the Create example. The request requires a `name:string` to be passed over. Perhaps you can do something similar to how environment variables are used. `{{__randstring}}`, maybe?

**Describe alternatives you've considered**
An Alternative could be having "setups" as part of the request. Similar to how Tests work you can manipulate environment variables, and set the value to something random there. This way you can just use the environment variable as normal, but the value would change with every request.

**Implementation:**

**Comment by rangav** [comment]
Hi @joekaiser will guid work for random string?

**Comment by joekaiser** [comment]
Absolutely

**Comment by rangav** [comment]
That’s Good, if possible I will include this for next update

**Comment by annymosse** [comment]
> Absolutely
> 
> I would imagine integers could even work. The need is for random data. At the end of the test the record is delete, so it doesn't matter what it is.

i think [Faker.js](https://github.com/marak/Faker.js/) or [Chancejs](https://github.com/chancejs/chancejs/) can help too much for this process .

**Comment by rangav** [comment]
I saw faker.js the size is around 6MB , which too big to use.  I will check the other one.

Any ultra lightweight library?

**Comment by annymosse** [comment]
@rangav actually `faker` is around [9.6MB PUBLISH SIZE & INSTALL SIZE](https://packagephobia.com/result?p=faker) however it's very huge because of the international data names (ar,fr,en,it,....) for `chancejs` [1.80MB PUBLISH SIZE & INSTALL SIZE](https://packagephobia.com/result?p=chance) with limited data and limited api compared to `chancejs`, you can remove the additional European the idea here is to keep only the main typography such as [en,it,es,...]=> latina and [ar,pr]=>ar and Chinese , only the main different characters.

**Comment by joekaiser** [comment]
I'm not suggesting how to build your product, but I don't see real fake data as something useful. I would imagine a string RNG number or UUID would solve 90%+ of all use cases

**Comment by rangav** [comment]
Hi all, started working on this, initially supports following variables

- randomString
- randomNumber
- randomEmail
- date
- dateISO

format will **{{_randomString}}**, single underscore prefix and variable name

let me know your feedback.

Planning to release new update by end of today.

**Comment by rangav** [comment]
Update: the underscore prefix is sometimes clearly not visible so changing the prefix to # 

the new format will **{{#randomString}}**

**Comment by rangav** [comment]
This feature is implemented now in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
