### ISSUE TITLE
It's unusable

### ISSUE THREAD

**Issue by M-Gonzalo** [rangav/thunder-client-support#1360]
**Describe the bug**

It won't let me open any of my saved requests. I just get an error about collections with more than 15 elements, but I'm not trying to run a collection, I just want to copy a param from an old request. I can't see my own data

**To Reproduce**

**Expected behavior**

I can understand you need to monetarize your work, but don't use our own work to hold us hostages. If you want to incentivize us to buy your product, entice us with extra functionality, don't rob us of what was functioning perfectly fine. Thank you.
**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Hi @M-Gonzalo

Please update the extension to `v2.12.5` and you can move the requests to other collections and be within the limits of 15 requests in the free version.

We are giving a free version of the software for FREE with limited features so it is suitable for personal or small companies, if you need more features users are required to purchase a subscription which is required for financial viability for our company.

**Comment by M-Gonzalo** [comment]
You're not understanding me, I didn't try to use a big collection, I couldn't even open a single request, any of them, inside or outside of a collection

**Comment by rangav** [comment]
You are alerted of this change everyday in the extension, then you should have made the changes needed by now.

If you still like to use our tool, please move requests to other collections

If you like to export the data by converting to postman format and use any other tool you can do it.
- https://github.com/rangav/thunder-client-support#how-to-convert-to-postman-format

**Comment by ultamatum** [comment]
Can I ask what is the reasoning behind this change other than forcing people to pay for data stored on their system?

**Comment by rangav** [comment]
Free version is meant for individual use only.

Big companies not supposed use our free version by the  teams. But most companies just ignore our terms or have not read. 

So we have to add this new restriction to stop free version from misuse.

since our storage is local only, we dont have a way of controlling number of users use the free version as team. 

Other API client with cloud storage can restrict number of team users accessing a project.

**Comment by rangav** [comment]
- We also increased the requests per collection limit to 25
- We have included the `Html Report` in free version

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.

**Comment by rangav** [comment]
Thanks for the feedback. We have increased the limit to `50 requests per collection` in the latest version `v2.13.2`
