### ISSUE TITLE
- You can load request data from different workspace easily.

### ISSUE THREAD

**Issue by HiraSomra** [rangav/thunder-client-support#1361]
- You can load request data from different workspace easily.

<img width="621" alt="Screenshot 2023-07-07 at 17 38 01" src="https://github.com/rangav/thunder-client-support/assets/8637550/b359bd26-8206-47c4-bde2-58de0104d204">

_Originally posted by @rangav in https://github.com/rangav/thunder-client-support/issues/1169#issuecomment-1625674417_

**Comment by rangav** [comment]
Closing your question not clear
