### ISSUE TITLE
not working with collections under 15 requests on free version

### ISSUE THREAD

**Issue by RaulJMCD** [rangav/thunder-client-support#1362]
**Question:**
I cant use any of my collections. 

I have collections over 15 requests, and other collections are under 15 requests. But I can't use none of them.
What am I missing here?
I have created a new collection with just one  request and still don't work.

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
Hi @RaulJMCD 

you cannot use the extension when any collection has more than 15 requests.

move requests to other collections and keep under 15 limit. Then everything works

**Comment by RaulJMCD** [comment]
All riight, I see now that ANY collection can have more than 15 requests, even if you are not using that collection. 
I think the messages can be more clear about this. 

thanks for the response.

**Comment by rangav** [comment]
Thanks for the feedback, will try to improve the message.

**Comment by rangav** [comment]
- We also increased the requests per collection limit to 25
- We have included the `Html Report` in free version

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.

**Comment by rangav** [comment]
Thanks for the feedback. We have increased the limit to `50 requests per collection` in the latest version `v2.13.2`
