### ISSUE TITLE
Option to run requests concurrently when running full collections/iterations?

### ISSUE THREAD

**Issue by victor-marino** [rangav/thunder-client-support#1363]
> **Please describe feature/problem details and the solution you'd like.**

When doing a batch run of all the requests in a collection (e.g.: the "runner-like" feature), each requests is only executed after the previous one has finished. However, when running load tests, it can be very useful to run all requests concurrently.

For instance, I may want to test a rate-limiting algorithm or a load balancing system in a proxy I'm building. These features are typically configured to reach a certain number of transactions per second (TPS) before they kick in, which is much easier to do (and measure) if your requests are launched concurrently as fast as possible.

> **Describe alternatives you've considered**

I have achieved this using a plugin for the Insomnia client, which allows you to choose between concurrent and sequential runs before running the test. But I couldn't find such option in Thunder Client.

> **Are you using the free version/paid version/trial:**

I'm using the free version. I could consider the 'Startup' pack if this feature was implemented, although the pricing seems quite steep and is a bit confusing to me.

For instance, is there any limit on the iterations feature when using the 'Startup' pack?

The [comparison table](https://www.thunderclient.com/pricing#compare) didn't even mention that the free plan doesn't support iterations... I found that (to my surprise) when trying to use the feature. I'm wondering if there might be other limitations in the 'Startup' pack as well that aren't mentioned in the table.

It's also unclear whether the limit of 250 collection runs per user and month also applies to iterations. E.g.: if I run a collection once, but using 250 iterations, have I consumed the whole monthly limit in one go? Or can I launch 250 monthly runs, even if each run does 1000 iterations?

In general, it seems like a really strange pricing policy to charge for the number of times we can run our own collections locally. It feels quite extreme to me, and makes me worried that those limits could be lowered further at any point in time, eventually forcing us to switch to higher and higher tiers.

I would appreciate any clarifications on this.

**Comment by rangav** [comment]
Hi @victor-marino 

concurrently running collection is in the roadmap.

Paid version plans does not have any limit on iterations.

for example you can run 1000 iterations on the startup plan. 

Hope its clear

**Comment by victor-marino** [comment]
> concurrently running collection is in the roadmap.

My bad, apologies for this. I searched but couldn't find it.

Do you know yet if this will be available in the free plan?

> Paid version plans does not have any limit on iterations.
> for example you can run 1000 iterations on the startup plan.

Thanks, good to know.

**Comment by rangav** [comment]
This feature will not be available in free plan.

**Comment by victor-marino** [comment]
Thanks for the prompt answer.

I know this is offtopic, but if I can provide some feedback on the pricing structure:

In order to build a solid userbase and become the "de-facto" API client, I think Thunder Client really needs a more flexible free plan that doesn't punish non-commercial usage so much. I think only through that kind of mass adoption and mouth-to-mouth recommendation, you can end up with businesses (both large and small) buying licenses for it, because that will be the tool their devs swear for, the one they've been using for years, and the only want they want to use at work.

But things like the 15-request limit per collection, or locking normal features behind the subscription... well, they just push away single devs who only want to use this for personal projects, not "Startups" like the plan name says. And people are rarely going to pay a subscription for something that doesn't generate any revenue for them.

Saving our collections wherever we want in our own filesystem and/or backing them up to our own (personal) GitHub repository is not a business or "startup" feature. It's part of the normal workflow for any personal project. So is being able to run a request 100 times (iterations) to test your own code. So all of this just hinders adoption at the bottom of your customer base pyramid, which is the fundamental pre-requisite for business (and thus paid) adoption later on.

Instead, most devs will switch to a different (free) solution for their non-commercial usage and build all their collections there. As a result, that's also the tool they'll want to continue using when they build a startup or join a company. And that's where the actual money rolls in.

Please don't take this the wrong way - this is of course just my personal opinion, and I could be completely wrong. You know your customer base best and you have data on them that I don't. And needless to say, I completely understand (and support) that you _do_ need to monetize Thunder Client _somehow_ if the project is to be sustainable. I know it's not easy to strike the right balance between pricing and user adoption, and even less so when trying to monetize a VS Code extension.

These are just my 2 cents on the topic, just in case you reconsider your commercial strategy in the future. I would want nothing more than for this project to succeed and become the go-to API client for most devs in the future. I think we can all agree that the world as a whole needs to move on from Postman!

**Comment by rangav** [comment]
Thanks for the feedback.

Other API Clients store data in the cloud, they can control how many users access a project.

Since we store data locally, the project can be accessed by 1 person or 1000 persons we don't know.

So all your suggestions will work for cloud sync api clients, will not work for us financially.

We are not targeting all users to our tool and we cannot make everyone happy.

**Comment by rangav** [comment]
I am closing this issue as there is existing issue

**Comment by rangav** [comment]
FYI - We have increased the limit to 50 requests per collection now

**Comment by rangav** [comment]
We have implemented this feature and published it to the marketplace, please update to v2.15.0

- FYI - we have included this feature in Free version also

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
