### ISSUE TITLE
When I click on delete an activity item, it shows error because of 15 limited items

### ISSUE THREAD

**Issue by playmono** [rangav/thunder-client-support#1364]
**Describe the bug**

When I click on delete an activity item, it shows error because of 15 limited items

**To Reproduce**
1. Click button right to one of the activity items.
2. Click on delete

**Expected behavior**
The items is successfully deleted

**Platform:** 
 - OS: Linux
 - vscode version:
 - extension version:

**Are you using the free version/paid version/trial:** 
Free

**Comment by rangav** [comment]
Thanks @playmono for reporting the bug, will look into it.

**Comment by rangav** [comment]
Its working for me

What version of the extension are you using?

**Comment by playmono** [comment]
v2.12.6

But now I cannot open the app anymore, it says: 
> Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

I tried to uninstall and install and happens the same :S

What did you change in this latest version??? :sweat_smile:

**Comment by playmono** [comment]
Ok, after reboot now is working...

**Comment by playmono** [comment]
Ok, after reboot now is working...

**Comment by Alokkumar8** [comment]
i had same issue. i uninstalled. rebooted. install. rebooted. then it worked.

**Comment by rangav** [comment]
- We also increased the requests per collection limit to 25

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.

**Comment by rangav** [comment]
Thanks for the feedback. We have increased the limit to `50 requests per collection` in the latest version `v2.13.2`
