### ISSUE TITLE
All collections and environments are wiped out on version downgrade

### ISSUE THREAD

**Issue by kapalkat** [rangav/thunder-client-support#1366]
**Describe the bug**
The latest version blocks the ability to use more the tool if there is more than 15 requests per collection. I had no time to split the collections so make it working so instead that I have moved the client to the last known version which was not blocking this. I moved to 2.10.5 and boooom....all my collections are gone...ale my envs are gone. Going back to the latest version (2.12.6) doesn't fix the issue. Collections and env are wiped out.

**To Reproduce**
As described

**Expected behavior**
Collections and envs are not wiped out...maybe some error with incompatibility or something but for sure NOT removed what people were gathering for years!!!!!!

**Platform:** 

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Your data is located here
https://github.com/rangav/thunder-client-support#storage

Please check and let us know

**Comment by kapalkat** [comment]
Yap, found them...however I have already tried to bring back some of the collections from my memory and I have named them with the same name as before and I see that those collections are overwritten:
![image](https://github.com/rangav/thunder-client-support/assets/26725074/adcc7c1a-7485-4b4a-9808-60763a6d70a1)
I guess those missing requests are gone for good...

**Comment by rangav** [comment]
You can follow this steps to convert to postman format
https://github.com/rangav/thunder-client-support#how-to-convert-to-postman-format

**Comment by rangav** [comment]
closing this issue, let me know if you have any further questions
