### ISSUE TITLE
HTML Report Generation Issue for v2.12.6

### ISSUE THREAD

**Issue by digi1010** [rangav/thunder-client-support#1367]
**Describe the bug**
HTML Report Generation Issue for v2.12.6

**To Reproduce**
1. Run the collection
2. Try to export the HTML report

**Expected behavior**
should allow user to export HTML report

**Platform:** 
 - OS: Windows 
 - vscode version: 1.80.1
 - extension version:v2.12.6
<img width="960" alt="MicrosoftTeams-image" src="https://github.com/rangav/thunder-client-support/assets/145583370/8fd09785-4980-4890-a093-6769528d39b9">

**Are you using the free version/paid version/trial: Free

**Comment by rangav** [comment]
@digi1010 Thanks for the feedback

Html report currently available for paid users only.

**Comment by rangav** [comment]
Will review about this change

**Comment by digi1010** [comment]
Thanks @rangav. We understand that free versions may have limitations, and we respect the need for a sustainable business model. However, if it is feasible to introduce this feature to the free version, it would undoubtedly benefit users like us who rely on your product for various purposes. We appreciate your dedication to continually improving Thunder Client and value your attention to user feedback.

**Comment by rangav** [comment]
- We have included the `Html Report` in free version
- We also increased the requests per collection limit to 25

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.
