### ISSUE TITLE
Cannot create new collection

### ISSUE THREAD

**Issue by brbecker** [rangav/thunder-client-support#1368]
**Question:**
I am trying to comply with the new 15 request limit for the free version by creating a new collection so I can move requests to them, but I'm unable to create a new collection. Any attempt to do so gives me the "Error: Free version only supports 15 request per collection. You can move requests to other collections or upgrade to premium version."

**Are you using the free version/paid version/trial:**
Free v2.12.6

**Comment by rangav** [comment]
Hi @brbecker 

please update to version `2.12.7` and try again 

let me know if you still have issues

**Comment by andersoncampolina** [comment]
Im having the same issue

**Comment by rangav** [comment]
@andersoncampolina can you share extension version you are using?

**Comment by brbecker** [comment]
After updating to v2.12.7, I was able to create new collections and move my requests into them, eventually getting under the 15 request cap. Thanks for the fix.

FYI, I'm using collections more like folders of similar individual requests rather than an automation tool across multiple requests.

**Comment by rangav** [comment]
Thanks for confirmation

**Comment by rangav** [comment]
- We also increased the requests per collection limit to 25
- We have included the `Html Report` in free version

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.0

Please let me know your feedback.

**Comment by rangav** [comment]
Thanks for the feedback. We have increased the limit to `50 requests per collection` in the latest version `v2.13.2`
