### ISSUE TITLE
If a user is opening existing POST request from collection then tab should shift to Body

### ISSUE THREAD

**Issue by anku580** [rangav/thunder-client-support#137]
**Is your feature request related to a problem? Please describe.**
I've created a collection in thunderclient that includes basic CRUD operation requests. However, when I open the POST request, every time I've to switch the tab to Body to update the request body. By default, the POST request opens in a Query Tab.

**Describe the solution you'd like**
Well, to my understanding since it is a POST request, usually the user will be updating the contents of the request so by default the Body tab should be opened. Let me know your thoughts.

**Comment by rangav** [comment]
Hi @anku580 user can do anything after opening a existing post request, like adding headers, auth, tests, or body? Generally first tab will be active and then user can go to any tab depending on his use case.

**Comment by anku580** [comment]
That's true @rangav but can we persist the state of that request? 

Every time switching to default for an already existing request in a collection seems like overwork.

**Comment by anku580** [comment]
sure buddy, no problem :)

**Comment by rangav** [comment]
@anku580  This feature is now implemented and published to marketplace as release version `v1.14.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2

Let me know if any feedback
