### ISSUE TITLE
when update lastest,  the request data file dont find. 

### ISSUE THREAD

**Issue by ChinaSunBoyVersion001** [rangav/thunder-client-support#1370]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Can you please reload vscode and try again. 

Can you share a screenshot?

**Comment by ChinaSunBoyVersion001** [comment]
> Can you please reload vscode and try again.
> its useless,  Storage Location  are no documents
> Can you share a screenshot?
![企业微信截图_16967458063099](https://github.com/rangav/thunder-client-support/assets/131323500/1469a084-aafe-4193-9009-57499a9c0082)


•when I want to use the request in collections, but it prompts me   (Error: Free version only supports 15 request per collection...) ,so unnload then download v2.12.7, finally gameover

**Comment by rangav** [comment]
Please update to the latest version `v2.13.0` and try again

Your data is located here
https://github.com/rangav/thunder-client-support#storage

**Comment by rangav** [comment]
We have increased the limit to `50 requests per collection` in the latest version `v2.13.2`
