### ISSUE TITLE
Incrementing an environment variable appears to have the environment file cached

### ISSUE THREAD

**Issue by carlMosettig** [rangav/thunder-client-support#1373]
**Describe the bug**
Incrementing a variable within an environment file does not take effect until the request completes

**To Reproduce**
Assuming an environment variable in place 'incrementCount' set with a value of 0.

Create a new get request, add a new post execution code element that will loop the request 20 times, for example

let incrementCount = tc.getVar('incrementCount') || 0

while( incrementCount < 20)
{
        // acting as if i didnt get the desired response so would like to retry
       tc.runRequest(<this request id>)
       incrementCount = incrementCount + 1
      tc.setVar( 'incrementCount', incrementCount)
      console.log(incrementCount)
}

**Expected behavior**
incrementCount should be incrementing and the console log should read similar to
1
2
3
4

**actual behaviour **

behaves like incoming environment is cached, console outputs

0
0
0
0
0

acts as if the final write to the environment isnt done until the request and code behind ends.

**Platform:** 
 - OS: macos
 - vscode version: 1.82.3
 - extension version: v2.13.0 - (2023-10-08)

tried free and trial

**Comment by rangav** [comment]
Hi @carlMosettig 

Thanks for reporting the bug, Will fix it asap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.13.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.3

Please let me know your feedback.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.13.5`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.5

Please **test** and let me know your feedback.

**Comment by rangav** [comment]
Also I think you should use `if` condition instead of `while` as when you call `runRequest` it is doing the loop already.

**Comment by rangav** [comment]
Also you should rearrange the code 
- change `while` to `if` condition
- move `runRequest` at the if condition, otherwise the next part of code is not reached, as you are calling runRequest which starts the process same request again.

```js
let incrementCount = tc.getVar('incrementCount') || 0

if( incrementCount < 20)
{
      incrementCount = incrementCount + 1
      tc.setVar( 'incrementCount', incrementCount)
      console.log(incrementCount)
     // acting as if i didnt get the desired response so would like to retry
      tc.runRequest(<this request id>) // <<--------------
}
```
