### ISSUE TITLE
runrequest for the same request doesnt execute post request script

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1374]
**Describe the bug**
Hi Ranga,

since the new CLI Update from 1.7.0 -> 1.7.1 the command tc.runRequest leads to an error. 
We have script where we execute the same Request, till the response is giving the expected attribute. 
In the earlier Version this worked well, but with the update we noticed that our tests are failing. 

We noticed the following behaviour: 

1. send request with post request script
1.1 expecting an attribute in response
1.2 giving console.logs, from post request script, in output to check the attribute
1.3 if its not the expected attribute, send the same request with tc.runrequest() till the expected attribute appears
2. sending the same Request
2.1 in the console the output didnt deliver the console.log from the first Step.

![image](https://github.com/rangav/thunder-client-support/assets/112586589/68d63aac-d9f7-40bf-9a6e-84cd1c35b29d)
![image](https://github.com/rangav/thunder-client-support/assets/112586589/fdcd73b7-b903-4ff6-b77e-7f4e2df590b0)

**Platform:** 
 - OS: Windows 10
 - vscode version: 
 - extension version: 1.7.0

**Are you using the free version/paid version/trial:**
paid

**Comment by rangav** [comment]
Hi @erwinmoretz thanks for reporting the bug.

Reverted to old code, should be fixed now. Please update CLI to `v1.7.2`

**Comment by rangav** [comment]
Please test and confirm, so I will update the extension also

**Comment by rangav** [comment]
one suggestion -  tc.runRequest instead of hardcoding the id - you can use the below

- `await tc.runRequest(tc.request.id)`

**Comment by erwinmoretz** [comment]
thanks for your hint! 

but the updated cli doesnt work aswell, same result: 

![image](https://github.com/rangav/thunder-client-support/assets/112586589/28b6b92d-ae68-4a9f-9701-0bddb9d9051d)

**Comment by rangav** [comment]
can you please confirm cli version using - `tc -v`

**Comment by erwinmoretz** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/112586589/f7edcd3a-d740-4bb7-8886-6332751e57ea)

**Comment by rangav** [comment]
made a few more changes, please update to - `v1.7.3` and try again
may be reset the `maxAttempts` variable value

**Comment by erwinmoretz** [comment]
thanks ranga, 

the new version works local in cli and in ci/cd!

**Comment by rangav** [comment]
Thanks, Erwin for confirmation
