### ISSUE TITLE
How to get the current request name from leaf node in collection tree?

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1375]
**Question:**
How to get the current request name from leaf node in collection tree?

![RequestName](https://github.com/rangav/thunder-client-support/assets/58699432/6ceb08b7-77c1-447e-9926-e516ee034b22)

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Hi @franky1964 this feature is implemented 

see details here https://github.com/rangav/thunder-client-support/issues/904
