### ISSUE TITLE
Pipeline job success if no collection is running

### ISSUE THREAD

**Issue by NSchefner** [rangav/thunder-client-support#1376]
**Describe the bug**
I had a successful job, when I looked into the console, I noticed that no collection had been executed. The error that was logged was "Error: e.toLowerCase is not a function"

The error was that I executed the command for the collection and the environment in the script, but did not specify an environment as a variable for the job.

What's bad is that the pipeline job ran successfully and didn't cause an error.

**To Reproduce**
Specify TC_COLLECTION with TC_ENV in the job script and then do not include the TC_ENV variable in the job

**Expected behavior**
The error occurs and the pipeline job fails

**Platform:** 
 - Win: 10 
 - vscode version: 1.83.1
 - extension version: 2.13.5

**Are you using the free version/paid version/trial:**
I use the Enterprise version. I belong to Erwin Moretz and Frank Blechschmidt from the DB.

**Comment by rangav** [comment]
Thanks, @NSchefner for reporting the bug, will look into it.

Is the script part of `pre-request` or `post-request`?

**Comment by NSchefner** [comment]
What this means is the script in the gitlab-ci.yml. When configuring the pipeline, you enter the Thunder Client commands for executing the collection and the environment in the script area of ​​the job

**Comment by rangav** [comment]
thanks, can you please share any screenshots of the CLI log to the console, and `hide` any `sensitive` info.

**Comment by NSchefner** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/148068833/d46bdeb1-21f4-4c95-b539-32fa5ebf96dd)

![image](https://github.com/rangav/thunder-client-support/assets/148068833/76bbbf68-6bfc-4b99-8008-bf532e3a80d6)

![image](https://github.com/rangav/thunder-client-support/assets/148068833/b175563f-9b88-4104-9127-b1f076c537f7)

**Comment by NSchefner** [comment]
gitlab-ci.yml configuration

![image](https://github.com/rangav/thunder-client-support/assets/148068833/cb8dc2c3-0bf2-4be9-9ed9-7daa23c35ffb)

**Comment by rangav** [comment]
`Error: e.toLowerCase is not a function` is the error happening in yaml code or in tc CLI?

**Comment by rangav** [comment]
Is it possible share tc cli run log?

**Comment by NSchefner** [comment]
You mean the complete console log from Gitlab Job

**Comment by rangav** [comment]
Yeah if possible or the section where tc executed

hide any sensitive

**Comment by NSchefner** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/148068833/b9408bd9-0c41-41cc-b158-92a94cac128d)

**Comment by rangav** [comment]
looks like tc `cli` did not run at all.

what is the value of `$TC_COLLECTION` variable? the value should be `--col "colName"`

**Comment by NSchefner** [comment]
So yes the value has --col"colName", but as I wrote it is on TC_ENV, I didn't specify that in the job, see the screenshots above.

We also found the error and fixed it.

But the problem is that it is not recognized as an error and the job runs successfully

**Comment by NSchefner** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/148068833/1ff3f906-e72d-44d7-895f-38ad5b04f636)

**Comment by NSchefner** [comment]
Thx

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.14.0`

https://github.com/rangav/thunder-client-support/releases/tag/v2.14.0

Please test and let me know your feedback.

**Comment by NSchefner** [comment]
Thanks for the fix. I'll test it. Sadly I can't make it today, but I'll test it on Monday.

**Comment by NSchefner** [comment]
Hi Ranga, sorry it took a little longer. 
The bug is fixed. 
Thanks and thx also for the inline scripting
