### ISSUE TITLE
Copy/Paste from context menu does not work

### ISSUE THREAD

**Issue by markafox** [rangav/thunder-client-support#1377]
When right clicking on selected text, in VS Code (1.83.1) Windows 11 the context menu with Cut, Copy, and Paste is displayed but they do not cut, copy or paste. A minor annoyance on free software but unacceptable in the paid version.

**Comment by rangav** [comment]
Hi @markafox this is vscode issue. and the menu is provided by vscode.

https://github.com/rangav/thunder-client-support/issues/1092#issuecomment-1490888852

**Comment by rangav** [comment]
I am closing this issue.

**Comment by markafox** [comment]
VS Code issue: [#141080](https://github.com/microsoft/vscode/issues/141080)
