### ISSUE TITLE
Cannot view/edit long environment variable values

### ISSUE THREAD

**Issue by markafox** [rangav/thunder-client-support#1378]
**Describe the bug**
Environment variables values over 122 characters in length are visually truncated.

**To Reproduce**
On the Thunder Client Environment tab create an environment variable and type or paste in a value that is longer than 122 characters. After 122 characters, characters for 120-122 become three periods "..." and the remainder of the text is hidden.

**Expected behavior**
The full environment variable value should be shown.

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.83.1
 - extension version: 2.13.5

**Are you using the free version/paid version/trial:**
Paid

**Comment by rangav** [comment]
Thanks @markafox for reporting the bug.

I have fixed the bug now. Will include in the next release.

Planning to release next update by end of this week.

**Comment by rangav** [comment]
This Bug is fixed now and published to the marketplace, please update to `v2.14.0`

https://github.com/rangav/thunder-client-support/releases/tag/v2.14.0

Please test and let me know your feedback.
