### ISSUE TITLE
Clear Cookies for select requests in Collection after collection run

### ISSUE THREAD

**Issue by askherconsulting** [rangav/thunder-client-support#1379]
**Question:**
I want to clear the cookies from a collection run programatically, but only for *some* of the endpoints in the collection - others will not re-run without cookies being present.

Is this possible in Thunderclient in a programatic way? Currently, I have to manually go into the selected endpoints after each run and hit the clear all button, but doing this automatically to allow subsequent runs to work without manual edits would be preferable.

**Are you using the free version/paid version/trial:**

Trial

**Comment by rangav** [comment]
Hi @askherconsulting 

you can clear cookie from script using `tc.clearCookies()`

all functions available 
https://github.com/rangav/thunder-client-support/blob/master/docs/tc-types.d.ts

**Comment by askherconsulting** [comment]
Thanks - the command however is to clear all cookies.

How can I made this apply to just a single endpoint in a collection?

**Comment by rangav** [comment]
Currently not possible, will add it in the next update in 1 or 2 days.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.14.1`

See release notes
https://github.com/rangav/thunder-client-support/releases/tag/v2.14.1

Please test and let me know your feedback.
