### ISSUE TITLE
HTTP Headers (raw format) does not retain the unselected headers

### ISSUE THREAD

**Issue by mrmaramreddy** [rangav/thunder-client-support#1382]
**Describe the bug**

HTTP Headers (raw format) does not retain the unselected headers.

**To Reproduce**

Selects the Request Headers tab
Unselect any headers (by unchecking the checkbox)
Save the changes
Select the "Raw" checkbox
Notice the unselected headers are not commented (in postman unselected headers are prefixed with //)
Uncheck "Raw" checkbox 
Notice the previously unselected headers are now selected.

**Expected behavior**

Unselected HTTP headers should retain same status on select and unselect of "Raw" checkbox.

**Platform:** 
 - vscode version: 1.83.1
 - extension version: v2.14.0

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
Thanks @mrmaramreddy for reporting the bug, Will verify and fix it asap.

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace, please update to `v2.14.1`

See release notes
https://github.com/rangav/thunder-client-support/releases/tag/v2.14.1

Please test and let me know your feedback.

**Comment by mrmaramreddy** [comment]
Awesome, it works now with ```v2.14.1```
