### ISSUE TITLE
thunderclient cli proxy configuration

### ISSUE THREAD

**Issue by elRisitas69** [rangav/thunder-client-support#1383]
I've been liking the vs code extension so I've decided to get the paid version in order to utilize cli integration.
Unfortunately, I can't get the cli utility to adhere to my proxy settings. I've tried setting env vars in the zsh and modifying settings.json inside ~/Library/Application Support/Code/User.

Am I overlooking something? Is there maybe a way to set the proxy config for the cli tool separately? 
The GUI version works fine, I can even use the --ui flag to successfully run requests from the shell because the extension itself can utilize the proper proxy configuration.

**Comment by rangav** [comment]
Hi @elRisitas69 

Updated the CLI Proxy details in docs
https://github.com/rangav/thunder-client-support/tree/master#cli-proxy

**Comment by elRisitas69** [comment]
thanks for the quick support @rangav !
