### ISSUE TITLE
Is there a way to get current active environment name in the inline script?

### ISSUE THREAD

**Issue by mrmaramreddy** [rangav/thunder-client-support#1385]
**Question:**
Is there a way to get current active environment name in the inline script? Equivalent to postman ```pm.environment.name```

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
Hi @mrmaramreddy Currently not possible, But will add it to the roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to v2.15.0

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
