### ISSUE TITLE
Automatically refresh the Auth token does not work.

### ISSUE THREAD

**Issue by Danny-ouo** [rangav/thunder-client-support#1386]
**Describe the bug**
If request has "pre-request" the function that automatically refresh the Auth token does not work. 

**To Reproduce**
When I send a request that includes the “pre-request”, automatically refresh the Auth token does not work. So response status is "401 Unauthorized".
However, when I send a request that not contain the “pre-request”, the Auth token is automatically refresh.
![image](https://github.com/rangav/thunder-client-support/assets/24267668/3fd5fca7-3410-48bc-baa5-b92af1339554)

**Expected behavior**
Auth token is refresh automatically and the API request works.

**Platform:** 
 - OS: Windows 10 Pro
 - vscode version: 1.83.1
 - extension version: 2.14.1(thunder client)

**Are you using the free version/paid version/trial: I used free trial version. But now I use free version.**

**Comment by rangav** [comment]
Hi @Danny-ouo Thanks for reporting the bug, Will look into it.

Where are the Auth details saved? is it the main request or collection settings?

**Comment by Danny-ouo** [comment]
Auth details is saved in collection settings.

**Comment by rangav** [comment]
I can reproduce the error, thanks for reporting it. Will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.16.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.16.0

Please test and let me know your feedback.

**Comment by Danny-ouo** [comment]
It works! Thanks a lot :)

**Comment by rangav** [comment]
Thanks for confirmation
