### ISSUE TITLE
Duplicate header values are concatenated 

### ISSUE THREAD

**Issue by mrmaramreddy** [rangav/thunder-client-support#1388]
**Describe the bug**
When duplicate headers are added to the HTTP headers, the values are concatenated to one header. 

**To Reproduce**
For example if you add following HTTP headers

firstname=john
firstname=john

HTTP request sends it as, firstname = "john,john"

**Expected behavior**
Duplicate headers as added to the headers to send in http headers like below from above example

firstname=john
firstname=john

**Platform:** 
 - OS: Mac
 - vscode version:1.83.1
 - extension version:v2.14.1

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
Hi @mrmaramreddy This is the expected result. Duplicate headers are not possible to send.

you can test in other api clients and see the result

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen it if needed
