### ISSUE TITLE
Support management collection as Workspace

### ISSUE THREAD

**Issue by phnhan0301** [rangav/thunder-client-support#139]
When using postman, I can management my collection in Workspace (like as personal, work...)
If can, please add workspace feature

Thanks so much

**Comment by rangav** [comment]
Hi @phnhan0301 you can create sub-folders inside a collection. there is no sub-collection thing.

Also see **Team Features section** to create collections per project.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.
