### ISSUE TITLE
I want Tests to examine deeper property values in response parameters

### ISSUE THREAD

**Issue by Zy76278** [rangav/thunder-client-support#1390]
**Please describe feature/problem details and the solution you'd like.**

I want to check if the innermost data field in the json response from the interface has any data，example：

```js
let json = {
  "code": 0,
  "msg": "操作成功",
  "data": {
    "data": [
        {
        "id": "43389",
        "createTime": "1678342507906",
        "updateTime": "1698136252270",
        "isDeleted": 0,
         "hisCode":"H00000089",
        "orgCode": "",
        "drugSpecsPack": "",
        "hisGenericPing": ""
        }
     ]
   }
}
```
**Describe alternatives you've considered**

For Now,it doesn't distinguish which level it is:
<img width="348" alt="1111" src="https://github.com/rangav/thunder-client-support/assets/92496121/628c710e-91dc-4df2-86ce-9126a1adf86b">

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Hi @Zy76278 see answer in the below image

<img width="1067" alt="Screenshot 2023-11-02 at 11 56 48" src="https://github.com/rangav/thunder-client-support/assets/8637550/b30b8b75-b834-4083-be13-ac88b2c72f07">

**Comment by rangav** [comment]
I am closing this issue, feel free to continue the discussion if you have any further questions.
