### ISSUE TITLE
CLI to support multiple report

### ISSUE THREAD

**Issue by esp0314** [rangav/thunder-client-support#1393]
Hi @rangav

**Please describe feature/problem details and the solution you'd like.**
We are running multiple collections with multiple scenarios in the azure pipeline, and with the latest update of CLI, reports merged into one report. With this kind of format, its hard for us to validate which API was failed because it is now merged to one report. Could you please add an option to not merge the report?

![image](https://github.com/rangav/thunder-client-support/assets/148940089/eea14335-67fe-43bc-852c-596a3e33dc45)

Here's the previous report using older version of CLI
![image](https://github.com/rangav/thunder-client-support/assets/148940089/b60e5e3a-935f-4bb9-8f2f-4febffae50d2)

**Are you using the free version/paid version/trial:**
Paid version

**Comment by rangav** [comment]
Hi @esp0314 

we have made changes to xml report for folders 

see details here - https://github.com/rangav/thunder-client-support/issues/1277#issuecomment-1772675113

**Comment by esp0314** [comment]
Hi @rangav,

I checked the version 1.9.0 but still, multiple scenarios/requests under one folder is merged into one result
![image](https://github.com/rangav/thunder-client-support/assets/148940089/a0d417ad-7633-4abd-900b-2285a6ea3015)


What i would like to be presented is, if i have a folder with multiple scenarios, result should be display as per scenario. This kind of format is easier to check which scenario was failed. Screenshot below is the previous format(version 1.8.0 and lower). 
![image](https://github.com/rangav/thunder-client-support/assets/148940089/59333043-aa8e-405c-9196-fe6188bf035f)

**Comment by rangav** [comment]
Looks like the grouping is the azure pipeline is based on the `classname` attribute on the `testcase` element

The current classname is `dc.getperiods` in v1.9.0

If we update classname value to `dc.getperiods.dc-get-periods-kbb` and `dc.getperiods.dc-get-periods-jd` 

May be this will fix the issue?

**Comment by rangav** [comment]
I looked at the[ JUnit spec](https://github.com/testmoapp/junitxml) , The classname should be name of testsuite

<img width="735" alt="Screenshot 2023-11-07 at 18 42 30" src="https://github.com/rangav/thunder-client-support/assets/8637550/686b4705-a7bc-4324-9a95-94104ab6564e">

**Comment by esp0314** [comment]
> f we update classname value to `dc.getperiods.dc-get-periods-kbb` and `dc.getperiods.dc-get-periods-jd`



> If we update classname value to `dc.getperiods.dc-get-periods-kbb` and `dc.getperiods.dc-get-periods-jd`

I think it will fix the issue

**Comment by rangav** [comment]
What are the correct values for classname?

1. `dc-get-periods-kbb` and `dc-get-periods-jd`
2. or `dc.getperiods.dc-get-periods-kbb` and `dc.getperiods.dc-get-periods-jd`

**Comment by esp0314** [comment]
dc.getperiods.dc-get-periods-kbb and dc.getperiods.dc-get-periods-jd

**Comment by rangav** [comment]
I have published new version of CLI - `v1.9.1` to fix this issue.

Please test and let me know your feedback.

**Comment by esp0314** [comment]
Thank you, @rangav. It is now displayed per request/test scenario.
![image](https://github.com/rangav/thunder-client-support/assets/148940089/a00097fe-9bc6-4452-ac43-dd4b7a5d8ab3)

**Comment by rangav** [comment]
Thats Good - Thanks @esp0314 for confirmation.
