### ISSUE TITLE
Apply Pre Run and Tests to collection

### ISSUE THREAD

**Issue by hmmftg** [rangav/thunder-client-support#1394]
Hi, thank you for all your effort in this product
**Please describe feature/problem details and the solution you'd like.**

on our project we have some tests or pre-runs used in all members, for example oauth 2 token should be generated with login request and should be logged out after request completion, so we copy and paste pre-request and test script for all members of collection. I think it's far better to set pre run and test script for all members of the collection and the request will be much cleaner and adding new members will be much easier.

**Describe alternatives you've considered**

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Hi @hmmftg 

The feature is already available 

you can open `collection settings` and add pre request and test scripts

**Comment by hmmftg** [comment]
thank you for your response, but the tests are ran only if request is successful, how can I configure it to be executed in any situation?

**Comment by rangav** [comment]
Can you provide more details by sharing screenshot

**Comment by hmmftg** [comment]
sorry my mistake on using request name instead of it's unique id in script

**Comment by rangav** [comment]
no problem
