### ISSUE TITLE
Performance slow on macOS

### ISSUE THREAD

**Issue by azplanlos** [rangav/thunder-client-support#1398]
**Describe the bug**
Performance of Thunder Client plugin within Visual Studio Code is very slow on macOS when a workspace with multiple collections with many folders and requests is open. Opening a request window takes up to 45-60 seconds while the whole client is unresponsive and multiple messages are presented by Visual Studio Code to inform about this unresponsibilty asking if the user wants to wait ore close the window. Meanwhile the request body of the request is already shown but existing variables are not highlighted in the correct color which changes after the window gets responsive again.

<img width="323" alt="Bildschirmfoto 2023-11-09 um 11 07 42" src="https://github.com/rangav/thunder-client-support/assets/2248438/54452d8c-97b1-4b54-9e41-675f21eeacd5">

**To Reproduce**
Open a request

**Expected behavior**
should open quickly

**Platform:** 
 - OS: macOS 14.1 (Apple M2 Pro)
 - vscode version: 1.83.0 (Universal)
 - extension version: 2.15.0

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Thanks @azplanlos reporting the bug, will look into it.

**Comment by rangav** [comment]
One Clarification:

Does the issue happen with Request Views only?

Can you open evironment view - is it slow or good?

**Comment by azplanlos** [comment]
Environment view is good, also "RunAll" view opens quickly as expected, also browsing the collection is fine. Seems to be request view only.

**Comment by rangav** [comment]
I did notice that the Request view is slow sometimes, might be the Ace Editor library that I am using is not updated for Apple Silicon.

Will investigate the issue further and get back to you asap.

**Comment by rangav** [comment]
I will make couple of code changes for testing and `Upload VSIX` file here for you to confirm which changes is fixing the issue.

Will you be available for quick testing?

**Comment by azplanlos** [comment]
Sure, just let me know

**Comment by rangav** [comment]
Can you please test the below version and let me know if you noticed any difference?

[vscode-thunder-client-2.15.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/13307290/vscode-thunder-client-2.15.1.vsix.zip)

**Comment by azplanlos** [comment]
Yes, this is much better now, thank you!

**Comment by rangav** [comment]
Thats Good, Thanks for confirmation - do you notice any other performance issues?

**Comment by azplanlos** [comment]
no, overall performance is very good now.

**Comment by rangav** [comment]
Super, Thanks for confirmation.

The change I made is that in the body JSON editor - the env variable highlighting is disabled. Which is causing the issue I guess.

**Comment by rangav** [comment]
@azplanlos I have re-enabled JSON body editor highlighting, but made a few code optimization around this issue.

[vscode-thunder-client-2.15.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/13308386/vscode-thunder-client-2.15.2.vsix.zip)

- Now I added a vscode setting to disable hightlighting

<img width="822" alt="Screenshot 2023-11-09 at 13 03 14" src="https://github.com/rangav/thunder-client-support/assets/8637550/38fd50f0-4d23-4145-880b-ca5c34e33a8b">

Can you please test with the above with setting enabled and disabled, and let me know the performance difference.

**Comment by rangav** [comment]
When you change setting value, please close request view and reopen

**Comment by azplanlos** [comment]
just testet your new version and it works fine regardless of the highlight setting.

**Comment by rangav** [comment]
Good Thanks, The changes I made to the code are working then. I will publish an update later today with these changes.

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.15.3`

https://github.com/rangav/thunder-client-support/releases/tag/v2.15.3

Please test and let me know your feedback.
