### ISSUE TITLE
v1.1.0 Features & Discussion

### ISSUE THREAD

**Issue by rangav** [rangav/thunder-client-support#14]
Hi All,

Thanks everyone for the support. Just want to give an update of whats coming for the next release. This will be major update since initial launch.

Here are the planned features for v1.1.0

**New Features**
- **Custom Storage** Location for collections to integrate with git, see README for details -  #2   (**status:** completed)
- **Nested folder** support for Collections - #8  (**status:** completed)
- **Improved request creation** workflow to save to collections faster - #7  (**status:** completed)
- **Run Last Request** from command palette. #2 (**status:** completed)
- **Drap & Drop sorting** for requests & folders (**status**: completed)
- Support Ctrl+S to save env vars #36 (**status**: completed)
- Create variable in env if doesn't exist when set - #35 (**status**: completed )
- Postman import nested folder support (**status**: completed )
- Shift+Alt+F to format JSON body #17
- proxy settings #61
- Show "Test Results" count in red if a test fails #55

**BUG Fixes**
- Fixes typed url text coverts to html symbol (**status:** completed) - #13 
- Fixes state value missing in OAuth 2.0 Url (**status:** completed) - #26 
- Fixes enable scope for OAuth client credentials request (**status:** completed) - #25 
- Fixes Set Env Variable in Tests only works on last instance v1.0.7 - (**status:** completed) - #46 
- Fixes Cannot test is equal to env variable - (**status:** completed) #58
- Fixes  Can't Import Postman Collection for no reason #77
- Fixes Broken format in JSON Body #63
- Fixes Import and save body parameters #47
- Can't save more than one environment variable from response #81

### ANNOUNCEMENT
- Thunder Client has **crossed 50k downloads** now, Thanks for the amazing response from everyone 🎉.

### LIVE NOW
- Pulished v1.1.0 -  documentation is updated partially.

If anything is not clear, please post your comments below, i will update documentation.

Please leave your feedback about v1.1.0 - features you like or  features that need further improvements..

**Comment by Stancobridge** [comment]
Nice one

**Comment by anastely** [comment]
@rangav  Can you add a Collection length under the collection name, like Postman?

>collection name
> 24 requests

**Comment by rangav** [comment]
Hi @anastely can you please create a new feature request, I will add to product roadmap list.

**Comment by jongio** [comment]
ETA for next release with #26 included?

**Comment by rangav** [comment]
Hi @jongio I am planning to release by end of the day tomorrow.

**Comment by jongio** [comment]
Thanks.  It would be cool if you could use the GitHub Releases feature so I can subscribe to releases.

**Comment by rangav** [comment]
Sure will start using Github release feature.

**Comment by rangav** [comment]
Hi All - version 1.1.0 is now published, please and let me know your feeback

**Comment by Pascal62223** [comment]
Hi,
   Looking at Thunder-client and it looks great.  Trying the 'test' feature and couldn't find a way to filter out the response based on a response property value when the response itself is an array of json objects.
   Use case : How to filter filter response to only show location.latitude == "25" in below example. (trying json.location.latitude doesn't work obviously as it is an array)

   [
     {
        "location" : {
           "latitude" : "25",
           "longitude" : "50"
        }
     },
     {
        "location" : {
           "latitude" : "00",
           "longitude" : "76"
        }
     }
   ]

**Comment by rangav** [comment]
Hi Pascal use json[0].location

**Comment by Pascal62223** [comment]
Thanks. I thought about that but was under impression it would only apply the test on he first object of the array and not to all objects in a loop.
I've tested, and it works :-)

**Comment by rangav** [comment]
Hi @Pascal62223 try json[0].timeZone == "+00:00", it does not have any time conversion functions built in. just try to match the strings

**Comment by Pascal62223** [comment]
Hi @rangav , Yes I do understand it does string match. The example is using timeZone as property, as I try to get all  record with property timeZone equals to teh string 'Z'
To ensure there is no confusion (I have no intend to do time conversion),  I use another example with the property 'uuid' which is a GUID string, and use the action 'contains'. Pure string match.
The response contains records with  'uuid' do not contains the string 'c93fbd6e' as specified in the test query criteria.
Also in that particular case the test result show an error (Cf. 2nd picture below) when doing the comparison apparently.

![image](https://user-images.githubusercontent.com/77442348/116649574-2da51b00-a9b2-11eb-923e-c1b6229dbc17.png)

Error when executing comparison : 
![image](https://user-images.githubusercontent.com/77442348/116650002-e2d7d300-a9b2-11eb-8063-479e441ddf46.png)
![image](https://user-images.githubusercontent.com/77442348/116650025-ee2afe80-a9b2-11eb-8647-8ff560da03d4.png)

**Comment by rangav** [comment]
Hi @Pascal62223 can you please create a separate bug for this, we can do discussion there. I will verify in the mean while.

**Comment by Pascal62223** [comment]
Ok. Thanks a lot
