### ISSUE TITLE
PUT/POST Form/Form-encode input values strip out tags

### ISSUE THREAD

**Issue by Isuckatdeving** [rangav/thunder-client-support#140]
**Describe the bug**
Anything that proceeds after a '<' character (with NO white-space), while typing values in to the Form/Form-encode input fields, is immediately deleted.

**To Reproduce**
Type '<' and then any character and it will erase the entire string after it. Placing a '<' within any string deletes the string if you place it where the is no proceeding white-space. 

**Expected behavior**
Should not deleted a string that has '<' and no proceeding white-space.

**Platform:** 
 - OS: Windows !0

**Solution:**

**Comment by rangav** [comment]
Hi @Isuckatdeving thanks for reporting. Will fix and release an update later on this week.

**Comment by miagg** [comment]
The same goes for the Response Headers.
If a Header value has '<' it strips the whole tag.
For example the link header in the following response is not actually '; rel="next" but <https://domain....>; rel="next".

**Comment by rangav** [comment]
This is now fixed in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.

**Comment by michael-tipton** [comment]
> 
> 
> This is now fixed in v1.3.0
> https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
> Let me know if any questions.

Confirmed. Seems to now be working as expected for me. Will report if I find any other issues. Thank you for the rapid fix!

**Comment by rangav** [comment]
Thunder  @michael-tipton for confirming 👍
