### ISSUE TITLE
Skip individual requests option during collection run from Scripts 

### ISSUE THREAD

**Issue by checkerix** [rangav/thunder-client-support#1402]
**Question:**
Before starting a collection run, you can set individual requests to be skipped, 
but I would like to make this decision in the inline scripts (e.g. dependent on variables). 
Is this possible?

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Hi @checkerix 

Currently not possible, will add this feature in the next update.

**Comment by rangav** [comment]
Can you also please confirm your subscription by using below form for our internal information.
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
The new proposed api will be - `tc.skipRequest("reqId");`

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.16.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.16.0

Please test and let me know your feedback.

**Comment by checkerix** [comment]
Thank you very much!
