### ISSUE TITLE
Import collection with request auth set is not supported

### ISSUE THREAD

**Issue by Plausible0Bug** [rangav/thunder-client-support#1403]
**Describe the bug**

It seems if an auth configuration exists the import of a collection will fail silently.

**To Reproduce**

Import following JSON:
```
{
	"info": {
		"_postman_id": "cf6aba3d-5aa0-4f4e-925c-7c77c51d672a",
		"name": "Schedule",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json",
		"_exporter_id": "11112222333"
	},
	"item": [
		{
			"name": "https://some.test.workers.dev/",
			"request": {
				"auth": {
					"type": "basic",
					"basic": {
						"password": "my-top-secret-api-pass-word",
						"username": "api"
					}
				},
				"method": "POST",
				"header": [],
				"url": "https://some.test.workers.dev"
			},
			"response": []
		}
	]
}
```

**Expected behavior**

The collection should be imported with 1 request.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.84.2
 - extension version: 2.15.3

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Hi @Plausible0Bug 

Postman import 2.0.0 format not supported 

Please export in 2.1.0 format in Postman app

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
