### ISSUE TITLE
Read secrets from an Azure Key Vault

### ISSUE THREAD

**Issue by glconti** [rangav/thunder-client-support#1405]
**Question:**
📄 We would like to have a custom filter to read secrets from an azure Key Vault, something we were already doing in Insomnia. The code is pretty simple, it uses MS purely node apis. Unfortunately, we get an error when trying to load the modules we need. 

> Script Log: Error loading node package: @azure/identity - Cannot find c:\Users\***\.vscode\extensions\rangav.vscode-thunder-client-2.15.3\dist\node_modules\@azure\msal-node\index.js in plugin @azure/msal-node

💡 The idea is to have a custom filter used like this:

`{{KeyVaultName | getSecret("MySecretName")}}`

`KeyVaultName` is an env variable, `MySecretName` is a string parameter. This will allow use to retrieve any secret from a key vault and rely purely on Azure permissions (the MS node library dependes on the Azure Cli being installed on the pc).

The script for the custom filter is also very simple:
```js
async function getSecret (input, param1) {

    const url = "https://" + input + ".vault.azure.net";

    const DefaultAzureCredential = await tc.loadModule("@azure/identity");
    const credential = new DefaultAzureCredential();

    const SecretClient = await tc.loadModule("@azure/keyvault-secrets");
    const client = new SecretClient(url, credential);

    const secret = await client.getSecret(param1);

    console.log(`read secret ${param1} from ${url}`);

    return secret.value;
}

module.exports = [getSecret];
```

❔ Is it something that ThunderClient doesn't support yet (I read it may not support all node modules out of the box) and could do in the future? Or is there a problem in how we call the ThunderClient apis?

**Are you using the free version/paid version/trial:**
Trial - Accelleron

**Comment by rangav** [comment]
Hi @glconti Thanks for reporting the issue, Will verify and get back to you asap.

**Comment by rangav** [comment]
There is also a Rest API to access secrets from Azure Vault - https://www.youtube.com/watch?v=j1xZoF_ewdo

Let me know if this alternative solution will work for you?

**Comment by rangav** [comment]
I just now tested it. Unable to install this library, I am getting the same error.

I will verify if there is a way to fix this.

**Comment by glconti** [comment]
> Let me know if this alternative solution will work for you?

I see that there would be a lot more to code (logic external to a single collection) to retrieve secrets, would like to avoid it, to be honest.

FYI: I also tried another approach, basically to invoke directly a cli command from a script, but I still the error on the node modele loading:

> Script Log: Error loading node package: child_process - Cannot find c:\Users\CHGICON\.vscode\extensions\rangav.vscode-thunder-client-2.15.3\dist\node_modules\child_process\index.js in plugin child_process

The script in this case would be:

```js
async function getSecret (input, param1) {

    const { exec } = await tc.loadModule('child_process');

    var result = "";

    exec(`az keyvault secret show --name ${param1} --vault-name ${input} --query value -o tsv`, (err, stdout, stderr) => {
        if (err) {
          // node couldn't execute the command
          console.log(`Key Vault Error: ${stdout}`);
          return;
        }
      
        // the *entire* stdout and stderr (buffered)
        console.log(`stdout: ${stdout}`);
        console.log(`stderr: ${stderr}`);

        console.log(`read secret ${param1} from ${url}`);

        result = stdout;
      });

     return result;
}

module.exports = [getSecret];
```

**Comment by rangav** [comment]
For CLI commands we already have api. Use - `var result = await tc.exec("command");`

**Comment by glconti** [comment]
@rangav It works! we can retrieve the secrets very easily and the custom filter looks super simple now. Many thanks for the help! I am sorry i haven't read this already in the docs, I would have saved you some time. But I hope this discussion will be helpful to others :)

```js
async function getSecret (input, param1) {

    var result = await tc.exec(`az keyvault secret show --name ${param1} --vault-name ${input} --query value -o tsv`);

     return result;
}

module.exports = [getSecret];
```

**Comment by rangav** [comment]
Happy to know it's working for you now. Thanks for confirmation :)

**Comment by rangav** [comment]
We have improved the `loading of Node modules` in the new update. Please update to `v2.20.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.20.0

Please test it and let me know your feedback
