### ISSUE TITLE
TC command line: Specified syntax for executing folders doesn't work

### ISSUE THREAD

**Issue by franky1964** [rangav/thunder-client-support#1406]
**Describe the bug**
We tried to use the following commands to run a folder as part of an existing collection:
tc --col "colName" --fol "folderId"
tc --col "colName" --fol "folderName"

In both cases the folder isn't found and the collections runs in total, this makes no sense.
(e.g.: ERROR: Folder not found - ab3b1c20-a2c2-440f-868a-c96fafe1b563)

The only way we got it to work was this "confusing" command:
tc --col "folderId"

Using  tc --col "folderName" we got "ERROR: Collection not found - folderName"

**To Reproduce**
Use described syntax

**Expected behavior**
Folder can be executed using the syntax: 
tc --col "colName" --fol "folderName" or "tc --col "colName" --fol "folderId"

**Platform:** 
 - OS: Windows
 - extension version: 1.9.1 (CLI)

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
@franky1964  The syntax to execute a folder is - `tc --fol "FolderName"`

Docs:
https://rangav.medium.com/d91eb5c71d8e

**Comment by franky1964** [comment]
Just tried out with:
![image](https://github.com/rangav/thunder-client-support/assets/58699432/ae87a559-f2ef-4e9c-a144-c581a42bc803)

**Comment by rangav** [comment]
Can you see the folder id when run this command - `tc list "colNameOrId"` to see all folders and Ids

**Comment by franky1964** [comment]
Ok, in this case it was an error from my side.
I will try to reproduce with annother example.

**Comment by rangav** [comment]
Sure, Let me know if you have any issues with this command.

**Comment by rangav** [comment]
I am closing this issue as its resolved
