### ISSUE TITLE
How to allow self-signed certs with axios

### ISSUE THREAD

**Issue by dviljoen** [rangav/thunder-client-support#1408]
**Question:**
Just upgraded to 2.16.0 and request failed with "self-signed certificate" error.  Switching to "got" http library works.  How do I get axios to accept self-signed certs?

**Are you using the free version/paid version/trial:**
Free version.

**Comment by dviljoen** [comment]
We are developing an API server and use self-signed certs for development purposes.

**Comment by dviljoen** [comment]
![image](https://github.com/rangav/thunder-client-support/assets/849415/8d1060c6-8979-45dd-b6f5-312d44293c71)

**Comment by dviljoen** [comment]
But with "got" client:
![image](https://github.com/rangav/thunder-client-support/assets/849415/257fa768-caef-45d6-bd0a-54ff40dd0f28)

**Comment by rangav** [comment]
can you confirm you are not using this right? - https://github.com/rangav/thunder-client-support#manual-ssl-certificates

**Comment by rangav** [comment]
You can test with axios yourself and see which config is working for you in the **Post Request scripting**.

sample script below:
```js
const axios = require('axios');
var result = await axios.get("https://dvred:443/redapi/v1/setup_status");
console.log(result.data);
```

useful links
https://www.codewithyou.com/blog/how-to-use-axios-to-handle-ssltls-certificate-verification-errors-in-nodejs

**Comment by dviljoen** [comment]
I don't understand the question about custom ssl vs. local host.  It's neither.  We generate a certificate for our api server.  But we are the CA.  It's self signed.  That's the only issue.  Just like you get the warning in a browser if you go to a self-signed cert on a web url.  That's all I'm asking.  How do I make axios do the thing that a browser can do when you click through the warning about a self-signed cert?

**Comment by rangav** [comment]
Ok got it.

please test this
https://github.com/rangav/thunder-client-support/issues/1408#issuecomment-1812711518

**Comment by rangav** [comment]
I have fixed the bug - Can you please install the `extension manually` and confirm its working with `axios`?

[vscode-thunder-client-2.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/13378632/vscode-thunder-client-2.16.1.vsix.zip)

**Comment by rangav** [comment]
Hi All, I made the small config changes to address this issue for axios.

Can you guys please update the extension to `v2.16.1`  and let me know if it's working or not?

**Comment by dviljoen** [comment]
Just tried with v2.16.1 and got the same error: "self-signed certificate" Sorry.

**Comment by rangav** [comment]
Thanks for testing.

I reverted default http library back to `got`. Please update to `2.16.2`
