### ISSUE TITLE
Cookies related bug

### ISSUE THREAD

**Issue by minixg** [rangav/thunder-client-support#1409]
**Describe the bug**
Cannot read properties of undefined (reading 'getCookies')

**To Reproduce**
I have neva met this bug before any Ideas on what might be causing this

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Are you using the free version/paid version/trial:**

**Comment by rangav** [comment]
Hi @minixg 

can you please share the code sample you used and fill all the issue template info required.

**Comment by rangav** [comment]
Closing this for not providing more info about the issue

**Comment by minixg** [comment]
The thing is that any request sent wether get or post or any other requests
I get that error and this started all of a sudden

**Comment by rangav** [comment]
Are you using scripting?
