### ISSUE TITLE
Support file download for server response

### ISSUE THREAD

**Issue by amin750** [rangav/thunder-client-support#141]
When using postman, I can download file (like excel, pdf and etc) from server response.
please add this feature
Thanks a lot

<img src="https://user-images.githubusercontent.com/19873094/117784862-3f5fab80-b259-11eb-9ea1-f46157d08532.jpg" width="400">

**Comment by cut2run** [comment]
It would be even better automatically download content based on the "Content-Type" of the response. There is no reason to preview binary in the response tab.

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Comment by shubhjack** [comment]
Hi, just wanted to check if this feature to send and download is being implemented or still in queue?

**Comment by shubhjack** [comment]
Hi, I'm generating the PPT file as response, but when I select save file its saving as generic file and I've to manually add the extension **.pptx** to open the file as ppt. It would be great if it recognizes the type of response while saving.

**Comment by rangav** [comment]
@shubhjack can you share screenshot of your response headers tab

could the response not sending proper content-type

**Comment by Toriekki** [comment]
This respose is a pdf file, but I don't see a option to save response as a file. What am I doing wrong?
![image](https://user-images.githubusercontent.com/26093193/221848264-261c0d2d-4cab-4935-88b3-003a3ea49079.png)

**Comment by rangav** [comment]
Hi @Toriekki can you share the `response Headers tab` screenshot?

**Comment by ziljin** [comment]
Hello
I am trying to receive a large zip file (gigs) and response stucks in pending state indefinitely. I can tell from Task manager performance there is no network activity after some point, so the file seem to be downloaded.
