### ISSUE TITLE
Run Collection tab in UI does not maintain state

### ISSUE THREAD

**Issue by aj-scram** [rangav/thunder-client-support#1410]
**Description**
If you start a Collection Run and click on a new collection or do anything that may change the tab, then when you come back to it, it will be in a strange state where it is still running, but no longer correctly recognizes that it _is_ still running.
 
![image](https://github.com/rangav/thunder-client-support/assets/150948796/c5e47a99-6325-43c9-85b1-b48c221a4221)

**To Reproduce**
1. Start collection run with multiple iterations.
2. Select new collection.
3. Select previous collection that you started run on.

**Expected behavior**
Would expect the Run Collection tab to maintain state since it's still in middle of previous run.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.84.2 (user setup)
 - extension version: 2.16.0

**Are you using the free version/paid version/trial:**
Paid

**Comment by rangav** [comment]
Hi @aj-scram thanks for the feedback, Will review it.

can you please confirm your subscription using below link for our internal support records
https://www.thunderclient.com/contact

**Comment by aj-scram** [comment]
> can you please confirm your subscription using below link for our internal support records
> https://www.thunderclient.com/contact

![image](https://github.com/rangav/thunder-client-support/assets/150948796/78cdd283-2f2d-4717-a9a9-0fc0747e7aa0)

Included link to this issue in message sent

**Comment by rangav** [comment]
Will enable for opening Multiple Run Collection Views in the next update.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.17.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.0

Please test and let me know your feedback.
