### ISSUE TITLE
Consolidate iterations in reports to one table structure.

### ISSUE THREAD

**Issue by aj-scram** [rangav/thunder-client-support#1412]
**Please describe feature/problem details and the solution you'd like.**

When doing performance profiling, or similar tasks, it's necessary to run the same set of requests multiple times, but the structure of the reports makes analyzing the results more difficult than they should be.

Please include iteration as its own column in generated reports, instead of a header, so entire result set can easily be consumed as table and analyzed via tools like Excel.

Instead of:

| Iteration | #n       |      |            |         |            |          |            |
|-----------|--------|----|--------|-------|--------|-------|--------|
| Method  | Name | Url | Status | Time | Passed | Total | Result |

What I actually need is:

| Method  | Name | Url | Status | Time | Passed | Total | Result | Iteration |
|-----------|--------|----|--------|-------|--------|-------|--------|-----------|

**Describe alternatives you've considered**

I'm manually transforming the data in excel or using excel formula. I'm considering forgoing the report feature and parsing the output myself to a CSV

**Are you using the free version/paid version/trial:**
Paid

**Comment by rangav** [comment]
@aj-scram Will update the report in the next update.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.17.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.0

Please test and let me know your feedback.
