### ISSUE TITLE
Error: getaddrinfo ENOTFOND [::1] 

### ISSUE THREAD

**Issue by degoya** [rangav/thunder-client-support#1415]
**Describe the bug**
When trying to connect to a IPV6 [::1} i get the following error

`getaddrinfo ENOTFOND [::1]
`

**To Reproduce**
connect to a api on local host with [::1]

**Expected behavior**
Should get the API, like it was before, this error is new. 

**Platform:** 
 - OS: Windows/Mac
 - vscode version: v1.84.2
 - extension version: v2.16.0

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
@degoya Please the solutions mentioned here https://github.com/rangav/thunder-client-support/blob/master/docs/common-issues.md

**Comment by degoya** [comment]
> @degoya
> 
> Please the solutions mentioned here https://github.com/rangav/thunder-client-support/blob/master/docs/common-issues.md

this solved the issue, thank you for the fast response and the great work with Thunderclient.
