### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by cawoodm** [rangav/thunder-client-support#1416]
**Describe the bug**
Since the latest update (axios?) it is not possible to call HTTPS URLs which are signed and trusted by the host (windows) but via private CA.

**To Reproduce**
GET https://mydomain.com

**Expected behavior**
SSL should respect windows trusted certificates OR there should be guidance as to how to configure cacerts.pem OR disable SSL check

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.84.2
 - extension version: 2.16.0

**Are you using the free version/paid version/trial:**
Free

**Comment by fdc-brian** [comment]
Got same issue

**Comment by rangav** [comment]
Hi All, I made the small config changes to address this issue for axios.

Can you guys please update the extension to `v2.16.1`  and let me know if it's working or not?

**Comment by rangav** [comment]
I have changed back the default http library from `axios` to `got`. Please update to `v2.16.2`
