### ISSUE TITLE
Why can't the 'Time' of the response in the GUI be treated as a reliable latency metric?

### ISSUE THREAD

**Issue by zihanfangms** [rangav/thunder-client-support#1418]
**Question:**

**Are you using the free version/paid version/trial:** I'm using the free version
Hi team,
I'm using the free version Thunder Client VSCode plugin to test my APIs, at first, it works well. But recently when I was testing one of my API, the 'Time' of response is always larger than 10 seconds, sometimes it can be 30+ seconds.
![image](https://github.com/rangav/thunder-client-support/assets/132629980/7aeffd4e-77d5-4acf-8f38-4da8adb21725)
I wrote a Python script to get the P99, P95, and P50 latency of this API, it turns out none of the 100 requests has a latency larger than 2 seconds. It shouldn't be caused by the cache mechanism, because I sent the same request multiple times using Thunder Client, the latency is always larger than 10 seconds. And in my python script, the latency is always 1 ~ 1.5 seconds.
I know we can't use the 'Time' to measure the latency of the APIs, but I still want to know the potential reason of the significant difference of the latency from Thunder Client and Python script, thanks!

And this is part of the Python script I used for measuring the latency, thanks!
```
latencies = []

# Run the GET request 100 times
for _ in range(100):
    # Start time
    start_time = time.time()

    # Send GET request
    response = requests.get(url, headers=headers)

    # End time
    end_time = time.time()

    # Calculate latency
    latency = end_time - start_time

    # Add latency to list
    latencies.append(latency)
    print(f'Latency: {latency} seconds')

# Convert list to numpy array
latencies = np.array(latencies)

# Calculate percentiles and average
p99 = np.percentile(latencies, 99)
p95 = np.percentile(latencies, 95)
p50 = np.percentile(latencies, 50)
average = np.mean(latencies)

# Print results
print(f'P99 Latency: {p99} seconds')
print(f'P95 Latency: {p95} seconds')
print(f'P50 Latency: {p50} seconds')
print(f'Average Latency: {average} seconds')
```

**Comment by rangav** [comment]
Hi @zihanfangms 

Please try below solution 
https://github.com/rangav/thunder-client-support/discussions/936#discussioncomment-7625161

**Comment by rangav** [comment]
I am closing this, if you still have issues let me know.

**Comment by zihanfangms** [comment]
[like]  Zihan Fang reacted to your message:
________________________________
