### ISSUE TITLE
Repeat a request until a specific variable is set to a specific value

### ISSUE THREAD

**Issue by tringler** [rangav/thunder-client-support#1419]
**Question:**
How could I repeat a request until I see i.e. `json.message.job = "suceeded"` and set the test to failed after i.e. 20 retries?

**Are you using the free version/paid version/trial:**
paid

**Comment by rangav** [comment]
Hi @tringler 

Please the details below on how to retry the request for 20 retries, modify the code as required
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#retry-request

Let me know if you have any questions

**Comment by tringler** [comment]
@rangav Thanks for pointing me in the right direction :+1:

**Comment by rangav** [comment]
You are welcome :)
