### ISSUE TITLE
Issue with Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Hristian233** [rangav/thunder-client-support#1420]
**Question:**
Whenever I try to send a request using Thunder Client I get the error "Self signed certificate in certificate chain". After doing research on the internet I still wasn't able to resolve it. I have the following VS Code settings:
    "git.confirmSync": false,
    "http.proxyStrictSSL": false

The version is 2.16.0

![image](https://github.com/rangav/thunder-client-support/assets/22296624/12b1c33e-2897-44d9-8370-ddb916bcda24)

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
@Hristian233 thanks for reporting the issue.

Can you please update the extension to `v2.16.1` and let me know if it's working or not?

**Comment by rangav** [comment]
I have changed back the default http library from `axios` to `got`. Please update to `v2.16.2`

**Comment by Hristian233** [comment]
Still the same ..

**Comment by rangav** [comment]
Can you share screenshot of setting as below
<img width="671" alt="Screenshot 2023-11-22 at 15 44 53" src="https://github.com/rangav/thunder-client-support/assets/8637550/9344e096-d61b-4de0-a3fc-52ccbc43fdce">

**Comment by Hristian233** [comment]
My Http Library setting is the same as yours. However I wrote "http.proxySupport": "on" in the settings.json and now it works.
