### ISSUE TITLE
Item counter on array responses

### ISSUE THREAD

**Issue by bombillazo** [rangav/thunder-client-support#1422]
**Please describe feature/problem details and the solution you'd like.**

As a helpful tool, if the API response returns an array, it would be nice to have a counter to know how many items were returned, probably next to the Time it took to run.:

![image](https://github.com/rangav/thunder-client-support/assets/44002321/fcb55b4c-695f-4bd0-9df1-d74e5e718510)

**Describe alternatives you've considered**

Manually counting items.

**Are you using the free version/paid version/trial:**

Paid

**Comment by rangav** [comment]
Hi @bombillazo Thanks for the feedback, it is a limited use-case to display in the UI.

Alternative solution: You can use the Ctrf+F and search property name will give you a count.
