### ISSUE TITLE
request body's text/json is misbehaving

### ISSUE THREAD

**Issue by GitJason33** [rangav/thunder-client-support#1423]
**Describe the bug**
When i try to write json, xml or graphQL in their respective text fields, a space gets added with each character i add, making the cursor go far from where i am writing

**To Reproduce**
simply try to add request body normally while writing (no copy pasting) with json, xml or graphQL

**Expected behavior**
the cursor should stay where i am writing, not run away from me :)

**Platform:** 
 - OS: Windows 10
 - vscode version: latest
 - extension version: latest

**Are you using the free version/paid version/trial:**
free

**Comment by rangav** [comment]
Hi @GitJason33 Are you using a custom font?

See solution here https://github.com/rangav/thunder-client-support/issues/1326#issuecomment-1714123998

**Comment by GitJason33** [comment]
> Hi @GitJason33 Are you using a custom font?
> 
> See solution here [#1326 (comment)](https://github.com/rangav/thunder-client-support/issues/1326#issuecomment-1714123998)

yes, using Lynstone. i tried to remove it and the thunder client cursor didnt run away (which means it works as expected). but still, then the bug happens from custom fonts as you mentioned. thanks for telling me. i removed the font.
