### ISSUE TITLE
How to ignore SSL Validation please?

### ISSUE THREAD

**Issue by i286** [rangav/thunder-client-support#1426]
**Question:**
How to ignore SSL Validation please?
I am trying to access some self signed certificate applications and I am not seeing any options to disable SSL validation so I can actually make an API call.
The error is: "unable to verify the first certificate"

**Are you using the free version/paid version/trial:**
I am using the paid version from my company

**Comment by i286** [comment]
I have no idea what happened but suddenly I am able to make API calls to my self signed cert application.
Somehow opening up the issue made it be fixed :)

However, the original question remains, I have no idea what changed for it to work now.

**Comment by rangav** [comment]
Please see this comment https://github.com/rangav/thunder-client-support/issues/1420#issuecomment-1822941875
