### ISSUE TITLE
2 cookies with same name shown in the Cookie Manager

### ISSUE THREAD

**Issue by duckradu** [rangav/thunder-client-support#1427]
**Describe the bug**

After setting an initial `refresh_token` cookie, when rotating the token & setting the new cookie value 2 cookies with the same name are shown in the Cookie Manager.

**To Reproduce**

1. /auth/login -> return a Set-Cookie with an initial `refresh_token`
2. /auth/refresh-tone -> return a Set-Cookie with new value for `refresh_token`
3. Open the Cookie Manager

![image](https://github.com/rangav/thunder-client-support/assets/133859854/69fc016d-460c-4cae-8aa4-ea8909ba0915)

**Expected behavior**

I assume the expected behaviour is that there's only one `refresh_token` with the latest value shown, unless I missed something or I need extra config but I couldn't find any info regarding this on the internet.

**Platform:** 

 - OS: Fedora Linux 38
 - vscode version: VSCodium 1.82.2
 - extension version: v2.16.2

**Are you using the free version/paid version/trial:**

The free version

Update:
- Just noticed that clearing the cookie will add a third cookie with the same name but empty value. However, when calling and endpoint that requires the cookie, the third cookie with the empty value is ignored, instead the last cookie with a value is being sent.
- I'm using `fastify` if that is of any help

**Comment by rangav** [comment]
Hi @duckradu 

Thanks for reporting the bug, Will look into it.

**Comment by duckradu** [comment]
@rangav I have figured out my issue:

It's a bit embarrassing to admit but I forgot to set the cookie `path` property and relied on `@fastify/cookie`. While setting the cookie, there was no default `path` in my config, but when clearing it the library would automatically add `path: '/'` :facepalm: 

I'll close this issue since it's not related to ThunderClient, sorry for wasting your time.
