### ISSUE TITLE
Connection was refused by the server

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#1428]
**Describe the bug**
I ran into this problem a lot when I tried to demo Thunder Client to friends, but now I can reproduce it on my machine.

I copied a curl from the browser to thunder client and I get the error "Connection was refused by the server"

I tried the same curl with postman, and it worked.

I tried changing http clients between got and axios - didn't help.
(Also there is a difference between the label that says that axios is the default, while actually got is the default)
![image](https://github.com/rangav/thunder-client-support/assets/16635859/4412afb5-3a1b-4ad5-b43a-44cd7cb457f5)

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: Windows 
 - vscode version: 1.84.1
 - extension version: 2.16.2
**Are you using the free version/paid version/trial:**
Free

Love the product for a while now :)

**Comment by rangav** [comment]
Hi @noam-honig 

Please try the solutions here https://github.com/rangav/thunder-client-support/blob/master/docs/common-issues.md

**Comment by noam-honig** [comment]
Hi @rangav 

Tried all of these, changed axios & got. Changed the url from localhost to 127.0.0.1 to 0.0.0.0 

Only changing the ip to [::1] worked - but that's hardly a good answer - I'm showing thunder client as a seamless http client to use when you develop within vs code - changing the ip after a curl paste kinda losses its appeal

**Comment by noam-honig** [comment]
I was accessing angular 13 dev server on 4200 in case you want to know what I was trying to do

**Comment by noam-honig** [comment]
I've tested with axios-test and it worked without any change.

One thing I noticed was that even though my uril says 'localhost' the error that comes back is from 127.0.0.1
![image](https://github.com/rangav/thunder-client-support/assets/16635859/224eaba2-a43d-4a40-b74e-353f65e4eaa7)

When I do the same with your axios test - localhost works ,but 127.0.0.1 give the connection refused

**Comment by rangav** [comment]
did it work for you before?

**Comment by noam-honig** [comment]
I think it did :) not sure with the angular dev server - probably with vite and react/vue etc...

Why is it changing from localhost to 127.0.0.1? is that something you do in your code?

**Comment by rangav** [comment]
The issue is with the library - https://github.com/axios/axios/issues/5785

**Comment by rangav** [comment]
Disable preview features setting - Restart vscode and Please test it again. 

Let me know if you notice any difference

<img width="772" alt="Screenshot 2023-11-29 at 16 06 41" src="https://github.com/rangav/thunder-client-support/assets/8637550/3726b6b8-b6b5-4372-b9ca-12fb61b61888">

**Comment by rangav** [comment]
did it work?

**Comment by noam-honig** [comment]
No :)

**Comment by rangav** [comment]
Thanks for the confirmation. The alternative solution is to use - [::1] for now, until we found a solution.

**Comment by noam-honig** [comment]
I understand, I'll find a solution, don't worry about me - I was
just trying to report to you after I finally reproduced it.

I still wonder what replaces the localhost with 127.0.0.1 in the response
error

**Comment by noam-honig** [comment]
Hi Rangav/Thunder-Client-Support,

I'm circling back to this - it seems that for me the issue was
introduced when I upgraded from node16 to 18 or 20.

::1 works - but localhost or 127.0.0.1 do not

I wish it did, as this makes thunder client less usefully for me - both for
demos, and for development where I use curl a lot.


Hope you'll figure this out

**Comment by rangav** [comment]
Thanks @noam-honig for the feedback.

I think i found a way to fix this issue. Will update here in next couple of days.

**Comment by rangav** [comment]
@noam-honig I have implemented a fix in `v2.17.2`, can you please test it and let me know if it's working or not?

How to use
1. From Vs Code Settings Enable setting `Preview Features` ( see screenshot below)
2. Change `Http Libary` to Axios in Vs Code setting
3. Now test the localhost URL and let me know your feedback.

<img width="703" alt="Screenshot 2024-01-31 at 16 25 07" src="https://github.com/rangav/thunder-client-support/assets/8637550/3535f408-3361-4de8-bb4f-8097767881e5">

**Comment by rangav** [comment]
@noam-honig 

I have updated the code again to fix localhost issues in update `v2.17.5`

Can you test again with `axios` and `got` and let me know your feedback.

You can use the **DNS Test** command to verify the IP used
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.5

Please test and let me know your feedback.

**Comment by noam-honig** [comment]
Hi @rangav, I'm traveling, and will only get to it on thursday

**Comment by noam-honig** [comment]
Hi @rangav , sorry for the delay.

I'm testing with v2.17.8.
created a vite project using:
```
npm create -y vite@latest remult-react-todo -- --template react-ts
cd remult-react-todo
npm i
npm run dev
```


Vite (5173) works well with [::1], but doesn't work with localhost or 127.0.0.1
DNS test works great:
```
---------------- Running Request: ----------------
DNS Results: localhost
DNS Address 127.0.0.1 IPv4
DNS Address ::1 IPv6
```

Windows 10
Node v18.18.2
(I think that in note 16 it worked ok)

Tried it with both axios and got

I hope this helps

**Comment by rangav** [comment]
when you `Preview features` setting did it work with localhost?

**Comment by noam-honig** [comment]
Nope
