### ISSUE TITLE
Database connection MongoDB with ThunderClient

### ISSUE THREAD

**Issue by Artem0ne** [rangav/thunder-client-support#1429]
**Question:** Is it possible to build a Database Connection in ThunderClient? 
In our case we use **MongoDB**. In the area "**Scripting**" using Javascript, something like this:

_const uri = "mongodb+srv://<username>:<password>@<your-cluster-url>/test?retryWrites=true&w=majority";
const client = new MongoClient(uri);_
 
Probably also using **Node.js** module. Is it possible to integrate **Node.js** in TC?
We need some ideas, thank you!

**Are you using the free version/paid version/trial:** We use paid version (Deutsche Bahn AG)

**Comment by rangav** [comment]
Hi @Artem0ne 

We never tried it, you can try using the scripting and test it.

**Comment by rangav** [comment]
We have improved the `loading of Node modules` in the new update. Please update to `v2.20.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.20.0

Please test it and let me know your feedback

**Comment by Artem0ne** [comment]
Yes, it works fine for **mongoDB** Database

**Comment by rangav** [comment]
Thanks for the confirmation
