### ISSUE TITLE
press Enter to run request

### ISSUE THREAD

**Issue by rajinder-yadav** [rangav/thunder-client-support#143]
Current one needs to click on the "Send" button to run the request, would be nice to be able to also press "Enter" after typing to run the request.

![snap-48](https://user-images.githubusercontent.com/439226/117948252-f4887700-b2de-11eb-892a-fde301d93950.png)

**Comment by rangav** [comment]
hi @rajinder-yadav shortcut is Cmd/Ctrl+Enter, see keyboard shortcuts section

**Comment by rangav** [comment]
`Enter` key to run request is now supported in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0

**Comment by rajinder-yadav** [comment]
Thank you for this update! One less key-stroke to press 😀
