### ISSUE TITLE
Error: Could not register service worker

### ISSUE THREAD

**Issue by philwu** [rangav/thunder-client-support#1430]
I have been using Thunder Client for a while and I got this error today. What should I do?

![1701316466711](https://github.com/rangav/thunder-client-support/assets/5704024/a2f86ea8-d85e-479a-b2b5-52d34a4d41c1)

Thunder Client v2.16.2 
free version

VSCode: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by rangav** [comment]
Hi @philwu 

1. please restart vscode and test it 
2. Or please reboot your system and try again
