### ISSUE TITLE
Duplicate IDs in JSON after duplicating requests

### ISSUE THREAD

**Issue by azplanlos** [rangav/thunder-client-support#1435]
**Describe the bug**
When duplicating requests from our test collection we sometimes end up with two requests having the same id in the test collection's json structure even after moving them to another folder. These requests can't be edited as saving them updates the first identical entry of this request and when running the request it seems unpredictable which version of this request is run. These requests can be deleted though. Sometimes the request's title isn't shown but the URL of the request.

**To Reproduce**
Duplicate a request in VSCode plugin.

**Expected behavior**
Should create an independent duplicate of the request.

**Platform:** 
 - OS: macOS 14.1.2
 - vscode version: 1.84.2
 - extension version: 2.16.0

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Thanks @azplanlos for reporting the bug.

Are you duplicating request in collection tab or Activity tab?

**Comment by azplanlos** [comment]
That is in collection tab.

**Comment by rangav** [comment]
I just now tested the duplicate request using the right click menu. It is working correctly generated new ID.

Can you please create a new collection and try to re-product it again?

**Comment by azplanlos** [comment]
This issue just happens from time to time on bigger collections with more than 100 requests.

**Comment by rangav** [comment]
ok will test with similar size collection and get back to you

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace, please update to `v2.17.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.0

Please test and let me know your feedback.
