### ISSUE TITLE
Pre Run allows the modification to ENV

### ISSUE THREAD

**Issue by wjxiz1992** [rangav/thunder-client-support#1436]
**Please describe feature/problem details and the solution you'd like.**
I have a Pre run request whose return value is a value in my ENV section.
Everytime I run this request, I have to manually copy it to my env.  Then run my main request.

**Describe alternatives you've considered**
/

**Are you using the free version/paid version/trial:**
free

**Comment by rangav** [comment]
Hi @wjxiz1992 

you can use Tests tab to set response value to Env

https://github.com/rangav/thunder-client-support#setenv

**Comment by rangav** [comment]
I am closing this issue, feel free to continue the discussion.
