### ISSUE TITLE
Response color highlighting disappears after closing and reopening the editor tab

### ISSUE THREAD

**Issue by rasitayaz** [rangav/thunder-client-support#1438]
**Describe the bug**
JSON responses in the response tab sometimes don't use color highlighting. And collapsing/expanding JSON objects/arrays doesn't work:

https://github.com/rangav/thunder-client-support/assets/45076094/a4ea338f-bd2d-404a-81a6-e5e0881364f7

**To Reproduce**
- Open a new VS Code window
- Select a request from left panel
- Send it couple of times
- Close the editor tab
- Select the same request again and try sending it

It stays broken until closing and reopening the VS Code window.

**Expected behavior**
Color highlighting to work properly

**Platform:** 
 - OS: macOS Sonoma 14.2
 - vscode version: 1.85.1
 - extension version: 2.16.3

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
Thanks @rasitayaz for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace, please update to `v2.17.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.0

Please test and let me know your feedback.

**Comment by rasitayaz** [comment]
works great, thanks

**Comment by rangav** [comment]
Thanks for confirmation
