### ISSUE TITLE
OAUTH2 Access token breaks on all versions higher that 2.14.1

### ISSUE THREAD

**Issue by y272nly** [rangav/thunder-client-support#1439]
**Describe the bug**
A simple GET request using OAUTH2 fails perhaps because the token is too big. In my case its an AZURE token that has 1301 characters.

When a GET request is SENT on versions higher that 2.14.1 it fails and then the field becomes read-only, cannot be changed and I need to close and re-open the request to try again, but same issue.
What happened to this and can it be fixed in latest release ?

Token Prefix : Bearer
Access Token : DyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSIsImtpZCI6IlQxU3QtZExUdnlXUmd4Ql82NzZ1OGtyWFMtSSJ9.eyJhdWQiOiIwZjZmNWJiMy0yNWU3LTQ0OWUtODI2Ni1mOGZkNDU3Yzg2ZWMiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hN2YzNTY4OC05YzAwLTRkNWUtYmE0MS0yOWYxNDYzNzdhYjAvIiwiaWF0IjoxNzAzMDgyNzQwLCJuYmYiOjE3MDMwODI3NDAsImV4cCI6MTcwMzA4NjY0MCwiYWlvIjoiRTJWZ1lDLaGY1aHRoUDZFeVlKSGZSZSs5alYvNUFBPT0iLCJhcHBpZCI6IjgzNzEyNDg4LThjM2YtNDk4OS04YjljLWNiYTYxYzFlNzE0MyIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2E3ZjM1Njg4LTljMDAtNGQ1ZS1iYTQxLTI5ZjE0NjM3N2FiMC8iLCJvaWQiOiJlZmMyNGI1Ny0xYjk1LTRjNWYtODJlZi0yOGYwY2ViYmRlNTUiLCJyaCI6IjAuQVFzQWlGYnpwd0NjWGsyNlFTbnhSamQ2c0xOYmJ3X25KWjVFZ21iNF9VVjhadXdMQUFBLiIsInJvbGVzIjpbIlJPQlQiLCJPUiIsIlRyaW5pdHkiLCJORzkiXSwic3ViIjoiZWZjMjRiNTctMWI5NS00YzVmLTgyZWYtMjhmMGNlYmJkZTU1IiwidGlkIjoiYTdmMzU2ODgtOWMwMC00ZDVlLWJhNDEtMjlmMTQ2Mzc3YWIwIiwidXRpIjoiRlNOV0YtcTl6VXl1R2JvRGM0RnRBQSIsInZlciI6IjEuMCJ9.o7clKwM9vlffOlVQkf-GGtUj4dVmSJkgB1n66OrsYmDLpPW5yOIkRtIaz8nfIBgsInBqb7PPqH_pgY0HcwgJtkc-ndj_TX3Y_iyHCLPDek5LG6H7AdhnkwVH8nMVsqD2p9TJ1XS84pc0N7TpM-dhN_ODB0sWnPowqxsUshBp-TXUBzok0my4LOz-UIsyzABwRxnW0HwGAgdD-4D7DoyA7raP1frsYkE8H_fhAHjBs9J8SANMwqfZqsmpJZ2GlD0UV35qg3cz6gP7deU-deGiO6Zioy9fk0c3XS2NSDjTW9CHoTiwAn80gmfhkZKT88eGBfZIo8ELngFD54hC81FJ9w

**To Reproduce**

Use a large token when using OAUTH2 GET calls on versions of thunder-client newer that 2.14.1

**Expected behavior**

On version 2.14.1 and lower, the token size is acceptable and the problem does not occur.

**Platform:** 
 - OS: Windows
 - vscode version:  1.85.1
 - extension version: 2.16.3

**Comment by rangav** [comment]
@y272nly are you using free or paid version?

**Comment by y272nly** [comment]
Free version

**Comment by rangav** [comment]
Thanks @rangav reporting the bug, will fix it asap.

Alternatively you can use `Bearer` tab and paste token value

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace, please update to `v2.17.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.0

Please test and let me know your feedback.

**Comment by y272nly** [comment]
Great news.

On testing, it now accepts a long string in the clip board when I CTRL+v
(paste).
But strangely a right mouse click and select paste (on windows) no longer
works.
Could be a local user pc issue, or maybe not. The mouse paste option
doesn't work in any field even with small single characters in the clipboard

**Comment by y272nly** [comment]
Wow... Thats a match... Thanks for your help and prompt responses.

Happy New Year

Phil

**Comment by rangav** [comment]
Welcome - Happy New Year to you too 🤝
