### ISSUE TITLE
Too many fields

### ISSUE THREAD

**Issue by tanluc1e** [rangav/thunder-client-support#1443]
**Question:**
![image](https://github.com/rangav/thunder-client-support/assets/93022030/b98aae60-ca48-4e5f-ae47-dfb5b45f35bb)
Why did I have err?
**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Please Ask stackoverflow

**Comment by tanluc1e** [comment]
> Please Ask stackoverflow

its fixed, because using multer
