### ISSUE TITLE
Body-Form post multiple

### ISSUE THREAD

**Issue by tanlucvn** [rangav/thunder-client-support#1444]
**Question:**
Here is Form
![image](https://github.com/rangav/thunder-client-support/assets/93022030/b8eb194d-c3ce-4234-95db-1090d7ba8bf3)

How can I post with postData..., in JSON its easy but cant upload attach. So Im using Form (above img) but idk how to post like this

![image](https://github.com/rangav/thunder-client-support/assets/93022030/68df14d9-3729-445b-8349-160280ea36c2)

{
  "postData": {
    "boardId": "6589448d790b5a67eeb94b84",
    "title": "threadtitle",
    "body": "thread"
  },
  "attach": [
    {
      "item": "item1",
      "thumb": ""
    },
    {
      "item": "item2",
      "thumb": ""
    }
  ]
}

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Hi @tanlucvn 

try using readFile filter - https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#readFile
