### ISSUE TITLE
error: params.addCertificatesV1 is not a function

### ISSUE THREAD

**Issue by JuanPa-Github** [rangav/thunder-client-support#1452]
When I try to instantiate the http endpoint the error for thunder client is:  params.addCertificatesV1 is not a function.
![image](https://github.com/rangav/thunder-client-support/assets/66334427/39deb320-fec8-429e-8eb8-ac2a8cb35fde)

**Comment by rangav** [comment]
closing this issue, as full details of the issue template not provided
