### ISSUE TITLE
Support showing/opening PDF as response

### ISSUE THREAD

**Issue by Pimpnase** [rangav/thunder-client-support#1457]
**Please describe feature/problem details and the solution you'd like.**
I have an API which responds with a PDF and Thunder Clients show the response as "The response is binary file, display not supported". Of course I can save the file to my file-system and open it, but other api-clients show the PDF natively within their response-window.

**Describe alternatives you've considered**
Show a button "Open in default-app"

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
@Pimpnase 

Please install [PDF viewer](https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf) extension and Click `Open in Code` link button

**Comment by Pimpnase** [comment]
Not a real fan of extensions for an extension and it's another click, but it works and is way easier, than saving the file and opening it 👍
