### ISSUE TITLE
Support response-header content-disposition/filename for saving binary-files

### ISSUE THREAD

**Issue by Pimpnase** [rangav/thunder-client-support#1458]
**Please describe feature/problem details and the solution you'd like.**
Our API responds with the header "content-disposition" which includes a filename. When saving this file thunder client suggests a random thunder-client-name instead of the one within the response-header. It would be ideal to adopt the content-disposition filename, if it is provided.

Example:
`content-disposition: attachment; filename="ABC-20240117-1.pdf"`

**Describe alternatives you've considered**
_none_

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Hi @Pimpnase 

Can you please confirm the subscription by using the below form?
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.17.2`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.2

Please test and let me know your feedback.

**Comment by Pimpnase** [comment]
Tested it and it works like a charm 👍 Very helpful.

**Comment by rangav** [comment]
@Pimpnase Thanks for confirmation :)
