### ISSUE TITLE
undo and redo doesn't work on certain fields.

### ISSUE THREAD

**Issue by mistercorea** [rangav/thunder-client-support#146]
This is something of the fields I found
 - Address bar
 - Query Parameters
 - tests values.

**Comment by rangav** [comment]
Hi @mistercorea thanks for reporting, Will look into it.

**Comment by caperso** [comment]
Is that a bug? 
I just thought that undo feature is not supported 😂

My url input can't undo 
Macos 11.2 with vscode1.56.2 （current latest）

**Comment by leonardoad** [comment]
Same here!
I can't undo or redo in any of the fields...
Extention v1.9.1
VSCode v1.60.0

**Comment by jleemur** [comment]
Was going to say me too, but looks like you're on it @rangav!

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
