### ISSUE TITLE
Skipping Tests in Testcollection for CI

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1461]
**Question:**
Hi Ranga,

we implemented a toggle to some features in our service, to turn them on or off. My question is, is it possible to skip some tests in a testcollection? 

i tried it with the command, but it doesnt work. 

> tc.runRequest(null);

**Are you using the free version/paid version/trial:**
paid version

**Comment by rangav** [comment]
Hi @erwinmoretz 

You want to skip requests right?

1. From Run Collection View
<img width="1193" alt="Screenshot 2024-01-19 at 09 36 59" src="https://github.com/rangav/thunder-client-support/assets/8637550/35397ece-4d6f-4c6b-9e9c-487bbb75349b">

https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

<br>
2. From JS Code

```js
tc.skipRequest("requestId");
```
https://github.com/rangav/thunder-client-support/releases/tag/v2.16.0

**Comment by erwinmoretz** [comment]
yes want to skip request. 

in my case its the first request, which tests if the toggle is active or inactive. in case of inactive i want to skip, all following testcases in the collection. so there is no requestId which i can write. 

Is it possible to stop the runner?

**Comment by rangav** [comment]
Enable the Stop on fail setting and save it.
<img width="348" alt="Screenshot 2024-01-19 at 10 08 39" src="https://github.com/rangav/thunder-client-support/assets/8637550/d9642477-d0c7-40d2-bb97-dc5e7ed8273f">

When a request test cases fail, it will stop the collection execution and skip remaining requests.

You can also trigger a test fail from the code and stop the runner.

```js
tc.test("custom fail test", false);
```

**Comment by erwinmoretz** [comment]
In our case, the test does not fail because I have built a case distinction into the script. Depending on how the parameter is set, other tests are executed. The tests should only stop if the script recognises that the feature switch is switched off.

**Comment by erwinmoretz** [comment]
when the requested status delivers 404 it needs to skip the following testcases in the collection. when the status 200, the runner has to continue.

**Comment by rangav** [comment]
Then you can check the  status code in post req script and then add a custom failed test to stop the runner

**Comment by rangav** [comment]
Closing this issue, feel free to continue discussion if you have more questions

**Comment by m3dbedb** [comment]
Where to ged request id?
 `Enable the Stop on fail setting and save it.`
How to save it?
