### ISSUE TITLE
Unable to copy text from Chart visualization

### ISSUE THREAD

**Issue by seanwcom** [rangav/thunder-client-support#1463]
**Describe the bug**
Using the new beta charting, I am unable to copy text from the rendered html. I can select it but cannot copy with hotkey (cmd-c). Likewise there is no context menu (with right click) to try and copy.

**To Reproduce**
Render any html using the new beta charting, select text from the chart view, try to copy and paste elsewhere.

**Expected behavior**
Expecting text to copy to clipboard.

**Platform:** 
 - OS: MacOS
 - vscode version: 1.85.1 (universal)
 - extension version: v2.17.0

**Are you using the free version/paid version/trial:**
Paid version

**Comment by rangav** [comment]
Thanks @seanwcom for reporting the issue, will look into it.

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace. Please update to `v2.19.3`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.3

Please test it and let me know your feedback
