### ISSUE TITLE
Cookie header is cached and same is used for subsequent requests

### ISSUE THREAD

**Issue by g54799** [rangav/thunder-client-support#1466]
**Describe the bug**

When a "Cookie" header is specified for a request, it is cached the first time is sent and then the same is sent with subsequent requests even if it is updated.

**To Reproduce**

1. Create a request with a "Cookie" header. 
2. Send the request.
3. Update the value of the cookie in the header.
4. Send the request again.
5. Check the value of the cookie in the remote service, you will see it is not the updated value but the previous one.

**Expected behavior**

When a cookie is set to a value in the Cookie header it should be used.

**Platform:** 
 - OS: Windows
 - vscode version: 1.84.2
 - extension version: 2.17.1

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
Hi @g54799 

I tested now its working for me.

1. You can use the test url - https://www.thunderclient.com/t/params
2. change cookie value from blue to red

<img width="1327" alt="Screenshot 2024-01-23 at 16 08 11" src="https://github.com/rangav/thunder-client-support/assets/8637550/fda6512b-5d41-4651-aaba-680224e4531c">

**Comment by rangav** [comment]
Closing this issue, feel free to continue discussion
