### ISSUE TITLE
YAML editor support

### ISSUE THREAD

**Issue by Falci** [rangav/thunder-client-support#1467]
**Please describe feature/problem details and the solution you'd like.**
When humans need to type a JSON, a YAML is easier for the job. 
It would be great if the body editor could support YAML and sent it as JSON. Meaning we type YAML (which is cleaner, don't have so much quotes, and Thunder Client send it as JSON (as expected by the server)

**Describe alternatives you've considered**
Currently, we can just type JSON, but it's more verbose than YAML.

**Are you using the free version/paid version/trial:**
Free

**Comment by rangav** [comment]
Are you using the free version/paid version/trial?

**Comment by rangav** [comment]
Currently not planning to implement this
