### ISSUE TITLE
Sending encoded string in query params causes error

### ISSUE THREAD

**Issue by jasonclane** [rangav/thunder-client-support#147]
**Describe the bug**
when using a REST API using GET method and encoding a query parameter, the request does not properly send the data to the remote end (seems to be mangling the query string). I was using this with the Salesforce REST API (query API) trying to execute a query against Salesforce

**To Reproduce**
Use any REST API where you send a query and try using encoded values in the query parameters. For example, %20 or %2c seem to cause problems with REST calls. An example of the query I was trying to pass is: SELECT%20id%2c%20name%20FROM%20Account

Remote end returns error about malformed query when using Thunder Client while the exact same syntax in Postman works fine.

Also tried + instead of %20 but that doesn't work either.

**Expected behavior**
Expected to work similarly to POSTMAN where html encoded query parameters are handled 

**Platform:** 
 - OS: Linux (Debian)

**Solution:**
Don't know what needs to be changed to handle this issue.

**Comment by rangav** [comment]
This is now fixed in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
