### ISSUE TITLE
JSON Schema for Schemavalidation gets Error in CI

### ISSUE THREAD

**Issue by erwinmoretz** [rangav/thunder-client-support#1471]
**Describe the bug**
Hello Ranga, 

I have upgraded the version of Thunder Client CLI in our pipeline to a current version to be able to use the tc.skipRequest() function. 

Unfortunately, this has triggered a side effect and my tests for the schema validations are failing. My analysis shows that the documents for the defined schemas cannot be read.

As soon as I switch back to the old version, the schema validation tests work again, but I can't use the function I need. 

when i run it in the local CI it works well! 

Is this bug known? 

CLI Version where schema validation is working: 1.9.0 
CLI Version which i tried to use: 1.11.0, 1.11.2

Screenshot from log: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/bbd82094-7aa8-437d-afc2-cd4ac2af8d78)

**Platform:** 
 - OS: Win 10
 - vscode version: 1.85.2
 - extension version: 2.17.1

**Are you using the free version/paid version/trial:**
paid

**Comment by rangav** [comment]
Thanks @erwinmoretz for reporting bug, will verify and fix it asap.

**Comment by rangav** [comment]
May be schema file path is not valid?

Can you right click on the schema file and select copy relative path and compare with existing path?

**Comment by erwinmoretz** [comment]
they use the exact same path. Here an example with the used path and the copied relative path: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/3728a527-5ae5-437d-9a1f-ada4c6ba2058)

**Comment by rangav** [comment]
Thanks for the confirmation. Will investigate and get back to you.

Can you also confirm below, will be helpful to investigate issue.

- **CLI v1.9.0** - Works locally (Yes/NO)? and CI/CD (YES/NO)?
- **CLI 1.11.0** - Works locally (Yes/NO)? and CI/CD (YES/NO)?

**Comment by erwinmoretz** [comment]
CLI v1.9.0 - Works locally (Yes) and CI/CD (YES)? ->schemavalidation working but no skipRequest feat. 
CLI 1.11.0 - Works locally (Yes) and CI/CD (NO)? -> schemavalidation not working but skipRequest is usable.

**Comment by rangav** [comment]
Thanks for the confirmation. will verify and get back to you ASAP.

**Comment by rangav** [comment]
We had similar issue before - https://github.com/rangav/thunder-client-support/issues/1310#issuecomment-1704905473

can you share the debug info by running command - `tc --debug`

**Comment by erwinmoretz** [comment]
Will share the informations from each run with the versions: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/5e4f93ef-2585-466e-8398-91752a85e41d)
![image](https://github.com/rangav/thunder-client-support/assets/112586589/f04a8be9-23c4-426f-a637-ac127d403521)
![image](https://github.com/rangav/thunder-client-support/assets/112586589/51ef23f1-0025-423c-9f62-ee058de5b3ba)

**Comment by rangav** [comment]
Thanks for sharing. Is it multi-root workspace?

**Comment by erwinmoretz** [comment]
No, its not: 
![image](https://github.com/rangav/thunder-client-support/assets/112586589/76f79604-5d6d-4784-825d-555946e59332)

**Comment by rangav** [comment]
I have fixed this issue, Please update CLI to `v1.11.6`

Please test and let me know feedback.
