### ISSUE TITLE
Special characters get converted incorrectly in cURL import functionality

### ISSUE THREAD

**Issue by xiaoxiaobt** [rangav/thunder-client-support#1472]
**Describe the bug**
Whenever there is a special character (for instance, `\u0021` i.e. `!`), the cURL import feature fails to keep the `\` in the character, resulting incorrect request body.

**To Reproduce**

Import 
```
curl "https://example.com" -H 'content-type: application/json' --data-raw $'{"a": "b", "c": "\u0021"}'
```

Result json body:

```json
{
  "a": "b",
  "c": "u0021"
}
```

**Expected behavior**

Expected json body:

```json
{
  "a": "b",
  "c": "\u0021"
}
```

**Platform:** 
 - OS: macOS 13.6.4
 - vscode version: 1.86.0
 - extension version: 2.17.4

**Are you using the free version/paid version/trial:**

Free version

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace, please update to v2.17.5

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.5

Please test and let me know your feedback.
