### ISSUE TITLE
Cookies received from "localhost" are being saved as domain "127.0.0.1" and not sent to "localhost" in subsequent requests

### ISSUE THREAD

**Issue by davidkhess** [rangav/thunder-client-support#1473]
**Describe the bug**

When I make a request to "localhost" and receive a cookie back, the cookie manager shows it stored for domain "127.0.0.1". On subsequent requests to "localhost" the stored cooke is not sent.

**To Reproduce**

Make a request to "localhost" that returns a cookie. Look in Cookie Manager and see it stored for domain "127.0.0.1". Make another request to "localhost" and verify in the console that the cookie is not sent.

**Expected behavior**

Cookies returned from "localhost" should be stored in the cookie manager under domain "localhost".

**Platform:** 
 - OS: macOS
 - vscode version: 1.85.2
 - extension version: 2.17.7

Note, I can downgrade to version 2.16.3 and this bug is not present. Received cookies are stored as "localhost" and sent as expected.

I haven't tested all versions in between to see which version introduced it though.

**Are you using the free version/paid version/trial:**

Paid version.

**Comment by davidkhess** [comment]
I guess you meant turn that setting off?

Regardless, thanks! Great extension and great support. Worth every penny.

**Comment by rangav** [comment]
Yes - Turn off.

Thanks, glad you like the extension :)

**Comment by alperencapar** [comment]
Disabling the `Preview Features` works for now.

**Comment by rangav** [comment]
The preview features setting is turned off by default in the new update `v2.17.8`
