### ISSUE TITLE
how to get Thunder-client to read my AWS auth settings from my ~/.aws/credentials file

### ISSUE THREAD

**Issue by preetmyob** [rangav/thunder-client-support#1475]
**Question:**

Then I go to a request autth and select AWS I get this panel

![image](https://github.com/rangav/thunder-client-support/assets/106501868/8a1e0472-f071-4ffb-aaa9-b15d0d00c343)

Acording to https://github.com/rangav/thunder-client-support/issues/489 this feature was created in v1.12.5. I'm currently using v2.17.7 .

I'm not finding the doco anywhere. I apologise if I've just not looked hard enough.

Thanks, Preet

**Are you using the free version/paid version/trial:**

I am using the free VSCODE extension - v2.17.7

**Comment by rangav** [comment]
Hi @preetmyob 

We don't have this functionality. Please use the AWS auth tab

**Comment by preetmyob** [comment]
> Hi @preetmyob
> 
> We don't have this functionality. Please use the AWS auth tab

Thank  you for the quick quick @rangav.

1. Could you tell what that issue https://github.com/rangav/thunder-client-support/issues/489 actually was about then please?

2. And also I wonder if you could help me understand how to I might be able solve the problem I have please? The problem is that our session tokens are timed, so I have to keep updating the settings when my token runs out. Is there where I can put theprogrammitically put my settings for auth that TC can find them without restarted the VS code process?

**Comment by rangav** [comment]
You can use .env files, generate new tokens and save to .env file and reference this file from your environment and then use these variables in aws auth tab

**Comment by preetmyob** [comment]
> You can use .env files, generate new tokens and save to .env file and reference this file from your environment and then use these variables in aws auth tab

Fabulous - thank you so much for such a quick response.
