### ISSUE TITLE
`HTTP Headers` not detect function exported from Custom Filter

### ISSUE THREAD

**Issue by flixyudh** [rangav/thunder-client-support#1477]
**Question:**

I just tried to use custom filter based on [Custom Filter doc](https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.md#how-to-create-customer-filters) but I'm struggling how to use exported function into HTTP Headers like `step 3`, my value didn't turn into green but the function itself detected in `Post Request Filter` and `Pre Request Filter`. Am i doing something wrong? or this feature not available for free version?

### Not Detected (didn't turn into green)
<img width="583" alt="Screen Shot 2024-02-14 at 22 37 52" src="https://github.com/rangav/thunder-client-support/assets/19633881/95eb6258-3eeb-4b45-a00d-cf8827a0f6db">

### available in Post/Pre Request Filter
<img width="514" alt="Screen Shot 2024-02-14 at 22 39 42" src="https://github.com/rangav/thunder-client-support/assets/19633881/4b8eb3ca-c4f5-4b13-96b3-7044dc53c921">

**Are you using the free version/paid version/trial:**
Free

**Comment by flixyudh** [comment]
Did you mean by adding `message |` before the function? I've tried it too
though but the color still doesn't turn into green

**Comment by rangav** [comment]
You can use filter on existing env variables
