### ISSUE TITLE
Weird Error when trying to open an request

### ISSUE THREAD

**Issue by Flavius-QA** [rangav/thunder-client-support#1478]
**Describe the bug**
 I get a weird error out of nowhere in Thunder client when I try to run a request. Everything worked fine yesterday. Today I opened one API request, did few GET requests with it, all good. I noticed I couldn't use the rest of the API requests so I closed Visual Studio and open it again. Now also my initial API request is not working. I just don't understand why. I try to resize de label and I can see the API url and try to click on SEND. The button does nothing.

**To Reproduce**
I wouldn't know what I did.

**Expected behavior**
I hope it works otherwise I have to quite Thunder client. I can't use it.

**Platform:** 
 - OS: Windows
 - vscode version: 1.86.1
 - extension version: v2.17.5

I am using free version.
![Thunder client bug](https://github.com/rangav/thunder-client-support/assets/160141525/4a04a3dc-529d-4205-a4b6-b9753e3c78af)

**Comment by Flavius-QA** [comment]
@rangav How can I update? it isn't v2.17.5 the latest? 
![image](https://github.com/rangav/thunder-client-support/assets/160141525/0eb03a34-0142-4d7d-92dc-1cdeac5470b5)

**Comment by Flavius-QA** [comment]
@rangav I think I do have my latest version.
![image](https://github.com/rangav/thunder-client-support/assets/160141525/a3f2f7f1-9d47-46bd-9bc7-c157c45a7ae7)

**Comment by rangav** [comment]
Please share error screenshot?

**Comment by Flavius-QA** [comment]
@rangav Is just text containing the URL and parameters of my API. I am not allowed to show the entire text because of security issues. But is just api URL
![Thunder client error](https://github.com/rangav/thunder-client-support/assets/160141525/b71de5ce-431e-48c9-bc03-44dca926b075)

**Comment by rangav** [comment]
The screenshot is not clear, may be try installing previous version that is working

**Comment by rangav** [comment]
1. try uninstall and re-install
2. try installing previous version that is working

**Comment by Flavius-QA** [comment]
@rangav I did uninstall and deleted cache. I re-installed it and works now. I don't know what could have been the problem but I am happy is solved now.

**Comment by rangav** [comment]
Thanks for confirmation.

sometimes installation could be corrupted, I also do not know the reason, but some users faced similar issues before.
