### ISSUE TITLE
Use env vars in Json tab

### ISSUE THREAD

**Issue by josephmaxim** [rangav/thunder-client-support#148]
Not sure if this is possible but would be nice to have.
<img width="309" alt="Screen Shot 2021-05-13 at 3 12 07 PM" src="https://user-images.githubusercontent.com/10732770/118175181-c2ba0200-b3fd-11eb-9eab-14165a7a110f.png">

**Comment by rangav** [comment]
Hi @josephmaxim yes its possible to use env vars in json content, but they are not green color highlighted

**Comment by josephmaxim** [comment]
Can you provide more info on how I can use var in JSON? Also, what do you mean by "not green color highlighted"?

Thanks,

**Comment by rangav** [comment]
you are using it correctly in the image you posted above.

Normally when you use env var in the fields they turn green color. see image below. 

![image](https://user-images.githubusercontent.com/8637550/118177449-9c5e8b80-b42a-11eb-8b98-05d2e01cb9a4.png)

**Comment by josephmaxim** [comment]
Oh, I see. So vars only works in the name-value fields like Form and Form-encoded. Not Json Content

**Comment by rangav** [comment]
Env Vars work everywhere, please try to execute that url and test yourself.

**Comment by josephmaxim** [comment]
It works here:
<img width="357" alt="Screen Shot 2021-05-13 at 3 49 09 PM" src="https://user-images.githubusercontent.com/10732770/118179156-ec295c80-b402-11eb-82dc-f49213498f57.png">

but not here:
<img width="362" alt="Screen Shot 2021-05-13 at 3 49 21 PM" src="https://user-images.githubusercontent.com/10732770/118179181-f21f3d80-b402-11eb-8898-8172c2c0c26a.png">

**Comment by rangav** [comment]
did execute the url for both? you are confusing yourself

**Comment by josephmaxim** [comment]
Yes I have. 
<img width="336" alt="Screen Shot 2021-05-13 at 3 57 07 PM" src="https://user-images.githubusercontent.com/10732770/118179979-fc8e0700-b403-11eb-886c-ed92e14413b3.png">
<img width="326" alt="Screen Shot 2021-05-13 at 3 57 29 PM" src="https://user-images.githubusercontent.com/10732770/118180050-19c2d580-b404-11eb-8917-63de243dd693.png">


Looks like it's returning {{email}} instead of the actual value.

Anyways Form-encoded works if I change my API to use ulrencoded but not Json.
