### ISSUE TITLE
Is there a way to display binary response instead of saving into file or opening in code?

### ISSUE THREAD

**Issue by qchroman** [rangav/thunder-client-support#1481]
Dear all,

I'm using a starter plan of this great product and I was wondering if there is a way to either automatically open some hex editor in VS Code, or display the response in HEX/Base64 format when the response is a binary?

Currently, the VS Code states that the response is a binary file, the display is not supported and offers to Save File or Open in Code.

These are extra steps to check the response. I'd rather see a response in the console, or have VS Code automatically open it in some built-in HEX editor.

Thank you in advance for your response.

**Comment by rangav** [comment]
Hi @qchroman 

You can click `Open in Code` button, to view in VS Code Hex editor

**Comment by qchroman** [comment]
Thank you, @rangav. That's what I'm doing right now, but, that's an extra step. Is there a faster way?

**Comment by rangav** [comment]
Currently - that is the best way to do it.

**Comment by qchroman** [comment]
Thank you! Is there a way to parse the response in a console, for example? That would be a way to format it in a format of choice.

**Comment by rangav** [comment]
Don't think it's possible now, but will make it possible in the next update

**Comment by qchroman** [comment]
Thank you so much for your response!

**Comment by rangav** [comment]
Sorry need more clarification

How will you plan format in console? can you provide more details?

**Comment by rangav** [comment]
Thanks got it, will think of a solution for this use case.

**Comment by qchroman** [comment]
JIC, there is no rush or immediate requirement. It was merely out of curiosity I've created this question and I think everyone can live w/o this feature :)

In any case, thank you so much for swift replies.
