### ISSUE TITLE
Multi-part requests: user should be able to set content-type for each part in a multi-part request.

### ISSUE THREAD

**Issue by ash-eng-spin** [rangav/thunder-client-support#1482]
When setting up a multipart request, Thunder Client automatically selects the content-type of the file part. The auto-assigned content-type is not always the desired content-type of the API spec, therefore our request will always result in a 400 Bad Request, because the content-type is wrong.

**Please allow a way for the user to set the content type for a file part or text part of a multi-part request.**

**Form Fields:** user should be able to set because this could application/json, application/xml, text/plain, blank or many other things.
**Files:** user should be able to set because this could be blank, application/pdf, application/octet-stream, application/vnd.ms-excel, text/csv or many other things.

Example: Multipart Form Data: PDF file content-type automatically set. No manual way for user to set content-type for a file.
Why is this a problem: API spec for the pdf file wants "application/octet-stream" for the content-type. Thunder Client automatically sets the content-type to "application/pdf". No way to manually set the content-type. Results in 400 bad request because content-type does not match API spec and there is no way to change in Thunder Client.

![image](https://github.com/rangav/thunder-client-support/assets/131696171/4f00d3bd-fcc8-4eac-9f67-1dc007a88ac2)

## Versions
ThunderClient v.2.17.8
Visual Studio Code 1.86.2
OS: Windows_NYx64 10.0.22621

## Steps to reproduce 1
1. Create POST request
2. Go to Body > Form > Form Fields
3. Enter field name and value <---User cannot change content-type of the file

## Steps to reproduce 2
1. Create POST request
2. Go to Body > Form 
3. Select Files check box 
4. Go to Files section
5. Enter field name and value <---User cannot change content-type of the file

For reference this is how it works in Postman:

![image](https://github.com/rangav/thunder-client-support/assets/131696171/72a2b365-55d9-4669-a64e-7d6b518a52b9)

Free Version - can't move to paid until this is a feature. It's a show stopper for us.

**Comment by rangav** [comment]
Hi @ash-eng-spin

Thanks for the feedback.

Can you share your company details using below form.
https://www.thunderclient.com/contact

**Comment by rangav** [comment]
@ash-eng-spin 

Here is the proposed solution in the next update - you can append `content-type` to the field names

Let me know your feedback

<img width="775" alt="Screenshot 2024-02-24 at 17 39 52" src="https://github.com/rangav/thunder-client-support/assets/8637550/4c7e1012-6175-4298-837c-42b9c9a412b5">

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.18.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.18.0

Please test and let me know your feedback.

**Comment by rangav** [comment]
Thanks for the confirmation 👍
