### ISSUE TITLE
Error when sending request: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by esp0314** [rangav/thunder-client-support#1483]
Hi @rangav,

One of our api endpoints is failing due to the error below. Can you please help us check? 
![image](https://github.com/rangav/thunder-client-support/assets/148940089/8702ee2d-8df9-419b-aaca-7556bf0d7e35)

Tried also in CLI, and got the same result
![image](https://github.com/rangav/thunder-client-support/assets/148940089/58b34607-732c-4b32-a9a0-403875c49919)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/88735a23-d6dc-406d-b127-379eb30033f2)
ThunderClient version: 2.17.8
CLI version: 1.11.8

Tried different version and it is working at least on 2.17.1(or maybe lower)
![image](https://github.com/rangav/thunder-client-support/assets/148940089/34be464d-643e-403a-b1d9-bc2d323f1c8e)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/07ee03d1-5965-4850-afaa-791c3fc78cce)

And for CLI, it is working from 1.11.4 and below
![image](https://github.com/rangav/thunder-client-support/assets/148940089/92af9b76-8b58-4452-a8ba-289ff42fad4c)

**Comment by rangav** [comment]
This Bug is fixed now and published to the marketplace, please update to `v2.18.0`
and CLI to `v1.12.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.18.0

Please test and let me know your feedback.

**Comment by esp0314** [comment]
Thank you for the update @rangav. Verified fixed
![image](https://github.com/rangav/thunder-client-support/assets/148940089/ed85739f-395f-4ec0-9b8c-dbd150f7d7de)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/a54bf2d3-c589-4950-bf3c-4e409ebc2813)

**Comment by rangav** [comment]
Thank you for the confirmation
