### ISSUE TITLE
How to use require instead of tc.loadModule for a non built-in module?

### ISSUE THREAD

**Issue by Sureshp11** [rangav/thunder-client-support#1485]
**Question:**
How to use require for a non built-in module?
I am using 'Lodash' module in my script and loadModule is not loading when I run the script first time. It works only for the second time. Is it possible to use require instead of LoadModule for Lodash? 

**Are you using the free version/paid version/trial:**
trial

**Comment by rangav** [comment]
Can you share the script you used for loadModule?

**Comment by Sureshp11** [comment]
I have used await in the code below. However it's not working. 
lodashTestDemoScript.js:

//Test class contains the actual tc test
class Test {
  constructor(obj1,obj2) {
    this.obj1 = obj1;
    this.obj2 = obj2;
  }
  async action() {
    
    const {_} = await tc.loadModule('lodash');

    _.mergeWith(this.obj1,this.obj2,
        function(objectValue, sourceValue) {
          tc.test('mergeWith Test ',
                function() {                  
                  expect(objectValue).to.equal(sourceValue);
                });
        });
  }
}

//Run function executes the test available in the tasks
async function run(tasks){      
  let taskNo = 1;
  try {      
    for (const task of tasks) {          
      await new Promise((resolve, reject) => {          
        task((err) => {            
          if (err) {
            reject(err);
          } else {              
            resolve();
          }  
          taskNo++;
        });
      });
    }           
  } catch (err) {
  console.log('Promise error');                
  }
}

//LodashTests function adds the test to the tasks and calls the run function
function LodashTests() {
 
  performLodashTest = async (obj1,obj2) => { 
    
    const tasks = [];

    tasks.push(async () => {
      await new Test(obj1,obj2)
          .action();
    
    });

    run(tasks);
    
  };

  return {
    performLodashTest: performLodashTest
};
}

module.exports = {
  LodashTests,  
};

The inline script that calls the function:
require("C:\\Temp\\lodashTestDemoScript.js");

const obj1 = {
      'amit': 20,
    };
  
    const obj2 = {
      'amit': 30,
    };    

await new LodashTests().performLodashTest(obj1,obj2);

**Comment by rangav** [comment]
I tested the lodash module its working for me, I did not understand your code, what you are trying to do.

Can you test with small code first?

<img width="799" alt="Screenshot 2024-02-29 at 07 17 24" src="https://github.com/rangav/thunder-client-support/assets/8637550/c2abcb9a-79a0-41af-936f-d5591451c47a">

**Comment by rangav** [comment]
why do you need promises our extension supports async and await.

**Comment by rangav** [comment]
Remove promised it will work directly and syntax for lodash also wrong I think.

<img width="1167" alt="Screenshot 2024-02-29 at 11 30 01" src="https://github.com/rangav/thunder-client-support/assets/8637550/d4422c00-8519-474a-b54f-e9a46754b297">


```js
const performLodashTest = async () => {
    const _ = await tc.loadModule('lodash');
    
        tc.test('Lodash test', function(){
          console.log(_.now());
          
          _.now()>0
          
        });
};

await performLodashTest();
```

**Comment by rangav** [comment]
you can simply the above code further as below

```js
const _ = await tc.loadModule('lodash');
    
tc.test('Lodash test', function(){
   console.log(_.now());
   _.now()>0;
 })
```

**Comment by Sureshp11** [comment]
We have been working on the existing code base to migrate to Thunder Client. Our existing code uses Lodash and promises in it. I don't want to change the logic.

**Comment by rangav** [comment]
ok here is your code updated with promises

```js
async function performLodashTest(){

const fn = async () => {
  const _ = await tc.loadModule('lodash'); // use _
      tc.test('Lodash test', function(){
        _.now()>0;  // use _
        
      });
  };

  new Promise(function(resolve, reject){
    return fn(() => { // return keyword missing
        resolve();
    });
  });
}

await performLodashTest();
```

**Comment by Sureshp11** [comment]
I still can't see it working. I ran exactly the same code and it didn't create the test. I ran it again then it did. 
![image](https://github.com/rangav/thunder-client-support/assets/160588122/2c9da711-13c0-4fbb-83fc-4781b82b9310)

**Comment by Sureshp11** [comment]
I have used two iterations below to show it more clearer:
![image](https://github.com/rangav/thunder-client-support/assets/160588122/e87680d1-7e8b-4808-bb62-53932a71e083)

**Comment by rangav** [comment]
modified further, this is working

```js
async function performLodashTest(){

    const fn = async () => {
      const _ = await tc.loadModule('lodash'); // --------> use _
          tc.test('Lodash test', function(){
            _.now()>0;  // ---------> use _
            
          });
      };
    
     return new Promise(function(resolve, reject){
       fn().then(()=>{  // --------> modified
           resolve();
        })
      });
}

await performLodashTest();
```

**Comment by Sureshp11** [comment]
That works. Thanks.
