### ISSUE TITLE
File Not Found (CLI v1.12.0, and UI v2.18.0)

### ISSUE THREAD

**Issue by esp0314** [rangav/thunder-client-support#1488]
Hi @rangav,
Could you please help us check this?

I have a pre-run custom script that reads a text file. This text file only contains the indicator on what environment to run the collections, in this case its int0. Basically its just a simple string. And the location of this text file is the same location with my custom script. When running the CLI using the filePath = '../env.txt', it was able to read the file, local environment was updated with the corresponding endpoints, and api was executed. 

![image](https://github.com/rangav/thunder-client-support/assets/148940089/85359922-edf4-4208-822a-ea7a52b56c51)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/2ded5ee3-028f-465a-aaf0-cf6a54fda139)

However, when running the API in the UI, it looks like the filePath = '../env.txt' is not recognized. As you can see, my local environment was not updated, that cause the error.

![image](https://github.com/rangav/thunder-client-support/assets/148940089/94600b89-eca0-477a-a217-cda06de9493c)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/6ba4f1a6-824d-44fe-8bb7-0296272e72e5)

I updated the filePath to 'api-tests/env.txt' and works fine
![image](https://github.com/rangav/thunder-client-support/assets/148940089/753372fd-6885-4bab-9f33-d57500456098)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/881aac10-e6d6-4f40-95fd-3e71bebbc65d)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/bee4780d-0b22-4da5-ad46-348f604757ad)

Going back to CLI, it was not recognized the updated filepath
![image](https://github.com/rangav/thunder-client-support/assets/148940089/071fae14-94ac-4ca1-b337-965d3b418a8b)

It looks like there is an inconsistent behavior between the UI and CLI. 

Thank you.

**Comment by rangav** [comment]
Hi @esp0314 

Please right click on file in vscode and select `Copy Relative Path` and use this path.

please test and let me know

**Comment by esp0314** [comment]
Hi @rangav,

Thank you for your reply. I did and got the same result
![image](https://github.com/rangav/thunder-client-support/assets/148940089/3132fa3a-58a2-417e-8b65-fdf38f302f05)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/f3697dd0-22c4-470a-b11f-7472bc7a5e61)

**Comment by rangav** [comment]
Thanks for testing

its it working in the extension?
Any previous version of CLI working?

I will verify and get back to you

**Comment by esp0314** [comment]
Last known working is CLI v1.11.5 using a relative path
![image](https://github.com/rangav/thunder-client-support/assets/148940089/bb41305e-cd09-4242-a62f-d713d4cc1b2f)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/a99095e4-af81-4277-819b-1d78c194ea33)

Yes, UI extension v2.18.0 is working using relative path

**Comment by rangav** [comment]
Thanks will verify and get back to you

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace. Please update to `v2.19.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test it and let me know your feedback

**Comment by esp0314** [comment]
Thank you for fixing the path issue on CLI v1.12.4 and Extension v2.19.2
![image](https://github.com/rangav/thunder-client-support/assets/148940089/120882e2-4f90-4d4d-8bbb-ca5e34f0e6c7)


However, i found another issue but not related to this. I will file a separate ticket and provide the complete info.

**Comment by rangav** [comment]
Thanks for confirmation
