### ISSUE TITLE
Ignore skipped flag on CLI run

### ISSUE THREAD

**Issue by arrensen** [rangav/thunder-client-support#1489]
**Please describe feature/problem details and the solution you'd like.**
When running a set of testcases using the CLI runner the skipRequest flag which was set through the "Run all" UI is evaluated and tests are skipped even though they are in an explicit list of testcases to run using the "--reqlist 'a,b,c'" flag.

I have a set of predefined request list which I run regularly through the CLI, but I also use the UI runner a lot to test out different scenarios where I enable or disable different requests quite often. When I now try to run my request lists from the CLI previous marked as skipped requests are skipped here as well. 

A solution I could think of would be to either ignore this flag if a explicit --reqlist is provided or another parameter like  "--executeMarkAsSkipped true/false" which would then also work when using the "--col" parameter to run a whole collection.

**Describe alternatives you've considered**
Before running a CLI command using the --reqlist parameter I always have to check if all necessary tests are enabled or disabled, which goes against the purpose of explicitly specifying requests to run.

**Are you using the free version/paid version/trial:**
Using the paid version

**Comment by rangav** [comment]
Thanks @arrensen for the feedback.

Will ignore the skipRequest when running the `--reqlist` command.

I will make changes in the next update, which might be in a few days.

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.19.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test it and let me know your feedback
