### ISSUE TITLE
OAuth2.0 Issues

### ISSUE THREAD

**Issue by baodad** [rangav/thunder-client-support#149]
**Describe the bug**
Cannot use OAuth2.0 in Thunder client to generate a token.

**To Reproduce**
I entered OAuth2.0 Grant Type, Token URL, Client ID, and Client Secret, but when I try to generate a token, I get an error "Something went wrong. Please try again."
Postman has OAuath2.0 options for "Header Prefix" and "Add authorization data to: Request Headers", as well as an option for Client Authentication which we can set to "send client credentials in the body".  Thunder Client has none of these options, and will not work for us.

**Expected behavior**
We would expect to receive an auth token when we click "Generate Token"

**Platform:** 
 - OS: Windows 10

**Solution:**
?

**Comment by rangav** [comment]
Hi @baodad 

What grant type are you using? where you would like to add the generated token?

**Comment by baodad** [comment]
@rangav 
Grant Type is client credentials.
I'm new to Oauth and REST.  I just wanted to prove that I can get a token.  I need to token for use in a POST request to a REST api.

**Comment by rangav** [comment]
Hi @baodad have you tested in postman with same values did it work? also there is scope variable that may be missing value?

Dont know who is your oauth provider, please check its documentation.

**Comment by baodad** [comment]
Yes, works in Postman, but Postman has options that Thunder client doesn't.

Just posting as feedback in case it's helpful to others

**Comment by rangav** [comment]
What option is missing to generate token? (not adding to header or body)

**Comment by rangav** [comment]
This is implemented now in v1.3.0, you will **Send Auth** as Header or Body which is last field
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
