### ISSUE TITLE
NTLM auth is not working

### ISSUE THREAD

**Issue by rajeesing** [rangav/thunder-client-support#1490]
**Describe the bug**
API is not working when I use NTLM auth.

**To Reproduce**
Create an API and in Auth tab, used NTLM and use your windows credential

**Expected behavior**

**Platform:** 
 - OS: Windows
 - vscode version: 1.86.2
 - node version: 18.17.1
 - extension version:2.17.5
 - 
 Using Free version

**Comment by rangav** [comment]
@rajeesing please update extension to v2.18.0 and test it.

**Comment by rajeesing** [comment]
It's the same with v2.19.0 even. I didn't find any good documentation for this NTLM setup in thunderclient. Do you have series of steps which tells you how to setup?

**Comment by rangav** [comment]
Did any previous version work for you before?

**Comment by rajeesing** [comment]
No, it wasn't. But it's working for some one else for the same endpoints.
