### ISSUE TITLE
Questions about Business Plan

### ISSUE THREAD

**Issue by broccolism** [rangav/thunder-client-support#1492]
**Are you using the free version/paid version/trial: Business plan**

Hi. I've been subscribed paid plan (Business) and have 3 questions.

1. It says I can use 500 collection runs monthly per user, so I want to check how many collection runs I have used now.
Where or how can I check this information?

2. Does 'collection runs' mean runs that executed by clicking `Run All` button? Does it mean I can run single requests on local as many as I want, right?

3. How many team member can I add using business plan??

Thanks.

**Comment by rangav** [comment]
Hi @broccolism 

can you please share your company details using below form to confirm subscription
https://www.thunderclient.com/contact

**Comment by broccolism** [comment]
Hi @rangav , my team already purchased plan.
Is it getting different depend on the company?

**Comment by rangav** [comment]
No, I am just confirming your company.

Answers:
1. The extension does not display the count yet to the user, We will add it in the next update.
2. Yes only applies to Collection Runs using the `Run All`. You can run unlimited individual requests.
3. Only one user per license. e.g if you purchase 5 seats then you can add 5 users.

Let me know if you have additional questions

**Comment by rangav** [comment]
One clarification: you can buy multiple licenses from a single account, just choose the right seats quantity required

**Comment by broccolism** [comment]
@rangav I understand. I'm gonna use contact link you gave me above going forward. Thanks for replay!

**Comment by rangav** [comment]
Sure, you can use our contact form if you have any additional questions.
