### ISSUE TITLE
request list does not show correct request type

### ISSUE THREAD

**Issue by m3dbedb** [rangav/thunder-client-support#1493]
**Describe the bug**
In collections tab there are request type logo, it is always shows get request sign

**To Reproduce**
Open collection tree, add collection with post request. It is stored as post, but always shows as get

**Expected behavior**
It is expected that thunder show post logo before request name in request list

**Platform:** 
 - OS: windows 64 bit
 - vscode version: 1.87.0
 - node version: 20.9.0
 - extension version: 2.19.2

**Are you using the free version/paid version/trial:**
free
![Смок](https://github.com/rangav/thunder-client-support/assets/25632818/4c13c50e-21c7-4bc0-859d-a5239c4c6d92)

**Comment by m3dbedb** [comment]
I will clarify: you can nor apply changes without sending request. You add new request, select put method, add request body, but there is no option to store changed, that's why request always shown with "get" method.

**Comment by rangav** [comment]
When you save request it will update the method in the sidebar.

Use `Ctrl/Cmd + S` to save request

**Comment by m3dbedb** [comment]
Also it would be great to mark unsaved request with red star like this:
Get stat *

**Comment by rangav** [comment]
The unsaved indicator is displayed in `v2.19.5`
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.5


<img width="369" alt="Screenshot 2024-03-12 at 17 26 53" src="https://github.com/rangav/thunder-client-support/assets/8637550/feb9aee5-f52c-41eb-b223-bb976e1cf082">
