### ISSUE TITLE
Open scripting tab when click on request>tests if tests>tests tab is empty

### ISSUE THREAD

**Issue by m3dbedb** [rangav/thunder-client-support#1494]
**Please describe feature/problem details and the solution you'd like.**
I don't use tests>tests tab and every type I want to see/edit test script I have to click on request > tests > scripting

**Describe alternatives you've considered**
I suggest to open tests > tests when user clicks on request > tests if there are some, and open tests>scripting if there are some script and no data in request > tests > tests tab

**Are you using the free version/paid version/trial:**
free

**Comment by rangav** [comment]
Thanks @m3dbedb for the feedback, Will add it to the roadmap.

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.19.3`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.3

Please test it and let me know your feedback
