### ISSUE TITLE
Authorization tokens not recognized

### ISSUE THREAD

**Issue by esp0314** [rangav/thunder-client-support#1496]
@rangav,
After this bug is fixed(https://github.com/rangav/thunder-client-support/issues/1488), we have updated the thunderclient version to v2.19.0 and cli v.1.12.1, but we encountered another issue.

Our api endpoint is requiring Authorization, and before this endpoint is executed, we must retrieve first the authorization tokens. In our setup, we have a pre-run api that returns tokens and saved in local environment and will be used as authorization headers in our main endpoints.  Looks like the authorization is not recognized during the initial execution and it is giving 401 Unauthorized response. And it is only recognized when the endpoint is executed the 2nd time around. Please help check

Pre-run endpoint
![image](https://github.com/rangav/thunder-client-support/assets/148940089/b26122b4-5741-4d0a-b882-86e8c3c09648)

Token saved in the local environment
![image](https://github.com/rangav/thunder-client-support/assets/148940089/a0d92102-df10-4acf-8cd1-3f0d36ccc199)

Main endpoint
![image](https://github.com/rangav/thunder-client-support/assets/148940089/6b57e7dc-52d6-4624-a34e-95ffdc23ec9c)

2nd attempt
![image](https://github.com/rangav/thunder-client-support/assets/148940089/21f2a3a5-2ab3-42c4-a5f8-31022fc812c5)

We have to revert to v2.18.0 and cli 1.12.0 and it is working fine for the authorization token headers, but we have to deal with the file not found issue again(https://github.com/rangav/thunder-client-support/issues/1488)

**Comment by rangav** [comment]
Thanks @esp0314 for reporting the bug, Will verify and get back to you asap.

**Comment by rangav** [comment]
Can you verify the [logs](https://github.com/rangav/thunder-client-support#logs) in Output window after the first attempt and see what headers are sent?

**Comment by esp0314** [comment]
1st attempt
![image](https://github.com/rangav/thunder-client-support/assets/148940089/d3003af6-60e3-4daf-b8c5-ea9baf9e0cd6)

2nd attempt
![image](https://github.com/rangav/thunder-client-support/assets/148940089/f0df4ba9-488c-4ba6-9157-e6ad359e53ba)

**Comment by rangav** [comment]
Thanks for sharing the logs.

how you are saving the access token from response to Local Env?

Will try to re-produce the issue here locally

**Comment by esp0314** [comment]
I have a custom script that will call the pre-run endpoint(that return the access token), then in the tests tab of that pre-run, i used to saved the token "setTo"
![image](https://github.com/rangav/thunder-client-support/assets/148940089/a60c919f-451c-4cf8-9599-6ac43fe2af32)

**Comment by rangav** [comment]
Little confused, want to clarify more

The screenshot above is it main request?
And where is the above script running?

**Comment by esp0314** [comment]
Sorry for the confusion. I have edited the previous reply

**Comment by rangav** [comment]
I think you are using it wrong.

You are setting the access_token after the main request is executed in Tests, that's why the main request header is not getting the access_token value.

You should set the access token directly in the script.

```js

var response = await tc.runRequest("reqId");
tc.setVar("access_token", response.json.access_token, "local");
```

**Comment by esp0314** [comment]
Hi @rangav,
I see your point, your suggestion is the same implementation with what i did. The only difference is that, saving the token is in the pre-req script, while mine is i saved in the UI.
We have been implementing this kind of setup since we use thunderclient as our main tool in api testing. As i have mentioned in the previous thread, it was working on the previous version.

Here's the setup: 
1. Collections settings
![image](https://github.com/rangav/thunder-client-support/assets/148940089/f0ab0da1-6af0-4910-a34e-c9b8ea38f22a)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/5713e5ad-3474-41e3-b42c-966309dc60b8)

![image](https://github.com/rangav/thunder-client-support/assets/148940089/86b45b03-d644-4c13-906d-5bc4d23e51e1)

2. In the main request, it uses this pre request filter(environmentEndPoint)
3. Pre-request filter will also call another request that returns the access token and save it to local environment.

**Comment by rangav** [comment]
Thanks,  now I understand how its setup. Its a correct setup, no need to change anything.

i will try to re-produce the issue and get back to you asap.

**Comment by esp0314** [comment]
Thank you!!

**Comment by rangav** [comment]
We identified the bug and will publish a fix later today. Thanks for reporting.

**Comment by rangav** [comment]
This bug is fixed and published to the marketplace. Please update to v2.19.3.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.3

Please test it and let me know your feedback

**Comment by esp0314** [comment]
Hi @rangav,

Verified to be fixed. Thank you

**Comment by rangav** [comment]
Thanks for confirmation
