### ISSUE TITLE
PayPal as Payment Option Planned?

### ISSUE THREAD

**Issue by MrJoermungandr** [rangav/thunder-client-support#1497]
**Question:**

Well dont have a credit card but would really like to buy your product sooo the question 

**Are you using the free version/paid version/trial:**

Bcs of this the free one :)

**Comment by MrJoermungandr** [comment]
sure but most likely overkill since im just an individual.
but i think you could really capture that user group with it since in europe the majority dont has a credit card :)

**Comment by rangav** [comment]
Please contact using this form, we will discuss alternative options
https://www.thunderclient.com/contact
