### ISSUE TITLE
tc.loadModule() not working for faker in Pre-Request script

### ISSUE THREAD

**Issue by ColinSowul** [rangav/thunder-client-support#1498]
**Describe the bug**
I've been attempting to use faker-js in order to generate test data for some APIs I want to test, but there seems to be an issue when Thunder Client attempts to load the module.  Currently, the only content of my script is simply copy & pasted from [what is shown in the documentation](https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#use-node-modules-to-generate-fake-data)

When I attempt to send the request, I get the following error:
`Error in Pre Request Script: - Cannot destructure property 'faker' of '(intermediate value)' as it is undefined.`

**To Reproduce**
- Place the following code snippet in the Pre-Request script of a request
```
    // example code to load faker-js module
    var { faker } = await tc.loadModule("@faker-js/faker");
    tc.setVar("firstName", faker.person.firstName());
```
- Send request
- The following error will appear:
![image](https://github.com/rangav/thunder-client-support/assets/27162728/fd5a7f60-eac7-47b1-ac34-e112479174a7)

**Expected behavior**
The Pre-Request script executes successfully, and populates a randomly-generated name into the "firstName" environment variable

**Platform:** 
 - OS: Windows 10 Pro
 - vscode version: 1.87.1
 - node version: 18.17.1
 - extension version: v2.19.0

**Are you using the free version/paid version/trial:** Paid

**Comment by rangav** [comment]
@ColinSowul There is problem loading latest versions.

version 8.0.0 is working

```js
var { faker } = await tc.loadModule("@faker-js/faker", "8.0.0");

console.log(faker.person.firstName());
```
