### ISSUE TITLE
GET request with "url=" parameter fails to prepend "Request Url" correctly

### ISSUE THREAD

**Issue by sh3llcmdr** [rangav/thunder-client-support#1500]
**Describe the bug**
Thunder Client fails to prepend the "Request Url" with "http://" if the GET request includes a "url=" parameter which also has a "http://" prefix

**To Reproduce**
In this instance I'm using a VM running VAPI (Vulnerable API) and redirecting to a public Burp Collaborator address to demonstrate. The request works perfectly if sent via Burp Suite, just for comparison.

Create a HTTP GET request with the "url=" parameter, adding the "http://" prefix to the URL and attempt to send:
![image](https://github.com/rangav/thunder-client-support/assets/126566000/ac99c6b9-b137-4fd7-ba39-8117ff0f72ab)
Thunder Client will simply show an ERROR status in the response window
![image](https://github.com/rangav/thunder-client-support/assets/126566000/cffee049-24fc-4c59-86ab-0675608e2624)

Create a HTTP GET request with the "url=" parameter, without adding the "http://" prefix to the URL and attempt to send:
![image](https://github.com/rangav/thunder-client-support/assets/126566000/36e41346-56f5-4919-94b0-f5e26afca3e6)
It will send but cause a "500 Server Error" as the "url=" parameter is not correctly formatted.
![image](https://github.com/rangav/thunder-client-support/assets/126566000/a8aeab47-fc4e-4854-bff9-668822a7d2d5)

**Expected behavior**
Thunder Client should correctly prepend the "Request Url" with "http://" (or "https://") if the "url=" parameter also has "http://" or "https://" included

**Platform:** 
 - OS: Win10
 - vscode version: VSCodium 1.83.0
 - node version: 18.15.0
 - extension version: v2.19.4

**Are you using the free version/paid version/trial:**
Free version

**Comment by rangav** [comment]
Hi @sh3llcmdr 

you can encode the query param value
<img width="779" alt="Screenshot 2024-03-12 at 11 56 50" src="https://github.com/rangav/thunder-client-support/assets/8637550/31ba8705-5054-4762-9750-a76b5bd324c4">

**Comment by sh3llcmdr** [comment]
OK, good to know. That's not really obvious for the user, or should be done automatically.

**Comment by sh3llcmdr** [comment]
Yep that works. Thanks for the quick reply
