### ISSUE TITLE
websocket do not work

### ISSUE THREAD

**Issue by xiaomocqk** [rangav/thunder-client-support#1505]
**Describe the bug**
Websocket do not work for me, the request url host is seems still sent with "http" protocol
Connect via postman instead, it works.
<img width="1340" alt="image" src="https://github.com/rangav/thunder-client-support/assets/22288684/7a4fce49-2a5b-446d-9376-b3cecd0c7318">
<img width="1353" alt="image" src="https://github.com/rangav/thunder-client-support/assets/22288684/c42c6728-b041-4b25-b537-6986af3e33ff">

**To Reproduce**
New request > Websocket Request

**Expected behavior**
Connect to ws successfully

**Platform:** 
 - OS: Darwin x64 21.5.0
 - vscode version: 1.85.1
 - node version: 18.15.0
 - extension version: v2.19.6

**Are you using the free version/paid version/trial:**
free version

**Comment by rangav** [comment]
Thanks @xiaomocqk for reporting the bug, Will fix it asap.

**Comment by rangav** [comment]
We have fixed the bug. Please update the extension to v2.19.7

**Comment by xiaomocqk** [comment]
Such efficient, thanks @rangav , it works now with v2.19.9

**Comment by rangav** [comment]
Thanks for the confirmation
