### ISSUE TITLE
Websocket only connects using WSS

### ISSUE THREAD

**Issue by c4ldas** [rangav/thunder-client-support#1506]
**Describe the bug**
After fixing the issue with Websocket connection on #1505, we can see the connection only allows WSS connection, and it is not able to connect to a websocket using just WS. That would be expected to work on a localhost environment.

**To Reproduce**
New request > Websocket Request
The dropdown menu shows WS, but it tries to connects via WSS
Connection fails with `Error: write EPROTO 14120576:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:231:` due to that

**Expected behavior**
The option on the dropdown menu shows WS, but it tries to connect using WSS
If possible, a new  option for WSS should be added

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.87.2
 - node version: 18.17.1
 - extension version:2.19.8

**Are you using the free version/paid version/trial:**
Free version

![image](https://github.com/rangav/thunder-client-support/assets/75918726/16c36f34-143c-430c-bd3c-577162b15a52)

![image](https://github.com/rangav/thunder-client-support/assets/75918726/60c8315f-d65f-41fc-9a9e-7a19fde2135e)

**Comment by rangav** [comment]
Thanks @c4ldas for reporting the bug, Will fix it asap.

**Comment by rangav** [comment]
We published a new update to fix this bug, Please update to `v2.19.9`

Let me know your feedback after testing.

**Comment by c4ldas** [comment]
> We published a new update to fix this bug, Please update to `v2.19.9`
> 
> Let me know your feedback after testing.

Wow, that was incredibly fast, didn't expect it to be fixed so quick! 
That's perfect! We are now able to connect using both WS and WSS! Thanks a lot!

![image](https://github.com/rangav/thunder-client-support/assets/75918726/5565c4db-6cc3-45b0-88bb-5be840eb4451)

**Comment by rangav** [comment]
Thank you for the confirmation.
