### ISSUE TITLE
Autocomplete variables

### ISSUE THREAD

**Issue by afonsoogomes** [rangav/thunder-client-support#151]
It would make it much easier to autocomplete variables when typing

**Comment by rangav** [comment]
Hi @Afonker will add to roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.18.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.18.0

Please test and let me know your feedback.
