### ISSUE TITLE
Is it possible to run a request for a token and use it after in another request?

### ISSUE THREAD

**Issue by gcstang** [rangav/thunder-client-support#152]
I would like to run a request that returns a JSON Payload with a key of "access_token"

Then I would like to use another request that has the value from that previous request in this new request's header variable "assertion".

Thank you

**Comment by rangav** [comment]
Hi @gcstang yes that's possible, save to env variable in first request 
and use that env variable in 2nd request. And add both requests to collection and click `Run All` option 

see testing section

**Comment by anilkk** [comment]
@rangav Not able to set the env variable in the first request. Please take a look at this recording for the details. 
https://www.loom.com/share/1f9528ac37ed498cb4f8345115b21846

**Comment by rangav** [comment]
Hi @anilkk did you follow instructions as described in Testing section?

**Comment by anilkk** [comment]
@rangav It works fine now. 👍

**Comment by anilkk** [comment]
@rangav Here you can take a look at the demo.
https://youtu.be/6PDZzhpl8Sg

**Comment by rangav** [comment]
Hi @anilkk thanks for confirmation and making a video on Thunder Client. let me know if you have any questions

I am also closing this issue, feel free to re-open if needed.

**Comment by gcstang** [comment]
@rangav this isn't working for me
As I mentioned I'm capturing the token from the first request then attempting to use it in the Header section of the second.

I obtain the Auth here
<img width="558" alt="ObtainAuth" src="https://user-images.githubusercontent.com/3171369/118499613-f5087f80-b6db-11eb-89d4-890f762e5686.png">

Attempt to use the Auth
<img width="532" alt="UseAuth" src="https://user-images.githubusercontent.com/3171369/118499641-fcc82400-b6db-11eb-82bf-fea313ea061d.png">

Run All as you suggested and I get a 401 on the call that should be using the Token
<img width="271" alt="Screen Shot 2021-05-17 at 06 49 31" src="https://user-images.githubusercontent.com/3171369/118499899-300ab300-b6dc-11eb-8561-d7d6a1643765.png">

**Comment by rangav** [comment]
Hi @gcstang you can run separately both the requests to test which one is failing.

1. run the first request and see whether the env var is set or not 
2. If 1st is successful then run the second and test it.

and let me know which request is the issue.

**Comment by gcstang** [comment]
@rangav 
I receive a 200 on the first request, how can I see if the env var is set properly?
The second request is the one with the 401 because it's not receiving the env var from the first.

Do you have documentation?
Can you provide an example so this is easier to configure?
------
Disregard, figured it out on my own but documentation would be very helpful on how to set something like this up.
- I made a guess and added an Env then added my variable into it without a value
- I then re-ran my first request and looked at the Env and see that it's now populated
- I then re-ran my second request and it worked.

**Comment by rangav** [comment]
Oh ok you did all this without creating Environment first. Then it won’t work. 

Will update documentation.

**Comment by gcstang** [comment]
@rangav once you have the updated documentation for this type of scenario, please add to this ticket.

Thank you

**Comment by rangav** [comment]
Sure will do 👍

**Comment by rangav** [comment]
Here is link to updated documentation for Set Env Variable
https://github.com/rangav/thunder-client-support#testing
