### ISSUE TITLE
Double data paste

### ISSUE THREAD

**Issue by pacifi5t** [rangav/thunder-client-support#153]
**Describe the bug**
Sometimes, when you hit CTRL + V, it pastes the data twice

**To Reproduce**
Create a new request, erase URL example, paste the copied URL. This works for JSON body text field as well. But in both cases, the bug doesn't occur all the time.

**Expected behavior**
The data being pasted only once

**Platform:** 
 - OS: Arch Linux

**Solution:**

**Comment by rangav** [comment]
HI @pacifi5t Thanks for reporting, I will verify it.

**Comment by rangav** [comment]
HI @pacifi5t i cant re-produce the issue on my mac. can you verify and let me know know if you still have the issue.

also please update vscode and extension to latest versions.

**Comment by pacifi5t** [comment]
Hi, I've used the extension this whole month and haven't faced this issue, so I'm closing it

**Comment by rangav** [comment]
Thanks @pacifi5t  for confirmation
