### ISSUE TITLE
what is the license for this plugin ?

### ISSUE THREAD

**Issue by faker690** [rangav/thunder-client-support#154]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 

**Solution:**

**Comment by rangav** [comment]
Hi @OliverQiu good question, it's not open source, but I haven't created any license document  yet. Are you interested in knowing any particular thing?

**Comment by faker690** [comment]
a very helpful tool, easy and powerful, so if it is open-source, would be very good news. meanwhile, many people may like to let more users enjoy it.

**Comment by rangav** [comment]
HI @faker690 one more user also asked about license, I will prepare one and update you.

**Comment by rangav** [comment]
HI @schizovivek License document is ready. Let me know if you have any questions

https://github.com/rangav/thunder-client-support/blob/master/LICENSE.txt
