### ISSUE TITLE
Ability to Add collections to git without export / re-import

### ISSUE THREAD

**Issue by spik3r** [rangav/thunder-client-support#155]
**Is your feature request related to a problem? Please describe.**

It would be great to have a simple way to share collections and individual requests through version control.

**Describe the solution you'd like**

When a new collection is added or updated it appears as a file maybe json in the project that can be checked into git or ignored.

**Describe alternatives you've considered**

Can export the collection as JSON check this into git and reimport manually.

**Comment by rangav** [comment]
Hi @spik3r git support already implemented, please see team features section.

**Comment by spik3r** [comment]
Oh awesome. Sorry I didn't see it. Here's the link for anyone googling the same thing later: https://github.com/rangav/thunder-client-support#team

**Comment by giuseppepaul** [comment]
Any chance you could point me in the right direction @spik3r ? I've looked at this:

https://github.com/rangav/thunder-client-support#team

...several times and I don't understand what I need to do. It doesn't actually tell you how to set it up, am I missing something?

Cheers

**Comment by rangav** [comment]
Hi @giuseppepaul 

There are 2 ways you save collections to git. so there 2 vscode settings options available
1. Save all requests in one location.
2. or Spilt requests by project/workspace.

Open vscode settings search thunder keyword, then choose option 1 or 2 and follow the instructions below.
https://github.com/rangav/thunder-client-support#team

btw which option suits you? and let me know what is not clear.
