### ISSUE TITLE
Blank Page when opening requests

### ISSUE THREAD

**Issue by Dru-Go** [rangav/thunder-client-support#156]
**Describe the bug**
When ever i open a request i imported from postman it opens a blank page. I have tried importing a new export and it still have this issue. 

![Thunder Client faliures](https://user-images.githubusercontent.com/36500142/118724281-15008600-b837-11eb-82c1-9330e214ebeb.png)

**Expected behavior**
Expected to open the page to route requests

**Platform:** 
 - OS: Linux - Solus OS

**Solution:**

**Comment by rangav** [comment]
Hi @Dru-Go thanks for reporting the issue.

The issue happens only with postman import requests or all requests?

For me to find the exact issue, can you share sample postman collection file that has the issue, so i can verify it. make sure no sensitive is in that.

**Comment by Dru-Go** [comment]
New Requests work fine, Its the Postman requests are not working

**Comment by rangav** [comment]
I will verify and get back to you.

**Comment by rangav** [comment]
Hi @Dru-Go its working for me, see screenshot below. is your vscode updated to latest?

![image](https://user-images.githubusercontent.com/8637550/118782458-068d8b00-b886-11eb-8a68-6aa9466f9ddf.png)

**Comment by Dru-Go** [comment]
Am on the latest update sadly version 1.56.2

```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-73-generic snap
```

**Comment by rangav** [comment]
Oh ok, don't know what is the issue, it's working fine on my machine , can you try completely closing all vscode instances and open again and test it.

**Comment by Dru-Go** [comment]
I have tried reinstalling the extension
I have tried restarting vscode
I have tried restarting my machine, its still an issue

i'm going to try reinstalling vscode, maybe that would do the trick. Thanks for the quick reply :+1:

**Comment by Andriiklymiuk** [comment]
https://user-images.githubusercontent.com/19595452/119337902-07645980-bc98-11eb-80f4-c7214893c78e.mov

almost same problem with latest vscode and latest thunder client version.
Have @Dru-Go you resolved it?

**Comment by rangav** [comment]
HI @Andriiklymiuk may be try vscode insider version - https://code.visualstudio.com/insiders/

**Comment by Andriiklymiuk** [comment]
@rangav thanks for fast response! 
Well, I tried insiders version, but it still doesn't work. I think it is probably laptop issue.

**Comment by rangav** [comment]
FYI - There is was an issue when vscode is zoomed out

**Comment by HBunnick** [comment]
Got the same issue that the Page is Blank when reopening requests. Importing exporting seems to be unrelated.

Version: 1.58.2 (Universal)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Pressing the "New Request" Button works as expected.

Reopening any "Saved Request" from the Activity Tab or Collection leads to a blank Page for me.

This is error is repeatable for me with any request.

**Comment by rangav** [comment]
Hi @HBunnick what is the extension version you are using?

**Comment by HBunnick** [comment]
Thunder Client Version 1.7.1

**Comment by rangav** [comment]
@HBunnick Can you backup and delete all collections and all activity and reload vscode and create new requests and test now?

is that possible?

**Comment by rangav** [comment]
Hi @HBunnick could be the issue related to #262, can you delete thunderResponses.db file

**Comment by HBunnick** [comment]
Hi @rangav after deleting all Files in ~/Library/Application\ Support/Code/User/globalStorage/rangav.vscode-thunder-client/thunder* it seems to be working again, issue is indeed related to #262.

Thanks for your support.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.
