### ISSUE TITLE
Addition of license agreement

### ISSUE THREAD

**Issue by schizovivek** [rangav/thunder-client-support#157]
I'm trying to get your plugin onboarded into our organization but the onboarding team will only look into it if you have a license agreement in place. Currently there is no license agreement that we can see. 
Can you add a license to your thunder-client repo?

**Comment by rangav** [comment]
Hi @schizovivek it's not open source, but I haven't created any license document yet. We have a privacy policy section.

I will try to prepare a license document, this may take time.

see similar issue #154

**Comment by rangav** [comment]
Hi @schizovivek 

one question - can I know your company name and how many users are planning to use thunder client.

**Comment by schizovivek** [comment]
> 
> 
> Hi @schizovivek
> 
> one question - can I know your company name and how many users are planning to use thunder client.
Morgan Stanley.. 


Im not sure if it has to be open source or not but we do have a lot of plugins within the firm. A few samples seem to have MIT license
https://marketplace.visualstudio.com/items/ms-python.python/license
https://marketplace.visualstudio.com/items/IBM.output-colorizer/license
https://marketplace.visualstudio.com/items/eamodio.gitlens/license

**Comment by rangav** [comment]
Thanks @schizovivek I will sort the license in next couple of days.

**Comment by schizovivek** [comment]
> Thanks @schizovivek I will sort out the license in next couple of days.

@rangav Hey.. Just wanted to know if this will take time for you (which is fine if it will). Only reason I ask is I had raised in ticket for adoption and if this will take time they will close it.
Let me know if this is lower down on your priority list. I will update the ticket accordingly (or rather close the onboarding one for now and then re-open once you have the license ready)

**Comment by rangav** [comment]
Hi @schizovivek its in my priority list, i am trying to sort out by middle of next week. 

I have already asked my legal guy about this, waiting for him.

I will update you early next the status.

**Comment by rangav** [comment]
In the mean time, your team can evaluate the extension to see if it has all the features that they need or anything missing.

**Comment by schizovivek** [comment]
Thanks .. I've informed them .. They don't do evaluations.. I think once it's onboarded I'll inform a few folks.. then maybe once it spreads you should start getting feedback on features or issues

**Comment by rangav** [comment]
Hi @schizovivek The legal guy responded, so planning to make it ready by Wednesday.

**Comment by rangav** [comment]
HI @schizovivek License document is ready. Let me know if you have any questions

https://github.com/rangav/thunder-client-support/blob/master/LICENSE.txt

**Comment by schizovivek** [comment]
>  
> HI @schizovivek License document is ready. Let me know if you have any questions.
> https://github.com/rangav/thunder-client-support/blob/master/LICENSE.txt
> The above license in not included in extension yet, will include in the next update, might be tomorrow.

Thank you! Will inform the onboarding team. Fingers crossed 😄

**Comment by rangav** [comment]
Hi @schizovivek just following up to see if your team started evaluating Thunder Client, as there any further issues blocking your team to use Thunder Client? or any feedback?

**Comment by schizovivek** [comment]
hey @rangav .. bad news.. they need open source software to be able to adopt within the org. sorry for all the trouble. was really looking forward to using your extension

**Comment by rangav** [comment]
no problem @schizovivek
