### ISSUE TITLE
File Upload not working with Remote - WSL

### ISSUE THREAD

**Issue by dimbslmh** [rangav/thunder-client-support#158]
**Describe the bug**
POST/GET request with file to upload fails immediately with error ENOENT: no such file or directory, stat

![image](https://user-images.githubusercontent.com/745635/118795080-6acf3f80-b8c4-11eb-97a8-ec99e5143b36.png)
![image](https://user-images.githubusercontent.com/745635/118795499-d6b1a800-b8c4-11eb-95e7-3be1c6db27e2.png)

**To Reproduce**
1. At Body > Form Tab, checked Files checkbox. 
2. Choose a file to upload 
    _I tried a .txt and .zip file located at Windows Desktop and also within a WSL2 distro of Ubuntu 20.04.2_
   - path on Windows: C:\Users\ [username] \Desktop\test.txt
   - path on WSL2: \\wsl$\Ubuntu\home\ [username] \test.txt
3. Send

**Expected behavior**
Expecting the request to complete successfully

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Comment by rangav** [comment]
HI @dimbslmh I tested file upload on windows its working for me.

Can you try POST request of any test file to https://httpbin.org/anything and see if its working.
and send me full screenshot of request and response.

**Comment by dimbslmh** [comment]
I have narrowed the issue down to a window running Remote - WSL:

![image](https://user-images.githubusercontent.com/745635/118816462-6282fe80-b8dc-11eb-9e29-65b54d5115e6.png)

This is working normal window:

![image](https://user-images.githubusercontent.com/745635/118816177-1f289000-b8dc-11eb-9be2-4154f8e613de.png)

**Comment by rangav** [comment]
Oh ok it’s WSL issue then. I try and see if I can find a solution to fix this.

**Comment by rangav** [comment]
May be you need to choose file from a different folder/drive that has access from wsl.

**Comment by dimbslmh** [comment]
It's the same for the file located on WIndows and in WSL2:

path on WSL2: \wsl$\Ubuntu\home[username]\test.txt

![image](https://user-images.githubusercontent.com/745635/118818387-792a5500-b8de-11eb-8212-9015b399be15.png)

path on Windows: C:\Users[username]\Desktop\test.txt

![image](https://user-images.githubusercontent.com/745635/118818543-a37c1280-b8de-11eb-8151-34701105c847.png)

**Comment by dimbslmh** [comment]
> Oh ok it’s WSL issue then. I try and see if I can find a solution to fix this.

I'll just open an additional standard window for now. It would be great if you are able to fix this for a WSL window (Remote - WSL extension). 

Thanks @rangav .

**Comment by dimbslmh** [comment]
Btw. this is also not working with a [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) window.

**Comment by IgnisDa** [comment]
@rangav Is there any update on this issue? I am facing the same problem.

**Comment by rangav** [comment]
It's in my list, I will update early next week.

**Comment by rangav** [comment]
I have fixed now for Remote WSL, 

1.  question1 - will the path be same format for different local/remote wsl machines  ` \wsl$\Ubuntu\home\ [username] \test.txt`

2. question2 - Hi @dimbslmh for wsl the path is - ` \wsl$\Ubuntu\home\ [username] \test.txt`, can you share full path in the container for any sample file, as I dont have the container setup on my machine.

**Comment by IgnisDa** [comment]
@rangav I think you should take a different approach to make Thunder compatible with remote development.

First of all, by remote development, I mean [this](https://code.visualstudio.com/docs/remote/remote-overview). 

I am sure VScode provides an API for extension developers to detect whether it is being run in a remote environment.

So I suggest that the extension detects if it is being run in this environment. If it does, then it uses the filesystem of the environment it is running on and not care at all about the host machine. This way you would not have to worry about adopting different strategies for different host machines.

**Comment by rangav** [comment]
Ok will check if there is any specific api for remote paths.

**Comment by dimbslmh** [comment]
It has something to do with extensionKind: https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

> You can also quickly test the effect of changing an extension's kind with the remote.extensionKind setting. This setting is a map of extension IDs to extension kinds. For example, if you want to force the Azure Databases extension to be a UI extension (instead of its Workspace default) and the Debugger for Edge to be a workspace extension (instead of its UI default), you would set:
> 
> ```
> {
>   "remote.extensionKind": {
>     "ms-azuretools.vscode-cosmosdb": ["ui"],
>     "msjsdiag.debugger-for-edge": ["workspace"]
>   }
> }
> ```
> Using remote.extensionKind allows you to quickly test published versions of extensions without having to modify their package.json and rebuild them.


To test as described in the docs, I tried adding this to settings.json, and it seems to fix the issue:
```
"remote.extensionKind": {
    "rangav.vscode-thunder-client": ["ui"],
  },
}
```

@rangav You probably need to set this in your package.json:
```
{
  "extensionKind": ["ui"]
}
```
or 
```
{
  "extensionKind": ["ui", "workspace"]
}
```

**Comment by rangav** [comment]
That’s great @dimbslmh, I will check.

one question can’t see any files in the response, they look empty.

**Comment by dimbslmh** [comment]
I did not add any field names in the previous screenshot, that's why the key is empty and there was no value to associate to non unique keys.

Here is a screenshot where I added the field names and content inside the .txt files:

![image](https://user-images.githubusercontent.com/745635/120099370-45b0bb80-c165-11eb-8dfb-54a175b93f52.png)

**Comment by rangav** [comment]
That’s super @dimbslmh 👌 - I will try on my pc and confirm.

**Comment by rangav** [comment]
Its working for me too, but one issue is its not loading requests data stored in workspace folder thunder-tests, when I set   `"extensionKind": ["ui"]`

**Comment by dimbslmh** [comment]
@rangav What happens when you add workspace to the array?
```
{
  "extensionKind": ["ui", "workspace"]
}
```

**Comment by rangav** [comment]
same issue with `["ui", "workspace"]`, will check if there is any other way.

**Comment by oncet** [comment]
Having same problem. I think if the extension would allow me to "Install Locally" instead of just "Install in WSL" it should work.

**Comment by rangav** [comment]
Hi @oncet you can download extension file from marketplace link and install as you like.

**Comment by rangav** [comment]
After testing the **solution** is to use below setting (**remote setting**) to test file upload and remove once done.
```
"remote.extensionKind": {
    "rangav.vscode-thunder-client": ["ui"]
  }
```

**Note:** if you don't remove the setting, the extension wont have access to thunder-tests in your workspace.

https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location
**"extensionKind": ["workspace"]** — Indicates the extension requires access to workspace contents and therefore will run in VS Code Server when connected to a remote workspace or codespace. Most extensions fall into this category.
**"extensionKind": ["ui"]** — Indicates the extension must run as a UI extension because it requires access to local assets, devices, or capabilities. Therefore, it can only run in VS Code's local extension host and will not work in the Codespaces browser-based editor (as there is no local extension host available).

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.

**Comment by AntoninBeaufort** [comment]
Hi,
It's seems that there is a similar problem with WSL when getting a binary response:
![image](https://user-images.githubusercontent.com/33757018/161213341-6bb6dd10-0f53-4fb7-838b-d26e92e5eb6a.png)

Tested directly on Windows (without WSL) and the same request works as expected.

**Comment by rangav** [comment]
@AntoninBeaufort did you add this setting?

```
"remote.extensionKind": {
    "rangav.vscode-thunder-client": ["ui"]
  }
```

**Comment by AntoninBeaufort** [comment]
I had tried but it didn't work, today I tried again to put this parameter in the global parameters of my VSCode then to restart it and it works, strange... Anyway it's good this solution works, thanks!

**Comment by rangav** [comment]
Thanks @AntoninBeaufort for confirming.
