### ISSUE TITLE
Show current selected "Environment" on Request Page

### ISSUE THREAD

**Issue by junalmeida** [rangav/thunder-client-support#159]
It should be good if there is a place somewhere in the request page that make it clear which environment is being used for a request, to avoid issuing a request to the wrong environment.

**Comment by rangav** [comment]
Hi @junalmeida will add to roadmap.

**Comment by markcarroll** [comment]
This is a real problem right now. I just spent an hour debugging the wrong environment because it is not clear which one the API is using.

**Comment by rangav** [comment]
Hi @markcarroll Thanks for the feedback, its already in my list.

Current selected Environment has a `star` sign
<img width="265" alt="Screenshot 2021-06-11 at 18 50 43" src="https://user-images.githubusercontent.com/8637550/121729721-b1d8db00-cae6-11eb-9bf3-085a516ed469.png">

**Comment by markcarroll** [comment]
Yes. I think the problem for me is that the menu item to change it says `set default` rather than `set active` or similar.  The word default implied to me there was another way to change it per call that I was just not finding.  

Great extension though BTW. Really well done.

**Comment by rangav** [comment]
Ok I will change it to `Set Active` to avoid confusion.

**Comment by rangav** [comment]
The `Set Default` option is renamed to `Set Active` in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0

**Comment by rangav** [comment]
This feature will be part of next update

see next update details here #282

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
