### ISSUE TITLE
JavaScript scripting pre-request feature

### ISSUE THREAD

**Issue by anwarulislam** [rangav/thunder-client-support#16]
In postman, we can attach scripting with requests. We can modify the request before it sending to the server using pre-req script. This feature is really usefull it would be great if you can include this feature into Thunder Client

**Comment by rangav** [comment]
Hi @anwarulislam can you post an example/use case what you will be doing with pre-request scripting?

**Comment by tiagoCristiano** [comment]
> Hi @anwarulislam can you post an example/use case what you will be doing with pre-request scripting?

![image](https://user-images.githubusercontent.com/9283704/115776428-79d8d580-a38a-11eb-88a0-3172037a89f8.png)
Will be usefull for something like that.

**Comment by norlancd** [comment]
Examples:

- https://liftcodeplay.com/2018/03/18/how-to-automatically-set-a-bearer-token-for-your-postman-requests/
- https://gist.github.com/bcnzer/073f0fc0b959928b0ca2b173230c0669

**Comment by S4G4R** [comment]
This would be very useful. I use pre-request scripts to add tokens to headers of requests in a collection. That way I do not need to manually add them to each request.

**Comment by rangav** [comment]
Hi @S4G4R @tiagoCristiano @norlancd if the pre-scripts are standard and common use cases, I should be able to build simple UI to hide the complexity of scripting from user - similar to scriptless testing.

Do you guys think that will work? any suggestions

**Comment by S4G4R** [comment]
> Hi @S4G4R @tiagoCristiano @norlancd if the pre-scripts are standard and common use cases, I should be able to build simple UI to hide the complexity of scripting from user - similar to scriptless testing.
> 
> Do you guys think that will work? any suggestions

Don't think it is a bad idea. 

For my usecase i need to bulk add headers to all requests inside a collection. I don't mind if it's a UI or manual script. 👍

**Comment by wildhart** [comment]
Another example is setting a HMAC header which is a hash of a secret key and the request body.  Here's an example of someone doing this in postman with a pre-request script: https://torbjornzetterlund.com/how-to-use-hmac-with-postman-to-test-webhooks.

Since the hash is generated from the request body it cannot be set in advance (unless you never change the body).

If you wanted to do this without scripting then all you need is a place for the user to enter the secret and you could calculate the HMAC for them and put it on a particular header.

Eg. in the header UI:
![image](https://user-images.githubusercontent.com/12505024/118222649-1bf46500-b4d4-11eb-8241-cea26575bdbc.png)

**Comment by hemantshelar** [comment]
> Hi @S4G4R @tiagoCristiano @norlancd if the pre-scripts are standard and common use cases, I should be able to build simple UI to hide the complexity of scripting from user - similar to scriptless testing.
> 
> Do you guys think that will work? any suggestions

Hi @rangav ,
Its a good idea to have UI to hide complexity but it will be great if developers do have access to modify the script to customize it further.
Common use case in our project is to generate **unique** payload ( lets say for order processing )

`request.body = {
   orderDate: {{#orderDate}},
   productId: {{#productId}}
}`

before posting this `payload` we have a script in place which replaces variables 

`{{#orderDate}} = someJavaScriptFunction();
{{#productId}} = someJavascriptFunction-That-Invoke-TestAPI-And-Fetch-Random-ProductID()`

**Comment by rangav** [comment]
HI @hemantshelar thanks for the suggestions, Will keep a note of these use cases, will provide more details when I start work on this feature. It might be 2nd half of this month.

**Comment by ahmedelkilani** [comment]
+1 to add pre-request scripting

**Comment by seanchan** [comment]
+1 to add pre-request scripting.
use case : 
often used with building a signature using hmac-md5 algorithm with several variables .eg:
const signature = md5(token+timestamp+etc...)
and put each vars into headers instead of mix in post-body.

**Comment by rocknet** [comment]
My use case is performing real, public client auth code with PKCE OAuth flow to get an Azure AD token for custom OAuth protected Apis.  I'm not sure how feasible this is with Thunder Client, as my pre-request script on Postman requires installation and activation of the Postman Interceptor as well, to be able to grab cookies from login.microsoftonline.com.

I've never understood why Postman acts like a confidential client (using a client secret).  It is by definition not a confidential client.  With my pre-request script and the interceptor, I can run auth the same way my SPA does.

**Comment by M0H314-hasani** [comment]
+1 to add pre-request scripting.

**Comment by blaxk** [comment]
JavaScript scripting pre-request function can be usefully used to generate dynamic strings of specific conditions.
- It is impossible to process only with system variables.

<img width="500" alt="pre1" src="https://user-images.githubusercontent.com/16889775/152637798-86a17b7c-d5be-46eb-87be-5e66401983b0.png">

<img width="500" alt="pre2" src="https://user-images.githubusercontent.com/16889775/152637803-6f4c03ff-da54-4395-9c7f-c4b3d848b31b.png">

**Comment by rangav** [comment]
Hi @blaxk thanks for sharing your use-case, I have noted it. Will update this issue when I plan to work on scripting for advanced use-cases

**Comment by rangav** [comment]
related #278

**Comment by rangav** [comment]
Hi All, started work on request linking. here is the preview screenshot of the feature. let me know your `feedback`

Advanced scripting will be implemented at later stage.

![Screenshot 2022-03-08 at 14 39 45](https://user-images.githubusercontent.com/8637550/157261049-2029168d-008c-4da3-936a-c2f29459e0db.png)

**Comment by skydiveryiyu** [comment]
> Hi All, started work on request linking. here is the preview screenshot of the feature. let me know your `feedback`
> 
> Advanced scripting will be implemented at later stage.
> 
> ![Screenshot 2022-03-08 at 14 39 45](https://user-images.githubusercontent.com/8637550/157261049-2029168d-008c-4da3-936a-c2f29459e0db.png)

Awesome, look forward for this feature!

**Comment by FarhanShares** [comment]
Can you have a way to update the environment variables from the pre-request hook? It's useful if we want to update dynamic content that needs to be stored in the environment variables. One use case could be to automatically update the Bearer Token.

However, thanks for considering to add the pre-request hook.

**Comment by mirkancal** [comment]
Really looking for the update for this feature. My use case is simple, in Backend we use firebase token, and I send an authentication request to firebase to get the token.

**Comment by rangav** [comment]
@mirkancal can you provide more details of your use case?, may be existing functionality is already can do what you are looking for

**Comment by mirkancal** [comment]
@rangav Sure. In Postman I have pre-request script. I use it to get token from firebase to use in my backend requests.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/26160059/179212755-8b1506c9-7df0-494c-817d-76b5afd41ca7.png">

**Comment by rangav** [comment]
You can achieve this now.

- Create a first request with required details
- and from Tests tab select `Set Env Envariable` and save the token to variable
![image](https://user-images.githubusercontent.com/8637550/179216313-c39fe85b-4aa6-49ae-a0f4-5c97338a20cf.png)

In 2nd request the use the token using {{token}}

You can add the 2 requests to collection folder and run them together.

let me know if you have further questions.

**Comment by JavierGonzalezAraujo** [comment]
> Hi All, started work on request linking. here is the preview screenshot of the feature. let me know your `feedback`
> 
> Advanced scripting will be implemented at later stage.
> 
> ![Screenshot 2022-03-08 at 14 39 45](https://user-images.githubusercontent.com/8637550/157261049-2029168d-008c-4da3-936a-c2f29459e0db.png)

We could inject javascript code as we do in Postman?

Good work @rangav !
Kind regards.

**Comment by pupca** [comment]
Any timeline on this? 

We need to generate a random title parameter for a request otherwise the validation fails when testing the feature.

**Comment by piyushchauhan2011** [comment]
Cool, something like this will be very useful in my current workfllow

**Comment by rangav** [comment]
> Hi All, started work on request linking. here is the preview screenshot of the feature. let me know your `feedback`
> 
> Advanced scripting will be implemented at later stage.
> 
> ![Screenshot 2022-03-08 at 14 39 45](https://user-images.githubusercontent.com/8637550/157261049-2029168d-008c-4da3-936a-c2f29459e0db.png)

Good News, This feature development is completed now. Will publish new release later today

**Comment by piyushchauhan2011** [comment]
🥳

**Comment by rangav** [comment]
`Request Chaining` feature is now implemented and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.

**Comment by anwarulislam** [comment]
Hi @rangav!
Thanks for bringing this feature 🚀

**Comment by rangav** [comment]
@anwarulislam glad, you like the feature.

**Comment by rangav** [comment]
It's time for `scripting` - the most request feature. Stay tuned... you will get this feature in few days

- I have nearly finished development, We trying to do in a unique way, I guess you all will like it.
- Please let me know who wants to test it and provide early feedback before we publish live?

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0


### Feedback
- Please let me know what additional build-in filters would be useful
- How can we improve this feature further.

**Comment by rangav** [comment]
Here is the documentation link for `Function Filters` and `Custom Scripting`

https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md

**Comment by rangav** [comment]
Hi @Darshan1304 you can generate the code and challenge in the custom script and save to env variable using `tc.setVar`

see sample js file
https://github.com/rangav/thunder-client-support/blob/af93118cb286ca0ccc04788c1ebace1007c873da/docs/custom-filters.js#L40

**Comment by Darshan1304** [comment]
But how can i add custom script in the prerun of api endpoint, can you help me on this.
because i am not able to find select custom filter field now in the VS code.
![image](https://user-images.githubusercontent.com/52024355/231960296-d1885b82-21c8-4d98-a791-26e79d2a6b39.png)

**Comment by rangav** [comment]
![Screenshot 2023-04-14 111234](https://user-images.githubusercontent.com/8637550/232017093-4a756240-d03e-47ba-b4d5-7ed2189567ac.jpg)

**Comment by Darshan1304** [comment]
Thank you now  I could see Pre filter options under pre run
