### ISSUE TITLE
Add ability to clear/delete all activity

### ISSUE THREAD

**Issue by skilkis** [rangav/thunder-client-support#160]
First off, thanks for this awesome plugin for VS Code! Currently the activity pane fills up quite quickly with requests and has to be one by one deleted.

A potential solution would be to add a `Clear Activity` item in the `Menu` dropdown!

An alternative solution would be to make it easier to delete these requests when using the keyboard. For example when hovering over a request in the Activity pane, pressing "Delete" would delete that request.

**Comment by kythuatwebso** [comment]
Vote +1

**Comment by rangav** [comment]
This will part of next update v1.4.0

**Comment by skilkis** [comment]
> This will part of next update v1.4.0

Thanks a lot @rangav!

**Comment by rangav** [comment]
This is now implemented in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
