### ISSUE TITLE
Do you have plans to support multiple languages? For example, support for Chinese?

### ISSUE THREAD

**Issue by Deroc-z** [rangav/thunder-client-support#161]
Do you have plans to support multiple languages? For example, support for Chinese?

**Comment by rangav** [comment]
Hi @Deroc-z have plans to support other languages in future.

If someone wants to help on this, that might help in implementing this.

there are other items on my list I have to complete before I can think of this.

is there any other extension that supports multi-language that you are using?

**Comment by Deroc-z** [comment]
Thank you very much for your reply. I use Chinese every day. Maybe I can help you complete the Chinese translation.

**Comment by rangav** [comment]
That’s good, when I start working on this I will notify you.

**Comment by Deroc-z** [comment]
OK👌

**Comment by wandergis** [comment]
Is there any progress? ❤️

**Comment by rangav** [comment]
@wandergis currently working on few other important issues, will look into this when I find time.

Are you not able to use the extension without Chinese translation?

**Comment by rangav** [comment]
Hi all, This feature is in my priority list to fix.

As a alternative you can use Environment variables to input Chinese chars and use them in URL field using format `{{variable}}`

Or you can also `paste` Chinese chars into the URL field.

**Comment by rangav** [comment]
I have fixed the problem now, would you guys like to test and confirm?

I can upload the `vsix` file here

**Comment by rangav** [comment]
[vscode-thunder-client-1.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/8470084/vscode-thunder-client-1.16.1.vsix.zip)

Download the attachment and install vsix manually as below
<img width="542" alt="Screenshot 2022-04-07 at 16 49 02" src="https://user-images.githubusercontent.com/8637550/162243863-efeeef39-458d-41bd-8d39-fdbd8cbdc1d4.png">

Please let me know your feedback

**Comment by wandergis** [comment]
![image](https://user-images.githubusercontent.com/5799374/162898512-a94c541d-521a-4f50-bd26-510a7e9edf28.png)
wow! tks！I can type chinese successfully!

**Comment by rangav** [comment]
super thanks for confirming.

the update also also fixes below issues
- undo and redo issue #146
- inputs scroll issue #526

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
