### ISSUE TITLE
Uploading Images doesn't work on the free version anymore?

### ISSUE THREAD

**Issue by Andonvr** [rangav/thunder-client-support#1611]
**Please describe feature/problem details and the solution you'd like.**

I've been using ThunderClient for upload images to our api a couple of months ago, and loved it. Now I wanted to revisit this, and noticed that uploading images is a paid feature? This comes as quite a shock, as uploading images is really basic in my opinion. Just an overall bad move. 
That's the problem detail, and the solution I would like is to not have something like that behind a paywall?

**Describe alternatives you've considered**
Alternatives I'm considering and will have to do for the time being is just to move away from ThunderClient? 

**Are you using the free version/paid version/trial:**
Free.

**Comment by rangav** [comment]
@Andonvr Thanks for the feedback. We moved this feature to a paid plan to help increase our paid customer base, which is essential for long-term sustainability.

**Comment by BornaBiro** [comment]
WTF?! Even opening simple image file form web is now on paid version?! I taught this is some kind of bug. I'm keeping older version since this still works on v2.29.6.
This is getting ridiculous...
