### ISSUE TITLE
Working in team / merge problems

### ISSUE THREAD

**Issue by Ibehem** [rangav/thunder-client-support#163]
Hello,
First, Thunder is really great and we really love it!!!

We are working on a project in a team of devs. So, we are all working on the same project, sharing our collections and Env.
So Dev 1 is working on some requests and Dev 2 on some others with shared variables, tests etc. 

We are using : "Load from Project" option and so _thunder-tests_ is shared on our project and included in our git.

The problem, is that we are not able to solve the merge problem on the thunderxxx.db files. 

Is there any way to share our collections in the team and manage the merge with the git?
(or am I missing something). 

Thank you,

Eric

**Comment by rangav** [comment]
Hi @Ibehem thanks for reporting the problem. 

Your doing it right, but I don’t know how we can resolve merge issue when working on the same file.

I think you have to manually choose which changes you should apply.

but it’s like any other file in git where multiple users edit the same file, there will be merge issue.

Manual choose and merge might solve.
Or search in google for any better suggestions.

I haven’t  tested the merge issue myself, I will check and test myself later on.

but if you have any other suggestions for improvement let me know

**Comment by Ibehem** [comment]
Hi! thank you for your quick reply... 

Of course we are used with the merge process, but in this case:

-  As the results are saved in the queries (which is normal), it generates a merge issue event if we are all working on different requests.
- the file format of the db doesn't allow an easy/possible way to solve the merge

<img width="925" alt="image" src="https://user-images.githubusercontent.com/39024490/118978686-e1794500-b977-11eb-82f0-646423d0fa90.png">

Thank you again for your time and help!

**Comment by rangav** [comment]
Are the 3 requests in green above belong to same request or different requests.

**Comment by rangav** [comment]
One suggestion you can compare the `_id` column and `modified` column see which one is latest.

the database files are powered by nedb, when you modified a request it will delete old request in file and append a new one.

**Comment by Ibehem** [comment]
The problem is that between merge there are tons of modifications event when the request is not modified (because the results are modified when a request is run).

One approach could be to split the request and the result db so we could ignore the results in the merge process and focus manually on the request itself...

**Comment by rangav** [comment]
the requests and results are already in different db files. responses file not in that git folder. when you run a request it will update the modified date. nedb create a duplicate req when its modified and removed them when vscode is re-started.

I force update the file to remove the duplicate immediately if that solve the problem.

**Comment by Ibehem** [comment]
Would be really great! Thank you!

**Comment by rangav** [comment]
This is now implemented in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0

**Comment by rangav** [comment]
I have updated the database format to normal `json` files in `v1.16.0`, which should fix git `merge` issues now.

Please upgrade to `v1.16.0` and let me know if any feedback 

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.0
