### ISSUE TITLE
Run All Hangs First Time

### ISSUE THREAD

**Issue by mbarnes195** [rangav/thunder-client-support#165]
When I select run all from a collection, one of the tests (first or second test) will hang and never complete.  I can get around this by selecting run all and run again, this time they will all run.  This only happens the first time I run all after starting Visual Studio Code. Tests are simple GET services, no special headers or authentication.  I have also tried reinstalling the Thunder-client extension.

**Comment by rangav** [comment]
Hi @mbarnes195 Thanks for reporting can share the vscode and extension version?

**Comment by mbarnes195** [comment]
VS Code: 1.56.2
Thunder-client: 1.3.0

**Comment by rangav** [comment]
Thanks @mbarnes195 for confirming. I will verify and see if i can re-produce the error.

**Comment by mbarnes195** [comment]
Should have also mentioned I am running on a Mac OS, Catalina Version: 10.15.7

**Comment by rangav** [comment]
I have tested on mac-os big sur, it working fine for me. 

Can you try to re-produce the error by creating a new collection and use any of these urls from https://httpbin.org/ or your current collection without any sensitive info.

and export and share the collection file, so i can find where is the bug.

**Comment by mbarnes195** [comment]
I cannot reproduce it with these services so maybe it is something within our network causing it.  I will note though it is very consistent, I can run the test standalone after starting VS Code with no issues, it is just the run all.  I have included a test collection with the first test being the problem, unfortunately, you will not be able to access this service so I'm not sure how useful it is.  For extra credit, the last test in the collection has null and boolean values, how do I test for null and true/false using the Json Query?  Unable to drag json files to this so I renamed the collection with .tst extension.
[thunder-collection_Test.txt](https://github.com/rangav/thunder-client-support/files/6517134/thunder-collection_Test.txt)

**Comment by rangav** [comment]
HI @mbarnes195 looks like the first url has timed out, when I run `Run All` or when I run that request separately, also tested in the browser it is not responding

so it seems url has some issue. please verify it.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by rangav** [comment]
HI @mbarnes195 

You can now do test to check true/false or null values

For null values you leave value input empty or type `null` keyword

https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
