### ISSUE TITLE
Query parameter that ends with '=' gets cleared

### ISSUE THREAD

**Issue by atnegrete** [rangav/thunder-client-support#166]
**Describe the bug**
Query parameters that end with '=' sign are clearing out the '=' and have to be re-added every time you switch back to that query tab.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Comment by rangav** [comment]
Hi @atnegrete thanks for reporting, can you share a screenshot where you are adding = sign.

**Comment by atnegrete** [comment]
![Untitled](https://user-images.githubusercontent.com/22260151/119009111-6c4a4780-b958-11eb-859e-a71f9f3ce31b.png)
Sure thing!

**Comment by atnegrete** [comment]
@rangav I ended up doing both.

I just wanted to bring it up because I've seen other similar tools like this that automatically encode it behind the scenes, didn't know if that's something worth doing.

Thanks! I'll keep using this, it's very slim & easy on vscode

**Comment by rangav** [comment]
Hi @atnegrete i am planning to fix this - to do automatically in the next update.

**Comment by rangav** [comment]
This is fixed now in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
