### ISSUE TITLE
Add descriptive icons in tabs

### ISSUE THREAD

**Issue by georgefarfan** [rangav/thunder-client-support#171]
Description

It is not clear if the tab belongs to the Thunder Client or to any file.

Solution

Add icons for the tabs. For example, to identify requests, environments, etc.

Implementation

Use Visual Code's own icon set, or add your own to make Thunder Client personalized.

![image](https://user-images.githubusercontent.com/55858336/119229874-393abc00-baf0-11eb-9c18-afecb2dff053.png)

**Comment by rangav** [comment]
Thanks @georgefarfan for the suggestion, will add to my list.

**Comment by rangav** [comment]
This is now implemented in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
