### ISSUE TITLE
Ability to attach ENV to a specific collection

### ISSUE THREAD

**Issue by Rezwanul-Haque** [rangav/thunder-client-support#173]
**Is your feature request related to a problem? Please describe.**
I'm working on different projects so each has its own ENV file with the same variables naming with different values. When I import the ENV file to thunder client I can't choose that ENV file for that specific project.

**Describe the solution you'd like**
A drop-down to each collection to select which ENV to use would solve the issue. If ENV not selected it will use the Global one.

![thunder_client_feature_request](https://user-images.githubusercontent.com/22642254/119306421-f01f6f00-bc8b-11eb-9c1f-c4f36b571712.png)

**Describe alternatives you've considered**
An alternative solution would be to attach from the ENV tab, which collections to be used by this ENV variable. 

![thunder_client](https://user-images.githubusercontent.com/22642254/119307047-e21e1e00-bc8c-11eb-9ae0-226233a8792e.png)

**Implementation:**

**Comment by rangav** [comment]
Hi @Rezwanul-Haque thanks for the suggestion, will implement this along with #33

**Comment by rangav** [comment]
This feature will be part of next update #282

**Comment by rangav** [comment]
Hi @Rezwanul-Haque when you attach an env to collection, should it ignore Active Env or override Active Env?

and in **Tests** when we use `Set Env Variable `, which env should it update the value, is it Active Env or Env attached to Collection?

**Comment by Rezwanul-Haque** [comment]
Ignoring the active env would be the best option here because the default env may be set for staging/prod environment but I want to test with the attached env for local testing purposes. But in case the user wants to override the active env, you can prompt a dialog if he wants to override or not.

If ENV is attached to the collection then `Set Env Variable` should update the attached ENV else the default.

**Comment by rangav** [comment]
Thanks @Rezwanul-Haque for feedback

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback

**Comment by rangav** [comment]
you can also set env variable using scope

see details here
https://github.com/rangav/thunder-client-support#set-env-with-scope
