### ISSUE TITLE
Thunder Client not properly url encoding form-encoded fields in some situations

### ISSUE THREAD

**Issue by BradAF** [rangav/thunder-client-support#174]
**Describe the bug**
In some situations, the form url encoding does not properly url encode body parameters.

**To Reproduce**
Use the Azure REST APIs for getting an access token as described [here](https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0#4-get-an-access-token). Create a client secret like the following:

**JrY6DVgGfOPDsZ//+2zivgOB/v5sASmMn49BMyDH1tc=**

Attempt to send the client secret that contains the string using the 'form-encoded' body parameters.

![image](https://user-images.githubusercontent.com/11336928/119343198-1f21ea80-bc64-11eb-9a27-e5c0682bb624.png)

**Expected behavior**
A bearer token with '200 OK' response should be sent, as it does when the string is manually encoded:
![image](https://user-images.githubusercontent.com/11336928/119343312-42e53080-bc64-11eb-8aab-e9ede6824d0d.png)

For most other strings, using form-encoding does properly encode the strings and returns the correct, expected response.

**Platform:** 
 - OS: Windows 10.0.18363 Build 18363
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Comment by rangav** [comment]
Hi @BradAF thanks for reporting, for Oauth 2.0 to generate token better to use **Auth** tab, it has all functionality to generate token. 

let me know if this solves the issue or not

![image](https://user-images.githubusercontent.com/8637550/119345078-57d7b900-bc90-11eb-9775-fab38c021e2d.png)

**Comment by rangav** [comment]
There is a blog article also on how to use OAuth client credentials
https://blog.jongallant.com/2021/04/azure-rest-apis-vscode-thunder-client/

**Comment by BradAF** [comment]
Hi @rangav! Can confirm, using the Auth > OAuth 2.0 does work. 

As an aside, one thing I neglected to mention in the original issue is that attempting to use an environmental variable in the client_secret form field using just a form-encoded field does not resolve, either.

**Comment by rangav** [comment]
For Env issue

- Make sure the proper env is **set default** to make it the **active** one.
- The variable case should match the env variable then it will turn **green**

![image](https://user-images.githubusercontent.com/8637550/119346352-03353d80-bc92-11eb-81e9-87d150b22941.png)

**Comment by BradAF** [comment]
Sorry, I was unclear - I am successfully using environmental variables in other APIs, and was even able to use them for this same OAuth 2.0 API using form-encoded form fields for other client secrets strings. I only mentioned since using environmental variables was listed as a workaround for another issue but it does not work for this specific URL encoding issue - the string still does not get url encoded properly when passed as an environmental variable.

**Comment by rangav** [comment]
Oh ok got it, I will verify and fix the encoding issue.

**Comment by rangav** [comment]
Hi @BradAF found the issue its the **+ sign in client_secret** is not sent to server from the extension, rest all fields working fine. I will fix it in the next update.

**Comment by rangav** [comment]
This is fixed now in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
