### ISSUE TITLE
Setting Environmental Variable from test does not set variable correctly 

### ISSUE THREAD

**Issue by martylavender** [rangav/thunder-client-support#175]
**Describe the bug**
When creating a Set Env Variable test to a Environmental Variable, the resulting data does not show up correctly in the related  Environmental Variable field.

**To Reproduce**

- From the Tests tab select Set Env Variable dropdown option
- Set Variable from Json Response: enter the json.propertyName on the left input box
- In value input enter the variable name, when its matches name in Env, it will turn green, if variable not exists, it will create new.
- Now execute the request you will see the variable value set in the Env.
- What is displayed is `[object Object]`

![image](https://user-images.githubusercontent.com/5631619/119371742-44baee00-bc7c-11eb-9307-4d1cc534e35b.png)

**Expected behavior**

- From the Tests tab select Set Env Variable dropdown option
- Set Variable from Json Response: enter the json.propertyName on the left input box
- In value input enter the variable name, when its matches name in Env, it will turn green, if variable not exists, it will create new.
- Now execute the request you will see the variable value set in the Env.
- What is displayed is the returned value from the API

**Platform:** 
 - OS: Windows 10 20H2 Build 19042.985
 - VSCode version: 1.56.2
 - Extension version: 1.3.0

**Solution:**
I have only attempted this process once before. The same behavior happened but at some point the value started populating. I am not sure at all what I did or what changed to make this functionality work correctly. But in my one previous attempt `[object Object]` was the initial value that was seen when viewing the Environmental Varitables.

**Comment by rangav** [comment]
Hi @martylavender I think you entered `json.` in the left input without property name.

can you try that once again now and confirm me

**Comment by martylavender** [comment]
![LvU2ZQwj8K](https://user-images.githubusercontent.com/5631619/119704780-aa92ab80-be1d-11eb-9e1b-ea5536a8ba09.gif)

Here is the process that I went through.

**Comment by rangav** [comment]
The json path is wrong, I think it should be
`json.binders[0].binder.id`

**Comment by martylavender** [comment]
Getting closer.   Now it shows up as `Error parsing json query`   I get what should be happening here.   Ill keep messing with it and report back.

**Comment by martylavender** [comment]
`json.data.binders[0].binder.id`  This did it.

**Comment by rangav** [comment]
thats right, forgot data property.

**Comment by martylavender** [comment]
Thanks for the help.  This has completely taken Postman out of my workflow. One more reason not to leave VSCode!!

**Comment by rangav** [comment]
Thats great 👍. Let me know if you have any issues in future.
