### ISSUE TITLE
Connection was forcibly closed by a peer.

### ISSUE THREAD

**Issue by Duldris** [rangav/thunder-client-support#177]
**Describe the bug**
On 10 request 7 give me back "Connection was forcibly closed by a peer."

**To Reproduce**
i've installed, imperted collection from postman and use

**Expected behavior**
that's work like postman

**Platform:** 
 - OS: Win 10 build 19042.985
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Solution:**

**Comment by Duldris** [comment]
Is a published url of thirdy company product

**Comment by rangav** [comment]
is it possible to share the url that has the issue - for me to test and re-produce the error

**Comment by Duldris** [comment]
yes, but i cannot give you the key but only url
https://api.cassanova.com/apikey/token
add header
X-Requested-With: *

body json format
{
    "apiKey":"string of api key"
}

without correct key your result is "Invalid apiKey" status"400 bad request"

when problem happen result are status: "error"

**Comment by rangav** [comment]
The url is working since it getting 400 bad request.

See reference for possible issue
https://stackoverflow.com/a/2582070/4035948

**Comment by Duldris** [comment]
i read article but, if i use the same call, on postman that's always work

**Comment by rangav** [comment]
if you share me any other url that has the same issue, without api key needed, then i can test and find cause of the error.

currently can't re-produce the error, so dont know what is causing the issue.

**Comment by Duldris** [comment]
all other test i've done without api token goes well.
if you send me an e-mail or private contact i can send you a apiKey to make a test

**Comment by rangav** [comment]
please send to this email - info@thunderclient.io

**Comment by rangav** [comment]
Got the key, will test and get back to you

**Comment by rangav** [comment]
its working for me, did you sent **post** request?

**Comment by Duldris** [comment]
Also for me work but not every time, i must make a lot call to have one response
![image](https://user-images.githubusercontent.com/56114333/119671834-619d2000-be3a-11eb-9527-2dbdfd9f8400.png)

**Comment by rangav** [comment]
dont remove default headers, i have sent request couple of times its working
![image](https://user-images.githubusercontent.com/8637550/119672217-5219d900-be32-11eb-96e8-e278b658aa03.png)

**Comment by Duldris** [comment]
i didn't remove header, i have import all from postman collection, however adding "accept:*/*" seems error call are reduce.

postman not export this header, i don't know why

**Comment by rangav** [comment]
Ok i will fix postman import issue with headers in next update.

If its working for you, i will close the issue.

**Comment by Duldris** [comment]
thanks for support

**Comment by rangav** [comment]
no problem, welcome, i have deleted the email and api key. please change the api key for safety.

**Comment by frankieci** [comment]
I encounter the same issue, but i think it has one bugger for the thunder client(v1.18.6 for vscode windows)

**Comment by rangav** [comment]
@frankieci 

we added new http library option for `axios` in v1.18.3. please update and test it. let me know your feedback

<img width="837" alt="http" src="https://user-images.githubusercontent.com/8637550/184552594-606c3ccc-850d-4dad-88f2-fc024f963f92.png">

See features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

**Comment by frankieci** [comment]
@rangav thank you very much, i tried the way that you provided, then succeed.

**Comment by JPtenBerge** [comment]
Adding two cents here: I also got this error when I was trying to send a request to a gRPC service using JSON transcoding, an [ASP.NET Core feature](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0). Turned out that Thunder Client was configured to use HTTP/1.1. Changing it to HTTP/2 got things working again.

![image](https://github.com/rangav/thunder-client-support/assets/3285470/d73b9671-9ef3-42db-9073-ce14fee3fe39)
