### ISSUE TITLE
Make the ENTER key work to send a request

### ISSUE THREAD

**Issue by DaSt1986** [rangav/thunder-client-support#178]
**Describe the solution you'd like**
When I have the page open on which I can send API request, the ENTER key on my keyboard should 'Send'. Now I either have to use the mouse, or press TAB followed by ENTER. It's a minor inconvenience, but it still is one.

**Describe alternatives you've considered**
TAB, ENTER and using the mouse.

**Implementation:**
I'm sorry, my TypeScript/JavaScript knowledge is below par, otherwise I would have used a Pull Request.

**Comment by rangav** [comment]
Hi @DaSt1986 the shortcut is `cmd/ctrl + Enter`

See all the keyboard shortcuts here
https://github.com/rangav/thunder-client-support#keyboard

**Comment by rangav** [comment]
`Enter` key to run request is now supported in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0

**Comment by DaSt1986** [comment]
Hi Ranga,

Amazing! Thank you so much!!

Daryl

**Comment by rangav** [comment]
No problem Daryl 😊
