### ISSUE TITLE
Headers not sent?

### ISSUE THREAD

**Issue by anentropic** [rangav/thunder-client-support#179]
**Describe the bug**
add an `Authorization` header
make a request
server replies `"error": "You are not authenticated"`

same request via curl works fine

**To Reproduce**
I tried adding my auth details via the Auth tab and separately also via Headers 

https://guides.railsbank.com/1/get-going/fetch-your-details

**Expected behavior**
should work

**Platform:** 
 - OS: macOS Catalina
 - vscode version: 1.56.2
 - extension version: 1.3.0

Seems like it's just not sending the header

**Comment by rangav** [comment]
Hi @anentropic thanks for reporting, 

Since you said it's working with curl, can you import curl into Thunder Client and test it?

**Comment by anentropic** [comment]
Same problem

my request looks like:
```
curl --request GET https://play.railsbank.com/v1/customer/me \
    --header 'Content-Type: application/json' \
        --header 'Accept: application/json' \
        --header 'Authorization: API-Key <<apikey>>
```

it seemed to import ok

one possible curiosity is the api key value has a `#` in the middle somewhere, the rest are alphanum chars

**Comment by rangav** [comment]
I have tested by posting sample data to this url https://www.thunderclient.io/t/params, to see what is sent to server.

Are you sure the prefix is **API-Key**?

![image](https://user-images.githubusercontent.com/8637550/120013909-49afd280-bfd9-11eb-90a0-7546ff6ab5b5.png)

**Comment by anentropic** [comment]
🤦   I had `'Authorisation` in the header field 🤦

**Comment by rangav** [comment]
oh ok - no problem :)
