### ISSUE TITLE
Can't set envvar from header

### ISSUE THREAD

**Issue by mbaas2** [rangav/thunder-client-support#180]
**Describe the bug**
I am trying to extract a value from the header into an envvar. This seems to be supported and I think my configuration is correct (well, it is inline with how I understood the doc) - but I have had misunderstandings before ;)

**Settings**
(sorry, currently running this locally, so no repro - but hopefully that isn't neccessary)
Config:
![image](https://user-images.githubusercontent.com/5645494/120064429-59c4c200-c06c-11eb-9ee8-296844e55748.png)

Response:
![image](https://user-images.githubusercontent.com/5645494/120064462-8d9fe780-c06c-11eb-9420-146312c2e82f.png)

Test:
![image](https://user-images.githubusercontent.com/5645494/120064485-a9a38900-c06c-11eb-9c55-c729a17b1e31.png)

**Expected behavior**
I had hoped the actual value that is shown in the response header would be transferred into the envvar.

**Platform:** 
 - OS:  Windows
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Comment by rangav** [comment]
Hi @mbaas2 thanks for reporting, will verify and get back to you.

**Comment by rangav** [comment]
one question did you select `set env variable` dropdown, its working for me see below

![image](https://user-images.githubusercontent.com/8637550/120065158-d903c700-c067-11eb-82f5-7f882efa1901.png)

![image](https://user-images.githubusercontent.com/8637550/120065185-efaa1e00-c067-11eb-8b79-4547afbacba8.png)

**Comment by mbaas2** [comment]
Thanks, @rangav, for the quick reply. Yes, I did that. (Have actually re-done it, just to be 100% certain.)  Is there any way I could enable more logging to see what exactly is causing the operation to fail?

**Comment by rangav** [comment]
are you checking the right env? it will update the active Environment only.

**Comment by mbaas2** [comment]
Hmm, no idea. I thought it would exist in that environment as I had set it up and it was shown in green after entering its name. Do I need to do anything more?

**Comment by rangav** [comment]
if its green, that should work. How many environments you have?

Can you try with this url https://www.thunderclient.io/welcome and please follow steps as shown in my screenshots above. and let me know if that's working are not?

**Comment by rangav** [comment]
Hi @mbaas2 its actually bug in the extension when there is no data returned. I was able to re-produce it. I will fix it in the next update.

**Comment by mbaas2** [comment]
Hmm, strange stuff. I can repro thew welcome test and it works as expected. So I looked at my test again and don't see a difference there :(
BTW, I only have ONE environment. These are still my 1st steps. Thanks for looking again and finding a bug - hopefully it's been "mine". I will keep eyes open for the update and test again! ;)

**Comment by rangav** [comment]
This is fixed now in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
