### ISSUE TITLE
[Feature] Showing ENV variables value when hovering over them.

### ISSUE THREAD

**Issue by Rezwanul-Haque** [rangav/thunder-client-support#184]
**Is your feature request related to a problem? Please describe.**
I need to go to the ENV tab to check a variable's value

**Describe the solution you'd like**
It'll be great if we can check the variable's value when hovering over them

![env_variable](https://user-images.githubusercontent.com/22642254/120294784-5c335000-c2e8-11eb-9c85-7c39408133bd.png)

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
HI @Rezwanul-Haque thanks for the suggestion, will add to roadmap.

**Comment by MelGrubb** [comment]
Yes please. I would love the ability to inspect the variables in place on a request rather than heading off to the environment tab and hunting them down.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
