### ISSUE TITLE
Response status code 404 where in postman response comes up

### ISSUE THREAD

**Issue by Prasanna024** [rangav/thunder-client-support#185]
API: 
http://brm-core-0.brsrvr.com/api/v1/core/?account_id=6142&auth_key=c9q5rupnq08ihh5d&q=crystal+chandeliers&request_type=thematic&domain_key=ylighting&request_id=205215805700&_br_uid_2=%5BCookie%20id%3D355365080%5D&ref_url=http%3A%2F%2Fylighting.comnull&fl=pid%2Ctitle%2Cbrand%2Cbrand_url%2Cprice%2Csale_price%2Cpromotions%2Cthumb_image%2Csku_thumb_images%2Csku_swatch_images%2Csku_color_group%2Curl%2Cprice_range%2Csale_price_range%2Cdescription%2Creviews%2Creviews_count&rows=48&start=0&sort=&url=http%3A%2F%2Fylighting.com%2Fcrystal-chandelier

**Comment by rangav** [comment]
Hi @Prasanna024 thanks for reporting the issue, I will verify and get back

**Comment by rangav** [comment]
identified the issue with query param `p = crystal+chandeliers`, if you remove + sign, it works

**Comment by Prasanna024** [comment]
Thanks, but since postman is able to give the response... any fix for this in future?

**Comment by rangav** [comment]
I will fix in the next update.

There were some users asked to encode + sign to send phone no e.g +91 123456789. so I encoded the plus sign.

I think i have to reverse it to match browser behaviour

**Comment by Prasanna024** [comment]
Great! Since most people use this extension as an alternative for POSTMAN, it would be great if this extension behaves same as postman does..

**Comment by rangav** [comment]
This is fixed now in v1.4.0
https://github.com/rangav/thunder-client-support/releases/tag/1.4.0
