### ISSUE TITLE
Query Parameteres with the same name aren't saved if unchecked

### ISSUE THREAD

**Issue by michael-tipton** [rangav/thunder-client-support#186]
**Describe the bug**
Having query parameters with the same name, if you uncheck  one and close the window the parameter that was unchecked is deleted. If both are checked and the window is closed it seems to save both parameters. 

![Capture1212](https://user-images.githubusercontent.com/43582055/120503302-2eeeac80-c391-11eb-8d27-59c8d2c36484.PNG)

**To Reproduce**
Have 2 parameters with the same name, uncheck one and close window.

**Expected behavior**
All parameters should persist until manually removed.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.56.2
 - extension version: 1.3.0

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0

**Comment by michael-tipton** [comment]
Verified. same-named parameters are not being removed. Thank you for the update!

**Comment by rangav** [comment]
Thanks @michael-tipton for confirmation 👍
