### ISSUE TITLE
"Couldn't resolve the hostname to an IP address. Please check the URL." error for requests against .test domains

### ISSUE THREAD

**Issue by mosfetish** [rangav/thunder-client-support#187]
**Describe the bug**

I use .test suffix for my local dev sites. They are set in my hosts file and accessible via browser, ssh client, etc. just like external sites. I connect to them using the SSH client in VS Code. No problems at all. But Thunder issues the warning "Couldn't resolve the hostname to an IP address. Please check the URL." with them.

**To Reproduce**

Access a .test domain.

**Expected behavior**

The client should treat .test domains like any other.

NOTE: Postman works perfectly with my .test domains.

**Platform:** 
 - OS: Windows 10 Pro 
 - vscode 1.56.2
 - extension version: 1.4.0

**Solution:**

**Comment by rangav** [comment]
Hi @mosfetish, thanks for reporting I will verify and get back to you.

**Comment by rangav** [comment]
Hi @mosfetish one question did you include full url including http prefix?

**Comment by rangav** [comment]
Hi @mosfetish do you still have this problem?

**Comment by mosfetish** [comment]
Issue appears resolved. I can access local .test domains.

Thanks, rangav

**Comment by rangav** [comment]
Thanks @mosfetish for confirmation 👍
