### ISSUE TITLE
Respect Editor Panel Location for selecting requests from collections or activity

### ISSUE THREAD

**Issue by bayoumymac** [rangav/thunder-client-support#188]
**Is your feature request related to a problem? Please describe.**

This similar to the request in #115 but for requests selected from collections or activity tab, Its really useful to be able
to have 2 or more different requests right beside each other that weren't new requests for comparison and copy/pasting

**Describe the solution you'd like**

Respect Editor Panel Location for selecting requests from collections or activity

**Comment by rangav** [comment]
Hi @bayoumymac you want open 2 requests in 2 tabs right?

double on the first request gets detached 
So click on the another  request to open in separate tab.

let me know if I understood your question correctly

**Comment by bayoumymac** [comment]
Hi @rangav, Thank you so much for the quick response and the great extension. 
I tried your solution and I can confirm it works, although slightly unintuitive it completely the job done.

If you agree about it being unintuitive, I will be happy to take a crack at it and simplify it to just open in active editor panel

**Comment by rangav** [comment]
Hi @bayoumymac is the requests not opening in active editor panel? Ref #115 

If you can share screenshots of its working now and how it supposed to work? To get better understanding of the problem

**Comment by rangav** [comment]
You can open request in new tab in 2 ways
`Open in New Tab` menu option
`Ctrl/Cmd + Click` on request will open in new tab

I am closing this issue, feel free to re-open if needed.
