### ISSUE TITLE
Environment is not visible in "Env" tab after first import

### ISSUE THREAD

**Issue by kamaruzzamanzuel** [rangav/thunder-client-support#189]
**Describe the bug**

When imported environment from .json file which was exported previously from Thunder Client or postman, it is imported successfully but not displaying under the "Env" tab. When I close vscode and reopen, then I can see that environment under the "Env" tab.

**To Reproduce**

vscode>Thunder Client>Env>Menu>Import>Select an exported environment json file>no environment under "Env" tab.
colse vscode>reopen vscode>Thunder Client>>Env>new environment can be found.

**Expected behavior**

The environment should have listed under the "Env" tab as soon as it is imported. No need to reopen.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.56.2
 - extension version: 1.4.0

![capture_20210608_124611_533](https://user-images.githubusercontent.com/10472602/121136656-b63b9480-c857-11eb-939f-ddb3f96e2c5c.gif)

**Comment by rangav** [comment]
Hi @kamaruzzamanzuel thanks for reporting, will verify and fix in the next update.

**Comment by rangav** [comment]
Hi @kamaruzzamanzuel the bug is fixed in v1.4.1

**Comment by kamaruzzamanzuel** [comment]
Thanks.
You guys are doing great.
Keep it up!!!
👍
