### ISSUE TITLE
(feature) Use current folder/workspace to load/save Request

### ISSUE THREAD

**Issue by Leccho** [rangav/thunder-client-support#19]
**Is your feature request related to a problem? Please describe.**
You cannot share easily when working in team. You have to export and import every time there's a change. It becomes less practical.

**Describe the solution you'd like**
You could create a collection related to folder/workspace. This would create a file in the current folder/workspace (allow to change location in settings). When you open a folder/workspace, it would look to find that file automatically and display it in the collections. When editing that collection, it would save automatically in the file.

**Comment by rangav** [comment]
Hi @Leccho integration with git using custom storage location is planned for next version, this is useful to sync requests across devices and data is under your control, This is already suggested by users in #2 , #9, #10, #15 

See planned features for v1.1.0 - #14
