### ISSUE TITLE
preview sends 2nd request with empty body instead of rendering 1st response

### ISSUE THREAD

**Issue by charonme** [rangav/thunder-client-support#190]
assuming the "preview" feature is supposed to render the html in the response, I'd expect it to just render the html in the already received response, but instead it appears to perform a 2nd request, but this time with an empty body

To reproduce POST some json data in the body of the request (to a server returning different html for an empty bodied request) and then click on the "preview" link/button at the bottom of the response view pane. The rendered HTML will be of an empty bodied request instead of the expected render of the first response. Also the background will not be rendered, instead the windows 10 theme background will be used (but that's a different bug)

ver.1.4.0

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0

Let me know your feedback
