### ISSUE TITLE
OAuth2 Token Caching?

### ISSUE THREAD

**Issue by gcalabro-rli** [rangav/thunder-client-support#191]
**Describe the bug**
The authorization header seems to be cached across all requests when trying to interact with different Authorization Servers.

**To Reproduce**
I create a new request A with OAuth settings for Authorization Server A.
The token is generated successfully. Verified a jwt.io that it has the correct Authorization Server A data.
Send request; successful.

I create a new request B with OAuth settings for Authorization Server B.
The token is generated successfully. Verified a jwt.io that it has the correct Authorization Server B data.
Send request; not successful. The Bearer token sent in the Authorization Header is that of Authorization Server **A** rather than **B**.

**Expected behavior**
For request A, send Authorization Header with Bearer token generated by Auth Server A
For request B, send Authorization Header with Bearer token generate by Auth Server B

**Platform:** 
 - OS:  MacOS
 - vscode version: 1.56.2
 - extension version: 1.4.1

**Comment by rangav** [comment]
Hi @gcalabro-rli thanks for reporting. The request will take access token from auth tab when you send a request. I will verify and get back to you.

**Comment by gcalabro-rli** [comment]
> Hi @gcalabro-rli thanks for reporting. The request will take access token from auth tab when you send a request. I will verify and get back to you.

Thank you, that is what I thought. Then I was like am I doing something wrong? But it consistently happens at least for me. Thanks for looking into this, I love this tool and I am trying to drop postman for this!

**Comment by rangav** [comment]
One question -  close all requests tabs and open those 2 requests with different auths and see the access tokens in auth tab are different?

**Comment by rangav** [comment]
One more Test - just test the 2nd auth request separately and check it’s working or not?

**Comment by gcalabro-rli** [comment]
So closing all the tabs worked. 
I created a new Request for Auth Server B and it sent the token generated by Auth Server B. 

Then in that same tab, I changed the values to Auth Server A and regenerated the token. It sent the token for Auth Server A as expected. 

Then I changed the values to Auth Server B (in that same tab again) and regenerated the token, it sent the token for Auth Server A instead of the new token for Auth Server B.

**Comment by rangav** [comment]
Thanks @gcalabro-rli now I understood how to re-produce the steps, I will verify them again and confirm.

I guess if you run them in 2 separate tabs they are working right?

**Comment by gcalabro-rli** [comment]
Close all tabs...

Create a new tab for Auth Server B and it sent the token generated by Auth Server B
Create another new tab for Auth Server A and it sent the token generated by Auth Server A

Flip to the Auth Server B tab and it sent the token generated by Auth Server A rather than B

**Comment by rangav** [comment]
What is your auth servers? Is it internal

for reproducing the error for my testing

**Comment by gcalabro-rli** [comment]
I am using two Okta auth servers

**Comment by rangav** [comment]
Thanks I will verify and get back to you

**Comment by rangav** [comment]
Closing this issue, feel free to re-open if needed
