### ISSUE TITLE
dd function of laravel is not working in HTML Preview Mode

### ISSUE THREAD

**Issue by tolgaberk** [rangav/thunder-client-support#192]
Hi, first of all thank you for your excellent job on making this extension a reality.

To my issue,
Laravel is a php framework and i develop some rest apis with it and it has a function called dd. this function allows you to display contents of a variable by returning an html with a script tag in it. with this script tag, it constructs a page in a tree form representing the contents of the variable.

![image](https://user-images.githubusercontent.com/32398085/121315732-4be72a80-c911-11eb-9c35-1aad0a5d1bd5.png)

it declares a function to build everything in this tag and then 

![image](https://user-images.githubusercontent.com/32398085/121315883-6faa7080-c911-11eb-9399-839094c2a478.png)

it executes it like this.

but for some reason this returned script tags is not executed(in my opinion) when i try to preview it hence i cannot see what the variable holds.

it just shows a blank screen like this
![image](https://user-images.githubusercontent.com/32398085/121316043-95d01080-c911-11eb-924b-5bd6645a2eae.png)

Again thanks for your hard work. i look forward to see this extension grows a lot.

**Comment by rangav** [comment]
Hi @tolgaberk, thanks for support.

Is there any public url for me to test and identify the issue.

There was a similar issue #190 see if this has similar problem.

**Comment by tolgaberk** [comment]
I don't think there is relevance between my issue and #190.

also i prepared a quick test url for you

https://pubengine.saveas.com.tr/api/dd

you can use this url to test dd response rendering.
but i can't guarantee that this link will not die in a few days 😄 

Thanks.

**Comment by rangav** [comment]
Thanks @tolgaberk very fast to create public url, will test later today and get back to you.

**Comment by rangav** [comment]
Hi @tolgaberk i can see some response, let me know if thats right

<img width="929" alt="Screenshot 2021-06-09 at 10 58 00" src="https://user-images.githubusercontent.com/8637550/121334542-a7191d00-c911-11eb-9777-b20630161cae.png">

**Comment by tolgaberk** [comment]
@rangav thanks for your really quick responses.

This is really weird if i use env variables like this:
![image](https://user-images.githubusercontent.com/32398085/121374704-c8493000-c948-11eb-8b1d-ec22094c947e.png)
it just prints nothing.

but if i use whole url it works :

![image](https://user-images.githubusercontent.com/32398085/121374816-e3b43b00-c948-11eb-9241-95867869660f.png)

i think it's something about those env variables.

**Comment by rangav** [comment]
Yeah could be a bug, I will verify with env and confirm.

**Comment by rangav** [comment]
I can confirm its a bug, will fix it in the next update.

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0

Let me know your feedback

**Comment by tolgaberk** [comment]
YES! 
It works perfectly. 
Thank you so much.

**Comment by rangav** [comment]
Thanks for confirmation 👍
