### ISSUE TITLE
can't apply string response to ENV

### ISSUE THREAD

**Issue by dodiwknd** [rangav/thunder-client-support#193]
if the response returns a string (not an object), performing the implementation on ENV is not executed

I hope this can be done, or there is an editor like po***an to extract the contents of the response for implementation

![image](https://user-images.githubusercontent.com/82150448/121332099-b7e18700-c941-11eb-9a3e-47a6880ebdc4.png)

**Comment by rangav** [comment]
hi @dodiwknd if its a text response, you need use `text` keyword in the left input box,

see documentation.
https://github.com/rangav/thunder-client-support#testing

**Comment by dodicandra** [comment]
hi @rangav thankyou for the response. even though i fill with text key on input, it's still the same

![image](https://user-images.githubusercontent.com/48325708/121774416-92a48100-cbac-11eb-95aa-04341ae56952.png)


![image](https://user-images.githubusercontent.com/48325708/121774450-a8b24180-cbac-11eb-8635-b104e925e1d3.png)

**Comment by rangav** [comment]
Oh ok may be there is issue with double quotes, I will verify and fix it.

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0
