### ISSUE TITLE
Getting 404 Not Found for all requests. Same request works within Postman

### ISSUE THREAD

**Issue by martylavender** [rangav/thunder-client-support#195]
**Describe the bug**
No matter what request I run within Thunder Client, the return response is 404 Not Found. If I run these same requests in Postman, they succeed. Additionally, manually piecing the request URL together and pasting in a browser works as well.

**To Reproduce**
Create a new request. 
Execute request

**Expected behavior**
Request should return valid data

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.4.1
 - extension version: 1.56.2

**Solution:**
None as of yet. This has never been an issue.

**Comment by martylavender** [comment]
We can close this one out. I had my request set to GET rather than POST. I didnt not realize that could result in a 404 Not Found error.

**Comment by rangav** [comment]
No problem @martylavender sometime it happens :)
