### ISSUE TITLE
Environment variables dont accept strings

### ISSUE THREAD

**Issue by Yazington** [rangav/thunder-client-support#196]
**Describe the bug**
I tried to do a simple: 
email : "test@gmail.com", it erases it after save ...
so tried removing the "" and used the variable like so {{#email}}, but it doesn't work. It only works if I directly put the email in the body of my request

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Hi @Yazington the environment variable syntax is `{{email}}`

dynamic variable syntax is `{{#randonEmail}}`

both are different.

**Comment by Yazington** [comment]
> Hi @Yazington the environment variable syntax is `{{email}}`
> 
> dynamic variables syntax is `{{#randonEmail}}`
> 
> both are different.

The problem is before even accessing these variables. When setting them in the beginning, if I put for example "test@gmail.com" instead of test@gmail.com, it erases the value after saving. Is this the intended behaviour? I need the quotes.

**Comment by rangav** [comment]
I think you need use “{{email}}”  for quotes. You save only email in env and use variable in quotes

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
