### ISSUE TITLE
Availability for Codium

### ISSUE THREAD

**Issue by london-coder** [rangav/thunder-client-support#197]
Hi
Lots of great reviews for your product, thanks for taking the time to create it. But, do you have any plan when (or if), the plug-in will be available for Codium?

**Comment by rangav** [comment]
Hi @london-coder 
Please see comments here https://github.com/rangav/thunder-client-support/issues/30

**Comment by london-coder** [comment]
> Hi @london-coder
> Please see comments here #30

Thank you. Sorry I missed the previous discussion. I wish continued success for your project.

**Comment by rangav** [comment]
Thanks @london-coder for the support 👍
