### ISSUE TITLE
Content Type Images are Shown In Binary Format and is Not Processed!

### ISSUE THREAD

**Issue by nimpossible** [rangav/thunder-client-support#198]
**Bug Description:**
With an ExpressJS Server, when `sendFile()` is called, although Headers (especially, `content-type`) are properly set, the image is not rendered in the output, but Binary data.

The same will work when checked with other agents like Postman, Insomnia, etc.

**Platform:** 
 - OS: `Windows 10 Home Edition (Licenced) - Windows_NT x64 10.0.19043`
 - vscode version: `1.57.0`
 - extension version: `1.4.1`

**Supporting Images:**

![image](https://user-images.githubusercontent.com/16114850/121798579-ce8b2500-cc44-11eb-900c-fd0d581ab1f7.png)

Automatically Set Headers:

![image](https://user-images.githubusercontent.com/16114850/121798638-1c079200-cc45-11eb-9df5-19795a5afb67.png)

**Comment by rangav** [comment]
Hi @nimpossible related issue to #97 

will implement this feature in next update
