### ISSUE TITLE
500 Internal Server Error - NO-BREAK SPACE Issue

### ISSUE THREAD

**Issue by dimbslmh** [rangav/thunder-client-support#199]
**Describe the bug**
I'm getting 500 Internal Server Error for a request I make using this extension. 
The requests works fine with Postman.

**To Reproduce**
I have no idea what is causing this, but this is what's currently configured:
- 1 Env with a jwt token
- 1 Collection with 10 requests, 9/10 works.

All the requests in the collection need authentication with jwt. 
Mine is setup from Headers with Bearer {{auth}}.
Tested in "Normal" window and "Remote - WSL" window.

Things I have tried, but don't work:
- New Request (Even replicating working request in my Collection)
- Deleting Collection
- Clearing Activity
- Remove `"rangav.vscode-thunder-client": ["ui"]` from `settings.json`

**Expected behavior**
Successful request. 

**Platform:** 
 - OS: Windows using WSL2
 - vscode version: 1.57.0
 - extension version: 1.4.1

**Comment by rangav** [comment]
Hi @dimbslmh thanks for reporting, did you set content type header?

Can you share your headers tab screenshot?

**Comment by dimbslmh** [comment]
Here is my headers tab @rangav.

![image](https://user-images.githubusercontent.com/745635/121847250-7ae70d00-cd12-11eb-9dc1-e20127f2c66d.png)

The backend does not allow GET requests.

OOT. I wanted to debug this myself, but there are no additional Output logging (`Ctrl+Shift+U`) for this extension and also nothing showing up in the Developer Tools (`Ctrl+Shift+I`).

**Comment by rangav** [comment]
can you remove content-type header and send the request.

**Comment by dimbslmh** [comment]
1st Test
![image](https://user-images.githubusercontent.com/745635/121853614-50e61880-cd1b-11eb-8509-6f294480f9fb.png)

2nd Test
![image](https://user-images.githubusercontent.com/745635/121853732-7c690300-cd1b-11eb-872f-b0c207e956be.png)

3rd Test Without Cache-Control
![image](https://user-images.githubusercontent.com/745635/121854422-54c66a80-cd1c-11eb-9a4b-738811e2fe8f.png)


Request in Postman with X-Authorization Header
![image](https://user-images.githubusercontent.com/745635/121854128-f4372d80-cd1b-11eb-857d-20f29b5ca8bd.png)

**Comment by rangav** [comment]
In postman request - after Bearer keyword there is no token?

**Comment by dimbslmh** [comment]
Btw. I've debugging enabled for my backend code. So, when I send a request from Postman or from a working saved collection request from Thunder Client, it will trigger my breakpoints. 
But when I get the 500 Internal Error, the request does not even reach the backend code.

> In postman request - after Bearer keyword there is no token?
It's removed in the image, but there is a token used in the client. (the same jwt in the env of Thunder Client)

**Comment by dimbslmh** [comment]
Here is a screenshot of a request I saved to the Collection that is still working.
![image](https://user-images.githubusercontent.com/745635/121858056-6c9fed80-cd20-11eb-8da4-753de17cf88e.png)


But If I replicate this as a New Request, it will fail with 500 Internal Server Error
![image](https://user-images.githubusercontent.com/745635/121857783-28ace880-cd20-11eb-802c-8c49103bdd3d.png)

**Comment by rangav** [comment]
thats very strange bug that its working from collection and not from new request.

Can you check the **body** content are same?

can you save the request created from new request to a collection and try it?

**Comment by dimbslmh** [comment]
Yeah, the body and Headers are the same. Copy pasted the values over to the New Request.

I'll try to make a short screencast so you can see.

Btw. I tried exporting my Collection and Env. Uninstalled the extension, closed vscode and then reinstalled the extension. Imported the Collection and Env I saved. And tried the previous tests, but the same issue is still there.

**Comment by dimbslmh** [comment]
https://user-images.githubusercontent.com/745635/121874109-40409d00-cd31-11eb-9bcb-272e66d0c8fc.mp4

**Comment by rangav** [comment]
Thanks @dimbslmh for the video, I will test and see if i can re-produce the issue.

**Comment by dimbslmh** [comment]
No problem @rangav. By the way, can debugging be enabled for this extension, like at the Output Log or Developer Tools?

**Comment by rangav** [comment]
you can also test and see what data is sent to server using this url https://httpbin.org/anything
you can see any dummy token value dont use original and you can compare


<img width="1172" alt="Screenshot 2021-06-14 at 11 06 20" src="https://user-images.githubusercontent.com/8637550/121875638-96e1b300-cd00-11eb-8fef-396d7169c127.png">

**Comment by rangav** [comment]
I will verify further and get back to you

**Comment by dimbslmh** [comment]
> it is sending **the dot** after Bearer keyword

Nice find! For some reason the space turns into a NO-BREAK SPACE [NBSP].

Type in "Bearer " and then type in the {{variable}} (it turns green). < Works
Type in "Bearer " and then copy paste {{variable}} (was already green when copied). < Fails, because of NBSP
Type in "Bearer " and then the {{variable}}, remove and add space before variable. < Fails, because of NBSP

You can try adding more spaces in between, not all of them turn into a NBSP.

**Comment by rangav** [comment]
Hi all, this bug is fixed now, will part of next update v1.7.0

**Comment by rangav** [comment]
This is now fixed in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0
