### ISSUE TITLE
Usability feedback

### ISSUE THREAD

**Issue by pikant** [rangav/thunder-client-support#2]
First of all, thanks a lot for your great extension! Exactly what I have looked for over the past month.

Since I could not find any specific contribution guidelines, please find some usability feedback below:

- It would be great to have a `Thunder Client: Send Request` command that one could fire from `command+shift+p`.
- Furthermore, it would be great to have a `Thunder Client: Re-run Last Request` command.
- It would be important to have the option to store the collections also within the current project directory. This would enable teams to share their requests via git.

**Comment by rangav** [comment]
Hi @pikant  thanks for feedback. This project is just getting started, any suggestions to improve documentation or features always welcome.

Here are my replies
* You can `cmd+shf+p` and type thunder or new request you will see option - `Thunder Client: New Request`
* Sure I can add option to the command list for Re-run last request, will add to my next feature list.
* This is good idea - Currently collections and env data are stored in [globalStorageUri](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalStorageUri), I can include option to customize storage path in settings.

**Comment by pikant** [comment]
Thanks for you quick reply!

> * You can `cmd+shf+p` and type thunder or new request you will see option - `Thunder Client: New Request`

Yes, I already saw this functionality. However, when you are in the view, where you can edit the current request, there is currently no command or hotkey to fire the current request.

In postman, you can simple hit `command+enter` to send the request. Hope that clarifies the desired behavior.

**Comment by rangav** [comment]
I will add that to the list.

**Comment by rangav** [comment]
Hi @pikant  Cmd+Enter to execute the request is now implemented, please update to v1.0.6

https://marketplace.visualstudio.com/items/rangav.vscode-thunder-client/changelog

**Comment by rangav** [comment]
v1.1.0 is now published
