### ISSUE TITLE
FIle upload sysytem

### ISSUE THREAD

**Issue by Tasen-pro** [rangav/thunder-client-support#20]
The sysytem of uploading file is still not implemented

**Comment by rangav** [comment]
Hi @Tasen-pro i will add this feature to product roadmap.

**Comment by rangav** [comment]
This is now implemented in v1.2.0, please update. 

Release details here 
https://github.com/rangav/thunder-client-support/releases/tag/1.2.0

**Comment by rangav** [comment]
i have to change the implementation to support field name option for file upload

**Comment by LuizAntonioPS** [comment]
@rangav In the POST body, can we only upload files OR text in the same request? Thanks.

**Comment by rangav** [comment]
Hi @LuizAntonioPS I am changing to allow both types can be sent in the same request.

**Comment by Eizeiky777** [comment]
> Hi @LuizAntonioPS I am changing to allow both types can be sent in the same request. will publish a new update in 1 or 2 days

thanks, I hope the upload files are the same as in Postman, there are key name of file and value of file itself

**Comment by rangav** [comment]
Yes they will have field name and file value

**Comment by rangav** [comment]
This feature is released in v1.2.1 for details https://github.com/rangav/thunder-client-support/releases/tag/1.2.1
