### ISSUE TITLE
Environments can no longer be used if a variable contains special characters

### ISSUE THREAD

**Issue by dlucazeau** [rangav/thunder-client-support#201]
**Describe the bug**
If a variable contains special characters (? AYntMVu *% 'u $ vpNL |. | 2 &: r), the environment no longer displays anything. The variables still exist because we can use them and see them in the exported file, but we can no longer manipulate them

**To Reproduce**
Create a variable with the characters above

**Expected behavior**
That the environments are manageable regardless of the content of the variables

**Platform:** 
 - OS: Windows 10

 - vscode version (1) : Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

 - vscode version (1) : Version: 1.58.0-insider (user setup)
Commit: e1161be26874f0d39a5b9cdeb2c5fbfd4f83bb80
Date: 2021-06-14T05:13:55.029Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

 - extension version: 1.4.1

**Solution:**

**Comment by rangav** [comment]
Thanks @dlucazeau for reporting, I will verify and fix it.

Are you using the above special chars in the variable name or value?

**Comment by dlucazeau** [comment]
Yes I use this string as a value

**Comment by rangav** [comment]
Ok thanks - will fix it in the next update.

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0
