### ISSUE TITLE
executable file

### ISSUE THREAD

**Issue by mishra5047** [rangav/thunder-client-support#202]
Kindly create an executable file, so that we can use it as we use postman.Also kindly create a extension for android studio.

**Comment by rangav** [comment]
Hi @mishra5047 thanks for the suggestion, currently not in the roadmap, but will review again at later stage.

**Comment by mishra5047** [comment]
Guys let me know if you need any help in the same, maybe I can be of some use. And would love to contribute to this amazing project.

**Comment by rangav** [comment]
Hey @mishra5047 as I said earlier, Currently no plans to do any executable or extension for other tools.

**Comment by rangav** [comment]
But if you want to contribute to others like **Code Snippet generation** and **Open API import**, let me know
