### ISSUE TITLE
Multiple tabs for each api under collection 

### ISSUE THREAD

**Issue by VpkPrasanna** [rangav/thunder-client-support#203]
Problem 

Suppose i have multiple api in a collection , it only shows one api in VS code ?
Is there any way to see both api in two seperate tab 

**![Screenshot from 2021-06-17 12-21-26](https://user-images.githubusercontent.com/30804112/122346476-9fd3be00-cf66-11eb-9587-eb07f5e6a796.png)**

**Expected**
Two Endpoint in two different Tab's

**Comment by rangav** [comment]
Hi @VpkPrasanna 

double click on first api request 
And then click on 2nd api request 

same way as vscode opens files

**Comment by VpkPrasanna** [comment]
> Hi @VpkPrasanna
> 
> double click on first api request
> And then click on 2nd api request
> 
> same way as vscode opens files

Hey @rangav Thanks. It work's thanks, FYI But if i double click on any of the request it again opens in new tab as the same request is opened already.

**Comment by rangav** [comment]
Can you share a screenshot of the other problem which requests you are opening

**Comment by VpkPrasanna** [comment]
> Can you share a screenshot of the other problem which requests you are opening

Here is the screenshot for the issue which i mentioned above
![Screenshot from 2021-06-17 12-38-10](https://user-images.githubusercontent.com/30804112/122348899-44ef9600-cf69-11eb-9378-79523d27c75a.png)

**Comment by rangav** [comment]
Ok got it, will verify and fix it. Thanks

**Comment by rangav** [comment]
Hi @VpkPrasanna I made improvements for opening in new tab and also fixed others issues that you mentioned.

will be part of next update.

**Comment by VpkPrasanna** [comment]
> Hi @VpkPrasanna I made improvements for opening in new tab and also fixed others issues that you mentioned.
> 
> will be part of next update.
Yeah sure, Thanks and waiting for the update to get released.

**Comment by rangav** [comment]
This feature is now implemented in v1.8.0

You can do in 2 ways

- `Open in New Tab` menu option
- `Ctrl/Cmd + Click `on request will open in new tab


see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
