### ISSUE TITLE
Remove request URL placeholder and add tiny copy and paste button for URL

### ISSUE THREAD

**Issue by shohagkhan** [rangav/thunder-client-support#204]
Every time I need to press ctrl + A to select the request URL placeholder, that's really boring.
Please remove this placeholder and add tiny **URL copy and paste button** on top of request URL input box, so that we can easily copy the URL and paste it to other request.
Also, you can make JSON content option default in Body, cuz  we use this feature most of the time.
At last, thanks for making this awesome extension.
![image](https://user-images.githubusercontent.com/16593128/122355901-1a570a80-cf74-11eb-8665-3428439daa38.png)

**Comment by rangav** [comment]
Hi @shohagkhan thanks for suggestions

**Comment by rangav** [comment]
Json tab is now default tab. moved to first position.

**Comment by rangav** [comment]
Default Url is removed if you create request from collection tab in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
