### ISSUE TITLE
Prohibited for use in development of "commercial" software

### ISSUE THREAD

**Issue by seversol** [rangav/thunder-client-support#206]
I was looking at the Licesne.txt file included in the repo and it appears that this extension is not licensed for use in the development of "commercial" software. Is that correct?

•	RESTRICTIONS ON USE OF THE SOFTWARE
You are NOT permitted to: a) Edit, alter, modify, adapt, translate or otherwise change the whole or any part of the Software. b) Decompile, disassemble or reverse engineer the Software or attempt to do any such things. c) Reproduce, copy, distribute, resell **or otherwise use the whole or any part of the Software for any commercial purpose.** d) Disable, modify or hide notifications sent by the Software. e) Distribute, resell, or share Licence Keys. f) Access or use Premium Features without a valid Licence Key..

**Comment by rangav** [comment]
Hi @seversol, Let me double check. its the wording done by my legal guy.

**Comment by rangav** [comment]
You can use for development of commercial software. I think it is talking about using `Thunder Client code `in your commercial software. not for using it.

if its not clear, let me know i will ask my legal guy to update the wording properly.

**Comment by seversol** [comment]
Thank you for the clarification. As it's currently worded I don't think our legal department is going to allow us to use it. I do appreciate your work.

**Comment by rangav** [comment]
I have asked my legal guy to review that point again. 

let me know the response from your legal team, so i can forward those points to him also.

**Comment by rangav** [comment]
Hi @seversol 

The wording is now changed to avoid confusing. 

**from**
`or otherwise use the whole or any part of the Software for any commercial purpose`

**to** 
`or otherwise use the whole or any part of the Software's Code for any commercial purpose`

**Comment by seversol** [comment]
Thank you for making the change. I'll re-submit to our legal department and see what they say. Either way, I appreciate your efforts both to make such a useful plugin and to make it as available as possible.

**Comment by rangav** [comment]
Hi @seversol i am closing this issue, feel free to re-open if needed
