### ISSUE TITLE
Changing ENV does not change variable value in collection

### ISSUE THREAD

**Issue by dmatis2** [rangav/thunder-client-support#207]
**Describe the bug**
I have multiple ENVs with the same variable name which I'm using in requests in a collection. Whenever I change active ENV, this change is not reflected when making the request as it returns the response from the previous ENV.

**To Reproduce**
- create multiple ENVs with the same variable name
- create a request using that variable
- make a request
- change ENV
- make that request again

**Expected behavior**
Request on correct address should be made.

**Platform:** 
 - OS: Ubuntu 20.04.2 LTS
 - vscode version: 1.57.0
 - extension version: v1.4.1

**Solution:**
-

**Comment by rangav** [comment]
Hi @dmatis2 thanks for reporting, I will verify and get back to you

**Comment by dmatis2** [comment]
Okay @rangav taking it back, it started working somehow now. Thanks for your effort anyway

**Comment by rangav** [comment]
no problem @dmatis2
