### ISSUE TITLE
Move the history into a separate file for shared repositories

### ISSUE THREAD

**Issue by exhuma** [rangav/thunder-client-support#208]
**Is your feature request related to a problem? Please describe.**

When sharing collections with the team, the JSON files are stored in the repository. Because the history is in the same file as other collections, it will always create diffs in version control.

Example:

* I check-out the project from git
* I open VS-Code and Thunder-Client
* I execute a request from the collection
* Result: A new entry is created in the history collection, causing a "diff" in `thunderCollection.db`
* A careless `git commit` will add the new history entry to the file and more than likely cause unnecessary conflicts

**Describe the solution you'd like**

The history collection should be kept in a separate file. This would make it possible to exclude it from version-control

**Describe alternatives you've considered**

A pre-commit task could clean out the history. But then every time a user commits, that user would lose the history. But at least it would keep git clean.

**Comment by rangav** [comment]
Hi @exhuma Thanks for the feedback.

One clarification, when you run a request from collection it wont create a entry in history, it will only update date modified for that request in collection. you can see the diff for this. 

Are you sure its creating new entry in history?

**Comment by exhuma** [comment]
I didn't notice this. I need to look more closely once I'm back in the office (I'm away for a few days).

But if what you're saying is true then this would *also* create a lot of unnecessary diffs when the collections are tracked. Information like this does not belong in shared repositories.

We're currently evaluating ThunderClient in our company for several teams for the exact reason that it would make sharing collections easier because they can be bundled with projects directly inside VS-Code. And because TC does not tempt employees to sync with the cloud. Which we want to avoid.

In my opinion, the *collections* should only contain *static* information which is independent from the different users. We already have environments which makes it possible to extract URLs and access-tokens from the shared data. Having #74 as well would be a REAL icing on the cake. The remaining "dynamic" data is the history (which request was exectuded when). And I don't believe this is important data to share between developers.

**Comment by rangav** [comment]
Thanks @exhuma for the feedback. you made very good points. I will include some of these in the next update.

**Comment by exhuma** [comment]
Sounds awesome. Thanks 👍

**Comment by rangav** [comment]
Import .env file is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

**Comment by rangav** [comment]
These feature are implemented in v1.8.0

- Separate activity requests into thunderActivity.db 
- Update request date only when content changes 

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

**Comment by rangav** [comment]
Hi @exhuma, any feedback did the features in v1.8.0 improve git merges?

**Comment by exhuma** [comment]
I'm currently working on another project and didn't have time to look into this yet. I'll give it a try as soon as I find some free time. This might me in the order of weeks/months though.
