### ISSUE TITLE
Search Bar Error VS code

### ISSUE THREAD

**Issue by yashrajbothra** [rangav/thunder-client-support#209]
VS Code Version: 1.57
OS Version: Mac OS 11.4

Steps to Reproduce:

1. Install Thunder Client Ext. (https://github.com/rangav/thunder-client-support)
2. Create New Request
3. Add Header Name
4. Open Search Bar and Paste anything

https://user-images.githubusercontent.com/47683556/122604335-6c428200-d093-11eb-8eff-f694bfbe4078.mov

**Comment by rangav** [comment]
Hi @yashrajbothra will verify and get back to you

**Comment by rangav** [comment]
I can re-produce the issue. i will check how to fix this.

**Comment by rangav** [comment]
This is vscode bug 
https://github.com/microsoft/vscode/issues/128118
https://github.com/microsoft/vscode/issues/127881

**Comment by rangav** [comment]
This is now fixed in vscode new release `v1.59.0`
