### ISSUE TITLE
Modifying a saved request in a collection generates a new request and discards the changes in the existing one

### ISSUE THREAD

**Issue by davidfilat** [rangav/thunder-client-support#21]
**Describe the bug**
A dublicate request is created whenever I modify a request saved in a collection.

**To Reproduce**
1. Make a request and save it to a collection.
2. Changer a parameter in the request query.
3. A new unnamed request will appear in the collection, but the changes will be reverted in the saved request.

**Expected behaviour**
The modifications to an existing request in a collection should be saved and there is no need to create a dublicate request in the collection.

**Platform:** 
 - Thunder Client: v1.0.7
 - OS: Mac OS
 - VS Code: Version: 1.55.2 (Universal)
 - Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
 - Date: 2021-04-13T09:36:32.643Z
 - Electron: 11.3.0
 - Chrome: 87.0.4280.141
 - Node.js: 12.18.3
 - V8: 8.7.220.31-electron.0
 - OS: Darwin x64 20.3.0

**Comment by rangav** [comment]
Hi @davidfilat is the duplicate request is created in activity tab or collection tab?

**Comment by davidfilat** [comment]
> Hi @davidfilat is the duplicate request is created in activity tab or collection tab? 

In the collection tab.

**Comment by rangav** [comment]
ok i will check and see if i can reproduce it

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14

**Comment by davidfilat** [comment]
Thank you! It works fine now
