### ISSUE TITLE
redered page for html responses

### ISSUE THREAD

**Issue by ProgrammingPlanet** [rangav/thunder-client-support#211]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Like response tab, there must be a tab for viewing the html pages like there is in postman.

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @ProgrammingPlanet the html preview button is at the bottom

<img width="916" alt="Screenshot 2021-06-19 at 13 12 36" src="https://user-images.githubusercontent.com/8637550/122641930-2079f200-d100-11eb-9bea-e1adee66ec2a.png">

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
