### ISSUE TITLE
Pre-request script

### ISSUE THREAD

**Issue by pathakvivek7865** [rangav/thunder-client-support#212]
I have a project where i want to add "x-api-key" header to every request.
I have used postman's pre-request-script feature for all request in the collection.
But I couldn't see such feature in Thunder-client.
So I request to show me how to do it, if it isn't present I would love to have such feature in future.
Thank You.

**Comment by rangav** [comment]
Hi @pathakvivek7865 thanks for the request.

Its already in roadmap. see existing issue here #16

Can you add your comments in the existing issue, so we can track in one place.
