### ISSUE TITLE
How to switch between staging and live env ?

### ISSUE THREAD

**Issue by Akashdeep312** [rangav/thunder-client-support#214]
**Is your feature request related to a problem? Please describe.**
While working with two env for production and testing how to switch between envs ?

**Describe the solution you'd like**
There should be an option to mark an env active so that all request take token and apis kyes from the active env

**Describe alternatives you've considered**
Tires postman for this

**Comment by rangav** [comment]
Hi @Akashdeep312 click on option icon `…` on the Env and click `Set Default` Option

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed

**Comment by Akashdeep312** [comment]
![image](https://user-images.githubusercontent.com/48234644/123364508-23f2fa80-d592-11eb-968f-78082f5e671a.png)


it's does not have any set default option @rangav

**Comment by rangav** [comment]
FYI - `Set Default` option renamed to `Set Active` in v1.5.0
