### ISSUE TITLE
Environment variable replacing not working with certain special characters

### ISSUE THREAD

**Issue by JorgIanFloren** [rangav/thunder-client-support#215]
**Describe the bug**
When using strong passwords as client_secret, the sent request gets corrupted and doesn't work as intended.

**To Reproduce**
Using Form-Encoded parameter with values like:
"X?Y8Gr\Y-G%x86*\"
"xX{SH@r3%3k}7d;#"

**Expected behavior**
The value should correctly be injected in the request

**Platform:** 
 - OS: Win10
 - vscode version: 1.57.0
 - extension version: 1.4.1

**Comment by rangav** [comment]
Hi @JorgIanFloren thanks for reporting i will verify and get back to you.

related issue #201

**Comment by rangav** [comment]
This is now fixed in v1.5.0
https://github.com/rangav/thunder-client-support/releases/tag/1.5.0
