### ISSUE TITLE
Automatically Refresh token

### ISSUE THREAD

**Issue by saymondamasio** [rangav/thunder-client-support#216]
I would like to suggest a very useful function that has in insominia which is refresh token, it updates the token automatically

**Comment by rangav** [comment]
Hi @saymondamasio thanks for the suggestion. Will add to list.
also related to https://github.com/rangav/thunder-client-support/issues/33#issuecomment-838837117

**Comment by omasseau** [comment]
That would be a great feature indeed.
Here our tokens last only 5 minutes.

**Comment by rangav** [comment]
Hi All,

Our next update will include this feature, planning to release this week.

this feature will be more advanced than insomnia and other clients.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by kvart714** [comment]
in which case the token will be automatically refreshed?

**Comment by rangav** [comment]
@kvart714 when the token expires, the extension will automatically refresh and fetch new token.

**Comment by kvart714** [comment]
@rangav understood: we use `grant_type=client_credentials` for auth and I store Client ID and Client Secret in extension, but after token expiration the extension is requesting a new token with `grant_type=refresh_token`
we don't support refresh_token for grant type and token aren't refreshed

**Comment by rangav** [comment]
@kvart714 there is a bug, will fix in next few hours.

**Comment by rangav** [comment]
@kvart714  This bug is fixed now, Please update to` v1.19.5`

**Comment by kvart714** [comment]
works perfect! 🎉
Thx, very much 🤝

**Comment by rangav** [comment]
@kvart714 super, thanks for confirmation 👍
