### ISSUE TITLE
Add System Variable {{#guid}} to produce a guid

### ISSUE THREAD

**Issue by reganheath** [rangav/thunder-client-support#218]
Something I use regularly in RESTClient plugin is {{$guid}} to add an RFC 4122 v4 UUID to my requests.
I would {{#guid}} added as a System Variable.

**Comment by rangav** [comment]
Hi @reganheath its already supported

details here
https://github.com/rangav/thunder-client-support#variables

**Comment by reganheath** [comment]
Wow.  ok.  Sorry.  I guess I read "string" and didn't continue reading that line :P
