### ISSUE TITLE
Error "Couldn't resolve the hostname to an IP address, Please check the Url" - need more details

### ISSUE THREAD

**Issue by reganheath** [rangav/thunder-client-support#219]
I have a request which uses environment variables to build the url (is this supported?).

In fact, it uses environment variables to build other environment variables (is this supported?).

I make the request and get:

Status: ERROR, Size: 0 B, Time: 0 ms
Couldn't resolve the hostname to an IP address, Please check the Url

From this.. I do not know how to debug it.  I cannot tell what hostname it was attempting to resolve (and thus whether my variables are being replaced, or not, and if so what with, etc)

I would like it to tell me the host name it tried.

The full url would be fine.

An output pane at the bottom would be ideal, with debugging of each action it took, etc.

**Comment by rangav** [comment]
Hi @reganheath thanks for reporting

try to test the full url directly without env and see if its working or not.

**Comment by reganheath** [comment]
Hi @rangav.  Yes, it works when I type the url with no env replacement.

Example url: {{scheme}}://{{host}}{{prefix}}/verify/{{platform}}
Example env:
- scheme = http
- name = test
- domain = domain.com
- host = {{name}}.{{domain}}
- prefix = /test
- platform = fake

**Comment by peeyar** [comment]
I have the same issue. I am not even able to see the default url '(GET) www.thunderclient.io/welcome' . In the same machine , rest-client is working fine with out any issues.

**Comment by rangav** [comment]
Hi guys, the resolved url is now displayed in error message in v1.5.0

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.

**Comment by rangav** [comment]
Hi all, the executed url is now displayed in output window in v1.9.0
