### ISSUE TITLE
Pre-request Script like postman

### ISSUE THREAD

**Issue by nhatquang-sl** [rangav/thunder-client-support#22]
**Is your feature request related to a problem? Please describe.**
For some APIs system, they request hash the ApiKey with the user token. 
So I need to build a script to build some variables before sending a request.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @nhatquang-sl this is duplicate request of #16, so i will close this one.
