### ISSUE TITLE
Preview request and/or view {{variable}} replacement via mouse over

### ISSUE THREAD

**Issue by reganheath** [rangav/thunder-client-support#220]
I would like to be able to preview the request, including url, headers, and body.  

Would be nice if this preview could be syntax checked in the case of json/xml.

Additionally, I would like to be able to preview variable replacement by mousing over the variable replacement token e.g. "{{name}}" in the url, headers, body, etc

**Comment by rangav** [comment]
duplicate of #184

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
