### ISSUE TITLE
Import from OpenAPI 3.0 / Swagger

### ISSUE THREAD

**Issue by reganheath** [rangav/thunder-client-support#223]
Our services publish their request schema using a OpenAPI 3.0 json schema document.  It would be amazing if I could import from this, creating collections and requests with placeholder values.

I could then, trivially, duplicate and edit these requests for each specific test case I need, creating a complete test suite.

It would certainly beat importing them all by hand.

**Comment by rangav** [comment]
Hi @reganheath this is in the roadmap, not yet prioritised.

The library is available separately, open for contribution 
https://github.com/rangav/thunder-imports

**Comment by reganheath** [comment]
My TypeScript is non-existent, sorry.

**Comment by rangav** [comment]
duplicate of #84
