### ISSUE TITLE
Can't use environment variable in Authentication token

### ISSUE THREAD

**Issue by uniyalnitin** [rangav/thunder-client-support#224]
**Describe the bug**
Cannot use the environment in authentication

**To Reproduce**
refer to screenshot

**Expected behavior**
should produce the value from environment variable

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**
see how postman does it

![Screenshot from 2021-06-24 11-16-45](https://user-images.githubusercontent.com/41964956/123209184-e2087c80-d4dd-11eb-8205-3dfb78f19d23.png)

**Comment by rangav** [comment]
Hi @uniyalnitin the **`{{auth_token}}`** variable did not turn green? did you create the variable in env? and also verify variable casing.

**Comment by uniyalnitin** [comment]
It is working now. Actually I have two different environment setup. There is no way to tell which environment is currently active without actually clicking the Env tab. It will be better if you can show it somewhere. For reference I have attached the screenshot
![suggestionpng](https://user-images.githubusercontent.com/41964956/123211367-02860600-d4e1-11eb-9d3e-655191196717.png)

**Comment by rangav** [comment]
Thanks for feedback, will review where to display current selected Env.
