### ISSUE TITLE
Support for OAuth2.0 token generation from Auth servers with self signed certificates

### ISSUE THREAD

**Issue by ghokun** [rangav/thunder-client-support#225]
**Describe the bug**
When trying to generate OAuth2.0 access token thunderclient returns the following error and does not populate access token field.

> Error: self signed certificate in certificate chain

**To Reproduce**
Reproducable example is here:
https://github.com/ghokun-contrib/keycloak-thunderclient 

**Expected behavior**
At least it could ask for permission to accept self signed certificates before error. Whitelisting via settings could be ok too.

**Platform:** 
 - OS: macOS Big Sur 11.4
 - vscode version: 1.57.1
 - extension version: 1.5.0

Mentioned here: #130

**Comment by rangav** [comment]
Thanks @ghokun do you need to provide manual certificate for you api request?

**Comment by ghokun** [comment]
I need to be able generate token from a auth server with trust self signed certificate. I don't provide certificate for the request.

**Comment by rangav** [comment]
Ok thanks I will verify and get back to you

**Comment by ilyakrasnovsky** [comment]
+1 for this - in the meantime, I was able to get the access token through a separate REST call with Thunder Client, as documented [here](https://developers.redhat.com/blog/2020/01/29/api-login-and-jwt-token-generation-using-keycloak#test_your_new_client) for example

**Comment by Sim9k** [comment]
Hi, it would be great to have an option in settings to disable SSL certificate verification. While trying to generate an Access Token in auth2.0 I'm getting error from Thunderclient: "Error: unable to verify the first certificate". 

In a testing environment I have a server with self-sign certificate and the SSL verification will not pass.

Thanks a lot.

**Comment by rangav** [comment]
Hi all, the Http library `got.js` that I am using in this extension is already configured to ignore ssl errors

see below
https://github.com/sindresorhus/got/blob/main/documentation/5-https.md#rejectunauthorized

**Comment by rangav** [comment]
Hi all, Found the issue, will apply fix in the next update.

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
