### ISSUE TITLE
When I fill http header for Authorization firstly thunder client not notice empty in Nodejs with Express.js

### ISSUE THREAD

**Issue by jack5341** [rangav/thunder-client-support#226]
**Describe the bug**
When I fill http header for Authorization firstly thunder client not notice empty in Nodejs with Express.js

**To Reproduce**
Create an input to HTTP Header for Authorization and for value put `<Bearer {token}>` you'll see when you send firstly you will se an output like this in your console.
`BearerÂ {token}`
But If you delete one space and then you add one space again it will notice and will work.

**Expected behavior**
While I fill this inputs I expected this output `Bearer {token}` and notice spaces in Authorization input.

**Platform:** 
 - OS:  Windows 10 Home
 - vscode version: 1.57.1
 - extension version: v1.5.0

**Comment by rangav** [comment]
Hi @jack5341 thanks for reporting.

similar issue as #199

**Comment by rangav** [comment]
Alternatively please use Auth tab - bearer token and provide only token there

**Comment by jack5341** [comment]
Yes its work looks like everything is well
Thank you @rangav

**Comment by rangav** [comment]
Thanks for confirmation, I will close this issue and we can track this on #199
