### ISSUE TITLE
Support for Path Variables

### ISSUE THREAD

**Issue by valtercfrancisco** [rangav/thunder-client-support#227]
**Is your feature request related to a problem? Please describe.**
At moment, there seems to have no support for path variables like in Postman. Because of this, if we want to use a path variable we have to edit the request it self every time.

**Describe the solution you'd like**
It would be great to in addition to Query Parameters, also have path variables like in Postman. Image of the feature in question in Postman below.

![image](https://user-images.githubusercontent.com/19156665/123265540-120e4a80-d4f3-11eb-831e-aed3829aa0a7.png)

**Comment by rangav** [comment]
Hi @valtercfrancisco 
Duplicate of #23
