### ISSUE TITLE
cURL returns error when executed

### ISSUE THREAD

**Issue by luanorlandi** [rangav/thunder-client-support#228]
**Describe the bug**
The cURL returns error when executed, it tries to execute each line in the command

**To Reproduce**

Copy the cURL and run in the terminal:

![image](https://user-images.githubusercontent.com/6919329/123282194-a8854080-d4e0-11eb-9f0a-76c713233193.png)

![image](https://user-images.githubusercontent.com/6919329/123281936-783da200-d4e0-11eb-9a62-f2dbfa627457.png)

**Expected behavior**

The cURL is executed without the errors.

![image](https://user-images.githubusercontent.com/6919329/123282364-ce124a00-d4e0-11eb-96fe-84f402872ea0.png)

**Platform:** 
 - OS: macOS Catalina version 10.15.7
 - vscode version: Version: 1.57.1
 - extension version: 1.5.0

**Solution:**

I fixed this by removing an empty space that I've found at the end of each line

![image](https://user-images.githubusercontent.com/6919329/123283082-6c061480-d4e1-11eb-8f34-9836cd749c8b.png)

**Comment by rangav** [comment]
Hi @luanorlandi thanks for reporting, I will verify and get back to you

**Comment by rangav** [comment]
this is now fixed in v1.6.0
https://github.com/rangav/thunder-client-support/releases/tag/1.6.0
