### ISSUE TITLE
Support preview for visual files such as images and pdfs

### ISSUE THREAD

**Issue by JonathanEspinosaLong** [rangav/thunder-client-support#229]
**Is your feature request related to a problem? Please describe.**
PDF and image files appear as raw information in the response window. 

**Describe the solution you'd like**
For pdf and image files to be rendered correctly and not just look at the raw data of the file.

**Describe alternatives you've considered**
Something similar to the preview feature in the Insomnia client 

**Implementation:**

**Comment by rangav** [comment]
Hi @JonathanEspinosaLong duplicate of #97

**Comment by rangav** [comment]
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0

Supports only images, not pdf.
