### ISSUE TITLE
Unable to import Postman environment json with 30 variable name & values

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#231]
**Describe the bug**
Unable to import Postman environment json with 30 variable name & values.

For yor information:
Then I deleted some variables & tried import. It is working as expected.

**To Reproduce**
Create an environment in postman with 30 variable name & values.

**Expected behavior**
Import should happen successfully

**Platform:** 
 - OS:  Windows 10
 - vscode version:
 - Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
 - extension version: 1.5.0

**Solution:**

**Comment by rangav** [comment]
Hi @IrshadSalik Thanks for reporting the issue, will verify with 30 variable name values and get back to you.

**Comment by rangav** [comment]
Hi @IrshadSalik i have tested with sample 30 env variables in postman and import into TC, all worked fine.

**Comment by rangav** [comment]
is it possible to share a sample env file exported from postman (with any sensitive data) for me to reproduce the issue

**Comment by rangav** [comment]
I am closing this issue, fell free to re-open if the problem still exists
