### ISSUE TITLE
Clone/Duplicate feature for the environment.

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#232]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @IrshadSalik will add to roadmap.

**Comment by rangav** [comment]
this is now implemented in v1.6.0
https://github.com/rangav/thunder-client-support/releases/tag/1.6.0
