### ISSUE TITLE
MS SQL integration to get test data from the DB to feed API request. Eg: OTP Code

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#233]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @IrshadSalik will review this feature request.

**Comment by rangav** [comment]
Hi @IrshadSalik You can use scripting now to achieve this.
