### ISSUE TITLE
API executed from collection are not part of history(Activity)

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#236]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Hi @IrshadSalik initially it was saving running the request of collection in history, but lot of users have suggested not to save to history, as it will create more diffs in git, so this was removed now.

**Comment by IrshadSalik** [comment]
> Hi @IrshadSalik initially it was saving running the request of collection in history, but lot of users have suggested not to save to history, as it will create more diffs in git, so this was removed now.

As a Postman user,  i have a automated collection for positive cases. I don't want to disturb my collection by testing with negative cases. So what i do is, i make use of history to do negative cases. 
It's upto you.

**Comment by rangav** [comment]
Will wait for more users feedback and decide then.

**Comment by rvenugopal** [comment]
@rangav Wouldn't it be possible to store these activity in a `.history` folder / file? Users can just add this file to their `.gitignore`

**Comment by rangav** [comment]
Hi @rvenugopal its already in my list to separate the activity requests from collections. I am planning to implement for next update.

**Comment by rangav** [comment]
Provided new vscode setting **Show Activity From Collection**  in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
