### ISSUE TITLE
Save option when changes made on API exist in collection

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#238]
**Is your feature request related to a problem? Please describe.**
**_Currently when i do any changes on API exist in collection. it is saved by itself. I recommend not to save instead ask to save or button to save_**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by stillie** [comment]
I would love this feature, to be able to modify and use an API without having to save it first - there are times where i would like to make some modifications to an API and not save it.

Currently i am aware of the option to save on demand rather than automatically, but the issue is, you need to save it first before you can submit the call :(

Subbed to this feature request and will be waiting eagerly for it

**Comment by gimzani** [comment]
I agree - there needs to be a better way to save each request.  I like the "Activity" bar, but sometimes the URL shown is not the URL that you get when you load it.  A multi-function save would be nice.  

Save button next to send might give the option to save current state or save to collection.  That would be super-helpful.

Thanks!

**Comment by rangav** [comment]
`Cmd/ctrl + s` will save the request without running it

**Comment by stillie** [comment]
Sometimes i dont want to save a request, as i might be changing the url for a specific endpoint and just want to see the response i get. Once i am done with that request i would like to not have to undo the call then save again.

I generally run one time api calls that i dont intend on saving?

**Comment by rangav** [comment]
@stillie how is done other api clients like postman or insomnia?

If we start adding additional buttons for each type, then it will be messy, if we add a dropdown beside send button, then it will look like postman interface.

Users have asked buttons for below use-cases

- Save only without Run
- Run without Save
- Save to Collection
- Send & Download file

**Comment by rangav** [comment]
@stillie  in your case, these are the alternative ways you do it for now.

- if the request is in activity you can delete it after finish testing.
- if the request is in collection, you can duplicate it and test and then delete it.

**Comment by stillie** [comment]
Yea,

I get that, and that's what I do. Is there some technical reason as to why this is not a feature that cant be implemented?

**Comment by stillie** [comment]
EDIT: I see that you commented earlier.

I guess its just something i will have to deal with.

**Comment by rangav** [comment]
implementing is not a problem, but doing it without complicating the UI is challenging.

for now you have to deal with it, when I find a better solution will update this.

**Comment by gimzani** [comment]
> `Cmd/ctrl + s` will save the request without running it

Aha!  Thank you!!!

**Comment by rangav** [comment]
We have provided the setting to disable save on send request, please enable it.
<img width="957" alt="Screenshot 2022-12-22 at 21 13 13" src="https://user-images.githubusercontent.com/8637550/209227034-cea23976-b1df-4c9b-a774-d34724ec856d.png">


Now you can the request using `Ctrl/Cmd + s`
