### ISSUE TITLE
Add option to configure whether to follow redirects

### ISSUE THREAD

**Issue by heinrich-ulbricht** [rangav/thunder-client-support#239]
**Is your feature request related to a problem? Please describe.**
I'm testing a REST API that - when successful - responds with a 302 redirect. I want to examine this response. I don't want the redirect to be followed.

Currently it's very intransparent that a redirect is being followed. The response of the followed redirect looks like the reponse to the initial call. But this is not true. In my case the site I'm being redirected to is not accessible for me thus I get a 403 Forbidden. Initially I thought the 403 was the response to the _initial call_. But no, the initiall call succeeds, redirects and the page I'm redirected to returns 403. Confusing.

**Describe the solution you'd like**
I would like to see an option to disable automatic redirects. 

**Describe alternatives you've considered**
None.

**Comment by rangav** [comment]
Provided new vscode setting **Follow Redirects** to enable/disable redirects in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
