### ISSUE TITLE
Cannot send requests to localhost

### ISSUE THREAD

**Issue by jordanhandy** [rangav/thunder-client-support#24]
**Describe the bug**
Requests to localhost fail with an "unknown error occurred".  Response code is ERROR, Size is 0B, and time is 0ms.
Requests to other endpoints like Google, ThunderClient.io, etc all work.

**To Reproduce**
Express server on localhost:3000.  Request work fine in Postman, but not in Thunder Client

**Expected behavior**

Requests are sent properly

**Platform:** 
 - OS:  Windows 10

**Solution:**

Is there anywhere where logs are stored?  Couldn't find documentation on this.

**Comment by rangav** [comment]
Hi @jordanhandy i will test and get back to you.

**Comment by rangav** [comment]
currently i am not storing logs anywhere, may be its good to have proper logging to file. will add to my dev list.

**Comment by rangav** [comment]
Hi @jordanhandy i have tested just now with my thunder client website locally on `https://localhost:5001/`, its working.

did you include full url for localhost with http prefix?

**Comment by jordanhandy** [comment]
> Hi @jordanhandy i have tested just now with my thunder client website locally on `https://localhost:5001/`, its working.
> 
> did you include full url for localhost with http prefix?

Hi @rangav, I believe the full URL was included, but I may have forgotten. I will test this, and close it fixed.

**Comment by jordanhandy** [comment]
@rangav .  Confirmed this works if you use the full URL.  Perhaps a feature request is needed so this is not required?  Small QoL improvement, but Postman does not require this
