### ISSUE TITLE
While Setting environment variable using json response wipes out all environment variables

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#240]
**Describe the bug**
I used "json.Result.TFNList[0].TrafficFileNumber" to set my environment variable.
My Json response looks like below
{
  "Result": {
    "TFNList": [
      {
        "TrafficFileEmirate": 1,
        "TrafficFileNumber": 10618643,
        "VehicleCount": 0,
        "TCUpdatedTime": "0001-01-01T00:00:00",
        "IsActive": true
      },
 {
        "TrafficFileEmirate": 1,
        "TrafficFileNumber": 10618643,
        "VehicleCount": 0,
        "TCUpdatedTime": "0001-01-01T00:00:00",
        "IsActive": true
      }
]
  },
  "ResponseCode": "71_0",
  "ResponseDescription": "Success"
}
**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Hi @IrshadSalik will verify it

**Comment by IrshadSalik** [comment]
Hope this is a critical bug.

**Comment by rangav** [comment]
Yes your are right, you found an critical bug. just now fixed it, will release as part of next update.

Thanks @IrshadSalik for reporting it.

**Comment by rangav** [comment]
this is now fixed in v1.6.0
https://github.com/rangav/thunder-client-support/releases/tag/1.6.0
