### ISSUE TITLE
Basic-Auth stopped working with 1.6.0

### ISSUE THREAD

**Issue by Eusebius1920** [rangav/thunder-client-support#241]
**Describe the bug**
Use Basic-Auth with requests to a backend. Apparently it will not send the (correct) credentials to the backend.

**To Reproduce**
Upgrade to 1.6.0 and connect to a server with basic auth.

**Example**: https://jigsaw.w3.org/HTTP/Basic/
**user**: `guest`, **password**: `guest`

get back `401 Unauthorized`

**Expected behavior**
get back `200 OK`
Also: credentials do not get saved either anymore.

**Platform:** 
 - OS: Linux x64 5.12.13-arch1-2 
 - vscode version: 1.57.1
 - extension version: 1.6.0

**Solution:**
downgrade to some prior version before `1.6.0`

**Comment by rangav** [comment]
Hi @Eusebius1920 thanks for reporting will verify and fix it asap.

**Comment by rangav** [comment]
Just now did a quick release to fix this bug.
https://github.com/rangav/thunder-client-support/releases/tag/1.6.1

**Comment by Eusebius1920** [comment]
Blazing fast, thanks for your awesome work!

Can confirm that it works again with 1.6.1.

**Comment by rangav** [comment]
Thanks @Eusebius1920 for confirmation 👍

**Comment by jacqueswho** [comment]
@rangav Unfortunately this issue has been replicated in the latest version 1.8.1

**Comment by rangav** [comment]
Hi @jacqueswho 

I have just now tested
Example: https://jigsaw.w3.org/HTTP/Basic/
user: guest, password: guest

Its working for me

**Comment by rangav** [comment]
> @rangav Unfortunately this issue has been replicated in the latest version 1.8.1. Will see if it something on my side

Could be on yourside

**Comment by jacqueswho** [comment]
@rangav  So we need to test with more complicated characters. t_!N!Dseqo-ziYno3KE@wboNyu7EWDUcrpNMy_jVdpVCygsCo9CdTnb7zhRmwDnVQjz6pM2n*G_YVTzpahNQ7ezh9vvtkrVf . This is just an example but I have a password that is quite complex like this. It fails but passes in postman

**Comment by rangav** [comment]
ok let me test

**Comment by rangav** [comment]
I can see the value is sent to backend, when i send request to test url https://httpbin.org/anything

Is it possible to share your server url and with sample username and password for me to test here locally

**Comment by rangav** [comment]
Hi @jacqueswho is it working for you?

**Comment by jacqueswho** [comment]
hi @rangav Currently on leave and will investigate and let you know when I am back.
