### ISSUE TITLE
Response tab colors

### ISSUE THREAD

**Issue by davioliveira-dev** [rangav/thunder-client-support#243]
**Is your feature request related to a problem? Please describe.**
The response tab does not have the colors of the current vscode theme, the json response always comes in the default theme (Dark+)

![image](https://user-images.githubusercontent.com/53924113/123865694-9fdaa300-d902-11eb-8eb3-032754df57b9.png)

I switched themes and this issue continues.

**Describe the solution you'd like**
Just get the current color scheme from vscode and apply to Response tab (on json response)

**Describe alternatives you've considered**
None

**Implementation:**

**Comment by rangav** [comment]
Hi @davioliveira-dev Will add this to roadmap.

**Comment by rangav** [comment]
Hi @rangav, Looks like vscode did not expose the editor themes to extensions yet

please see this issue in vscode repo https://github.com/Microsoft/vscode/issues/56356

**Comment by APerricone** [comment]
for this kind of thing are not sufficient the css variables? in my extension I obtains good result... for example https://github.com/APerricone/vscode-dbf/blob/master/media/style.css

**Comment by rangav** [comment]
@APerricone they are not sufficient, I am also using those css variables for extension theme, but code editor part is not sufficient 

If you know how to use them in vscode webviews for code syntax highlighting let me know

**Comment by APerricone** [comment]
as we see on microsoft/vscode#56356 they use [shiva](https://shiki.matsu.io/) , I can see on the page it says "But really, any VS Code theme will do" I think you can use env.uriScheme.  I have not tried

**Comment by rangav** [comment]
@APerricone  Thanks - Will give it a try and see if works.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.0

Please let me know your feedback.

**Comment by ejabu** [comment]
how can you do it ? did vscode provide you new API to interact with ?
