### ISSUE TITLE
Support redirects?

### ISSUE THREAD

**Issue by apptessence** [rangav/thunder-client-support#244]
This may be already a working feature, but I haven't found it. Testing with a localhost server, when the server issues a redirect through middleware (usually an authentication condition), ThunderClient hangs, although it works perfectly well in an actual browser. 

Is there a way to enable this? Can it be done with some kind of header that in my pathetic ignorance I know nothing of?

**Comment by rangav** [comment]
Hi @apptessence it automatically follows redirects, it's enabled.

what status code are you sending and rediectTo url?

**Comment by apptessence** [comment]
Hey Rangav, thanks for the quick response. TBH, and not at the computer, I'm relying on supplied middleware that's part of Vapor Server to pick up the non-auth condition. The only parameter I control is the path, which is a very straightforward absolute path, e.g. "/fallback". I'll see if I can dig up the returned status code when I'm chained to my desk later.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
