### ISSUE TITLE
Setting to open each request in a new tab

### ISSUE THREAD

**Issue by alessandrofc** [rangav/thunder-client-support#246]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A way to set a config to open each request in a new tab. To do this I need to double click on it.

**Describe alternatives you've considered**
No

**Implementation:**

**Comment by rangav** [comment]
Hi @alessandrofc you can double on the first request and click on 2nd request to open in new tab.

**Comment by davnarau** [comment]
Hi @rangav , the current double click implementation is a bit clunky but useful until this feature request is developed. Could I suggest a right click menu item on the request or a new option off the kebab menu called "Open in new Tab" or something similar.

**Comment by rangav** [comment]
This feature is now implemented in v1.8.0

You can do in 2 ways

- `Open in New Tab` menu option
- `Ctrl/Cmd + Click `on request will open in new tab


see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

**Comment by alessandrofc** [comment]
Great. Tks
