### ISSUE TITLE
Thunder client error with vscode 1.57.1

### ISSUE THREAD

**Issue by cabrinoob** [rangav/thunder-client-support#247]
Hello,
Since the last VScode update (1.57.1), the thunder client extension stopped working with this error message : 

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```
Everything worked fine with this extension before this upgrade.

Thank you for your help

**Comment by rangav** [comment]
Hi @cabrinoob can you try uninstall and re-install the extension?

or close all vs code instances and open again?

**Comment by rangav** [comment]
Hi @cabrinoob I am closing this issue, feel free to re-open if needed

**Comment by dvnrsn** [comment]
I've been observing this as well. Tried uninstalling and reinstalling v1.19.7. Also tried killing VS Code

**Comment by dvnrsn** [comment]
On Mac resolved by force killing vscode from activity monitor

https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai
