### ISSUE TITLE
Make Bearer Token Easier To Copy/Paste

### ISSUE THREAD

**Issue by snerks** [rangav/thunder-client-support#248]
**Is your feature request related to a problem? Please describe.**
If I need to replace the Bearer Token, there is currently no option to Select All.
Also, because the value is so long, it is not possible to see the entire value.

**Describe the solution you'd like**
Render the Bearer Token in a TextArea that is large enough to view the entire value.
Enable an option to "Select All"

**Describe alternatives you've considered**
Attempts to double-click are frustrated by the fact that the amount of selected text is constrained by the presence of certain "delimiter" characters in the Bearer Token value.

**Implementation:**
Use multirow TextArea for Bearer Token

**Comment by rangav** [comment]
Hi @snerks thanks for the feedback, will add to roadmap

**Comment by abelsoares** [comment]
@snerks you can use a keyboard shortcut to select all, just click on the input an CMD + A (macOS).

**Comment by rangav** [comment]
Bearer token field in now textarea in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
