### ISSUE TITLE
Setting up Complex Environment Variable

### ISSUE THREAD

**Issue by kush-jain** [rangav/thunder-client-support#250]
**Describe the bug**
Cannot find a way to set up environment variable of format `<string> json.property`

**To Reproduce**
Tried:
XYZ json.attribute   setTo  {{myVariable}}

**Expected behavior**
Correct value of myVariable

**Platform:** 
 - OS: Mac
 - vscode version: 1.57.1
 - extension version: v1.6.1

**Comment by rangav** [comment]
Hi @kush-jain did not understood your question?

can you share a sample screenshot of your response?

or can you provide more details clearly?

**Comment by rangav** [comment]
Currently this is not possible, but while using the variable, you can use in that format `Hello {{variable}}`.

I will review about this feature request.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.1`

We added a new filter called `format`, you use it as `{{variable | format("hello {0}")}}`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.1

Please let me know your feedback.

**Comment by rangav** [comment]
Filters documentation here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md
