### ISSUE TITLE
Connection refused by Server, using PHP 8.0.6 internal Server

### ISSUE THREAD

**Issue by raphievila** [rangav/thunder-client-support#251]
**Describe the bug**
Setting up for the first time, I have set up Env Variable as I did with Postman to use `{{testurl}}` with value http://localhost:9000. The server is served by PHP inner server as follow:

```shell
php -S localhost:9000 /directory/to/project
```

Sending POST request as a Form with three key/value pair:

```json
{"user": "foo", "password": "bar", "key": "bunch_of_symbols"}
```

When send I get:

```
Connection was refused by the server.
```

I have the exact same set up on Postman, where I do receive a response with a JSON file.

**To Reproduce**
1. Install PHP 8.0.6
2. open VS Code
3. install Thunder Client Extension
4. set Env and set variable `testurl` with value "http://localhost:9000".
5. Create a new POST request pointing to: "{{testurl}}?method=foo"
6. in the body tab select Form, set anything.
7. Create a directory and save a PHP file `index.php` that serves a JSON file.
8. open Windows Terminal and navigate to that directory
9. start PHP internal server with "php -S localhost:9000"
10. go back to Code and try sending request

**Expected behavior**
I was expecting a response as a JSON file

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.57.1
 - extension version: 1.6.1

**Solution:**
No idea

**Comment by rangav** [comment]
Hi @raphievila there was similar issue before 

see if this solution works 

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-864047143

**Comment by raphievila** [comment]
Thank you @rangav I did check the solution, and it kind of works, not sure is because is Windows, but the IP `0.0.0.0` does not resolve.

But instead of using `localhost:9000` I did use the actual IP set for the computer… `198.168.0.189:9000` for example, then it works.

If someone else faced this issue on Windows, and do not know the IP, just open the terminal (Command Prompt or PowerShell or Windows Terminal) and type:

```console
$ ipconfig /all
```

The IP normally in on the `IPv4 Address` under `Ethernet adapter Ethernet` group with a label `(Preferred)` by it.

I also tested it with `127.0.0.1` and also worked.

**Comment by rangav** [comment]
Thanks @raphievila for confirmation 👍

**Comment by co-bby** [comment]
if you are using WSL on Windows use [::1] instead of localhost in the address bar. Example [::1]:3000/api/v1 .
Another option is to use the PowerShell instead of the WSL terminal. Lastly, You can also move your project directory to the Linux file system (~/home)

**Comment by remotedevelopment-info** [comment]
If I start the npm server (using pnpm, maybe this is not the same?) with --host then it exposes the host and the api calls with thunderclient work with localhost
