### ISSUE TITLE
How to set up to localhost 

### ISSUE THREAD

**Issue by ShankarUppala** [rangav/thunder-client-support#252]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Hi @ShankarUppala its not clear what you are looking for?

**Comment by ShankarUppala** [comment]
Hi @rangav while I am trying to get data through my local host routes then it was showing raw data i wills end screenshot

**Comment by ShankarUppala** [comment]
![thunderclient](https://user-images.githubusercontent.com/81143370/124707591-a5de0e80-df16-11eb-8c2a-97f275b79c68.png)

**Comment by rangav** [comment]
There is a preview button below the raw text to render html.

**Comment by ShankarUppala** [comment]
419 page expired error was came

**Comment by rangav** [comment]
Can you share screenshot of the error?

**Comment by ShankarUppala** [comment]
![thunder2](https://user-images.githubusercontent.com/81143370/124709162-cc04ae00-df18-11eb-90b1-4302300c4838.png)

**Comment by rangav** [comment]
What is your extension version and vscode version?

**Comment by ShankarUppala** [comment]
extension version is v1.6.1
vs code version 1.53.1

**Comment by ShankarUppala** [comment]
vscode version 1.57.1

**Comment by rangav** [comment]
Can you run request again and click preview button

**Comment by ShankarUppala** [comment]
same error came

**Comment by ShankarUppala** [comment]
https://github.com/rangav/thunder-client-support/issues/252#issuecomment-875316754

**Comment by rangav** [comment]
Is there any published url, so I can verify and find the issue

**Comment by ShankarUppala** [comment]
I dont have but my requirement is to set up the thunder client to my localhost i want to explore my local routes

**Comment by ShankarUppala** [comment]
![thunder3](https://user-images.githubusercontent.com/81143370/124716616-eb540900-df21-11eb-95da-b293a27bb506.png)
I git this error please check once

**Comment by rangav** [comment]
Is it possible for you record a video of the steps and share it

**Comment by ShankarUppala** [comment]
not possible to record a video

**Comment by rangav** [comment]
Ok no problem, are you sure you are latest version of extension?

because the raw request has 200 status code https://github.com/rangav/thunder-client-support/issues/252#issuecomment-875307998

and preview button will not change status code

**Comment by ShankarUppala** [comment]
v1.6.1

**Comment by rangav** [comment]
Looks like you are not providing authentication details for the request 

are these working in postman

**Comment by rangav** [comment]
Also you shared 3 different urls,
- /get_organisation
- /app/get_organisation
- /app/get_available.....

**Comment by ShankarUppala** [comment]
how can i provide authentication details in thunder client?

**Comment by rangav** [comment]
Click on Auth tab

**Comment by ShankarUppala** [comment]
![thunder3](https://user-images.githubusercontent.com/81143370/124734181-7e953a80-df32-11eb-9a36-01f7cfd9b81b.png)

see there i have already provided auth realted info

**Comment by rangav** [comment]
See your server logs and put break point see what’s missing in the request 

What api client you used  before?

**Comment by ShankarUppala** [comment]
i didnt used any api clients before

**Comment by rangav** [comment]
This could be your api/server problem, You need to check your api requirements and send in thunder client

**Comment by rangav** [comment]
Hi @ShankarUppala closing this issue, feel to reopen if needed.
