### ISSUE TITLE
Add a definitive uuid/guid option to random generated data

### ISSUE THREAD

**Issue by nevcook** [rangav/thunder-client-support#253]
**Is your feature request related to a problem? Please describe.**
When testing some services, each post request requires a unique GUID/UUID.
The current random data generation includes only string, number and email, so I was initially manually modifying the request each time I submit it.
We have found by experimentation that in the version we are currently using {{#randomString}} does actually generate a GUID.
However that may change in the future, as it's not part of the documented behaviour of {{#randomString}}, and we are now relying on that behaviour.

**Describe the solution you'd like**
Add a new dynamically generated variable something like {{#randomGUID}}
Having {{#randomGUID}} as well as {{#randomString}} would give us more confidence that tests requiring a GUID will keep working for the long term.

**Describe alternatives you've considered**
We are just using {{#randomString}}.for now, and hoping the implementation doesn't change.

**Implementation:**
This should be an almost trivial change, with {{#randomGUID}} begin identical to the current implementation of {{#randomString}} generation, but documented as generating a GUID, instead of potentially generating some other string format.

**Comment by rangav** [comment]
Hi @nevcook thanks for suggestion will add new variable `{{#guid}}`

**Comment by rangav** [comment]
This is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0
