### ISSUE TITLE
Date & DateISO with parameters

### ISSUE THREAD

**Issue by MaxiDutra** [rangav/thunder-client-support#256]
I have a project who needs a specific datetime format (datetime 'YYYY-MM-DDThh:mm:ss') it is any way to implement this feature ?

**Comment by rangav** [comment]
Hi @MaxiDutra will think of how to implement custom date format and get back to you.

**Comment by MaxiDutra** [comment]
> Hi @MaxiDutra will think of how to implement custom date format and get back to you.

Thank you!

**Comment by rangav** [comment]
Hi @MaxiDutra I am implementing this feature, the format will be `{{#date, "YY-MM-DD hh:mm:ss:fff"}}` fff is millisecs
### ### 
One question what is `T` in your question?
 >(datetime 'YYYY-MM-DDThh:mm:ss')

**Comment by MaxiDutra** [comment]
Hello, The T is just a standard (ISO 8601) way to delimit the time, you can see more in the link below 
https://en.wikipedia.org/wiki/ISO_8601

**Comment by rangav** [comment]
Ok got it. Thanks. 

See next update details here #282

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
