### ISSUE TITLE
Thunder Client is not working in New version of VSCode v1.58.0

### ISSUE THREAD

**Issue by VpkPrasanna** [rangav/thunder-client-support#257]
**bug**
Error Msg -> Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

**To Reproduce**
Install New Version of VS code  June 2021 (version 1.58)

**Platform:** 
 - OS: Ubuntu 20.04.2
 - vscode version: (version 1.58)
 - extension version:v1.6.1

**Comment by rangav** [comment]
Hi @VpkPrasanna thanks for reporting, I will verify the issue.

Try reinstalling the extension

**Comment by VpkPrasanna** [comment]
Yes i had done that too, it does not work. I rolled back to previous version of VS Code and it is working as expected.

**Comment by apoorvpandey0** [comment]
> Yes i had done that too, it does not work. I rolled back to previous version of VS Code and it is working as expected.

I'm facing same issue in VSCODE v 1.57.1
How to roll back?

**Comment by rangav** [comment]
You can see release month and version in the below and download options
https://code.visualstudio.com/updates/

**Comment by smaculan** [comment]
I also have this issue, same OS and VSCode version.

**Comment by kthornbloom** [comment]
Hello, same here. Sad to see this awesome plugin just sitting blank now :(

<img width="598" alt="Screen Shot 2021-07-13 at 10 06 29 AM" src="https://user-images.githubusercontent.com/3322795/125466379-4f7efc88-dcbe-4d4a-9825-975fa9936d1b.png">

I did try un-installing and re-installing

**Comment by rangav** [comment]
Hi @kthornbloom upgrade to v1.7.0 see if that works.

Or you can downgrade to previous version of vscode.
https://code.visualstudio.com/updates/

**Comment by kthornbloom** [comment]
Hi @rangav - I'm on the latest 1.7
<img width="742" alt="Screen Shot 2021-07-13 at 10 12 03 AM" src="https://user-images.githubusercontent.com/3322795/125467225-3dedc2b8-96d0-469b-912b-8e976cc3dab2.png">

but I still have the issue with a "loading" icon and empty tab. Maybe something to do with all the additional security added to vscode recently? I don't think I'll downgrade vscode, but happy to help test changes if needed.

**Comment by rangav** [comment]
Hi all

vscode released new version `v1.59.0` please check if the issues are fixed and let me know.

**Comment by VpkPrasanna** [comment]
> Hi all
> 
> vscode released new version `v1.59.0` please check if the issues are fixed and let me know.

Yes it is working for me @rangav

**Comment by rangav** [comment]
Thanks @VpkPrasanna for confirmation

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if anyone still having issue.

**Comment by kthornbloom** [comment]
Sorry, no luck for me. Still gets stuck while loading:

<img width="419" alt="Screen Shot 2021-08-06 at 8 18 23 AM" src="https://user-images.githubusercontent.com/3322795/128509343-cb21d7e9-dc45-4b0a-89c4-661af5f29d86.png">

VSCode Version: 1.59.0 (Universal)
macOS Big Sur Version 11.5

**Comment by rangav** [comment]
@kthornbloom may be downgrade to the version that is working for you, until it’s fixed

**Comment by sivachandran** [comment]
Yes, still not working.

VSCode Version: 1.59.0
Ubuntu 20.04

**Comment by sivachandran** [comment]
> Yes, still not working.

It works after uninstalling, closing all windows then opening and installing.

**Comment by azulkipli** [comment]
Still not working.

VSCode Version: 1.59.0
Mojave, Macbook Pro 13

**Comment by rangav** [comment]
Hi @azulkipli its a vscode issue for some users. Try downgrading vscode to 1.57 or 1.56

**Comment by rangav** [comment]
@azulkipli can you see error logs in output when you launch Thunder Client. 

You need to select `Thunder Client` dropdown in the output window.

**Comment by azulkipli** [comment]
> @azulkipli can you see error logs in output window when you launch Thunder Client.
> 
> You need to select `Thunder Client` dropdown in the output window.

I've change default folder for collections data.

<img width="987" alt="Screen Shot 2021-08-19 at 01 28 28" src="https://user-images.githubusercontent.com/8231792/129952980-76848453-aab0-4ca0-89f1-6495f2b5afcc.png">

**Comment by rangav** [comment]
Hi @bugada can you create a new issue, we can tract it separately

**Comment by rangav** [comment]
I am closing this
