### ISSUE TITLE
Automatic backup and restore suggestion

### ISSUE THREAD

**Issue by saymondamasio** [rangav/thunder-client-support#259]
I would like to give a suggestion, it would be nice if there was an option in the settings to enable automatic saving of a backup in a project folder. Then it would read these files automatically when opening the project.

**Comment by rangav** [comment]
Hi @saymondamasio its already supported - see team features section 

https://github.com/rangav/thunder-client-support#team

enable `Load from project` setting

**Comment by saymondamasio** [comment]
sorry, i hadn't paid attention, thank you very much

**Comment by rangav** [comment]
no problem @saymondamasio , any suggestion to improve documentation to make it clear that this feature exists, as lot of users ask similar question.
