### ISSUE TITLE
Support State for OAuth 2.0

### ISSUE THREAD

**Issue by JoshTRN** [rangav/thunder-client-support#26]
When I go to generate the token, I get a url that doesn't have the the content of the state parameter, it just says `state=&client_id=<CLIENT ID>` even though there is text in the state text field.

![image](https://user-images.githubusercontent.com/33141876/115742115-5e57d580-a35e-11eb-8b04-7aa240ede828.png)

**Comment by rangav** [comment]
Hi @JoshTRN  this is now fixed, will be part of next update v1.1.0, more details here - #14

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14
