### ISSUE TITLE
Synchronisation across vs code instances

### ISSUE THREAD

**Issue by chrisoftech** [rangav/thunder-client-support#260]
**Is your feature request related to a problem? Please describe.**
Currently, working on a different machine other than my laptop would mean re-initiating thunder-client's request again since i can't export these request calls.

**Describe the solution you'd like**
A feature to synchronise user requests across vs-code instances (via authenticated account - thunder-client account?) and also to export request would be great to have.

**Comment by rangav** [comment]
Hi @chrisoftech this feature is already supported - see **team features** section

https://github.com/rangav/thunder-client-support#team

just now another user asked this #259

**Comment by chrisoftech** [comment]
Thanks.
