### ISSUE TITLE
collection level variables

### ISSUE THREAD

**Issue by copdips** [rangav/thunder-client-support#261]
Hi,

I have 2 collections, one for dev, another for prd.
The 2 collections have the same url except for the keyword env in the path, for example:

In the dev collection, the url is: `http://myUrl/dev/xxx`
In the prd collection, the url is: `http://myUrl/prd/xxx`

I would like know if I can define a collection level env var, for example `env='dev'` in the dev collection, then the url syntax is something like: `http://myUrl/{{env}}/xxx`

**Comment by rangav** [comment]
Hi @copdips currently collection level variables are yet supported, 

Alternatively you can create 2 environments prod and Dev and set them active based on the collection you run.

**Comment by copdips** [comment]
hi @rangav ,
thanks for you reply, but I still cannot figure out how to achieve it by using `create 2 environments prod and Dev and set them active based on the collection`. Could you please provide more details ?

**Comment by rangav** [comment]
![Screenshot 2021-07-12 at 22 16 05](https://user-images.githubusercontent.com/8637550/125356974-df6fa900-e35e-11eb-8213-6d7b60a1be12.png)

**Comment by copdips** [comment]
Okey, thanks, got it. I just realized that the `Env` is just some kind of variable groups.
