### ISSUE TITLE
Invalid Payload format does not shows error about payload instead shows 400 bad request as it is from API.

### ISSUE THREAD

**Issue by devashishg** [rangav/thunder-client-support#263]
I tried passing JSON with some format/comma issue, It does not shows error in editor/payload area, also If I sends request, It shows 400 bad request as it is from API & It does not show any proper error.

How It should be: 
it depends, Ideally it should show error with in the text area itself when I am under JSON tab and does not have proper format data.

I tried using postman, there also I got similar error message but at-least I get to see error marked in the text-area itself.

I just came across this issue, but not sure what could be the solution, 
I think the reason might be that the editor area under JSON tab is not designated file type (JSON). Because I noticed If I make similar error in a JSON type file, It does highlight the error.

**Comment by rangav** [comment]
Hi @devashishg thanks for the feedback, will look into it.

**Comment by rangav** [comment]
Hi @devashishg this will fixed in the next update v1.9.0 #282

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
