### ISSUE TITLE
Add tests code generation feature

### ISSUE THREAD

**Issue by etienne-klein** [rangav/thunder-client-support#264]
**Is your feature request related to a problem? Please describe.**
To complement feature request #194, I would love to have an "export" or "generate tests" button at collection level, to generate the corresponding code in TypeScript for Jest. 
Then more complex tests may be implemented and re-imported as suggested in #194.

For even greater genericity, you may even add a small templating engine to target different testing frameworks or accomodate any specific needs by adding/modifying a bunch a templates.

Having all the tests generated would allow running them with any CI pipeline.

BTW, thanks for this excellent extension !

**Comment by rangav** [comment]
Hi @etienne-klein thanks for the suggestion, will review this request.

**Comment by rangav** [comment]
Hi @etienne-klein currently no plans to implement this
