### ISSUE TITLE
what's wrong with text/plain response

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rangav/thunder-client-support#265]
Doesn't render plain text in response

Write a simple http server in node and with content type plain text. It doesn't render plain text in response. However it should render plain text 

VSCodium ::: 
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-18T00:13:37.935Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.42-1-MANJARO

![res](https://user-images.githubusercontent.com/8083613/125550432-2e91acfb-4fee-470c-b13d-92d521a57b6a.png)

**Comment by dortamur** [comment]
I have a similar problem - a Request is returning type "text/calendar" (ICS format), yet the Response is showing a broken image instead of the text content.

**Comment by rangav** [comment]
Hi @AbhimanyuAryan thanks for reporting, I will verify and fix it ASAP.

**Comment by rangav** [comment]
Just now did a quick release to fix this. please update to v1.7.1
https://github.com/rangav/thunder-client-support/releases/tag/1.7.1

**Comment by AbhimanyuAryan** [comment]
that was quick. Thanks :)
