### ISSUE TITLE
CTRL Z is not working as expected in headers

### ISSUE THREAD

**Issue by IrshadSalik** [rangav/thunder-client-support#266]
**Describe the bug**
In header section, in the key-value table. Ctrl+Z is not working as it suppose to work

**To Reproduce**
For example below is the header,
Accept - application/json
Delete the value & update with some other value say
Accept - test
Ctrl + Z, check the field

**Expected behavior**
After Ctrl + Z, header should be Accept - application/json
![image](https://user-images.githubusercontent.com/79840486/125588542-048fe2b9-2fd0-49a4-9c12-9ce9f78baa29.png)

**Actual behavior**
After Ctrl + Z, header is Accept - testapplication/json
![image](https://user-images.githubusercontent.com/79840486/125588659-44097227-62cb-4287-8a44-c11a3161fcda.png)

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by IrshadSalik** [comment]
After new update CTRL Z is not working

**Comment by rangav** [comment]
Hi @IrshadSalik thanks for reporting

Don't think this is working from the beginning.

duplicate issue of  https://github.com/rangav/thunder-client-support/issues/146
