### ISSUE TITLE
Publish Thunder Client in OpenVSX

### ISSUE THREAD

**Issue by bitsper2nd** [rangav/thunder-client-support#268]
Hi can you publish Thunder Client in [OpenVSX](https://open-vsx.org/)? It would be great for those of us that use [VSCodium](https://vscodium.com/) or [Onivim2](https://v2.onivim.io/#preorder) to not need to install the extensions manually.

**Comment by rangav** [comment]
Hi @bitsper2nd duplicate of #30

**Comment by bitsper2nd** [comment]
Oh, sorry for that. Carry on.
