### ISSUE TITLE
Highlight the selected query in the collection - it's easy to lose track of where you are!

### ISSUE THREAD

**Issue by ssnyder** [rangav/thunder-client-support#269]
**Is your feature request related to a problem? Please describe.**
It is currently not easy to determine which query you are running in a collection - the collection is highlighted, but no indicator which query in the collection is being run other than the tab header - which may/may not show the entire name (that is a configuration)

**Describe the solution you'd like**
Somehow highlight/indicate the query you are showing in the tab (or active tab if you are going to enable multiple tabs).  Optionally scroll the listing explorer window to the query as well if you enable multiple tabs.

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @ssnyder thats a good suggestion, will add to roadmap

**Comment by rangav** [comment]
Hi @ssnyder I have increased the tab name length to 25 chars in `v1.10.0`, 
highlighting the request in sidebar, based on the active tab is in development, will be part of next update

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback
