### ISSUE TITLE
A button to clear cookies

### ISSUE THREAD

**Issue by MatheusNaldi** [rangav/thunder-client-support#271]
**Is your feature request related to a problem? Please describe.**
I was implementing a feature in an API auth endpoint and this API returns session within the cookies, I can't clear the cookies to test a new request as a new user, I'm using postman just to test this endpoint because clear the session in the server-side is painful

**Describe the solution you'd like**
A simple button to clear the cookies will solve the problem

**Describe alternatives you've considered**
I found this [issue](https://github.com/rangav/thunder-client-support/issues/142) to implement the postman's cookie manager, it is better to have all of this stuff in the final product, and I know this will be a lot of work and maybe will get some time to deliver this, maybe the first version could be just a button to clear the cookies, and then you can continue working on the cookie manager

**Implementation:**

**Comment by rangav** [comment]
Hi @MatheusNaldi thanks for the suggestion, I will add to roadmap.

**Comment by rangav** [comment]
This feature will be part of next update #282

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

The button is in cookies tab
please let me know if any feedback

**Comment by MatheusNaldi** [comment]
@rangav the button is there, I've just tested it today...when I click it appears the message "Removed All Cookies...", but the cookies remain there even if I close the tab and open it again

**Comment by rangav** [comment]
Hi @MatheusNaldi can you share screenshot where cookie is still there?

**Comment by rangav** [comment]
I think probably you are seeing previous saved response

you need execute the request again after clearing cookies to see new response.

**Comment by MatheusNaldi** [comment]
> I think probably you are seeing previous saved response
> 
> you need execute the request again after clearing cookies to see new response.

Yes, you are right, I think it is just cache even closing tab and reopening again, if I send the request again I will see new values for the cookies...

But if after clicking the button to clear cookies the message "No Cookies Available" shows again, it will be a lot better for the UX

**Comment by rangav** [comment]
Did not understood your suggestion?

> But if after clicking the button to clear cookies the message "No Cookies Available" shows again, it would be a lot better for the UX

**Comment by MatheusNaldi** [comment]
When I click in "Clear All", the cookies should update to "No Cookies Available"

After clicking in "Clear All" the cookies remain showing after delete
![image](https://user-images.githubusercontent.com/16821957/130288436-5ae3db1d-c3da-4977-8a5f-47fa1d867ade.png)

It should appear "No Cookies Available" as in this example below with new requests
![image](https://user-images.githubusercontent.com/16821957/130288534-607b5e4b-8d68-40ad-9917-986977ec2b89.png)

**Comment by rangav** [comment]
Ok got it, will update it. Thanks
