### ISSUE TITLE
Sometimes open next/previous editor command not working

### ISSUE THREAD

**Issue by RashminDungrani** [rangav/thunder-client-support#272]
**Describe the bug**
when we are on thunder client editor then can't go to next or previous open editor with keyboard shortcut.

**Platform:** 
 - OS: macos big sur
 - vscode version: 1.53.2
 - extension version: 1.7.1

**Comment by rangav** [comment]
Hi @RashminDungrani thanks for reporting, I will verify it.

**Comment by rangav** [comment]
what is the keyboard shortcut you are using?

**Comment by RashminDungrani** [comment]
i am using ctrl pageup - pagedown to switch open editors, I tried with default keybinding but that's not the issue.
mostly 3 or 4 times continuously switch from thunder client editor to another editor works but after that i have to use mouse for changing open editor.

**Comment by rangav** [comment]
thanks, will check and get back to you

**Comment by rangav** [comment]
I checked the mac key shortcuts, it is Tab + up/down arrow, its working for me.
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

**Comment by RashminDungrani** [comment]
workbench.action.nextEditor

**Comment by RashminDungrani** [comment]
workbench.action.nextEditor
workbench.action.previousEditor

**Comment by RashminDungrani** [comment]
These are the commands i use for switch editors

workbench.action.nextEditor
workbench.action.previousEditor

**Comment by rangav** [comment]
here is the screenshot of keymap - shf+cmd+ [ or ] working
![Screenshot 2021-07-22 at 13 23 42](https://user-images.githubusercontent.com/8637550/126638478-e4400af1-2bc0-4126-8226-0d0c1336c6a4.png)

Looks like there are multiple ways to navigation

- Shift+cmd+ [ or ]
- Ctrl + Tab + up/down arraw

Can you share your screenshot

**Comment by RashminDungrani** [comment]
![Screenshot 2021-07-24 at 9 06 31 AM](https://user-images.githubusercontent.com/48521608/126856286-8d3de117-2bf4-46aa-b0b8-21c2eaa84358.png)

**Comment by rangav** [comment]
Hi @RashminDungrani dont think this issue is related to thunder client, it could duplicate keybindings issue

https://stackoverflow.com/a/52321934/4035948
