### ISSUE TITLE
Add ability to upload a binary file as the body of a request

### ISSUE THREAD

**Issue by supernoodles** [rangav/thunder-client-support#273]
It would be great to be able to attach a binary file to be the body of a request (just like you can in Postman).

**Comment by rangav** [comment]
Hi @supernoodles will add this to roadmap.

**Comment by akarazeev** [comment]
Hi guys, I double this request :) I love using Thunder Client, but only for a couple of requests I had to use Postman because of a lack of binary body. Hope to see it someday in TC.

Thank you for great work!

**Comment by rangav** [comment]
Hi @akarazeev Planning to include this in the next update.

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
