### ISSUE TITLE
README: Cookie Names

### ISSUE THREAD

**Issue by brannonh** [rangav/thunder-client-support#275]
Just thought I would mention a gap in the documentation for accessing cookies. We use a hyphenated cookie name and couldn't find anything in the README about how to access it via `cookie.cookieName`. By trial and error, we figured out we could replace the hyphen (`-`) with an underscore (`_`). It would probably be a good idea to add that to the README.

**Comment by rangav** [comment]
Hi @brannonh thanks for the suggestion, will update the documentation. 

You can also update documentation by submitting PR, if you like to.

**Comment by rangav** [comment]
`cookie.cookie-name` is working without using underscore `_`

**Comment by brannonh** [comment]
@rangav Thanks, we just discovered the same thing. Not sure what happened the first time. Sorry for the invalid issue.

**Comment by rangav** [comment]
No problem @brannonh
