### ISSUE TITLE
Support use of OS system environment variable as global variable

### ISSUE THREAD

**Issue by ajaydwarkani** [rangav/thunder-client-support#276]
**Is your feature request related to a problem? Please describe.**
- I want to share the `thunderEnvironment.db` with my teammates as it has a lot of other variables that are not secret. For not I am not committing this file to Git due to security risk of exposing secrets.

**Describe the solution you'd like**
Add support for using OS system environment variable.
For example, if I have an OS system variable as `API_TOKEN=some-value` then I should simply be able to consume it in thunder client as `{{API_TOKEN}}` or `{{#API_TOKEN}}` without needing to import or declaring it.

**Describe alternatives you've considered**
Presently, I am not sharing the `thunderEnvironment.db` and share the file as needed basis via cloud drive/email.

**Comment by rangav** [comment]
Thanks @ajaydwarkani will add this to roadmap.

**Comment by VanCoding** [comment]
+1 for this as it would also add direnv support!

**Comment by rangav** [comment]
one question:
What happens if the same variable exists in` Active Env` & `OS Env`? which one should it take?

**Comment by ajaydwarkani** [comment]
@rangav , Here are my thoughts, if both environment variables name is same then `Active Env` should overwrite `OS Env`. If possible add a warning note next to `Active Env` that there is a `OS Env` already exists with the same name.

**Comment by rangav** [comment]
Thanks @ajaydwarkani for clarifying.

**Comment by umernalla** [comment]
Hi @rangav - I found the .env file support which I had not noticed. This works well for me too - since I occasionally use a .env file for the credentials.
Excellent stuff- thank you!

**Comment by rangav** [comment]
Hi All, This feature will be part of next update.

**Comment by umernalla** [comment]
Excellent news - thanks.
FYI - you probably already know this but in the VS Code launch.json file, the OS envs are accessed in the following format:

"-username",  "**${env:MY_LOGIN}**",
"-password", "**${env:MY_PASSWORD}**",
"-clientId","**${env:APP_KEY}**"

**Comment by rangav** [comment]
This feature is now implemented, please update to version `v1.16.4`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.4

**Comment by rangav** [comment]
Hi All, can you let know any feedback on this.

Is it working as you expected?

**Comment by ajaydwarkani** [comment]
@rangav, Thank you for implementing this. I have tested it in my environment for both Mac and Windows and it's working perfectly as expected. 

You ROCK!

**Comment by rangav** [comment]
Thanks @ajaydwarkani for confirming :)
