### ISSUE TITLE
Store relative path of files included in a request body multipart form data

### ISSUE THREAD

**Issue by alejandrofdez-us** [rangav/thunder-client-support#277]
I have some example assets at my project, such as example avatar images, that I use in my sample requests. These assets are stored under myproject/example_api_client/example_assets.

I want to share my requests and tried both alternatives: a)exporting requests and environment and adding these json files to my git and b) activating team features selecting myproject/example_api_client/thunder-tests

In both alternatives my files paths are stored including the complete path (showing my file system structure) and when it is imported by another contributor it obviously doesn't work, forcing contributors to select assets again for each of the requests involving files.

Is there any workaround for this o some way of storing relative paths for files in a request body of type form data?

Thanks in advance.

**Comment by rangav** [comment]
Hi @alejandrofdez-us thanks for suggestion, Will think about how to fix this issue.

**Comment by rangav** [comment]
This feature is now implemented in v1.8.0, to use relative paths, execute those requests it will automatically convert to relative paths

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
