### ISSUE TITLE
Horizontal split layout

### ISSUE THREAD

**Issue by Nzent** [rangav/thunder-client-support#280]
**Is your feature request related to a problem? Please describe.**
Default vertical split layout sometime not enough space to response text (need to resize the column)

**Describe the solution you'd like**
Suggest horizontal split option (top query section , bottom response section)

![Desktop Screenshot 2021 07 27 - 08 36 09 55 (2)](https://user-images.githubusercontent.com/26079832/127089657-4c178cef-0933-489f-874d-5067b498906c.png)

**Comment by rangav** [comment]
Hi @Nzent there is full screen button in the bottom right

**Comment by Nzent** [comment]
I think horizontal split still useful , no need to toggle 
but thank you for fast response 🎉

**Comment by rangav** [comment]
If you are in split mode it will show in up/down layout

**Comment by jandreaucodes** [comment]
How do you get Thunder Client into split mode (as mentioned in the above comment)?

If I split VS Code itself, Thunder Client stays in a single pane, split vertically.

**Comment by rangav** [comment]
Hi @jandreaucodes 

see the video link
https://youtu.be/ycTPdsnXFF8

**Comment by jandreaucodes** [comment]
Got it @rangav. Is there a roadmap item for splitting Thunder Client by itself? I don't want to have it only take up half my screen being split with other things.  I want top half to be my query and bottom half to be the response.

**Comment by rangav** [comment]
@jandreaucodes will provide option in settings in future release

**Comment by rangav** [comment]
<img width="987" alt="settings" src="https://user-images.githubusercontent.com/8637550/184168346-f1b5bc6a-fe01-4b0d-89e0-3a2c7d0e1b84.png">

This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
