### ISSUE TITLE
Activity not added

### ISSUE THREAD

**Issue by Jacques-eMediaIT** [rangav/thunder-client-support#281]
**Describe the bug**

Nothing is being added to the activity list when performing get requests.

**To Reproduce**

Maybe I misunderstand the activity list, but no items are being added?

**Expected behavior**

Activity list should show history of get / post / etc.

**Platform:** 
 - OS: Win 10 64
 - vscode version: 1.58.2
 - extension version: 1.8.0

**Solution:**

**Comment by rangav** [comment]
Hi @Jacques-eMediaIT Did you request from by clicking New Request button? Or you are running requests from collection.

related issue https://github.com/rangav/thunder-client-support/issues/236#issuecomment-886723089

**Comment by Jacques-eMediaIT** [comment]
I tried both ways, new request and from a collection.

**Comment by rangav** [comment]
Can you share a screenshot or a video?

**Comment by pavloskl** [comment]
I can confirm that this bug is also happening to my installation. 

- Windows 10 Pro (fully updated)
- Visual Studio Code 1.58.2
- TC v1.8.0

**Comment by rangav** [comment]
Did you open that request by clicking **New Request** button? 

can you enable this vscode setting and see if it works

![Screenshot 2021-07-27 at 13 51 37](https://user-images.githubusercontent.com/8637550/127156589-fcba7548-a087-4099-8d0c-63f1ac9b010f.png)

**Comment by rangav** [comment]
can you share a screenshot of collection tab also

**Comment by pavloskl** [comment]
I did not save anything in "Collections" tab (yet). I only created a new collection "New API"

![image](https://user-images.githubusercontent.com/5225388/127157198-c79f7ed5-df2c-4cc3-b977-549496d6e8d8.png)

**Comment by rangav** [comment]
Ok thanks I will verify and fix asap

**Comment by rangav** [comment]
Just now released v1.8.1 to fix this bug, please update and let me know.

Thanks for reporting this important bug.

**Comment by pavloskl** [comment]
I can confirm that I can see the activity of my calls now. The issue is fixed. 

![image](https://user-images.githubusercontent.com/5225388/127168539-739dcf42-7fc6-45bf-9c20-800efcd7fc40.png)


Thank you @rangav

**Comment by rangav** [comment]
Thanks @pavloskl for confirmation 👍
