### ISSUE TITLE
Content length header auto set to body text length 

### ISSUE THREAD

**Issue by Aazih** [rangav/thunder-client-support#283]
I'm testing an API that demands content-length be set on header for text payload. But I'm unable to find a way for this header to be automatically populated with the bytelength of the text payload as per HTTP standard

**Describe the solution you'd like**
Would like to have content-length be populated automatically in some fashion so it can be easily included as a header.

**Comment by rangav** [comment]
Hi @Aazih will research on this.

How you do this in other api clients?

**Comment by Aazih** [comment]
soap Ui puts it in as a default header though it's a bit buggy about it, which is what I'm trying something else. It also has options to accommodate chunked payloads but I don't know those workflows.

**Comment by webhype** [comment]
Need this too urgently. Postman does this with an option to calculate that header's value automatically.

Even something very simple, like a text field that counts the correct number of body bytes and displays them always as I edit the body. I can then manually copy/paste the current content-length into the raw headers.

**Comment by rangav** [comment]
Hi All, when you use send `body` the extension is automatically sending content-length header with correct value.

Is that what you are looking for?

<img width="1413" alt="Screenshot 2022-05-18 at 19 57 31" src="https://user-images.githubusercontent.com/8637550/169133857-7710f2b5-28be-4684-b1e7-e7a83be92756.png">

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
