### ISSUE TITLE
Ability to save request results as a file

### ISSUE THREAD

**Issue by harleybl** [rangav/thunder-client-support#284]
Some of the APIs that I call return large documents or CSV files. I bring these files into other applications like Excel for analysis while I am experimenting. To capture the results I could select all, copy, open a new file, paste, and save the file.
It would be nice if there was a way to download the contents and save them as a file either via a button or the right-click menu.

**Comment by rangav** [comment]
Hi @harleybl, thanks for the feedback will add to roadmap.

Is this similar to https://github.com/rangav/thunder-client-support/issues/141

**Comment by harleybl** [comment]
@rangav  - Sorry for the duplicate - I didn't see #141, otherwise I would have just +1'd it.

**Comment by rangav** [comment]
No Problem @harleybl
