### ISSUE TITLE
Add Convert Javascript Object to JSON

### ISSUE THREAD

**Issue by hadnet** [rangav/thunder-client-support#285]
**Describe the solution you'd like**
When coding I model a JS object with many props and then I need to test it using a POST endpoint that request that object model. So it would be great to just copy that JS modeled object and paste it in the request json content and the convert that JS object to a JSON object. Currently in order to avoid doing all that transformation manually I use https://www.convertsimple.com/convert-javascript-to-json/. It would be great if Thunder could have got that Js to JSON function feature in a button (or refactor the already Format button in order to convert JS to JSON as well):
<img width="511" alt="Screen Shot 2021-07-31 at 3 28 31 PM" src="https://user-images.githubusercontent.com/13828833/127750086-aaabc53a-49b5-4031-bd8b-3bbdbf8d5b24.png">

**Comment by rangav** [comment]
Thanks @hadnet will add to roadmap.

**Comment by rangav** [comment]
Hi @hadnet  this is now implemented, its easy fix. The `Format` button will format it JS object to json automatically.

This will be part of next update.

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
