### ISSUE TITLE
Script to C# etc does not include 'File' form body fields

### ISSUE THREAD

**Issue by JYouren** [rangav/thunder-client-support#288]
The script to <insert language here> feature is very nice, however it does not include 'File' form fields. I would expect something like

content.Add(new ByteArrayContent(File.ReadAllBytes(@"C:\some\file.ext")), "file", "<default to filename of selected file>");

To be output when a file is selected for a form entry (under body tab).

**Comment by rangav** [comment]
Hi @JYouren, thanks for feedback, will include file option in the next update

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
