### ISSUE TITLE
Add url to status, size and time section

### ISSUE THREAD

**Issue by andrewperkins** [rangav/thunder-client-support#289]
**Is your feature request related to a problem? Please describe.**

Right now there is no way to see the full URL with the variables after you send it. 

**Describe the solution you'd like**

In the section where you have Status, Size, and Time include a space for the url
![Screen Shot 2021-08-03 at 8 49 47 AM](https://user-images.githubusercontent.com/42021047/128037207-f3a997a6-becb-4aad-90e0-4894ab71e670.png)

**Comment by rangav** [comment]
Hi @andrewperkins thanks for feedback. Planning to implement logging to console output, where you see url, headers etc

**Comment by rangav** [comment]
Hi @andrewperkins, the url is now displayed in output window in v1.9.0
