### ISSUE TITLE
Are you planning of making this project Open Source?

### ISSUE THREAD

**Issue by imrishabh18** [rangav/thunder-client-support#29]
I really loved this project. Would be glad if I could contribute in some way.😃

PS - Feel free to remove this issue. I couldn't contact you via Twitter or LinkedIn so made this issue. 😅

**Comment by rangav** [comment]
Hi @imrishabh18 have to plans to open source some parts of the project at later stage.

Currently if you want to contribute, you have to create a sample node or .net app for a particular feature. let me know which feature you like to contribute i will guide you further..
