### ISSUE TITLE
Add a folder (like ".thunder-client") to auto import all collections and environment files

### ISSUE THREAD

**Issue by leandroluk** [rangav/thunder-client-support#290]
**Describe the solution you'd like**
Hello, in each project I have a folder called "postman" where I export all the collections and environment variables for that and so I can manage changes in these files. It would be nice if the plugin could read from this or some folder when opening the project in VSCode so that it is not necessary to keep importing file-by-file when opening a folder

![image](https://user-images.githubusercontent.com/8602982/128051397-d1758ca1-52f8-471f-b605-539b42f05158.png)

**Comment by rangav** [comment]
Hi @leandroluk thanks for feedback

is it similar to #62

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.

Currently No plans to read directly from postman files

**Comment by charalamm** [comment]
Hi @rangav. To extend the idea of this feature request, it would be nice to have a commited folder where the project's thunder client environment and collection files exist and that get updated automatically upon changes on the requests.

That way a developer could easily keep the repo updated with latest versions of thunder client requests and other developers could immediately use the said requests.

**Comment by rangav** [comment]
@charalamm 

Are you referring to Git Sync feature 
https://github.com/rangav/thunder-client-support#git-sync

**Comment by charalamm** [comment]
Oh, that is probably it thanks!
