### ISSUE TITLE
Global environment variable not set after request sent

### ISSUE THREAD

**Issue by IamCrypt0n** [rangav/thunder-client-support#291]
**Describe the bug**
A global defined evironment varibale is not set after receiving the JSON repsponse body.
I defined a global environment variable to store a JWT received by the API. Under the "Test" section I defined a test with as following: "json.jwt - setTo - {{JWT}}". The "{{ JWT }} is being highlighted green and there definelty exists a jwt property in the response body. 

**To Reproduce**
1. Define a global environment variable called JWT
2. Create a PUT request sending properties called "emailAddress" and "password" to the API.
3. Unter "Tests" define a test with "columns: json.jwt - setTo - {{JWT}}
4. Send request to an API that returns a JSON object with a property called jwt

**Expected behavior**
I expect my global environment to be set according to the response bodys jwt property.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.58.2
 - extension version: 1.8.1

**Comment by rangav** [comment]
Hi @IamCrypt0n, Current it will set variable in `active environment` not global, 

Do you have both active env and global env?

**Comment by IamCrypt0n** [comment]
Hi rangav,
as you said only variables in an active environment are set. To bad that global envs are read only :( 
So this isnt actually not a bug. Would be a cool feature setting global env variables :)

**Comment by rangav** [comment]
In the next update, you can set using scope

example global scope : `{{JWT, global}}`

**Comment by IamCrypt0n** [comment]
Nice, im look forward to use it then :) Thank you for your time and this nice tool :)

**Comment by rangav** [comment]
you are welcome :)
