### ISSUE TITLE
What is "thunder-client.enableSaveOption"?

### ISSUE THREAD

**Issue by Leccho** [rangav/thunder-client-support#293]
This is more a support question, but I have `thunder-client.enableSaveOption` in my `setting.json` which I forgot what it was for. I would also like to know what it has been replace with. Thank you!

You could also add Support request in your Github issues.

**Comment by rangav** [comment]
Hi @Leccho that vscode setting is now removed- deprecated.

what version of extension you are using?

thanks for suggesting will add new issue type for support

**Comment by Leccho** [comment]
I got 1.8.1 and it's not recognizing the option so it's working fine. I set that option on an earlier version, that's why it's still there.

**Comment by rangav** [comment]
You can use `cmd/ctrl + s` now to save request

**Comment by Leccho** [comment]
does it work with vscode autosave too ?

**Comment by rangav** [comment]
no - not yet implemented auto save. have plans in near future
