### ISSUE TITLE
The pasted text is doubled

### ISSUE THREAD

**Issue by pacifist-inside** [rangav/thunder-client-support#294]
- When pasting text into Body or Address fields of a request it's pasted twice.
- When pressing Ctrl+Z the previous text is added to the end of string instead of replacing it. Sometimes it just doesn't change anything (the text does not change)
- After some unknown actions the behaviour changes back to normal: the text is replaced and stops doubling.

**Comment by rangav** [comment]
Hi @pacifist-inside, thanks for feedback 

The issue is be related to undo/redo #146 

undo and redo not yet implemented

**Comment by pacifist-inside** [comment]
Oh, sorry then for undo.

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
