### ISSUE TITLE
Load body from json file

### ISSUE THREAD

**Issue by bojanpikl** [rangav/thunder-client-support#296]
I am using the Thunderclient and have configured it to load collection from the repository which is currently loaded. It is awesome. Thanks for that.

I have example json requests in my project. The same json can be used in API requests. Currently, I need to copy it to Thunderclient request. And when it is changed, the change needs to be applied to 2 places consiquently.

It would be great if I could add path where the request body should be read from in the form of relative path to some json file in my repository.

**Comment by rangav** [comment]
Hi @bojanpikl thanks for the feedback, will review about this request.

**Comment by bombillazo** [comment]
Also looking forward for this feature!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.3.0`

Steps are listed in this link
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.
