### ISSUE TITLE
Thunderclinet doesnt support any token endpoint auth methods apart from none?

### ISSUE THREAD

**Issue by mcrobbj** [rangav/thunder-client-support#297]
**Is your feature request related to a problem? Please describe.**

Having an issue with Thunderclient and OKTA as there doesnt seem to be any way to select the token endpoint auth method.
It only seems to support none? Hard to tell as you cant see the request (on thunderclient, on OKTA you dont see the request syntax just the failure)
types can be none, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt

**Describe the solution you'd like**

Would be nice to see the request that goes to the OIDC provider, but ultimately beable to select the token endpoint auth method. If its only none they make that explicit in the generate token tab.

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @mcrobbj can you share auth screenshots on TC, hide out any secrets.

that will give better understanding what you sending and the problem

**Comment by rangav** [comment]
What is `token endpoint auth method`? Did not understood your question? 

We have oauth2 Authenticator

**Comment by mcrobbj-abrdn** [comment]
Can close this for OKTA the Send Auth as request body needs to be used for Oauth or you get this spurious error

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
