### ISSUE TITLE
Run a request multiple times 

### ISSUE THREAD

**Issue by MaxiDutra** [rangav/thunder-client-support#298]
There is any way to run a single collection multiple times ?

**Comment by rangav** [comment]
Hi @MaxiDutra what is your use-case for this? Trying to understand how it’s useful to you?

**Comment by MaxiDutra** [comment]
In my case i generate a ticket with random data and for test the API i would like to seend multiple times the same request kind of 
api load test

**Comment by rangav** [comment]
Thanks got it. Will add this feature for next update.

**Comment by rangav** [comment]
there is a similar request earlier #95

**Comment by rangav** [comment]
I am closing this issue, as we already have existing issue #95, we can track it there.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
