### ISSUE TITLE
What led to the decision to not open source the project?

### ISSUE THREAD

**Issue by hichemfantar** [rangav/thunder-client-support#299]
A lot of devs such as myself don't want to start relying on this tool due to its closed source nature.

The problem is in case the project maintainer decides to drop the project for whatever reason, then we can't simply fork it and continue developing it.

In this case, the extension will left be to die without any updates and eventually become full of deprecated APIs and bugs.

I honestly want to know the reason the developer decided to not open source the project.

**Comment by rangav** [comment]
Hi @hichemfantar few users asked the same question before, my answer below

Not all open source projects are not maintained well, they end up into deprecated/not-active status. 

If we open source this it will become commercially unviable to develop and maintain. also there is be clone's of the software by others. 

If I abandon the project for what ever reason, then I will definitely open source it. 

But current plans are to develop and maintain for long-term. and also launch paid plans at later stage.
