### ISSUE TITLE
Open in new tab from collection does not open a new tab.

### ISSUE THREAD

**Issue by migueLoureiro** [rangav/thunder-client-support#300]
**Describe the bug**

Open in new tab button on "..." on a collection does not open a new tab, just focus window on the one tab opened.

**To Reproduce**

1. Go to Thunder Client extension page
2. Open collections tab
3. Choose a collection click on it
4. Choose a Request previously saved
5. Click on "..." on the right bottom of the request
6. Click "Open in New Tab" from the dropdown menu

**Expected behavior**

Create a new tab with the request from collection.

**Actual behavior**

Focus the window on an already open request of the same kind clicked.

**Platform:** 
 - OS: Mac OSX 10.15.7
 - vscode version: 1.59.0
 - extension version: 
```
Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 wk ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0
```

**Solution:**

The new request should open in a tab rather than focus on an already opened tab.

**Comment by rangav** [comment]
HI @migueLoureiro thanks for reporting the issue, I will verify and fix it.

**Comment by rangav** [comment]
one question- how did open the first request?

**Comment by migueLoureiro** [comment]
I tried 2 ways:
1. Double-click the request inside the collection
2. Without anything open, click on "..." and click on "Open in New Tab"

Both ways, opening the 2nd time using the "...">"Open in New Tab" always results in window focus on the 1st request open rather than actually opening a 2nd one in a new tab.

**Comment by migueLoureiro** [comment]
As a workaround I have been duplicating the request opening it and then deleting it.

**Comment by rangav** [comment]
are you trying open the same request twice?

**Comment by migueLoureiro** [comment]
yes, I have to have multiple tabs open with the same request. As the option suggests: "Open in a New Tab" should have multiple, more than one, tabs with the same request.

**Comment by rangav** [comment]
I open the first request by click
and 2nd request by open in new tab, it did work as expected.
<img width="1231" alt="Screenshot 2021-08-18 at 14 16 23" src="https://user-images.githubusercontent.com/8637550/129904818-db69f99b-2efd-4289-a323-dc1af2bc486f.png">

**Comment by migueLoureiro** [comment]
You have 2 different requests open. I can want to have multiple tabs of the `same request` open.

**Comment by rangav** [comment]
Oh ok - That wont work 
If the request is already open, then it will try to open in that same tab.

**Comment by migueLoureiro** [comment]
Than the option "Open in a New Tab" is wrong. because it is not opening in a new tab. It may be the intended behaviour. But the name of the feature is missleading. and this would be a feature request rather than a bug report?

**Comment by rangav** [comment]
its a feature request.

**Comment by rangav** [comment]
thats fine we can use this request.

**Comment by migueLoureiro** [comment]
thanks for the very quick and on point replies. cheers! 👍

**Comment by rangav** [comment]
you are welcome 👍, will implement this in the next update.
