### ISSUE TITLE
Make tab display the full name of the request

### ISSUE THREAD

**Issue by Kents-Consulting** [rangav/thunder-client-support#301]
When working with a request within a collection, can you make the TAB text be more than 13 characters? I would like to see the full name of the request in the tab so that I can tell which request I'm working on.  Thanks!

**Comment by rangav** [comment]
Hi @Kents-Consulting thanks for the feedback, will update in the next release

**Comment by rangav** [comment]
Is 20 chars length good for you?

**Comment by Kents-Consulting** [comment]
Hi rangav, 

20 to 25 chars would work for most situations.  Most names are approximately 18 characters. There are a couple that are 24 characters in length. However, I have not had a name longer than 24 char. 

Thanks for take a look at this so quickly.

**Comment by rangav** [comment]
This feature is now implemented in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

The title length increased to 25 chars length

please let me know if any feedback
