### ISSUE TITLE
graphql is not working

### ISSUE THREAD

**Issue by c0ffeec0der** [rangav/thunder-client-support#302]
**Describe the bug**
sending request in graphql is not working, the query is not passed

**To Reproduce**
send any graphql request (see in raw window, the query is not passed)

**Expected behavior**
query is sent

![2021-08-19 21_57_23-Window](https://user-images.githubusercontent.com/64681762/130091676-1e9ef13c-ffbd-4a8e-a570-141031882c50.jpg)

**Comment by rangav** [comment]
Hi @c0ffeec0der graphql not yet supported in Code Snippet. Will add support in the next update

**Comment by c0ffeec0der** [comment]
Hi @rangav, Thank you for the update

**Comment by rangav** [comment]
This feature is now implemented in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
