### ISSUE TITLE
Allow users to select which token to use in Oauth2 flows (id_token instead of access_token)

### ISSUE THREAD

**Issue by cjuega** [rangav/thunder-client-support#304]
**Is your feature request related to a problem? Please describe.**

Some API use **id_token** instead of **access_token** to authenticate a user. For instance: Amazon Cognito, Auth0, Azure AAD, etc. These IDPs typically return three tokens when using an Oauth2 flow: **id_token**, **access_token** and **refresh_token**; however, thunder client only exposes **access_token**. That means, APIs behind these IDPs can't be reaching using this client.

**Describe the solution you'd like**

It would be nice if we could select which token we want to send as part of the request when OAuth2 flow is being used.

**Describe alternatives you've considered**

The only alternative I can think of is to perform the login separately (in a different tool) and copy the **id_token** manually into thunder client. But that effectively turns thunder client useless in these scenarios. Nobody wants to be switching between tools. Plus, nowadays Oauth2 flows are more and more common, so I believe this is a fair request.

Apparently this is an issue in Postman too, they have at least 10 issues opened regarding this since 2014. It seems they have taken this into consideration according to https://github.com/postmanlabs/postman-app-support/issues/8231

**Comment by mathieubrd** [comment]
7 years.

**Comment by donrolling** [comment]
@rangav OneLogin returns id_token. - https://developers.onelogin.com/openid-connect

Thanks for taking a look at this. I'd be happy with any solution that let me grab and store any of the values in the response from the "Get New Access Token" button on the Collection Authorization.

**Comment by rangav** [comment]
Hi All

finished implementing this feature, will release the next update later today.

see screenshot, let me know your feedback
<img width="778" alt="Screenshot 2022-06-15 at 15 40 01" src="https://user-images.githubusercontent.com/8637550/173855972-e3f5231b-a451-48ed-8a04-a21aeb993d6d.png">

**Comment by rangav** [comment]
Hi all, Can anyone let me know if it's working correctly as expected? Or any feedback?

**Comment by jdemovic** [comment]
Works like a charm.
Great work.
Thanks!
