### ISSUE TITLE
Make input URL friendly to edit

### ISSUE THREAD

**Issue by aswinkumar863** [rangav/thunder-client-support#308]
**Is your feature request related to a problem? Please describe.**
I found that the request URL input box is extremely hard to edit long URLs. Because it lacks scrolling forward and backwards. Fails to scroll on `shift + scroll` also.

![image](https://user-images.githubusercontent.com/32381261/131221301-eb41264a-c2d6-4156-9cda-5d6472a2f7ef.png)

**Describe the solution you'd like**
Making the request URL input box scrollable or display the full URL on focus will be the solution.

**FYI..Postman showing full URL on focus**
![image](https://user-images.githubusercontent.com/32381261/131221161-f67ceadb-7e9d-4ee4-a385-a275d0a0709a.png)

**Comment by rangav** [comment]
Hi @aswinkumar863 thanks for the feedback, will look into this issue.

**Comment by JFernando122** [comment]
I do think that is a great suggestion, but i think you could "reduce" the length of that url by using some env variables, like for the base url or for what i think is an id for something, so you could have something like
`{{base_url}}/citation-style-language/locales/{{locale}}/locales.json`

**Comment by jetz** [comment]
Same problem， It's hard to edit long URL, can't scroll by mouse.

**Comment by rangav** [comment]
Hi Guys, I was thinking about what is the best solution for this.

When a user performs action the Url field expands to full width, could be keyboard shorcut or mouse click etc.

![Screenshot 2022-01-29 at 11 40 24](https://user-images.githubusercontent.com/8637550/151659736-d7c7082c-4657-445f-980a-e05b3d7b3de3.png)

Let me know your feedback?

**Comment by aswinkumar863** [comment]
@rangav I think mouse click or `focus` would be more user friendly

**Comment by rangav** [comment]
I have fixed the `shift + scroll` problem, would you like to test and confirm?

[vscode-thunder-client-1.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/8470084/vscode-thunder-client-1.16.1.vsix.zip)

Download the attachment and install vsix manually as below
<img width="533" alt="Screenshot 2022-04-12 at 07 26 55" src="https://user-images.githubusercontent.com/8637550/162894687-4aea1d35-feeb-4d08-a217-3677d47451b5.png">

Please let me know your feedback

**Comment by rangav** [comment]
Super thanks for confirmation 👍
