### ISSUE TITLE
Plans for opensourcing the plugin?

### ISSUE THREAD

**Issue by Rikihanks** [rangav/thunder-client-support#309]
The plugin is nice but since its free to use I'm wondering if theres any plans to open source it. I don't feel entirely confortable without knowing whether my info is reaching a 3rd party server or not.

**Comment by rangav** [comment]
Hi @Rikihanks currently no plans to open source.

and no data is sent any servers, all the data is stored locally on your pc.

read more here
https://github.com/rangav/thunder-client-support#privacy
