### ISSUE TITLE
Vim Key bindings for Body.

### ISSUE THREAD

**Issue by JoshTRN** [rangav/thunder-client-support#31]
I'm not sure what you're using for the input field for the body, but I have my editor set up to used vim key bindings. I actually integrated neovim into the editor itself. Sadly, this doesn't work for the input box you made. I hope, if it's not too difficult, this input box could enjoy support for vim key bindings.

**Comment by rangav** [comment]
Hi @JoshTRN I will look into this.

**Comment by aNickzz** [comment]
I was going to raise a bug about vscode shortcuts not working in the body input, but I'll +1 this issue instead and just say weird things happen when I try to use the shortcuts I usually use.

For one example; `ctrl+k, ctrl+d` is "format document" but in the json and xml editors it seems to be `ctrl+k` "find next match" and `ctrl+d` delete line.
No shortcuts work in the text editor other than the basic cut/copy/paste.

I think the "correct" solution for this would be to embed vscodes built-in Monaco editor and rely on the existing functionality there.

**Comment by rangav** [comment]
Hi @aNickzz thanks for the feedback

initially I tried to integrate Monaco editor, it was not possible due to vscode limitations 

I am implementing ALT + SFT +F to format code.

In Visual Studio, the shortcut for Code Formatting is Ctrl+k Ctrl+D but in Visual Studio Code, it's Shift+Alt+F

**Comment by aNickzz** [comment]
You are right, when started using VSCode I was also using Visual Studio, and I found it easier to rebind VSCode than VS.

In any case, I hope the situation with monaco changes, though I do wonder how the [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) extension works, as it includes embedded text editors, though I couldn't get it to format any code (even by the command palette)

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
