### ISSUE TITLE
vscode settings options

### ISSUE THREAD

**Issue by nelson-andrew** [rangav/thunder-client-support#310]
Is there a sample of the vscode settings?

**Comment by rangav** [comment]
Hi @nelson-andrew, which vscode setting are you looking for?

**Comment by nelson-andrew** [comment]
Hi there,

The thunder client settings for team support.

Cheers

**Comment by rangav** [comment]
Open vscode settings view and search `thunder` keyword

Then you have 2 option as shown in below screenshot, use any one which suits your needs

more details about each option is here
https://github.com/rangav/thunder-client-support#team

<img width="955" alt="Screenshot 2021-09-01 at 04 29 51" src="https://user-images.githubusercontent.com/8637550/131607589-c96a7c23-f4e6-400f-9a5f-f7bfa161b242.png">

**Comment by nelson-andrew** [comment]
Brilliant! that worked a charm.

Thanks

**Comment by rangav** [comment]
you are welcome 👍
