### ISSUE TITLE
Binary File Download (or Render)

### ISSUE THREAD

**Issue by robinhalabicki** [rangav/thunder-client-support#311]
**Is your feature request related to a problem? Please describe.**
If your response is a binary file, it renders the binary.

**Describe the solution you'd like**
Give the option to download the file Or render the file in the window (postman does this)

**Comment by rangav** [comment]
Hi @robinhalabicki thanks for feedback will add to roadmap

**Comment by robinhalabicki** [comment]
Feature Requested
