### ISSUE TITLE
In WSL Thunder Client fails to post file in request since it takes windows path not WSL Path

### ISSUE THREAD

**Issue by sushantg2001** [rangav/thunder-client-support#313]
**In WSL Thunder Client fails to post a file in request since it takes windows path not WSL Path**
While using WSL extension in vscode, if we try to send a file in the POST request, it fill give "ENOENT: no such file or directory, stat '{file_path}'". This is because, the path for the same file changes in WSL. For example - if a file path is C:\files\test.csv then in WS:  it will be /mnt/c/files/test.csv. However if you open a new window for vscode with windows instead of WSL and run the same request it will work.

**Platform:** 
 - Windows: 

**Solution:**
If working in WSL change the path of the file while sending 

Error in WSL
![image](https://user-images.githubusercontent.com/58122819/132027905-bd5c68d1-ec76-413b-b1bc-14c9450794ee.png)
![image](https://user-images.githubusercontent.com/58122819/132027987-b18f177c-d031-4489-a0e9-3e7a28246744.png)

Working in Windows
![image](https://user-images.githubusercontent.com/58122819/132028075-a81363f4-8087-47bb-98b9-8edbb4945758.png)

**Comment by rangav** [comment]
Hi @sushantg2001 

Please see the solution in this comment https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
