### ISSUE TITLE
Add a Base Url To Collections.

### ISSUE THREAD

**Issue by VanshCodes** [rangav/thunder-client-support#316]
**Is your feature request related to a problem? Please describe.**
When we developed an app, We use localhost as the base URL but when we deploy it we use a domain-based Solution so we have to change the Base URL again in the collections tab

**Describe the solution you'd like**
My Solution is to provide a BASE_URL var while making a collection and just append it when the 'Send Request' Button is clicked.

**Comment by rangav** [comment]
Hi @VanshCodes you can use environment variable for this right? and use `{{baseUrl}}`

**Comment by VanshCodes** [comment]
But still doesn't it look like a basic feature.
It should be there since it has to be repeated in every collection>request.
So I think that a new collection should have a baseURL option.

**Comment by rangav** [comment]
Does any other client has this feature?

**Comment by VanshCodes** [comment]
Well postman doesn't seem to have it.
And I haven't used much api clients after thunder client.
So I don't think anyone has this feature.

**Comment by rangav** [comment]
Ok then environment variables is the solution for this problem. Most users use `baseUrl` variable in environment and change environment accordingly as needed when testing.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
