### ISSUE TITLE
[Support] Please release Thunder Client to VScodium

### ISSUE THREAD

**Issue by kevinadhiguna** [rangav/thunder-client-support#317]
Hi, thank you for your very nice work on Thunder Client!

I hope it will be available on [VS codium](https://vscodium.com/) as well.

![image](https://user-images.githubusercontent.com/43397636/132327308-86849ba3-6cb0-4bb0-a0b4-805f098465cb.png)

Thank you

**Comment by rangav** [comment]
Hi @kevinadhiguna duplicate of #30

**Comment by rangav** [comment]
Hi, finally managed to publish to open-vsx, now you can download from extensions tab
https://open-vsx.org/extension/rangav/vscode-thunder-client

**Comment by kevinadhiguna** [comment]
Cool, much appreciated @rangav !

![image](https://user-images.githubusercontent.com/43397636/152913860-ecf9f7f6-8f5b-4935-857b-5074bca2d86f.png)
