### ISSUE TITLE
setTo for boolean values is not working

### ISSUE THREAD

**Issue by majso** [rangav/thunder-client-support#318]
**Describe the bug**
Not able to save true/false as environment variable with setTo Test function

**To Reproduce**
In Tests section use setTo as variable for boolean value from response for example "isDeleted": true

**Expected behavior**
Environment variable will be set to true or false accordingly

**Platform:** 
 - OS: Win 10
 - vscode version: 1.60
 - extension version: 1.9.1

**Comment by rangav** [comment]
Hi @majso thanks for reporting the issue, will verify and fix it ASAP.

**Comment by rangav** [comment]
Hi @majso I think this is fixed in v1.9.0, Please test it and re-open if needed.

**Comment by rangav** [comment]
Hi @majso I think this is fixed in v1.9.0, Please test it and re-open if needed.
