### ISSUE TITLE
event-stream subscribe request

### ISSUE THREAD

**Issue by Dipta-IIC-EU** [rangav/thunder-client-support#319]
**Is your feature request related to a problem? Please describe.**

I tried to send a request to a server, and the response is in the type of a subscription to an event stream. It seems that thunder collects all chunks of data until the response is "complete" , before showing it in the response page. Because this is a subscription, the response will never be "complete". As a result, the response page only shows the following:
![image](https://user-images.githubusercontent.com/85555091/132536008-bea9ba02-74a5-438e-91b0-80438ae7954d.png)

**Describe the solution you'd like**

It would be great if thunder can show the stream live, without waiting until the response is complete

**Describe alternatives you've considered**

I created a cURL script using thunder and then use a terminal to send the request. It works well in the terminal.

**Comment by rangav** [comment]
Hi @Dipta-IIC-EU will add to roadmap

**Comment by bioshazard** [comment]
Hello from the future, I would like this too please

**Comment by atambi802** [comment]
Hey I would also like this, It would be nice to have, all the web browsers have it today.

**Comment by rangav** [comment]
Thanks for the feedback, Will look into it asap.

Can you share any sample streaming URL for testing?

**Comment by bioshazard** [comment]
OpenAI completion endpoint is a good example. Can't share my live case.
