### ISSUE TITLE
Support change prefix in Bearer Token Auth

### ISSUE THREAD

**Issue by InDIOS** [rangav/thunder-client-support#32]
Hi and congrats for such a great work. It would be awesome if could be possible to set custom prefixes other than Bearer in Authentication section like Insomnia does. This feature could improve this awesome extension. 

Thanks for the effort and keep going forward with it

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.14.0`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.0
