### ISSUE TITLE
Response not copied when i select and press ctrl+c

### ISSUE THREAD

**Issue by saugat1** [rangav/thunder-client-support#322]
Why I can't copy response results. I selected all response and try to copy but nothing copied.

**Comment by rangav** [comment]
Hi @saugat1 thanks for reporting the issue.

ctrl + c should work, I will verify and get back to you.

Can you share your

- Your vscode version 
- Extension version 
- OS

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
