### ISSUE TITLE
The REST request keeps spinning and Cancel Request Button below does not work.

### ISSUE THREAD

**Issue by mboulatian** [rangav/thunder-client-support#323]
The REST request keeps spinning and Cancel Request Button below does not work. It disappears when hovered over but even then not clickable

**Comment by rangav** [comment]
Hi @mboulatian is it happening for all requests or for some requests.

Is it localhost url or production url?

**Comment by mboulatian** [comment]
Hi Ranga,

URL was a production URL but seemed to be down and the request was taking
too long. So, the right panel where the response was supposed to be
received, was spinning and below there was a link "Cancel Request". When I
was moving mouse over to click to cancel the request, it was disappearing.
Even though, I still tried to click on it but nothing was happening. The
only solution was to close the thunder client window.

I hope this helps. Thanks for the great product.
Misak

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
