### ISSUE TITLE
The client silently changes localhost to 127.0.0.1 (macOS Mojave)

### ISSUE THREAD

**Issue by eighthjouster** [rangav/thunder-client-support#324]
**Describe the bug**
If I make a request to http://localhost, the connection gets refused even though there is a local server listening for connections on localhost.

**To Reproduce**
1. Set up a local server listening for connections on localhost.
2. Make a request to http://localhost.
3. Thunder reports that the connection is refused.

**Expected behavior**
Thunder should connect to the local server and show response.

**Platform:** 
 - OS: macOS Mojave.
 - vscode version: 1.59.1
 - extension version: 1.9.1

**Solution:**

**Comment by eighthjouster** [comment]
Workaround: Have the local server explicitly listen for 127.0.0.1.

With other tools (e.g. HoppScotch), this workaround is not necessary.

**Comment by rangav** [comment]
What port the server is running on?

**Comment by eighthjouster** [comment]
Port 9000.  It seems like this is a duplicate of that issue.  Since the workaround seems to be enough, and that ticket was closed, then I'll close this one too.  Thanks!

**Comment by oaklandgit** [comment]
For anyone using json-server on Mac OS Monterey 12.5 with Thunder Client, the above solution worked for me.

Summarized: set the host to 127.0.0.1 and NOT localhost:
```
json-server -H 127.0.0.1 -p 4000 data.json
```
