### ISSUE TITLE
Parse Error: Header overflow

### ISSUE THREAD

**Issue by Mardenlr** [rangav/thunder-client-support#325]
**Describe the bug**
When I login in my API and get de result
![Error](https://user-images.githubusercontent.com/13383265/133188450-f7cf7b98-dcb7-455d-b124-2fb7722a2911.PNG)
[Result.zip](https://github.com/rangav/thunder-client-support/files/7158617/Result.zip)

**Expected behavior**
Show the result

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.60.0
 - extension version: 1.9.1

**Solution:**
Show the result of a post no matter the size of result

**Comment by rangav** [comment]
Hi @Mardenlr can you please share header tab screenshot

**Comment by Mardenlr** [comment]
Hi @rangav 

![image](https://user-images.githubusercontent.com/13383265/133267784-2c7a4c57-9925-4fc7-9266-7de715f04efe.png)

Has no result there

**Comment by rangav** [comment]
looks like the issue is with response headers length.

see possible solution here
https://stackoverflow.com/a/62336802/4035948
https://stackoverflow.com/a/67442440/4035948

**Comment by Mardenlr** [comment]
the same request in Postman works fine no problem, in Thunder Client give me a error, the links above not solve the problem

**Comment by rangav** [comment]
Ok, can you share any published url that has the same issue, so I can test here to identify the problem.

**Comment by Mardenlr** [comment]
Not at moment, but you can test with the file Result.zip he is attached in the first post in this tread, this is a json archive result from the service with postman

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open it if needed.
