### ISSUE TITLE
How to specify the certificate and the key for particular host

### ISSUE THREAD

**Issue by mboulatian** [rangav/thunder-client-support#326]
Hi. I  am trying to create a request that requires client certificates to be sent with the request. In the Postman, this is specified going to the settings at the top right corner and selecting certificates tab, then create an entry for the host and specify the file locations for the certificate and the key file.

I found some examples in GitHub support docs to specify in VS Code settings.json file as an entry. Here is my example:

"thunder-client.certificates": [
        {
            "host": "https://api.xyz.com",
            "certPath": "C:\\temp\\samplecert.cer",
            "keyPath": "C:\\temp\\samplecert.key",
        },
    ]

Then create the new request URL with the above host. Regardless what I do, I get a response that no valid certificate is found. This URL works in Postman.

Is this feature implemented? If yes, is my above example URL correct. I am on windows 10 computer.

Thanks,
Misak

**Comment by rangav** [comment]
Hi @mboulatian 

use `api.xzy.com` for host.
And please double check certificate paths are right

**Comment by mboulatian** [comment]
Thanks for the answer. It worked. I was mistakenly using https in front of it instead of just host name.

Thanks,
Misak
