### ISSUE TITLE
Nested Environments

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [rangav/thunder-client-support#327]
**Is your feature request related to a problem? Please describe.**
Trying to minimize the amount of duplication across environment files.

**Describe the solution you'd like**
Common environment could be included by other environment files.

E.g. Imagine an Env call `Common`.  It contains all the common environment variables.  Then create multiple environment files that include the `Common` env.  This saves duplicating of the `Common` env in each of the environment files that need it.

It would be great to support deeply nested environments.

E.g. one nesting example might be:
```
Common Env:
    Base environment variables

Component1 Env:
    Component-specific environment variables

Component2 Env:
    Component-specific environment variables

Product1:
    {{$INCLUDE Common}}
    {{$INCLUDE Component1}}
    {{$INCLUDE Component2}}
    Other Product-specific environment variables
```
_NOTE: I'm just skylarking with the syntax, treat it as pseudo-code only._

**Describe alternatives you've considered**
Some form of a deepMerge of JSON environment files.

**Implementation:**
N/A.

**Comment by rangav** [comment]
Hi @LiveFreeAndRoam 

we have global environment option for this,

from Env tab click menu icon and select `Enable Global Env`

**Comment by LiveFreeAndRoam** [comment]
That worked perfectly.  I didn't really understand how to use Global Env until you mentioned this.  Thanks!!

**Comment by rangav** [comment]
Thanks for confirmation 👍
