### ISSUE TITLE
Could not set Env Variable.

### ISSUE THREAD

**Issue by ktt9117** [rangav/thunder-client-support#329]
I tried to set the value (accessToken) in the response to an environment variable, but I got the following test result: What should I do?

![Screen Shot 2021-09-17 at 12 58 23 PM](https://user-images.githubusercontent.com/5284987/133722010-8370f8c4-13ff-4e43-889d-6f36101e1ed9.png)

```Set Env Variable not supported for Content-type: application/Json;charset=UTF-8```

**Comment by rangav** [comment]
Hi @ktt9117 thanks for reporting the issue,

I will verify and get back to you

**Comment by rangav** [comment]
Can you share screenshot of response headers tab

**Comment by ktt9117** [comment]
I am sorry for being late.
Here is the screenshot of response headers tab.
![Screen Shot 2021-09-24 at 12 16 48 PM](https://user-images.githubusercontent.com/5284987/134612960-f6120b79-7c2d-4304-8dc9-4a99bc5903b6.png)

**Comment by rangav** [comment]
Your content type header value `Json` J is capital word, that could be issue.

Is it possible to return content type `application/json;charset=UTF-8`

**Comment by ktt9117** [comment]
Thank you for helping me. I'll give it a try and close the issue if it works.
