### ISSUE TITLE
Auth at Collection and Folder Level

### ISSUE THREAD

**Issue by jongio** [rangav/thunder-client-support#33]
**Is your feature request related to a problem? Please describe.**

Yeah, don't want to enable auth for every request

**Describe the solution you'd like**

Allow setting Auth at collection and folder level

**Describe alternatives you've considered**

Not using OAuth provider

**Implementation:**

**Comment by rangav** [comment]
Hi @jongio Will add to the product roadmap list

**Comment by AllanJeremy** [comment]
Was about to write this! Agreed! Much as I love the client, can't use it when I have to set auth for every single request.

**Comment by rangav** [comment]
Hi all, will start work on this feature very soon...

**Comment by jongio** [comment]
@AllanJeremy  - In the meantime, you can create a new review to just make the OAuth request and then read the access_token into an env var and then read that in other requests.  Or just wait until this is implemented.

The way I do it here - I put as much as I can into env vars so having in each request is not as bad.

https://blog.jongallant.com/2021/04/azure-rest-apis-vscode-thunder-client/

**Comment by AllanJeremy** [comment]
Thanks @jongio !
I'd reverted to Postman. Definitely gonna do that. Cheers.

**Comment by cnshenj** [comment]
Two other requests related to auth:
1. Show the expiration time like Insomnia (e.g. will expire in 1 hours, expired 1 day ago).
2. Automatically refresh the auth token when sending a request but the auth token is already expired.

**Comment by rangav** [comment]
Hi all, This feature will be part of next update v1.9.0

**Comment by jongio** [comment]
Awesome!  Thank you

**Comment by rangav** [comment]
Hi all, I currently implementing Attach env to collection feature #173

### **Need feedback?**

- When you attach an env to collection, should it ignore Active Env or override Active Env?

- and in **Tests** when we use `Set Env Variable `, which env should it update the value, is it Active Env or Env attached to Collection?

I know you guys are used to using variables at Collection Level not attach an Env.

**Comment by jongio** [comment]
You should have a consistent hierarchy of envs.  "Global, Collection, Request" and the commands should use the one closet to itself that has a value.

**Comment by rangav** [comment]
Thanks @jongio.

So the order of hierarchy will be in this case

- Global Variables
- Active Environment
- Collection Level Env (Attached)

Set Env Variable will update the **Collection Level Env**, if not attached then it will update **Active Environment**.

**Comment by jongio** [comment]
Is collection the lowest level or can I also set an env at the request level w/in an env?  If you can set env at the request level w/in an env, then you may want.

You may also consider making the "set" explicitly ask for scope.  See what Postman does here.

**Comment by rangav** [comment]
Request level variables only possible in pre-request scripts in postman and also setting scope via scripting.

Planning for advanced use-cases via scripting in near future.

**Comment by rangav** [comment]
This feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback

**Comment by rangav** [comment]
You can also set env variable using **scope**

see details here
https://github.com/rangav/thunder-client-support#set-env-with-scope

**Comment by AllanJeremy** [comment]
Awesome!!
