### ISSUE TITLE
Thunder client extension not available on manjaro

### ISSUE THREAD

**Issue by taftadjani** [rangav/thunder-client-support#330]
Hello Ranga,

I just hear of this extension and want to use it in my project but I could not find it. 

![thunder client manjaro](https://user-images.githubusercontent.com/46008060/133836547-d7b93670-b820-4d96-b841-28dabb244fb2.png)

So I thought you may want to expand the support on that platform too.

**Comment by rangav** [comment]
Hi @taftadjani thanks for the feedback 

currently you need to manually download and install the extension for now.

**Comment by taftadjani** [comment]
Hi Ranga,

Yeah, Found something already. 
I installed the microsoft version of vs code on manjaro and installed thunder client already. 
So I just need to test if everything work correctly.

And thank you for your quick feedback and the extension. 
Saw that a lot of people like it.
