### ISSUE TITLE
Cannot set environment variable on simple JSON response

### ISSUE THREAD

**Issue by ssnyder** [rangav/thunder-client-support#331]
**Describe the bug**
Simple login to a vendor system, provides a basic response:
{
  "msg": "success.",
  "success": true,
  "userid": 1002,
  "token": "B275CB1A1F6F0733C7BB903A319570E0"
}

I am trying to set the token value to a variable using: 

> json.token  setTo  {{myEnvVar}}

It consistently fails just saying that Error occurred

See attached file for screenshot.  Yes, the variable exists in my environment, and is currently filled in with a dummy value (same problem if it is blank).

**To Reproduce**

**Expected behavior**
The environment variable should be filled in properly.

**Platform:** 
 - OS:  Win 10
 - vscode version: 1.60.1
 - extension version: 1.9.1

**Solution:**
<!--- if you know the solution, please post it ---
![thunderClient testResults](https://user-images.githubusercontent.com/1420892/133844746-b477a824-304b-4309-86a8-d3355ea088ce.PNG)
>

**Comment by rangav** [comment]
Hi @ssnyder 

I have tested this using the `https://www.thunderclient.io/welcome` url, its working for me, see screenshots below

<img width="965" alt="Screenshot 2021-09-17 at 22 09 11" src="https://user-images.githubusercontent.com/8637550/133854031-ea1cf800-6c0f-475b-8800-5b7cf8062880.png">

<img width="1226" alt="Screenshot 2021-09-17 at 22 09 28" src="https://user-images.githubusercontent.com/8637550/133854060-43d39b05-7e3e-41e7-aaec-7a0de3ed8394.png">

**Comment by ssnyder** [comment]
That sample works...but not sure why mine is not working....It doesn't indicate what the error is - just Actual: Error Occurred

**Comment by rangav** [comment]
did you create environment and is it active?

can you share screenshots of tests and results tab open.

and environments tab

**Comment by ssnyder** [comment]
Yes, I created an environment and it's active. 
![environment](https://user-images.githubusercontent.com/1420892/134081117-0ed197ef-7a66-41f8-81df-78562dacfd19.PNG)
![test and results](https://user-images.githubusercontent.com/1420892/134081272-68bd958b-b954-4136-b61e-9936f79d0e3f.PNG)

**Comment by rangav** [comment]
your response data is not color highlighted 

Can you please  share your `response headers` tab screenshot

**Comment by Alynva** [comment]
Maybe looking for the request header "Accept: application/json" should work, in the case that there is no content-type header in the response

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

Now it will allow without content-type header in response for json and text outputs

please let me know if any feedback
