### ISSUE TITLE
copy/paste not always working....

### ISSUE THREAD

**Issue by ssnyder** [rangav/thunder-client-support#332]
**Describe the bug**
Because of bug just reported on SetTo not working, I am copy/pasting the token provided by the login API response, I cannot reliably copy/paste the value from that window anymore.  Every so often, I get it to work, but I'm not sure how!

The mouse and keyboard have the same results.  

**To Reproduce**
Try to copy a value out of the response tab, and it won't copy to clipboard (may actually be a vscode bug - but I don't know)

**Expected behavior**
copy should copy to the system clipboard for me to paste elsewhere

**Platform:** 
 - OS: Win 10
 - vscode version: 1.60.1
 - extension version: 1.9.1

**Solution:**

**Comment by rangav** [comment]
Hi @ssnyder, thanks for reporting the issue, you can copy and paste using ctrl+C and Ctrl+V, but if there is issue using keyboard shortcuts, then it might be related to vscode itself.

I am also planning for dedicated `copy` button to copy the response

**Comment by ssnyder** [comment]
I could not copy using the keyboard shortcuts OR the right mouse button click to bring up the menu and choosing copy from there.

**Comment by josejaner** [comment]
it doesn't work, the same thing happens to me

**Comment by rangav** [comment]
copy/paste functionality is provided by vscode. so could be vscode version issue.

**Comment by dignin** [comment]
Having the same issues on Vesion 1.60.2

**Comment by rangav** [comment]
Hi @dignin please downgrade vscode and verify

**Comment by rangav** [comment]
I am closing the issue, feel free to reopen if needed

**Comment by jc-camosun** [comment]
I think this issue should be re-opened. Using the Copy button from a Login API Response copies the entire JSON object, not just the token itself. Pasting it into the "Bearer Token" field causes a `Invalid character in header content ["authorization"]` error, same as issue #340, even after deleting the extra JSON characters so it's only the token.

**Comment by rangav** [comment]
Hi @jc-camosun, thanks for reporting the issue. 

Can you create a new issue and steps to reproduce the issue

you can use this test url to reproduce the error
https://httpbin.org/anything
