### ISSUE TITLE
JSON formatting not working when a value has a URL

### ISSUE THREAD

**Issue by alokraoprakash** [rangav/thunder-client-support#333]
**Describe the bug**

JSON formatting doesn't seem to work when one of the values is a URL.

**To Reproduce**

Create a JSON with a url value in the request body and try to format it.

![formatting](https://user-images.githubusercontent.com/84446878/133998769-0985781d-406e-4b10-a6f9-16c2a081e7d5.png)

In fact, any pattern with a : prefixed with text (e.g. one:four) seems to break the formatting.

**Expected behavior**

The formatting should work the same as it does without a url value.

**Platform:** 
 - OS: Ubuntu 21.04
 - vscode version: 1.61.0-insider
 - extension version: v1.9.1

**Comment by rangav** [comment]
Hi @alokraoprakash thanks for reporting, I verify and fix ASAP.

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
