### ISSUE TITLE
Save a result file

### ISSUE THREAD

**Issue by diosby** [rangav/thunder-client-support#334]
**Is your feature request related to a problem? Please describe.**
The service return blob-data of a file and I want to have a possibility to save the file. 

Now I look at raw data. 

![Screenshot from 2021-09-20 17-28-54](https://user-images.githubusercontent.com/19969187/134019990-4df3f289-1b50-4a37-8be7-084191c571bf.png)
![Screenshot from 2021-09-20 17-28-55](https://user-images.githubusercontent.com/19969187/134019995-862cf603-1bdd-4a82-a394-7fb03d197ae6.png)

**Describe the solution you'd like**
Automated request with a window dialog to save file (set a name, a path and format if it is possible).

**Describe alternatives you've considered**
Now I use Postman to save the result. Also I can use a browser, but it can make troubles with the request as POST and has parameters.

![Screenshot from 2021-09-20 17-31-58](https://user-images.githubusercontent.com/19969187/134020564-89e362c0-10d0-4a73-8596-aa91e1ed5a0d.png)

Sometimes response data can be too much to show and the window can be frozen, so I want to save file without showing result.

Thank you.

**Comment by rangav** [comment]
Hi @diosby, thanks for the feedback, will add to roadmap.

**Comment by onmusic-development** [comment]
I'd like to second this request. Thunder Client is such a great tool, but it is difficult to move away from Postman without the ability to download and save files.

**Comment by rangav** [comment]
Hi guys, if possible I will include this for the next update

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0, The feature is still in BETA, so let me know if you have any issues
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Comment by onmusic-development** [comment]
This seems works well for my use cases. I think it's a better approach than in Postman since I no longer have to remember to send the request differently if I actually want the file (and often have to do it twice). Great job.

**Comment by rangav** [comment]
Thanks @onmusic-development, glad you like the implementation 🙂
