### ISSUE TITLE
Copy an existent request

### ISSUE THREAD

**Issue by diosby** [rangav/thunder-client-support#335]
**Is your feature request related to a problem? Please describe.**
Sometimes I have many similar requests, but to send a new request I change an old request or create a new request and fill it the same or similar data excepted URL. 

**Describe the solution you'd like**
Add a button Copy to Popup Menu. 

![Screenshot from 2021-09-20 17-40-06](https://user-images.githubusercontent.com/19969187/134021627-a3be4d54-d021-4971-9ff3-cb5b390393db.png)

**Comment by rangav** [comment]
Hi @diosby 

duplicate request menu option in available for requests in the `collections` tab.

**Comment by diosby** [comment]
@rangav Thanks. But I don't use collections.

**Comment by rangav** [comment]
Ok will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback
