### ISSUE TITLE
Can we expect websocket requests support

### ISSUE THREAD

**Issue by Dzivo** [rangav/thunder-client-support#336]
**Is your feature request related to a problem? Please describe.**
We can not make websocket requests.

**Describe the solution you'd like**
I would like to make simple websocket requests similar to Postmans websockets

This would helps us with moving completely from Postman and stay in VS Code

**Comment by rangav** [comment]
Hi @Dzivo duplicate of #3

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.19.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test it and let me know your feedback
