### ISSUE TITLE
How define multipart Content-Type

### ISSUE THREAD

**Issue by mchassy** [rangav/thunder-client-support#337]
Could you post an example of how to define requests with multipart/form-data? In this case for a file upload.
For example, in the other REST client extension on VS code, you first define the multipart in the header like this:
```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
```
Then in the body, I define this:
```
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="[filename]"
Content-Type: text/plain 

< [/path/to/file]
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
In thunder, I defined this in the header:

![image](https://user-images.githubusercontent.com/15926092/134247740-ad20f5fc-a274-4b55-9c5e-eaf49998e4db.png)

But I'm not so sure what to put in the body

![image](https://user-images.githubusercontent.com/15926092/134247864-fc6b97e5-ed2a-4608-8fae-8d67da2a1fe2.png)

**Comment by mchassy** [comment]
I have figured this out. Don't put multipart in the header. The tool will take care that. Then in the Body, use Form and do something like this:

![image](https://user-images.githubusercontent.com/15926092/134305254-7ae8dedb-4d54-4880-ad53-bf3f568c6fc9.png)

**Comment by mchassy** [comment]
As stated above, I have found how to do this properly. Left a nice screenshot for those looking for the same, but it would be nice to put it in the documentation.

**Comment by YashWani28** [comment]
okay...but how to access this data in an endpoint, req.body.name gives undefined
