### ISSUE TITLE
Environment variables don't resolve in JSON Body 

### ISSUE THREAD

**Issue by mchassy** [rangav/thunder-client-support#338]
**Describe the bug**
When using environment variables in a JSON body, they don't turn green or resolve.

**To Reproduce**
Create a POST with a JSON body and replace some values with environment variables

**Expected behavior**
Variables should resolve correctly

**Platform:** 
Windows 10 Pro
VS Code 1.60.1
Thunder 1.9.1

**Impact:**

This makes the use of the tool very limited as you can't pass values from one call to another if the value need to go into a JSON body, which will often be the case.

**Example:**

You can see that the variable resolves in the URL (as it has turned green), but not in the JSON body data. I tried both using the double quotes around the variables and taking them a away.

![image](https://user-images.githubusercontent.com/15926092/134308673-de65be22-fb7f-4754-bf42-38eb00020a80.png)

**Comment by rangav** [comment]
Hi @mchassy they work in body as well, just execute the request you can see the result.

variable are not color highlighted yet

**Comment by mchassy** [comment]
Hi @rangav. You are right they are resolving, I see now that it is a problem of string/number conversion. here is the error which I get


![image](https://user-images.githubusercontent.com/15926092/134310703-845848c1-40a4-4372-a90d-7bdb7f397c57.png)


If I replace that one tag with an actual number then it works fine.

**Comment by mchassy** [comment]
Ok, I have it figured out now.
You should leave those variable which are string like this
"{{VAR}}"
but those variable which you want to be number like this
{{VAR}}
