### ISSUE TITLE
Can't set the value of an environment variable by using another environment variable

### ISSUE THREAD

**Issue by mchassy** [rangav/thunder-client-support#339]
**Describe the bug**
Can't set the value of an environment variable by using another environment variable

**To Reproduce**
I sometimes have move than one case which I want to run for a given message. Instead of going and changing all of the values, I would rather do something like this
```
case1_apikey     XXXXXXX
case2_apikey     ZZZZZZZ
current_apikey   {{case1_apikey}}
```
This way I would not have go change the variable where it is used. I would always use current_apikey.

**Expected behavior**
variable value should resolve

**Platform:** 
Windows 10 Pro
VS Code 1.60.1
Thunder 1.9.1

**Solution:**

**Comment by rangav** [comment]
Hi @mchassy this will also work, please execute the request and see the result.

not color highlighted yet.

**Comment by mchassy** [comment]
You are right, it is working. I'm not sure if you point out in the documentation, but if you use the code snippet functionality, you can see the values changing in real time. Thanks for helping out, this extension is much cleaner than the basic REST client in VS.

**Comment by rangav** [comment]
Thanks @mchassy for the great feedback 👍
