### ISSUE TITLE
Variable replacements in variables

### ISSUE THREAD

**Issue by jongio** [rangav/thunder-client-support#34]
**Is your feature request related to a problem? Please describe.**

Yes, if I reference a variable in the value of another variable it isn't expanded

![image](https://user-images.githubusercontent.com/2163001/115949661-6c574480-a48b-11eb-91d9-8934014e17e1.png)

**Describe the solution you'd like**

Expand them.

**Describe alternatives you've considered**

Hard-coding instead of referencing.

**Implementation:**

**Comment by rangav** [comment]
Hi @jongio got it, will fix this asap.

**Comment by rangav** [comment]
This is now implemented in v1.2.0, please update. 

Release details here 
https://github.com/rangav/thunder-client-support/releases/tag/1.2.0
