### ISSUE TITLE
Bearer token feature not working when pasting JWT into field

### ISSUE THREAD

**Issue by ffxsam** [rangav/thunder-client-support#340]
**Describe the bug**
When I try to make requests that require authorization via JWT token, I get `Invalid character in header content ["authorization"]` even though the JWT is valid (verified via https://jwt.io/#debugger-io)

**To Reproduce**
Make a POST request and paste a JWT into the "Bearer Token" field. For security reasons, I can't post the token here, but the token consists of `[A-Za-z0-9]` as well as these chars: `_-.`

**Expected behavior**
I would expect the request to work.

**Platform:** 
 - OS: macOS 11.6
 - vscode version: 1.60.1
 - extension version: 1.9.1

**Comment by ffxsam** [comment]
Oddly enough, if I enter `{{token}}` as the token so it uses the same JWT in my env, it works fine. But when the token is pasted directly into the "Bearer Token" field, it fails.

**Comment by aentwist** [comment]
I can't get this to work at all. It is a critical issue because it renders the entire thing useless. Will be using Postman..

**Comment by rangav** [comment]
Hi @ffxsam 

for bearer  token `Bearer` Keyword Will be prefixed automatically 

so use token value only without prefix

**Comment by ffxsam** [comment]
I wasn't using a prefix of any kind, I was just pasting the JWT into the field. But it's been working for a long time now, so maybe an update fixed it?
