### ISSUE TITLE
Connection was refused by the server

### ISSUE THREAD

**Issue by kiranabn** [rangav/thunder-client-support#341]
When I fire the local host request, getting this response

**Comment by rangav** [comment]
Hi @kiranabn 

see below comments for solution
https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-864047143

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed

**Comment by co-bby** [comment]
if you are using WSL on Windows use [::1] instead of localhost in the address bar. Example [::1]:3000/api/v1 .
Another option is to use the PowerShell instead of the WSL terminal.  Lastly you can also move your project directory to the Linux file system (~/home)

**Comment by ZooDoo4U** [comment]
I'm running into this error if issuing a request from Thunder Client, just updated VS Code and Thunder client (vs code 1.75.1,  Thunder  Client v2.4.1, i'm on Win 10).  My setup/configuration is about as simple as can be.  Simply created a new sveltekit app to prototype some stuff:

pnpm create svelte@latest test-post 
cd test-post
pnpm i

Added one get request in a "+server.js" file in src/api/posts.

export const GET = () =>
{
    return new Response(JSON.stringify({ "message": "test..."}), { status: 200 })
}

Now for the bug:

Create a new request  in thunder client request and "Send" (given my test app is on port 3000...  My GET request  is:

http://localhost:3000/api/post

No matter what  "connect ECONNREFUSED 127.0.0.1:3000"

I'm getting an error with this request when issued from withing Thunder Client, 

Using curl, postman, insomnia, or simply the browser (Chrome or Firefox) no problems.   Any suggestions?

**Comment by rangav** [comment]
@ZooDoo4U 

Please try below suggestions in comments 
https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-864047143
