### ISSUE TITLE
Add popover to Thunder client icon in action bar mentioning shortcut key to switch to it 

### ISSUE THREAD

**Issue by 5hu6hamKadam** [rangav/thunder-client-support#342]
User experience issue.
Most of the time I use the only the keyboard. So having shortcuts helps. All other default action bar component also has a shortcut.

**Comment by rangav** [comment]
Thanks @5hu6hamKadam for feedback, will update it.

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Comment by rangav** [comment]
There is new issue related to this #451

**Comment by rangav** [comment]
Just now published new quick release - v1.11.1 to address the issue #451

The new shortcut is ctrl+shift+R
