### ISSUE TITLE
Ability to change order of Activity/Collection/Env tabs, or set default tab

### ISSUE THREAD

**Issue by ffxsam** [rangav/thunder-client-support#344]
When I first open Thunder Client, it defaults to showing the "Activity" tab, which I never use. IMO, the most useful tab to start on would be "Collections," but I can't set that in any way.

It would be great if we could set the default starting tab, or change tab order to put "Collections" first.

**Comment by rangav** [comment]
Hi @ffxsam thanks for feedback, will add to roadmap.

**Comment by ffxsam** [comment]
@rangav Thank you! This extension is fantastic. 🏆

**Comment by garcipat** [comment]
I would in general like the option to hide it. Also in the request view it clutters up the list of requests.

Just switching to it from Postman :) keep up the work!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.4.3

Please let me know your feedback.
