### ISSUE TITLE
Testing with JS

### ISSUE THREAD

**Issue by alpgul** [rangav/thunder-client-support#347]
Response, cookie, header values should be tested with javascript code.

**Comment by rangav** [comment]
Hi @alpgul thanks for feedback, you can test now response and headers. Cookie testing will add to roadmap.

**Comment by rangav** [comment]
@dmitrach We have `pre-request scripting` in roadmap #16, you can express your interest there.

I am closing this issue, as it's a duplicate.

**Comment by rangav** [comment]
Hi, Now Tests via scripting is possible with v2.10.0

https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0
