### ISSUE TITLE
An error occurred while loading view: thunder-client-sidebar

### ISSUE THREAD

**Issue by rpai9** [rangav/thunder-client-support#349]
**Describe the bug**
An error occurred while loading view: thunder-client-sidebar message on the side bar.

**To Reproduce**
Not sure how to reproduce this

**Expected behavior**
Unable to use the thunder client
![image](https://user-images.githubusercontent.com/68650968/135464170-3d9620f3-5ba4-4771-9b97-1449d391513a.png)

Re-installing the extension didn't help

**Platform:** 
 - OS: 10.15.7 (19H1419)
 - vscode version:  1.60.2
 - extension version: 1.9.1

**Comment by rangav** [comment]
Hi @rpai9 thanks for reporting the issue.

can you try downgrading the vscode to previous version?

Did it work previously for you?

**Comment by rpai9** [comment]
It was working fine before. This is one of my favourite tools! Awesome work @rangav 

I did downgrade going back a few version and none of them worked. It might be something to do with VS-code. Let me try to re-install the application to see if it fixes the issue. I'll keep you posted.

**Comment by rpai9** [comment]
@rangav The extension started working again after I re-installed vscode. I'm not sure of the underlying cause. 
I'm using the same extensions as before on the new installation. That's why I'm pretty sure it's not one of them causing interference. 

Let me know if you want me to look into something (log/trace file) that might help establish the root cause. If not, I think we can close the issue.

**Comment by rangav** [comment]
Thanks for confirmation,

there is no log file currently, so we will close the issue.

**Comment by mtebele** [comment]
Same here. VSCode Version: 1.61.0

**Comment by rangav** [comment]
Hi @mtebele try downgrading to previous version and test it

**Comment by PavelSafronov** [comment]
Just experienced this with VSCode version 1.62.0.

This worked for me:
1. Disable "Thunder Client" extension
2. Reload VSCode
3. Enable "Thunder Client" extension
4. Reload VSCode

Is there a plan to add logs/tracing to the extension?

**Comment by rangav** [comment]
Hi @PavelSafronov yes there is plan to add logs to the extension in near future

**Comment by eriksavage** [comment]
I just experienced this as well with VSCode Version: 1.63.2, macOS 12.0.1 (21A559)

@PavelSafronov 's steps resolved it for me.

**Comment by xvrx** [comment]
i just had the same issue, only reinstalling the extension wouldn't solve the problem for me, i had to first manually delete the extension folder in %USERPROFILE%/.vscode/extension and then proceeded installing it again in vscode.

**Comment by VASKOTechDesign** [comment]
Hello, sorry to disturb you again, but unfortunately, I have this problem still. I Installed it on 24.3.2022 and used it for 2 requests, then I open the second session of VS Code, and suddenly after the closing of first session the "Thunder Client" stop working. 

**I tried all methods to repair it but o success:**
Method 1 (PavelSafronov commented on Nov 5, 2021) --> no success
Method 2 (xvrx commented on Feb 17) --> no success
Method 3 Uninstall extension, restart PC and install again --> no success

**My setup:**
Visual Studio Code:
   Version: 1.65.2 (user setup)
   Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
   Date: 2022-03-10T14:33:55.248Z (1 wk ago)
   Electron: 13.5.2
   Chromium: 91.0.4472.164
   Node.js: 14.16.0
   V8: 9.1.269.39-electron.0
   OS: Windows_NT x64 10.0.19044

**Thunder Client:**
   Version: v1.14.0

**Printscreen:**
![image](https://user-images.githubusercontent.com/50368892/159937725-e57f9ff1-493c-4c1b-9f24-ec030979d461.png)

**Comment by Nathnael12** [comment]
deleting '_rangav.vscode-thunder-client_' folder from _%USERPROFILE%/.vscode/extensions/_ directory then reinstalling thunder client worked for me

**Comment by JEricaM** [comment]
Same problem here. Nothing of the previous answers works for me.

**Comment by rangav** [comment]
Hi @JEricaM, try install previous version of the extension.

**Comment by JEricaM** [comment]
@rangav 

tried v1.18.1, v1.17.1, v1.16.6 but nothing worked

**Comment by JEricaM** [comment]
v1.14.4 seems to load correctly.

**Comment by rangav** [comment]
is your vscode updated to latest version?

**Comment by Kislame** [comment]
just hade the same problem, installing the v1.14.4 fixed for me.

**Comment by JEricaM** [comment]
I've updated the extension to the last version and now works again.

**Comment by yashnarkhedkar** [comment]
> Just experienced this with VSCode version 1.62.0.
> 
> This worked for me:
> 
> 1. Disable "Thunder Client" extension
> 2. Reload VSCode
> 3. Enable "Thunder Client" extension
> 4. Reload VSCode
> 
> Is there a plan to add logs/tracing to the extension?

Just Reinstall the thunder client extension

**Comment by deepsimrantechie** [comment]
hlo @rpai9 i am working on food del web application in backend the database is conncted successfully and it is working fine but still thunder client throws error while uploading image path is fine i checked it millions of time but still its not working even i install nod_module and multer 10 times db connected but thunder client is not working could you please help me in this problem pleasee
