### ISSUE TITLE
Create variable in env if doesn't exist when set

### ISSUE THREAD

**Issue by jongio** [rangav/thunder-client-support#35]
**Is your feature request related to a problem? Please describe.**

Yes, In a Test I want to set an env var, but it looks like I have to first manually create that variable.

Here:
![image](https://user-images.githubusercontent.com/2163001/115949858-a248f880-a48c-11eb-9d41-0b8b0f3f6b6a.png)

**Describe the solution you'd like**

Create the variable in the Env if it doesn't already exist.

**Describe alternatives you've considered**

Manually create the variable before running.

**Implementation:**

**Comment by rangav** [comment]
Hi @jongio  Will add this to my list.

**Comment by rangav** [comment]
v1.1.0 is now published - discuss here #14
