### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by juninhodeluca** [rangav/thunder-client-support#350]
Hi, I just made some tests to use this amazing extension in real world projects and  was partially KO since all our REST documentation is based on openAPI, with a specs.yml file, which is not supported at the moment in collection / import
To by-pass, I should load the specs.yml collection into postman and from there export it again as json, which is a huge problem for dev-teams flow, since specs.yml is into repository and became updated eventually, while the json format not.
Anyways, it's a very amazing extension and I really enjoy it. Nice work!

**Comment by rangav** [comment]
Hi @juninhodeluca open Api import support coming soon. If you like to contribute to this let me know.

**Comment by eladhaim22** [comment]
i would love to contribute to this awesome project.

**Comment by rangav** [comment]
I am closing this issue, as it's duplicate of #84
