### ISSUE TITLE
Does this support to write test cases on the results

### ISSUE THREAD

**Issue by chennas** [rangav/thunder-client-support#351]
Does this support to write test cases on the results and assign the values to env variables?
currently i don't see that in the thunderclient, all i see is the pre populated drop down selections.

**Comment by rangav** [comment]
Hi @chennas you can set environment variable from response 

see details here
https://github.com/rangav/thunder-client-support#setenv

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
