### ISSUE TITLE
Select Environment at the Request Level 

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [rangav/thunder-client-support#354]
**Is your feature request related to a problem? Please describe.**

I have environments configured for different machines. To send the same Collection request to each machine I need to:

1. Open the Collections tab
1. Right-click the 3-dots beside my collection
2. Select Settings
3. Select Environment
4. Pull-down the environment I want to attach to the collection.
5. Select the Request from my Collection
6. Press Send

When I need to target a different machine, I have to repeat this exercise, which quickly becomes inhibitive.

**Describe the solution you'd like**

On the Request page, introduce an "Environment" tab which would be use to select the environment.

**Describe alternatives you've considered**

**Implementation:**

**Comment by hbirkdale** [comment]
The environment UI is also confusing. You can make an env "Active" by clicking on the ... and selecting "Set Active", but it actually doesn't do anything (as far as I can tell) unless you have already associated your Collection with the env.  Worse yet you can only associate one environment with your collection, so as @LiveFreeAndRoam says, every time you want to change your environment you have to go through multiple steps. 
What is the "Set Active" supposed to do anyway?

**Comment by rangav** [comment]
Hi @hbirkdale `Set Active` Will make that environment active.

But it will be overridden if you assign environment to a collection using collection setting

let me know if it’s not clear

**Comment by hbirkdale** [comment]
@rangav Thanks! Once I removed the environment from the collection Set Active worked fine - thanks.

**Comment by rangav** [comment]
Hi Just want to give you all a heads-up of the upcoming changes to improve Changing Environment.

**1. Collection Level Env clarification:**
NOTE: This is optional feature. Use this only to tightly link Environment to this Collection, the values in this Environment will take precedence over Active Environment. If you are changing Environment frequently for this collection, then it is recommended not to attach Environment here, instead use the Active Environment from the Env Tab in Sidebar 

![Screenshot 2022-02-12 at 21 42 30](https://user-images.githubusercontent.com/8637550/153751116-186519e5-7854-489f-b300-d9b9e3e82966.png)


2. **Changing Env**: 
 - Active Environment will be displayed in StatusBar at the bottom, clicking on it will display the options to change the Env
 - From Keyboard - Ctrl/Cmd+E shortcut
 - From Command Palette also Change Environment option available

StatusBar Display of Active Env
![Screenshot 2022-02-13 at 11 37 25](https://user-images.githubusercontent.com/8637550/153751222-9f8d5182-972a-4482-8266-5527fda192ed.png)

Quick Change Options
![Screenshot 2022-02-13 at 11 38 54](https://user-images.githubusercontent.com/8637550/153751261-852c4c7e-f03e-4887-b1ed-eba933bc2c1a.png)

Let me know your feedback.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
