### ISSUE TITLE
Add a button to save the response body

### ISSUE THREAD

**Issue by Alterant-zz** [rangav/thunder-client-support#356]
**Is your feature request related to a problem? Please describe.**
For binary bodies (actually for any types) it's not convenient to copy and paste the contents and then save it to file.

**Describe the solution you'd like**
It would be nice to have a button "Save to file" on the right of "Status: 200 OK Size: 59.22 KB Time: 712 ms" text above response.
Like this:
![изображение](https://user-images.githubusercontent.com/1001060/136399302-ceec5c04-be24-4b77-acf3-7076d64d3d7a.png)

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback
