### ISSUE TITLE
Multipart Form Data not working for me

### ISSUE THREAD

**Issue by WTIGER001** [rangav/thunder-client-support#357]
I am unsure what I am doing wrong. I have a local API running (I am using go-swagger) and I have a request with a file as the body. When I submit that request the Go Libraries do not see the Form Data. When I run the same request using Curl it works for me. 

**In Thunder Client**
![image](https://user-images.githubusercontent.com/4420898/136427506-97cdd2c8-e197-403c-b6fb-791cf3f8d1d2.png)

**In Curl**
curl -v -F upload=@zip-MknsjBSnR.zip http://localhost:8889/flt-api/testevents/tst-3k11hCnn1bJ/files

I love ThunderClient and I would like to figure out how to get the file uploads to work for me

**Comment by WTIGER001** [comment]
Thanks.. I get this:

`{
  "code": 415,
  "message": "unsupported media type \"application/octet-stream\", only [multipart/form-data application/json] are allowed"
}`

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
