### ISSUE TITLE
Authentication: OAuth2 Header Prefix and Audience

### ISSUE THREAD

**Issue by nametable** [rangav/thunder-client-support#359]
**Is your feature request related to a problem? Please describe.**

I am trying to authenticate to Auth0 via OAuth 2. It currently works properly in Insomnia but I don't have all of the same options with Thunder Client. I'm not seeing `Header Prefix` and `Audience`

This is what Insomnia provides:
![image](https://user-images.githubusercontent.com/19422826/136477070-5020bda4-8596-4b9e-b05e-f96305d6f4ff.png)

And this is what Thunder Client shows:
![image](https://user-images.githubusercontent.com/19422826/136477315-10d1aef5-8a77-4e6e-910e-ba648acf5239.png)

**Describe the solution you'd like**

I would expect these extra options that Insomnia has to be included in thunder client.

**Describe alternatives you've considered**

I have obtained a token manually and used that. This works temporarily but I would like Thunder Client to be able to refresh it.

**Implementation:**

I have not looked at the code-base but given time I could probably figure it out and create a request. Although someone with more experience with this codebase may be faster.

**Comment by nanaasumadu** [comment]
Just to add that perhaps implementing a refresh_token, https://oauth.net/2/grant-types/refresh-token/ grant type may be what is needed.

**Comment by rangav** [comment]
Hi @nanaasumadu auth 2 should work I think

select `Sent Auth` Option to `As Auth Body` It will send as post request

can you try and let me know

**Comment by nanaasumadu** [comment]
Just to add that making a direct POST request to the API endpoint works as per below.  
<img width="1293" alt="Screen Shot 2021-10-10 at 10 12 52 am" src="https://user-images.githubusercontent.com/29611833/136675972-2714c96b-f93c-4127-8287-1b1a8df8a705.png">

However, because of the short expiry of the access token, the goal is to be able to generate the auth token on the fly by clicking the "Generate Token" button.

**Comment by rangav** [comment]
Looks like it's not OAuth 2 request format, so you have to POST request which did correctly 

you can the request in collection, and save the refresh token in environment variable and use the variable using format `{{variableName}}` in other requests 

you can save to variable from response, see below link
https://github.com/rangav/thunder-client-support#setenv

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.14.0`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.0

**Comment by rangav** [comment]
Now the extension will also write OAuth request details to `Output window`, useful for debugging purpose
