### ISSUE TITLE
Support Ctrl+S to save env vars

### ISSUE THREAD

**Issue by jongio** [rangav/thunder-client-support#36]
**Is your feature request related to a problem? Please describe.**

Yeah, I hit CTRL+S assuming it saved the item

**Describe the solution you'd like**

Save when I hit CTRL+S

**Describe alternatives you've considered**

Click save button

**Implementation:**

**Comment by rangav** [comment]
Hi @jongio  Will add this to my list.

**Comment by rangav** [comment]
v1.1.0 is now published - discuss here #14
