### ISSUE TITLE
Projet bases collection

### ISSUE THREAD

**Issue by barbaroskoca** [rangav/thunder-client-support#360]
**Is your feature request related to a problem? Please describe.**
When I planned to use the thunder-client under many different projects, as an extension I would like to see each collection in related project.

**Describe the solution you'd like**
There might be collection based storage system so it can be stored under a specific project folder. Also, this solution may enable to archieve the collection in the project repository so other team member can reach the collection easily.

**Implementation:**
Collection directories can be mapped with the users' preference. And this can be done with a routing table in the extension's settings.

**Comment by rangav** [comment]
Hi @barbaroskoca this feature is already available 

see details here
https://github.com/rangav/thunder-client-support#team

Use the first option `Load from Project`
