### ISSUE TITLE
Thunderclient files changed as soon as a project opens.

### ISSUE THREAD

**Issue by wildhart** [rangav/thunder-client-support#361]
whenever I open a project Thunderclient updates its database even if nothing has changed.  This makes me think there are changes needing commiting when there are not.

![image](https://user-images.githubusercontent.com/12505024/136619942-c2744913-27c5-4e12-9f71-878346241454.png)

**Comment by rangav** [comment]
I think the extension is updating few properties which was needed.

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
