### ISSUE TITLE
Request Timeouts

### ISSUE THREAD

**Issue by swanav** [rangav/thunder-client-support#362]
**Is your feature request related to a problem? Please describe.**
When making requests to an unresponsive server, the client keeps waiting indefinitely.

**Describe the solution you'd like**
The client should support a Request Timeout in the settings.json, so that the user can add a default timeout.

**Describe alternatives you've considered**

**Implementation:**
Should be pretty straightforward, based on the http client used.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
