### ISSUE TITLE
Thunder Client is not uploading image in  VSCode that run on Github Codespaces

### ISSUE THREAD

**Issue by YassinHussein** [rangav/thunder-client-support#363]
**bug**

when I uploading images to using Thunder Client that installs on VSCode  that runs on my local machine it work fine
but when tried to upload an image using VSCode that run on cloud [(codespaces)](https://github.com/features/codespaces) it's return this error :
![Screenshot (285)](https://user-images.githubusercontent.com/21006775/136814548-730b7d51-48d6-4421-8b14-136bc2951ea9.png)

**To Reproduce**
upload image and click send button

**Expected behavior**

**Platform:** 
 - OS:  linux (Ubuntu - 20.04)
 - vscode version: 1.61.0 
 - extension version: 1.9.1

**Solution:**

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by maheshwarikashish** [comment]
Currently I am facing the same issue what can I do is it only available in paid version now?

**Comment by golesuman** [comment]
@maheshwarikashish It seems it's only available on paid version now.

You can use `curl` or just use postman to upload the image

**Comment by maheshwarikashish** [comment]
Yeah, I just got to know about that—thanks a lot for letting me know! I
really appreciate it. If you come across any other tips or updates like
this in the future, please do share. Always happy to learn from you!

**Comment by Nitish2004kumar** [comment]
i am also facing same problem , is it available on paid version of thunder client

**Comment by rangav** [comment]
Yes, paid version supports other editors.
