### ISSUE TITLE
Enable Ctrl+z (Cmd+z) in URL field

### ISSUE THREAD

**Issue by OmarOdaini** [rangav/thunder-client-support#365]
**Is your feature request related to a problem? Please describe:**
Once I update the URL parameters I usually rely on Cmd+z alot to conveniently return to previous values. Unfortuanly, in the URL field I'm unable to use Cmd+z. 
**Describe the solution you'd like:**
Enable Cmd+z shortcut to return to previous values

**Comment by OmarOdaini** [comment]
@rangav not sure how noone is asking for this feature but it's essential for the URL field to to allow cmd+z.

**Comment by rangav** [comment]
Hi @OmarOdaini the url field is not standard input field, it’s a `contentEditable` element which lost all the standard features like undo redo etc.. 

Need to implement custom logic for this, I will look into when I find time.

**Comment by rangav** [comment]
I have fixed the problem now, would you like to test and confirm?

I can upload the `vsix` file here

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2

**Comment by rangav** [comment]
Hi @OmarOdaini, the undo and redo is not 100% perfect yet, as I need to develop custom functionality for this.

But I think its better than previous version, and also try to improve it in the future versions.

> test case 1: {{URL}}/repositories/4/versions/1/json -> {{URL}}/repositories/4/versions/1/js --cmd+z-> {{URL}}/repositories/4/versions/1/json
> 
> took two "cmd+z" clicks to get it back
> 
> test case 2: {{URL}}/repositories/4/versions/1/json -> "" --cmd+z--> {{URL}}/repositories/4/versions/1/json{{URL}}/repositories/4/versions/1/json
> 
> printed my URL twice.
> 
> Other than that I tested it with other scenarios and it works great! its not bullet proof for me but I'm keeping this VSIX version :)

Hi @OmarOdaini, the undo and redo is not 100% perfect yet, as I need to develop custom functionality for this.

But I think its better than previous version, and also try to improve it in the future versions.

**Comment by Nelfym** [comment]
Hello, just a little comment from a French user (me).
ctrl+z seems to be linked to the qwerty layout, I am currently on an azerty keyboard. The shortcut is unusable.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.15.0`

See all features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
