### ISSUE TITLE
FeatureRequest: Allow a "Notes" tab to describe Request parameters and other details specific to the request

### ISSUE THREAD

**Issue by tomwitt2** [rangav/thunder-client-support#366]
**Is your feature request related to a problem? Please describe.**
Some of the input values require special formatting on the backend.  I'm constantly have to look at other documentation to determine the format.

**Describe the solution you'd like**
I'd like to have a "Notes" tab that allows me to add notes, meaningful to me, about the Request  I'm trying to execute.  
Something like
The "Campaign" parameter expects a value of: 3/4 char stub#instance GUID#cost-code
Clear the CMP_Instance table prior to execution 
Take care not to delete the ACME# test campaign instances

**Describe alternatives you've considered**
I have text files and evernote notes which describe the Requests and their parameters I'm working with but it would be great to have those notes tied to the specific Thunder Client Requests.

**Implementation:**
I'd love the Notes to be a new tab on the right side so it can be displayed at the same time the GraphQL Query/Variables or other Body types are being edited.
Response|Headers|Cookies|Test Results|Notes

**Comment by rangav** [comment]
Hi @tomwitt2 thanks for the feedback, there is existing issue for this #200. I am closing this one, so we can track in one place. You can add comments in that.
