### ISSUE TITLE
Cannot sent multiple files in post request

### ISSUE THREAD

**Issue by thdtt** [rangav/thunder-client-support#367]
**Is your feature request related to a problem? Please describe.**

Currently I'm using Thunder-Client in Vscode, but while testing API, with Post request, i cannot select multiple files and send to backend, I can only select a single file for a request. Maybe I didnt find the option to select multiple files in one request, please let me know.

**Describe the solution you'd like**

I would like you can support to send multiple files in a request

**Comment by thdtt** [comment]
![image](https://user-images.githubusercontent.com/48815911/137094680-c23ced83-a271-4339-bc59-fe5dfae216fa.png)
The problem is when click choose file, i cannot select multiple file at a time

**Comment by rangav** [comment]
You can select multiple single files

**Comment by ngrhadi** [comment]
> you need to select like below image (`field name is optional`) ![Screenshot 2021-10-13 at 10 06 14](https://user-images.githubusercontent.com/8637550/137102903-ab5ef374-8a73-498f-bc90-cbc1014b1a25.png)

Hy i have problem, when I have 1 field, and on that field store not only one path of image, but multiple, it's not work when I pun same Field name on file section, how can I do?

**Comment by rangav** [comment]
Hi @ngrhadi did not understood your question clearly. Can you please share screenshot of the problem?

**Comment by ngrhadi** [comment]
![SS](https://snipboard.io/931trv.jpg "case one field")

Here is my case, I have 1 column in DB and store multiple path img, but on db just get last path img, may be I have wrong parsing path, are it's posible in thunder using same field name to store multiple file on that's field?

**Comment by ngrhadi** [comment]
Apologies, my bad, that's work to put same field on thunder, 🙏🏽  ty
