### ISSUE TITLE
Test results failed when graphql return data: null

### ISSUE THREAD

**Issue by bbaltatu** [rangav/thunder-client-support#368]
**Describe the bug**
When the response from a graphql server is  { errors: [..], data: null} tests are passing. Look on the picture for more info.

![image](https://user-images.githubusercontent.com/11313025/137200224-3bf0e739-7e11-4c14-bb69-a4e9dd24931a.png)

and the response is like : 
![image](https://user-images.githubusercontent.com/11313025/137200294-16cfdf27-fefc-4b3f-ba4b-dd46394d6da6.png)

**Expected behavior**
both tests failed.

**Platform:** 
 - OS:  MACOS
 - vscode version: Last
 - extension version: 1.9.1

**Comment by rangav** [comment]
Thanks @bbaltatu for reporting the issue, will fix it in the next update

**Comment by bbaltatu** [comment]
@rangav  . Thank you for your response. Do you know when will be the next update?

**Comment by rangav** [comment]
Next update will be around end of the month

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
