### ISSUE TITLE
Hyperlink to the request on the run all page

### ISSUE THREAD

**Issue by jongio** [rangav/thunder-client-support#37]
**Is your feature request related to a problem? Please describe.**

After I run all a collection, I want to be able to quickly go to the results by clicking on the request

**Describe the solution you'd like**

Make the following rows clickable

![image](https://user-images.githubusercontent.com/2163001/115950041-b7725700-a48d-11eb-8ce8-1727f095ba3c.png)

**Describe alternatives you've considered**

Go to activity and find the request

**Implementation:**

**Comment by rangav** [comment]
Hi @jongio  Will add this to my list.

**Comment by rangav** [comment]
Hi @jongio this is implemented in v1.2.1
https://github.com/rangav/thunder-client-support/releases/tag/1.2.1

Let me know if you need further improvements

**Comment by jongio** [comment]
Works great!  Thank you
