### ISSUE TITLE
Float values incorrect convert from JSON for Response View

### ISSUE THREAD

**Issue by diosby** [rangav/thunder-client-support#370]
**Describe the bug**
I have result with float values and there values contain values with floating point: 0.0, 1.0, 2.0, 2.5. When values can be converted to int, their fractional parts delete:

```
1.0 => 1,
2.0 => 2,
2.5 => 2.5
```
It is incorrect to check values visually, because I expect values with floating point. 

![Screenshot from 2021-10-14 16-52-16](https://user-images.githubusercontent.com/19969187/137332276-cce9db0c-61aa-4fad-8aba-5cb8255f0b5d.png)
![Screenshot from 2021-10-14 16-42-52](https://user-images.githubusercontent.com/19969187/137332281-59bfc4e7-67c0-4032-9077-ee14ecba689e.png)

**To Reproduce**
Return float values from the server. For example: 0.0, 1.0, 2.0, etc.

**Expected behavior**
Real values from the server. For example: for 0.0 is 0.0 instead of 0, for 1.0 is 1.0 instead of 1.

**Platform:** 
 - OS: Ubuntu 20.04
Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:02.929Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic
 - extension version: v1.9.1

Thank you.

**Comment by rangav** [comment]
Thanks @diosby for reporting the issue, will look into the issue.

**Comment by rangav** [comment]
This bug is now fixed in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
