### ISSUE TITLE
Does not save when using workspaces with remote files

### ISSUE THREAD

**Issue by BananaAcid** [rangav/thunder-client-support#372]
**Describe the bug**
It does not do anyhting when adding collections. We need to distribute the API tests with the project.

**To Reproduce**
Workspace is created using the plugin `liveecommerce.vscode-remote-workspace`

config file for the project `test.code-workspace`
```json
{
    "folders": [
        {
            "uri": "ftps://user:pw@host/",
            "name": "FTP Folder"
        }
    ],
    "settings": {
        "thunder-client.loadFromProject": true,
        "thunder-client.workspaceRelativePath": "./FTP Folder/username/.vscode"
    }
}
```

**Expected behavior**
it should work :)

**Platform:** 
 - OS: MacOS 11.6
 - vscode version: 1.61.1
 - extension version: v1.9.1

**Solution:**
It probably relates to https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider support is required

**Comment by rangav** [comment]
Hi @BananaAcid, I think the issue related to remote file paths,

please set this settings as menu in the below comment

https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by BananaAcid** [comment]
tried to add the mentioned config, thunder client does not save into the workspace ... it does nothing - just showing the user saved config. loadFromProject=true still shows a blank tab when trying to add a request.

config file for the project `test.code-workspace`
```
{
    "folders": [
        {
            "uri": "ftps://user:pw@host/",
            "name": "FTP Folder"
        }
    ],
    "settings": {
        "deaktivated-----thunder-client.loadFromProject": true,
        "deaktivated-----thunder-client.workspaceRelativePath": "./FTP Folder/username/.vscode"
        "remote.extensionKind": {
            "rangav.vscode-thunder-client": ["ui"]
        }
    }
}
```


Any more ideas for me to try out?

**Comment by rangav** [comment]
Hi @BananaAcid remove workspace relative path setting, set it to empty and try

**Comment by BananaAcid** [comment]
@rangav updated my previous code block to match my problem description more.

`"remote.extensionKind"` just does nothing, is there a special place to add it or write it within a `.code-workspace` file?

**Comment by rangav** [comment]
You need add those settings to `settings.json` File located in `.vscode` Folder 


https://code.visualstudio.com/docs/getstarted/settings

**Comment by rangav** [comment]
I dont have a remote workspace currently. 

Can you share your settings.json values here and where its located?

https://code.visualstudio.com/docs/remote/ssh#_advanced-forcing-an-extension-to-run-locally-remotely

**Comment by BananaAcid** [comment]
For the settings values, please read the first and second post of mine. :)

I will test the link you provided later.

**Comment by rangav** [comment]
the one your shared does look like proper settings file, it should look like below

<img width="422" alt="Screenshot 2022-03-22 at 14 34 06" src="https://user-images.githubusercontent.com/8637550/159506474-9be4686d-d411-4e88-adae-86283d1255dd.png">

**Comment by BananaAcid** [comment]
The settings key was some where in the docs for `.code-workspace` files. 

It is pretty easy to try out, I will prepare a workspace file (with above config) with the remote workspace extension and a test FTP -

**Comment by BananaAcid** [comment]
[remote-space-test.code-workspace.txt](https://github.com/rangav/thunder-client-support/files/8332665/remote-space-test.code-workspace.txt)

How to use:
1. remove the `.txt` ext.
2. doubleclick or open in vscode, open VS-Code workspace
3. click on add extensions on the lower right corner
4. click on thunder client icon
5. click on "New Request"

... and it opens a blank folder.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
