### ISSUE TITLE
[Feature] Function of Pre-request, one way to send one onre request before main request.

### ISSUE THREAD

**Issue by mauriliofilho** [rangav/thunder-client-support#374]

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by rangav** [comment]
please let me know your feedback on this https://github.com/rangav/thunder-client-support/issues/249#issuecomment-1061853717

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.
