### ISSUE TITLE
Support for running tests in Pipeline

### ISSUE THREAD

**Issue by mikaelsand** [rangav/thunder-client-support#376]
**Is your feature request related to a problem? Please describe.**
Being able to incorporate testing in a build or release pipeline is very useful. I do not see that being possible using collections or requests created by TC.

**Describe the solution you'd like**
A way of running the collection from the command line, similar to Newman.

**Describe alternatives you've considered**
No using TC.

**Comment by rangav** [comment]
Hi @mikaelsand thanks for feedback, will add to roadmap

**Comment by rangav** [comment]
related to #764 #98

**Comment by rangav** [comment]
Hi All, development is finished, We are planning to launch Thunder Client CLI next week, which will have lot of new innovative features, stay tuned…

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.0`

### Thunder Client CLI
- https://github.com/rangav/thunder-client-support/releases/tag/v2.4.0

### Documentation
- For documentation read our blog post on [medium.com](https://rangav.medium.com/d91eb5c71d8e)

### Product Hunt
- We are launching today on [Product Hunt](https://www.producthunt.com/posts/thunder-client-cli), Please **upvote** and let us know any feedback.

**Comment by rangav** [comment]
Hi All, 

Hope you all used `CLI` tool, Please let me know your feedback about what you like and any improvements required?

**Comment by douglas-gibbons-lark** [comment]
Thank you so much for this - it's the feature that I've been eagerly waiting for. I was able to easily incorporate it into a Docker image, and run our tests that way.

The only thing I'd personally like is to be able to run a collection and see more detail.  `tc --col mu_collection --log 1,2,7` looks nice, but didn't show me additional output.

**Comment by rangav** [comment]
Thanks @douglas-gibbons-lark for the feedback.

Currently `—log` switch is applied when you run request.

you can save reports to see more details for collection
- `tc —col my_collection —report cli,json,html`

let me know if the reports are useful or not?

**Comment by rangav** [comment]
Hi, Now you can run **Multiple or All Collections** from CLI in `v1.1.0`

- Run **All** Collections using `tc --col all`
- Run **Multiple** Collections `tc --col colIdOrName1,colIdOrName2`
- Update CLI to version - **v1.1.0**

Release Notes:
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.

**Comment by douglas-gibbons-lark** [comment]
> Currently `--log` switch is applied only when you run request - `tc 'requestName' --log 1,2,7`
> 
> you can save reports to see more details for collection
> 
> * `tc --col my_collection --report cli,json,html`

This is perfect - thank you. The HTML report is beautiful.

**Comment by rangav** [comment]
@douglas-gibbons-lark you are welcome. Glad you like it 🙂. Spent lot of time in designing Html report to make it beautiful.
