### ISSUE TITLE
Support Editor font family settings

### ISSUE THREAD

**Issue by shenghui0779** [rangav/thunder-client-support#377]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @shenghui0779 thanks for feedback, will add to roadmap

**Comment by rangav** [comment]
Hi @shenghui0779 there is existing issue for this #4. I am closing this one, so we can track in one place. You can add comments in that.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

Now the extension uses Editor Font style and Size

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

Please let me know your feedback.
