### ISSUE TITLE
JSON formatted output

### ISSUE THREAD

**Issue by sourvinos** [rangav/thunder-client-support#379]
For perfectionists, picky persons and fussy devs:
It would be nice if the user would be able to change the indentation of the output, say from two spaces to four for better visual appearance.

Thanks for being awesome! ❤

**Comment by rangav** [comment]
This feature is now implemented in version `v1.17.1`. please update and use the `Indent Size` setting as shown in image below

<img width="716" alt="Screenshot 2022-08-02 at 10 52 20" src="https://user-images.githubusercontent.com/8637550/182346803-b8f1de07-f43a-409f-9461-eb820ff7d23d.png">

Please let me know your feedback.
