### ISSUE TITLE
Allow Environments to inherit from others (prevents variable re definition)

### ISSUE THREAD

**Issue by harogaston** [rangav/thunder-client-support#38]
**Is your feature request related to a problem? Please describe.**
As a user I don't want to re-define common variables on each of the environments

**Describe the solution you'd like**
Envirnoment inheritance/extension something like nested folders for environment with a hierarchy so that variable definitions can be reused. 

**Describe alternatives you've considered**
Copy/pasting variables in all Environments, it gets hard when you need to make changes to them, specifically if you have many Environments

**Implementation:**
Postman handles this by means of Workspaces and Global variables. I don't find that a good solution. Because it doesn't allow for multiple nesting of environments (just one Global variables section) nor does make much sense to me. I'd rather have inheritance.

**Comment by rangav** [comment]
Hi @harogaston how about have `duplicate env` dropdown option, so it will copy variables to the new env?

**Comment by harogaston** [comment]
That would only work if you would never have to modify the "common" variables ever again. Otherwise you cannot keep your environments consistent.

**Comment by rangav** [comment]
Hi @harogaston please see the solution that will be implemented https://github.com/rangav/thunder-client-support/issues/70#issuecomment-830849370

**Comment by gaston-haro** [comment]
Hi! Sorry I didn't get what the proposed solution is.

**Comment by rangav** [comment]
Hi @gaston-haro see comment link. https://github.com/rangav/thunder-client-support/issues/70#issuecomment-830100080

There will be option to select any Env to make it global
and all others Env will inherit from it. if the variable available sub environment, it will use that value otherwise use the global.

**Comment by gaston-haro** [comment]
Hi @rangav I see it as a step forward. Though it doesn't solve my use case yet. Thanks for keeping me posted!

**Comment by rangav** [comment]
Global Env Variables implemented in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

Currently not planning to do any nested env
