### ISSUE TITLE
Allow empty passwords in Basic Auth

### ISSUE THREAD

**Issue by ThargoN** [rangav/thunder-client-support#380]
**Is your feature request related to a problem? Please describe.**
Basic Auth header is not added to the request when password is empty.

**Describe the solution you'd like**
Allow empty password strings.

**Comment by rangav** [comment]
Hi @ThargoN This will be part of next update which will be next week.

**Comment by rangav** [comment]
This feature is now implemented in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
