### ISSUE TITLE
Inherit authentication doesn't work

### ISSUE THREAD

**Issue by nickkrykunov** [rangav/thunder-client-support#381]
**Describe the bug**
I have a collection from the postman, where authentication is set globally.
But inherit auth in requests doesn't work, and i need to save auth in each request.

![image](https://user-images.githubusercontent.com/40613315/139050608-de72c67b-8ee5-4f02-ac9e-3810e69b4188.png)

![image](https://user-images.githubusercontent.com/40613315/139050768-fbb769ee-4ac6-426a-b640-17906cd5fb6b.png)

If i set bearer token manually, then it's working fine
![image](https://user-images.githubusercontent.com/40613315/139050890-75e494fd-fa93-47ec-aa99-7a9bdb02d2fa.png)

**Platform:** 
 - OS: Ubuntu 20.04.3 LTS
 - vscode version: 1.16.2
 - extension version: 1.9.1

**Comment by paramSonawane** [comment]
If the bearer token is inherited, it adds new line character at the end of token in Authorization header. But if it is given in the request itself (even from environment variable) it works.
![Using variable in bearer no newline at the end of token](https://user-images.githubusercontent.com/43324924/139637145-88104fcd-018b-45f8-9f2f-78a983dc0fb4.png)


![Using inherit adds a newline](https://user-images.githubusercontent.com/43324924/139637220-1fbc1a51-8b2a-45a1-b989-29ce26e982d7.png)

**Comment by rangav** [comment]
Thanks for reporting the issue, will look into it.

**Comment by rangav** [comment]
Hi Guys, Fixed this bug now, Will release part of next update, which will be by end of next week.

Thanks for notifying about this bug.

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
