### ISSUE TITLE
JSON body cursor wrong position

### ISSUE THREAD

**Issue by kstan79** [rangav/thunder-client-support#382]
**Describe the bug**
during i prepare http request with json body, i notice that the cursor is not exactly sit at correct position. I cause when i try something the text offset 1 space. 
I suspect this is font issue but cant solve it anyway. I don't have similar problem when i edit any source code in vscode.

**To Reproduce**
use below example:
```
{
    "action": "save",
    "data": {
        "global_tenant": [
                {
                  "tenant_code":"T1",
                  "tenant_name":"tenant 1"
                }
            ]
    }
}
```
<img width="572" alt="Screenshot 2021-10-28 at 11 55 35 AM" src="https://user-images.githubusercontent.com/1889979/139184191-e29377fd-750b-4c42-809a-514552b6e50e.png">

**Expected behavior**
Cursor shall focus at correct position

**Platform:** 
 - OS:  Mac OSX
 - vscode version: 1.61.2
 - extension version: v1.9.1

**Comment by rangav** [comment]
If you changes your vscode default font settings, could be the issue. 

please see here
https://github.com/rangav/thunder-client-support/issues/815#issuecomment-1318738562

**Comment by rangav** [comment]
closing this issue, feel free to re-open if needed
