### ISSUE TITLE
Support for request-level variables with caching

### ISSUE THREAD

**Issue by stefaanMLB** [rangav/thunder-client-support#383]
It would be great to have variables at the request level that cache the values that were used before
Basically, add a list the request window where on can add variables to be user in that request's url, headers or body
and add a value drop-down test field in which new values can be set or recent variables can be chosen
Having the cache synchronised between equally-named variables in different requests would be a great extention.

DBeaver's "where clause editor field" can server as inspiration
![image](https://user-images.githubusercontent.com/50827063/139216369-12e03939-d142-48dc-922e-50dd71cae925.png)

**Comment by rangav** [comment]
related to this #823
