### ISSUE TITLE
Is there a Description field for params?

### ISSUE THREAD

**Issue by Attiv** [rangav/thunder-client-support#387]
just like postman
![CleanShot 2021-11-05 at 16 45 22@2x](https://user-images.githubusercontent.com/15698129/140483037-946690c3-1542-4213-bebb-76d6f43ac582.png)

**Comment by rangav** [comment]
Hi @Attiv 

Currently not possible to add description

**Comment by Attiv** [comment]
@rangav 
Thanks :)

**Comment by rangav** [comment]
We now released a dedicated Docs tab for documentation in version `v1.14.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2

**Screenshots here**
https://github.com/rangav/thunder-client-support/issues/200#issuecomment-1082438213

Let me know if any feedback
