### ISSUE TITLE
Redirects with same method instead of GET in Thunder Client

### ISSUE THREAD

**Issue by Pawper** [rangav/thunder-client-support#388]
**Describe the bug**
Hello! I have a form POST route set up in an Express app. The route has a redirect. In the browser, this works as expected (redirect has method of GET). When I submit to the route with ThunderClient, the redirect is with a method of POST. I am not sure why...

**To Reproduce**
Express route (note the redirect):
```
app.post('/campgrounds/:id/reviews', validateReview, catchAsync(async (req, res) => {
    console.log("REVIEW POSTED!!!")
    const campground = await Campground.findById(req.params.id);
    const review = new Review(req.body.review);
    campground.reviews.push(review);
    await review.save();
    await campground.save();
    res.redirect(`/campgrounds/${campground._id}`);
}))
```
Thunder Client:
![image](https://user-images.githubusercontent.com/22269691/140696037-b95417b0-f186-4bc6-b7ee-37eb7386721d.png)

Form (EJS):
```
            <form action="/campgrounds/<%= campground._id %>/reviews" method="POST">
                <div>
                    <label for="rating">Rating</label>
                    <input class="form-range" type="range" min="1" max="5" name="review[rating]" id="rating">
                </div>
                <div class="mb-3">
                    <label for="body">Review</label>
                    <textarea name="review[body]" id="body" cols="30" rows="3" required></textarea>
                </div>
                <button>Submit</button>
            </form>
```

**Expected behavior**
Using morgan - this is what I get when submitting from the form on the web page:
![image](https://user-images.githubusercontent.com/22269691/140695940-41618a6c-6d62-433d-9d31-5efa4cc82028.png)
Instead I get this with Thunder Client:
![image](https://user-images.githubusercontent.com/22269691/140696080-a5498a06-4914-4806-b413-8087dcf8f260.png)

**Platform:** 
Visual Studio Code - Insiders

Version: 1.63.0-insider (user setup)
Commit: 552af97a0170b43c9323bec62211feb184da9749
Date: 2021-11-05T05:16:20.583Z (3 days ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

 - extension version: 1.9.1

**Comment by rangav** [comment]
Hi @Pawper thanks for reporting the issue

**Comment by rangav** [comment]
This issue is now fixed in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Comment by me-nkr** [comment]
issue persists in `v1.12.2`

**Comment by rangav** [comment]
Hi @me-nkr can you share more details of the issue you are facing and any screenshots
