### ISSUE TITLE
Syntax error indicator under the text block

### ISSUE THREAD

**Issue by diosby** [rangav/thunder-client-support#389]
**Is your feature request related to a problem? Please describe.**
I have a large JSON and when I past it into the text block it is pasted twice (it is a bug Thunder for all fields when I past data).

In result I have a mistaken JSON into the block, but it is so large that I don't see the mistake. To find the mistake I have to scroll all the input. It isn't usable and I don't sure that the mistake exists, because I have taken a valid JSON.

![Screenshot from 2021-11-10 16-25-23](https://user-images.githubusercontent.com/19969187/141122238-0ba00ba9-ff8b-4292-9f5f-62bd70e91ade.png)

**Describe the solution you'd like**
It would be useful if the indicator or the message is under the input. 
![Screenshot from 2021-11-10 16-25-23](https://user-images.githubusercontent.com/19969187/141122962-6d63de49-69e6-4f05-baa1-822ca27d9c77.png)

If it is possible then also scroll up to the line. 

Thank you!

**Comment by rangav** [comment]
Thanks @diosby for the feedback, will add to roadmap.

**Comment by rangav** [comment]
Hi @diosby this will be part of next update

**Comment by rangav** [comment]
This feature is now implemented in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
