### ISSUE TITLE
Allow using environment variables in request body

### ISSUE THREAD

**Issue by soumyamahunt** [rangav/thunder-client-support#390]
**Is your feature request related to a problem? Please describe.**

In some scenarios I want to use environment variables in my post request body but can't currently do so. For example, I want to send json in the following format:
```
{
    "name": {{user_name}}
    "address": {{address_line1}}
}
```

**Describe the solution you'd like**
 
I would like to have option to directly use environment variables inside request body

**Describe alternatives you've considered**

Copy pasting values present in env, not a good solution by the way.

**Implementation:**

1. If it is possible I would like to have option to directly use environment variables inside request body.
2. Alternatively there can be a way to write javascript code that constructs request body. [Proxyman](https://docs.proxyman.io/scripting/script) allows writing pre-processing/post-processing scripts that modify request body and response data respectively. Similar approach can be taken for Thunderclient if mentioned approach in 1st point not possible.

By the way love this tool and all the effort you are making to make it better than alternatives.

**Comment by rangav** [comment]
Hi @soumyamahunt 

you can use environment variables request body

Color highlighting is not supported yet

**Comment by soumyamahunt** [comment]
> Hi @soumyamahunt
> 
> you can use environment variables request body
> 
> Color highlighting is not supported yet

Thank you, I was confused because couldn't see any indication that response body is detecting environment value. Closing this issue since it is already implemented.
