### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [rangav/thunder-client-support#391]
Getting this error with no other details

**Comment by rangav** [comment]
Hi @mcrobbj-abrdn, can you please screenshot

**Comment by mcrobbj-abrdn** [comment]
![certs](https://user-images.githubusercontent.com/93191982/142636312-42092289-0f36-4191-a629-74ebb1955944.jpg)

Is there a log file with more info?

**Comment by rangav** [comment]
Don’t have a log file, are you making a request with manual ssl certificates? 

never saw that error before.

**Comment by mcrobbj-abrdn** [comment]
I havent made any changes to the default config. Where are the certs is Thunderclient/VSC using?

**Comment by rangav** [comment]
Thunder Client does not use certificates by default, user can provide them using the below config.

See manual config section 
https://github.com/rangav/thunder-client-support#auth

**Comment by rangav** [comment]
Hi @mcrobbj-abrdn 

We have published new version, see if its working now

https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

**Comment by rangav** [comment]
Hi @mcrobbj-abrdn I am closing this issue, feel free to reopen if needed.
