### ISSUE TITLE
How to disable automatic line wrapping in response?

### ISSUE THREAD

**Issue by Offerel** [rangav/thunder-client-support#392]
Some of my responses have relatively long lines. How can I prevent the lines in the response from being automatically wrapped?

**Comment by rangav** [comment]
Hi @Offerel currently not possible, we can provide setting option in future

**Comment by Offerel** [comment]
This would be nice. This is my first try with Thunder Client and i really like the what i can do with it. I spent a few hours today optimizing my response on the server side, until I realized that the incorrect formatting was not caused by the response at all. So anyway, I'll wait eagerly for future versions.

**Comment by rangav** [comment]
Hi @Offerel there is full screen view button for the response, it may reduce the wrapping issue. let me know if that works.

**Comment by Offerel** [comment]
Hi there. This is a little bit better, but not really a full solution. For example logfiles are a pain to read in this case. As a workaround, I copy&paste the response currently to a external editor. Hopefully you can find a full solution in future, since i really like the addon.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback

**Comment by Offerel** [comment]
Nice. Many thx. This works now as expected. Many thx for this.

**Comment by rangav** [comment]
Thanks great @Offerel, thanks for confirmation 👍

**Comment by rangav** [comment]
@Offerel forgot to mention you can also use keyboard shortcut `Alt+Z` to toggle Word Wrap, same shortcut as vscode.
