### ISSUE TITLE
Request body is saved in the collections when it isn't called

### ISSUE THREAD

**Issue by diosby** [rangav/thunder-client-support#393]
**Describe the bug**
I have saved a collection of requests. When I am continuing to work with the collection and changes the body I don't save the items of the collection, but they have the last body. 

**To Reproduce**
1. Make an request of a collection with a body.
2. Change the body, but don't save it.
3. Send the request.
4. The body is saved.

**Expected behavior**
I expected that changed request body will reset after reopening or when I send requests with a new body it makes new items for each new body (or it's optional). Add a button to reset changes and return the base body and parameters (all the parameters of the request). 
![Screenshot from 2021-11-16 16-49-05](https://user-images.githubusercontent.com/19969187/141997698-b94522eb-e084-4caf-ad10-805cbea72502.png)

**Platform:** 
 - OS: Ubuntu 20.04
 - vscode version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:51:30.084Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-40-generic
 - extension version: v1.9.1

Thank you!

**Comment by rangav** [comment]
Hi @diosby all the requests are auto-saved when you send the request.

**Comment by diosby** [comment]
Hi @rangav! I see it, but I inspect another case, because I lose saved requests and it doesn't keep recent questions. 

I hope it will be fixed in the future. Thanks!

**Comment by rangav** [comment]
Hi @diosby, I can provide vscode setting option to disable auto-save, so when you send a request nothing will be saved, Request details will be saved only when `Ctrl+s` is used,

let me know if that is any useful?

**Comment by diosby** [comment]
Hi @rangav ! For a fast solution it sounds good. The expected behaviour in the topic is the best solution for me (where a user can choose an action for the changes. 

Could you please answer some questions about it?

1. Will the query be reset after changing queries? I do series different queries in a collection and the acititvies and I have to keep saved data between them. If the data are reset after choosing another query it would be better not to change anything now.  
2. Is it possible to add changed requests to the Activity? 

Thanks!

**Comment by rangav** [comment]
1. When auto-save is disabled (not implemented yet) you can run queries on the request, new changes not applied yet until you save, close the window/tab, open again you will see the original request details 
2. We have vscode setting `show in activity` If you enable it, when you run requests in collection it will show in activity tab

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback

**Comment by rangav** [comment]
Read 2nd point here, for more details 
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0
