### ISSUE TITLE
Content-Type is added twice to codegen if it is both explicitly set by the user and implicitly set through the content of the body

### ISSUE THREAD

**Issue by benthillerkus** [rangav/thunder-client-support#394]
**Describe the bug**
I'm working against an API that only accepts JSON structured data but requires a custom `Content-Type` header to be set.
Unfortunately, _Thunder Client_ will just add whatever it infers from the option I set in the data menu and adds that Header additionally to the request, effectively trying to add two `Content-Type` headers.

**To Reproduce**
Set `Content-Type` yourself. Then add some data to the request.

![image](https://user-images.githubusercontent.com/29630575/142095081-4939432a-5b73-4d65-acfe-a7b3d8e01beb.png)
![image](https://user-images.githubusercontent.com/29630575/142095102-05d17352-c07a-48c9-85b3-aa14b0773b88.png)

**Expected behavior**
If the user sets a custom `Content-Type` header, _Tunder Client_ will not add another `Content-Type` header.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.62.2
 - extension version: 1.9.1

**Comment by rangav** [comment]
Hi @benthillerkus 

you are using `get` request, please try POST request

**Comment by benthillerkus** [comment]
Hi Ranga

unfortunately, the behavior persists

**Comment by rangav** [comment]
Thanks for feedback, I will verify and fix it soon.

**Comment by jmwhelan** [comment]
I am encountering the same issue. Custom content type but thunder client changes it to: text/xml; charset="utf-8"

**Comment by rangav** [comment]
I just tested the custom content-type, its working for me, see image below

![content-type](https://user-images.githubusercontent.com/8637550/145887532-eba5dfbe-93ab-483b-b18d-b9c35e40dc3f.PNG)

**Comment by rangav** [comment]
Note: The error is only with code snippet generation code, not when sending actual request.

**Comment by rangav** [comment]
Hi All, This is fixed now, will be part of next update.

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
