### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by JasonGoemaatAtCorteva** [rangav/thunder-client-support#396]
**Describe the bug**

Thunder doesn't show anything and there's no way to do anything

**To Reproduce**

1. Install "Thunder Client" in VS Code
2. Click on the new lightning icon on the left
3. Activity, Collections, and Env show default messages and have no options to do anything:
    *  'Welcome to Thunder Client', 'Your activity will appear here...'
    * 'No Collections Available...', 'You can create collections here...'
    * 'No Environments Available...', 'Save sensitive information here...'
4. CTRL+SHIFT+P and selecting 'Thunder Client: New Request' creates a 'New Request' tab that is completely blank with nothing to do

**Expected behavior**

I'm not sure, this is the first time I'm trying to use Thunder Client and there doesn't appear to be a way to do anything

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.62.2
 - extension version: v1.9.1

**Solution:**

**Comment by rangav** [comment]
Hi @JasonGoemaatAtCorteva, 

This could be issue with latest version of vscode, can you try downgrading vscode to previous version.

**Comment by fowl2** [comment]
Running VS Code 1.62.3 on Windows, I had to downgrade to Thunder Client 1.8.1 and open a request. After doing that, I could upgrade to 1.9.1 and it works.

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
