### ISSUE TITLE
Synchronization of the collections with the account storage

### ISSUE THREAD

**Issue by mayaleh** [rangav/thunder-client-support#397]
Hello,

it would be nice to have synchronization of the collections to VSCode account. So, when switching to another machine, the collections will be available under the account on all machines.

![image](https://user-images.githubusercontent.com/20840273/142392858-fca5b264-323a-47eb-9f94-d8d5148d9f4f.png)

For example, this feature is available in SQL server ext from MS:
https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

Alternativly solution could be ability to export all collections in the same time.

**Comment by rangav** [comment]
Hi @mayaleh this is possible with saving requests to git project.

please see details here
https://github.com/rangav/thunder-client-support#team
