### ISSUE TITLE
Clicking and Dragging in the URL field does not move cursor to left or right

### ISSUE THREAD

**Issue by jandreaucodes** [rangav/thunder-client-support#398]
**Describe the bug**
If the entirety of my URL does not fit in the URL bar, clicking and dragging does not move my cursor to the end like it does in a traditional input field. See screencast: https://kustomer.d.pr/TMW2Bb

**To Reproduce**

Make your VS Code window narrow.
Enter a URL into the URL window
Try to drag your cursor to the end of the text.

**Expected behavior**

Text scrolls to the right to allow me to add more to the end of the URL.

**Platform:** 
 - OS: macOS Big Sur 11.6
 - vscode version: 1.62.1
 - extension version: 1.9.1

**Solution:**

**Comment by rangav** [comment]
Hi @jandreaucodes, thanks for reporting, will look into it.

**Comment by rangav** [comment]
I have fixed the problem now, would you like to test and confirm?

[vscode-thunder-client-1.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/8470084/vscode-thunder-client-1.16.1.vsix.zip)

Download the attachment and install vsix manually as below
<img width="533" alt="Screenshot 2022-04-12 at 07 26 55" src="https://user-images.githubusercontent.com/8637550/162894687-4aea1d35-feeb-4d08-a217-3677d47451b5.png">

Please let me know your feedback

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
