### ISSUE TITLE
Please include code snippet for php curl like postman

### ISSUE THREAD

**Issue by lenner90** [rangav/thunder-client-support#399]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
hi @lenner90 are you looking for phpcurl in the codegen?

**Comment by rangav** [comment]
if you like to contribute, here is repo link https://github.com/rangav/thunder-codegen

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

**Comment by lenner90** [comment]
thanks
