### ISSUE TITLE
Respect Editor font family settings

### ISSUE THREAD

**Issue by naiyerasif** [rangav/thunder-client-support#4]
Thunder Client displays the request body and response using it's own monospaced font family stack. Instead, it should use the editor font family configured by the user.

Environment:
Thunder Client 1.0.5
VS Code 1.55.0
Windows 10 20H2

**Comment by rangav** [comment]
I am using Ace Editor for syntax highlighting, it only supports monospace fonts.

**Comment by izcream** [comment]
+1 default font on windows with large screen look not smooth😂

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
