### ISSUE TITLE
Add Headers using raw mode

### ISSUE THREAD

**Issue by uchihaslowx** [rangav/thunder-client-support#40]
**Is your feature request related to a problem? Please describe.**
In the "Header" tab, add the "RAW" option, then when you need to copy all the "Headers" of a Web, you can paste them quickly.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/16154111/115967838-74020200-a4fa-11eb-94e1-35e55a5df3e8.png)

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @uchihaslowx will add this product roadmap
