### ISSUE TITLE
Open multiple windows at the same time

### ISSUE THREAD

**Issue by stefaanMLB** [rangav/thunder-client-support#400]
Is it possible to open more than 1 window simultanuous ?
When I click on a request while having a window open, the open window gets overwritten with the clicked request.
I'd like to open 2 Thunder Client Windows next side-to-side

**Comment by rangav** [comment]
Hi @stefaanMLB 

click option icon (…), select `Open in New Tab`

Or `Ctrl + Click` On a request

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
