### ISSUE TITLE
Can't set to variable from json array

### ISSUE THREAD

**Issue by Alynva** [rangav/thunder-client-support#401]
**Describe the bug**

I'm trying to set to a variable a value under a list.

**To Reproduce**

The API may respond with an array (eg. `[{ test: 1 }]`) or within the object (eg. `{ list: [{ test: 1 }] }`

**Expected behavior**

I think that it should work these values:
- `json[0].test`
- `json.list[0].test`

**Platform:** 
 - OS: Windows
 - vscode version: v1.62.3
 - extension version: v1.9.1

**Solution:**

**Comment by Alynva** [comment]
Nevermind, it works without `[]`: `json.0.test`. I think it should be documented.

**Comment by alejandrofdez-us** [comment]
My API returns an array, in order to access one element json.positionNumber is not working anymore.

Any thoughts?

**Comment by rangav** [comment]
Hi @alejandrofdez-us 

You can use `json[0]`

See docs
https://github.com/rangav/thunder-client-support/blob/master/docs/testing.md#test-arrays

**Comment by rangav** [comment]
@alejandrofdez-us setting Env variable is not a test, so its not displayed in Results tab. Thats by design.
