### ISSUE TITLE
Export the run collection results

### ISSUE THREAD

**Issue by Alynva** [rangav/thunder-client-support#402]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I would like to export the results when I run all the requests under the collection. Not only the summary, like, the table, I would need the entire data for each request. I want to process that later (with my own external script) to create a report of how are the API going.

**Describe alternatives you've considered**

Idk, I just want to have that information that is already in the memory.

**Implementation:**

**Comment by rangav** [comment]
Hi @Alynva Thanks for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
