### ISSUE TITLE
Any plans to spin this off as a standalone app ?

### ISSUE THREAD

**Issue by arslantx** [rangav/thunder-client-support#403]
I really like this. It would be really great if there was an app version of this too. For example, when I open new folder in vscode, all open thunder client tabs also disappear. Any plans to make it as a separate app ?

**Comment by rangav** [comment]
Hi @arslantx currently no plans to launch separate standalone app.

**Comment by rangav** [comment]
Hi @arslantx  I am closing this issue, feel free to re-open if needed
