### ISSUE TITLE
[Feature] - Add pre-request script

### ISSUE THREAD

**Issue by engFelipeMonteiro** [rangav/thunder-client-support#409]
**Case of use:**
Need random data on each request

**Describe the solution you'd like**
Maybe a script support to add valiable with JS or typescript.

**Describe alternatives you've considered**
Maybe another intermediate option to generate a json output to be used

**Comment by chrisbward** [comment]
Would be useful for fetching CSRF headers!

**Comment by chrisbward** [comment]
https://blogs.sap.com/2019/08/27/csrf-token-in-postman.-one-click-to-get-it-and-use-it./

**Comment by rangav** [comment]
Hi @chrisbward thanks for feedback, will add to roadmap

**Comment by rangav** [comment]
Hi @chrisbward  there is an existing issue related to this, so closing this one. you can add any further comments in below issue

#16

**Comment by rangav** [comment]
please let me know your feedback on this https://github.com/rangav/thunder-client-support/issues/249#issuecomment-1061853717
