### ISSUE TITLE
Right Click > Copy Value to Environment Variable

### ISSUE THREAD

**Issue by dickofn** [rangav/thunder-client-support#41]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to fill my variable value with something from api response, an easy way to block and copy the response to my variable is awesome. Like the build-in feature in Postman, thank you!

**Comment by rangav** [comment]
Hi @dickofn this is possible now, you can set env variable from tests tab, see **scriptless testing** section for details.

**Comment by dickofn** [comment]
> Hi @dickofn this is possible now, you can set env variable from tests tab, see **scriptless testing** section for details.

I see it work the same way, but done it with a different way... as long as it gives same result, I'm happy. Thanks for the great plugin
