### ISSUE TITLE
Font Size in send/response windows

### ISSUE THREAD

**Issue by GreatScott000** [rangav/thunder-client-support#410]
**Is your feature request related to a problem? Please describe.**
My eyesight is not what it used to be and small fonts make it difficult for me to read.  I know I can zoom in/out (ctrl+/ctrl-) in vs code but that affects that whole window and all the "widgets".  I prefer making the font in the "code" window larger using ctrl+zoom.

**Describe the solution you'd like**
The ability to increase/decrease the font size in the send and response windows

**Describe alternatives you've considered**
As noted the zoom in/out in VS code works but makes everything bigger not just the current tab.

**Implementation:**
Sorry, beyond my current capabilities.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
