### ISSUE TITLE
Resize/wrap URL control when overflows

### ISSUE THREAD

**Issue by GreatScott000** [rangav/thunder-client-support#411]
**Is your feature request related to a problem? Please describe.**
When editing/viewing the url to be sent, it is bothersome to have to scroll through the url to make sure you typed everything correctly.

**Describe the solution you'd like**
If the URL control would "wrap" at the "send" button and vertically resize so there is no need to scroll through the control.

**Describe alternatives you've considered**
Resizing the panels works but as per #305 it is very fussy when the selection is active and when another request is selected the panels reset to the default and you have to fight with the splitter again.

**Implementation:**
Sorry, no.

**Comment by rangav** [comment]
Hi @GreatScott000 thanks for feedback, will add to roadmap

**Comment by rangav** [comment]
Hi @GreatScott000 thanks for the feedback, there is existing issue for this #308. I am closing this one, so we can track in one place. You can add comments in that.
