### ISSUE TITLE
Thunder future - Questions

### ISSUE THREAD

**Issue by majso** [rangav/thunder-client-support#412]
Hey, 

First of all, thank you for your work on this awesome extension.

I have couple of questions regarding future of Thunder:

- Is there a plan to make extension open source?
- When we can expect new version and what is planned to be implemented?

Thanks!

**Comment by rangav** [comment]
Hi @majso 

1. I haven't any decision about open source yet,
2. The next version will be end of this month or early January. I will post more about the features planned later.

Let me know if you need any specific feature.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
