### ISSUE TITLE
Reordering of Environment Variables

### ISSUE THREAD

**Issue by kahennig** [rangav/thunder-client-support#414]
Hi, first of all, congrats on a great tool!!!
Just a item for the wish list if possible :)

**Is your feature request related to a problem? Please describe.**
Not related to a problem - it's a features suggestion.
On the Environment Variables page, the variables cannot be easily reordered

**Describe the solution you'd like**
On the Environment Variables page it would be great to be able to easily reorder the variables. (ideally via drag and drop or arrows to move a variable up or down)

**Describe alternatives you've considered**
The alternative would be to copy and paste both name and value up or down until they are ordere correctly.
It is rather gruesome when dealing with about 20 variables which is about average for me.

**Implementation:**
Sorry, no idea on this front.

**Comment by rangav** [comment]
HI @kahennig thanks for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
