### ISSUE TITLE
Slightly confused as to how to configure "Load From Project"

### ISSUE THREAD

**Issue by alexander-paterson** [rangav/thunder-client-support#415]
I have my code stored in `/home/alex/_code/{project1}`

I have my `.code-workspace` file in the `.vscode` folder in my project. (So `/home/alex/_code/{project1}/.vscode`)

I have `Load From Project` checked and I have `Workspace Relative Path` set to `..` but I'm not seeing the thunder-tests folder `/home/alex/_code/{project1}/thunder-tests`

Have I completed got the wrong end of the stick with configuring this?

**Comment by rangav** [comment]
Hi @alexander-paterson 

remove `..` from `Workspace Relative Path`, leave it empty if you want at root of project folder 

`Workspace Relative Path` is useful if like save in sub folder or parent folder
