### ISSUE TITLE
Export to Postman

### ISSUE THREAD

**Issue by Diwakar14** [rangav/thunder-client-support#416]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I have created a small script to export to Postman, currently it only supports formdata and json. Please have a look.

**Implementation:**
let thunder = <Thunder Client Export Object>
let postman = {
    info: {},
    item: [],
};

postman.info = {
    _postman_id: "4fef4022-4e0c-49ee-ba3c-12f31786b105",
    name: <Name of your collection>
    schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
};

let request = null;

for (let index = 0; index < thunder.folders.length; index++) {
    const element = thunder.folders[index];
    let items = [];
    for (let index = 0; index < thunder.requests.length; index++) {
        const requests = thunder.requests[index];

        if (element._id === requests.containerId) {
            if (requests.body?.type === "json") {
                request = {
                    mode: "raw",
                    raw: requests.body.raw,
                    options: {
                        raw: {
                            language: "json",
                        },
                    },
                };
            } else if (requests.body?.type === "formdata") {
                request = {
                    mode: requests.body?.type,
                    formdata: requests.body?.form.map((form) => ({
                        key: form.name,
                        value: form.value,
                        type: "text",
                    })),
                };
            }
            items.push({
                name: requests.name,
                protocolProfileBehavior: {
                    disableBodyPruning: true,
                },
                request: {
                    auth: {
                        type: requests.auth?.type,
                        bearer: [
                            {
                                key: "token",
                                value: requests.auth?.bearer,
                                type: "string",
                            },
                        ],
                    },
                    method: requests.method,
                    header: [],
                    body: request,
                    url: {
                        raw: requests?.url,
                        host: [requests?.url],
                    },
                },
                response: [],
            });
        }
    }

    postman.item.push({
        name: element.name,
        item: items,
    });
}

fs.writeFile("./postman.json", JSON.stringify(postman), function (err) {
    if (err) {
        return console.log(err);
    }
    console.log("The file was saved!");
});

**Comment by rangav** [comment]
Thanks @Diwakar14 for creating the script, will look into it.

**Comment by rangav** [comment]
Related to #162

**Comment by Diwakar14** [comment]
Hello Ranga,

Thanks for your reply and involving in update.

Ok, I will review this once again.

Thanks again.

**Comment by rangav** [comment]
Also closing this issue, there is existing similar issue https://github.com/rangav/thunder-client-support/issues/162

So you can add any further comments there.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback

**Comment by Diwakar14** [comment]
Awesome, thanks!

**Comment by roofiq** [comment]
Hey @rangav, would be cool to have similar for environments :)

**Comment by rangav** [comment]
@roofiq sure, will implement in the next update

**Comment by rangav** [comment]
Convert environment is now implemented and published to marketplace as release version `v1.14.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2

Let me know if any feedback
