### ISSUE TITLE
Sync feature

### ISSUE THREAD

**Issue by dalisoft** [rangav/thunder-client-support#417]
**Is your feature request related to a problem? Please describe.**
Using this extension on two machines does not get sync

**Describe the solution you'd like**
Adding sync feature

**Describe alternatives you've considered**
Using GitHub as sync account as used by **Settings Sync**, **GitLens**

**Implementation:**

**Comment by rangav** [comment]
Hi @dalisoft 

see documentation here
https://github.com/rangav/thunder-client-support#team

**Comment by dalisoft** [comment]
@rangav Thank you, yes it's good way to get started, but more easier variant could be better, i'll can wait

**Comment by rangav** [comment]
Settings sync, git lens, they are single account sync right?

**Comment by dalisoft** [comment]
Yes, they are using my VSCode GitHub account. One account for all thing in VSCode, very great feature

<img width="520" alt="Screenshot 2021-12-15 at 12 38 22" src="https://user-images.githubusercontent.com/3511344/146143628-6f6bc180-a9cb-4b46-b024-4366d7a2b8d9.png">

**Comment by rangav** [comment]
That may not be suitable for team with multiple members, so it’s not a suitable solution for this api client.

what we is easy and better with no login needed, just save to git folder.

**Comment by dalisoft** [comment]
@rangav Thanks, i just wanted to know it's possible or not

**Comment by rangav** [comment]
@dalisoft as I said above, currently no plans to implement any other sync solution.
