### ISSUE TITLE
Set env variable from returned header.

### ISSUE THREAD

**Issue by larkov** [rangav/thunder-client-support#42]
**Is your feature request related to a problem? Please describe.**
API I'm using returns token in header and not in the body as json.

**Describe the solution you'd like**
It would be nice to set env variables from header response in the same way as from json results.

**Comment by rangav** [comment]
Hi @larkov will add to the product roadmap list.

**Comment by vaseyxxi** [comment]
Set env variable from cookies would be great too.

**Comment by rangav** [comment]
sure will add cookie option too.

**Comment by aalbericio** [comment]
I'm also waiting for this feature.

Setting a ENV variable from a returned Header is a very common pattern.

Thanks!

**Comment by aalbericio** [comment]
You should also rename some actions to something like:

header.token "storeIn" {{TOKEN}} 

Or something like that.

**Comment by rangav** [comment]
This feature is released in v1.2.1 for details https://github.com/rangav/thunder-client-support/releases/tag/1.2.1

See documentation how to use

**Comment by rangav** [comment]
Hi All, I have changed the prefix for Set Env from Header and Cookie in v1.2.2, the new prefix are below
The prefix for `set var from header `is `header.` instead of `h:`
The prefix for `set var from cookie` is `cookie.` instead of `c:`
