### ISSUE TITLE
Form Fields and Form Encoded cannot input  Chinese.

### ISSUE THREAD

**Issue by wudder** [rangav/thunder-client-support#420]
**Describe the bug**

Form Fields and Form Encoded cannot input  Chinese.
**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: macOS Catalina 10.15.7
 - vscode version: 1.63.2
 - extension version: 1.9.1

**Solution:**

**Comment by rangav** [comment]
Hi @wudder  thanks for feedback, will add to roadmap

**Comment by rangav** [comment]
I am closing this, as we already have a existing issue for this https://github.com/rangav/thunder-client-support/issues/161

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
