### ISSUE TITLE
Team feature issue

### ISSUE THREAD

**Issue by ashokganesan** [rangav/thunder-client-support#421]
**Describe the bug**

I installed Extension in my workspace and my developer workspace. I used a custom path to store the collection JSON file. When I access my developer workspace, the extension page shows an error . I checked the ownership of thunderclient JSON files is in my name if I change it to www-data then I can able to access it from my developer workspace, but not from my workspace since it automatically changed the owner to my developer. Can you please suggest a solution for this?

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: Windows 10 in AWS workspace
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Hi @ashokganesan 

what is difference between my workspace and my developer workspace? are they separate project folders?

also please check the same `custom path` value is used for both workspaces

**Comment by ashokganesan** [comment]
Hello

Thanks for the reply.

We worked on the AWS workspace.

Working on the same server but a different folder, my path will become /home/aganesan/..., and developer path will be /home/developer/...

For the custom path I gave /local/dev/, this can access by both of us.

**Comment by rangav** [comment]
thanks @ashokganesan

can you confirm that in the vscode settings for both workspaces the custom path value is `/local/dev/`

and both are local workspaces right?

**Comment by ashokganesan** [comment]
Yes its the same path only

**Comment by rangav** [comment]
- can you share screenshot of the error 
- can you share screenshot of the vscode setting for custom location for both workspaces, to make sure its all ok here?

**Comment by ashokganesan** [comment]
Below is My Developer Workspace screenshot when he click the icon
![image (1)](https://user-images.githubusercontent.com/92977812/147256294-0e893386-c004-4ccb-8106-a49887137e3d.png)

Below is My Workspace screenshot when i click the icon
![image (2)](https://user-images.githubusercontent.com/92977812/147256347-a4ca8dab-be13-4e5e-a89e-c34d5a3dcf67.png)

Below the filecustompath
![image](https://user-images.githubusercontent.com/92977812/147256600-f79b65e2-7c06-40cc-a7ec-c75fecb5c968.png)

Below is the file stored with my name as owner
![image](https://user-images.githubusercontent.com/92977812/147256902-164b77a0-908a-418b-afae-d03e05f4dc87.png)

**Comment by rangav** [comment]
thanks @ashokganesan for sharing screenshots

your developer workspace is it remote or local workspace?

**Comment by ashokganesan** [comment]
We both using Amazon Workspace Client. Its remote.

**Comment by rangav** [comment]
I think its remote workspace related issue, the paths are different for local and remote.

try the setting in the below comment
https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by ashokganesan** [comment]
So in settings.json I need to set like below correct?

	"thunder-client.customLocation": "/local/dev/gp_api_samples",
	"remote.extensionKind": {
		"rangav.vscode-thunder-client": ["ui"],
	}

**Comment by rangav** [comment]
yes please try that and let me know

**Comment by ashokganesan** [comment]
Once I added my existing collection was gone. I can able to create New Collection, but unable to import a collection, it gives 'Failed to Import'

**Comment by rangav** [comment]
where is the collection file located that your are importing?

**Comment by ashokganesan** [comment]
In My Workspace

**Comment by rangav** [comment]
may be try copying that json file to your local pc and try to import it. again this could be path issue.

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
