### ISSUE TITLE
Show the name of the request in the pane, not just in the tab. Also make the request being edited more distinctive in the requests list.

### ISSUE THREAD

**Issue by razaltcom** [rangav/thunder-client-support#422]
**Is your feature request related to a problem? Please describe.**

I use descriptive names on my requests. These request may have the same url (E.g. they change only in the access_token, etc. For when I want to test multiple users, etc.). When I have a couple of tabs open (tabs of code editors and thunderclient tabs) I can confuse which request I am working on, since they have the same url.

**Describe the solution you'd like**

Show the name of the request just above the url field.

See the image.

![Capture](https://user-images.githubusercontent.com/79233395/147379370-26875eae-0e47-4702-b096-2ae5e71fb9ea.PNG)

Another help on this issue would be highlighting the request being edited in the list on the left. See the image.

![Capture2](https://user-images.githubusercontent.com/79233395/147379483-78f37aa8-cc7c-4335-a10f-81bf2718a148.PNG)

Thanks a bunch, avesome client though. I love that everything is savable inside the project directory.

**Comment by rangav** [comment]
Hi @razaltcom thanks for the feedback, will add to roadmap

**Comment by razaltcom** [comment]
You are welcome. For the time being, I started giving ids to request names to circumvent this issue. E.g 

1- Login Ozi1
2- Login Ozi 2
...

Here "1-" is part of the name.

Best.

**Comment by rangav** [comment]
We published new version v1.10.0
The length of the request window name increased to 25 chars

https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

Please let me know if any feedback.

**Comment by oaltun** [comment]
I am not sure what was changed. I installed v1.10.0 and the tab lenght is still 11 or 12 characters.

**Comment by oaltun** [comment]
Yes, 25 characters is much better. I still think the UI improvements I suggested is needed to make the usage easier. Thanks again.

**Comment by rangav** [comment]
Highlighting sidebar request item already is in development, It will be part of next update

**Comment by rangav** [comment]
related #269

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback
