### ISSUE TITLE
Import from Postman not available?

### ISSUE THREAD

**Issue by jdpedrie** [rangav/thunder-client-support#424]
I installed the plugin this morning, and have been trying to figure out how to import my Postman collections.

The README references https://github.com/rangav/thunder-imports, which apparently no longer exists. I found the utility to import cURL, but nothing regarding postman.

Am I missing something?

**Comment by rangav** [comment]
Hi @jdpedrie 

Click on `Collection Tab` and Click Menu Icon near Search and you will see import option. this will import postman collection

Let me now if you have further questions

**Comment by rangav** [comment]
Hi @jdpedrie  I am closing this issue, feel free to re-open if needed
