### ISSUE TITLE
Uploading multiple files in a single field as in postman

### ISSUE THREAD

**Issue by sushantg2001** [rangav/thunder-client-support#425]
**Is your feature request related to a problem? Please describe.**
We cannot upload multiple files as a list in a POST or PATCH request.

**Describe the solution you'd like**
We can Implement a solution similar to how POSTMAN allows uploading multiple files
https://stackoverflow.com/questions/28185300/how-to-send-multiple-files-in-postman-restful-web-service

**Comment by rangav** [comment]
Hi @sushantg2001 

did you try the `Form` tab, in Body and select `Files` Checkbox

**Comment by sushantg2001** [comment]
I did but then we can only add one file per field. What if we need to add a list of files?

**Comment by rangav** [comment]
Try adding same field name to multiple inputs and upload files and see if you getting the desired result.

**Comment by sushantg2001** [comment]
Thanks now it is working

**Comment by sushantg2001** [comment]
Is there a way for us to handle nested fields as well using forms, rather than the json format?

**Comment by rangav** [comment]
did not understood your question, can you share a screenshot.

**Comment by rangav** [comment]
Hi @sushantg2001  I am closing this issue, feel free to re-open if needed

**Comment by MatheusRamalho** [comment]
Putting the same input name on all file entries didn't work, the fields are ignored and only the last one is sent.

**Comment by rangav** [comment]
@MatheusRamalho can you share screenshot?
