### ISSUE TITLE
Refresh button for Requests Collection 

### ISSUE THREAD

**Issue by vembry** [rangav/thunder-client-support#427]
**Is your feature request related to a problem? Please describe.**

The problem I'm having is having request collection not updated in realtime.

step to reproduce(atleast from what i can find):
- make new request on thunderclient
- do `git stash`
- reload vscode window
- open thunderclient
- do `git stash pop` to brings back the change
- the stashed new request wont show up on UI, but its shows up on thunderclient.db

##
**Describe the solution you'd like**

I would like to have a button to refresh the request collections on the UI.
Or make the collection to track the thunderclient.db changes in real time

##
**Describe alternatives you've considered**

##
**Implementation:**

**Comment by rangav** [comment]
Hi @vembry 

In collection tab click Main Menu near search and select `Reload` option

**Comment by vembry** [comment]
![image](https://user-images.githubusercontent.com/22610742/147772607-4e866808-48de-478d-9302-12259807a432.png)
ah yes, my bad 🙏
