### ISSUE TITLE
New feature : Export collection run results to a file

### ISSUE THREAD

**Issue by raphapari** [rangav/thunder-client-support#428]
**Context**: When running collections, we have a pretty screen which is great, but no way to export these results for later archiving.

![image](https://user-images.githubusercontent.com/6030197/147736390-2c38b103-313b-44d4-a60c-fe219f75b2e7.png)

**Proposed feature**: When running collections, it would be interesting to be able to export the results displayed on screen (requests, statusCode and test results) as a stuctured file (json, xml, csv or else) so that we can keep a trace of these tests results in time outside of VSCode and include it in release or QA reports.

![147736390-2c38b103-313b-44d4-a60c-fe219f75b2e7_2](https://user-images.githubusercontent.com/6030197/147736869-96fef1d7-8efd-4d66-b471-f9cd78d58019.png)

Thanks @rangav for this great extension and the time you dedicate to it!

**Comment by rangav** [comment]
Hi @raphapari that’s a good feature to have, will add to roadmap.

**Comment by rangav** [comment]
Hi there is an existing issue related to this, so closing this one. you can add any further comments in below issue

#402

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
