### ISSUE TITLE
In dark theme `Cancel Request` option on hover is not visible.

### ISSUE THREAD

**Issue by MUzairS15** [rangav/thunder-client-support#429]
The Cancel Request option is not visible on hover when the dark theme is enabled.
Pls, see the attached video.

https://user-images.githubusercontent.com/79860504/147833082-5cdf7e0f-28da-4666-b87d-faea1e1b3189.mov

**Expected behaviour**
Button should be visible on hover in all themes.
**Platform:** 
 - OS: MacOS BigSur
 - vscode version: 1.62.1
 - extension version:v1.9.1

**Comment by rangav** [comment]
Hi @MUzairS15 thanks for reporting the bug, will fix in the next update

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
