### ISSUE TITLE
ThunderClient sets a default `User-Agent` header if one has not been set

### ISSUE THREAD

**Issue by binaek** [rangav/thunder-client-support#430]
**Describe the bug**
ThunderClient sets a default `User-Agent` header if one has not been set

**To Reproduce**
Send any request without the `User-Agent` header set

**Expected behavior**
It should set the headers exactly as given to it and should not set defaults

**Platform:** 
 - OS: Linux
 - vscode version: 1.63.2
 - extension version: v1.9.1

**Solution:**
The header being set is `got (https://github.com/sindresorhus/got)` which is probably the HTTP Request Library that TC uses under the hood. Not sure if this will work, but `got ` documentation mentions that if a header to `undefined`, it will be omitted from the request. Maybe setting it to `undefined` will also prevent it from using the default value in the merge.

**Comment by rangav** [comment]
Hi @binaek 

I think got.js library is setting the default value.

**Comment by binaek** [comment]
Yes @rangav I noticed that

As I mentioned in the Solutions section, maybe setting it to `undefined` will prevent it from setting a default.

**Comment by rangav** [comment]
Hi @binaek  I am closing this issue, feel free to re-open if needed
