### ISSUE TITLE
Feature: Import collection from YAML

### ISSUE THREAD

**Issue by kowalski7cc** [rangav/thunder-client-support#431]
At the moment, OpenAPI YAML files can't be imported as only JSON import is supported.

**Comment by rangav** [comment]
Hi @kowalski7cc thanks for the feedback, will add to roadmap 

alternatively you can import yaml file  to postman and then export to json format, so you can import to Thunder Client

**Comment by rangav** [comment]
I am closing this issue, as it's duplicate of #84
