### ISSUE TITLE
Undeletable item created when dropping a test

### ISSUE THREAD

**Issue by moniuch** [rangav/thunder-client-support#433]
**Describe the bug**

Dragging a test to the list of requests creates a request that is impossible to delete.

**To Reproduce**

1. Drag a test from a request A to the list of requests
2. A new item list gets created
3. Right-click three-dots to remove it. It won't

**Expected behavior**

3. It should.

**Platform:** 
 - OS: Darwin arm64 21.2.0
 - vscode version: 1.63.2
 - extension version: v1.9.1

**Solution:**

**Comment by rangav** [comment]
Thanks @moniuch for reporting the bug.

What you mean by dragging the test?

can you please share screenshots

**Comment by moniuch** [comment]
This relates to #434 UI problem. You are actually able to drag a test, and drop it anywhere. Try doing so, try dropping it on the list of requests.

**Comment by rangav** [comment]
Hi @moniuch I am closing this issue, feel free to re-open if needed
