### ISSUE TITLE
Drag and drop tests to copy/move

### ISSUE THREAD

**Issue by moniuch** [rangav/thunder-client-support#434]
**Is your feature request related to a problem? Please describe.**

I need to quickly copy a test into another request or folder.

**Describe the solution you'd like**

My api naming convention is pretty uniform, therefore a test:

```
json.refresh_token setTo {{REFRESH_TOKEN}}
```

would work for me - it could be freely dropped on other request (say, from `/login`, into `/token`) or onto a folder.
When dropping a test, the UI's pre-drop feedback (a circled plus sign) suggests that the operation is valid.

no modifier - moving (with confirmation prompt?)
option - copying

**Describe alternatives you've considered**

There doesn't seem to be any.

**Implementation:**

**Comment by rangav** [comment]
Drag and drop tests is only for re-ordering  them, they can’t be moved to another request or folder.

**Comment by moniuch** [comment]
In that case the UI is misleading. Pre-drop should signal the area is not a valid target.

**Comment by rangav** [comment]
Hi @moniuch I am closing this issue, feel free to re-open if needed
