### ISSUE TITLE
Unable to select .env file for linking

### ISSUE THREAD

**Issue by moniuch** [rangav/thunder-client-support#435]
**Describe the bug**

Not able to select an .env file in the .env linking dialog

**To Reproduce**

collection settings > link to env file

**Expected behavior**

should be able to select

**Platform:** 
 - OS: Darwin arm64 21.2.0
 - vscode version: 1.63.2
 - extension version: 1.9.1

**Solution:**

From what I know cmd-shift-. should toggle showing the hidden dot files in Open/Save dialogs. I tried that. It wouldn't work for me. Maybe there has to be an alternative way to link.

**Comment by rangav** [comment]
Are you not able to see the env files in open dialog?

**Comment by moniuch** [comment]
omg, now it works when I tried that again. Sorry for the noise. Please close this ticket.

**Comment by dinhanhthi** [comment]
I've encounted the same problem I don't know how to fix it.

**Comment by dinhanhthi** [comment]
Finally, I can see the .env file. Workaround: Click on "Link to .env..." -> popup -> select the folder containing the .env file -> press `cmd + shift + .` -> nothing is shown yet but keep the popup stay open -> click on another folder -> return to the folder containing the .env file -> the hidden file is shown!!!

Note that, every time we click on "Link to...", the popup resets the view setting and we have to do the above steps again.

Hope that it's helpful for others!
