### ISSUE TITLE
publish to open-vsx

### ISSUE THREAD

**Issue by ashwin31** [rangav/thunder-client-support#437]
Hi,
I and most of the app developers using vscode are using this extension. Of course the adoption is growing for thunder-client.
Can you push this extension to open-vsx too so that we can use it in vscode browser workspaces.
please refer https://github.com/eclipse/openvsx/wiki/Publishing-Extensions for more details.

**Comment by rangav** [comment]
Hi @ashwin31 Thanks for feedback, there is an existing issue for this, can you add comments in that.

https://github.com/rangav/thunder-client-support/issues/30

**Comment by ashwin31** [comment]
Thank you @rangav
