### ISSUE TITLE
Unable to install 'rangav.vscode-thunder-client' extension because it is not compatible with the current version of VS Code (version 1.35.1).

### ISSUE THREAD

**Issue by onghcom** [rangav/thunder-client-support#438]
Unable to install 'rangav.vscode-thunder-client' extension because it is not compatible with the current version of VS Code (version 1.35.1).

**Comment by nbonbon** [comment]
Did you end up figuring our what the issue was? Or what the supported versions of VS code are?

**Comment by rangav** [comment]
Minimum vscode version required is `v1.63.0`
