### ISSUE TITLE
Pre Execution action to set value for variables

### ISSUE THREAD

**Issue by mchassy** [rangav/thunder-client-support#442]
**When running an API call multiple times, I want to change some variable values at the request level**
This is useful for testing numerous test cases, but also just for getting things done. I am working on a project where I need to execute certain jobs on a server. There is a web UI with the different jobs, but I prefer using Thunder Client so that I can execute those jobs in VS Code while I am working on the file which are being processed. 
A very simple example is that I may need to upload a file to the server and then run a server job which validates that file, and then another job which generate something and sends it back to me. There could be any number of other jobs all having to do with that original file. And I will need to do that for various iterations of files

**Describe the solution you'd like**
You already have a way of setting a variable, post-execution. You could simply add a pre-execution action.  If I had a set of calls to make, I could do the pre-exectuion action in one test, and then the others would get the right value.

**Describe alternatives you've considered**
Going in the env variable and changing the value.

**Implementation:**
You could use this screen to put a value into a variable, before test execution.
![image](https://user-images.githubusercontent.com/15926092/149191929-75fcfc4f-3218-4dfa-ba4b-83c6bd0c2ec9.png)

**Comment by rangav** [comment]
Hi @mchassy Thanks for feedback, will add to roadmap

**Comment by Laul0** [comment]
Exactly the same case. I have to test several use cases and I need to change an URL part (GUID, Id, etc).
If a can use a variable, that will be easier than changing the URL (quite long in addition to that)

**Comment by rangav** [comment]
Hi @Laul0  we have dynamic variables feature, see if that is useful

https://github.com/rangav/thunder-client-support#variables

**Comment by rangav** [comment]
@Laul0  how your are setting those values currently in the existing tool you are using?

**Comment by mchassy** [comment]
@Laul0 ... look at the first line in the screenshot above. That line retrieves the authorization token from the ressponse of a first call so that it can be used in a second call.

**Comment by Laul0** [comment]
One of my use case is:
`https://domain.ext/api/get('{{myvar}}')/`
I configure the **Tests** tab like this:
0002456789 | setTo | {{myvar}}

The main idea is to change {{myvar}} before the request

The other case is like the @mchassy one

**Comment by mchassy** [comment]
Oh Ok.
@Laul0 you and I are trying to do the same thing, which doesn't currently work.
@rangav said he would put it on his backlog.
What does work for now is getting a value from the responnse and passing it on to another call.

**Comment by rangav** [comment]
Thanks guys for providing your use cases 👍

To use system variables 
e.g in url if you want to use random number, use it as below

`https://domain.ext/api/get/{{#number}}/`

**Comment by rangav** [comment]
Hi Guys, there is an existing issue related to this, so closing this one. you can add any further comments in below issue

#16

**Comment by ajaydwarkani** [comment]
> Thanks guys for providing your use cases 👍
> 
> To use system variables e.g in url if you want to use random number, use it as below
> 
> `https://domain.ext/api/get/{{#number}}/`

@rangav, how can I store this random number (from URL) in a local environment variable so that I can access it from multiple other APIs?

**Comment by rangav** [comment]
Hi @ajaydwarkani 

you can use pre filter to generate random number and save it local env variable and then use that variable in all the requests

**Comment by ajaydwarkani** [comment]
@rangav, this is great. so. basically I can do this using custom filters, right? Some like below

```javascript
function preFilter1() {

    console.log("set env variable example");
    let uuid = uuid4();

    // ---- save to active environment
    tc.setVar("uuidFromScript", uuid);

    // ---- save to local environment
    // tc.setVar("uuidFromScript", uuid, "local");

    // ---- save to global environment
    // tc.setVar("uuidFromScript", uuid, "global");
}

```

**Comment by rangav** [comment]
thats right

you this for local env
 `tc.setVar("uuidFromScript", uuid, "local");`

**Comment by rangav** [comment]
you need to import this at the top - `const { v4: uuid4 } = require("uuid");`

Full script below

```js

const { v4: uuid4 } = require("uuid")

function preFilter1() {

    console.log("set env variable example");
    let uuid = uuid4();

    // ---- save to active environment
    //tc.setVar("uuidFromScript", uuid);

    // ---- save to local environment
     tc.setVar("uuidFromScript", uuid, "local");

    // ---- save to global environment
    //tc.setVar("uuidFromScript", uuid, "global");
}

module.exports = [preFilter1]
````
