### ISSUE TITLE
Auth settings not imported from a previously exported json

### ISSUE THREAD

**Issue by GuidoPreite** [rangav/thunder-client-support#443]
**Describe the bug**
If I import a collection (previously exported from Thunder Client) the Auth settings are not imported

**To Reproduce**
After I insert some values inside the Auth panel of a collection and I export the collection I get the following json:

`{
    "client": "Thunder Client",
    "collectionName": "New Collection",
    "dateExported": "2022-01-13T08:39:06.972Z",
    "version": "1.1",
    "folders": [],
    "requests": [],
    "settings": {
        "headers": [],
        "auth": {
            "type": "oauth2",
            "oauth2": {
                "accessToken": "",
                "grantType": "client_credentials",
                "callbackUrl": "https://www.thunderclient.io/oauth/callback",
                "authUrl": "",
                "tokenUrl": "a",
                "clientId": "b",
                "clientSecret": "c",
                "scope": "d",
                "state": "",
                "username": "",
                "password": "",
                "clientAuth": "in-header"
            }
        },
        "tests": []
    }
}`

but if I import this json the Auth settings are not considered (they default to None)
**Expected behavior**
The saved Auth settings should be imported

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.63.2
 - extension version: 1.9.1

**Comment by rangav** [comment]
Hi @GuidoPreite thanks for reporting the bug, I will verify and get back to you.

**Comment by rangav** [comment]
HI @GuidoPreite the format of the json data is wrong. can you re-export the collection and try again.

**Comment by rangav** [comment]
Please the correct format attached.

[thunder-collection_Sample.txt](https://github.com/rangav/thunder-client-support/files/7871998/thunder-collection_Sample.txt)

**Comment by GuidoPreite** [comment]
@rangav thanks for testing but in your sample the auth settings are at request level, but the issue I am facing happens at collection level, I tested again (I clicked the "Save" button inside Collection Settings after I saved the auth info) and the exported json contains the auth settings but they don't get reimported.

**Comment by rangav** [comment]
Ok got it, thanks @GuidoPreite i can reproduce the bug, will fix in the next update

**Comment by rangav** [comment]
This is fixed now, will be part of next update.

As a temporary fix - create one folder in that collection and then export, then it should work.

**Comment by rangav** [comment]
This is now fixed in v1.10.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.10.0

please let me know if any feedback
