### ISSUE TITLE
Add Code Snippet generation in Thunder Client Plugin (similar to Postman)

### ISSUE THREAD

**Issue by Hollyw00d** [rangav/thunder-client-support#445]
**Is your feature request related to a problem? Please describe.**
It's a feature request.

**Describe the solution you'd like**
In your Thunder Client plugin, can you eventually add a Code Snippet generation feature like Postman has? Here's docs from Postman about what this looks like:
https://learning.postman.com/docs/sending-requests/generate-code-snippets/

Even if it's just generating a JavaScript code snippet only (and not other languages like Postman) that would be helpful.

**Describe alternatives you've considered**
N/A.

**Implementation:**
If you are interested in adding this Code Snippet feature to the Thunder Client plugin (like for JavaScript only) I'd download the Postman desktop app (see "Download the desktop app" text at https://www.postman.com/), try testing some API endpoints, and then follow the steps below to see the generated code (like for JavaScript):
https://learning.postman.com/docs/sending-requests/generate-code-snippets/

Maybe you could do something similar in Thunder Client plugin. And if you are not able to do this I appreciate your plugin anyway. It's working great for me!

**Comment by rangav** [comment]
Hi @Hollyw00d , we already have this feature 

https://github.com/rangav/thunder-client-support#codegen

**Comment by Hollyw00d** [comment]
Thxs @rangav. I see it now. 

Good work! This issue is resolved and can be closed.

**Comment by rangav** [comment]
Hi All, We now added Code Snippet for more languages in `v1.17.0`

<img src="https://github.com/rangav/thunder-client-support/blob/master/images/code-snippet.png?raw=true"  />

See all features released here
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
