### ISSUE TITLE
Possible to have an option to confirm saving URL Requests?

### ISSUE THREAD

**Issue by ZooDoo4U** [rangav/thunder-client-support#446]
First i'd agree this isn't a huge problem, more of a preference, but would like an option to require some confirmation before saving/setting the values for a given URL.    

As-is it seems for any URL within a collection, after editing and submit it (success or failure) the request is now updated,  while (possibly another request would be enabling 'undo') but either case if we had a working URL, submit <error> here i'd be happy to copy the current URL and revert to the saved request...  But neither are an options...  Might be better if the request is successful upon "SEND" then save it?  Safe to assert on a 4xx or 5xx status result, is this anything desired to be saved if the request use to work?  

The easiest solution might be only update the request upon success?  Might assert simply moving your save url after the request and seeing the status code, just a guess, but might be the simplest fix for most of this.  But even then better have an on the individual request to "Save" and possibly a "Save All" at the collection level?   Could think there might be times when issuing good requests, but i'm lazy (okay i'll admit it), but i have any number of end points and mainly work with one, they change by the base URL, and yep I use environments, but if an environment i'm not normally working against...   I might just edit the URL within a collection as needed.   Here it would be night to simply discard any edits.... Revert to my "standard" URL request values...   This might be, before i gave up using postman, this would be the only design where i liked postman over Thunder Client, in that i had the peace of mind no matter what is do, given i'm human and can easily break whatever,  i can simply close and revert back to a known good state where things are working...  Another place where "Did you turn it off and back on" fixes it, just like windoZe ;) 

Not sure if a separate feature request would be appropriate to undo changes on the request,  really helpful working with a new interface where being human as myself making mistakes an undo buffer would be helpful...

**Comment by rangav** [comment]
Hi @ZooDoo4U Thanks for feedback, If you are saving the request files in git, you can always revert the changes you made and go back to the original state

Was it not useful?

**Comment by ZooDoo4U** [comment]
Thanks for your comment @rangav  this would probably work but not really convenient.  Think of the user scenario of create a request edit, undo, oops no undo...  If the request is new using Git to get the request back, hmmm there is nothing .  Or if they are saved in git, it doesn't seem convenient to make an edit, oops failed, revert file, change again fail, revert file, not an ideal work flow?

**Comment by rangav** [comment]
ok got it, Will add to roadmap.

**Comment by Bus42** [comment]
If I understand correctly, I agree. The automatic saving of edits in saved requests has been a bit of a thorn in my side and slows my workflow. When I have a request saved in a collection, I might want to make some arbitrary one-time change to it, but don't want to permanently change the request. I would much prefer that the requests I save in my collection stay exactly as I saved them unless I explicitly save the change to the request.

**Comment by rangav** [comment]
Hi all, it’s in my roadmap to provide vscode setting to disable auto save.

**Comment by ZooDoo4U** [comment]
Thanks for your attention @rangav, sure you'll do great as most everything else i've seen you do in the past.

Cheers!

**Comment by Bus42** [comment]
Awesome! Thanks!

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback

**Comment by ZooDoo4U** [comment]
Still appears to be auto saving the request, no matter what?   If i'm reading this is auto save on submitting/sending the request?  Even worse no "Undo" for the text in the request?  No way to get the request back to what was working.  Appears there is a "SAVE" for the environment, but that should only save the Environment, nothing else?  Postman one could start up, open a collection, edit any of the requests, and simply quit and close without saving anything, nothing is updated, URLs, collection, environment, all three are separate ...  Or one could save 4 or 5 requests edited,  and not save the environment.

Consider this, i work primarily in 2 environments possibly 4 or more  at times. As a tester my collection is set up for my primary environment.  Both the requests, and/or environments may change slightly, or need to check prototype endpoints for ad hoc stuff as needed...  One of my devs ask me to do a quick test for his fixes just stood up.  Will open Thunder Client select my collection and test away, editing requests, simply close VS Code, off to lunch, or come back in a week or more, after all was forgotten what changes were made. Load up my collection and everything for my primary environment is broken.   Was never prompted to save anything...  Thus this request to have an explicitly prompt to save.  Will agree did suggest to possibly save on a valid request response, possibly a bad assumption, could have negative request that should fail, did say i'm a tester..   So really the only safe choice it not to assume saving anything without prompting the user...

Seems the explicit "Save" is implemented only for the Environment, not the individual URL requests within a collection...   Really does seem there should be an option to save each individual "URL Request". within a collection, and a separate "Save Environment".

**Comment by rangav** [comment]
Hi @ZooDoo4U there is new vscode setting that you need to disable `Save Request on Send`

read 2nd point here
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0
