### ISSUE TITLE
Changing environments modifies thunderEnvironment.db

### ISSUE THREAD

**Issue by bdharrington7** [rangav/thunder-client-support#448]
First, thank you for making this extension. As a long time Postman user like yourself, I found the team sharing feature in Postman to be a non-starter and too far removed from the application code. 

As a user that is using the teams feature and saving the `thunderEnvironment.db` file to source control, switching environments causes a confusing change where the `default` key in the environment object is set to `true` and the timestamp is updated. In the UI, the context menu has an option for 'Set active' on the unstarred environment, which seems like it shouldn't update which environment is `default`. Switching back still leaves a pending change in version control since the timestamp is updated. 

**Describe the solution you'd like**
Having a `default` option setting for an environment is a good thing (I think a new developer opening the project should default to using the dev environment, not what the last developer was using). Switching shouldn't update the database though. During a testing session, I may want to switch to a QA or prod environment, but I'd never want to set QA or prod as the "default".

**Describe alternatives you've considered**
I thought about removing the thunderEnvironment.db file from source control, but that removes my ability to transfer common environment variables to the team, which are used in the collections. 

**Implementation:**
N/A: Library isn't open source.

**Comment by rangav** [comment]
Hi @bdharrington7 

Thanks for feedback, I will remove modifying the date when `Set Active` is selected, so switching env will not change git. 

In terms of default Environment, I think its better to leave it developer or user to decide which Env is default, rather than extension to decide.

also names of environments can be named differently by different users.

We also have Local Environment feature, which will exclude secrets from source control.

**Comment by bdharrington7** [comment]
> its better to leave it developer or user to decide which Env is default, rather than extension to decide.

I completely agree! But my only issue with that is that the menu option to change the default is named “Set Active”. Could it be renamed to “Set as default” or something, and then have another option that switches the environment, but saves that state in memory instead of changing the database?

**Comment by rangav** [comment]
In the first version we had `Set Default` as the name, lot of people said it’s confusing and requested to change name to `Set Active`, so we changed it.

Once you use it couple of times, you will get used to the name.

In-Memory change:
Will think of this request and research if there is better way

**Comment by bdharrington7** [comment]
6+, and many team members have multiple machines so that could work out to at least double

**Comment by rangav** [comment]
This feature is now implemented in v1.11.0, it will not modify the date when you change Env
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

please let me know if any feedback

**Comment by bdharrington7** [comment]
Working beautifully, thanks!

**Comment by rangav** [comment]
Thanks @bdharrington7 for confirmation  👍

**Comment by mattiasd** [comment]
First, love the extension, thank you!

Seems related so continuing here. Set Active is still changing thunderEnvironment.db by setting default. Is that by design? I switch environment often and I don't want to remember to reset active environment before committing.

**Comment by rangav** [comment]
Hi @mattiasd, Glad you like it.

Yes its by design, when you change the active env it will update the file. 

But if change the active env back to original, then no changes will be seen in thunderEnvironment.db file.

**Comment by rangav** [comment]
Hi All, Update on changing env.

Now you can use CLI to run collection or request with different env, this wont change the current active env.

**Install:**
- `npm i -g @thunderclient/cli`

**Examples**
- `tc 'requestNameOrId' --env 'Staging'` to run request using staging environment
- `tc --col 'colNameOrId' --env 'Staging'` to run collection using staging environment


**Documentation:**
- `tc --help`
- https://rangav.medium.com/d91eb5c71d8e

Please let me know your feedback

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.18.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.18.0

Please test and let me know your feedback.
