### ISSUE TITLE
Can't redirect with multipart/form-data

### ISSUE THREAD

**Issue by RodrigoSosa96** [rangav/thunder-client-support#449]
**Describe the bug**
If you try to send a `multipart/form-data` and then redirect, it will never show the result, it just keeps waiting a response.

I test it with `urlencoded` form and it works, the bug only triggers with `multipart/form-data`, with or without a file attached to it

**To Reproduce**
Here is a simple example on how to trigger the bug:
```javascript
    app.listen(8080, () => {
        console.log('listening on port 8080');
    });
    app.use(express.json())
    app.use(express.urlencoded({ extended: true }))
    const upload = multer({ storage: multer.memoryStorage() });

    app.post('/form', upload.none(), (req, res) => {
        console.log(req.body)
        /**
         *  [Object: null prototype] {
                email: 'some@email.com',
                ocupation: 'some ocupation',
            }
        */
        res.redirect('/destiny')
    })


    app.get("/destiny", upload.none(), (req, res) => {
        res.status(200).send("Thunder can't see this")
    })
```
**Expected behavior**
I should see *Thunder can't see this* but the extension just keeps waiting it

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.63.2
 - extension version: 1.10.0

**Comment by rangav** [comment]
Hi @RodrigoSosa96 thanks for reporting the bug, I will look into it.

**Comment by rangav** [comment]
I have released a new update, Let me know if you still have this issue.
https://github.com/rangav/thunder-client-support/releases/tag/v1.11.0

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
