### ISSUE TITLE
New action editor shortcut overrides a basic VS Code key binding

### ISSUE THREAD

**Issue by ihouwat** [rangav/thunder-client-support#451]
**User experience issue**
The latest update adds a key binding of Ctrl+Shift+t to access Thunder Client in the action bar. Unfortunately, this overrides a pretty basic VS Code shortcut to reopen a previously closed editor - which incidentally is the same shortcut implemented in Chrome, Edge, Firefox browsers as well.

**Solution I'd like**
The shortcut for action bar is a great idea, but can we have a shortcut that doesn't clash with such a basic and simple native one. Sure, I can override, but I don't want to have to do it. 

Alternative?
Maybe ctrl+k ctrl+shift+t, since it doesn't clash with workbench, but I don't know how that impacts other extensions.

**Comment by rangav** [comment]
Thanks @ihouwat for the feedback, will review if there is a better shortcut keys.

**Comment by rangav** [comment]
what about `ctrl+shift+R` short key? its not used in vscode shortcuts list

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by ihouwat** [comment]
> what about `ctrl+shift+R` shortcut key? its not used in vscode shortcuts list
> 
> https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

I see it in a couple of places in the keybindings - I can't find the file, but I search for "Open Default Keyboard Shortcuts (JSON)" in the Command Palette inside of VS Code. For some reason, I can't paste a screenshot...

**Comment by rangav** [comment]
Yeah two key press action is complicated, most people will ignore.

and also the other windows in sidebar start with `ct+sh+someKey` shortcut keys, so it's better to follow same pattern

**Comment by ihouwat** [comment]
> Yeah two key press action is complicated, most people will ignore.
> 
> and also the other windows in sidebar start with `ct+sh+someKey` shortcut keys, so it's better to follow same pattern

Got it. I guess, I'd be thrilled with the new one you suggested, but someone else might complain 😂

**Comment by rangav** [comment]
This bug is now fixed in v1.11.1, Just now published new quick release.

The new shortcut is `ctrl+shift+R`

please let me know if any feedback

**Comment by ihouwat** [comment]
Thanks for the quick response!

**Comment by iqfareez** [comment]
Hi. The new shortcut `ctrl+shift+R` overrides the refactor shortcut (or the yellow bulb things). 

Is there any way to change the keybinds to something else? Thx!

**Comment by rangav** [comment]
Hi @iqfareez, open keyboard shortcuts from command pallete and you can modify the keys

**Comment by iqfareez** [comment]
@rangav, problem solved. Thanks!!
