### ISSUE TITLE
Incorrectly shows response as binary in v1.11.0

### ISSUE THREAD

**Issue by alwinzwets** [rangav/thunder-client-support#452]
**Describe the bug**
An API call returning valid UTF-8 XML with header `application/vnd.vizrt.payload+xml; charset=utf-8` is marked as binary. Application only gives the option to save the response as a file download. Version v1.10.0 did not have this problem. 

**To Reproduce**
Make a call to an endpoint returning XML with `application/vnd.vizrt.payload+xml; charset=utf-8` as Content-type header.

**Expected behavior**
Show UTF-8 XML-response.

**Platform:** 
 - OS: Windows
 - vscode version: 1.63.2
 - extension version: 1.11.0

**Solution:**
Properly handle charset and/or `+xml` in Content-type headers or give the option to always show result inline, even when classified as binary.

**Comment by rangav** [comment]
Thanks @alwinzwets for reporting the bug will asap.

**Comment by rangav** [comment]
This bug is now fixed in v1.11.1

please let me know if any feedback

**Comment by marcelogp** [comment]
@rangav I'm having the same problem. My HTTP response is `content-type: Multipart/Related (...)`

**Comment by rangav** [comment]
Hi @marcelogp thanks for reporting 

can you share full content type, I will look into the issue

**Comment by marcelogp** [comment]
It includes random IDs, like this one: `Multipart/Related; boundary=3b0ec11232ab10e54d98ee58d7d960255e6ade63`

**Comment by rangav** [comment]
This bug is now fixed in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
