### ISSUE TITLE
Wsl Body FIle choose file bug 

### ISSUE THREAD

**Issue by hirupamganguly** [rangav/thunder-client-support#453]
**Describe the bug**
Wsl Body FIle choose file bug 

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by rangav** [comment]
Hi @hirupamganguly 

Please read this comment for solution 
https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.

**Comment by AliSentice2022** [comment]
Just Tested on WIN 10 Home and it works ✔

Good Job man
