### ISSUE TITLE
Link requests to multiple collections

### ISSUE THREAD

**Issue by Ziuan** [rangav/thunder-client-support#454]
**Is your feature request related to a problem? Please describe.**
Not a problem, rather an improvement

**Describe the solution you'd like**
The ability to share requests between multiple containers (collections and folders) without copying the requests

Example:
Collection 1: Auth -> Get token
Collection 2: Get-Data -> Get Data
Collection 3: Flows -> Get token, then Get Data (those 2 requests are linked or shared from Collection 1 and 2)

This would give the user the option to "Run all" in a specific folder/collection and still maintain only 1 copy of each request

**Describe alternatives you've considered**
Testfully supports multi-step testing but is not a VS Code extension - Thunder Client is great and we want to keep using that

**Implementation:**
Define requests in thunderclient.db, but don't link them to any specific container.
In thunderCollection.db, define an array of "members" for each collection, using the already existing _id from thunderclient.db

Thanks for a great extension!

**Comment by rangav** [comment]
Hi @Ziuan we already have this in roadmap, and also there is similar request already created #249

I am closing this you can add comments there.

**Comment by rangav** [comment]
please let me know your feedback on this https://github.com/rangav/thunder-client-support/issues/249#issuecomment-1061853717

**Comment by Ziuan** [comment]
Hi, the image you posted in https://github.com/rangav/thunder-client-support/issues/249#issuecomment-1061853717 looks good! Questions:

1. Can you have more than one Pre-request for a request?
2. Will the Pre-request also execute its own Pre-request?

We especially like the "When env variable is empty". Overall, nice addition!

**Comment by rangav** [comment]
@Ziuan thanks for feedback 

2. Yes pre-request can also run it’s pre-prequest, that way you can multiple requests

the above interface provides a way link only one request

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.
