### ISSUE TITLE
Unable to find extension in VS Codium 

### ISSUE THREAD

**Issue by Vignesh-Ganesan-008** [rangav/thunder-client-support#455]
I'm using VS Codium (latest release)and I'm unable to find this extension. Is it not supported or am I doing something wrong?

![image](https://user-images.githubusercontent.com/58505455/151932143-7160b99a-414d-443d-ba6f-c4d497d67f8c.png)

**Comment by rangav** [comment]
Hi @Vignesh-Ganesan-008 

it’s not published yet, you need to install manually for now, see this comment https://github.com/rangav/thunder-client-support/issues/30#issuecomment-827205300

**Comment by rangav** [comment]
There is already issue for this, so I am closing this issue.

**Comment by Vignesh-Ganesan-008** [comment]
Thanks

**Comment by rangav** [comment]
Hi @Vignesh-Ganesan-008 

finally managed to publish to open-vsx
https://open-vsx.org/extension/rangav/vscode-thunder-client
