### ISSUE TITLE
Substitution of env variable placeholder with query parameter

### ISSUE THREAD

**Issue by jorgelaranjo** [rangav/thunder-client-support#456]
Scenario:
Environment is linked to environment file.
Environment file contains:
```
base_url=https://apiurl.com/api/v1
endpoint={{base_url}}/resource/{id}/result
```

`{id}` should be substituted by a query parameter, for testing purposes.

Is this currently possible or is there another way to achieve the same goal?

**Comment by rangav** [comment]
Hi @jorgelaranjo currently not possible. 

but if you use url field value as `{{base_url}}/resource/{id}/result` then {id} will be path variable then you can change it easily

**Comment by rangav** [comment]
Currently no plans, as no one has asked that till now.

**Comment by jorgelaranjo** [comment]
> Hi @jorgelaranjo currently not possible.
> 
> but if you use Request Url field value as `{{base_url}}/resource/{id}/result` then {id} will be path variable then you can change it easily

That's nice but if `Request URL` changes the whole variable is deleted (value)

**Comment by jorgelaranjo** [comment]
Closing as original issue answered
