### ISSUE TITLE
Add Path Parameters

### ISSUE THREAD

**Issue by jleemur** [rangav/thunder-client-support#459]
**Describe the solution you'd like**
<img width="710" alt="Screen Shot 2022-02-03 at 2 46 15 PM" src="https://user-images.githubusercontent.com/15106385/152408626-dbad7265-e174-4cef-a3c4-05fc6759df99.png">

Add a "Path Parameter" section, to define `id`'s such as `customerId` in this example

Example: `{{API_URL}}/{{API_INGRESS}}/customer/:customerId`

**Path Parameters**
parameter: customerId
value: 1

**Comment by rangav** [comment]
Hi @jleemur 

for path variables use format `{customerId}`

**Comment by jleemur** [comment]
Great, thanks

**Comment by jleemur** [comment]
It might save you some questions if it gets added to the README

**Comment by rangav** [comment]
Sure will add 👍

**Comment by rangav** [comment]
Updated the documentation for path variables
https://github.com/rangav/thunder-client-support#path

Let me know if any feedback

**Comment by rangav** [comment]
Hi @lekhnath glad you like it 🙂

thanks for feedback, will add to roadmap.

currently highlighting not possible
