### ISSUE TITLE
Set Env Variable in Tests only works on last instance v1.0.7

### ISSUE THREAD

**Issue by tvalladon** [rangav/thunder-client-support#46]
**Describe the bug**

In the Tests for a request only the last `Set Env Variable` is being set, any `Set Env Variable` prior to the final one are left as their prior value or blank.
**To Reproduce**

Make a call and attempt to assign 2 Env Variables using the test system, only one will be set. 
**Expected behavior**

Any Tests that preform a `Set Env Variable` will set those Env Variables.
**Platform:** 
 - OS: Windows10, WSL2 with Ubuntu 20.04 container
**Notes:**
I can also do testing on Linux (Ubuntu, Pop-os!), Windows 10 without WSL2 and Macos if needed.

**Solution:**

![log_id is set but log_user is not](https://user-images.githubusercontent.com/50340/115983149-637e7580-a554-11eb-9f76-49995ca5d0cb.PNG)
![log_id set](https://user-images.githubusercontent.com/50340/115983156-65e0cf80-a554-11eb-8819-465f1627f232.PNG)
![log_user is set but log_id is not](https://user-images.githubusercontent.com/50340/115983161-69745680-a554-11eb-9899-6ad3b4d4a9c0.PNG)
![log_user set](https://user-images.githubusercontent.com/50340/115983165-6bd6b080-a554-11eb-8ff6-d21d387332a8.PNG)

**Comment by rangav** [comment]
Hi @tvalladon i will test and fix it. Thanks for reporting the issue.

**Comment by rangav** [comment]
Hi @tvalladon this is now fixed, will be part of next update v1.1.0, more details here - #14

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14
