### ISSUE TITLE
Only 1 body persists

### ISSUE THREAD

**Issue by jleemur** [rangav/thunder-client-support#460]
**Describe the bug**
If I have a form-encode body and send a json body, after I exit vscode form-encode is empty

**To Reproduce**
If I have a form-encode body and send a json body, after I exit vscode form-encode is empty

**Expected behavior**
form-encode is not deleted when I reopen vscode. Is it possible to default to last opened body tab?

**Platform:** 
 - OS: macOS Monterey 12.1
 - vscode version: 1.63.2
 - extension version: 1.11.1

**Comment by rangav** [comment]
Hi @jleemur only active tab values will be saved others will be ignored.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
