### ISSUE TITLE
Allow Script Testing

### ISSUE THREAD

**Issue by pdgomes89** [rangav/thunder-client-support#465]
**Is your feature request related to a problem? Please describe.**
For complex validations Scriptless Testing is not enough as it requires long time to configure. Having also the option to create testing based on scripting would make the best of the two worlds available. 

**Describe the solution you'd like**
Allow scripts creating for testing. 

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @pdgomes89 Thanks for feedback. 

duplicate issue already exists for this https://github.com/rangav/thunder-client-support/issues/278, you can add comments there.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please let me know your feedback

**Comment by rangav** [comment]
Hi @pdgomes89 Now Tests via scripting is possible with v2.10.0

https://github.com/rangav/thunder-client-support/releases/tag/v2.10.0
