### ISSUE TITLE
Add Setting to Not Save API Calls from Collection on Change

### ISSUE THREAD

**Issue by jandreaucodes** [rangav/thunder-client-support#468]
**Is your feature request related to a problem? Please describe.**
When editing an API call from a saved collection, the API call is saved upon close, which overwrites the data in the collection.

**Describe the solution you'd like**
Add a setting to disable this behavior. I want to keep the original, unedited, call from the API collection.

**Comment by rangav** [comment]
Hi @jandreaucodes thanks for feedback, this is already planned for next update, you will have a setting not to save request to sending api call, it will save only when explicitly called with Ctrl + S 

There is already existing issue for this here #446, So I am closing this.
You can add any further comments there.

**Comment by rangav** [comment]
This feature is now implemented in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
