### ISSUE TITLE
An error occurred while loading view: thunder-client-sidebar

### ISSUE THREAD

**Issue by ozgurdemir** [rangav/thunder-client-support#469]
**Describe the bug**

The sidebar shows this message "An error occurred while loading view: thunder-client-sidebar"

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: OSX 12.2.1
 - vscode version: 1.64.2
 - extension version: v1.12.0

**Solution:**

Tried to disable, enable, uninstall, install with vscode restarts which did not solve the problem.

**Comment by rangav** [comment]
Try installing previous version of vscode or thunder client

**Comment by rangav** [comment]
Hi @ozgurdemir Please follow the steps here and let me know if it works or not
https://github.com/rangav/thunder-client-support/issues/349#issuecomment-962253811

**Comment by ozgurdemir** [comment]
I tried this already and it didn't work.

**Comment by rangav** [comment]
Do you have lot of requests or few?

Just checking to see amount of data is causing the initialization problem

**Comment by rangav** [comment]
if you have time, please try below

Open **vscode settings**, then search Thunder Client. then enable the below setting

![Screenshot 2022-02-18 at 16 03 55](https://user-images.githubusercontent.com/8637550/154718476-45788b2c-ac74-4adc-b714-f40debe3005c.png)

Then open any folder in vscode and click Thunder Client Icon on the sidebar.

Let me know if this works.

**Comment by ozgurdemir** [comment]
Thx @rangav this did fix the error.

**Comment by rangav** [comment]
Thanks for confirmation. I think db files could be corrupted which are in default location.

You can delete all the files in default location, if they are not `important`

The default location path
/Users/`{{userName}}`/Library/Application Support/Code/User/globalStorage/rangav.vscode-thunder-client/

**Comment by ozgurdemir** [comment]
Yes after deleting the default location path it works again with the default thunder settings. Thx a lot for your quick help.
