### ISSUE TITLE
Depends on

### ISSUE THREAD

**Issue by oaltun** [rangav/thunder-client-support#474]
Problem:

 When you want to run a request, sometimes you need another request to be already runned. E.g. to run "update the post" request, you need to run "login user1".

It is cumbersome to find the request to login that user if you have a lot of requests.

Solution:

"Depends on". A request should be able to depend on another request. The depended request should be automatically runned.

E.g. when I run "update the post" request, "login user1" request must be automatically run.

**Comment by rangav** [comment]
Hi @oaltun  thanks for feedback, we already have this in roadmap, and also there is similar request already exists https://github.com/rangav/thunder-client-support/issues/249

I am closing this, you can add comments there.

**Comment by rangav** [comment]
Alternatively for now, you can use folder to group requests in collection and run them in sequence

**Comment by rangav** [comment]
please let me know your feedback on this https://github.com/rangav/thunder-client-support/issues/249#issuecomment-1061853717

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.
