### ISSUE TITLE
Headers of the same name are overridden

### ISSUE THREAD

**Issue by lewiuberg** [rangav/thunder-client-support#475]
**Describe the bug**

Headers of the same name are overridden.

**To Reproduce**

Make several headers with the same name.
See the rightmost (ThunderClient) side of the picture in the next section.

**Expected behavior**

See the leftmost (Postman) side of the picture below.

![Skjermbilde 2022-02-20 kl  20 55 51](https://user-images.githubusercontent.com/43423020/154861849-669eb214-9b1b-4ac3-bf2c-2e1d49fb38a0.png)

**Platform:** 
 - OS: macOS
 - vscode version: 1.64.1
 - extension version: 1.12.1

**Solution:**

**Comment by rangav** [comment]
Thanks @lewiuberg for reporting the bug, will look into it.

one question for clarification:
Why would you send 2 headers with same, what is your use case?

**Comment by lewiuberg** [comment]
Thanks, @rangav!

To be honest, I am following a Udemy course learning about FastAPI, and the instructor shows that Swagger has this behavior as well, so he instructs us to use postman. The importance of this has to be evaluated by someone more experienced than me 😃

**Comment by rangav** [comment]
@lewiuberg  thanks got it, understood 

I will look into it.

**Comment by rangav** [comment]
This feature is now fixed in v1.12.2

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.2
