### ISSUE TITLE
Extend system variables

### ISSUE THREAD

**Issue by diosby** [rangav/thunder-client-support#476]
**Is your feature request related to a problem? Please describe.**
I do a lot of requests with different data to test some endpoints, fill a database and so on.

Now there are several system variables in the extension. They are useful, but they are a few to make all values. 

Unfortunately, it is not possible to see all possible options for values. So I'm asking If it is possible to make own generators via JS/TS with arguments.

```
{{#myOwnCallback, its, arguments, true, 'string, 50.5}}
```

Could you please also add the following system variables:
- `{{#bool}}` - returns true or false
- `{{#enum, 'val1', 'val2', ...}}` - returns one of specified values

If it is possible add generation preview of these data and add possibility to regenerate these data/values.

![Screenshot from 2022-02-22 14-32-13](https://user-images.githubusercontent.com/19969187/155124380-88e813d7-b2fc-4ec6-8a8f-7bf8c0b60691.png)

Thank you!

**Comment by rangav** [comment]
Hi @diosby, Thanks for feedback.

Custom generators will be used part of pre-request scripting which is in roadmap.

I will add the additional system variables `bool` and `enum` to roadmap.

**Comment by rangav** [comment]
Just a suggestion for testing purpose. If doesn’t suit your use case, you can ignore it.

Preview will also show different values as System variables will always generate new values when you access them each time.

**Comment by rangav** [comment]
@diosby for enum the format will be `{{#enum, val1, val2, ...}}` comma separated values **without** single quotes, will be easy to type

**Comment by rangav** [comment]
This feature is now implemented v1.12.2

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.2

see updated docs here
https://github.com/rangav/thunder-client-support#variables
