### ISSUE TITLE
Set json part to variable and use it in the next request

### ISSUE THREAD

**Issue by Rebkas68** [rangav/thunder-client-support#477]
Hi Rangav

Thanks for this great VS Extension!
I asked myself if this is not possible, or I make a mistake: I tried to save a json part of a response in a variable (to use it in the following request body), but the content is just [object Object].
The test is
![image](https://user-images.githubusercontent.com/79982097/155286872-a3722fa1-5a49-4472-a469-56d8992ddab5.png)
Value of ResponseData after the request:
![image](https://user-images.githubusercontent.com/79982097/155287995-ee400c00-6551-4501-85c2-381c3087392b.png)

The start of the response body (source) is the following:
{
  "Warnings": [],
  "Errors": [],
  "Infos": [],
  "Data": [
    {
      "TemplateId": "f80448b2-6166-4ac6-9112-d08dba15ee40",
      "Subreports": {
        "ReportHeader": {
          "TemplateId": "54403807-4291-4832-b249-7a9036443c94",
          "Sets": {
            "Data": {
              "CompanyAddress": [
                {
                  "Name": "Glenn D Vandorn",
                  "Street": "Red Hawk Road",
                  "StreetNumber": "782",
:

As written above, the value of ResponseData is [object Object]. It should be the Data part:
{
      "TemplateId": "f80448b2-6166-4ac6-9112-d08dba15ee40",
      "Subreports": {
        "ReportHeader": {
          "TemplateId": "54403807-4291-4832-b249-7a9036443c94",
          "Sets": {
            "Data": {
              "CompanyAddress": [
                {
                  "Name": "Glenn D Vandorn",
                  "Street": "Red Hawk Road",
                  "StreetNumber": "782",
:

Can my requirement be met with Thunder Client? How?

Best Regards
Dieter (Rebkas)

**Comment by rangav** [comment]
Hi @Rebkas68, currently not possible to set json to a env variable. 

Will enable in the next update

**Comment by Rebkas68** [comment]
The REST API first prepares the data for a report (see above). The report is then retrieved with sending this data.

**Comment by rangav** [comment]
got it thanks 👍

**Comment by rangav** [comment]
This feature is now implemented v1.12.2

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.2
