### ISSUE TITLE
Reload Data being added to every view

### ISSUE THREAD

**Issue by worksofliam** [rangav/thunder-client-support#478]
Hi

When I have the Thunder Client extension enabled, it is adding a 'Reload Data' button using the 'refresh' icon to every view context, **even outside of Thunder Client's extension**.

Thunder Client disabled. No 'Reload Data':

![image](https://user-images.githubusercontent.com/3708366/155343536-21060177-0d40-4770-a0b4-1e1ef2d2d84e.png)

Thunder Client enabled: 'Reload Data' button appears in every other view:

![image](https://user-images.githubusercontent.com/3708366/155343650-35efc76b-d763-4881-9b81-b2646f256a0a.png)

**Comment by rangav** [comment]
Hi @worksofliam thanks for reporting the bug, Will fix it in the next update.

**Comment by rangav** [comment]
This bug is now fixed in v1.12.2

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.2
