### ISSUE TITLE
Cant't copy any Text from a json response into the Windows clipboard

### ISSUE THREAD

**Issue by tpoth** [rangav/thunder-client-support#479]
**Describe the bug**
After requesting a rest api which responds with a json format I was not able to copy some of the code from the Response Tab into my clipboard

**To Reproduce**
call any REST API Endpoint with GET that responds with an Application/JSON Format.
Select any text part in the Response Tab
copy the text to the clipboard (ctrl+c or context menu)
try to pull out the copied text passage into notepad only pulls out the former copied text if there was any.

**Expected behavior**
I would expect the copied text to be in the clipboard availabe to paste it into any application.

**Platform:** 
 - OS: Windows 10 Pro / Version 21H2 / osbuild 19044.1526 / 
 - vscode version: 1.64.2
 - extension version: v1.12.1

**Solution:**
Until now, type be hand.

**Comment by rangav** [comment]
Hi @tpoth the copy and paste functionality are provided by vscode. so this could be vscode bug

Please see similar issue here
https://github.com/rangav/thunder-client-support/issues/439#issuecomment-1032633209

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
