### ISSUE TITLE
Doesn't work on the M1 MacBook Pro 13

### ISSUE THREAD

**Issue by slayerjain** [rangav/thunder-client-support#48]
**Describe the bug**
The New request tab is blank

**To Reproduce**
- Install the extension
- Add a collection
- Create new request
**Expected behavior**
See options on the request screen

**Platform:** 
 - OS: MacOS Big Sur, ARM.

<img width="1446" alt="Screenshot 2021-04-25 at 4 31 33 PM" src="https://user-images.githubusercontent.com/12831254/115991043-12b65d80-a5e4-11eb-98a4-478f3e9465bf.png">
<img width="1450" alt="Screenshot 2021-04-25 at 4 31 27 PM" src="https://user-images.githubusercontent.com/12831254/115991045-14802100-a5e4-11eb-8fb5-a4eafde188bb.png">

**Solution:**

**Comment by rangav** [comment]
Hi @slayerjain try restarting the vs code?

**Comment by slayerjain** [comment]
@rangav Tried that, didn't work

**Comment by rangav** [comment]
May be Try uninstalling and re-install the extension

**Comment by slayerjain** [comment]
Just tried that too, didn't work..

**Comment by slayerjain** [comment]
I just restarted my computer, and it worked for the first time, but now its blank if I try again

**Comment by rangav** [comment]
I don’t m1 MacBook, but I see if there is any specific issue with it, I will get back to you on this. 

Try open another new request window

**Comment by slayerjain** [comment]
Thanks. I've tried multiple request tabs - I mostly see blanks.

**Comment by rangav** [comment]
HI @slayerjain when you open new request window, from command palette - can you open `Open Webview Developer Tools` and see if there is any errors in console tab?

**Comment by slayerjain** [comment]
@rangav I don't see anything here too. 

<img width="1459" alt="Screenshot 2021-04-26 at 1 05 23 PM" src="https://user-images.githubusercontent.com/12831254/116045875-1c959a80-a690-11eb-9778-a05c71837aab.png">

**Comment by rangav** [comment]
That is strange, may be i should rent a M1 mackbook soon to fix this issue.

**Comment by rangav** [comment]
one more place to check - is there any messages in Terminal or Debug Console?

**Comment by fbondia** [comment]
Same problem here, Mac Air M1... the first time I`ve used the New Request feature were ok.

Tried to uninstall, restart, open other tabs, change version, even tried to delete all $HOME/Library/Application Support/Code/User/globalStorage contents, but no success.

**Comment by wbso** [comment]
Same problem here Mac Pro M1 on VSCode stable Version: 1.55.2. 
But no issues on Version: 1.56.0-insider.

**Comment by rangav** [comment]
Hi @wbso thanks for pointing to solution, could be VS code support issue. @slayerjain and @fbondia  is it possible for you to test with v1.56.0-insider

**Comment by fbondia** [comment]
Thanks @wbso. @rangav it is working correctly with insiders!

**Comment by slayerjain** [comment]
@rangav thanks, working for me too

**Comment by rangav** [comment]
Hi @slayerjain and @fbondia thanks for confirmation.

**Comment by foneazmi** [comment]
get this error on version 1.58, macbook pro m1

**Comment by rangav** [comment]
Hi @foneazmi, looks like there is some issue in vscode 0.58.0 version, please download to earlier version.

you can see comments in this thread.
https://github.com/rangav/thunder-client-support/issues/257

**Comment by foneazmi** [comment]
work perfectly without downgrade vscode on thunder client v1.7.0
