### ISSUE TITLE
express cookie-parser http-only attribute set true blocks cookie

### ISSUE THREAD

**Issue by Andromeda7177** [rangav/thunder-client-support#482]
**Describe the bug**
issue: when cookie-parser attribute httpOnly set to true does not allow cookie data pass.  The client browser outside thunder-client allows the cookies to pass. instead empty data [Object: null prototype] {}

**To Reproduce**
set httpOnly: true.  
perform query

app.use(cookies-parser()) is placed before the routes

**Expected behavior**
expect the thunder-client to allow cookies data pass.

**Platform:** 
 - OS: macOS 10.16
 - vscode version: 1.64.2
 - extension version: v1.12.2

**Solution:**
temp work around to set attribute httpOnly: false.   when false the thunder-client works as expected

**Comment by rangav** [comment]
Hi @Andromeda7177 thanks for reporting the bug

**Comment by rangav** [comment]
Hi @Andromeda7177 what is the url, you used in both cases?

**Comment by rangav** [comment]
Try this solution https://github.com/rangav/thunder-client-support/issues/872#issuecomment-1492728459

I am closing this issue as it's not related to TC, Feel free to reopen if needed
