### ISSUE TITLE
When cookie name contains . then the extension throws error 

### ISSUE THREAD

**Issue by jmagnetti** [rangav/thunder-client-support#483]
**Describe the bug**
When calling a particular API (private authorised oauth2) I get a 200 response, but the data area is empty. Extension details screen shows this error: "Uncaught error found in extension: Field names cannot contain a ."   If I generate powershell script from TC for this call it works fine. Also works fine in Postman. 

**To Reproduce**
1) Call this particular API. Get 200 response but no data.
2) Check extension details - see a new uncaught exception: Field names cannot contain a .
2) Generate Powershell script
3) Run Powershell script, get 200 response and lots of data.

**Expected behavior**
The data should be returned & displayed in TC

**Platform:** 
 - OS:  Windows 11
 - vscode version: 1.64.2
 - extension version: 1.12.2

**Solution:**

**Comment by rangav** [comment]
Hi @jmagnetti thanks for reporting the issue. 

are you using the token generated in Oauth2 tab for authentication?

**Comment by jmagnetti** [comment]
I have an environment setup with variables for oauth2, then going to
collection settings to generate the token, then inheriting from the request.

**Comment by rangav** [comment]
thanks, let me check if i got it right

1. you used **collection Settings** to generate oauth token
2. Then you saved you saved the token in env and used env variable in oauth2 tab token field
3. Then the requests in collection, are inheriting the auth details 
4. When executing the request the it is failing right?

**Can you test the request by using the auth tab in request view, without the collection Settings? to see if there is bug in collection Settings.**

also can you share the error message if possible with hiding any sensitive info.

**Comment by jmagnetti** [comment]
Hi,
1) correct, collection settings to generate oauth token - message comes up
saved
2) no I did not go to env, this step is not part of the flow
3) yes the request is in a collection, and set to inherit the auth details
4) the request is successful (200 response) but there is no data returned.
The same request when run from the generated powershell script also runs
with a 200 response but does return data. An error is displayed in the
extension runtime status screen: "Field names cannot contain a ."

The same result happens when I use the auth settings in the request to
generate the token there. Also note that another request with the same
configuration as the one that fails that calls another api on the same
endpoint succeeds. I have checked the json returned from the powershell
script and it does not contain a field called "names".

I hope this helps. I am open to recording a screencam or some such to show
you if this is not clear. I would just ask to send it to you privately.

Thanks,

Joel.

**Comment by rangav** [comment]
@jmagnetti thanks for reply. 

could be issue with response data, recently I fixed this bug https://github.com/rangav/thunder-client-support/issues/88 with different JSON library for display.

is it possible to share the response data you got from powershell, **remove any sensitive info.**

**Comment by jmagnetti** [comment]
@rangav I am ok to email you the data directly, but I am not comfortable posting publicly due to the nature of the contents. Can I please send to an email address?
Thanks.

**Comment by jmagnetti** [comment]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/815527/156100577-7e974bd3-3873-4722-b7f5-76659271e88c.png">
Could the issue be the ips.username cookie?

**Comment by rangav** [comment]
My email `ranga.vadhineni@thunderclient.com`

Please remove any sensitive info from data

**Comment by jmagnetti** [comment]
Hey mate, I think it has more to do with the cookie having a "." in it than
the json payload. What do you think?

Thanks,

Joel.

**Comment by rangav** [comment]
Don't know about the cookie issue, let me verify and get back to you

**Comment by rangav** [comment]
You said another request to different api is working, what is the difference in response properties or cookies?

**Comment by jmagnetti** [comment]
The working response does not have the cookie with the period in it. That's
the major difference I see.

**Comment by rangav** [comment]
Yes i can notice the same error where there is . in cookie name, but the response was still displayed.

https://www.thunderclient.com/t/cookie

![Screenshot 2022-03-01 at 06 24 58](https://user-images.githubusercontent.com/8637550/156117245-7993fb38-075c-45c2-a185-7f9f9b962cc1.png)

**Comment by jmagnetti** [comment]
Interesting, yes I have just replicated this too. I'll email you the
response json now.

**Comment by rangav** [comment]
the response also seems to work fine

Is it possible for you to remove the cookie `ips.username` and test the response on your side?

**Comment by jmagnetti** [comment]
Unfortunately I don't control the API so not sure I can do that just in the
client?

**Comment by rangav** [comment]
ok let me fix the issue `Field names cannot contain a .`  and then you can test again.

**Comment by rangav** [comment]
if header name has . also throws error.

**Comment by rangav** [comment]
@jmagnetti i have fix the error, would like to test?

I can upload the pre-released vsix file, let me know

**Comment by jmagnetti** [comment]
That'd be great, just let me know how :)

**Comment by rangav** [comment]
[vscode-thunder-client-1.12.3.vsix.zip](https://github.com/rangav/thunder-client-support/files/8161137/vscode-thunder-client-1.12.3.vsix.zip)

un-zip the file and install as shown in below image
![Screenshot 2022-03-01 at 11 20 11](https://user-images.githubusercontent.com/8637550/156160172-a2472913-b43c-4268-a631-d6cd57c3dcf5.png)

**Comment by jmagnetti** [comment]
I installed the file & reloaded the extension. No errors anymore but also
no data still. 200 response, 0 bytes. Powershell generated script from the
extension still works fine and returns data.

**Comment by jmagnetti** [comment]
Note: I do get this warning in the powershell results:
WARNING: Resulting JSON is truncated as serialization has exceeded the set
depth of 2.

**Comment by rangav** [comment]
thanks, issue could be something else then.

can you generate curl command and run it and see you get the result?

**Comment by rangav** [comment]
also can you see if there are any errors in output window
![Screenshot 2022-03-01 at 11 36 16](https://user-images.githubusercontent.com/8637550/156162390-5b70639f-115e-4c7b-a7ec-c096c2e8fca4.png)

**Comment by jmagnetti** [comment]
Only items in the output window are:

Environment Used: **blah** (Active)
Request Url: **blah**

curl command worked perfectly.

**Comment by rangav** [comment]
can import that curl command again into thunder client, execute the request.

![Screenshot 2022-03-01 at 11 49 38](https://user-images.githubusercontent.com/8637550/156164129-64bc972a-241d-49dc-a49e-4742907a8b29.png)

**Comment by jmagnetti** [comment]
The exported curl had line breaks. I removed them to run the command in
windows terminal. It worked fine & returned results in terminal.
I imported the curl from my edited version into the extension. It ran, 200
response, no data. Errors did show up as such:
[image: image.png]

**Comment by jmagnetti** [comment]
[{
"resource": "Untitled-2",
"owner": "typescript",
"code": "1005",
"severity": 8,
"message": "';' expected.",
"source": "ts",
"startLineNumber": 1,
"startColumn": 9,
"endLineNumber": 1,
"endColumn": 12
},{
"resource": "Untitled-2",
"owner": "typescript",
"code": "1005",
"severity": 8,
"message": "';' expected.",
"source": "ts",
"startLineNumber": 1,
"startColumn": 125,
"endLineNumber": 1,
"endColumn": 131
},{
"resource": "Untitled-2",
"owner": "typescript",
"code": "1005",
"severity": 8,
"message": "';' expected.",
"source": "ts",
"startLineNumber": 1,
"startColumn": 150,
"endLineNumber": 1,
"endColumn": 156
},{
"resource": "Untitled-2",
"owner": "typescript",
"code": "1005",
"severity": 8,
"message": "';' expected.",
"source": "ts",
"startLineNumber": 1,
"startColumn": 221,
"endLineNumber": 1,
"endColumn": 227
}]

**Comment by rangav** [comment]
Hi @jmagnetti , published a pre-release version `v1.13.0` to marketplace.

How to install pre-release version

![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

**Comment by jmagnetti** [comment]
Thanks mate, that new version has not solved the issue unfortunately.

**Comment by jmagnetti** [comment]
I don't suppose I could get a version with some more debug or some such to
try and diagnose the issue a bit better? I'm sorry I can't provide access
to the API.

Thanks.

Joel.

**Comment by rangav** [comment]
As I have don't required info to re-produce the issue.
I am closing this issue, feel free to re-open if needed.
