### ISSUE TITLE
Go (golang) code snippet support 

### ISSUE THREAD

**Issue by brentdurksen** [rangav/thunder-client-support#484]
**Is your feature request related to a problem? Please describe.**
In the code snippet UI, please add support for generating Go code. This is available in Postman and I use it regularly there.

**Describe the solution you'd like**
Generate idiomatic Go code for requests using only standard library packages like net/http and io/ioutil

**Describe alternatives you've considered**
Using Postman; writing code manually

**Implementation:**
e.g. https://blog.logrocket.com/making-http-requests-in-go/

**Comment by rangav** [comment]
Thanks @brentdurksen will add to roadmap

**Comment by rangav** [comment]
@brentdurksen you can contribute for this feature if interested.
https://github.com/rangav/thunder-codegen

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
