### ISSUE TITLE
Overwritten my custom content-type after new release

### ISSUE THREAD

**Issue by pascaldice** [rangav/thunder-client-support#485]
**Describe the bug**
custom content-type was overwritten when using Json Content.

**To Reproduce**
1. input custom content-type (etc. application/json+sua)
![image](https://user-images.githubusercontent.com/35025260/156274793-08eadb62-a8d8-42e9-b4cf-fe7c695b0637.png)

2. input your Json Content on Body tab
![image](https://user-images.githubusercontent.com/35025260/156274861-b079558b-3f53-4603-8534-4ee0e63e633c.png)

3. Server received only "application/json" (ignored my content-type)
![image](https://user-images.githubusercontent.com/35025260/156275306-4d665155-aeaf-495e-b310-baa7e554265d.png)

4. If Json Content is empty, client can send custom content-type.

**Expected behavior**
Client must send header as user input.

**Platform:** 
 - OS: Windows10
 - vscode version: 
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.17763
 - extension version: v1.12.2

**Solution:**

**Comment by rangav** [comment]
Hi @pascaldice thanks for reporting the bug, will fix asap.

**Comment by rangav** [comment]
Hi @pascaldice, fixed this bug and published a pre-release version `v1.13.0`, so you don't have to wait for release version.

How to install pre-release version

![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

**Comment by pascaldice** [comment]
@rangav It works nicely for now. 
Thanks for your support.

**Comment by rangav** [comment]
This bug is is now fixed and published marketplace as release version in `v1.12.5`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.5
