### ISSUE TITLE
Local environment needs "delete and re-enable" to work

### ISSUE THREAD

**Issue by LarsPede** [rangav/thunder-client-support#486]
**Describe the bug**
When moving between computers I have to delete and re-enable the local environment. If I don't then I cannot set an env variable through my test step of the calls.

**To Reproduce**
- Create call
- Enable local env
- Set local env var programmatically in the call's test section
- Run call
- Push to branch
- Pull to different machine
- Run call from that machine
- Test fails with "enable local env" even though the local env already exists and cannot be enabled without deleting 

<img width="302" alt="Screenshot 2022-03-02 at 10 51 12" src="https://user-images.githubusercontent.com/6368624/156337877-b0f2d23d-621b-4d07-bd21-35d72b5080c1.png">
<img width="665" alt="Screenshot 2022-03-02 at 10 50 50" src="https://user-images.githubusercontent.com/6368624/156337879-0e7da741-01ab-439d-9c12-1d42f10c9099.png">

**Expected behavior**
The test should pick up the local env that has already been enabled for that project.

**Platform:** 
 - OS: Mac OS
 - vscode version: 1.64.2
 - extension version: v1.12.2

**Expected Solution:**
Expecting it to be a check on an ID or created date that needs to be removed in the test section. 

**Others**
Just wanted a place to write: Great product! Makes it so much easier for devs to work!

**Comment by rangav** [comment]
Hi @LarsPede thanks for reporting the bug, will verify and fix it asap.

**Comment by rangav** [comment]
Hi @LarsPede, fixed this bug and published a pre-release version `v1.13.0`, so you don't have to wait till release version.

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

**Comment by LarsPede** [comment]
Amazing @rangav hope the bug wasn't too hard to find 🥇

**Comment by rangav** [comment]
Yeah it was easy fix, but surprised how I missed that. 

May be that’s part of product development cycle - bugs and fixes.

**Comment by rangav** [comment]
This bug is is now fixed and published marketplace as release version in `v1.12.5`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.5
