### ISSUE TITLE
When request body is binary, content type is unknown instead of application/octet-stream

### ISSUE THREAD

**Issue by ppgpn** [rangav/thunder-client-support#487]
**Describe the bug**

When making a request with a binary request body, its content type is unknown instead of application/octet-stream

**To Reproduce**

- Open Thunder client
- Create new request
- Choose Binary File as body
- Upload a binary file (e.g. .tgz file)
- Send the request
- Look the request with a traffic tool (e.g. fiddler), or look at the proposed generated curl from code snippet
- Header has `Content-Type: unknown`

**Expected behavior**

Header has `Content-Type: application/octet-stream`

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.64.2
 - extension version: 1.12.2

**Solution:**

**Comment by rangav** [comment]
HI @ppgpn thanks for reporting the bug, will look into it.

**Comment by rangav** [comment]
is `application/x-compressed` is the correct content type for `.tgz` file?

**Comment by rangav** [comment]
Hi @ppgpn, fixed this bug and published a pre-release version `v1.13.1`, so you don't have to wait till release version.

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

**Comment by ppgpn** [comment]
I confirm that with the prerelease version, with binary file body, the Header has `Content-Type: application/octet-stream`.

Thank you for the fast response and have a nice day 🙂.

**Comment by rangav** [comment]
Thanks @ppgpn for confirmation 👍

**Comment by rangav** [comment]
This bug is is now fixed and published marketplace as release version `v1.12.5`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.5
