### ISSUE TITLE
Can't Do Custom Headers

### ISSUE THREAD

**Issue by jdgamble555** [rangav/thunder-client-support#488]
**Describe the bug**
If I select a custom header like `Content-type: application/dql`, there is no where for me to add a custom body.  If I select text, the header is changed.  There should be a `other` option like insomnia has!

This one problem makes Thunder Client Unusable for me.

Thanks, 

J

**Comment by rangav** [comment]
Hi @jdgamble555, there is a bug with custom header `content-type`, so published a pre-release version `v1.13.1` to address this isssue, so you don't have to wait till release version.

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

please let me know pre-release version solved the issue or not?

**Comment by jdgamble555** [comment]
Just tried it out, that fixed the problem.  Thanks!
