### ISSUE TITLE
AWS Sigv4 Signer

### ISSUE THREAD

**Issue by ChorjoDev** [rangav/thunder-client-support#489]
**Describe the solution you'd like**
Postman provides a feature that signs the AWS keys using the AWS Sigv4 signer. The keys are signed and added to the headers. The actual signing of the headers is a simple task but requires the AWS sdk to do this. 
 https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

This is really useful when testing API's via API Gateway and triggering lambdas that sit behind this level of authentication. It would be nice if the client was able to access these keys that sit in the '~/.aws/credentials'. Postman is currently unable to do this due to it being sandboxed and not having access to the local machine.

**Describe alternatives you've considered**
Postman does provide the SIgV4 signing method and it is widely used in many Organisation's I have worked in. 

https://learning.postman.com/docs/sending-requests/authorization/#aws-signature

**Comment by rangav** [comment]
Thanks @ChorjoDev for creating feature request, Will add to roadmap.

**Comment by rangav** [comment]
Hi @ChorjoDev I have finished development of this feature.

would you like to test? I can upload the `vsix `package here.

Just want to make sure its working as expected before I publish to everyone

**Comment by ChorjoDev** [comment]
Hi,

Oh wow that was quick..yes more than happy to test. I’m out today but should be able to test out tomorrow if that is ok?

Thanks
Gareth

**Comment by rangav** [comment]
@ChorjoDev thats ok, I will upload the file later today.

**Comment by rangav** [comment]
[vscode-thunder-client-1.13.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/8191505/vscode-thunder-client-1.13.2.vsix.zip)

@ChorjoDev attached the pre-release vsix file. Please test multiple aws services if possible and let me now.

Install manually from extensions tab
![Screenshot 2022-03-05 at 21 34 56](https://user-images.githubusercontent.com/8637550/156900551-8e233bfd-d8a9-4c35-9aac-f8ac999ce708.png)

**Comment by ChorjoDev** [comment]
Hey @rangav, 

Worked like a dream.  I tested it against API Gateway, as this is where the authentication of the signing happens. I ported all of our collections over from postman and all worked. 

Thanks

**Comment by rangav** [comment]
super thanks @ChorjoDev for confirmation, will publish to marketplace as a `pre-release` version, so others can also install it.

And will do a production release end of this week or early next week along with other planned features

**Comment by rangav** [comment]
Now its published to marketplace

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)
