### ISSUE TITLE
Features to make Thunder Client Better, Folders, Configurations and Right Click Features

### ISSUE THREAD

**Issue by Stancobridge** [rangav/thunder-client-support#49]
So I heard about this extension thunder client from a youtuber it was really amazing and am ready to test and see how it work.

I like postman so much and how it works and believe me, the current postman we are using was not really how it was when it first came out and I so much applaud the team behind it for the continuous development and improvements they have done so far to make using postman worth it for both rest API and graphl support.

I and my team are currently working on a project where we are using postman but due to some issues, sometimes it fails to start we have to restart the pc before it will start and synchronization is offline first which means if am not connected to the internet I can't access my collections in postman if there is a way to change that I don't know. 

When I saw the video about this extension it got my attention and I decided to test it and here are the issues that made my team not go on with it.
1. Once I click on the Collections tab and select a collection, am not able to create a request inside the collection, we are used to right-clicking and select add request to be sure that this new request belongs to this collection.

2. I can't create folders and subfolders inside a collection to able to group my requests
3. I can't set collection-specific configurations like header authorization for every request, even though I set the environment variable am not able to set headers for a single collection, every request in this collection will use it

So far the extension is good and wonderful for a start. I will love it if this features a put into consideration thanks

**Comment by rangav** [comment]
Hi @Stancobridge thanks for great feedback, These features are already in my product roadmap.

The 1 and 2 are already finished development see - #14 
Collection specific config is already suggested here - #33

So i am closing this issue, please add any comments in above issue links.
