### ISSUE TITLE
The ability to select and copy text from the Response window

### ISSUE THREAD

**Issue by gerhardvr-finclude** [rangav/thunder-client-support#493]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to select text in the Response window. Because of this it is also not possible to copy text. This becomes problematic when setting up tests since it will help a great deal to be able to copy key names from the JSON response to paste them into test setup screen edit boxes.  The same goes for the JSON response values. 

**Describe the solution you'd like**
Be able to select and copy text in the response window. For example, currently I have to count all the 0's in the json.transaction_value.tendered_breakdown[1].value field and type the value manually in my test.

![image](https://user-images.githubusercontent.com/78418254/157065245-05d8a3da-c4b0-4f40-8ce4-0f56b1089ae8.png)

**Describe alternatives you've considered**
Only alternative at the moment is to place the cursor on the value in the response window and then move the cursor using the left and right keys while counting the 0's

**Implementation:**

**Comment by rangav** [comment]
@gerhardvr-finclude thanks for reporting the issue, what OS are you using?

this could be vscode bug, please see this issue https://github.com/rangav/thunder-client-support/issues/439#issuecomment-1032633209

**Comment by gerhardvr-finclude** [comment]
I may very well be related, however, the case I'm experiencing is a bit different. I did some more testing and can now confirm:
1) I have the API request window and a source file edit window open side by side.
2) It is possible to select text in the response window
3) The copy/past context menu does pop up when right-clicking
4) When using the context menu to copy the text, the text from the source code edit window is copied from the line where the cursor is currently in that window, instead of copying the selected text in the response windows
5) When using the keyboard shortcut to copy the text, instead of the context menu (Cntrl-C on Windows), the correct, selected text, is copied from the response window.

![image](https://user-images.githubusercontent.com/78418254/157069163-6e07fa60-bfed-414a-aa38-54ef1439927c.png)

**Comment by gerhardvr-finclude** [comment]
OK, in that case, I'm closing this report.

Thanks for your quick response.

BTW Thunder Client is awesome. Had it installed for some time now but only really started using it in earnest today. I can kick my butt that I waited so long. :)

Thanks for the great work done on it.

Regards

Gerhard

**Comment by rangav** [comment]
Thanks Gerhard, Glad you like it :)

feel free to share any feedback to improve the product.
