### ISSUE TITLE
Batch Requests

### ISSUE THREAD

**Issue by PeterDomC** [rangav/thunder-client-support#496]
Hi there 😃 

**Is your feature request related to a problem? Please describe.**
Currently I am using Thunder Client for testing against my OData API.
As OData is supporting [batch requests](https://www.odata.org/documentation/odata-version-2-0/batch-processing/) and I rely on them a lot, I need to test them with Thunder Client as well.
Unfortunately, it seems that batch requests are not supported.
I get an "415".

<img width="313" alt="status" src="https://user-images.githubusercontent.com/80814965/157396930-a1a35d70-9186-4cb0-85b7-66b8f73ba7f9.png">

**Describe the solution you'd like**
I was using Postman before and they had a solution involving the keyword "$batch" in the call.
So the below call would go through:

<img width="500" alt="call" src="https://user-images.githubusercontent.com/80814965/157398042-226a1491-6664-4e7d-9c2c-2dffc94d188c.png">

**Describe alternatives you've considered**
The alternative is going back to Postman which I want to avoid at all cost...

Best regards and thanks for the great VSC extension!

**Comment by rangav** [comment]
Thanks @PeterDomC for the feedback, will add to roadmap.

**Comment by rangav** [comment]
@PeterDomC dont know about the batch requests, never used them.

Just trying to understand what steps needs to be done for this to work.

Just send the body you entered in the `Text tab` or do we need split the body into multiple requests and execute?

If you can provide the steps needs to make this work, would be appreciated.

**Comment by PeterDomC** [comment]
Thank you for the answer!
I think it would be enough to send the content of the "text tab" without further preprocessing.
Actually, the receiver (API) should decompose the body of the batch request into multiple calls.

What I saw is that it seems that the wrong content type is sent to the API. 
What I specified in the header:

<img width="492" alt="header" src="https://user-images.githubusercontent.com/80814965/157451236-edb7a17f-0465-43b3-abfa-8f97fee28aba.png">

does not arrive at the server:
<img width="121" alt="textplain" src="https://user-images.githubusercontent.com/80814965/157451151-7feedfd1-cbd9-44c5-9717-87f68fde13c0.png">

**Comment by rangav** [comment]
Got it thanks,

There is issue with content-type, switch to pre-release version where this issue is fixed.

you install `pre-release` version from extension tab

**Comment by PeterDomC** [comment]
Wow, this already seemed to solve my problem completely :)
Thanks a lot!

**Comment by rangav** [comment]
This bug is is now fixed and published marketplace as release version in `v1.12.5`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.5
