### ISSUE TITLE
Html Renderer

### ISSUE THREAD

**Issue by sghsri** [rangav/thunder-client-support#5]
It would be super helpful if this amazing extension could render html for responses, kind of like how Postman does it!

**Comment by rangav** [comment]
hi @sghsri you are referring to html preview right?

**Comment by sghsri** [comment]
> hi @sghsri you are referring to html preview right?

Yes I am

**Comment by rangav** [comment]
ok i will research on how to implement

**Comment by Spotnyk** [comment]
This is the main thing keeping me from completely transitioning from Insomnia to Thunder. Glad to hear it's coming. Thanks!

**Comment by lcuevastodoit** [comment]
Excelent work, amazing. Please give us HTML Preview

**Comment by rangav** [comment]
Hi all, Will include this feature in the next update v1.3.0.

**Comment by rangav** [comment]
This feature is implemented now in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.

**Comment by jashgopani** [comment]
I am not able to see the rendered HTML on clicking the "preview" option...
The response returned from server is `<html><body><h1> hello world</h1></body></html>` and `content-type` is `text/html`
How do I fix this ?

**Comment by rangav** [comment]
Hi @jashgopani i just now tested with the same html, its working for me

https://www.thunderclient.io/t/html

![image](https://user-images.githubusercontent.com/8637550/120454212-97d32600-c38b-11eb-8a4d-1154a0167f4a.png)

**Comment by jashgopani** [comment]
@rangav I tried the thunderbird URL you provided and that worked for me...
After that I tried multiple more URLs those also worked.
But my simple express server response is not getting rendered. 😔
Can you please try out the below code on your machine and test the preview once...
```javascript
const express = require('express');
const http = require('http');
const hostname = 'localhost';
const port = 9000;

const app = express();
app.use((req, res, next) => {
	console.log(req.headers);
	res.statusCode = 200;
	res.setHeader('Content-Type', 'text/html');
	res.end('<html><body><h1> hello world</h1></body></html>');
});

const server = http.createServer(app);
server.listen(port, hostname, () => {
	console.log('Server running on ', { hostname, port });
});

```

**Comment by rangav** [comment]
Hi @jashgopani  can you share screenshots of raw and preview response.

open your express url in browser and see if it works or now.

**Comment by frees11** [comment]
Hello how about running JS in preview? Would it be possible? For example my Backend produces this beautiful debugger page on some error

![image](https://user-images.githubusercontent.com/1942987/147705624-3974720b-d77d-43b1-a929-b9de02edd3eb.png)

Only problem is, that opening some additional panels and navigating throught call stack doesn't work, because it counts with working JS, which sadly isn't working

**Comment by rangav** [comment]
Hi @frees11 

there are some CORS and security issues, will look into it when I get time.

**Comment by rangav** [comment]
Html Preview now enabled to run javascript.

please update to `v1.14.1`

let me know if any feedback

**Comment by Thavarajan** [comment]
can you provide a html preview switcher, still it was not showing html in proper way if it was not having a html tag

**Comment by rangav** [comment]
@Thavarajan  I have changed few things last version, that might caused the issue.

can you please your sample response text, I will verify and fix it asap.

**Comment by Thavarajan** [comment]
[Html Preview not showing](https://github.com/rangav/thunder-client-support/issues/725)

This is the exact output for me too
