### ISSUE TITLE
Body content ignored while making GET requests

### ISSUE THREAD

**Issue by sinnl** [rangav/thunder-client-support#50]
Hi,

Body parameters seem to be only working when request type is set to POST and ignored when using GET

Can body be also used while making GET requests?

Thanks

**Comment by rangav** [comment]
Hi @sinnl GET request doesn't have body right?

**Comment by sinnl** [comment]
I'm far from being the expert on the subject but I think hey can. I've been working with a lot of different APIs passing body with additional parameters, filters, search queries etc. Doing the same with POST changes the context and received response. 

You can of course pass them in the URL with GET I just found it easier with body especially when you have a lot of them. Having them as json makes it  very easy to paste them to new request and tweak, rather than defying all as query parameters. It's just quicker :)  

 I'm not sure if passing body to GET is against best practice, just something I've been doing and seen working in insomnia or postman :) If it is feel free to close this issue.  

Thank you for your time and quick repose. Great work by the way!

**Comment by rangav** [comment]
You should use post request if need to send body, not GET

**Comment by contibru** [comment]
I`m having the same issue.
Ok, it is not the best practice, but there is some legacy software working like that  (GET with Body). 
So, if the postman and insomnia allow this, I think the Thunder could allow to.

I searched about that and I found this post on StackOverFlow.
https://stackoverflow.com/questions/978061/http-get-with-request-body#:~:text=Yes.,semantic%20meaning%20to%20the%20request.
