### ISSUE TITLE
Add db file formatting

### ISSUE THREAD

**Issue by droppedcode** [rangav/thunder-client-support#500]
**Is your feature request related to a problem? Please describe.**
Currently the db files (json files) that contain the requests/collections are not formatted. This is good if you want space, but hellish for merge.

**Describe the solution you'd like**
An option to the settings (to keep backward compatibility) that allows to set the a boolean flag like "Formatted db files".
It would do the following:
Use indented json stringify.
Alphabetically sorted properties on the objects.
In the arrays sorted by the name of the request or an index if there is something like that.

**Describe alternatives you've considered**
Possibly doing it before commit with a tool, but it would add an additional step to the workflow.

**Implementation:**
https://stackoverflow.com/questions/5467129/sort-javascript-object-by-key
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by rangav** [comment]
Thanks @droppedcode for the feedback, will review and add to roadmap.

I am using this json db library which will save in that one line format
https://github.com/louischatriot/nedb

**Comment by JoelOnGithub** [comment]
I would like this feature too! New lines, sorted by key _and_ trailing commas. It would make git merging with the team so much easier.

But I don't think NeDB supports this. That library has not been updated since 2016.

**Comment by rangav** [comment]
It’s in my priority list to fix this. Will provide an update soon.

**Comment by rangav** [comment]
Hi all, started work on this feature. When it's ready I want you guys help for testing.

**Comment by droppedcode** [comment]
I'm looking forward to it.

**Comment by rangav** [comment]
Hi all, Implemented the new db format which all normal json files. Below is the pre-release version download and install manually. it will auto upgrade the existing `.db files to .json` files and move .db files to backup folder, incase if you want to roll-back to previous version


[vscode-thunder-client-1.15.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/8444526/vscode-thunder-client-1.15.2.vsix.zip)

How to install vsix manually
<img width="542" alt="Screenshot 2022-04-07 at 16 49 02" src="https://user-images.githubusercontent.com/8637550/162243863-efeeef39-458d-41bd-8d39-fdbd8cbdc1d4.png">

Please let know your feedback

**Comment by JoelOnGithub** [comment]
I have tested it and so far it seems to work like a charm!

**Comment by rangav** [comment]
@JoelOnGithub thanks for confirmation 

have you tested git merge, did you find it better now?

**Comment by droppedcode** [comment]
@rangav Thank you for the change, this will save me quite a few hours in the future.

Tried with git merge (of course it tried to merge 2 requests together) but with any tool you can correct it (I use beyond compare).

But the important thing that it was quite simple to see what was the change and how I should solve the conflict. I saw what was new and what has changed.

Really thanks, this is quite a good change.

**Comment by rangav** [comment]
Thanks @droppedcode for confirmation 

good to know that you guys are happy with the changes made.

I will publish the release to marketplace later today.

**Comment by JoelOnGithub** [comment]
> @JoelOnGithub thanks for confirmation
> 
> have you tested git merge, did you find it better now?

Yes, the merge is a million times better now! I can't wait to kill postman in our organization, lol.

Features to consider, which will improve team work as well:
- When the json database files are updated (because switching git branch), reload collections automatically.
- Aside from environment variables, introduce something like local variables (which are not stored in a DB) would be nice. Because I store my JWT tokens for the tests in there, but they should never be committed
- Save extension settings in a .thunder-client.conf.json file, so that other devs on the same project use the same settings.

**Comment by rangav** [comment]
@JoelOnGithub thanks for feedback. see below answers

1. changes to db files reload collections automatically is in roadmap. For now you can reload by clicking the `Reload Data` icon manually
<img width="290" alt="Screenshot 2022-04-08 at 10 35 19" src="https://user-images.githubusercontent.com/8637550/162409176-a1683bcc-b338-4ec8-856c-8ca32558da5c.png">

2. We already have this feature called `Local Environment`, see below how to enable it.
https://github.com/rangav/thunder-client-support#environments
<img width="284" alt="Screenshot 2022-04-08 at 10 37 35" src="https://user-images.githubusercontent.com/8637550/162409545-f92fb817-28f2-45f9-b20b-a6b56566d919.png">

3. For Thunder Client settings, if you use the workspace settings tab in the settings UI, it will save in your current workspace in `.vscode` folder. which can be shared with the team

<img width="922" alt="Screenshot 2022-04-08 at 10 44 55" src="https://user-images.githubusercontent.com/8637550/162410849-8acba6fb-7712-4008-8d5b-d4f9148d556b.png">


<img width="683" alt="Screenshot 2022-04-08 at 10 39 48" src="https://user-images.githubusercontent.com/8637550/162410312-f0d252b1-dbf0-470c-a742-b5ca0a4d6906.png">

**Comment by JoelOnGithub** [comment]
Awesome! Then only point 1 still stands. But that is very low priority.

I'm going to set-up a pilot in the upcoming month to evaluate in our organization.

**Comment by rangav** [comment]
sounds good @JoelOnGithub, let me know if you have any further questions.

**Comment by rangav** [comment]
This feature is now published to marketplace as release version `v1.16.0`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.0

**Comment by wvanderdeijl** [comment]
Love this feature. Also makes reviewing changes to the file in a github PR easier as it easy to see what changed without lots of horizontal scrolling
