### ISSUE TITLE
"Error: Invalid URL"  Convert To Postman Format  

### ISSUE THREAD

**Issue by wutkaru** [rangav/thunder-client-support#502]
**Describe the bug**

Convert To Postman Format  
"Error: Invalid URL: {{url}}/test?PARAMS={"URL":"https://demo.com"}"

<img width="1129" alt="Screen Shot 2565-03-16 at 23 25 04" src="https://user-images.githubusercontent.com/43336971/158640093-407bea6b-a6db-4a98-a4a0-bb3f3054c784.png">
**To Reproduce**

1. Export Collection to Json file.
2. Select Json file Covert to Postman Format.

**Expected behavior**

Converted Sucessfully

**Platform:** 
 - OS: MacOS Monterey
 - vscode version: 1.65.2
 - extension version: 1.12.5

**Solution:**

Cause may be colon in URL value or {{url}} match with "URL".
I can converted successfully by 3 methods
1. Disable PARAMS
2. Enable PARAMS and remove colon
3. Replace {{url}} from env value Ex. http://localhost:port

**Comment by rangav** [comment]
Thanks @wutkaru for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is is now fixed and published to marketplace as release version `v1.14.0`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.0

**Comment by rangav** [comment]
Thanks @oflannabhra for reporting the issue, will verify and get back to you

**Comment by rangav** [comment]
@oflannabhra i just now tested it, it working fine for me. no issues.

Can you share your sample collection file, so I can test here. you can remove any sensitive info
