### ISSUE TITLE
Option to toggle default display preview/raw

### ISSUE THREAD

**Issue by rodber** [rangav/thunder-client-support#504]
**Is your feature request related to a problem? Please describe.**
The client response displays raw, without a way to configure that. It requires an extra step to click on "preview" for html documents.

**Describe the solution you'd like**
A configurable default display as a drop down / checkbox enabling to skip the need for clicking on the preview button.

**Describe alternatives you've considered**
None.

**Implementation:**
👉👈

**Comment by rangav** [comment]
Thanks @rodber for the feedback, will add to roadmap.

**Comment by kythuatwebso** [comment]
Vote 1+

**Comment by rangav** [comment]
Hi all, I am planning to make html preview as default view instead of raw text, that will address the issue.

**Comment by rangav** [comment]
This feature is is now implemented and published to marketplace, please update to `v1.14.1`

let me know if any feedback
