### ISSUE TITLE
Import PostMan collection fails

### ISSUE THREAD

**Issue by stefanstranger** [rangav/thunder-client-support#507]
**Describe the bug**
I'm trying to import the following [PostMan Collection](https://www.postman.com/twitter/workspace/twitter-s-public-workspace/overview) but it fails with the following information in vscode

![image](https://user-images.githubusercontent.com/2125385/159342209-c948d186-8795-409a-bbe9-c6f7ab3b8bb9.png)

**To Reproduce**
Import PostMan Collection (tried both available versions)

**Expected behavior**
PostMan Collection imported successfully. 

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.65.2
 - extension version: 1.12.5

Thanks for your help.

Regards,
Stefan Stranger

**Comment by rangav** [comment]
Hi @stefanstranger I exported the collection files as Postman 2.1 format and imported sucessfully

<img width="261" alt="Screenshot 2022-03-21 at 19 11 57" src="https://user-images.githubusercontent.com/8637550/159347294-60c7d736-ecd1-4068-b9e0-66d4e21dcb84.png">

**Comment by stefanstranger** [comment]
Hi Ranga,

Thanks for testing! I found the issue, it was a mistake on my side. I selected Environment instead of Collection before doing the import. I tried to import it again and now it works fine.

Excuses for the confusion.

Regards,
Stefan Stranger

**Comment by rangav** [comment]
@stefanstranger no problem 👍
