### ISSUE TITLE
Add support for Pre request scripts and getting / setting env var through script

### ISSUE THREAD

**Issue by chandanjainn** [rangav/thunder-client-support#51]
**Describe the solution you'd like**
1. Want to run some scripts before sending the requests. e.g - encrypting the credentials in login api before making the request using **_CryptoJS_** package . 
Postman's equivalent of `var encrypted = CryptoJS.AES.encrypt(
    "R@nd0mPassw0rd",
    pm.environment.get("encryptSecretKey")
    ).toString();`
2. To be able to set env variables through test script.
 Postman provides a feat. something like this `pm.environment.set("encryptedPassword", encrypted);`

**Comment by rangav** [comment]
HI @chandanjainn no 2 is it after request or pre-request?

**Comment by chandanjainn** [comment]
@rangav it could be both I guess. We are just setting the env variable.
Let me elaborate on my use case if it helps-
After login am getting the token from login api response and saving it into a global env variable so that it can be auto appended to all outgoing requests header using that variable instead of the user changing the token manually everytime.

**Comment by rangav** [comment]
if its setting env var, it is already possible see testing section. pre-scripts is already requested here - #16, can I close this issue, so we can discuss in issue #16
