### ISSUE TITLE
string "null" not equals "null" in response body

### ISSUE THREAD

**Issue by harimambura** [rangav/thunder-client-support#510]
**Describe the bug**
When server retruns "null" in response body, test (responseBody equal null) fails

**To Reproduce**
Create request to https://thunder-bug.free.beeceptor.com
Create test for this request: set responseBody => equal => null (without any quotes)
Send request -> test fails

**Expected behavior**
test passes

**Platform:** 
 - OS: windows 10
 - vscode version: 1.65.2
 - extension version: v1.14.0

**Comment by rangav** [comment]
Thanks @harimambura for reporting the bug, Will verify and fix it.
