### ISSUE TITLE
Import Postman collections 

### ISSUE THREAD

**Issue by Shinobi247** [rangav/thunder-client-support#512]
**Is your feature request related to a problem? Please describe.**

It'll be helpful if there is an option to import the existing postman collections and convert them to Thunder Collection. 

**Describe the solution you'd like**

N/A
**Describe alternatives you've considered**

Copy-pasting APIs from the postman and that's very time-consuming.

**Implementation:**

N/A

**Comment by rangav** [comment]
Hi @Shinobi247 this feature also supported from version 1.0

From collections tab you can import 

Details here
https://github.com/rangav/thunder-client-support#import

**Comment by Shinobi247** [comment]
@rangav Got it. Thanks! for the quick response. 

Just FYI from a user perspective, it was hard to find out the option. It looks like an option for the filter.

**Comment by rangav** [comment]
Thanks for the feedback, will review and improve the UI.
