### ISSUE TITLE
An error occurred while loading view: thunder-client-sidebar - again

### ISSUE THREAD

**Issue by VASKOTechDesign** [rangav/thunder-client-support#513]
Hello, sorry to disturb you again to return to this topic. I Installed it on 24.3.2022 and used it for 2 requests, then I open the second session of VS Code, and suddenly after the closing of the first session the "Thunder Client" stop working, and I'm not able to enable it to run again.

I tried all methods to repair it but o success:
Method 1 (PavelSafronov commented on Nov 5, 2021) --> no success
Method 2 (xvrx commented on Feb 17) --> no success
Method 3 Uninstall extension, restart PC and install again --> no success

My setup:
Visual Studio Code:
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Thunder Client:
Version: v1.14.0

Printscreen:
![image](https://user-images.githubusercontent.com/50368892/159938644-6af657ca-c118-495c-bf26-e6c2252440c2.png)

Think it is connected to the "#349" which is already closed.

Thank you for help

**Comment by rangav** [comment]
thanks @VASKOTechDesign for reporting the issue, the db files may have corrupted.

you can delete those files and it should work.

follow the steps here
https://github.com/rangav/thunder-client-support/issues/469#issuecomment-1046696308

let me know if you further questions

**Comment by VASKOTechDesign** [comment]
Hello, thank you for the hint, unfortunately I do not have a folder "C:\Users\{{USERr}}\**Library**\Application Support\Code\User\globalStorage\rangav.vscode-thunder-client\"

is there any other place where the file can be stored? or what is file name so I would be maybe able to find it?

Thank you

JAn Vaško

**Comment by VASKOTechDesign** [comment]
HEllo so thank you I found it:
![image](https://user-images.githubusercontent.com/50368892/159943936-baa20277-adc6-4257-bf5c-c42289bbe836.png)

--> this works. I think that it would be somehow caused by another extension I use "Project Manager" --> link: https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager

Thank you

we can close this bug

**Comment by rangav** [comment]
thanks for confirmation.

**Comment by VASKOTechDesign** [comment]
Hello,

Sorry to disturbe you agan, but I found the same issue, even if the DB is stored by Workplace.

I use several of them and every time in some point of time the extension stop working. From my perspective it looks like when some requests are stored in the" Collections".

This issue makes the extension almost not possible to use as you cannot save Requests and create them every time when you want to check it.

I can offer you my collaboration/testing if you will want as, I see your extension as the best what is available and I want it :-)

So can you please take a look?

Than you 

Jan Vasko

**Comment by rangav** [comment]
@VASKOTechDesign thanks for reporting the issue.

Can you uncheck the `save to workspace` and open the project and then thunder client sidebar.

Now enable back the `save to workspace` and re-open the project again.

Let me know if this works or not?

Also I am planning to change the database layer to different format to address the multiple issues around the current db architecture.

**Comment by rangav** [comment]
I have updated the database format in `v1.16.0`, which should fix this issue now.

Please upgrade to `v1.16.0` and let me know if any feedback 

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.0

**Comment by VASKOTechDesign** [comment]
Hello Mr. Vadhineni,

Sorry for late ipdates from my side. I still was not able to test it as my son was born few days ago. I want to test it, but need more time :-)

I already updated to 1.16.0.

Thanks Jan

Jan Vasko
________________________________

**Comment by rangav** [comment]
No problem @VASKOTechDesign just want to give you the update.

You can test and let me know any feedback when you are free, no rush.

Have a great time with your new baby 🙂

**Comment by VASKOTechDesign** [comment]
Hello, just want to confirm that now it seems that Thunder Client holds stored data in collections :-) with no error. 

Thank you

Jan

**Comment by rangav** [comment]
Super thanks for confirmation 👍
