### ISSUE TITLE
Add Support for saving collection into json files.

### ISSUE THREAD

**Issue by saravanakumarrc** [rangav/thunder-client-support#514]
**Is your feature request related to a problem? Please describe.**
Yes. we are a team of developers like to share the api collection as an json file. so we need the git support. 

**Describe the solution you'd like**
we may store the collections into specific folder (given in the settings) so that each collection will be portable to postman and it should be in the json format. so that we can initialize the git repo and share/sync our api collections.

**Describe alternatives you've considered**
we can have a default folder where the collections are stored and retrieved from physically, If you expose then it would be great.

**Implementation:**
No, I have not started

**Comment by rangav** [comment]
Hi @saravanakumarrc you can save request data files to git project currently, this feature is already supported 

you need to enable vscode setting `Save To Workspace`

More details here
https://github.com/rangav/thunder-client-support#team

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
