### ISSUE TITLE
System Variable Detected as a Bad String in Editor

### ISSUE THREAD

**Issue by rizkimhd** [rangav/thunder-client-support#516]
**Describe the bug**

When I use system variable the vs code showing error sign

**To Reproduce**

Utilize system variable in the JSON request body
<img width="476" alt="Screen Shot 2022-03-25 at 16 50 08" src="https://user-images.githubusercontent.com/22513017/160098292-593f356f-ec3c-4b3a-8027-16adf11c287d.png">

**Expected behavior**

There should be detected as a bad string error warning, because the syntax is a correct system variable as mentioned in thunder client documentations
<img width="356" alt="Screen Shot 2022-03-25 at 16 53 30" src="https://user-images.githubusercontent.com/22513017/160098318-e84dddbf-25ae-45b2-b20a-2662c5597af0.png">

**Platform:** 
 - OS: MacOS Monterey
 - vscode version: 1.65.2
 - extension version: v.1.14.0

**Solution:**

**Comment by rangav** [comment]
Hi @rizkimhd thanks for the feedback.

It’s just complaining that it is not valid json, though technically it’s correct,

I need to customize the json validator to support this syntax which is in roadmap.

for now you can ignore that warning, when you run request it should work correctly.

**Comment by haffi96** [comment]
Can this feature be made open for contribution? 

Would be great to extend this features capabilities.

One of the things I have in mind is being to use something like {{#date+/-1day, 'X'}}  or {{#date+/-1hour}}. Basically adding the ability to auto-generate a timestamp which is +/- of the current timestamp. Apologies if this is already possible or you think it will be difficult to implement. But I'd like to give it a go

**Comment by rangav** [comment]
@haffi96 thanks for feedback, can you please a new issue for this feature request.

**Comment by haffi96** [comment]
> @haffi96 thanks for feedback, can you please a new issue for this feature request.

https://github.com/rangav/thunder-client-support/issues/656 Here you go

**Comment by rangav** [comment]
We have fixed the JSON validation syntax error for environment variables in `v2.8.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.8.0

Please let me know your feedback.
