### ISSUE TITLE
Environment Variable for atomsvc+xml

### ISSUE THREAD

**Issue by PeterDomC** [rangav/thunder-client-support#517]
Hi,

*Problem Description*
Currently, I am testing an API which requires to fetch a token in the beginning.
Like always, I wanted to store the token in an environment variable after the initial request.
The response that I get in the corresponding request is of content-type: atomsvc+xml.
Thunder Client tells me that it is not supported to set the env var with this content type:

<img width="480" alt="envvar" src="https://user-images.githubusercontent.com/80814965/160141290-0ae6a9c0-a20e-4a06-b62f-84f9cce6a0f4.png">

The token is actually present in the header:

<img width="379" alt="token" src="https://user-images.githubusercontent.com/80814965/160141371-c894d7d9-392e-4998-b7b5-ec93f74358b4.png">

Would it be a large effort to allow setting the environment variable in this case?
This would help me out :)

Best regards,
Peter

**Comment by rangav** [comment]
thanks for sharing, currently does not support xml query parsing, only json content type.

Will add to roadmap

**Comment by rangav** [comment]
See if you send `Accept` header with application/json, the request returns json?

**Comment by rangav** [comment]
sorry mis-understood your question, from `header` it should work, let me verify and get back to you

**Comment by rangav** [comment]
Looks like there is bug here, will fix and publish in next 1 hour

**Comment by rangav** [comment]
@PeterDomC  fixed this bug and published a `pre-release` version `v1.15.1`, so you don't have to wait till release version.

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)


Wait for few minutes, if you dont see the new version yet.

**Comment by rangav** [comment]
This bug is is now fixed and published to marketplace, please update to `v1.14.1`

let me know if any feedback
