### ISSUE TITLE
Can you generate other language for code snippet

### ISSUE THREAD

**Issue by Peter-Nithitanabhornkul** [rangav/thunder-client-support#518]
PHP, NodeJS, Swift, Obj C, etc.
for comparison my code may be wrong !!!

Thank you.

**Comment by rangav** [comment]
Thanks @Peter-Nithitanabhornkul for creating feature, will add to roadmap

**Comment by rangav** [comment]
if you like to contribute, here is repo link https://github.com/rangav/thunder-codegen

**Comment by imranbarbhuiya** [comment]
The link to the repo is no longer valid.

**Comment by rangav** [comment]
@imranbarbhuiya what code snippet lang are you looking for?

**Comment by rangav** [comment]
Hi All, The next update will support most languages, will publish in 1 or 2 days

![image](https://user-images.githubusercontent.com/8637550/182019486-cc24c420-cc94-4b4d-9d39-9d44eb40f445.png)

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
