### ISSUE TITLE
XSS JS code breaks environment settings

### ISSUE THREAD

**Issue by xshpakx** [rangav/thunder-client-support#519]
**STR**
1. Open environment properties
2. Add a new variable with XSS JS code as its value (<script>alert(123)</script>)
![image](https://user-images.githubusercontent.com/32393499/160246165-01dd01e2-1299-48df-be64-42b4b5b75036.png)
3. Save сhanges
5. Close the tab and reopen it

**Expected result**
The list of environment variables contains the added variable with JS code and is available for adding new variables

**Actual result**
The list of environment variables is not displayed and does not have a field for adding new variables
![image](https://user-images.githubusercontent.com/32393499/160246208-774bfa07-4556-437d-8347-72a5dd9423a1.png)

**Platform:** 
 - OS: Win10x64 21h2 // macOS Monterey 12.2.1
 - vscode version: 1.65.2
 - extension version: 1.14.0

**Comment by rangav** [comment]
Thanks @xshpakx for the reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is is now fixed and published, please update to  `v1.14.1`

let me know if any feedback
