### ISSUE TITLE
Set environment variables from headers response

### ISSUE THREAD

**Issue by zapisanchez** [rangav/thunder-client-support#520]
**Tests field. I can't store response headers as environment variable**

I'm trying to save a cookie from a response in a env variable in order to use in next requests, but I can't. 
I Only can access json of the response

**Describe the solution you'd like**

An option is Enable the option of make javacsripts scripts as postman does (i Understand we can't use their libs for parsing results here).
Also the option of have pre-requisites script will be nice

Thanks four you effort

**Comment by rangav** [comment]
Hi @zapisanchez 

you can save header and cookie from response to environment variable 

please see details here
https://github.com/rangav/thunder-client-support#setenv

**Comment by zapisanchez** [comment]
oh, sorry about this!
