### ISSUE TITLE
Broken link for code snippet contribution in readme.md file.

### ISSUE THREAD

**Issue by Dancheg97** [rangav/thunder-client-support#521]
### Description
When i go by this link: https://github.com/rangav/thunder-codegen, i am not getting to repository for code generation contribution.

### Reproduce
Create repositroty for codegen snippets generation, give a link.

### Solution
IMO contributing to this repository directly with code snippet generation would be very helpfull.

**Comment by rangav** [comment]
I have made it public, thanks.
