### ISSUE TITLE
Posting files randomly triggers "write EPIPE" error

### ISSUE THREAD

**Issue by WesleyYu1995** [rangav/thunder-client-support#522]
**Describe the bug**

1. Golang [Echo ](https://github.com/labstack/echo) acts as the backend.
2. A post entry "/e" to handle posting request from thunder client, no logic in this handler, just an entry.
3. No fail at all when posting purely without files attached.
4. Randomly fail when posting with files (by contrast, in fact most times were failed).
5. Postman has no such an issue.
6. No error throws by Echo
7. Printing code is always executed no matter with or without files attached.

A demo,

https://user-images.githubusercontent.com/101940568/160530550-385ce52d-b6a3-4d1b-b13b-2ed63c01d2c1.mov

**To Reproduce**
1. Start an echo server to handle post, example code,

```go
func PostT(ctx echo.Context) error {

	fmt.Println("Hello")

	return ctx.JSON(http.StatusOK, BRAND)
}

```
2. Do post with files from thunder.

**Expected behavior**
No exception when posting with files.

**Platform:** 
 - OS: MacOS
 - vscode version: Latest
 - extension version: 1.14.1

**Solution:**
None

**Comment by rangav** [comment]
Thanks @WesleyYu1995 for reporting the issue

**Comment by WesleyYu1995** [comment]
Seems the pre-released version 1.15.1 works like a charm, no such a problem.

**Comment by rangav** [comment]
Thanks for confirming, thats strange did not change anything related to this in pre-release version.

**Comment by rangav** [comment]
So I am closing this issue then, feel free to re-open if needed.
