### ISSUE TITLE
Missed request body during CURL import

### ISSUE THREAD

**Issue by v-anzhurov** [rangav/thunder-client-support#523]
**Describe the bug**
When trying to import POST Curl extensions misses request body

**To Reproduce**
Go to extension
Import curl using ctrl/cmd + u
Enter 'curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data'

**Actual behavior**
Request created
Req body missed
<img width="373" alt="image" src="https://user-images.githubusercontent.com/100565783/160569504-14c379d6-0322-4699-b35d-54a6f7d5ba29.png">

**Expected behavior**
Request created
Req body appeared
<img width="394" alt="image" src="https://user-images.githubusercontent.com/100565783/160569474-f1c391bb-5609-478a-a879-bd9ff34adf86.png">

**Platform:** 
 - OS: macOS Big Sur 11.5.2
 - vscode version: 1.65.2
 - extension version: v1.14.1

**Comment by rangav** [comment]
Thanks @v-anzhurov for reporting the bug,

I have fixed the bug and will release the fix part of next update this week.

If you want early, I can publish a pre-release version with this fix. let me know.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.14.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2

Let me know if any feedback
