### ISSUE TITLE
"Raw html" toggle is not persistent and defaults to "Preview" on send

### ISSUE THREAD

**Issue by tolgaulas** [rangav/thunder-client-support#524]
With the recent update the option having "Raw html" and "Preview" is neat however it's missing the option to be toggled or lacking to assign a default behavior via setting. 

For those like us who prefer raw content over preview, had to click "Raw html" after every "send". 

A quick plan to make it variable or being toggled would be highly appreciated. 

Many thanks in advance.

**Comment by rangav** [comment]
Thanks @tolgaulas for the feedback, will provide a setting to choose default view

**Comment by tolgaulas** [comment]
@rangav : <3 <3 <3

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.14.2`

Now it will persist the `user last selection`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.2
