### ISSUE TITLE
Input texts are not scrolling

### ISSUE THREAD

**Issue by DanRotaru** [rangav/thunder-client-support#526]
Input texts are not scrolling on mouse move, I need manually to press arrow keys, that sucks

https://user-images.githubusercontent.com/7759507/160935093-689415af-d9f2-4c37-be37-b677867a4bdf.mp4

**Comment by rangav** [comment]
Thanks @DanRotaru for reporting the bug, will look into it.

**Comment by rangav** [comment]
I have fixed the problem now, would you like to test and confirm?

[vscode-thunder-client-1.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/8470084/vscode-thunder-client-1.16.1.vsix.zip)

Download the attachment and install vsix manually as below
<img width="533" alt="Screenshot 2022-04-12 at 07 26 55" src="https://user-images.githubusercontent.com/8637550/162894687-4aea1d35-feeb-4d08-a217-3677d47451b5.png">

Please let me know your feedback

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
