### ISSUE TITLE
Export Request to Normal Text or Raw Request is not there. Can't see Exact Request that was sent. Export also won't export in simple form

### ISSUE THREAD

**Issue by Shahid-Roofi-Khan** [rangav/thunder-client-support#528]
Export Request to Normal Text or Raw Request is not there. Can't see Exact Request that was sent. Export also won't export in simple form

**Comment by rangav** [comment]
Hi, you can use the code snippet feature to see the request details 

https://github.com/rangav/thunder-client-support#codegen

> Export also won't export in simple form
Can you please share a screenshot, I will verify it

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open it if needed.
