### ISSUE TITLE
Syncronizing collection for better team working

### ISSUE THREAD

**Issue by fachryansyah** [rangav/thunder-client-support#529]
**Is your feature request related to a problem? Please describe.**
its would be nice if i can syncronize the collection to another computer with git

**Describe the solution you'd like**
with saving collection into file on current opened project, so we can push it to git and another dev can retrive same collection

**Describe alternatives you've considered**
syncronizing collection for better team working

**Implementation:**

**Comment by rangav** [comment]
Hi @fachryansyah 

this feature is already supported, details below 
https://github.com/rangav/thunder-client-support#team


let me know if you have any questions
