### ISSUE TITLE
Use env vars on request body

### ISSUE THREAD

**Issue by jmlxxvi** [rangav/thunder-client-support#53]
Hi, I am using the env var to be set dynamically from a request, that works fine and the env is set using JSON query from a response,
The thing is that I need to use that env var on the body of another request, something like:

{
    "token": "{{ZOMBI_ENV_SERVER_TOKEN}}"
    "mod": "sandbox/bucket",
    "fun": "ping"
}

You think it would be possible to do that?

Thanks.

**Comment by rangav** [comment]
Hi @jmlxxvi using the same steps as set env var should work? i think your question is not fully clear to me.

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen if needed
