### ISSUE TITLE
Renaming request/folder/collection that has quotation marks shows partial name 

### ISSUE THREAD

**Issue by lihail-melio** [rangav/thunder-client-support#531]
**Describe the bug**
If you create a request, folder, or collection that has **at least one** quotation marks (") in its name, e.g.:
```
Get all "good" cars
```
or:
```
This is a "test
```
... and then click "Rename" on that request/folder/collection, the input field in top of the screen will **sometimes** only show the name until that quotation mark. e.g.:
```
// Notice the space after the "all", right before the quotation mark is supposed to be:
Get all 
```
or:
```
// Again, notice the space after the "a"
This is a 
```

**To Reproduce**
1. Open the extension in vs code.
2. Click "Collections".
3. Click the menu near "filter collections".
4. Click "New Collection".
5. Type `Hello "world"` and then press enter:
6. Click the menu button (...) near the newly created collection, click "Rename".
7. The name should be `Hello "world"` but instead it might show just `Hello `.

**Expected behavior**
The name should be the exact one, with the quotation marks.

**Platform:** 
 - OS: 12.13.1 Monteray
 - vscode version: 1.66.0
 - extension version: 1.14.4

**Solution:**
I'm not sure, but I assume this issue has something to do with escape characters, since in order to have `"` in a JSON file you should escape it with `\`.

**Comment by rangav** [comment]
Thanks @lihail-melio  for reporting the bug, will look into it.

**Comment by rangav** [comment]
This bug is fixed now, please test and let me know your feedback
