### ISSUE TITLE
cloud storage

### ISSUE THREAD

**Issue by codthing** [rangav/thunder-client-support#532]
**Is your feature request related to a problem? Please describe.**

When I am in company and traveling and when I want to be able to store my api data in the cloud.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @codthing you can save the requests data to a git repo, and access it from anywhere.

See details here 
https://github.com/rangav/thunder-client-support#team

Let me know if you any further questions.

**Comment by codthing** [comment]
@rangav 
I appreciate it.
