### ISSUE TITLE
Tests queries should parse environnement variables

### ISSUE THREAD

**Issue by Vincent-HD** [rangav/thunder-client-support#533]
**Is your feature request related to a problem? Please describe.**
I'm using this extension for a Wordpress website, for authentication I still use Cookies, but in wordpress, the Cookie's name depends on a hash:
there is two main cookie:
`wordpress_sec_<hash> = <user's cookie>`
and
`wordpress_logged_in_<hash> = <user's cookie>`
But the client only permit to set an ENV variable from an already known cookie name.
It would be cool to be able to specify tests queries depending on variable, for exemple, I have a rest route (only for dev) that gives me back the wanted **hash** in the cookie's name
I would like to be able to have `cookie.{{hashname}}` setTo `{{another_env}}`
Like in this screenshot:
<img width="383" alt="Code_irs0lr9Fpd" src="https://user-images.githubusercontent.com/61592570/161760044-223e83b5-e12d-4345-a778-aad33242583a.png">

Tests "queries" doesn't support environnement variable (the left side)

For now, I'm doing it by passing the whole cookie via JSON response, but using Set-Cookie Response with Tests queries would be a ""cleaner"" solution (even tho it's not for production use)

**Comment by rangav** [comment]
Thanks @Vincent-HD for the feedback, will add to roadmap.

**Comment by rangav** [comment]
@Vincent-HD we aded `custom scripting` using filters in v2.0.0

see details here
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please let me know your feedback

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to v2.0.1

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.1

Please let me know your feedback.
