### ISSUE TITLE
I can't input Chinese characters on URL bar and query

### ISSUE THREAD

**Issue by alexhtwen** [rangav/thunder-client-support#535]
**Describe the bug**
Chinese characters can't be input both on url and query bars, but OK on other places.  I am using gcin Chinese input method.

**Screen Capture**
![Can't input Chinese characters](https://user-images.githubusercontent.com/32437370/161819463-a2038a79-fb6b-41bc-bf30-b63d63e2bfa6.png)

![Can't input Chinese characters-1](https://user-images.githubusercontent.com/32437370/161825056-0f013e43-29f4-466a-aa8f-c3220867c854.png)

**Expected behavior**
Chinese characters can be input on URL bar.

**Platform:** 
 - OS: Ubuntu 20.04
 - vscode version: 1.66.0
 - extension version: 1.14.4

**Solution:**
Should I set any environmental arguments on Ubuntu to make gcin work on URL bar?

**Comment by rangav** [comment]
Hi @alexhtwen Chinese Lang not yet supported.

may be try environment variable and use var name `{{variable}}` in url

**Comment by alexhtwen** [comment]
>may be try environment variable and use the var name {{variable}} in url

It works. Thank you. 

However, I have another question.  It seems two environment variables are not permitted in a single url.  Is it possible if I really need to?

![Can I use 2 enviroments in a single URL](https://user-images.githubusercontent.com/32437370/162017642-05945d8a-b78f-45f9-a829-bb19ad4f2cee.png)

**Comment by rangav** [comment]
you are trying to access variable from 2 different environment. which is not possible.

You can create `host` variable in `action` environment or you enable the `global environment` which is available to all requests and create a host variable in it.

let me know if its not clear

**Comment by alexhtwen** [comment]
I really appreciate your help.
>You can create host variable in the same action environment

I didn't get your point.  Would you make it more clear?  Some screenshots would be much appreciated.

---

>or you can enable the global environment which is available to all requests and create a host variable in it.

Did you mean that?  It works for me.  Thanks a lot.
![global-env-1](https://user-images.githubusercontent.com/32437370/162104185-a5f7ac8d-8c4b-4dd5-86ca-3141b1fe9f57.png)
![global-env-2](https://user-images.githubusercontent.com/32437370/162104192-5d3b9abc-15b0-490c-9671-6dd02a92eb21.png)

**Comment by rangav** [comment]
yes you are using it right for global env.

**Comment by rangav** [comment]
for active environment see below

<img width="1059" alt="Screenshot 2022-04-07 at 09 52 52" src="https://user-images.githubusercontent.com/8637550/162164380-f9b0a1df-22e8-456f-bb36-d08f3b2251ae.png">

**Comment by alexhtwen** [comment]
I got it.  Thank you so much.

**Comment by rangav** [comment]
I am closing this, as we already have a existing issue for this https://github.com/rangav/thunder-client-support/issues/161

**Comment by rangav** [comment]
I have fixed the problem now, would you guys like to test and confirm?

I can upload the `vsix` file here

**Comment by alexhtwen** [comment]
![Chinese displayed correctly](https://user-images.githubusercontent.com/32437370/162909148-5d2153a2-617c-42e9-959f-5373d451145e.png)

**Comment by rangav** [comment]
Here is the new update, please test and confirm.

[vscode-thunder-client-1.16.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/8470084/vscode-thunder-client-1.16.1.vsix.zip)

Download the attachment and install vsix manually as below
<img width="533" alt="Screenshot 2022-04-12 at 07 26 55" src="https://user-images.githubusercontent.com/8637550/162894687-4aea1d35-feeb-4d08-a217-3677d47451b5.png">

Please let me know your feedback

**Comment by alexhtwen** [comment]
Yep, It does work.  You've done a great job, Ranga.  Thanks a lot.

![Chinese can be input on the URL bar now](https://user-images.githubusercontent.com/32437370/162913119-a182a41a-54cd-48ff-8e03-f519fd0fa570.png)

**Comment by rangav** [comment]
Super, Thanks for the confirmation 👍

**Comment by rangav** [comment]
Thanks, Glad to know you like extension.

Feel free provide any feedback to further improve the product

**Comment by alexhtwen** [comment]
Good bye, Postman😃

**Comment by alexhtwen** [comment]
>Feel free provide any feedback to further improve the product

Sure

**Comment by rangav** [comment]
> Good bye, Postman😃
> 
> Our team has transfered to Thunder Client from Postman.

That’s good to know, can I know what is your team size

**Comment by rangav** [comment]
Thanks for sharing info 👍

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
