### ISSUE TITLE
Using schema action in testing

### ISSUE THREAD

**Issue by econesag** [rangav/thunder-client-support#537]
I'm working on validate a Json Response from an API REST. I want to check if has a defined structure. I'm trying to use schema because it has many fields, but i'm not able to find any documentation about how it works. Is this the correct use of schema?

**Comment by rangav** [comment]
Hi @econesag thanks for contact us

you can save the schema in environment or you can just paste schema text in the Tests Value field

see screenshot below
![Screenshot 2022-03-08 at 16 29 00](https://user-images.githubusercontent.com/8637550/157281791-7c5b0244-9728-44c6-a9c2-17a0ab729518.png)

let me know if anything not clear

**Comment by econesag** [comment]
I was pasting my structure in the environment but i don't kmow if it's correct. Could you show an example of a detailed structure of the schema? I was using that as example schema:
{
    "foo" : { "type" : "string"},
    "bar" : { "type" : "boolean"}
}

**Comment by rangav** [comment]
See below image, then you can use the variable in Tests using format `{{schema1}}`

Just paste the schema text in Env variable `Value` field
<img width="1178" alt="Screenshot 2022-04-06 at 17 19 36" src="https://user-images.githubusercontent.com/8637550/162021238-b1777a75-05dd-4438-9571-b081dff8f054.png">

**Comment by econesag** [comment]
It's still not working. Here is my test response:
![image](https://user-images.githubusercontent.com/100274132/162141864-68582a41-851f-4a0a-a279-57f8c417a52e.png)

Here is my schema definition:
![image](https://user-images.githubusercontent.com/100274132/162142060-6ae8d838-76f6-4479-9304-bba8fc85060a.png)

And finally the results and the test;
![image](https://user-images.githubusercontent.com/100274132/162142260-17e7da20-b909-45b3-9020-96618e13c05c.png)

What is wrong?

**Comment by rangav** [comment]
when defining the varaibles it should be just name `schema` not  `{{schema}}`, see below image

When using the variables then you need to use the format `{{schema}}`

<img width="1178" alt="Screenshot 2022-04-06 at 17 19 36" src="https://user-images.githubusercontent.com/8637550/162021238-b1777a75-05dd-4438-9571-b081dff8f054.png">

**Comment by econesag** [comment]
Okey, now it raises the next error:

Response Body schema is valid => Actual: error occurred while validating schema - strict mode: unknown keyword: "foo"

**Comment by rangav** [comment]
ok let me verify and get back to you

**Comment by econesag** [comment]
okey, I was testing and find my error, all the fields must be inside "properties" field. The schema must be like this:

{"properties": {"foo": {"type":"string"}, "bar":{"type": "boolean"}}}

**Comment by econesag** [comment]
Is it based on this documentation?

https://ajv.js.org/guide/getting-started.html

**Comment by rangav** [comment]
yes

I think the schema should be in this format
```
{
  type: "object",
  properties: {
    foo: {type: "integer"},
    bar: {type: "string"}
  },
  required: ["foo"],
  additionalProperties: false
}
```

**Comment by econesag** [comment]
perfect, I will improve my test now, thank you!

**Comment by rangav** [comment]
you are welcome, I am closing this now, feel free to re-open if needed
