### ISSUE TITLE
Version control of Collections

### ISSUE THREAD

**Issue by kclubbresideo** [rangav/thunder-client-support#538]
I cannot understand whether or not Thunder Client Environments and Collections are stored in such a what that they can be version controlled. I sometimes make changes but I can normally use git to recover my original settings. What is the model to use for a single developer to version control Thunder Client Collections?

**Comment by rangav** [comment]
Hi @kclubbresideo 

You need to enable vscode setting `Save To Workspace`

See details below
https://github.com/rangav/thunder-client-support#team
