### ISSUE TITLE
Auto load collections and envs from workspace folder or root location on first initialization of project

### ISSUE THREAD

**Issue by Caladbol** [rangav/thunder-client-support#539]
Hello, I saw that #62 suggestion got recently implemented in [v1.14.0](https://github.com/rangav/thunder-client-support/releases/tag/v1.14.0), with the possibility to bulk import files, but it would be nice if the extension could auto load those files when the project is opened for the first time, or at least offer the possibility in a warning box.

Suggestion: Allow Thunder Client to recognize and auto import files inside a custom workspace folder, or configuration files with a specific naming convention like (i.e. .thundercollections.json / .thunderenvs.json).

**Comment by rangav** [comment]
Hi @Caladbol 
Your question is not fully clear to me.

if you are looking for saving data to workspace and load automatically, see below
https://github.com/rangav/thunder-client-support#team

**Comment by Caladbol** [comment]
Hi @rangav , thanks for your quick reply, I see now how it works. It was an implementation problem on our side.
Sorry for the trouble.
