### ISSUE TITLE
Workspace Relative Path description not updated to reflect label change

### ISSUE THREAD

**Issue by Caladbol** [rangav/thunder-client-support#540]
**Describe the bug**
Load From Project setting name changed to Save To Workspace in [v1.14.0](https://github.com/rangav/thunder-client-support/releases/tag/v1.14.0), but not updated its name inside of Worspace Relative Path description.

![image](https://user-images.githubusercontent.com/74319532/162200635-68d07185-6d91-46fd-9934-6eba9ebed88c.png)

**To Reproduce**
Check VSCode Settings page for Thunder Client.

**Expected behavior**
Correct name display of option.

**Comment by rangav** [comment]
Thanks @Caladbol for reporting, I noticed that issue after publishing the release, will fix in the next update.

**Comment by Caladbol** [comment]
No problem, it's a small issue but got a few people confused here when setting a new workspace up.

**Comment by rangav** [comment]
This bug is is now fixed and published to marketplace as release version `v1.16.0`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.0
