### ISSUE TITLE
Import curl hotkey (ctrl-u) on OSX is bound to the qwerty layout

### ISSUE THREAD

**Issue by unyo** [rangav/thunder-client-support#542]
**Describe the bug**
Ctrl-U does not work if using the dvorak keyboard layout. Ctrl-G must be pressed instead.

**To Reproduce**
Switch to dvorak keyboard on OSX and try to pull up the import curl hotkey with Ctrl-U.

**Expected behavior**
Import curl prompt comes up.

**Platform:** 
 - OS: OSX 12.3.1
 - vscode version: 1.66.1
 - extension version: 1.16.0

**Comment by rangav** [comment]
Thanks @unyo reporting the bug, will look into it.

alternatively you can also use the menu in `active tab` for import curl

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace as release version `v1.16.2`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.2
