### ISSUE TITLE
thunder client is creating backup folder with db file and creating json file in root folder

### ISSUE THREAD

**Issue by yoyoy74662000** [rangav/thunder-client-support#543]
![image](https://user-images.githubusercontent.com/26075572/162526421-8773c8a9-96e0-4ee1-bc4a-e6b7f582cf48.png)

**Comment by rangav** [comment]
@yoyoy74662000 the new update released today have upgraded the the database files from .db files to json for better git merge and readability.

the old .db files moved to backup folder, in case if you like to rollback to previous version of extension 

you can check in both files now. In future you can delete backup folder.

details here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.0

**Comment by yoyoy74662000** [comment]
Thx
