### ISSUE TITLE
Error: No URL protocol specified

### ISSUE THREAD

**Issue by LaCocoRoco** [rangav/thunder-client-support#544]
When i am using "Generate New Token" VS Code throws following Error:

![image](https://user-images.githubusercontent.com/10038346/162533817-194021e4-ab76-44bd-baf1-d4e2931e4486.png)

This happens after the OAuth2 Redirect in the Browser with the URL: "http://localhost:6789/callback?code=SomeRanomNumber" and the Information "Success! Please close this tab." Probably The VSCode Thunder Client Extension does not know what to do with the callback, but i have no clue how to fix it. Someone has any idea?

**Comment by rangav** [comment]
Hi @LaCocoRoco 

can you share a screenshot of oauth 2 tab details 
With hiding any sensitive data

**Comment by LaCocoRoco** [comment]
Hi @rangav, thank you for this fast response!
Today i got more time to do some additional testing.
Probably i should have done this before writing an issues.
Sorry from my behalf!

I installed Thunder Client on my second workstation.
There everything worked as expected.
So i uninstalled VSCode and reset all Settings.
Afterwards the problem was fixed.

But, there is a second issues i thought about to ask.
I could close this issue an reopen a second one if this would be prefered.
I also use the Thunder Client Web Extension with [Code Server](https://github.com/coder/code-server).
I'm aware code server can't grab the callback from **https://www.thunderclient.com/oauth/callback**.
Is it possible to redirect the callback via reverse proxy to the code server instance,
so the thunder client can use the callback for the OAuth token?
Probably these functionality was never expected to be used with Code Server.

**Comment by rangav** [comment]
There is a local web server running, to get code from the callback. Not sure will it work on code server

Can you test on code server and let me know the error displayed.

**Comment by LaCocoRoco** [comment]
When i redirect the callback to the running code server instance via reverse proxy i get a "Bad Request" response in the browser. I have absolutly no idea how i have to configurate the running code server instance which is running on port 8080 to accept or handle these callback (Also i have no idea how code server and the extension handles such things, nor do i know how i could debug it). But it is possible to resend the code manually with a second request to the token url.

**Comment by rangav** [comment]
Super, good to know it’s working.

If pot can you provide steps how you resolved, so other can use them if they have similar issue.

**Comment by LaCocoRoco** [comment]
When the Thunder Client Extension is used in an Code Server Environment, it is not possible to use the Callback URL **https://www.thunderclient.com/oauth/callback**, because there is no local service running on port 6789. It is necessary to handle this via reverse proxy in the server environment. In this particular situation, i generated a DNS Zone on my provider with the url "https://thunder.client.mydomain.com" and created a caddy reverse proxy entry to the port 6789. At last i used "https://thunder.client.mydomain.com/callback" in the Thunder Client extension.

**Comment by rangav** [comment]
Thanks for sharing the steps 👍, really appreciate it. Will be very useful to others.
