### ISSUE TITLE
Add Additional Query Paramters to Generate New Token Advanced Options

### ISSUE THREAD

**Issue by LaCocoRoco** [rangav/thunder-client-support#545]
#### Is your feature request related to a problem? Please describe
Some OAuth2 application need additional query parameters to **Generate New Token**. For [Coinbase](https://developers.coinbase.com/docs/wallet/coinbase-connect/integrating) scope parameter **wallet:transactions:send** it is necessary to add additional [permission parameters](https://developers.coinbase.com/docs/wallet/coinbase-connect/permissions) like **meta[send_limit_currency]=USD**.

#### Describe the solution you'd like
Implementing the possibility to add query parameters into the Advanced Options.

#### Describe alternatives you've considered
As example the current workaround for this problem is to add the additional parameter into the scope: **wallet%3Atransactions%3Asend&meta%5Bsend_limit_amount%5D=1&meta%5Bsend_limit_currency%5D=USD&meta%5Bsend_limit_period%5D=day**

**Comment by rangav** [comment]
@LaCocoRoco  How you did in other api clients?

when workaround is getting the authentication sorted, why not continue the same?

because it’s not feasible to add fields specific to each oauth server

**Comment by LaCocoRoco** [comment]
I can't say how other api clients handled this problem, because it was a first with thunder client.
The workaround fullfils its purpose, so there is no reason to add a feature, but it is still a workaround.
An solution proposel from my side: Remove Audience and Resources from the OAuth2 tab in the Auth register and replace it with simple parameter & value fields. This would give a better flexibility and also fix this issues. This is no necessity and only was a proposel, so i will close this issues!

**Comment by rangav** [comment]
Thanks for the feedback will review it. 

You can also send normal request for oauth using form-encoded tab with required paramerters which is more flexible

**Comment by LaCocoRoco** [comment]
This sounds legit. If i am not mistaken a normal request does not redirect into a external browser window and only uses the internal response browser, which is only a problem if i use thunder client on code server because of internal reverse proxy problems.
