### ISSUE TITLE
Thunder client not handling large requests such as base 64 encoded image for facial recognition.

### ISSUE THREAD

**Issue by pavanblast** [rangav/thunder-client-support#546]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Solution:**

**Comment by pavanblast** [comment]
![IMG_20220411_212638.jpg](https://user-images.githubusercontent.com/24886495/162781642-362d8fde-7d04-49db-aa72-c3d5c9c51745.jpg)

**Comment by pavanblast** [comment]
Where you see cursor, there is actually request exists, but we are unable to see  that and response time is 17.43s. In some cases we don't get response at all.

**Comment by rangav** [comment]
Let me see if I understood correctly 

- you are using body `base64` image string in the post request 
- Sometimes you are not getting the response


So the issue is you are not getting response right?

What is the size of base64 image?

**Comment by pavanblast** [comment]
I am passing base 64 encoded code to request not an image.

**Comment by rangav** [comment]
Thanks, what is the `size` of base64 code?

**Comment by pavanblast** [comment]
150 KB.

**Comment by pavanblast** [comment]
Is it fixed?

**Comment by rangav** [comment]
Not yet, 

can you share a sample post data, that is causing the issue.

 Will try and fix it.

**Comment by rangav** [comment]
If you can share steps to reproduce the issue that will be useful to fix the issue.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open it if needed.
