### ISSUE TITLE
Need help, lost all requests

### ISSUE THREAD

**Issue by pazakharov** [rangav/thunder-client-support#547]
I have been using the client for a long time, this morning everything was ok. In the evening I opened it - there is no data, everything is gone, there are no collections, no requests. What can I do? where is information stored?
I see only this:
```
No Collections Available...
You can create collections here.
```..

**Comment by rangav** [comment]
Hi @pazakharov 

the data is stored in default location?

are you using Mac or pc?

did you change any thunder client settings?

**Comment by pazakharov** [comment]
@rangav, thx for you replay.
I use PC win10, I didn't change any settings.
I try to find any "thunder" files,  found only `\AppData\Roaming\Code\User\globalStorage\rangav.vscode-thunder-client`
I found the backup directory, it looks like some of my data is there. Can I restore backup to json settings?

**Comment by pazakharov** [comment]
v1.16.0
in backup dir i see *.db
in rangav.vscode-thunder-client dir *.json 
I tried to rename but it didn't work.
i tried to make a valid json from db strings, but that didn't work either (

**Comment by korwalskiy** [comment]
@rangav I am having same issues on Mac Big Sur. I can't find the .db or .json files anywhere searching for `vscode-thunder-client` in `/usr` or `/Users`

Can you give some itemized steps to follow when these things happen for others like myself that run into these issues

**Comment by rangav** [comment]
Hi @korwalskiy are you using pc or mac?

**Comment by rangav** [comment]
on PC
`%APPDATA%\Code\User\globalStorage\rangav.vscode-thunder-client`

on Mac
`/Users/{{userName}}/Library/Application Support/Code/User/globalStorage/rangav.vscode-thunder-client/`

replace {{username}} with yours

**Comment by jtsom** [comment]
This? 
![image](https://user-images.githubusercontent.com/13488/166545359-7706f896-8503-4bd5-ab1e-46845998a69d.png)

**Comment by sid-the-sloth** [comment]
In case anyone uses this extension in VSCodium under GNU/Linux, the storage path for collections, environments and responses is here:

```
$HOME/.config/VSCodium/User/globalStorage/rangav.vscode-thunder-client/
```
