### ISSUE TITLE
Support env on Basic Authentication

### ISSUE THREAD

**Issue by rya112** [rangav/thunder-client-support#549]
Today is not possible use envs on Basic Authentication params

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1384851/163036042-a9984efd-b565-44d9-9326-b6f091b9d631.png">

**Comment by rangav** [comment]
Hi @rya112 

Env variables will mostly everywhere in the request. see below screenshot 

<img width="1183" alt="Screenshot 2022-04-12 at 20 29 07" src="https://user-images.githubusercontent.com/8637550/163039185-6643e90a-3d9b-48d6-849f-1c25d88052b4.png">

Make sure you activated the environment by using `Set Active `

**Comment by rangav** [comment]
I am closing this issue, feel to re-open if needed
