### ISSUE TITLE
Show "Test Results" count in red if a test fails

### ISSUE THREAD

**Issue by wildhart** [rangav/thunder-client-support#55]
If a test fails, could the test count in the "Test Results" tab be red instead of blue, so we only need to look at the test results if there is a problem?

![image](https://user-images.githubusercontent.com/12505024/116021735-deeb3e80-a69c-11eb-963a-bf3ad54753fa.png)

**Comment by rangav** [comment]
Hi @wildhart will add this to roadmap.

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14
