### ISSUE TITLE
nodemon server restarting on every requeset

### ISSUE THREAD

**Issue by S-STALWART-S** [rangav/thunder-client-support#551]
**Describe the bug**
I have issue when using nodemon. after send any request server restarting over and over. I also tested with postman and web browser and there is no problem. I dont know what cause the problem but two month ago i didnt have this problem, so i installed older version (1.10.0).
now its working as normal. 

**Platform:** 
 - OS: Linux kubuntu 20.04 and 22.04
 - vscode version: 1.66.2
 - extension version: 1.16.2

**Comment by rangav** [comment]
Thanks @S-STALWART-S for reporting the issue.

can share a sample mini nodemon project that I can use to reproduce the issue. Will be useful for investigating the issue.

**Comment by rangav** [comment]
One more question where are you saving thunder client requests data 

- is it in default location or in your current workspace?

**Comment by S-STALWART-S** [comment]
here is my project:
https://github.com/S-STALWART-S/teletalk-server

Im using current workspace directory. new version of thunder-client using .json files, right?

I ignored thunder-tests directory and its working fine now. This is not thunder-client problem, Sorry I created this

**Comment by rangav** [comment]
Thanks for confirmation 

did you ignore `thunder-tests` from git or from nodemon?

**Comment by S-STALWART-S** [comment]
I ignored from nodemon. 
script:
```cross-env NODE_ENV=development nodemon --ignore ./thunder-tests --trace-warnings ./src/server.js```

**Comment by rangav** [comment]
Thanks for confirmation 👍

Closing the issue now
