### ISSUE TITLE
Invalid characters in URL when pass percentages as query string

### ISSUE THREAD

**Issue by leandroluk** [rangav/thunder-client-support#552]
**Describe the bug**
I'm building an API using node with express and it has a GET route as shown in the example below:

```bash
curl -X GET "localhost:3000/todos?description__like=%description%"
```

Upon receiving the request below from CURL, express is able to parse the req.query property for the following result:

```json
{ "description__like": "%desc%" }
```

But if I make the same request using thunder-client it returns the following object:

```json
{ "description__like": "%desc%25" }
```

**To Reproduce**
> node: you will need nodejs and vscode installed...

Create any simple project with node and install express deps like this:

- Open any folder in terminal and run `node init -y`
- Open folder with project (you can use the command `code FOLDER_NAME`)
- In terminal, install express with command `npm add express`

Create a minimal express api with this code:

```javascript
// index.js
require('express')()
  .get('/', (req, res) => res.json(req.query))
  .listen(3000, () => console.log('running on port 3000))
```

Start project with command `node ./index.js` and make a request with the url `http://localhost:3000?foo=%bar%` using the thunder client. You can see that the parsing done by express is wrong because the sent url is different.

Now make the same request using curl to see the result (command: `curl -X GET "http://localhost:3000?foo=%bar%`). The express parser will be correct as sent. If the request comes from the browser (tested in Chrome) it is also parsed correctly

**Expected behavior**
It was expected that the parsing result of express when receiving the request via curl would be the same as when receiving via thunder-client as it is for the browser

**Platform:** 
 - OS: Windows
 - vscode version: 1.66.2
 - extension version: 1.16.2

**Solution:**
Check for any interpolation or method that is incorrectly converting characters by adding the number 25 at the end

**Comment by rangav** [comment]
Thanks @leandroluk for reporting the bug, will look into it.

**Comment by rogueturnip** [comment]
I have the same issue with a QP like ?email=test+1@test.com

Looks like the QP's aren't being url encoded correctly.

**Comment by rangav** [comment]
Thanks @rogueturnip for reporting the issue.  

Can you please share full url?

**Comment by rangav** [comment]
Hi @rogueturnip the plus sign wont be encoded it is treated as space which how browser will handle it.

`https://httpbin.org/anything?email=test+1@test.com`
you can test yourself by opening above url in chrome

To send `+` sign user needs encode the plus sign with `%2B`

**Comment by rogueturnip** [comment]
Thanks.  All good.  I just have to make sure to encode the email before sending.

**Comment by rangav** [comment]
This bug is now fixed and please update to `v1.16.3`

See all features & bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.3

**Comment by usimarit** [comment]
> Hi @rogueturnip the plus sign wont be encoded it is treated as space, which is how browsers will handle it.
> 
> you can test yourself by opening this url in chrome https://httpbin.org/anything?email=test+1@test.com
> 
> To send `+` sign user needs encode the plus sign with `%2B`

Is there any plan to auto encode query parameters before sending, or on query params input, or have a button to enable query params encoding? Manually encode the query parameters is not UI friendly.
I still have to manually encode the parameters and copy to the client, in version v1.16.7, which takes lots of time.
I see in postman or insomnia they encode the params before merging them with the url, which makes things work.

**Comment by rangav** [comment]
Hi @usimarit thanks for the feedback 

can you please create a new feature request for this, will add to roadmap

**Comment by usimarit** [comment]
> Hi @usimarit thanks for the feedback
> 
> can you please create a new feature request for this, will add to roadmap

Thanks @rangav, I just make a feature request here #678
