### ISSUE TITLE
Rate limit when running all requests in a collection

### ISSUE THREAD

**Issue by wildhart** [rangav/thunder-client-support#56]
When Running All request/test in a collection, could we have a configurable delay between each request to avoid rate limits?

![image](https://user-images.githubusercontent.com/12505024/116022637-a6e4fb00-a69e-11eb-833a-107a55c4f040.png)

**Comment by rangav** [comment]
Hi @wildhart will add this to roadmap.

**Comment by rangav** [comment]
Hi @wildhart the requests are now running in sequence(earlier they run in parallel),  does it solve the issue?

**Comment by wildhart** [comment]
@rangav, no it wont.  One of the API's I'm working with have a rate limit of one GET every 5 seconds (!) shared across all endpoints, so I would need to put a 5 second delay between each request.

**Comment by rangav** [comment]
Ok got it, will provide vscode setting for request delay, do you want it in seconds or milliseconds?

**Comment by rangav** [comment]
may be millisecs would be more configurable to everyone.

**Comment by wildhart** [comment]
Yep, I was thinking milliseconds would be best 👍

**Comment by wildhart** [comment]
Would the setting be editable from the "Run All" page, or would you have to go to the Settings page each time?

Having it on the "Run All" page would make it more visible (fewer duplicate bug reports!) and make it easier to change for different API's.  Ideally different delays could be saved for each project.

**Comment by rangav** [comment]
@wildhart  Yes you are right, I was thinking the same vscode setting might not be that useful, I will provide this in the folder or collection level setting.

**Comment by LiveFreeAndRoam** [comment]
I have Thunder Client v1.9.1 from August, yet I cannot find this feature for injecting a delay between tests.  Am I missing it?  I looked on the "Run All" and also the "Collection > Settings" as well as the VSCode settings.

**Comment by rangav** [comment]
Hi @LiveFreeAndRoam this feature not yet implemented, planning to include this in the next update.

**Comment by rangav** [comment]
related #95

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
