### ISSUE TITLE
OAuth 2 Generate Token issue?

### ISSUE THREAD

**Issue by tony-belfiore-red-sail** [rangav/thunder-client-support#561]
I am using Thunder Client v1.16.2, and I am trying to generate an OAuth token from Collection Settings. 

I set up all of my properties

- Token Prefix: Bearer
- Grant Type: Authorization Code
- Auth Url
- Auth Url
- Callback Url
- Client Id
- Scope
- Send Auth: As Auth Header

When I hit the "Generate Token" button a browser tab opens and I successfully log in with my credentials. Everything looks great.

Based on the Thunder Client text that says "The generated oauth token will be automatically added to Autorization header", I would expect for my token to be used, but it is not. And the "Access Token" field in the Thunder Client screen still looks empty. Should it now have a value if everything worked? 

I also looked in the Thunder Client "Output" window and see no errors.

Am I doing something wrong or is this a limitation of Thunder Client?

**Comment by tony-belfiore-red-sail** [comment]
![image](https://user-images.githubusercontent.com/91634526/164235627-66774c3f-291e-49f1-b926-39f7ec67c0f8.png)

**Comment by rangav** [comment]
From the screenshot client secret is missing?

try change the `Send Auth` option to `as Auth Body`

**Comment by tony-belfiore-red-sail** [comment]
There is no client secret.

It works in Postman as Auth Header.

I tried your suggestion. Still does not work.

**Comment by rangav** [comment]
For callback url, use the default url provided by the extension, because the callback needs to forward the code back to extension.

**Comment by tony-belfiore-red-sail** [comment]
Hmmm... then this might be an issue for me. Postman allows us to specify our own callback url. I tried using the ThunderClient callback Url but our systems here prevent it.

Here is the Postman Callback Url text
<img width="424" alt="image" src="https://user-images.githubusercontent.com/91634526/164240374-76f31c2c-2d5c-4919-89dd-abb57501eb77.png">

**Comment by rangav** [comment]
Ok then, your callback url needs to forward the code to below url in the specific format 
http://localhost: 6789/?code=codevalue

then the extension can access the code to request access token

**Comment by mgross-ebner** [comment]
I'm not able to auth with our Keycloak server, it always gives me a "not found"

![image](https://user-images.githubusercontent.com/89461948/164413161-556d83a5-bbcd-4ae8-a5d7-2f59c1ef260a.png)
![image](https://user-images.githubusercontent.com/89461948/164415469-eef8920a-8ba1-4e1c-ad75-c638c15bdb3a.png)

**Comment by rangav** [comment]
You should use your own callback url and 

that callback url should forward the code this localhost url

you got it?

**Comment by mgross-ebner** [comment]
I'm sorry, but I don't get it. 😢 

How should the code be forwarded? Currently it's "forwarded" as query parameter to `http://localhost:6789/?code=...`.

The only difference is the empty state query parameter...

**Comment by rangav** [comment]
ok let me test here and get back to you with the steps.

**Comment by mgross-ebner** [comment]
Thank you so much! Now it works!

**Comment by rangav** [comment]
Super thanks for confirmation 👍

you can close the issue if all sorted

**Comment by tony-belfiore-red-sail** [comment]
It worked for e too. 
Thank you so much!
