### ISSUE TITLE
setTo Global variables to null from tests tab

### ISSUE THREAD

**Issue by JuanRodriguezAbarca** [rangav/thunder-client-support#562]
In order to have the ability of cleaning Global Variables, would be nice to have the possibility to set the Global Variables using setTo to null value or "". As well would be usefull the possibility of set hardcoded/modified value instead of using any response value as it comes.

Thank you very much in advance, best regards, Juan

**Comment by rangav** [comment]
Thanks @JuanRodriguezAbarca for creating the feature request, will implement in the next update.

**Comment by spali** [comment]
Question from my side. I can solve my use case with this to, but maybe if @JuanRodriguezAbarca had the same in mind, there would be a cleaner solution...
My use case is to use variables in "Test Suites" (folders with multiple requests in sequence) which uses variables to store temporary information for the next test. These variables are only required during a single run of the tests and can then be thrown away.
What I don't like currently is, that these variable values gets saved and clutters the saved enviroments. 
With the above solution I could clean them up in the last request.
But I would prefer kind of "Run Environment" scope which only exist during the Run of the folder or a single test. These could be kept in the result for debugging, but not saved in any other environment.

Would that match here?

**Comment by rangav** [comment]
Hi @spali you request is similar case.

we have a local environment feature, you can use it to save any variables so they are not saved in the main environment file. They are saved locally on your in separate location 

Let me if this is useful to you?

**Comment by spali** [comment]
Hi @rangav 

Thanks for the feedback. Actually I already use the local environment for these kind of variables. But still doesn't feel god to save something, that's actually only wanted temporary. With this feature request solved, I could at least clean up manually.

My idea was more of an additional  "run only" scoped environment that is only hold in the memory and latest thrown away at a subsequent run or closing the test run.
The biggest advantage for testing would be, that this ensures to not leak a test result into the next test and maybe affect the test result unexpectedly. 
The same could happen when running multiple different testset's or even projects, which shares variable names.

**Comment by JuanRodriguezAbarca** [comment]
The idea is to be able to overwrite global variables with an input which is not taken from the json.response. Setting the value to an empty string or any other value (even hardcoded). It would be a nice achivement while we can't pre process or post process the requests.

Thank you!

**Comment by rangav** [comment]
Hi All, can you let me know any feedback on this.

Is it working as you expected?
