### ISSUE TITLE
Path Variables are deleted whenever url is modified

### ISSUE THREAD

**Issue by Zizaco** [rangav/thunder-client-support#563]
**Describe the bug**
The **values** of the [Path Variables](https://github.com/rangav/thunder-client-support#path-variables) disapear when anything changes in the url.

![path_variable_value_disapear](https://user-images.githubusercontent.com/777635/164276770-5f7f80c2-ff0c-4af3-9cfb-ea6c3b234b8f.gif)

**To Reproduce**
1. In a Request to an url with path variables (ex:`path/{variable}`)
2. Go the the Query tab
3. Set the path variable
4. Change anything (beginning, end, anywhere) on the url
5. ⚠️ All path variable values disapear

**Expected behavior**
The path variable values should remain defined unless the name of the slots change. 

_(improvement suggestion)_ thought it would be nice if Thunder memorizes the values even if the slot name changes, so that if we type a previous slot name, the value is still there.

**Platform:** 
 - OS: Ubuntu 20.04
 - vscode version: 1.66.2
 - extension version: 1.16.2

**Solution:**
The values of the path variables should remain defined even if the URL change.

**Comment by rangav** [comment]
Thanks @Zizaco for reporting the bug, will look into it.

**Comment by rangav** [comment]
This bug is now fixed, please update to version `v1.16.4`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.4
