### ISSUE TITLE
Authorization header key being sent with lowercase A for PUT, PATCH

### ISSUE THREAD

**Issue by jim-pickering** [rangav/thunder-client-support#564]
Using a PATCH endpoint, the Authorization header key with the jwtToken is being sent with a lowercase A, which causes the Node API call to not run. When using Postman, the same call gets an uppercase A for the Authorization header key, and it works. Doesn't matter for GET or POST, but it matters for PUT and PATCH. Anyone else seeing this?
```
headers:{user-agent: 'Thunder Client (https://www.thunderclient.com)', accept: '*/*', authorization: '...', accept-encoding: 'gzip, deflate, br', Host: '127.0.0.1:3010', …}
httpMethod:'GET'
isOffline:true
multiValueHeaders:{user-agent: Array(1), accept: Array(1), authorization: Array(1), accept-encoding: Array(1), Host: Array(1), …}
multiValueQueryStringParameters:{page: Array(1), type: Array(1), limit: Array(1), sort: Array(1)}
path:'/dealers'
pathParameters:null
paths:{}
queryStringParameters:{page: '1', type: 'dealer-list', limit: '20', sort: 'name:asc', filter: 'all', …}
requestContext:{accountId: 'offlineContext_accountId', apiId: 'offlineContext_apiId', authorizer: {…}, httpMethod: 'GET', identity: {…}, …}
resource:'/dealers'
routePath:'/dealers'
stageVariables:null
__proto__:Object
accept:'*/*'
accept-encoding:'gzip, deflate, br'
authorization:'...'
Connection:'close'
Host:'127.0.0.1:3010'
user-agent:'Thunder Client (https://www.thunderclient.com)'
```

**Comment by rangav** [comment]
Hi @jim-pickering thanks for reporting the issue.

are you sending the Authorization manually using the headers tab?

if possible can you share a screenshot of headers tab with hiding any `sensitive` data

**Comment by rangav** [comment]
there is a vscode setting to send header is case-sensitive format. please enable it and try again.
<img width="811" alt="Screenshot 2022-04-25 at 15 40 44" src="https://user-images.githubusercontent.com/8637550/165112646-d1d03fe4-81c0-480a-b076-0fd9494c74ee.png">
