### ISSUE TITLE
File Upload on remote server

### ISSUE THREAD

**Issue by anoirak** [rangav/thunder-client-support#565]
**Describe the bug**
When you are ssh connected to a server and want to send a file in a request , the extension shows local files instead of remote files.

**Comment by rangav** [comment]
Hi @anoirak you need to add vscode setting for remote files to work

see this comment https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by januwA** [comment]
I have this problem too, because I always work in a virtual machine

**Comment by rangav** [comment]
Hi @januwA you need to add vscode setting for remote files to work

see this comment https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
