### ISSUE TITLE
Docs don't get saved after edit until Send is pressed again

### ISSUE THREAD

**Issue by reinux** [rangav/thunder-client-support#567]
**Describe the bug**

Docs don't get saved after editing and hitting Done. Need to press Send before it saves to the json file.
**To Reproduce**

- Edit Docs
- Press Done
- Check thunderclient.json or restart vscode and open the same Docs again -- it isn't saved.
- Edit Docs, press Done, press Send
- Check thunderclient.json or restart vscode -- it is saved.

**Expected behavior**

Save immediately upon pressing Done.

**Platform:** 
 - OS: Win 11
 - vscode version: 1.66.2
 - extension version: 1.16.2

**Solution:**

**Comment by rangav** [comment]
Thanks @reinux for feedback, will implement in the next update.

**Comment by rangav** [comment]
This bug is now fixed, please update to version `v1.16.4`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.4
