### ISSUE TITLE
cookie disappears after first request

### ISSUE THREAD

**Issue by MasterIfeanyi** [rangav/thunder-client-support#568]
**Describe the bug**
I am working on a REST API, with a sign-up and log-in functionality, when I make a request to `/login` cookie is sent along, but on the second request to another route `/refresh` to request for a new accessToken, the cookie is not sent along.

**To Reproduce**
when a user log-in `res.cookie("jwt", refreshToken, {httpOnly: true, maxAge: 24 * 60 * 60 * 1000 })` and then in another `/refresh`, check for the presence of any cookie `const cookie = req.cookie; console.log(cookie)`

**Expected behavior**
I am supposed to get a cookie on the `/refresh` route handler so that I can make a request for a new accessToken.

**Platform:** 

- OS: Window 10
- vscode version: 1.66
- extension version: 1.16.2

**Comment by rangav** [comment]
Thanks @MasterIfeanyi for reporting the bug, will look into it.

**Comment by rangav** [comment]
@MasterIfeanyi when the login cookie expires? can you share the screenshot of `cookies` tab of `login` request, you can hide any sensitive data.

**Comment by rangav** [comment]
closing this issue, feel free to re-open if needed.

**Comment by dhiegomaga** [comment]
> when I make a request to /login cookie is sent along, but on the second request to another route /refresh to request for a new accessToken, the cookie is not sent along

This is sentence is quite hard to understand, but I guess I could say I have the same issue: 

When you send a request to say, `/login`, the `cookie` is successfully received by Thunder Client (ie, the cookie appears on the `Response Cookies` tab of the response). However, subsequent requests to the same domain do not include the cookie that was received. That means, the cookie is not being saved/set/resent by thinderclient, but it should, as any browser would (and Postman also does it automatically).

**Comment by MasterIfeanyi** [comment]
> > when I make a request to /login cookie is sent along, but on the second request to another route /refresh to request for a new accessToken, the cookie is not sent along
> 
> This is sentence is quite hard to understand, but I guess I have the same issue:
> 
> When you send a request to say, `/login`, the response contains a `cookie`, which is successfully received by Thunder Client (ie, the cookie appears on the `Response Cookies` tab of the response). However, subsequent requests (made with thunderclient) to the same domain **do not include the cookie that was received**. That means, the cookie is not being saved/set/resent by thinderclient, but it should, as any browser would (and Postman also does it automatically).
> 
> Edit: Nevermind, the cookie was being sent on the `req.headers.cookie`, but I was looking in the wrong place. Now it works for me

This guy gets it.
