### ISSUE TITLE
Typo in Thunder Client test response

### ISSUE THREAD

**Issue by stefanstranger** [rangav/thunder-client-support#569]
![Thunderclient_error](https://user-images.githubusercontent.com/2125385/165108341-dd929770-a66e-4369-b53a-4bf08a765e76.png)

**Comment by rangav** [comment]
Thanks @stefanstranger for reporting, will fix in the next update

**Comment by rangav** [comment]
This bug is now fixed and please update to `v1.16.3`

See all features & bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.3
