### ISSUE TITLE
Test action "matches regexp"

### ISSUE THREAD

**Issue by wildhart** [rangav/thunder-client-support#57]
Being able to match a body or json.query against a regular expression would be really useful in tests.

Currently string tests are limited to "equals" and "contains".

PS, I love what you've done with Thunder Client, it's awesome, well done!

**Comment by rangav** [comment]
Hi @wildhart Glad to know you like Thunder Client, Will add this also to roadmap.

**Comment by rangav** [comment]
HI @wildhart

Can you provide couple of examples how you envision this to work?

**Comment by wildhart** [comment]
I've some requests where the response is similar to the below:
![image](https://user-images.githubusercontent.com/12505024/120693854-a6414f00-c4fd-11eb-8bd8-e37b8b08b0d1.png)

I had some tests to check that the `json.message` included various key strings:
![image](https://user-images.githubusercontent.com/12505024/120694224-0cc66d00-c4fe-11eb-93ae-c06bfd7861af.png)

I was simply looking for a way to combine these into a single test such as `action = regex`, `value = ^Hi {{userName}}.*OUT.*{{location}}`, where variables are replaced before the regex is executed.

To be honest though, it's not that much of a time saving so feel free not to bother.

However, I would expect the following simple `contains` test to work:
![image](https://user-images.githubusercontent.com/12505024/120694700-9fffa280-c4fe-11eb-9c71-1338966d37fa.png)
But it doesn't substitute variables mid-string:
![image](https://user-images.githubusercontent.com/12505024/120694795-b574cc80-c4fe-11eb-8dc6-030132eb36ba.png)

**Comment by rangav** [comment]
Ok then will leave out regex for now.

i will test the mid-string replace and get back to you.

**Comment by rangav** [comment]
Hi @wildhart Test the mid-replace string, it does not work, its a bug, I will fix in the next update.

**Comment by rangav** [comment]
HI @wildhart the mid-replace bug is fixed in v1.4.1

**Comment by rangav** [comment]
Regex match feature is now implemented in v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

please let me know if any feedback
