### ISSUE TITLE
Avoid using `ctrl+shift+R` as the thunder client shortcut

### ISSUE THREAD

**Issue by tusharsadhwani** [rangav/thunder-client-support#570]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> is reserved for "Refactor code" by VSCode, consider changing your shortcut to avoid overriding it.

**Comment by tusharsadhwani** [comment]
@rangav my bad, it's ctrl+shift+R that's used by VSCode, not T.

**Comment by rangav** [comment]
@tusharsadhwani please open keyboard shortcuts from command pallete and you can modify the keys that’s suits you.

because if I change to different shortcut still it will mix up with some existing shortcut

**Comment by tusharsadhwani** [comment]
@rangav then maybe remove a default shortcut completely, and let the users choose it according to their convenience

**Comment by rangav** [comment]
The shortcut was created for a feature request by another user https://github.com/rangav/thunder-client-support/issues/342

Very few seems to have problem with this shortcut, so it should be fine.

**Comment by rangav** [comment]
there might be lot of users who already using this shortcut, Changing this now will cause more issues

**Comment by rangav** [comment]
closing this issue, feel free to re-open if needed.
