### ISSUE TITLE
How to get csrf-token value from server?

### ISSUE THREAD

**Issue by memiljamel** [rangav/thunder-client-support#572]
Hi, I just used Thunder Client. Here I am having trouble setting the csrf-token which is obtained from the server automatically (in postman as dynamic value). How can I do something similar with Thunder Client?

**Comment by rangav** [comment]
@memiljamel if the token is generated from the api request, then you can save to environment variable and use in the next request 

Details here how to save to variable 
https://github.com/rangav/thunder-client-support#setenv

**Comment by rangav** [comment]
@memiljamel closing this question, feel free to reopen if needed

**Comment by ai-mine-max** [comment]
Tried performing CRUD operations in spring boot3 and always got Invalid CSRF Token when posting. The GET request seem to be fine.

**Comment by coreymunn3** [comment]
@rangav the link to set env appears to be broken. Can you please explain how to link an env var to a request in the docs? I've been trying to figure this out for a while and it's not obvious in the UI. I'm getting invalid csrf token errors in all of my  PUT and POST requests

**Comment by rangav** [comment]
Updated link

https://docs.thunderclient.com/testing/set-env
