### ISSUE TITLE
Not able to save env var

### ISSUE THREAD

**Issue by Crafty06** [rangav/thunder-client-support#575]
**Describe the bug**
Hi, I just transferred my Requests and vars from my Laptop to my pc.
Since then I can`t save any data to env vars over tests. It always fails and says:
"Set Env Failed: Please create environment first from Env tab"
It even continues to say it, with new requests and new vars

**To Reproduce**

1. Export and then import requests and env.
2. Try to save json data in var over test

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.66.2
 - extension version: 1.16.2

**Comment by rangav** [comment]
Thanks @Crafty06 for reporting the bug, will look into it.

**Comment by Crafty06** [comment]
Hi, just found the answer to the problem.
I just had to attach the env to the collection over the settings.
Thanks for the fast response
