### ISSUE TITLE
Allow to hide ".sec-line" divs (last usage time) via extension settings

### ISSUE THREAD

**Issue by RollingHog** [rangav/thunder-client-support#577]
**A problem** is that every line in requests list takes up too much space on screen. In postman, for example, they are much more condensed.

A **solution** I want to ask for is to add a checkbox in `Extension Settings` called something like `Compact mode`, which will hide divs with class ".sec-line" in requests list and maybe reduce padding

An **alternative solution** I use now is applying custom CSS via dev tools, but this is clearly not very comfortable.

**Comment by RollingHog** [comment]
Thanks a lot. Any ETAs?

**Comment by rangav** [comment]
ETA could be end of next month. If it’s possible to implement earlier I will post update here.

**Comment by RollingHog** [comment]
Okay, thanks.

**Comment by rangav** [comment]
@RollingHog one question 

are you using activity tab or collection tab for requests?

**Comment by RollingHog** [comment]
@[rangav](https://github.com/rangav) Collection tab

**Comment by rangav** [comment]
If you group the requests in folders in collection then you minimize/maximize folders, then it won't take much space.

**Comment by JLCareglio** [comment]
🤗 I love ThunderClient, it's a powerful tool while having a simple and clean design 👍

I work with the Collections Tab to save space but I would like to be able to hide the "time details"

Is this feature request totally ruled out?

**Comment by rangav** [comment]
@JLCareglio will include in the next update

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.1

There is a new vscode setting `Hide Date Modified`

Please let me know your feedback.

**Comment by rangav** [comment]
This setting has been renamed to `Sidebar Layout` in `v2.8.0`
