### ISSUE TITLE
Support use of variables in URL's scheme, host and port

### ISSUE THREAD

**Issue by chakrayadavalli** [rangav/thunder-client-support#578]
**Is your feature request related to a problem? Please describe.**
Presently the env variables are not supported in the URL scheme (http or https), host and port.

**Describe the solution you'd like**
It would be nice to have scheme, host and port externalized as variables so that the same collection could be used for testing in different environments such as LOCAL, DEV, QA, UAT and PROD. 
The developer's env may not have https and cloning the collection just to change the host names is cumbersome.

**Describe alternatives you've considered**
1. Manipulate /etc/hosts to map a host name to one of the hosts of different env in which you want to test the API.
2. Use HTTP Reverse Proxy to use use the scheme appropriate for the env and route the requests to the host of that env.
3. Scripting is something to be considered but I am not familiar with it. 

**Implementation:**
I think this implementation should be similar to that of the URL path variables.

**Comment by rangav** [comment]
Hi @chakrayadavalli this feature is already supported, did you try?

**Comment by chakrayadavalli** [comment]
My bad. I think the env file was not saved. Sorry about that.
