### ISSUE TITLE
Thunder client not loading vscode 1.66.2

### ISSUE THREAD

**Issue by Vincent-HD** [rangav/thunder-client-support#579]
Thunder client do not load when clicking on the tab menu

**Platform:** 
 - OS: 
 - vscode version: v1.66.2
 - extension version: v1.16.2

**OUTPUT**
```
[exthost] [error] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $.read (c:\Users\Vincent\.vscode\extensions\rangav.vscode-thunder-client-1.16.2\dist\extension.js:1:363335)
    at K.read (c:\Users\Vincent\.vscode\extensions\rangav.vscode-thunder-client-1.16.2\dist\extension.js:1:368148)
````

**Comment by Vincent-HD** [comment]
Rolled back to vscode 1.65, still having issue.
The extension only works when I rollback to 1.14.4, but idk if I should use it, my collections is more recent than this version

**Comment by rangav** [comment]
Hi @Vincent-HD thanks for reporting the issue, 

what is previous version of vscode where the extension was working before you upgraded the vscode?

**Comment by jmlane** [comment]
I'm having the same issue. I suspect it's because I had large requests saved in the old DB format and the migration to the new DB format was failing.

I rolled back to 1.14.4 to get the extension to work again. All my saved data is gone. When I update to 1.16.2 at this point, it works as expected.

**Comment by rangav** [comment]
Did you manually change json files? 

when you first upgraded to new db format, did it work?

**Comment by xshi3x** [comment]
I don't think any files were modified manually. 
Because I also encountered the same problem after the automatic upgrade。

**Comment by Vincent-HD** [comment]
Sorry for the late answer, the only thing I did is to transfer my collection from the global configuration files (json etc...) to the workspace config (I didn't know that we could do that before starting).

I noticed that the extension doesn't work on new workspaces (empty, without any collection), when I open the project where I transferred the collection to, it works fine, so I guess I maybe made a mistake, I'll try to reset all files when I'll have some time (stills weird because the error is on a dist file from the extension)

**Comment by rangav** [comment]
@Vincent-HD 

The requests data should be in below default location

on PC
`%APPDATA%\Code\User\globalStorage\rangav.vscode-thunder-client`

on Mac
`/Users/{{userName}}/Library/Application Support/Code/User/globalStorage/rangav.vscode-thunder-client/`

replace {{username}} with yours

you can copy the data files to new workspace location

don’t copy the `thunderLocalEnvironment`

**Comment by rangav** [comment]
closing this issue, feel free to re-open if needed.
