### ISSUE TITLE
Cannot test is equal to env variable

### ISSUE THREAD

**Issue by wildhart** [rangav/thunder-client-support#58]
**Steps to reproduce:**
1. Set an environment variable to a string you'd expect in the json response
2. Create a test with "equal" and value {{your_env_var}}

Test fails.  E.g.:

![image](https://user-images.githubusercontent.com/12505024/116028663-c33b6480-a6ab-11eb-91f1-dc27222d1147.png)

![image](https://user-images.githubusercontent.com/12505024/116028709-e0703300-a6ab-11eb-8b8b-8d15925f618e.png)

![image](https://user-images.githubusercontent.com/12505024/116028767-fbdb3e00-a6ab-11eb-92e6-4cff04cc9a53.png)

**Comment by rangav** [comment]
Hi @wildhart i will test and fix this, thanks for reporting.

**Comment by rangav** [comment]
Hi @wildhart this is now fixed, will be part of next update v1.1.0, more details here - #14

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14

**Comment by hecmondev** [comment]
This issue is happening again:

![image](https://user-images.githubusercontent.com/96672315/219957021-8fcb5b0e-d614-41b1-bd6d-5fff93b49c60.png)

my installed version:

![image](https://user-images.githubusercontent.com/96672315/219957055-bf1660a0-9d4a-497f-8fbf-e2d205c1bb39.png)

**Comment by rangav** [comment]
@hecmondev thanks for reporting, let me verify and get back to you.

Did you set active environment?

**Comment by hecmondev** [comment]
yes @rangav this is my current env that i'm using:

![image](https://user-images.githubusercontent.com/96672315/219958513-902b1d0b-6e06-4673-83ed-ae6c868b93db.png)

this looks active.

**Comment by rangav** [comment]
no - you need to create normal environment . 

Currently you only created Local Environment.

<img width="252" alt="Screenshot 2023-02-19 at 15 45 15" src="https://user-images.githubusercontent.com/8637550/219958666-1df94efb-05fc-4fa0-b9e4-64433b4703dc.png">

if you like set env variable and save to local env then use this format `{{variable, local}}`

see docs here
https://github.com/rangav/thunder-client-support#environments

**Comment by rangav** [comment]
Active Environment will have `star` beside it.
<img width="266" alt="Screenshot 2023-02-19 at 15 48 00" src="https://user-images.githubusercontent.com/8637550/219958799-167af117-5f28-4c14-8a64-9a0cbbfde6ff.png">

**Comment by hecmondev** [comment]
Oh man sorry @rangav my bad surely, i'll check what you're saying ty for your answers!

**Comment by rangav** [comment]
no problem @hecmondev, feel free to reach out if you have any further questions.
