### ISSUE TITLE
{{#string}} variable does not work as expected

### ISSUE THREAD

**Issue by sindhu-bytebeam** [rangav/thunder-client-support#580]
**Describe the bug**
`{{#string}}` does not generate random string, it generates random guid (same as doing `{{#guid}}`

**Comment by rangav** [comment]
Hi @sindhu-bytebeam thanks for the feedback.

currently `{{#string}}` also generates random guid.

Will update in the next release

**Comment by rangav** [comment]
This bug is now fixed and please update to `v1.16.3`

See all features & bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.3
