### ISSUE TITLE
Thunder Client forever updating database

### ISSUE THREAD

**Issue by jtsom** [rangav/thunder-client-support#581]
Tried to load Thunderclient and the panel shows "Upgrading database please wait..." and nothing else is happening.

![image](https://user-images.githubusercontent.com/13488/166514555-3610f57c-8717-4d8d-a8bd-90793a3d9496.png)

There are no errors or messages in the developer tools console.

**To Reproduce**

Open VSCode. Click Thunderclient icon.

**Expected behavior**

Thunderclient panel shows previous requests.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.67.0-insiders
 - extension version: 1,.16.2

**Solution:**

**Comment by rangav** [comment]
Hi @jtsom 

can you downgrade vscode to v1.66 and try again?

**Comment by jtsom** [comment]
I only have the insiders build installed, I don't see a way to download a previous version. I did install the release version (1.66.2), and installed the Thunderclient extension and they shows the panel without the upgrade notification .. but that make sense as there is no history for that newly installed version.

**Comment by jtsom** [comment]
I downgraded the the extension to 1.14 and everything was working

**Comment by rangav** [comment]
Ok now can you upgrade the again to `v1.16.0`

**Comment by jtsom** [comment]
Upgraded and the same thing is happening.

**Comment by rangav** [comment]
Are you saving requests data to git workspace?

**Comment by jtsom** [comment]
No I am not.

**Comment by rangav** [comment]
Here are the steps how to re-upgrade the db

https://github.com/rangav/thunder-client-support/issues/547#issuecomment-1098342512

can you share a screenshot of requests data folder located in above link

**Comment by jtsom** [comment]
This? 
![image](https://user-images.githubusercontent.com/13488/166549940-ef13199e-caaf-4280-b40c-f261b11986f1.png)

There isn't a backup folder, not any .json files in that folder.

**Comment by rangav** [comment]
Ok thanks got it.

can downgrade your vscode to 1.65 and 
And extension version to 1.16

you download vscode here 
https://code.visualstudio.com/updates/v1_65

**Comment by rangav** [comment]
trying to see which vscode version is working with extension for db upgrade

**Comment by jtsom** [comment]
I had installed the release version of VSCode (1.66.2) and the latest version of the Thunderclient extension. Since I had never run that version of Code, there wasn't any history. I took a copy of the rangav.vscode-thunder-client folder from the Code-Insiders\User\globalStorage folder and dropped it into the Code\User\globalStorage folder and launched Code (1.66.2), and it looks like it updated the data:

![image](https://user-images.githubusercontent.com/13488/166552591-82b6b534-675a-4354-b607-d00bc0bb5186.png)


So possibly it is something in the 1.67-insiders version.

**Comment by jtsom** [comment]
I took that folder with the updated files and copied to the insiders data folder, and I see my history. So it can read the history, just not do the update.

**Comment by rangav** [comment]
Close vscode and open again

**Comment by jtsom** [comment]
No change. No response to clicking, continuous progress bar and watch icon.

**Comment by rangav** [comment]
Does your request data contain any sensitive data?

If you don’t mind sharing the requests data complete folder, so I can test and see what’s the issue here

**Comment by jtsom** [comment]
Unfortunately it does contain some proprietary info (client ID's and secrets, etc.)  I did try removing the one .db file, thinking that's what was causing the unresponsiveness, but that didn't make any difference.

**Comment by jtsom** [comment]
For what it's worth, I cleared out all the .json files (saving them of course) and relaunched Code. Nothing is showing in the activity, but I'm still seeing the progress bar and the watch icon. The New Request button is also non-responsive.

I also just tested on a Macbook Pro that I have the extension installed in VSCode-Insiders. I've not made requests, so there isn't any history, but I'm seeing the same behavior - continuous progress bar, and watch icon and non-responsive New Request button.

**Comment by rangav** [comment]
Ok no problem, 

use the release version of vscode 

delete thunderLocalEnvronment. .db and .json files and re-open vscode?

**Comment by rangav** [comment]
I think it’s better to save request data to git workspace for safety and sharing with team members.

you can save by enabling VSCode setting, details below
https://github.com/rangav/thunder-client-support#team

**Comment by jtsom** [comment]
Doesn't seem to matter how I set that setting, the panel is unresponsive.

**Comment by rangav** [comment]
Are you using release version of vscode?

Just enable that `save to workspace` Setting and launch vscode might work.

**Comment by jtsom** [comment]
I've been trying to use Insiders, as that's what I normally use. I also generally don't use "workspaces", just open a folder and do my work. Or just a new single document. Or just do some REST client calls, not necessarily with a workspace/folder.

**Comment by rangav** [comment]
Ok got it, will investigate further if I find any solution will back to you.

**Comment by rangav** [comment]
You can use older version of extension till then.

**Comment by jtsom** [comment]
Will do. Thanks for the help!

**Comment by rangav** [comment]
This bug is now fixed and please update to `v1.16.3`

See all features & bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.3

**Comment by jtsom** [comment]
Looks good! Thanks!
