### ISSUE TITLE
graphQL queries with Bearer token authorization not working with thunder client

### ISSUE THREAD

**Issue by avimehenwal** [rangav/thunder-client-support#583]
**Describe the bug**

I am trying to test a backend graphQL enabled api with thunderclient. The API uses JWT bearer token for authorization the client call.
ThunderClient should have worked flawlessly as with other POST calls but it fails with following error "Connection was refused by the server".

However the same query works if I copy the cURL "code snippet" generated by thunder client in the terminal

**To Reproduce**

1.  take a graphQL api which uses JWT bearer in headers for authorization
2. setup up a POST call in thunderclient with graphQL query in Body->Graphql section
3. Also set AUTH for the call to Bearer and use the token from environment
4. Try to send the call, it fails on thunderclient response section

![thunder-client-graphql-bug-report](https://user-images.githubusercontent.com/3624059/166703020-257ce742-3ae4-4c60-8731-d497762e36ac.png)

Now,

1. get the code-snippet generated by thunder client in cURL format for the same query
2. Try to run it in terminal
3. It works

![thunder-client-curl-works](https://user-images.githubusercontent.com/3624059/166705651-0f15b600-f9be-476d-9da0-b01aed08dba9.png)

**Expected behavior**

Thunderclient graphQL call with JWT bearer token should not fail in vs-code extensions RHS
graphql should work both in vs-code extension and in terminal from cURl code-snippet generated by the thunder-client

**Platform:** 
 - OS: windows - 10
 - vscode version: 1.66.2
 - extension version: 1.16.2

**Solution:**

**Comment by avimehenwal** [comment]
Hi @rangav , graphQL HTTP calls works fine both from cURL on terminal and Postman using `localhost`. I can also run see graphQL playground in browser at `http://localhost:8888/graphql`.
Postman even tells me when my token has expired and I need to get a new one with HTTP status 200.

Here is a screenshot

![postman](https://user-images.githubusercontent.com/3624059/166748647-a17baee6-d8b5-49cb-8483-a55e4262a72a.png)

**Comment by rangav** [comment]
The library I am using for Http requests is got.js
https://github.com/sindresorhus/got

Some users seems to have problem using localhost.

can you try using IP address?

are you using ipv6 or ipv4?

**Comment by avimehenwal** [comment]
Hello @rangav , thankyou for the suggestion. Based on my findings it had something to do with graphQL AUTH (I am not even sure myself where exactly the problem lies). But I can confirm I was able to use thunderClient seamlessly once I disabled the AUTH

I like this client :) Great tool. Thankyou for sharing it.

**Comment by rangav** [comment]
@avimehenwal glad you like it :), let me know if you have any other questions.
