### ISSUE TITLE
Thunderclient is Bricked on VS Code Update v1.67

### ISSUE THREAD

**Issue by cadencereplies** [rangav/thunder-client-support#585]
**Describe the bug**
Thunderclient is unresponsive after the latest VS Code update:
Version: 1.67.0
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:10:15.217Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

**To Reproduce**
Open VS Code, open Thunderclient, attempt to open any saved request or a new one. Thunderclient extension sidebar shows a scrolling "loading" line forever.

**Expected behavior**
Extension loads correctly and saved requests are accessible and usable.

**Platform:** 
 - OS: MacOS Monterey 12.3.1 (21E258)
 - vscode version: 1.67.0
 - extension version: v1.16.2

**Comment by rangav** [comment]
Thanks @cadencereplies for reporting the bug, Will look into it.

**Comment by ddeepeshkumar** [comment]
This is a serious issue. We just recently migrated all our API tests from REST Client to ThunderClient and this happened.
Platform: Linux/Ubuntu 20.04

**Comment by rangav** [comment]
Could be issue with vscode version 1.67

if you downgrade to 1.66 then it should work

**Comment by rangav** [comment]
I have rebuild the extension in vscode 1.67 and that seems to fix the issue. Would you like to test I will attach vsix file?

**Comment by Zachlson** [comment]
This issue is still persisting after disabling/enabling the extension as well as uninstalling and reinstalling

**Comment by rangav** [comment]
@Zachlson investigating the issue, in the meantime you can downgrade vscode to v1.66

**Comment by rangav** [comment]
This bug is now fixed and please update to `v1.16.3`

See all features & bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.3
