### ISSUE TITLE
it's not taking my request 

### ISSUE THREAD

**Issue by Rahulx01** [rangav/thunder-client-support#586]
Issue Type: <b>Feature Request</b>

it's not taking my request i have been trying from last 1 hour , i even tried to re-install it many times but still not working, it's just loading , i am very disappointed!

Extension version: 1.16.2
VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by rangav** [comment]
Hi @Rahulx01, could be issue with vscode version 1.67

please downgrade the vscode and try

**Comment by rangav** [comment]
I have rebuild the extension in vscode 1.67 and that seems to fix the issue. Would you like to test i will upload `vsix` file?

**Comment by rangav** [comment]
This bug is now fixed and please update to `v1.16.3`

See all features & bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.3
