### ISSUE TITLE
Bearer Token is not renewed when switching environment

### ISSUE THREAD

**Issue by DOliana** [rangav/thunder-client-support#588]
**Describe the bug**
OAuth2 Bearer Token is cached when switching environments. This is a problem when using environment specific credentials.

**To Reproduce**
1. Create 2 Environments
2. Add Variables für OAuth2 Authentication (for me: client secret, client id)
3. Use environment variable in OAuth2 Setting (for me it was on collection level)
4. Select environment 1
5. execute request which requires authentication -> observe that it works
6. Switch to environment 2
7. execute request which requires authentication -> observe that it it faily (usually a 401)
(workaround: remove the content of the token field in authentication settings and it will work)

**Expected behavior**
When switching to environment 2 it should either clear the token cache or have separate caches for each environment

**Platform:** 
 - OS: Windows
 - vscode version: 1.67.0
 - extension version: 1.16.3

**Solution:**

**Comment by rangav** [comment]
Thanks @DOliana for reporting the issue, will look into it.

**Comment by rangav** [comment]
related #216

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
