### ISSUE TITLE
All collections and requests suddenly removed!

### ISSUE THREAD

**Issue by EizEddin** [rangav/thunder-client-support#589]
Hi,

I've added several collections with several requests in each collection. And they were all saved.

But when I closed VSCode and reopened it again, all collections and requests disappeared!

Why would this happen?
Where can I recover them from? Where are they usually stored?

By the way, I have the setting "Save To Workspace" enabled, but nothing seems to be saved in the workspace!

I appreciated any help in this issue.
Thanks

**Comment by rangav** [comment]
@EizEddin 

The requests data should be in below default location

on PC
`%APPDATA%\Code\User\globalStorage\rangav.vscode-thunder-client`

on Mac
`/Users/{{userName}}/Library/Application Support/Code/User/globalStorage/rangav.vscode-thunder-client/`

replace {{username}} with yours

you can copy the data files to new workspace location

don’t copy the `thunderLocalEnvironment`

**Comment by rangav** [comment]
Currently if there are already requests available in default location, you need to manually copy the data as a one time operation to your workspace.

Automating moving data will have side effects and other tricky use case issues.

So manually doing by user is better option
