### ISSUE TITLE
No way to reward the author for his hard work and support!

### ISSUE THREAD

**Issue by wildhart** [rangav/thunder-client-support#59]
Currently there is no way to reward @rangav for his hard work and support ;-)

Please signup for [Github Sponsors](https://github.com/sponsors) or similar...

**Comment by rangav** [comment]
Thanks for suggestion @wildhart :) , will add soon..

**Comment by rangav** [comment]
Hi @wildhart finally finished setting up sponsors page, thanks

![Screenshot 2022-03-01 at 12 25 43](https://user-images.githubusercontent.com/8637550/156168980-e42e6493-7646-4655-9f1c-e381c4dc5399.png)

**Comment by wildhart** [comment]
No worries, you've earnt it!  I use ThunderClient nearly every day on multiple projects - it's so handy having it open in split window next to the code I'm working on, with the requests & variables automatically stored in version control.

Have a few beers/coffee's on me!
