### ISSUE TITLE
Feature request: Allow tests to assign variables from raw body string

### ISSUE THREAD

**Issue by caseymcj** [rangav/thunder-client-support#590]
Feature request:

Allow tests to assign variables from the raw body string. For example, in Tests, allow this:

`body` setTo `{{variable}}`   (where "body" is the raw body string.) This is a very important feature for me and my colleagues during API tests.

Currently only `json.[etc]` is allowed as the left-most parameter.

**Comment by rangav** [comment]
Hi @caseymcj 


This feature is already supported, just use the keyword `text` In the left input.

see more details here
https://github.com/rangav/thunder-client-support#setenv
