### ISSUE TITLE
POST request doesn't work properly

### ISSUE THREAD

**Issue by 0xj0hn** [rangav/thunder-client-support#592]
**Describe the bug**
I've tested POST request and GET request. but all of them is as same as each other.
it only send a GET request. it cannot handle POST request. it just make them as GET request.

**To Reproduce**
- reinstall extension
- restart my computer

**Expected behavior**
i wanna send a POST request towards my server.
i don't know whether it's a BUG or not. but i expected to have a POST request.

**Platform:** 
 - OS: Arch Linux
 - vscode version: Vscodium 1.63
 - extension version: 1.16.2
**Image**:
![image](https://user-images.githubusercontent.com/50566073/168010581-8f3538c3-1a55-441e-aa70-157e08423e98.png)

**Comment by rangav** [comment]
@0xj0hn thanks for reporting the issue

how you verified the POST is not working?

**Comment by 0xj0hn** [comment]
@rangav I'm sorry dude. i thought we have to use "Query" here. but after some minutes i got we have to go to "Body" section, then we should implement our form fields there.
it was fixed.
