### ISSUE TITLE
Modify cookies?

### ISSUE THREAD

**Issue by katsar0v** [rangav/thunder-client-support#593]
**Is your feature request related to a problem? Please describe.**
Currently the extension does not allow preview/modification of cookies sent or received.

**Describe the solution you'd like**
It would be great if I could modify my cookies before sending an http request with the extension

**Comment by rangav** [comment]
He is link cookies documentation
https://github.com/rangav/thunder-client-support#cookies

I am closing this issue, feel free to re-open if needed.
