### ISSUE TITLE
Command Thunder client reload sidebar not found

### ISSUE THREAD

**Issue by shivam0812-code** [rangav/thunder-client-support#594]
Yesterday I used thunder client and it was working fine
But, when I started my pc and tried to start thunder client it's showing -
"Command, 'thunder-client.reload-sidebar' not found"
I didn't change any setting on my vs code or pc.
I tried re-installing the extension but it didn't work.
Then I disable and enabled the extension but these didn't work either. 
So, how can I fix this problem?

Note- "Command, 'thunder-client.reload-sidebar' not found" is coming only after clicking on refresh button on the side of thunder-client 
Platform :
OS: Windows 10
vscode version: 1.66.2
extension version: 1.16.3

**Solution:**

**Comment by shivam0812-code** [comment]
Problem is solved when I installed the previous version of this(Thunder-client) extension.

**Comment by rangav** [comment]
@shivam0812-code why are you clicking refresh button?

when you launch launch vscode the extension will load the data automatically in the sidebar

**Comment by shivam0812-code** [comment]
> @shivam0812-code why are you clicking refresh button?
> 
> when you launch launch vscode the extension will load the data automatically in the sidebar

when I was opening thunder-client extension it was showing nothing...there was a blank sidebar. So, I was refreshing in a hope that something would appear. However, my problem was solved after installing the previous version of thunder-client.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
