### ISSUE TITLE
It would be useful if the output headers could be set to Environment Variables. For example save header.tsec from ther output to {{tsec}}. Thanks for your job.

### ISSUE THREAD

**Issue by alexCosario** [rangav/thunder-client-support#595]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
@alexCosario this is already supported 

see details below 
https://github.com/rangav/thunder-client-support#setenv
