### ISSUE TITLE
I can not get the json response but the status is 200

### ISSUE THREAD

**Issue by MNouroozi** [rangav/thunder-client-support#596]
![Screen Shot 1401-02-23 at 01 26 34](https://user-images.githubusercontent.com/37396752/168166788-495a8cf3-8be5-4f73-b3ce-4d76fca1a024.jpg)

in postman is ok

![Screen Shot 1401-02-23 at 01 27 32](https://user-images.githubusercontent.com/37396752/168166858-500d098a-5538-4775-8d9b-e24b720847d0.jpg)

thank's please help me !

**Comment by rangav** [comment]
Hi @MNouroozi thanks for reporting the issue.

is the possible to share the url, so I can test here?

can you share full json response text

**Comment by MNouroozi** [comment]
![Screen Shot 1401-02-24 at 12 22 06](https://user-images.githubusercontent.com/37396752/168416735-2abd20a4-84a5-4aac-beca-b7ec8ad2e260.jpg)
![Screen Shot 1401-02-24 at 12 23 07](https://user-images.githubusercontent.com/37396752/168416738-62a8decb-422a-4745-85aa-c559d8c9cf47.jpg)
![Screen Shot 1401-02-24 at 12 24 19](https://user-images.githubusercontent.com/37396752/168416749-ecf5dbe3-c65c-4fbc-9310-026941f363aa.jpg)
> 
Thanks

**Comment by rangav** [comment]
From the response content type, it is `application/grpc` Which could be the issue.

Is it grpc request?

**Comment by MNouroozi** [comment]
oh my god
thank for respose
I hope add it soon

**Comment by rangav** [comment]
@MNouroozi i am closing this issue, as we already have a existing request for grpc https://github.com/rangav/thunder-client-support/issues/12
