### ISSUE TITLE
Get request doesn't work.

### ISSUE THREAD

**Issue by HANKAIKAI** [rangav/thunder-client-support#597]
**Describe the bug**
I've tested POST requests and GET requests, but all of them are the same (Status: _404 Not Found_).
Even though my code could be executed properly on the browser,  when I tried to use the thunder client I still got this issue(Status: _404 Not Found_). 

**To Reproduce**

reinstall extension
restart my computer
Still got the same result(Status: _404 Not Found_).

**Platform:**

OS: Windows 11
vscode version: 1.67.1
extension version: 1.16.3

![image](https://user-images.githubusercontent.com/45023946/168195958-dcfd16be-81ba-420f-9c07-f8573314e56a.png)

**Comment by rangav** [comment]
Hi @HANKAIKAI the issue could be local dns issue

see below comments for solution
https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-864047143

let me know if it works or not

**Comment by rangav** [comment]
@HANKAIKAI  we add new http library option for `axios` in v1.18.3. please test it and let me know your feedback

<img width="837" alt="http" src="https://user-images.githubusercontent.com/8637550/184552594-606c3ccc-850d-4dad-88f2-fc024f963f92.png">

See features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by ahmedtaha01** [comment]
I have the same problem, did you find an answer?

**Comment by rangav** [comment]
Hi @ahmedtaha01 

did you try the suggestions mentioned here
https://github.com/rangav/thunder-client-support/issues/597#issuecomment-1125806771

**Comment by TJselevani** [comment]
@rangav @HANKAIKAI @ahmedtaha01  @SourceR85 @surfmuggle 
Solved by using http://[::1]:4040/api/auth/login

>>the loop bal adress is in square brackets

**Comment by dhiegomaga** [comment]
same issue here, works on chrome but not thunderclient, same URL and request type (GET)

**Comment by rangav** [comment]
Hi @dhiegomaga 

We just now published a new version to fix this issue.

Please update the extension to version - `v2.10.2`

Let me know if this works or not

**Comment by AntonioMontenegro-Glich** [comment]
i have the same problems, but all the solutions doesn't work

**Comment by ndayiringiye** [comment]
i forward this issue

**Comment by ranjansharma-ind** [comment]
I got the same issue, but if you are working in next.js create the file app/users/route.js and then call it users
