### ISSUE TITLE
Extract data from a JSON response and set it as an environment variable?

### ISSUE THREAD

**Issue by chaeron** [rangav/thunder-client-support#6]
How can we extract data from a JSON response and set it as an environment variable to be used by subsequent requests?

Looked in the tests tab, but don't see a way to do this.

We do this all the time using REST Client (and Postman), but can't see any way to do this with Thunder Client.  Without this capability, we won't be able to use your extension, as it's a critical feature for us.

Thanks!

**Comment by rangav** [comment]
Hi @chaeron Current it is not possible, i will add this to list of features for next version. ETA by end of this week or early next week.

**Comment by chaeron** [comment]
Nice...thanks!

I'm curious at to why the project is not open source?

**Comment by rangav** [comment]
haven't decided yet about open source, i will open source some parts of the project at later stage.

**Comment by rangav** [comment]
This is now implemented in v1.0.6, please update extension.
