### ISSUE TITLE
setTo not working

### ISSUE THREAD

**Issue by jacodv** [rangav/thunder-client-support#60]
**Describe the bug**
Environment variable not being set

**To Reproduce**
Add test with "Set Environment Variable

**Expected behavior**
Environment variable updated after successful request

**Platform:** 
 - Windows

**Solution:**
![image](https://user-images.githubusercontent.com/5814127/116039619-3f618800-a66b-11eb-8aa9-c918cd08b3ea.png)
![image](https://user-images.githubusercontent.com/5814127/116039680-530cee80-a66b-11eb-95d7-cd723fd52852.png)

**Comment by rangav** [comment]
Hi @jacodv there is a bug when you use 2 set env vars, it is updating only one, this issue is already reported here - #46, I am closing this, you can add comments in above issue link.
