### ISSUE TITLE
Hung on processing

### ISSUE THREAD

**Issue by Tanmai2002** [rangav/thunder-client-support#601]
**Describe the bug**

when ever i send request for any link(including default thunder client link) , i Receive response but respose is not displayed. instead it shows processing (after response is received). it worked a week ago , now it doesnt.
**To Reproduce**

![image_2022-05-22_111425803](https://user-images.githubusercontent.com/40868910/169680716-6eac49e5-60d5-4091-9593-d00801be5119.png)

**Expected behavior**

response in form of json is expected.
**Platform:** 
 - OS: Windows 10
 - vscode version:1.67.2
 - extension version:

**Solution:**

**Comment by rangav** [comment]
@Tanmai2002 thanks for reporting the issue, 

what version of extension are you using?

**Comment by Tanmai2002** [comment]
1.16.4

**Comment by rangav** [comment]
Try downgrading to `1.16.3` and test it. Meanwhile I will look into the issue

**Comment by Tanmai2002** [comment]
ok sure thank you

**Comment by Tanmai2002** [comment]
Now it works. Thank you. Hope you resolves the issue soon.

**Comment by rangav** [comment]
I just now published new version `v1.16.5,` you can install and see if it’s working for you or not.
