### ISSUE TITLE
Option to hide & show Password or other parameters

### ISSUE THREAD

**Issue by E9B7B1** [rangav/thunder-client-support#602]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option to hide password parameter and when I share my screen with other teammates, they can potentially see my password.

**Describe the solution you'd like**
Add an option to hide and show password and other parameters.

**Describe alternatives you've considered**
Postman has this feature but I don't want to go back to using Postman due to this one problem I have.

**Implementation:**
I can definitely look into it and any input would be appreciated!

**Comment by rangav** [comment]
Hi @E9B7B1 thanks for the feedback.

Can you share a screenshot the fields you are referring to?

Alternatively you can use Environment variables to save password and use variable in fields with format `{{password}}`

**Comment by E9B7B1** [comment]
Hello @rangav thank you for your prompt reply!

Yes, I can share a screenshot of the field.
<img width="596" alt="Screen Shot 2022-05-23 at 11 15 45 AM" src="https://user-images.githubusercontent.com/104611215/169852070-ba959470-0e77-48a8-aea4-cb06191dd0b5.png">

To give a bit of context, when sharing screen, I often need to go to 'OAuth 2'  page to get refresh token and always have to remind myself to stop sharing screen becuase they can potentially see my password and other parameters I don't want to share.

**Comment by rangav** [comment]
got it thanks, will implement it soon.

As I suggested earlier, it is good use env variables to save clientId, client secret and password for safety and also you can re-use in multiple requests.

**Comment by E9B7B1** [comment]
Whoops, I somehow didn't read the first line of your comment and closed the ticket by an accident.
Thank you again!

**Comment by rangav** [comment]
I think since there are so many fields that can contain secrets values, it may not solve the problem by just implementing masking value for only password field.

may be using env fields is the right solution.

will close this issue for now.
