### ISSUE TITLE
"Custom Location" settings do not support environment variable on Windows

### ISSUE THREAD

**Issue by ajaydwarkani** [rangav/thunder-client-support#603]
**Describe the bug**
Using environment variables in "Custom Location" under user settings (https://github.com/rangav/thunder-client-support#team) is not working on Windows

**To Reproduce**
Update the Custom Location property with "$HOME/<thunderclient JSON files>" on Windows
 
**Expected behavior**
All the APIs should show under the collection tab

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.67.2
 - extension version: 1.16.4

**Solution:**

**Additional request:**
Also, add support for environment variables other than HOME as Windows does not have a variable HOME

**Comment by rangav** [comment]
Thanks @ajaydwarkani for reporting the bug, will look into it.

**Comment by rangav** [comment]
Hi @ajaydwarkani I just now tested using `$HOME/` its working. 

The location will be `C:\Users\<userName>`

How did you verify it?

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed

**Comment by ajaydwarkani** [comment]
@rangav Thanks for your response. The reason it didn't work because I was trying to create a variable `HOME` on Windows. But now after you clarification I was able to use variable `HOME` without needing to create a variable.

Since my thunder client files are located in some other directory, the way I am doing currently is by creating a symbolic link mapped to `HOME` directory. As I work on multiple system (Mac and Windows both) and my VS Code settings get synced across platform, I needed a way that works on both the system.

Any chance to support custom variable for this field?

**Comment by rangav** [comment]
@ajaydwarkani use the `custom location` value as `workspace setting`, then it will work across Mac and windows

**Comment by ajaydwarkani** [comment]
@rangav, Thanks for the tip. I totally forgot about workspace settings as it's local to workspace and do not get synced. Now I can use different paths for Mac and Windows.

**Comment by rangav** [comment]
Workspace setting can be synced if you save `.vscode` folder also to git.
