### ISSUE TITLE
Unable to install, not compatible with the current version of VS Code

### ISSUE THREAD

**Issue by nbonbon** [rangav/thunder-client-support#604]
**Describe the bug**
When attempting to install I get the following error:

"Unable to install 'rangav.vscode-thunder-client' extension because it is not compatible with the current version of VS Code (version 1.36.1)."

**To Reproduce**
Click install 

**Expected behavior**
To be able to install the extension

**Platform:** 
 - OS: Linux
 - vscode version: 1.36.1
 - extension version: 1.16.4

**Comment by rangav** [comment]
Hi @nbonbon Minimum vscode version required is `v1.63.0`
