### ISSUE TITLE
Enter key on numeric keypad does not send the request

### ISSUE THREAD

**Issue by MGMehdi** [rangav/thunder-client-support#606]
**Is your feature request related to a problem? Please describe.**

When pressing the Enter key on the numpad it add a space or go to the line then come back but does not send the request.
The shortcut `ctrl + numpad enter key` does not working too

**Describe the solution you'd like**

Make the numpad enter key act like the other enter key

**Comment by rangav** [comment]
Hi @MGMehdi 

`Enter` key will work when your mouse focus is on Url field

where is the mouse focus in your case when you Enter.

You can use `Ctrl + Enter` from anywhere on the request window to send request

**Comment by MGMehdi** [comment]
Hi @rangav 
I make a gif so you can see. Every time I presse the `Enter` key on the **numpad** it does this
![enter bug](https://user-images.githubusercontent.com/48625769/170969855-a8e36dc1-da0d-4c12-ab83-38569c9b138e.gif)
If I press `Ctrl + Enter on numpad` it does nothing

**Comment by rangav** [comment]
Thanks @MGMehdi will verify and get back to you

**Comment by MGMehdi** [comment]
Thanks !

**Comment by rangav** [comment]
We will keep the bug as open issue, easy for my tracking. Will close when I fixed the bug

**Comment by MGMehdi** [comment]
Hello,
Any news on the next update ?

**Comment by rangav** [comment]
We haven’t got any specific date yet, might be by end of this month, as an alternative you can use normal `Enter` key

**Comment by rangav** [comment]
@MGMehdi this bug is fixed now, will publish new update today or tomorrow.

**Comment by MGMehdi** [comment]
Super ! Thank you !

**Comment by rangav** [comment]
This bug is fixed now, please update to version `v1.16.4`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.4
