### ISSUE TITLE
proxy settings?

### ISSUE THREAD

**Issue by dimsis** [rangav/thunder-client-support#61]
Hi

I am getting an 'unknown error' message: 
Status: ERROR
Size: 0 B
Time: 0 ms
unknown error

I am behind a proxy server, is there any settings for it?

**Comment by rangav** [comment]
Hi @dimsis don't know i haven't tested with proxy server, may be its a new feature request

**Comment by dimsis** [comment]
> Hi @dimsis don't know i haven't tested with proxy server, may be its a new feature request

Yeah, it might be. If you ever have the time and a way to test it, please let us know.
My connection is through VPN and using a proxy server. (company security)

**Comment by waheedahmed55** [comment]
> > Hi @dimsis don't know i haven't tested with proxy server, may be its a new feature request
> 
> Yeah, it might be. If you ever have the time and a way to test it, please let us know.
> My connection is through VPN and using a proxy server. (company security)

Yes I have same request and blocked currently not able to use this tool in VS Code. Request to prioritize this planned release v 1.1.0

**Comment by rangav** [comment]
Hi @waheedahmed55 sure if possible I will try and include for v1.1.0

what options you need to configure proxy?

**Comment by waheedahmed55** [comment]
> Hi @waheedahmed55 sure if possible I will try and include for v1.1.0
> 
> what options you need to configure proxy?

We have to set HTTP_PROXY , HTTPS_PROXY and we set it with port number 

https://learning.postman.com/docs/sending-requests/capturing-request-data/proxy/#:~:text=Turn%20Global%20proxy%20on%20if,and%20select%20the%20Proxy%20tab.

![image](https://user-images.githubusercontent.com/29276911/116437440-737bab00-a81b-11eb-8e93-90d1e6156d5a.png)

In restassured if I have to send request I will need to provide the ip address of proxy server its port and mode (http/https)

ProxySpecification pro = new ProxySpecification("ipaddress", port, "mode");

mode = http or https

**Comment by rangav** [comment]
ok got it. mode should be either http or https right, why postman has 2 modes selected?

**Comment by rangav** [comment]
Hi @waheedahmed55 are you currently using vs code using proxy? if yes may be i can access these settings use

http://blog.majcica.com/2016/04/07/visual-studio-code-behind-a-proxy/

**Comment by waheedahmed55** [comment]
> ok got it. mode should be either http or https right, why postman has 2 modes selected?

Not sure about it Ranga but I forgot to add is we have to turn off the SSL Certificate issues 

Yes I was reading same from vs code settings https://code.visualstudio.com/docs/getstarted/settings

![image](https://user-images.githubusercontent.com/29276911/116444336-9f4e5f00-a822-11eb-985a-bc0dd38b838a.png)

**Comment by rangav** [comment]
Thats good, i will try to use them and update you tomorrow.

**Comment by rangav** [comment]
Hi @waheedahmed55 is your proxy server http or https?

**Comment by waheedahmed55** [comment]
> Hi @waheedahmed55 is your proxy server http or https?

In my case when I set proxy I use mode as HTTP and turn off that ssl certificate flag as shown in vscode setting

**Comment by rangav** [comment]
ok got it, i have finished enabling the proxy and tested its working, it will go live tomorrow #14

**Comment by waheedahmed55** [comment]
> ok got it, i have finished enabling the proxy and tested its working, it will go live tomorrow #14

So how will I update? 

And where do I set proxy in vscode user setting or workspace settings?

**Comment by rangav** [comment]
![image](https://user-images.githubusercontent.com/8637550/116486114-c2115f80-a884-11eb-89de-e95fbfb2ea19.png)

**Comment by rangav** [comment]
I will release the update tomorrow, then you can install.

**Comment by rangav** [comment]
format: `http://username:password@host:port`

**Comment by waheedahmed55** [comment]
> format: `http://username:password@host:port`

In my case format is: http:://host:port

**Comment by RaheelAhmed3** [comment]
I am also need this fix. Any idea on what time today it will drop?

**Comment by rangav** [comment]
Hi @RaheelAhmed3 i am still doing few more last minute fixes, may be in next 3-4 hours

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14

**Comment by metalshanked** [comment]
Hi, I am behind a corporate proxy as well and seem to be getting the below errors

**Comment by metalshanked** [comment]
> Hi @dimsis the extension reads proxy value from vscode settings, if its not set no proxy will be used. Not sure how it works with corporate proxy.

Thanks. Ideally we need both.  The vscode proxy settings(http(s)_proxy) for urls that need to go through the corporate proxy and another "no_proxy" ENV variable for URLs that should not go through the corporate proxy.
https://www.npmjs.com/package/proxy-from-env#environment-variables

**Comment by rangav** [comment]
i can provide option to excludeProxyHostList vscode settings, you can list the host names to exclude, will that work?

**Comment by metalshanked** [comment]
> i can provide option to excludeProxyHostList vscode settings, you can list the host names to exclude, will that work?

Sure, that sounds like a good option. Thanks will check it out.

**Comment by rangav** [comment]
Hi @metalshanked i will try and see if thats possible or any other solution

**Comment by rangav** [comment]
This is implemented now in v1.3.0, see readme.
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.

**Comment by metalshanked** [comment]
Thanks much @rangav !   It is working great now by adding the No proxy items in the new vscode setting option you provided.

**Comment by rangav** [comment]
Thanks @metalshanked for confirmation 👍

**Comment by carloswm85** [comment]
> This is implemented now in v1.3.0, see readme. https://github.com/rangav/thunder-client-support/releases/tag/1.3.0 Let me know if any questions.

Please, include the correct settings to the section: https://github.com/rangav/thunder-client-support#proxy

**Comment by rangav** [comment]
@carloswm85 

try this - https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by carloswm85** [comment]
> @carloswm85 
> 
> try this - https://code.visualstudio.com/docs/setup/network#_proxy-server-support

I already knew that. I was suggesting you to add the correct settings in the documentation of your extension.

Great work, by the way. Really appreciated.

**Comment by rangav** [comment]
@carloswm85 Thanks, updated the docs
