### ISSUE TITLE
Simplify workflow to click OAuth 2 "Generate Token" button

### ISSUE THREAD

**Issue by nathan-seddig-techedge** [rangav/thunder-client-support#611]
**Is your feature request related to a problem? Please describe.**

I use thunder client regularly and several of my collections require OAuth 2 authentication (specifically client credentials). The generated tokens have a relatively short expiration time so that I frequently have to re-generate them. The current workflow for generating a tokent is the following. 
 1. Open Thunder Client sidebar.
 2. Click the three dots next to the collection name. 
 3. Click Settings. 
 4. Navigate to the Auth tab. 
 5. Scroll to the bottom of the page. 
 6. Click on the Generate Token button. 
 
I wish there was an alternative workflow with fewer steps. Please note that in my use case I cannot simply leave the "Collection Settings" page open (to avoid repeating steps 1-5) since I am regularly working with several collections at a time and it seems that only one Collection Setting (for a single collection) can be opened at a time. 

**Describe the solution you'd like**

I would like a simpler workflow to generate the OAuth 2 token. Some ideas are presented in the next section. 

**Describe alternatives you've considered**

 - When clicking the three buttons next to a collection name, an item could be added (below Run All and Settings) to "Generate Token" (visible only if the collection has OAuth 2 authentication enabled). This would reduce the workflow from 6 steps to 3. 
 - A command "Thunder Client: Generate OAuth 2 Token" could be added to the palette. Running the command would prompt the user to select which collection's token to generate. 
 - Slightly off-topic, but I believe that adding the possibility to open the Collection Settings page for several collections at the same time would also mitigate this usability issue and is probably a usability improvement regardless. 
 
**Implementation:**

No implementation suggestion. 

Thanks for the great work, I will continue to use Thunder Client daily even without this improvement, but having it would save me (and probaly many other folks) lots of time :)

**Comment by rangav** [comment]
Thanks @nathan-seddig-techedge for the great feedback. Will review and add to roadmap.

We have also to auto-generate token after expiry, that might solve this issue.

**Comment by nathan-seddig-techedge** [comment]
Thanks! Sorry I didn't find #216 "Automatically Refresh token" while searching for previous issues, I'll leave the reference here in case anyone finds this issue in the future. 

Have a nice day!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
