### ISSUE TITLE
Need Parameter Bulk Edit option

### ISSUE THREAD

**Issue by cpatel22** [rangav/thunder-client-support#612]
Nice to have if the parameter has a bulk edit option. it will make copy and paste parameters and start to work.
Like postman
![image](https://user-images.githubusercontent.com/7018966/172639699-186a72b1-3b76-465c-874c-696494bddb6e.png)

**Comment by rangav** [comment]
Thanks @cpatel22 for the feedback, will add to roadmap..

**Comment by rangav** [comment]
This feature is implemented in `v2.13.3`

https://github.com/rangav/thunder-client-support/releases/tag/v2.13.3
