### ISSUE TITLE
Iterative requests

### ISSUE THREAD

**Issue by navotoz** [rangav/thunder-client-support#613]
**Describe the solution you'd like**
Running the same request in a loop.
More precisely - Run->Answer->Run->Answer->Run->...
This will enable checking memory leak, CPU usage over extended time, Heating issues (in Rpi or Jetson for instance).

**Describe alternatives you've considered**
I'm currently making a long collection, but this is uncomfortable because its hard to know exactly how many calls there are in the collection.

**Comment by rangav** [comment]
Thanks @navotoz for the feedback, Will add to roadmap

**Comment by rangav** [comment]
The requests count is displayed in Run Collection view now, Please update to `v1.16.5`

**Comment by navotoz** [comment]
Thanks.
