### ISSUE TITLE
Malformed return not displayed and not viewable in any manner

### ISSUE THREAD

**Issue by designgears** [rangav/thunder-client-support#614]
**Is your feature request related to a problem? Please describe.**
When debugging an api endpoint that returns malformed json/xml/etc... the request is successful but the response tab will be empty with no way to see the raw return to see that the return was malformed. 

**Describe the solution you'd like**
Add a tab next to Response or an options in the menu to see the raw output called Raw or Original, something similar to how you can see the original email with all of the headers in such in gmail.

**Describe alternatives you've considered**
Option to dump the raw return to the extensions console output.

**Comment by rangav** [comment]
Thanks for the feedback @designgears, will add to roadmap.

Can you please a sample malformed response for testing

**Comment by designgears** [comment]
@rangav while I can't provide my exact example, in my testing a broken compression function was only allowing 1024 characters causing it to cut off about half of the returned xml. I think an easy example would be anything with a missing closing tag or a cut off tag. Also returning a line break before the xml tag would break it.

**Comment by rangav** [comment]
@designgears I was able to output the malformed xml 

you can test using this url
https://www.thunderclient.com/t/echo

<img width="1370" alt="Screenshot 2022-06-14 at 09 18 28" src="https://user-images.githubusercontent.com/8637550/173529280-4275fec3-4eee-4cfa-a775-7e3700af22dc.png">

**Comment by rangav** [comment]
works for json also for missing closing bracket
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/8637550/173529803-a6ef30b6-7a1d-47a5-854e-ce085335b68c.png">

**Comment by designgears** [comment]
@rangav what about a chopped off tag? 

<text>
  <name>Test</name>
  <area>boston</ar

**Comment by designgears** [comment]
Looks like your echo endpoint is trimming off the linebreak before returning it.

**Comment by rangav** [comment]
Can you let me know how to re-produce the issue, because I can see the output for malformed xml/json.

**Comment by rangav** [comment]
Closing this issue, feel free to re-open if needed
