### ISSUE TITLE
Not Showing an Icon in Action Bar Of Thunder Client Extension in VS Code

### ISSUE THREAD

**Issue by AmitGagal** [rangav/thunder-client-support#617]
i installed thunder client and did reload the window  but  icon didn't appear on the action bar . i did close and reopen vs code but still its not working then i installed old version of it and it didn't worked.  i am using Ubuntu.

**Comment by rangav** [comment]
Thanks @AmitGagal for reporting the issue, will look into it.

**Comment by rangav** [comment]
what version of `vscode `are you using?

**Comment by gkennedy87** [comment]
I'm having the same issue but with Mac OS 12.2.1. My VSCode version is 1.68.0. I had been using Thunder Client with this same project just fine but now it's gone.

Tried disable-enable, uninstall-install, uninstall-restart-install-restart. Nothing worked.

**Comment by theksg** [comment]
I tried installing previous versions plus tried installing uninstalling both vs code and thunder client ,still no good happening at my end. I had created a collection of api end points which I wish to access. Can you help in getting that through local storage? I would like to know the path from where i can get my collection of apis

**Comment by rangav** [comment]
@theksg use `Ctrl+Shift+R` shortcut to see the Thunder Client sidebar.

**Comment by theksg** [comment]
I have tried doing it but it is coming complete blank, no changes on reloading as well.
![Screenshot (949)](https://user-images.githubusercontent.com/43683974/176999336-878d18fd-7075-4712-9935-c13c72b55fa2.png)

**Comment by rolandjlevy** [comment]
I had the same problem. This worked for me:

Ctrl+shift+P for Windows or Command+shift+P for Apple, then type Thunder and select 'Focus on Thunder Client View'

Thunder Client options then appear in the panel where the terminal normally is, Ctrl+J for Windows or Command+J for Apple.

Right click on the top of that panel and select 'Reset Location'. Now the Thunder Client icon appears in the Activity Bar on the side.

![image](https://user-images.githubusercontent.com/38256994/179701774-d3d8197a-4519-499c-b7c6-0c9e1b185cfd.png)

**Comment by rangav** [comment]
Closing this issue, feel free to re-open if needed

**Comment by rmoralesd** [comment]
> This is vscode issue, some users have this issue earlier
> 
> Try installing previous version of extension `v1.16.3` And let me know

This worked for me!!!!. I install previous version of the failing one.
