### ISSUE TITLE
It is possible to support command to open a collection item by `_id` or `colId`?

### ISSUE THREAD

**Issue by FeeStack** [rangav/thunder-client-support#618]
**Is your feature request related to a problem? Please describe.**

It is possible to support command to open a collection item by `_id` or `colId`?

**Describe the solution you'd like**

by command line (with params ) open the collection item.

**Describe alternatives you've considered**

it is usefull for workflow.

**Implementation:**

add a command to support open collection item by `_id` or  `colId`

**Comment by rangav** [comment]
@FeeStack thanks for feedback.

Are you looking to open a request in collection by `id` right?

**Comment by FeeStack** [comment]
> @FeeStack thanks for feedback.
> 
> Are you looking to open a request in collection by `id` right?

yes. i want to construct a workflow by `thunder-client`

**Comment by rangav** [comment]
can you share more info of what kind of workflow?

It will help me to think of better solution.

**Comment by FeeStack** [comment]
> can you share more info of what kind of workflow?
> 
> It will help me to think of better solution.

1. i want use vscode registerHoverProvider to capture the text. 
2. analyse thunder-tests/thunderclient.json, and math the collection info.
3. hover the api info and support to jump the `thunder-client` , just for test fastly.

**Comment by rangav** [comment]
you will use registerHoverProvider to capture request id?

> analyse thunder-tests/thunderclient.json, and math the collection info.

The above is is not clear?

**Comment by FeeStack** [comment]
> are you looking to open request from another extension?

yes. i construct another extension to support the workflow.  and the target is link to `thunder-client` collection item.

**Comment by rangav** [comment]
ok thanks got it.

**Comment by rangav** [comment]
let me check whether this is possible now.

**Comment by FeeStack** [comment]
> ok thanks got it.

it is possible to support it?

**Comment by FeeStack** [comment]
> 

thank you.

**Comment by rangav** [comment]
I will get back to you in 1 or 2 hours after testing here.

**Comment by rangav** [comment]
Yes its possible now to open request from another extension.

use the sample code below
```
let reqOptions = {
  reqId: "request_id_here",
  colId: "collection_id_here",
  newTab: true
}

// open request using exe command
vscode.commands.executeCommand("thunder-client.request-panel", reqOptions);
```
