### ISSUE TITLE
Thunder Client stopped returning data - multiple environments

### ISSUE THREAD

**Issue by erickemde** [rangav/thunder-client-support#619]
**Describe the bug**
I'm using TC to POST to an internally developed api. It was working, but has stopped returning data. When I submit the request, I see "Processing ... Cancel Request" in the Response tab, but never actually get a response. I also do not have the option to actually cancel the request.
If I run the exact same POST in Postman, it works. 
I have tried:

- Disabling/Enabling the extension
- Uninstalling/Re-installing the extension
- Looking a VS Code Developer tools

If I open the VS Code Developer tools, I get the following error as soon as I open Thunder Client:

`main.bundle.js:1 Uncaught SyntaxError: Invalid regular expression: /(?:({{(?:+CCEHIP_NCIPC_OSP_Share-FC|+CCEHIP_NCIPC_Share-fc|+CCID_NCPDCID_DGMQ|+CDC_IT_R&D|+CSELS_General_Data_Hub-RO|+My_Large_Workspace|+NCIPC_Darpi_Speb-FC|+NCIPC_Informatics_Support-FC|+OA_DHS_HIBR_SAG-RO|+OCIO_SCA_DEV_MTG_REC-RO|+OCOO_HRO_Projects-RO|+OD_HCRMO_CDCU_Training-FC|+OD_HCRMO_LDIITS-RO|+OD_MASO_External_Share-RO|+OD_OCOO_HRO_SP_Share-RO|+OD_OWCD_ELearning_Content|+OWCD_TCD_Transfer-FC|+OWCD_Video|ALLUSERSPROFILE|APPDATA|APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL|CDC_Login|CDC_Login_Version|CDC_PIVCheck_Version|ChocolateyInstall|CHROME_CRASHPAD_PIPE_NAME|CommonProgramFiles|CommonProgramFiles(x86)|CommonProgramW6432|COMPUTERNAME|ComSpec|deployment.expiration.check.enabled|DriverData|ELECTRON_RUN_AS_NODE|EXSERVER|HOMEDRIVE|HOMEPATH|LOCALAPPDATA|LOGONSERVER|MyDocs|NUMBER_OF_PROCESSORS|OneDrive|OneDriveCommercial|ORIGINAL_XDG_CURRENT_DESKTOP|OS|Path|PATHEXT|PROCESSOR_ARCHITECTURE|PROCESSOR_IDENTIFIER|PROCESSOR_LEVEL|PROCESSOR_REVISION|ProgramData|ProgramFiles|ProgramFiles(x86)|ProgramW6432|PSModulePath|PUBLIC|PyCharm Community Edition|RTOOLS40_HOME|SESSIONNAME|SystemDrive|SystemRoot|TEMP|TMP|UATDATA|USERDNSDOMAIN|USERDOMAIN|USERDOMAIN_ROAMINGPROFILE|USERNAME|USERPROFILE|VSCODE_AMD_ENTRYPOINT|VSCODE_CODE_CACHE_PATH|VSCODE_CWD|VSCODE_HANDLES_UNCAUGHT_ERRORS|VSCODE_IPC_HOOK|VSCODE_IPC_HOOK_EXTHOST|VSCODE_LOG_NATIVE|VSCODE_LOG_STACK|VSCODE_NLS_CONFIG|VSCODE_PID|VSCODE_PIPE_LOGGING|VSCODE_VERBOSE_LOGGING|windir|Node_URL|BI_URL|SAS_API)+}}|{{#(?:guid|bool|enum|string|randomString|number|randomNumber|email|randomEmail|date|dateISO)+}}|({{#number(?:, ?(?:[0-9])+ ?)*}})|({{#date(?:, ?'(?:[^a-zA-Z0-9]|X|Y|M|D|h|m|s|f)+' ?)?}}))|(.))/: Nothing to repeat
    at new RegExp (<anonymous>)
    at new r (main.bundle.js:1:83958)
    at u.ace.define.getTokenizer (main.bundle.js:1:101946)
    at E (main.bundle.js:1:397532)
    at HTMLDocument.<anonymous> (main.bundle.js:1:399195)
    at x (main.bundle.js:1:421419)
    at HTMLDocument.<anonymous> (main.bundle.js:1:421596)`

**To Reproduce**
Open Thunder Client

**Expected behavior**
Return a JSON statement

**Platform:** 
 - OS: Windows 2019
 - vscode version: 1.66.1
 - extension version: 1.16.4

**Solution:**
I wish I did.
This is a great extension and I like it a lot better than Postman.

**Comment by rangav** [comment]
@erickemde thanks for reporting the issue 

can you update vscode to latest version 1.68 and test again

**Comment by rangav** [comment]
@erickemde are you using regex in Tests? 

Can you share any screenshots that will be helpful to identify the issue.

**Comment by erickemde** [comment]
Hi there. I upgraded to VS Code 1.68. No joy.
Here is VS Code w/ dev tools open, before I select the request:
![image](https://user-images.githubusercontent.com/5263597/173587686-6c5caf24-977f-4c4b-aa00-23902596bb15.png)
Here it is when I select the request:
![image](https://user-images.githubusercontent.com/5263597/173587823-5e104e10-4aa4-4696-a9a3-0b3f1fddc3df.png)
Here's what I get when I submit the request:
![image](https://user-images.githubusercontent.com/5263597/173587899-5f2dd222-d619-4ffb-81cc-02f1b4cb3f30.png)
Here is the exact same request running successfully in Postman:
![image](https://user-images.githubusercontent.com/5263597/173588084-760754e4-cf85-48be-a460-66da17454391.png)

**Comment by rangav** [comment]
Thanks for sharing screenshots.

can you share xml and response as text, so I can test here

**Comment by rangav** [comment]
ok, is it possible to share the url? 

I need a way to re-produce the error, to identify the issue

**Comment by rangav** [comment]
https://www.thunderclient.com/welcome

**Comment by rangav** [comment]
try installing extension version `v1.16.3` and test it. 

Looks like some files are corrupted.

**Comment by rangav** [comment]
where are you saving the data, is it in default location or git folder?

**Comment by rangav** [comment]
related to #601

**Comment by erickemde** [comment]
Do you have a link to v1.16.3 handy?

**Comment by rangav** [comment]
<img width="523" alt="Screenshot 2022-06-15 at 17 13 00" src="https://user-images.githubusercontent.com/8637550/173875578-0abcaadb-6027-493e-bf22-b65aeccd51a7.png">

**Comment by erickemde** [comment]
It works! Thanks! Again, I'd like to say that this is a great extension. I much prefer being able to stay in VS Code to test rather than having to switch apps.

**Comment by rangav** [comment]
Thanks @erickemde for confirmation, glad you like the extension :)

**Comment by rangav** [comment]
I just now published new version `v1.16.5`, you can install and see if it’s working for you or not.

**Comment by erickemde** [comment]
v1.16.5 has the same problem. v1.16.3 works.
