### ISSUE TITLE
Environment variables do not take effect in subfolders

### ISSUE THREAD

**Issue by ljnchn** [rangav/thunder-client-support#621]
**Describe the bug**

Collection Settings can't  take effect in subfolders
**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS:  win10
 - vscode version:  1.68.0 (user setup)
 - extension version: 1.164

**Solution:**

**Comment by ljnchn** [comment]
sorry for this issues，i miss it.

**Comment by rangav** [comment]
no problem @ljnchn
