### ISSUE TITLE
Add right click support to list items

### ISSUE THREAD

**Issue by Martini002** [rangav/thunder-client-support#623]
Would be nice if we can get the mouse right click support for this menu in each item, instead of clicking the three dots menu button

Thank you

![image](https://user-images.githubusercontent.com/22435591/173605274-b48f7de3-4126-478f-9123-111d49c50259.png)

**Comment by rangav** [comment]
Thanks @Martini002 for the feedback, will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.2`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.2

Please let me know your feedback.
