### ISSUE TITLE
transforming response data - stringify variable data

### ISSUE THREAD

**Issue by M4x3e3e** [rangav/thunder-client-support#626]
i want to save the json i get from an endpoint in an environment variable, lets call it {{response}}. After that i want to do another api call with the reponse data from the privious request in my request body, but this time i want it stringifyed like JSON.stringify({{response}})

In Postman it would look like this.
pm.environment.set("response", JSON.stringify(responseBody));
one solution could be that i transform the body in my test and then save it stringifyed in my environment variable.
other solution would could that i stringify it in my request, like: 
{
    "foo": "JSON.stringify({{response}})"
}

With that feature i could fully migrate from Postman! You're doin great work, thanks!

**Comment by rangav** [comment]
Hi @M4x3e3e 

when you save response data to variable, its already saved using stringify func.

so you can just use the variable in the next request as `{{response}}`

**Comment by M4x3e3e** [comment]
Hi,

thanks for your quick response.
You're right, but i need to stringify it again so that it is a escaped string:

'"{\"foo\":\"bar\"}"'

**Comment by rangav** [comment]
the data is send in escaped format, see below screenshot

you can test with this url
https://httpbin.org/anything

![image](https://user-images.githubusercontent.com/8637550/174265094-303e9f44-7cb8-4682-b4af-cdab867f4347.png)

**Comment by M4x3e3e** [comment]
yeah i know, but i need a nested String in my json:
this is my expected Request:
{
    "variables": {
        "xyv": "{\"foo\":\"bar\"}",
        "foo": "bar"
    }
}
it's completely clear that the whole Json is parsed into a string

from your example:
![Bildschirmfoto 2022-06-17 um 11 19 34](https://user-images.githubusercontent.com/27812271/174268909-5baacb29-9189-4179-9b47-1993331f537e.png)

**Comment by rangav** [comment]
Thanks got it, will add to roadmap

**Comment by rangav** [comment]
as in alternative solution

you can output the whole body in the first request in the required format and then save to variable

![image](https://user-images.githubusercontent.com/8637550/174273341-b494deba-4967-4ee0-a29d-d4c7868872e6.png)

**Comment by M4x3e3e** [comment]
thanks!

unfortunately i cant. I could use https://httpbin.org/anything as a proxy too stringify my json as a workaround until your solution is finished :)

**Comment by rangav** [comment]
@M4x3e3e This feature is now implemented in v2.0.0, We now have a stringify filter, please use in env variables or Tests

- To use in env variable - `{{jsonVariable | stringify}}`
- To use Tests when settings env variable - `json.data | stringify`

if above does not suit your use-case, you can now write custom scripting.

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Docs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md

Please let me know your feedback
