### ISSUE TITLE
Show active environment name at all times in UI

### ISSUE THREAD

**Issue by reinux** [rangav/thunder-client-support#628]
**Is your feature request related to a problem? Please describe.**
Sometimes I make requests on the wrong environment, and I don't notice until something breaks.

**Describe the solution you'd like**
It would be cool if it would show the current active environment somewhere in the UI, maybe under the New Request button or something on the sidebar.

Thanks for this plugin! We're very much enjoying it at work.

**Comment by rangav** [comment]
@reinux the currently active environment is shown in the `statusbar` at the bottom.

Also in the output window

**Comment by reinux** [comment]
Ahh, not sure how I missed that. Thanks!

**Comment by rangav** [comment]
@reinux you can also change active environment from the `statusbar`
