### ISSUE TITLE
Setting CSRF cookie with a pre-request script

### ISSUE THREAD

**Issue by JayRSG** [rangav/thunder-client-support#629]
CSRF protection is now commonplace in web and api routes. Modern API testing utilities provide features that enables handling CSRF cookies and embedding such cookies in the request headers automatically. 

One such feature is- pre-request scripts which enables sending an API request to a route, receive cookies from the request, set that to an environment variable and include the cookie data into the request headers as X-XSRF-TOKEN which authorizes the API request made in the same request.

Thunder-Client has the awesome feature of setting environment variables to store important information from different parts of the response and to be used in other requests or stored for convenience. 
But, CSRF requires the information to be fetched and validated within the same request. 

![image](https://user-images.githubusercontent.com/14149138/175039360-bfee2137-7bb5-455f-9ed1-d6c3649d91c5.png)

This request receives a xsrf-token in the cookies. which is then set to an environment variable using 'test' feature of thunder-client for further use 

![image](https://user-images.githubusercontent.com/14149138/175040447-3fb8d673-3f38-4022-abba-371d461a6d8c.png)

The environment variable would be then used in another request header - 
![image](https://user-images.githubusercontent.com/14149138/175040831-07cc49ae-4a78-4b8b-805f-0a09e49d8c9a.png)

But the response says CSRF token mismatch. 

This problem is handled by clients like Postman using a pre-request script as mentioned above instead of two different requests.

**Comment by rangav** [comment]
@JayRSG one question

the header name needs to be send in upper case? `X-XSRF-TOKEN`

**Comment by JayRSG** [comment]
I have now enabled the setting Headers Case Sensitive in VS code but with no luck. 
The X-XSRF-TOKEN header is automatically set by axios and is sent in the same manner as I have checked in the network tab.
![image](https://user-images.githubusercontent.com/14149138/175378837-b0108d50-2573-4e34-b986-bb12adbbc954.png)

The cookie -> xsrf-token is first set by the request made to /sanctum/csrf-cookie and the cookie data is sent in the X-XSRF-TOKEN header to the consecutive requests to the routes protected by sanctum in my laravel backend application. 

![image](https://user-images.githubusercontent.com/14149138/175379940-56f8aa66-e3d5-4129-81ea-e37010d93ae9.png)


However, this doesn't work in thunder-client and I receive a csrf token mismatch error with 419 status code.

**Comment by rangav** [comment]
please remove the `content-type` header and test it again.

the `content-type` header is automatically set the extension

**Comment by rangav** [comment]
Is it possible for me to test those api endpoints, do you have any published version with test account?

**Comment by rangav** [comment]
looks like you have wrong content-type header in the request.

Can you please remove the content-type header and test it again?

**Comment by JayRSG** [comment]
I have removed the content type header and tried but it still gives the same error

**Comment by rangav** [comment]
ok thanks, Dont know what is the reason. and I have not used laravel before.

**Comment by rangav** [comment]
may be post on `stackoverflow`, someone with laravel experience can suggest an answer.

**Comment by glaucomorais** [comment]
Try decoding the value of the cookie from URL to normal string before saving in the environment.

The XSRF-TOKEN ends with "%3D" what it means that is an "=" (equal sign), and that in the X-XSRF-TOKEN cause a mismatch.
![image](https://user-images.githubusercontent.com/1200107/190072731-1ce7ec9c-0399-41f9-8758-5345e8a7943f.png)

**Comment by rangav** [comment]
Custom Scripting is now implemented and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please let me know your feedback.
