### ISSUE TITLE
Broken format in JSON Body

### ISSUE THREAD

**Issue by pacifist-inside** [rangav/thunder-client-support#63]
Hello.
Got broken format in JSON Body when tried to add this json:
`{"siteUser": "someuser", "sitePassword": "fC0]VovncO0]o!<tv"}`
**Looks like it's being corrupted while saving**

## The way to reproduce
1. **This is the first run, everything's fine**
![image](https://user-images.githubusercontent.com/68074212/116066523-d68d0680-a690-11eb-8f46-8f454a4f7f77.png)

1. **After saving to collection json happens to be corrupted:**
![image](https://user-images.githubusercontent.com/68074212/116068026-6aab9d80-a692-11eb-93af-6166758e1b76.png)

*I'm using v1.0.7*

**Comment by rangav** [comment]
Hi @pacifist-inside thanks for reporting the bug, looks like `< `is the issue, i will fix asap.

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14

**Comment by pacifist-inside** [comment]
Works perfectly! Thanks a lot!
