### ISSUE TITLE
Refresh Access Token automatically

### ISSUE THREAD

**Issue by kvart714** [rangav/thunder-client-support#630]
Hello
I regularly use Thunder Client

I have added collections with requests. I also have OAuth authorization configured at the collection level, and all requests inherit it.
Every time the token is expired I get a 401 response from the API. And I have to go to **Collection Settings** -> **OAuth 2** and click the **Generate Token** button.

I would like to have the Refresh Token button in a more convenient location. (may be in Collection context menu?)
Ideally: automatic token generation by 401.

**Comment by rangav** [comment]
@kvart714 thanks for feedback.

duplicate of https://github.com/rangav/thunder-client-support/issues/216

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
