### ISSUE TITLE
Allow switching environment from within Request pannel

### ISSUE THREAD

**Issue by yaugenka** [rangav/thunder-client-support#633]
The title is self-explanatary.

**Comment by ryancabanas** [comment]
I'm on a Mac.  Since the shortcut `Ctrl + E` exists for this action, can you please remove the shortcut `Cmd + Shift + E` that does the same thing?  `Cmd + Shift + E` is overriding a basic VS Code shortcut to show the Explorer window.  Thank you!

**Comment by ryancabanas** [comment]
Hmm.  For some reason, though, if I press `Cmd + Shift + R` to open the Thunder Client window and then I press `Cmd + Shift + E`, the **"Select Active Environment"** dropdown pops up.  If I press `Cmd + Shift + E` again, ***then*** it will open the Explorer window.

Does this not happen for anyone else on a Mac?  Thanks!

**Comment by rangav** [comment]
Thanks for the issue, will look into it.

**Comment by rangav** [comment]
Keyword shortcut issue is tracked here https://github.com/rangav/thunder-client-support/issues/642

**Comment by ryancabanas** [comment]
Thanks!
