### ISSUE TITLE
Import curl directly from `Enter url`

### ISSUE THREAD

**Issue by fabiofdsantos** [rangav/thunder-client-support#638]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Detect the curl command in "Enter url" and avoid the shortcut `ctrl/cmd+U`:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/8303937/176160059-6301f660-0c80-4d7b-8e90-11499e071de3.png">

**Describe alternatives you've considered**

N/A

**Implementation:**

An example of [Insomnia](https://insomnia.rest):

![ezgif-5-e5905eb4f4](https://user-images.githubusercontent.com/8303937/176160932-4e3d5c9b-f8b4-46f6-8445-83d1a8625aaa.gif)

**Comment by rangav** [comment]
@fabiofdsantos thanks for the feedback.

Is there any problem with `ctrl/cmd+U`? which is very similar.

**Comment by fabiofdsantos** [comment]
@rangav
No problem but just "another shortcut" to know. It could be replaced (or extended) by this feature :)

**Comment by fabiofdsantos** [comment]
I understand :+1:
Feel free to re-open this issue if you would accept a PR.
Thanks!
