### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by SmithG1997** [rangav/thunder-client-support#64]
**Is your feature request related to a problem? Please describe.**

When the server responds with a redirect code, the client freezes in 'processing' state.

**Describe the solution you'd like**

There should be an option to automatically follow redirects after an HTTP request just like in Postman

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Hi @SmithG1997, Thanks for reporting issue, i will look into this.

**Comment by rangav** [comment]
Hi @SmithG1997 i have testing with http://thunderclient.io will redirect to https://www.thunderclient.io/ it worked for me. Can post the steps to reproduce the issue. and http code

**Comment by karlmacklin** [comment]
@rangav My guess is that he wants to do the same thing that I want to do: An option to **not** follow redirects.

This is very useful for testing header location responses for different URL:s for example.
I use it all the time in Postman.

**Comment by heinrich-ulbricht** [comment]
I landed here searching for an option to disable automatic redirects for Thunder Client. Since the OP seems to like redirects being followed and @karlmacklin and I _don't_ want that I created a feature request: #239

**Comment by rangav** [comment]
Provided new vscode setting **Follow Redirects** to enable/disable redirects in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0
