### ISSUE TITLE
Is it possible to add a pre-request script to generate a signature Hmac SHA256 

### ISSUE THREAD

**Issue by alex290** [rangav/thunder-client-support#640]
**Implementation:**
To work with Exchanges, you need to encrypt the parameters with a key. In Postman, this is done using a pre-request script. And it is usually encrypted using HmacSHA256. Here's how it looks like

![](https://i.imgur.com/USGYIhg.png)

Is it possible to implement this

**Comment by rangav** [comment]
@alex290 currently not possible, its in roadmap
