### ISSUE TITLE
No saves more than 2780081 bytes to a variable

### ISSUE THREAD

**Issue by XiveZ** [rangav/thunder-client-support#643]
Hello. There is a problem when adding data to the regular - it is not able to save more than 2780081 bytes. Can you add support for larger long values?

The data is written to the variable as json

**Comment by rangav** [comment]
@XiveZ don’t have any limit for environment variable, may be json has some limits.

can you share the sample variable value, I will test and verify

**Comment by XiveZ** [comment]
@rangav 
Only if the data is drafted.
[test_json.txt](https://github.com/rangav/thunder-client-support/files/9028016/test_json.txt)
link to json generator generator-https://json-generator.com/
 
In my case the response from the server contains approximately 50 000 to 100 000 lines.
Minimum number of symbols - 1 500 000, maximum number of symbols - 2 500 000

**Comment by rangav** [comment]
Why you want to save 100K lines of json in environment variable?

**Comment by XiveZ** [comment]
for easy data manipulation

**Comment by rangav** [comment]
May be save only part of json, env variables not intended for that purpose
