### ISSUE TITLE
Environment variables don't work from dotenv file when using thunder client in wsl

### ISSUE THREAD

**Issue by prince-b4u** [rangav/thunder-client-support#648]
**Describe the bug**
When trying to use environment variables from a dotenv file in a project opened in WSL the environment variable don't work/aren't loaded (the variable is gray), but when I open the same project in windows the environment variables work (the variable is green).

**To Reproduce**
I created a simple project using json placeholder [here](https://github.com/prince-b4u/test) with a dotenv included

- Clone the repository in wsl and switch to the Linux branch and update the Test environment to point to the dotenv file in the project and run the JSONPH request in the TEST collection which will result in the following error `Couldn't resolve the hostname to an IP address, Verify Url: http://%7B%7BURL%7D%7D/posts`

**Expected behavior**
- for the request to run and get the following response back 
`
{
  "title": "foo",
  "body": "bar",
  "userId": 1
}
`
- To get the proper result  clone the repository in Windows and switch to the windows branch and update the Test environment to point to the dotenv file in the project and run the JSONPH request in the TEST collection

**Platform:** 
 - OS: Windows/ WSL
 - vscode version: 1.68.1
 - extension version:

**Comment by rangav** [comment]
@prince-b4u this could be path issue in wsl.

try adding this vscode setting when working with WSL https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by rangav** [comment]
where did you set the setting? 

may try close and open the vscode?

Can you share some screenshots if possible.

**Comment by prince-b4u** [comment]
@rangav I tried setting it in the User then Remote and Workspace settings all with the same result and I opened and closed vscode every time I set it
I attached screenshots of the problem I was experiencing 

![Linux dotenv](https://user-images.githubusercontent.com/103312444/177314602-2c6cdd99-0636-49c7-80f9-c520daddebed.png)
![Linux Environment](https://user-images.githubusercontent.com/103312444/177314610-88238387-1397-4b21-8685-067ed754a843.png)
![Linux Request](https://user-images.githubusercontent.com/103312444/177314613-df8302c3-f8c4-4ee0-8f4f-a0062fc7302a.png)

**Comment by prince-b4u** [comment]
@rangav  here is the same project in window

![Windows dotenv](https://user-images.githubusercontent.com/103312444/177315030-986bca66-6f5f-4afc-8fea-aabcad07af44.png)
![Windows Environment](https://user-images.githubusercontent.com/103312444/177315032-a8caabbf-652e-45bd-b55c-64499306c8f4.png)
![Windows Request](https://user-images.githubusercontent.com/103312444/177315035-d762cb02-47e8-4f5d-b82f-3ae2adf0f613.png)
s

**Comment by rangav** [comment]
Will verify and get back to you

**Comment by rangav** [comment]
its working for me. can you share the settings screenshot?

**Comment by rangav** [comment]
my working screenshots

![image](https://user-images.githubusercontent.com/8637550/177320815-136955c3-04f7-4d11-814a-8f9d958e1088.png)

![image](https://user-images.githubusercontent.com/8637550/177320941-fc8419a2-2a4c-4fc7-8dc2-d62aeb2a3ff5.png)

![image](https://user-images.githubusercontent.com/8637550/177321025-778f22be-4348-48be-a436-4afa8443bdbd.png)

**Comment by prince-b4u** [comment]
@rangav  then there must be something I'm missing on my end I check and update if I find the issue

**Comment by rangav** [comment]
you wsl path did not start with `\\wsl$`?

**Comment by rangav** [comment]
where is the request located? and how did you assign the environment to it?

**Comment by prince-b4u** [comment]
> your wsl path did not start with `\\wsl$`?

I use a custom wsl install of Fedora, so I don't have that file path but I figured out the issue I was having I had the `Save To Workspace` setting enabled, when that is enabled I can't interact with the extension but with it disabled the environment variables work
![Update](https://user-images.githubusercontent.com/103312444/177325320-7f114082-dbaf-481c-91a2-b30d3eba45df.png)

**Comment by rangav** [comment]
thats right, when I open the workspace folder in vscode in wsl, with `Save To Workspace` option enabled, then its not working.

Will look into that issue.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.
