### ISSUE TITLE
Code Snippet - Raw HTTP Request

### ISSUE THREAD

**Issue by kfird214** [rangav/thunder-client-support#649]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be cool to get the raw HTTP request as another option of Code Snippet.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
