### ISSUE TITLE
generate the OAuth token in a local env

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [rangav/thunder-client-support#652]
**Is your feature request related to a problem? Please describe.**
When using the OAuth2 feature the generated access token is written inside of a commitable file when using the git sync feature

**Describe the solution you'd like**
I think the better solution would be to write the generated access token inside a localEnv variable and use this variable inside the request or collection

**Describe alternatives you've considered**
there is a workaround but it has to be donne manually which can become annoying for short duration access token

**Implementation:**
I don't have any experience making vscode extentions so I don't really know how to start

Thanks you for your time,

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

Now all the tokens are saved local cache, and not in json files. So no need to save to Local Env.

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
