### ISSUE TITLE
making the local env exportable

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [rangav/thunder-client-support#653]
**Is your feature request related to a problem? Please describe.**
there is no easy way to export the local env.

**Describe the solution you'd like**
a way to export the local env file
 
**Describe alternatives you've considered**
the workaround is to get the file from the file location 
https://github.com/rangav/thunder-client-support/discussions/636

thanks you for your time

**Comment by rangav** [comment]
@gabrielsantosblanchet thanks, will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to v1.16.7

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.16.7
