### ISSUE TITLE
Bad formatting when using Json in the editor

### ISSUE THREAD

**Issue by sant123** [rangav/thunder-client-support#655]
**Describe the bug**

Hi, when writing some Json inside the editor it shows a strange formatting.

**To Reproduce**

https://user-images.githubusercontent.com/7959437/178035877-4bb2833b-67b8-4394-973a-22b87986708e.mp4

**Expected behavior**

Should show a normal formatting as editing any file in Visual Studio Code

**Platform:** 
 - OS: Fedora 36
 - vscode version: v1.69.0
 - extension version: v1.16.6

**Solution:**

Unfortunately not 😕

**Comment by rangav** [comment]
@sant123 thanks for reporting, will look into it.

**Comment by sant123** [comment]
Perhaps https://github.com/microsoft/vscode/issues/78058 and https://github.com/microsoft/vscode/issues/80170 are related? 

I have tried the solutions in there but had no success. VS Code works normally but the extension.

Thanks @rangav

**Comment by rangav** [comment]
The extension uses Ace Editor for body fields. 
https://github.com/ajaxorg/ace

see if you can find any solution in their github page.

**Comment by sant123** [comment]
I set this:

![image](https://user-images.githubusercontent.com/7959437/178042058-95e29d72-722e-4df1-b22c-ab62a9655681.png)

In VS Code but still didn't work :/

**Comment by sant123** [comment]
@rangav are you able to reproduce it?

**Comment by sant123** [comment]
> you changed in wrong location.
> 
> You need to change one of the extension file.
> 
> steps:
> 
>     * Find extension folder in `~/.vscode/extensions` which is `rangav.vscode-thunder-client-1.16.6`
> 
>     * then open `main.min.css` file located in `dist/main.min.css`
> 
>     * then add this line `font-family: 'Source Code Pro', monospace;` to `.ace_editor { color: var(--custom-input-color); }`
> 
> 
> are you ok to modify css?

It works!

https://user-images.githubusercontent.com/7959437/178053073-2645c7b8-296c-44e5-a94d-4e6ebf2e6e07.mp4

@rangav could you let me know when a new version is released?

Thank you very much, this workaround works for me 😃

**Comment by rangav** [comment]
Don’t know whether this issue applies to all Linux distros? That’s why this fix was not included yet

**Comment by sant123** [comment]
I know what you mean, well looking at the previous issues it is presented on:

- Manjaro using KDE
- Mint using Cinammon
- Fedora 36 using KDE (this issue)

Also tested on Mac and works good.

**Comment by sant123** [comment]
If anyone uses Deno run this script to fix the issue:

``` ts
const fix = ".ace_editor{font-family:'Source Code Pro',monospace;}";

const path = `${Deno.env.get(
  'HOME',
)}/.vscode/extensions/rangav.vscode-thunder-client-1.16.6/dist/main.min.css`;

const cssFile = Deno.openSync(path, { append: true });
cssFile.writeSync(new TextEncoder().encode(fix));

console.log('done!');

```

And run it as:
`deno run --allow-write --allow-env mod.ts`

**Comment by sant123** [comment]
Works perfect! Thank you!

**Comment by rangav** [comment]
Thank you for confirmation
