### ISSUE TITLE
Extend {{#date}} system variable capabilities 

### ISSUE THREAD

**Issue by haffi96** [rangav/thunder-client-support#656]
**Is your feature request related to a problem? Please describe.**

Adding the ability to auto-generate a timestamp which is +/- of the current timestamp

**Describe the solution you'd like**

Existing functionality: {{#date,'X'}} lets us auto-generate the **current** timestamps for request

Can this be extended to allow for this:
Something like {{#date+/-1day, 'X'}} or {{#date+/-1hour}}

Where {{#date+1-day, 'X'}} would give the timestamp of current datetime + 1 day

Python snippet of what I mean:
```python
In [8]: now = datetime.now().replace(microsecond=0)

In [9]: now
Out[9]: datetime.datetime(2022, 7, 8, 20, 33, 49)

In [10]: now.timestamp()
Out[10]: 1657308829.0

In [11]: tmrw = now + timedelta(days=1)

In [12]: tmrw
Out[12]: datetime.datetime(2022, 7, 9, 20, 33, 49)

In [13]: tmrw.timestamp()
Out[13]: 1657395229.0
```

**Implementation:**
Not sure but wouldn't mind contributing if system variables were open sourced

**Comment by rangav** [comment]
@haffi96 thanks, will add to roadmap

I am thinking of this syntax.

`{{#date, ‘X’, ‘+1day’}}`

**Comment by cgatian** [comment]
I think the syntax should be :

`{{#date, 'day', 1}}`

Allowing 

`{{#date, 'second', -200}}`

**Comment by rangav** [comment]
@cgatian 2nd argument we are using it for date format e.g `{{#date, 'YYYY-MM-DD hh:mm:ss:fff'}}`.

 So we have use these date manipulation args after.

**Comment by cgatian** [comment]
Sorry for my laziness on that, I didn't look at the existing API and was browsing this issue in the middle of the night 😄 . 

My head was at an API similar to [date-fns](https://date-fns.org/v2.28.0/docs/add).

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.1

Please let me know your feedback.

<img width="1304" alt="Screenshot 2022-10-19 at 08 12 16" src="https://user-images.githubusercontent.com/8637550/196635142-a778cb30-25ca-479e-99d8-ada66bf2e66b.png">

**Comment by haffi96** [comment]
Amazing 👏🏽 , this will be really helpful going forward.

Side note: Are you planning on open sourcing the actual implementations of this project in the future? No worries if not

**Comment by rangav** [comment]
@haffi96 glad you like it. 

I may open source some parts fo the extension in future.
