### ISSUE TITLE
HTML Table response incorrectly indented

### ISSUE THREAD

**Issue by crystalfp** [rangav/thunder-client-support#657]
**Describe the bug**

Accessing a local server that returns a HTML table (see below) renders incorrectly the table adding not existing indentation making the response difficult to read and different from the true response.

![image](https://user-images.githubusercontent.com/865866/178226345-b2ba82ed-694c-4702-978e-0c00623fa6a9.png)

**To Reproduce**

Unfortunately this is a local server API that cannot be accessed from outside.

**Expected behavior**

The true output from the api is (with a single \n at the end of each line):
```
<h1>This is the server API for the Idea Igniter Environment</h1>
<h2>Paths</h2>
<table>
<tr><td>/api</td><td>HEAD, GET</td><tr>
<tr><td>/api/config</td><td>HEAD, GET, PUT</td><tr>
<tr><td>/api/config/exports</td><td>HEAD, GET</td><tr>
<tr><td>/api/ref/tags</td><td>HEAD, GET, PUT</td><tr>
<tr><td>/api/projects</td><td>HEAD, GET, POST</td><tr>
<tr><td>/api/projects/:uuid</td><td>HEAD, GET, DELETE, PUT</td><tr>
<tr><td>/api/kb</td><td>HEAD, GET, POST</td><tr>
<tr><td>/api/kb/:uuid</td><td>HEAD, GET, PUT</td><tr>
<tr><td>/api/worklist</td><td>HEAD, GET, PUT</td><tr>
<tr><td>/api/annotations/:duuid</td><td>HEAD, GET</td><tr>
<tr><td>/api/annotations/:duuid/:auuid</td><td>PUT</td><tr>
<tr><td>/api/server</td><td>POST</td><tr>
</table>
```
I expect to see this in the response without added formatting.

**Platform:** 
 - OS: Windows 11 64bits
 - vscode version: 1.69.0 
 - extension version: 1.16.6

**Solution:**

No, don't know the solution

**Comment by rangav** [comment]
@crystalfp thanks for reporting, will look into it.

**Comment by rangav** [comment]
looks like your html format is wrong.

all the `<tr>` tags not closed properly. ending of tr tag should be `</tr>`

**Comment by crystalfp** [comment]
Red face. Your are right. Never noticed. Thanks! 

Anyway, the response is formatted, it is not the output of the API. There are two spaces at the beginning of the table lines that are not in the API output.

Maybe adding a "raw response" tab that show what is output by the API and leave the "response" pretty printed tab in place.
Just a suggestion.

**Comment by rangav** [comment]
@crystalfp thanks for the feedback.
