### ISSUE TITLE
Enabled Save to Workspace and lost everything after restart

### ISSUE THREAD

**Issue by kabeza** [rangav/thunder-client-support#658]
**Describe the bug**
I've enabled "Save to Workspace" setting, restarted VSCode and lost all my collections/requests
Thanks!

**To Reproduce**
File -> Preferences -> Settings
Extensions -> Thunder Client 
Enable "Save to Workspace"
Define "Custom Location" with $HOME/path
Restart VSCode

**Expected behavior**
I expected not to loose my already created collections/requests

**Platform:** 
 - OS: Windows
 - vscode version: 1.69.0
 - extension version: 1.16.6

**Solution:**
I guess there's none to recover

**Comment by rangav** [comment]
@kabeza your original is located in default location.

`%APPDATA%\Code\User\globalStorage\rangav.vscode-thunder-client`

copy these files to the new location
![image](https://user-images.githubusercontent.com/8637550/178351519-01c1e8fd-87bb-42a2-9832-8f162a8c3ab6.png)

Note: you can use either `Save to Workspace` or `Custom Location` but not both.

if you use both then `Save o Workspace` will take preference


Documentation here
https://github.com/rangav/thunder-client-support#team

**Comment by kabeza** [comment]
Hi @rangav 
Didn't know original data was being saved into %APPDATA% folder
Thanks a lot
I've copied those files to new synced one and all works great

**Comment by rangav** [comment]
@kabeza thanks for confirmation 👍
