### ISSUE TITLE
OAuth 2.0: Add support for password credentials flow

### ISSUE THREAD

**Issue by salomaosnff** [rangav/thunder-client-support#66]
**Is your feature request related to a problem? Please describe.**

Today, it is not possible to obtain access tokens using a username and password.

**Describe the solution you'd like**
Add the Password option in the Grant Type checkbox on the OAuth 2.0 tab.

**Describe alternatives you've considered**

Postman and Insomnia have this feature.

**Implementation:**

**Comment by rangav** [comment]
Hi @salomaosnff will add to the roadmap

**Comment by rangav** [comment]
This feature is implemented now in v1.3.0
https://github.com/rangav/thunder-client-support/releases/tag/1.3.0
Let me know if any questions.
