### ISSUE TITLE
VS Code win10 + WSL extension not working

### ISSUE THREAD

**Issue by AdamRussak** [rangav/thunder-client-support#661]
**Describe the bug**
after installing extension (and reload) the extension buttons are not responding.
* extension shows in VS Code but cant do anything

**To Reproduce**
not sure how to reproduce:
installed on wsl ubuntu 20.4
on windows 10

**Expected behavior**
after installation of the extension start working on it without any issues

**Platform:** 
 - OS: widnows
 - vscode version: 1.69.1
 - extension version: v1.16.6

**Solution:**
didn't find it yet

**Comment by rangav** [comment]
@AdamRussak did you enable the thunder client vs code setting `Save To Workspace`?

**Comment by AdamRussak** [comment]
By default it was off.
But i did turned it on and restored the client.
still no go.

**Comment by AdamRussak** [comment]
turning it off did the trick.
Does it make sense?
what was the cause?

**Comment by AdamRussak** [comment]
i reopened to allow you to close it if its not an issue (or leave it open if it is..)

**Comment by rangav** [comment]
@AdamRussak when `Save to workspace` enabled the extension is not able to read file paths correctly. We will close issue for now.
