### ISSUE TITLE
Extensions fails loading when using Gitpod on an iPad

### ISSUE THREAD

**Issue by wilmarques** [rangav/thunder-client-support#662]
**Describe the bug**
Gitpod is a solution similar to Github Codespaces, which is a virtual development environment used directly from a browser.
When I open a repo on Gitpod and try to use Thunder Client, some views won't load correctly and is not possible to fire a request.

Image:
![Example of Thunder Client views not loaded correctly](https://user-images.githubusercontent.com/1015148/179132612-0950beab-816b-4174-9ae8-3cfc9458a727.jpeg)

**To Reproduce**
Load a Gitpod workspace on an iPad, install Thunder Client and try to request any API.

> Example repo: https://gitpod.io/#/https://github.com/wilmarques/bootcamp-dio-angular-java-back/tree/ready 
> This link will open a new Gitpod workspace with Thunder Client already installed.

**Expected behavior**
The extension should load as expected.

**Platform:** 
 - OS: iPadOS 15
 - vscode version: Version: 1.69.1
 - extension version: Latest
 - Browser: Safari

**Solution:**
:(

**Comment by rangav** [comment]
Thanks @wilmarques for reporting, will look into it.

**Comment by thunderclient** [comment]
Hi @wilmarques I tested it, it is working fine for me

![image](https://user-images.githubusercontent.com/98588816/180311211-66db185e-9991-466c-adb6-04b4e6c47f2c.png)

**Comment by thunderclient** [comment]
download the latest version of extension and try it

**Comment by rangav** [comment]
Hi @wilmarques I tested it, it is working fine for me

![image](https://user-images.githubusercontent.com/98588816/180311211-66db185e-9991-466c-adb6-04b4e6c47f2c.png)

**Comment by rangav** [comment]
Thunder client was not installed, I have to download it manually and install it.

 download the latest version from below link and try it
 https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

**Comment by wilmarques** [comment]
I see you have tested it on Chrome, right? The issue only happens on an iPad :(

**Comment by wilmarques** [comment]
Just tried again for you to see:

![Gitpod about page when running on iPad and Thunder Client not showing up on this setup](https://user-images.githubusercontent.com/1015148/180606163-16fccc87-29b9-40dc-bdee-a5846bf63449.png)

**Comment by rangav** [comment]
Ok , right I have tested on desktop chrome. Will test on iPad and get back to you.

**Comment by wilmarques** [comment]
Just tried on Safari for Mac and the issues also happens:

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/1015148/180606596-1bafe529-cd9a-42b5-b992-61fb855fa636.png">

**Comment by rangav** [comment]
May be it’s related to safari browser issue, will look into it.

**Comment by rangav** [comment]
Just tested on safari, there are some javascript loading issues, Will investigate and fix asap.

**Comment by rangav** [comment]
meanwhile you can try chrome browser in iPad

**Comment by wilmarques** [comment]
I'd love to use Chrome, but unfortunately any browser on iPad is just a skin for Safari :(
You can see that when you open the same repo on Chrome and go to About Page. Like below:

![Gitpod about page when running on Chrome for iPad and Thunder Client not showing up on this setup](https://user-images.githubusercontent.com/1015148/180613409-8b959927-ee0b-495f-a683-fbab829c95cd.png)

**Comment by rangav** [comment]
Thanks got it. Will look into it asap.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

Please let me know your feedback.
