### ISSUE TITLE
Increase Collapsable arrow size in JSON output?

### ISSUE THREAD

**Issue by ooobii** [rangav/thunder-client-support#665]
**Is your feature request related to a problem? Please describe.**
No, it's not really a problem / bug that exists, but it sure would be handy!

**Describe the solution you'd like**
It would be extremely helpful to have JSON objects in an API result be collapsible - hiding their child property values in a tree-like fashion. 

**Describe alternatives you've considered**
Copying the JSON output from an API call result and pasting it into a blank VSCode editor window accomplishes this using VSCode's folding functionality, but being able to do it inside of the ThunderClient editor would be extremely helpful 😄 

**Implementation:**
I don't really have enough skill with TypeScript or VSCode extension development to implement something like this 😢

**Comment by rangav** [comment]
@ooobii not sure you noticed or not, its already possible to collapse json response.

also you can open response in vscode without copy paste

you can try this url and test it https://httpbin.org/anything

![image](https://user-images.githubusercontent.com/8637550/179573464-e4f266fe-6607-424f-8859-39efc15bdd2b.png)

**Comment by ooobii** [comment]
Wow... look at that!

Thank you so much for pointing this out. Would increasing the size of the arrow be something to consider? :)

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.0

Please let me know your feedback.
