### ISSUE TITLE
Auth: Add support for grant_type=“refresh_token”

### ISSUE THREAD

**Issue by jimmybutton** [rangav/thunder-client-support#668]
First of all, I just wanted to say how much I like Thunder Client. It's such a great productivity tool!

I recently discovered the built-in OAuth 2 authorization options. There are currently four options available for grant type. I'd like to be able to use `refresh_token` as a grant type to generate the access token using that method.

Or maybe I'm missing something and I can already do what I want to using one of the existing options. If so, please let me know. Many thanks!

**Comment by rangav** [comment]
Thanks @jimmybutton, Glad you like the extension :)
 
Currently not possible with OAuth tab, but you can send normal post request for refresh_token also.

details below link, use `form-encoded` tab
https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/

Let me know if the above will work for you or not.

**Comment by jimmybutton** [comment]
Yes, that works for me. Many thanks!

**Comment by rangav** [comment]
related to #216

**Comment by rangav** [comment]
I am closing this issue, feel free re-open if needed

**Comment by rangav** [comment]
Now the tokens are auto refreshed automatically in new update, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.
