### ISSUE TITLE
Failed to install 'rangav.vscode-thunder-client 

### ISSUE THREAD

**Issue by vikash-aquera** [rangav/thunder-client-support#67]
Failed to install 'rangav.vscode-thunder-client - not able to install manually. Tried multiple times but getting the same error. Please let me know how to install it so I can introduce it to my team.
System - MacBook Pro (16-inch, 2019),2.6 GHz 6-Core Intel Core i7, macOS Big SUR [11.2.3].
VSCode - Version 1.30.2 (1.30.2)
Please help me to install it.

**Comment by rangav** [comment]
Hi @vikash-aquera thanks for reporting the issue. Can you update the VS Code? as the current version is 1.55. you seem to have old version.
