### ISSUE TITLE
Project folder store

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rangav/thunder-client-support#670]
## Hi, I suggest that:
1- every project (git repo) has it own thunder client folder that to store collections and environments and other related data.
2- if working inside workspace that include multiple project then when opening thunder client ui let choose from witch project need stored data

## Advantages of the suggestion are:

1- no need to account sync every things stored inside project repo.
2- let developer export there projects with there api's testing collections.

i hope this suggestion be good idea for thunder client extension

Thank you.

**Comment by rangav** [comment]
Thanks @abdosaeedelhassan for the feedback. 

Choosing the location everytime may not be easy for everyone.

Did you read this section fully?
https://github.com/rangav/thunder-client-support#git-sync

We have 3 options to choose. one of them might fit your use-case
<img width="975" alt="Screenshot 2022-07-20 at 09 53 35" src="https://user-images.githubusercontent.com/8637550/179940966-36e129f4-7d83-4c3a-9926-f6d00003f188.png">

**Comment by abdosaeedelhassan** [comment]
Yes, i hope store location to be per project repo also as well as it per constant workspace path for all projects, thank you

**Comment by rangav** [comment]
@abdosaeedelhassan do you still have any questions?

shall I close this issue?

**Comment by abdosaeedelhassan** [comment]
No, Thank you.
