### ISSUE TITLE
How to query GitHub API?

### ISSUE THREAD

**Issue by mbaas2** [rangav/thunder-client-support#671]
I must missing something elementary - but I just don't see it. Would appreciate some help...

As an example, I'm trying to use the [releases API](https://docs.github.com/en/rest/releases/releases#get-the-latest-release) 

So, I've entered the following in the headers tab:
![image](https://user-images.githubusercontent.com/5645494/180011928-644d0345-b950-4a20-9689-1d610dbf7049.png)

And Auth has my API token with prefix `token`.

Clicking "Send" gives result below:
![image](https://user-images.githubusercontent.com/5645494/180012231-e559a69b-c1d0-4b26-b868-c8307d6481a8.png)

**Comment by rangav** [comment]
@mbaas2 will test and get back to you

**Comment by thunderclient** [comment]
its working for me
url tested: https://api.github.com/repos/microsoft/vscode/releases/latest
![image](https://user-images.githubusercontent.com/98588816/180018409-c4f5740f-a46e-4f55-b2b2-36537cfaf5da.png)

**Comment by rangav** [comment]
its working for me
url tested: https://api.github.com/repos/microsoft/vscode/releases/latest
![image](https://user-images.githubusercontent.com/98588816/180018409-c4f5740f-a46e-4f55-b2b2-36537cfaf5da.png)

**Comment by mbaas2** [comment]
Argh - I noticed my extension wasn't uptodate. After updating it works fine now!  (Sorry, should have checked that before bothering you!)

**Comment by rangav** [comment]
you can use ` Auth -> Bearer ` tab or header both will work.
