### ISSUE TITLE
Add request linking or referencing

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#672]
**Is your feature request related to a problem? Please describe.**

I've organized my request to mirror the api tree I'm querying but now I want to make a 'routine' or a series of requests in a specific order to achieve something on the server. My current solution was to create a folder and copy the requests that I wanted to execute. But now if I have to fix the original request, I have to change it in 2 places.

**Describe the solution you'd like**

I would like a way for two requests to mirror each other so if I change one, the other also changes.
Or someway to reference a request to be able to create 'routines'

**Describe alternatives you've considered**

**Implementation:**

**Comment by rangav** [comment]
Thanks @andresatierf for the feedback, We have this is roadmap. might start implementation in next month.

there is already existing issue for this https://github.com/rangav/thunder-client-support/issues/249

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.
