### ISSUE TITLE
Cannot use PROPFIND HTTP method

### ISSUE THREAD

**Issue by fidothe** [rangav/thunder-client-support#674]
**Describe the bug**
Thunder Client's list of HTTP verbs is constrained, but doesn't include all the methods in the various HTTP specs - specifically `TRACE` and `CONNECT` from [HTTP 1.1][1], and the methods added by [WebDAV][2] and its variants, like `PROPFIND`, which I need to write tests against.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
[2]: http://webdav.org/

**To Reproduce**
1. Create new request in Thunder Client.
2. Try to select `PROPFIND` from the HTTP verb drop down
3. `PROPFIND` is missing from drop down

**Expected behavior**
1. Create new request in Thunder Client.
2. Select `PROPFIND` from the HTTP verb drop down

**Platform:** 
 - OS: macOS 12
 - vscode version: 1.69.2
 - extension version: 1.16.7

**Solution:**
There are so many standardised but rarely used HTTP methods that it would probably be better to allow text entry of for those cases.

**Comment by rangav** [comment]
Thanks @fidothe for the feedback, will review and enable new methods asap.

**Comment by rangav** [comment]
Do you any sample url to test this method?

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

Please let me know your feedback.
