### ISSUE TITLE
Is there a way to re-order query string parameters?

### ISSUE THREAD

**Issue by ryancabanas** [rangav/thunder-client-support#677]
Very happy with this tool.  Thank you!

I'm just wondering if there's a way to re-order query string parameters?

Thanks!

**Comment by rangav** [comment]
Hi @ryancabanas currently not possible, will add to roadmap.

**Comment by ryancabanas** [comment]
Okay.  Thank you!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.0

Please let me know your feedback.
