### ISSUE TITLE
Auto Encoding Query Parameters

### ISSUE THREAD

**Issue by usimarit** [rangav/thunder-client-support#678]
**Is your feature request related to a problem? Please describe.**
Users now have to manually encode the query params like isostring "2022-01-22T00:00:00+07:00" -> "2022-01-22T00%3A00%3A00%2B07%3A00" and copy the encoded value to Thunder Client's UI to make the requests work
Therefore, it's not UI friendly

**Describe the solution you'd like**
1. Automatically encode query params so that users only need to input "2022-01-22T00:00:00+07:00", not "2022-01-22T00%3A00%3A00%2B07%3A00", the encoded values will be merged to the URL and the UI display unencoded values
2. [Optional] A button to enable/disable query params url encode so that users can choose

**Comment by rangav** [comment]
Thanks @usimarit will add to roadmap 

The extension will auto encode for some of the chars. Auto encode for all chars will cause confusion 

I am planning to include manual encode button - option 2

**Comment by jpinz** [comment]
+! to this. I would love the ability to use path variables and have them be automatically encoded (or at least have the option to enable encoding!)

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.2`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.2

Please let me know your feedback.
