### ISSUE TITLE
Cannot choose setTo option on tests tab

### ISSUE THREAD

**Issue by helmiattastify** [rangav/thunder-client-support#679]
**Describe the bug**
I cannot see after several times trying to use the setTo option

**To Reproduce**
go to the test tab, Klik dropdown setTo, disappear and old data for setTo still exists, but after I remove the old data setTo Option still disappear

**Expected behavior**
I can choose setTo Option on tests tab

**Platform:** 
 - OS: Mac OS latest
 - vscode version:  1.69.1 
 - extension version: v1.16.7

**Solution:**

**Comment by rangav** [comment]
Hi @helmiattastify 

you cannot choose `setTo` Manually, as its only suitable when you select `Set Env Variable` Option.

so it’s not relevant to other functionality

**Comment by helmiattastify** [comment]
@rangav 

https://im.ge/i/FDADcL

**Comment by helmiattastify** [comment]
@rangav thanks i found it
