### ISSUE TITLE
Maintain Open Tabs on shutdown

### ISSUE THREAD

**Issue by jandreaucodes** [rangav/thunder-client-support#680]
**Is your feature request related to a problem? Please describe.**
When restarting VS Code, any open tab you have with code it in persists, even if the tab isn't saved.

Thunder Client does not maintain the open tabs, meaning you've lost anything you have open before restarting the application.

**Describe the solution you'd like**
Keep the tabs open and maintain their state after reboot.

**Describe alternatives you've considered**
None.

**Comment by rangav** [comment]
Thanks @jandreaucodes for the feedback, Will add to roadmap.

**Comment by rangav** [comment]
Closing this issue, track progress in the latest issue #1462

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.21.15`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.21.15

Please test it and let me know your feedback
