### ISSUE TITLE
NOT WORKING FOR LOCALHOST

### ISSUE THREAD

**Issue by eedrxs** [rangav/thunder-client-support#681]
**Describe the bug**
Request made to localhost return with "Connection was forcibly closed by peer" error

**To Reproduce**
Make a request to any port on a locally run server

**Expected behavior**
![Code_hmPKuOVE6c](https://user-images.githubusercontent.com/76642653/180927036-90edec34-1bd4-4707-9900-24065d871af6.png)

**Platform:** 
 - OS: Windows
 - vscode version: 1.69.2
 - extension version: 1.16.7

**Solution:**

**Comment by rangav** [comment]
Hi @eedrxs thanks for reporting

please use IP address and test it

see suggestions here
https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-1079710824

**Comment by eedrxs** [comment]
I tried this and it worked.

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-1079710824

**Comment by rangav** [comment]
Thanks @eedrxs for confirmation 👍

**Comment by rangav** [comment]
you can save baseUrl in env variable, so it will be easy to change in one place.

**Comment by eedrxs** [comment]
Yeah, already did that. Appreciate the feedback.  👍
