### ISSUE TITLE
AWS v4 signed requests with query strings fail signature verification

### ISSUE THREAD

**Issue by kibiz0r** [rangav/thunder-client-support#682]
**Describe the bug**

When using the AWS auth setting to send requests to an AWS API Gateway endpoint, a GET request that contains a query string will result in an error response from AWS, stating:

"The request signature we calculated does not match the signature you provided"

(along with the expected canonical string and string-to-sign)

**To Reproduce**

- Set up an AWS API Gateway endpoint
- Create a new Thunder Client GET request with auth setting of "AWS v4 Signature" and enter your credentials, plus service name "execute-api"
- Make the request, adding no query string
- Add a query string, like ?foo=bar
- See that the request now fails, complaining about a signature mismatch

**Expected behavior**

Signing should follow procedure described here: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

**Platform:** 
 - OS: macOS 12.4
 - vscode version: 1.69.2
 - extension version: 1.16.7

**Solution:**

Not sure.

**Comment by rangav** [comment]
I can reproduce the bug, will fix asap.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

Please let me know your feedback.
