### ISSUE TITLE
Support for files?

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#684]
**Is your feature request related to a problem? Please describe.**

I would like to send a pdf file as binary data

**Describe the solution you'd like**

The ability to send a file as binary data

**Describe alternatives you've considered**

**Implementation:**

Is there any plans to add this feature in the roadmap?

**Comment by rangav** [comment]
Hi @andresatierf 

We already have this feature
![image](https://user-images.githubusercontent.com/8637550/181277250-2c3e9932-0fbb-4622-b6fe-8879ebae13f3.png)
