### ISSUE TITLE
Thunder Client stucked on waiting mode

### ISSUE THREAD

**Issue by ashiqtasdid** [rangav/thunder-client-support#685]
**Describe the bug**
Thunder client extension not working, it's showing waiting mode and upon clicking reload, it says, command 'thunder-client.reload-sidebar' not found
Here is the image: https://ibb.co/Y2R9CJs

**Expected behavior**

**Platform:** 
 - OS: Windows 10 Pro x64
 - vscode version: 1.69.2 (Lastest)
 - extension version: 1.16.7 (Latest)

**Solution:**

**Comment by rangav** [comment]
Hi @ashiqtasdid  can you please restart vscode and try again

**Comment by ashiqtasdid** [comment]
Restarted, Re-Installed, Re-Installed the extension everything

**Comment by rangav** [comment]
dont click the re-load icon, while its loading.

May try installing previous version, sometimes vscode has some strange issues.
![image](https://user-images.githubusercontent.com/8637550/181481561-77328f2e-5373-431e-8371-2cb4e6b770dd.png)

**Comment by rangav** [comment]
Not sure what is causing that issue, is it same error? now

try these installation steps as show in video
https://youtu.be/c3sqFK7zBKE?t=56

**Comment by rangav** [comment]
Hi Try this last option

Please enable this vscode setting `Save To Workspace`, and close and re-open vscode
![image](https://user-images.githubusercontent.com/8637550/181602180-7f3d3a32-c3ab-408c-82ba-887efd3f5880.png)

**Comment by ashiqtasdid** [comment]
Thanks, working fine

**Comment by rangav** [comment]
The above setting will save requests data in your current workspace. might be the files in your default location are corrupted.

You can create `backup` the files and `delete `the files in default location below.
`%APPDATA%\Code\User\globalStorage\rangav.vscode-thunder-client`

then you can uncheck the above vscode setting, then it should work.
