### ISSUE TITLE
Import openapi v3 swagger.json URL

### ISSUE THREAD

**Issue by monim67** [rangav/thunder-client-support#687]
Our backend provides a URL for swagger.json file which updates regularly as development progresses.

Now that we can import swagger.json file, is there any plan of importing swagger from URL? It will be awesome if we could reload the collection from the URL if backend team updates the swagger.json?

_Originally posted by @monim67 in https://github.com/rangav/thunder-client-support/issues/84#issuecomment-1200428100_

**Comment by rangav** [comment]
@monim67 thanks for creating new issue. Will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.17.0`

See all features and bugs fixed released
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0

<img width="289" alt="Screenshot 2022-08-01 at 14 25 54" src="https://user-images.githubusercontent.com/8637550/182158459-46e9806d-a732-480f-92e0-6d51162de5ff.png">

**Comment by monim67** [comment]
After importing a collection from a URL can we sync the collection from the Url later when the swagger schema changes?

**Comment by rangav** [comment]
Sync is not yet possible, you need to re-import

Auto sync questions
- Should the sync needs to completely replace the collection requests.
- What happens you made changes to any request under that collection?

**Comment by monim67** [comment]
Automatic background sync raises a lot of questions. I think user can click a button to download and replace the collection overwriting everything, for example a button named "Download again".

Now if the server content changes, I delete the collection, grab the URL from email, and download the collection. Have to do this quite often as the API is under active development.

**Comment by monim67** [comment]
If download again feature seems like a no go, then a "Copy collection url" button can also be very helpful. Then user don't need to go through email looking for the url, he can just copy collection url, delete it, and add the collection from the url.

**Comment by rangav** [comment]
Thanks for the suggestions

Where you want `Download Again` or `Copy collection url` options?

**Comment by monim67** [comment]
I think these can be sub-menu items on the collection drop-down menu.

**Comment by rangav** [comment]
Thats a good suggestion, This can work for if user imports a `openapi spec from file` too.

Will think of name like like Re-Sync or Sync Again?

**Comment by rangav** [comment]
May be better can you please create a new feature request for this, so its easy to keep track of it.
