### ISSUE TITLE
Did you remove the thunder-codegen?

### ISSUE THREAD

**Issue by babula38** [rangav/thunder-client-support#688]
Did you remove the thunder-codegen?

I could not see the thunder-codegen project any more

**Comment by rangav** [comment]
@babula38 Hi the project is private now. Will give access to it, if someone like to contribute to it.

Would you like to contribute for any language?

**Comment by babula38** [comment]
Yes i am in the process of creating golang client code

**Comment by rangav** [comment]
Not sure you notices or not, our new updates supports lot of languages including golang

<img width="815" alt="Screenshot 2022-08-02 at 16 52 08" src="https://user-images.githubusercontent.com/8637550/182418130-c6acd88a-980a-4bfb-931a-0a296fa4753b.png">

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
