### ISSUE TITLE
Font Size  please add a option adjust font size it is so discusting

### ISSUE THREAD

**Issue by mevishnudas** [rangav/thunder-client-support#689]
Please add a option to set font-size for thunder it is so big.
![image](https://user-images.githubusercontent.com/95905352/182301324-5a5fc9a2-2786-4ec8-aadd-b8c95742059e.png)

**Comment by rangav** [comment]
Hi @mevishnudas 

The font size is based on your vscode editor font size. you can reduce the size is vscode settings

What OS are you using?

**Comment by mevishnudas** [comment]
i am using Windows 11, The Json values are now looking big and congested.
if i adjust font size in vscode settings it will make some readability issues for me, the code's become so small to see.

i found this problem today yesterday all fonts are normal 

Font Size 22
![image](https://user-images.githubusercontent.com/95905352/182302667-72f75bc7-de70-4b7f-af7a-8d96db56eda3.png)

Font size 16 
![image](https://user-images.githubusercontent.com/95905352/182302990-2e8edff4-c6cf-46d9-925e-8e4898a8fe7d.png)

**Comment by rangav** [comment]
Thanks for sharing screenshots.

Please install previous version of the extension until I fix this.

**Comment by mevishnudas** [comment]
Thank you i truly appreciated your effort <3

**Comment by rangav** [comment]
I just now fixed this and published `v1.17.1` to marketplace. please update and use the new vscode setting to set custom font size

Let me know your feedback.

<img width="755" alt="Screenshot 2022-08-02 at 10 48 33" src="https://user-images.githubusercontent.com/8637550/182346414-f6fd6b9a-a72b-41a9-9b49-ddfb41554937.png">

**Comment by mevishnudas** [comment]
You are osm dude. I Love thunder client more.🔥🔥🔥🔥

**Comment by rangav** [comment]
Glad you like it, Is it looking better now?

**Comment by rangav** [comment]
Just now added another vscode setting along with this, might be useful
<img width="716" alt="Screenshot 2022-08-02 at 10 52 20" src="https://user-images.githubusercontent.com/8637550/182346803-b8f1de07-f43a-409f-9461-eb820ff7d23d.png">

**Comment by mevishnudas** [comment]
Perfect 🌟
![image](https://user-images.githubusercontent.com/95905352/182356327-46d26b13-42ce-48a4-b6d8-6fdf2348df1d.png)

**Comment by rangav** [comment]
Thank you for confirmation
