### ISSUE TITLE
Making a OAuth2 call and retrieve the code to, then, call an api URI

### ISSUE THREAD

**Issue by cavo789** [rangav/thunder-client-support#690]
Hi all,

First of all, many thanks for both the quality of the addon and the speed of your feedback (https://dev.to/cavo789/comment/20hee).

So, what I was trying to do is to be able to debug a PHP API route (Laravel). Should works but the route is protected an OAUTH2 middleware (so I need to first make a valid login).

In vscode, I've created a collection called API. Then I click on the `three dots button` and go to the `Auth` tab. This done, I click on the `OAuth 2` link.

From there, I'm not sure which values should be filled in... (so I'm certainly doing something wrong).

![2022-08-02_09h30_48](https://user-images.githubusercontent.com/355999/182317725-6b91284d-c607-4c55-90cf-1de28248e791.png)

Here are my environment variables:

![2022-08-02_09h31_26](https://user-images.githubusercontent.com/355999/182318121-aa674410-8873-48c9-9cf1-35d3b770c3fe.png)

By clicking on the `Generate Token` button, my browser is started, the `oauth_auth_URL` URL (`http://xxxxx/oauth/authorize?client_name={{oauth_client_name}}`) is displayed and I can make a login using a valid email/password. 

On that login page, I click on the `Login` button and, then, I'm not sure what should happens.  

Should the login page redirect to the `Thunder client` (how to do this?) so the code can be captured or should the login continue to my application ?  In a normal use, after the login, the page is redirecting to `http://xxxxx/saveCode` but, in this case, how to set up `Thunder Client` to use the code ?

I miss something, for sure.

Thanks in advance !

**Comment by rangav** [comment]
HI @cavo789 thanks for sharing the details.

After you login, auth server will generate auth code, that needs to be passed to extension.

- Use the default callback url and add it to your auth server valid callback url list, this will get the code automatically to extension.  - `https://www.thunderclient.com/oauth/callback`

**Comment by rangav** [comment]
<img width="766" alt="Screenshot 2022-08-02 at 09 26 08" src="https://user-images.githubusercontent.com/8637550/182328876-ce44afd5-745d-4bfa-b3b9-3d4ceb0f9680.png">

**Comment by cavo789** [comment]
So fast...

I've changed the callback URL to the one you've mentioned here above.

After the login, the code is redirecting to `http://localhost:6789/callback?code=xxx`, which is probably better. I can see a very long code and should I copy/paste it myself in the `OAuth Authentication` area?

I've paste it and click on the `Save` button

![2022-08-02_10h42_21](https://user-images.githubusercontent.com/355999/182332151-0c46f85a-a565-4c90-bbbd-8e6fe850fb19.png)
 
When trying to run the API once more, I got an error 500 with this text: `Route [login] not defined. (500 Internal Server Error)`.  That one is generated by Laravel when the authentication wasn't retrieved.  

Can you confirm please if I was doing right i.e. copy/paste the code in the `Access Token` area, save and rerun the API? I've the feeling that the authentication was not correctly done.

Thanks

**Comment by rangav** [comment]
Once the token is generated, it will automatically add to all requests in the collections, you `dont` need to copy/paste again.

After token is generated, run the request thats needs the token and see the result.

**Comment by cavo789** [comment]
Ok, so just click on `Generate token`, fill in my login/email on my own login page, see the `Success! Please close this tab!` and run the request again (that one is saved in the correction).  Sorry, but didn't work (but this is perhaps something wrong in my PHP code).  How can I validate that the token was correctly saved and used?

![2022-08-02_11h08_23](https://user-images.githubusercontent.com/355999/182337753-8c435773-12f7-4a22-b069-0c5de1425917.png)

I see in my vscode status bar an error **Response code 45 (Method Not Allowed); Source: Thunder Client (Extension)**

![2022-08-02_11h07_28](https://user-images.githubusercontent.com/355999/182337552-8a44072a-347f-4a54-8c9d-5d6cee5f3f43.png)

When trying to get more info in the "Developper tools" (CTRL-SHIFT-I), I've only a stack trace with nothing really usefull to me:

![2022-08-02_11h07_09](https://user-images.githubusercontent.com/355999/182337480-4965766b-c8cd-4239-bd88-df983bdefe3b.png)

**Comment by rangav** [comment]
you can put a break point in your code and check for request headers, you should see `authorization` header with the code

**Comment by rangav** [comment]
> ![](https://user-images.githubusercontent.com/355999/182337552-8a44072a-347f-4a54-8c9d-5d6cee5f3f43.png)

This error happened when you generate auth2 code right?

**Comment by cavo789** [comment]
> > ![](https://user-images.githubusercontent.com/355999/182337552-8a44072a-347f-4a54-8c9d-5d6cee5f3f43.png)
> 
> This error happened when you try to generate auth2 code right?

Correct. Just after `Generate Token` and once my login/password has been filled in.

**Comment by rangav** [comment]
close the view and re-open and try again.

**Comment by cavo789** [comment]
I've quit vscode and shutdown my browser.  Then try again (vsccode -> collections ->  the one called API -> three dots button -> Settings -> Auth -> OAuth2 -> Generate Token). The browser is then opened, I make a login, an URL liek `http://localhost:6789/callback?code=xxxx` is displayed and, back to vscode and same error 405.

Changed my default browser to Edge and same story.

(sorry for all my questions)

**Comment by rangav** [comment]
were you able to generate code earlier? did you change any settings? You can see the `output window` for log details about the oauth request

**Comment by cavo789** [comment]
Not sure to fully follow you : by clicking on Generate token, my login page is displayed then I can fill in my email / password and click on login. Then, a browser window is displayed with an URL like `http://localhost:6789/callback?code=xxxx` (so I can see the code in the URL). That page is saying `Success! Please close this tab!`. 

On vscode side, I got the 405 error as a vscode notification in my status bar.

The output window (menu `View` - `Output` in vscode; CTRL-SHIFT-U) is totally empty.

![2022-08-02_11h53_42](https://user-images.githubusercontent.com/355999/182346807-8606eb9c-bb1f-48e8-b961-65ce2fec8b72.png)

(once again sorry for all that questions)

**Comment by rangav** [comment]
change he dropdown from Tasks to Thunder Client. it will have secrets so `dont share image` here.
<img width="399" alt="Screenshot 2022-08-02 at 10 56 43" src="https://user-images.githubusercontent.com/8637550/182347508-a92a0dda-c949-4c8a-924c-d0270a720f92.png">

**Comment by rangav** [comment]
Looks like 2nd step of auth code process has failed..

**Comment by cavo789** [comment]
Oh, nice !!!

I get this:

```text
OAuth2 AuthUrl Request:
http://xxxx&redirect_uri=https%3A%2F%2Fwww.thunderclient.com%2Foauth%2Fcallback
Request Method: GET

OAuth2 TokenUrl Request: http://yyyy/saveCode
Request Method: POST
Request Headers:
{
  "Content-Type": "application/x-www-form-urlencoded",
  "Authorization": "Basic MTplSWt6aHo4emhsdlMzZWhKTXZOcVBacHRwSUtzQ1FXakZVeEFBRjhh"
}
Request Body:
grant_type=authorization_code&code=xxxx&redirect_uri=https%3A%2F%2Fwww.thunderclient.com%2Foauth%2Fcallback&client_id=1
```

The `xxxx` part is my login page and the `yyyy` part is the redirection URL for my client.

>Looks like 2nd step of auth code process has failed..
Ok, that means my `yyyy` part; I'll investigate that part more and come back to give you a feedback.

**Tremendous support; thanks!**

**Comment by rangav** [comment]
may be try sending as auth Header in the last downdown
<img width="758" alt="Screenshot 2022-08-02 at 11 26 54" src="https://user-images.githubusercontent.com/8637550/182353337-43a1f37c-9c67-4eed-a2af-e826eb50f81d.png">

**Comment by cavo789** [comment]
> Looks like 2nd step of auth code process has failed..

Yes, it seems indeed that the problem comes from the 2nd step.  Using extra debugging, it seems that the /saveCode (second part) is only accepting the `GET` method while should also accept `POST`.  

So the problem is coming from my code not from your addon.

Last question: is it possible to avoid to use the `https://www.thunderclient.com/oauth/callback` URL. Right now, after a valid login on my site, a call is made to `https://www.thunderclient.com/oauth/callback?code=xxxxxx&state=` and thus share sensitive info with your site. Can you explain a little more why this is needed?

**Comment by rangav** [comment]
if you have no further questions you can close this
