### ISSUE TITLE
oauth2 token generation

### ISSUE THREAD

**Issue by jsissom** [rangav/thunder-client-support#693]
Hello, I have copied all the oauth2 parameters from postman into thunder client.  When I click Generate Token, my browser opens and I authenticate, but then I get an error in my browser that says "Something went wrong, please try again." and thunder client gives a message "Error: Something went wrong, please try again".  

Is there a way to get more details about what went wrong?

**Comment by rangav** [comment]
Hi @jsissom 

The log is displayed in out window, select Thunder dropdown

<img width="399" alt="Screenshot 2022-08-02 at 10 56 43" src="https://user-images.githubusercontent.com/8637550/182347508-a92a0dda-c949-4c8a-924c-d0270a720f92.png">

May be the callback url should whitelisted in your auth server.

**Comment by jsissom** [comment]
Thank you for your quick response.  scope is set to undefined.  How can I make it either not send a scope or send a blank scope?

**Comment by rangav** [comment]
Leave scope value empty

**Comment by jsissom** [comment]
When I leave it empty, it is sent as the value undefined.

I found a workaround.  I created an empty variable in my .env file and referenced that in the scope field.  Now it sends a blank scope which works for my auth server.

Thanks

**Comment by rangav** [comment]
Good to know it’s working for you now..

I will look into that scope issue later

**Comment by rangav** [comment]
@jsissom I fix this issue now, Thanks for reporting.
