### ISSUE TITLE
Can not delete collections or enviroment

### ISSUE THREAD

**Issue by qburst-ragavaraaj** [rangav/thunder-client-support#695]
**Describe the bug**
When I try to delete the collections or the environment from SSH it is not deleting and it stays there forever I have no other choice but just ignore it. This behavior is only seen when I connect via SSH and when using it locally I am able to delete it with ease.

**To Reproduce**
1. Connect to a remote PC via SSH within VSCode
2. Create a new collection in thunder client.
3. Click on the three dots and click delete to delete the collection.

We can follow the same steps to reproduce the same error with environments rather than creating a collection we have to create an environment.

**Expected behavior**
I was expecting a small popup in the bottom right that will ask for confirmation to delete the collection or environment on clicking yes the collection or environment has to be deleted from the collections or environment tab of thunder client.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.69.2
 - extension version: 1.17.1 
 - Remote PC's OS: Ubuntu 20.04.4LTS

**Comment by rangav** [comment]
Hi @qburst-ragavaraaj 

Where are you saving requests data in SSH? is it in current git workspace or default location?

**Comment by qburst-ragavaraaj** [comment]
I am sorry but I did not understand what you are asking still let me brief you on my setup and I think that might answer your question. I have like 2 different PCs within my LAN and I take SSH of the Ubuntu PC into my windows using the Remote SSH extension that we can find in the VSCode extension. Now when I delete a collection or environment on my windows PC it's at that time I face the issue.

**Comment by rangav** [comment]
did you enable `Save To Workspace` vscode setting

<img width="1219" alt="Screenshot 2022-08-03 at 17 25 25" src="https://user-images.githubusercontent.com/8637550/182660267-ddbe5d73-f585-49d4-b1ca-216b7873ba57.png">

**Comment by qburst-ragavaraaj** [comment]
it was not turned on before but now I did turn it on but till it did not work I am still unable to delete the collections I created a new collections called test2 and now I can't delete it :(  @rangav

**Comment by rangav** [comment]
Turn off that setting.

please add this setting to your vscode
https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by qburst-ragavaraaj** [comment]
I tried like literally everything @rangav I think there is an issue with the confirmation popup being loaded in windows because I tried in WSL as well it did not work but when I try it in Ubuntu the popup is appearing in the bottom right which is not happening in windows

**Comment by rangav** [comment]
@qburst-ragavaraaj ok thanks, leave it with me will test here and get back to you later.

**Comment by rangav** [comment]
Sorry just checked - I only have WSL setup, which is working fine. Dont have a SSH server setup to test here.

**Comment by qburst-ragavaraaj** [comment]
Hi @rangav

oh ok, that's fine but I did spin up the same vscode on my wsl but it was not working also I did try the same thing in native windows as well and it was not working in it as well if you don't mind may i know wt version of windows do you use Windows 10 Pro N 21H2. Do you think the windows versions could be an issue ??

**Comment by rangav** [comment]
That could be vscode issue, as you are not seeing delete alert

update vscode to latest v1.70.0 and try again 

or try vscode insiders version

**Comment by qburst-ragavaraaj** [comment]
May I know what version of vscode are you using i just updated it to the lates version that is 1.70 and still the issue has not been resolved @rangav

**Comment by rangav** [comment]
I am on `1.69.2`

**Comment by qburst-ragavaraaj** [comment]
ohh ok I really dont know what to do now maybe I can reach out to few friends of mine and see if they are also facing the same problem if not then i think there is something fishy with my PC if they face the same issue then i dont know. Anyways can u give me some time to reach out to my friends and see if they are facing the problem. And by the way i really love thunder client. Is it not open source ?? because i thought of foking it and see what the issues was by my self.

**Comment by rangav** [comment]
@qburst-ragavaraaj no problem, please check with your friends. Yes the project is not open source.

**Comment by Macktireh** [comment]
Hello, I have the same problem, I can't delete the collections or the environment.

**Comment by rangav** [comment]
@Macktireh is it related to WSL issue?

mare you using thunder client in WSL?
