### ISSUE TITLE
Where can see the full request when using system variables?

### ISSUE THREAD

**Issue by costmeyer** [rangav/thunder-client-support#697]
If I use a system variable (such as {{#email}}) in my request, where can I see what string value was actually generated during the request?

**Comment by rangav** [comment]
Hi @costmeyer where you using that variable, is it in url or body?

**Comment by costmeyer** [comment]
@rangav :  Both In the body and in the header.  I see the preview of the response; I was hoping there'd be something similar to show the full request (headers and body)

**Comment by rangav** [comment]
@costmeyer planning to add in the next update - request log vscode setting. you can configure.

Will publish new update tomorrrow.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
