### ISSUE TITLE
Tests -> Results -> regex didn't match

### ISSUE THREAD

**Issue by cavo789** [rangav/thunder-client-support#698]
Hello

I'm trying to add some basic controls to a XML SOAP request make using Thunder client. The returned answer is a XML content.

I quickly check that the XML contains some nodes. To do this, I think I need to use "regex" here.

As you can see in the image below, the message `Response Body did not match regex expression => Actual result did not match the condition` isn't really useful here since I've a lot of tests items.

![2022-08-05_11h41_33](https://user-images.githubusercontent.com/355999/183050617-6dc64f14-de44-415a-9685-0d7e4c051a5d.png)

Is it possible to make the error easier to understand f.i.  `Response Body did not match regex expression => Actual result did not match the ".*<language>.*<\/language>.*"`?

Thanks

**Comment by rangav** [comment]
Thanks @cavo789 for the feedback, will fix in the next update.

did you know that you can do json query tests on xml response also.

**Comment by cavo789** [comment]
> did you know that you can do json query tests on xml response also.

Really?  No, I was not aware of this; will try when appropriate.

In my current use case, regular expressions are fine since I can then use complex validations.

**Comment by rangav** [comment]
I will keep this issue open, when I fix I will close it. will be easy to track.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.

**Comment by cavo789** [comment]
It works perfectly!  Well done

![2022-08-12_07h44_20](https://user-images.githubusercontent.com/355999/184292175-2c94a807-d5e3-4a26-b492-8fe9637c89bc.png)

**Comment by rangav** [comment]
Thank you for confirmation 👍
