### ISSUE TITLE
Need to create/run request before you can save it to collection?

### ISSUE THREAD

**Issue by chaeron** [rangav/thunder-client-support#7]
It seems that you need to create and then run a request before you can save it to a collection.

That is a bit of an awkward workflow and not intuitive at all.

It would be nice if the create request tab had a "save" button, so you could create the request and save it to a collection, without having to run it first.

**Comment by rangav** [comment]
Ok I will look into improving the workflow. Where would be position of save button be appropriate?

also there is a limitation we cannot launch pop up window for save to collection view.

**Comment by chaeron** [comment]
Doesn't really matter to us where the save button is located, so long as it's consistent in placement.

Maybe have a collections drop down beside the save button to avoid the popup.

**Comment by archebyte** [comment]
Glad I found this before posting new. First thing I came upon. See attached on my suggestion for "New Request in this Collection".  Awesome plug-in by the way! Love it!
![NewRequestInCollection](https://user-images.githubusercontent.com/18292613/115918565-831a7e80-a42c-11eb-9589-8e3c3d2d2431.jpg)

**Comment by rangav** [comment]
Hi @archebyte, I have already made improvements, this will be part of next update - #14

**Comment by archebyte** [comment]
Thanks great work!

**Comment by jongio** [comment]
Heads up for people who find this issue:

The only way I could find how to save to collection, is to click on activity, then click on the request and choose save to collection

![image](https://user-images.githubusercontent.com/2163001/115949954-3ca93c00-a48d-11eb-9a28-515812e580b7.png)

**Comment by archebyte** [comment]
That'll do for me!  :). Looking good. Too bad it's not available on the collections flyout.

**Comment by junalmeida** [comment]
+1, I can't manage to save request data without sending it.

**Comment by oliveiradrodrigo** [comment]
@rangav what do you think in adding a shortcut on the request screen? Like Ctrl + S to save the collection request if changed or ctrl + shift + s to "Save as...".

**Comment by rangav** [comment]
v1.1.0 is now published - discuss here #14

**Comment by rangav** [comment]
Hi All there is a settings option called **enableSaveOption**, if you enable it, Requests Created or Modified from Collection Tab will have option to Save Request without Running.

Send button will turn to Save button when modify the request. 

This is for users who are looking for Save request without send.

**Comment by wildhart** [comment]
@rangav.  I find both these workflows un-intuitive.
* With `enableSaveOption` **enabled**, there is no way to re-run a request without saving it first.  Sometimes you want to play with a request to get it working before saving it, to avoid overwriting a working request with a broken request.  It also means an extra click on the "Save" button every time you want to re-run it.
* With `enableSaveOption` **disabled**, there is no way to just play with a request without it saving itself.

Can't we just have separate **send** and **save** buttons?

**Comment by rangav** [comment]
Hi @wildhart no I can't put too many buttons. 

Implementing Ctrl + S for saving only, to solve the problem, 

one more thing when you run a request it will automatically saves the request.

**Comment by junalmeida** [comment]
As a suggestion, maybe a tiny dropdown right to the button like this, but with Save action:
![image](https://user-images.githubusercontent.com/991675/117017891-9a256000-acb9-11eb-9dff-c0e94c213512.png)

Also Ctrl/Cmd+S would be nice.

**Comment by rangav** [comment]
Hi @junalmeida cant do exactly same as others. Ctrl +S should be good I think.

**Comment by jongio** [comment]
I would like to see a better way to save to a collection, other than going to the Activity tab and without having to go into settings.  

I'm in favor of adding a Save button which prompts the user which collection to add it to.

**Comment by rangav** [comment]
Hi @jongio From the collection tab you can create request directly from there, right click on folder or collection you will see options.

and Save button above there are referring to Request Window, Save request without running it. not the same feature as you are requesting i think.

**Comment by jongio** [comment]
My scenario:

I click the blue "New Request" button.

I run the request.

I want to save the request.

Right now I have to go to activity to find it and then click the "...", then save to collection.

I would rather:

From the request page see a way to easily save it to a collection.

LMK if you'd rather see this in a new issue.

Thanks!

**Comment by rangav** [comment]
I think this is new feature request, please create new one.
I also don't like add too many buttons for each scenario, but let think if there any other way with out adding button like keyboard shortcut.

**Comment by rangav** [comment]
Hi All, Now **enableSaveOption** is removed, replaced with `Cmd/Ctrl + s` keyboard shortcut to save request without running in v1.8.0

see all features released 
https://github.com/rangav/thunder-client-support/releases

**Comment by hamzAhmd** [comment]
Honestly, the best thing about this extension is that it has already saved the previous request history which you can easily save in your collection.
