### ISSUE TITLE
JSON Validation Error with Environment Variables

### ISSUE THREAD

**Issue by milesje** [rangav/thunder-client-support#700]
**Describe the bug**
JSON validation error occurs when using environment variables.

**To Reproduce**
Use an env variable in a JSON Body.

**Expected behavior**
No validation error displayed

**Platform:** 
 - OS: Fedora Linux 36
 - vscode version: 1.70.0
 - extension version: 1.17.1

**Solution:**
Don't show JSON Validation errors when line contains an environment variable.
![image](https://user-images.githubusercontent.com/537359/183234847-8c05044b-6f6d-446b-ac4d-857fdf44a2ed.png)

**Comment by rangav** [comment]
@milesje thanks for reporting the issue

It’s just complaining that it is not valid json, though technically it’s correct,

I need to customize the json validator to support this syntax which is in roadmap.

for now you can ignore that warning, when you run request it should work correctly.

There is existing issue for this #516, so closing this one
