### ISSUE TITLE
Run all collections

### ISSUE THREAD

**Issue by t3rr11** [rangav/thunder-client-support#701]
**Describe the solution you'd like**
To put it simply the 'Run All' button to run all tests over a collections is awesome, however over multiple collections we need to run them one at a time, waiting for the previous collection to finish then export, then run all the next collection, etc...

It would be really nice to be able to single click run all collection tests, one after the other, then be able to export all at once.

**Comment by rangav** [comment]
Thank @t3rr11 for the feedback, Will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.5.0`

You can run all collections using `CLI`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.
