### ISSUE TITLE
A settings to determine the default url of a new request

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#702]
**Describe the solution you'd like**
I would like to have a setting where I can change the default url used when creating a new request. Currently it's set to "https://www.thunderclient.com/welcome" and I would like to change it to something else.

**Comment by rangav** [comment]
Thanks @noam-honig for the feedback, will add to roadmap.

**Comment by rangav** [comment]
Sure @noam-honig will include in the next update.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.1.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.1.0

Please let me know your feedback.

**Comment by noam-honig** [comment]
Thanks - that's precisely what I had in mind!
👍👍👍👍👍

**Comment by rangav** [comment]
Glad you like it.
