### ISSUE TITLE
Split Request/Response View (Vertical)

### ISSUE THREAD

**Issue by Bluecakes** [rangav/thunder-client-support#703]
On the main extension page in VSCode, the Thunder Client is shown with the request on the left and the response on the right:

![image](https://user-images.githubusercontent.com/12452056/183418698-37a5bbfa-9f7c-4f98-b2d3-098676d85ff1.png)

After installing Thunder Client, my request is at the top and my response is at the bottom, since i have a large widescreen monitor i'd like to put the request/response side by side as i have more real estate horizontally than i do vertically.

![image](https://user-images.githubusercontent.com/12452056/183419256-83a162aa-a0bb-4467-926d-aeab5541cee1.png)

There doesn't appear to be any extension option or documentation on how to change the orientation so i'm wondering if there's a hidden setting or maybe i need to edit the JSON settings manually to get the extension to look the same as it was advertised on the marketplace?

**Comment by rangav** [comment]
Thanks @Bluecakes for the feedback, currently there is no option. Will add in the next update

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
