### ISSUE TITLE
Ability to interrupt ongoing requests

### ISSUE THREAD

**Issue by novellizator** [rangav/thunder-client-support#704]
**Is your feature request related to a problem? Please describe.**
Yes. Sometimes if the server is down or takes it forever to respond (due to serve bug, etc), I'm blocked.
**Describe the solution you'd like**
I'd like to be able to stop the ongoing request. So the "Send" button could be changed to "Cancel" (and made red or whatever) to abort the request.
**Describe alternatives you've considered**
Killing off the server to cut the connection. That is however not always possible, understandably ;-)

**Implementation:**
I know you know about this, but just adding it for completeness https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by rangav** [comment]
Hi @novellizator there is cancel button below the processing icon

![image](https://user-images.githubusercontent.com/8637550/183466850-3b62d383-86b6-4922-862c-53175618705d.png)

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
