### ISSUE TITLE
Better SSE support

### ISSUE THREAD

**Issue by infalmo** [rangav/thunder-client-support#705]
Currently, SSE responses are printed as is, without any formatting or highlighting
```
data:{...}
```

I'd like if a `sse` toggle is provided, splitting the response data by event name.

**Comment by rangav** [comment]
Hi @infalmo thanks for the feedback.

What is `SSE`? can you also please provide more details

**Comment by infalmo** [comment]
https://en.wikipedia.org/wiki/Server-sent_events

Basically, a unidirectional version of websockets, that works over plain HTTP requests.

**Comment by rangav** [comment]
Thanks got it.

Can you share a `sample full response` for me to test. and what is the response `content-type` for this?

**Comment by infalmo** [comment]
https://hoppscotch.io/realtime/sse

^^This captures SSE perfectly.

**Comment by rangav** [comment]
Thanks for sharing url, we dont have SSE feature yet in Thunder Client, how did you test it?

**Comment by rangav** [comment]
> Currently, SSE responses are printed as is, without any formatting or highlighting
> 
> ```
> data:{...}
> ```

Thanks for sharing url, we dont have SSE feature yet in Thunder Client, how did you test it?

**Comment by infalmo** [comment]
SSE's are glorified GET requests. Just make a get request to the endpoint on thunder.

**Comment by infalmo** [comment]
Alternatively (since thunder prints the body only after the request is completed), `curl -N https://express-eventsource.herokuapp.com/events` to try it out.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.19.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test and let me know your feedback.
