### ISSUE TITLE
GraphQL queries put quotes around empty variables array

### ISSUE THREAD

**Issue by MelGrubb** [rangav/thunder-client-support#707]
**Describe the bug**
If you submit a GraphQL query with no variables, the resulting query contains the empty pair of braces, but they have been quoted like this:

`{..., "variables":"{}"}`

Which is invalid syntax. That's meant to be an empty array, not a string with a "picture" of an empty array.

**To Reproduce**
Submit a GraphQL query with no parameters

**Expected behavior**
The generated query should have a proper empty array in it, not a stringified empty array.

**Platform:** 
 - OS: Windows
 - vscode version: 1.70.0
 - extension version: 1.17.1

**Workaround:**
Put an empty pair of brackets in the Variables pane.

**Comment by rangav** [comment]
Thanks @MelGrubb for reporting will fix asap.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.
