### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6789

### ISSUE THREAD

**Issue by cavo789** [rangav/thunder-client-support#708]
Good morning

I'm trying to use OAuth2 for my web appl;ication.

Here are my Collection Settings (I prefer to use the localhost:6789 syntax to make clear it's a local connection):

![2022-08-10_09h15_55](https://user-images.githubusercontent.com/355999/183838750-28bfe56c-7f84-4389-8219-64a393d446a4.png)

And here my environment variables:

![2022-08-10_09h16_40](https://user-images.githubusercontent.com/355999/183839001-ec83604f-6359-4604-8d16-9fff139ea9f9.png)

I've created a new client in my `oauth_clients` table to make things clean:

![2022-08-10_09h19_37](https://user-images.githubusercontent.com/355999/183839473-78cb0624-3e36-453a-a6bd-93bfdfca9339.png)

So, if I'm not wrong, I can now click on the `Generate Token` button.  My browser is started and the login page is displayed.  I call fill in a valid login / password and there is a redirection to `http://localhost:6789/callback?code=xxxxx&state=`; like expected.

At this step, as far I've understood, ThunderClient (vscode) should receive the code and be able to use it.  But ... vscode is showing me an error : `Error: connect ECONNREFUSED 127.0.0.1:6789`

![2022-08-10_09h22_00](https://user-images.githubusercontent.com/355999/183839868-845f805a-d0ef-4c64-bb69-033abf56ca80.png)

I think I'm almost there but ... ;-)  Can you tell me what to do? 

Thanks!

(I've see your answer https://github.com/rangav/thunder-client-support/issues/561#issuecomment-1104953437 and used the same Callback Url)

**Comment by rangav** [comment]
@cavo789 can you please try below suggestions

- can you please close the `tab` and open again and test it.
- or close `vscode` and re-open and try again.

**Comment by cavo789** [comment]
Thanks for being always so fast.

I've quit `vscode` and restart it, no changes.  Still got the `Error: connect ECONNREFUSED 127.0.0.1:6789` popup just after the login.

**Comment by rangav** [comment]
from your screenshot above, token url is wrong? it should be your auth server url
<img width="516" alt="Screenshot 2022-08-10 at 09 06 11" src="https://user-images.githubusercontent.com/8637550/183849150-9aed5b7d-2fda-41ce-9cc2-d37a676cf472.png">

**Comment by cavo789** [comment]
Ooooh yes! For the first time, I've finally make it working; thanks for your last answer!

This is very unclear to me (i.e. not intuitive) but, yes, with the following settings, it works:

* `oauth_auth_URL` : `http://127.0.0.1:82/oauth/authorize?client_name={{oauth_client_name}}`
* `oauth_token_URL`: `http://127.0.0.1:82/oauth/token?grant_type=authorizationcode&client_name={{oauth_client_name}}&client_id={{oauth_client_id}}&client_secret={{oauth_client_secret}}`
 
(I'm running a Laravel application on `127.0.0.1:82`; I've found the list of querystring variables on [https://laravel.com/docs/9.x/passport#requesting-tokens-converting-authorization-codes-to-access-tokens](https://laravel.com/docs/9.x/passport#requesting-tokens-converting-authorization-codes-to-access-tokens))

Now, it's works like a charm.  Once the login has been made, the token is automagically saved and APIs can be called like f.i. a /users/getcurrent that will display information's about the user used for the login.

![2022-08-10_11h08_55](https://user-images.githubusercontent.com/355999/183862601-caf19157-ddf3-484f-ae70-5ffb38efd6f1.png)

Thanks @rangav ; wonderful support and addon.

**Comment by rangav** [comment]
Super, finally its working - :) 👍

**Comment by cavo789** [comment]
Some tools are pure wonders for the developer; `wsl2`, `vscode` or `docker` for example. `Thunder client` is certainly one of them.

**Comment by rangav** [comment]
@cavo789 thank you very much for kind words, very happy to hear :)

**Comment by rangav** [comment]
FYI - next update will have this feature https://github.com/rangav/thunder-client-support/issues/95#issuecomment-1208470105
