### ISSUE TITLE
System Variables: #enum fails with emoji

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#709]
**Describe the bug**

using emoji inside the {{#enum}} does not evaluate the expression

**To Reproduce**

use `{{#enum, 🙂, 🙃}}`

**Expected behavior**

Choose a value

**Comment by rangav** [comment]
@andresatierf thanks for reporting the issue, will fix it asap.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.

**Comment by andresatierf** [comment]
Working as intended, thank you very much. Love your extension

**Comment by rangav** [comment]
Thank you for confirmation 👍 , Happy to hear that you love the extension :)
