### ISSUE TITLE
Add format button to response 

### ISSUE THREAD

**Issue by TroyWitthoeft** [rangav/thunder-client-support#712]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Let's add the ability to format the response

**Describe alternatives you've considered**
Formatting the response outside of thunderclient

**Implementation:**
No. But, if the source is shared, I am happy to take a swing at a PR!

**Comment by rangav** [comment]
Hi @TroyWitthoeft, thanks for creating the issue.

Can you share a screenshot of the use-case and also where you like format button?

**Comment by TroyWitthoeft** [comment]
Yes, I can.  

![image](https://user-images.githubusercontent.com/1102958/184190485-115cb415-b978-4256-bbe0-3799c5e66356.png)

Can we add a format button on the response object?  In the example above, we are sending and receiving some complex xml.  The response xml does not contain linebreaks or indentations.  However, other api software does offer the ability to pretty-print / format the response xml.  

Adding this capability would help us adopt thunder-client over our existing standalone api app.

**Comment by rangav** [comment]
Thanks for sharing screenshots. It should format the xml automatically. which could be a bug

What is response `content type`?, it should be in `headers` tab? just to clarify the content type.

**Comment by TroyWitthoeft** [comment]
The response type coming out of that server is `text/html; charset=utf-8`
So, it's clear why it's not being formatted.  However an optional format button could help in these types of situations!  😄

**Comment by rangav** [comment]
Thanks for clarifying. If you can update the content-type this should be fixed.

If we provide Format button also, it would be base on content type right? 

the format functionality should know what type content it is to format correctly.

**Comment by TroyWitthoeft** [comment]
> If we provide Format button also, it would be based on content type right?

I mean, that is a _convenient_ way to do it, yes.  But, it also creates a dependency on the remote client setting the content-type accurately.   That may not always be the case. 

What about a format button that was a dropdown between, xml, json, and text and would just let the user apply prettification after the response arrived?  It would handle these types of situations.

**Comment by rangav** [comment]
Thanks for the suggestion, Will add to roadmap for manual format button.

**Comment by TroyWitthoeft** [comment]
Thanks, and happy to recon other clients for you to see if they have lightweight way of intelligently deciding what type of formatting should be applied in situations where the response body and content-type disagree.

**Comment by rangav** [comment]
you can use this url to test yourself
https://www.thunderclient.com/t/echo

Add request header `content-type - text/html`

and this in xml body
```
<test><name>abc</name><loc>test</loc></test>
```

**Comment by TroyWitthoeft** [comment]
Thanks my working example is postman.   It does detect and format for me.   Haven't checked others.

**Comment by rangav** [comment]
actually there is option in thunder client, you can open the response in vscode and let vscode format it for you..

<img width="802" alt="Screenshot 2022-08-11 at 18 49 40" src="https://user-images.githubusercontent.com/8637550/184201375-a915e3fa-af5f-4553-9fb5-59148e5e2d90.png">

**Comment by rangav** [comment]
This is very much similar to having a manual format button. let me know what you think?

**Comment by TroyWitthoeft** [comment]
That's a decent workaround!  But, it is an extra hop and click for users.  
I guess I'm trying to get thunder up to feature parity with peers.  
I recently had a dev say they wouldn't adopt it because postman formats and thunder doesn't.

**Comment by rangav** [comment]
Thanks for feedback. Will add to roadmap.

**Comment by TroyWitthoeft** [comment]
Found some detail on hoppscotch approach here
https://github.com/hoppscotch/hoppscotch/blob/c1cc1ce2955d6b82a82a53cdae54830220431084/packages/hoppscotch-app/helpers/curl/sub_helpers/contentParser.ts

**Comment by rangav** [comment]
Thanks @TroyWitthoeft for sharing the info, will look into it.

**Comment by rangav** [comment]
strange hoppscotch does not do auto format based on content.

<img width="770" alt="Screenshot 2022-08-12 at 17 30 34" src="https://user-images.githubusercontent.com/8637550/184403137-43018665-0991-4a0e-80a0-ca80f3ed8d4d.png">

**Comment by rangav** [comment]
I have fixed this issue now. I have to use different logic to detect xml.

I am uploading the `vsix` file, please install manually and test and let me know your feedback.

Let me know what other issues you team have with thunder client, so I can try to prioritise for next update if possible.

[vscode-thunder-client-1.18.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/9329858/vscode-thunder-client-1.18.2.vsix.zip)

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

Please let me know your feedback.

**Comment by TroyWitthoeft** [comment]
Just retested with latest version of thunder-client and all looks good!   Returned xml is automatically format even if the remote server is not correctly setting the content-type. 

Thank you, and impressively quick work! 🤯   
Let's mark this as resolved, and let me know how I can be of service in the future!

**Comment by rangav** [comment]
Thanks @TroyWitthoeft for confirmation :)

Any feedback to further improve the product is appreciated very much.
