### ISSUE TITLE
No options to reset a variable [ On Pre request ]

### ISSUE THREAD

**Issue by KSandeep06** [rangav/thunder-client-support#713]
Hello,
        Basically, I want to set a variable to blank before calling a Request.
        
E.g. I have a variable {{token}} now, I want to **clear** that before [Pre request] i call a LOGOUT api.

**Comment by rangav** [comment]
Hi @KSandeep06 

Please see the details below
https://github.com/rangav/thunder-client-support#setenv

> <img width="994" alt="Screenshot 2022-08-11 at 17 29 55" src="https://user-images.githubusercontent.com/8637550/184183356-3c38434a-ee24-4cf4-83f5-4020243d083c.png">

**Comment by Sandeep06Dev** [comment]
Got it but how to use it ?  🙄
I want to delete variable only when call LOGOUT api.

**Comment by rangav** [comment]
From the Tests tab of the request, select `Set Env Variable` dropdown option

<img width="798" alt="Screenshot 2022-08-11 at 18 11 35" src="https://user-images.githubusercontent.com/8637550/184193449-542d06d5-5ab2-4f1e-b74c-03ea99ae1f25.png">

**Comment by Sandeep06Dev** [comment]
**Thanks**

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed.
