### ISSUE TITLE
Test overriding

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#714]
**Describe the bug**

These tests are overriding
![image](https://user-images.githubusercontent.com/29847057/184181972-3857536d-7194-41ef-b99e-81ca976cfce9.png)

**To Reproduce**

Use tests in image provided above

**Expected behavior**

Tests should only override if `action` is the same (>, <, equal, ...)

**Comment by rangav** [comment]
Hi @andresatierf thanks for reporting, I have fixed this https://github.com/rangav/thunder-client-support/issues/691, which might caused this bug.

Will fix it in next few hours.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.1`

**Comment by andresatierf** [comment]
@rangav is there a way to override the `isJson` action? I'm using that action in a collection because most items return a json. But there are some endpoint that return nothing. I was thinking that maybe there could be a way to make a test like:
`ResponseBody - isJson - false`

**Comment by rangav** [comment]
@andresatierf thats a good suggestion. can you please  create a new issue, we can track there.
