### ISSUE TITLE
Json schema test validation failed for format

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#715]
**Describe the bug**

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": { "type": "string" }
    }
}
```
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "id": { "type": "string", "format": "uuid" }
    }
}
```
The second json schema fails the test because it has a format property

**To Reproduce**

Use second json

**Expected behavior**

The test should pass

**Platform:** 
 - OS: Manjaro
 - vscode version: 1.70.1
 - extension version: 1.18.0

**Solution:**

**Comment by rangav** [comment]
@andresatierf thanks for reporting, can you share your response json, I will verify and get back to you.

**Comment by andresatierf** [comment]
```json
{
  "id": "c58f418a-82fe-4bfd-af8a-ee8d880afac9"
}
```

**Comment by rangav** [comment]
Looks like I need use this additional formats library from AJV https://github.com/ajv-validator/ajv/issues/1536#issuecomment-814449811

I have fixed that now, will publish a quick update in next 1 hour.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.1`

**Comment by andresatierf** [comment]
Is now working as expected :+1:

**Comment by rangav** [comment]
thank you for confirmation
