### ISSUE TITLE
Overridding `isJson` test

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#716]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to override a test for `ResponseBody - isJson`

**Describe the solution you'd like**

Perhaps the `value` field of the test could be used to disable it
`ResponseBody - isJson - false`

**Describe alternatives you've considered**

There could be a new action `isNotJson`

**Implementation:**

**Comment by rangav** [comment]
@andresatierf thanks, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

Please let me know your feedback.

**Comment by andresatierf** [comment]
@rangav I'm trying to test this but seems to not work

![image](https://user-images.githubusercontent.com/29847057/184554753-080498f9-0719-4cdf-8ca1-be35afbfa2d6.png)

**Comment by rangav** [comment]
Is your response empty?

can you check api that has some response

**Comment by andresatierf** [comment]
Yes, my response in empty, that was why I was trying to set isJson to false

**Comment by rangav** [comment]
When there is no content, it is better check with null right?

**Comment by andresatierf** [comment]
I have the isJson test in the collection because most of the endpoints respond with json. Because this one does not, I was trying to override it to not fail. I am also checking if it's null. [Comment](https://github.com/rangav/thunder-client-support/issues/716#issuecomment-1214447961)

**Comment by rangav** [comment]
Ok got it, Will look into it later.

**Comment by rangav** [comment]
I did a quick fix and published `v1.18.4` please update.

**Comment by andresatierf** [comment]
Working as intended. Thanks
