### ISSUE TITLE
Bug in 1.18.x, Collections force reboot of nodejs server

### ISSUE THREAD

**Issue by TomMiller-mas** [rangav/thunder-client-support#717]
**Describe the bug**
As of Update 1.18, when running a collection of tests, the first one passes and the second one reboots the node.js server.  I backed down the update to 1.17.1 and all the collections run fine (with appropriate errors in the test).  This is happening to all of our developers.

**To Reproduce**
Open a collection, run the collection, the first test runs fine, sometimes the second (rarely), the node.js server reboots, and the rest of the tests fail.  No error was reported.  And if you run the tests one at a time, they all run fine.

**Expected behavior**
When running a collection, the test should run and not reboot the node.js server.

**Platform:** 
Version: 1.70.1 (system setup)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043

node: 16.15.1
express: 4.17.3

**Solution:**

**Comment by rangav** [comment]
Thanks @TomMiller-mas for reporting the issue, will look into it.

**Comment by rangav** [comment]
One clarification: is it happening with localhost url only?

can you test with this sample published url and let me know.
https://jsonplaceholder.typicode.com/

**Comment by TomMiller-mas** [comment]
Yes.  http://localhost:4100/eqp/dntime

Will test the sample and let you know.

**Comment by TomMiller-mas** [comment]
We set up the 4 get routes on the page and they ran fine.  We didn't do any special detail test, just set up the routes.  But they ran fine as a collection.  Maybe "localhost" is the problem.

**Comment by rangav** [comment]
I am verifying the code with both v1.17.0 and v1.18.0 with localhost, will get back to you.

**Comment by rangav** [comment]
The both versions are working fine for me on localhost. 

There are some issues with the library I am using for http requests [got.js](https://www.npmjs.com/package/got)

Try these solutions here
https://github.com/rangav/thunder-client-support/issues/251#issuecomment-874439967

https://github.com/rangav/thunder-client-support/issues/170#issuecomment-1079710824

I am planning to move to different library like `axios` soon.

**Comment by TomMiller-mas** [comment]
We tried both 127.0.0.1 and [::1] and neither worked.  Additional info, we are using environment variables. 

![image](https://user-images.githubusercontent.com/96563084/184457238-a67050c6-8c3b-41bc-8da6-ae57a919263c.png)

**Comment by rangav** [comment]
Try uninstall and re-install extension, if that does not work,

Then may be you can downgrade extension to version `v1.17.1`

In the next we will migrate to new library

**Comment by TomMiller-mas** [comment]
We have been using 1.17.1.  Let me know if you have a preview I can test with the new library.  Love the product!!!!

**Comment by rangav** [comment]
@TomMiller-mas I will upload the `vsix` file tomorrow morning, you can test and  let me know your feedback on the new library.

**Comment by rangav** [comment]
Hi all, we add new http library option for `axios` in v1.18.3. please update test it and let me know your feedback

<img width="837" alt="http" src="https://user-images.githubusercontent.com/8637550/184552594-606c3ccc-850d-4dad-88f2-fc024f963f92.png">

See features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

**Comment by TomMiller-mas** [comment]
Still the same issue even with Axios.  My team feels like it is a timing issue.  Did anything change there with the new features you added in 1.18? Because all of the tests run fine if we run them one at a time.  They only fail when we run them as a collection.  And even if we run them against a real IP address, they sometimes fail. And if we click on the failure and run it by itself, it always passes.

**Comment by rangav** [comment]
@TomMiller-mas thanks , will investigate further when I got time.

**Comment by rangav** [comment]
@TomMiller-mas can you check whether your issue is related this?

https://github.com/rangav/thunder-client-support/issues/551

**Comment by rangav** [comment]
if you can create a sample node project that can re-produce the issue, i can test and investigate the issue here.

**Comment by rangav** [comment]
The new updated collection runner will save the runner settings to `thunderCollection.json` file which might be causing the node server to reboot on file changes, you need to ignore the folder thunder-tests from nodemom as mentioned here https://github.com/rangav/thunder-client-support/issues/551

**Comment by TomMiller-mas** [comment]
That did the trick!!!  Can you add that as part of the installation? Maybe it failed because I already had an "ignore" section?

```
package.json

  "nodemonConfig": {
    "ignore": [
      "multi-tenant.json",
      "thunder-tests/*"
    ]
  }
```

**Comment by rangav** [comment]
Super you got it working,

Users use different backends other then node, so it's it's difficult  for extension to change anything in user code.

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed

**Comment by rangav** [comment]
@irkhamissimo you need to ignore `thunder-tests` folder

see this comment https://github.com/rangav/thunder-client-support/issues/717#issuecomment-1214462246

**Comment by irkhamissimo** [comment]
@rangav  Yeah, I did that. CMIIW, my `thunder-tests` folder is in the same level with  package.json
