### ISSUE TITLE
Request response layout setting no longer respected since 1.18

### ISSUE THREAD

**Issue by kekonn** [rangav/thunder-client-support#718]
**Describe the bug**
Since update 1.18, the following setting is no longer respected:

```json
"thunder-client.requestLayout": "Left/Right"
```

As you can see, my env is set to left/right, but my view is Top/Bottom. Before the update, this was working as intended. Changing the setting also does not change the layout of the request/response pages.

![image](https://user-images.githubusercontent.com/149670/184336004-f1fe07a2-6d97-414e-a190-827d2ff98c5d.png)

**To Reproduce**
Set layout to left/right and open a request.

**Expected behavior**
That the set layout is respected.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.70.1
 - extension version: 1.18

**Solution:**
If only I knew

**Comment by rangav** [comment]
@kekonn did you change any setting in vscode?

that is the default Layout `Left/Right`, you dont need add any setting for that

**Comment by kekonn** [comment]
No I did not change anything. And I know that is the default layout, and yet, the screenshot does not reflect the default layout. So why is that?

**Comment by rangav** [comment]
Change setting to `top/bottom` And see what happens?

after testing change it back to `left/right`

**Comment by kekonn** [comment]
As described in my report, I tried this already. Changing the setting does not have a noticeable effect on the layout.

**Comment by rangav** [comment]
did you close the request view and re-open?

**Comment by kekonn** [comment]
I did a reload window between each setting change.

**Comment by rangav** [comment]
is your extension version `v1.18.1`?

**Comment by rangav** [comment]
share you share your settings screenshot for `request layout`?

**Comment by kekonn** [comment]
![image](https://user-images.githubusercontent.com/149670/184413576-e36c7738-dba4-47ac-bbab-a00e0f1996fe.png)

**Comment by rangav** [comment]
thanks for sharing. strange something is not working.

Here are few things you can try

- Uninstall and re-install extension
- or downgrade extension to `v1.17.1`

**Comment by rangav** [comment]
did you still have the issue?

**Comment by kekonn** [comment]
Currently the issue is no longer present

**Comment by rangav** [comment]
Thanks @kekonn for confirmation 👍

**Comment by rangav** [comment]
Hi @manuelvalenzuela can you share screenshot of setting and request view?

and also version of extension used?

**Comment by manuelvalenzuela** [comment]
Hi @rangav, I'm sorry for not answering before. I can't live without Thunder Client :D, so I reinstalled vscode, and everything is working good now!
I don't have the screenshot, but was using the latest version of the extension.
