### ISSUE TITLE
Json array set env variable

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#719]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

When setting the env variable I'd like to be able to use negative numbers like:
`json.[-1] - setTo - {{variable}}` for the last element of the array
`json.[-3] - setTo - {{variable}}` for the third last element of the array

**Comment by rangav** [comment]
Thanks @andresatierf for the suggestion, Will add to roadmap.

standard access of array `json[8]` is useful for your use-case?

**Comment by andresatierf** [comment]
I have an array that changes in size and would like to always take the last element

**Comment by andresatierf** [comment]
Also, since I'm asking for this change, have you heard of JMESPath? Is a language to query json objects. allows for things like `json[*].id` and returns a list with all the ids fron each object in the array

**Comment by rangav** [comment]
JMESPath is good, but looks like more complex syntax.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

Please let me know your feedback.

**Comment by andresatierf** [comment]
This works as expected, thanks!

**Comment by rangav** [comment]
Thanks @andresatierf for confirmation
