### ISSUE TITLE
Per-Workspace Activity, Collections, Env

### ISSUE THREAD

**Issue by brandoningli** [rangav/thunder-client-support#72]
**Describe the solution you'd like**

A separate activity, collections, and environments panel for each workspace instead of having all global for every workspace.

**Implementation:**

Store/load in a separate file in the `.vscode` folder when a workspace/folder is open.

**Comment by rangav** [comment]
Hi @brandoningli will add to product roadmap.

**Comment by rangav** [comment]
Hi @brandoningli we release v1.1.0 that has option to store data per project. see documentation Team Features section. I am closing this issue, feel free to re-open if needed

details here #14
