### ISSUE TITLE
New Test Action for "Not Contains".  E.G. ResponseBody NotContains 'UnitNumber'

### ISSUE THREAD

**Issue by MrMPorter** [rangav/thunder-client-support#721]
I would like a way to test that a string is not in the Response Body.
For example, I have a route that has options for returning a full set of fields or a partial set of fields.
I can easily test the full set of fields by using Contains.
"ResponseBody Contains 'UnitNumber':"
When I use the partial set of fields I want to test that one of the full fields is not in the Response Body.
"ResponseBody NotContains 'UnitNumber':"
Thanks

**Comment by rangav** [comment]
@MrMPorter thanks for creating will add in next update

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.3

Please let me know your feedback.

**Comment by MrMPorter** [comment]
Thank you for the amazing fast response and update.

Mark
