### ISSUE TITLE
OAuth 2 scope leave empty

### ISSUE THREAD

**Issue by clutchJoe** [rangav/thunder-client-support#724]
I try to use OAuth Authentication and leave empty scope. Will get the authorization like that:
`https://xyz.com/api/v1/authorize?......&scope=&redirect_uri=......`

If leave the scope blank, can you not put it in the URL?

If I leave the scope blank in postman, it will not be added to the URL.

**Comment by rangav** [comment]
Hi @clutchJoe did not fully understood your question?

Do you want to send empty `scope`?

**Comment by clutchJoe** [comment]
Yes

**Comment by rangav** [comment]
Ok got it,, thanks, will fix in the next update.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.7`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.7

Please let me know your feedback.

**Comment by snd-mn** [comment]
This bug is reproducable in v2.2.4

**Comment by rangav** [comment]
@snd-mn can you please share logs screenshot to confirm this?

**Comment by rangav** [comment]
@snd-mn  What type of OAuth request were you testing?
