### ISSUE TITLE
Html Preview not showing properly for script tags

### ISSUE THREAD

**Issue by gabbobazinga** [rangav/thunder-client-support#725]
**Describe the bug**

After last update Raw Html or Preview does not show Laravel dd correctly.

**To Reproduce**
dd('example');
return <script> ... </script>

**Platform:** 
 - vscode version:
 - extension version:

**Comment by rangav** [comment]
Hi @gabbobazinga thanks for reporting the issue,

Can you sample response text that has the issue. So I can verify and fix it.

**Comment by gabbobazinga** [comment]
Sure, 
dd('example')

return 
<script> Sfdump = window.Sfdump || (function (doc) { var refStyle = doc.createElement('style'), rxEsc = /([.*+?^${}()|\[\]\/\\])/g, idRx = /\bsf-dump-\d+-ref[012]\w+\b/, keyHint = 0 </script>

**Comment by rangav** [comment]
can you share a screenshot the response section in the thunder client.

**Comment by gabbobazinga** [comment]
![image](https://user-images.githubusercontent.com/71637743/184869864-8d644c9a-25ca-4cec-8e33-264ecde5d641.png)

Before update in this section I could see the dd correctly. I had set Preview instead of Raw Html

I tryied also with in settings.json 
- "thunder-client.htmlView": "Preview"

**Comment by rangav** [comment]
Thanks understood the issue, will fix it asap.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.7`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.7

Please let me know your feedback.
