### ISSUE TITLE
Undo misbehaves in the bearer token textarea

### ISSUE THREAD

**Issue by Tyriar** [rangav/thunder-client-support#726]
**To Reproduce**

1. Type something into the auth > bearer token text area
2. Ctrl+a to select all
3. Ctrl+x to cut
4. Ctrl+z to undo, 🐛 the undo result will be duplicated

![Recording 2022-08-16 at 07 08 15](https://user-images.githubusercontent.com/2193314/184900603-b4bdb3e9-5b0c-4b7f-864d-b89a46901da7.gif)

**Platform:** 

Version: 1.71.0-insider (user setup)
Commit: 8e42bda5487a953d59fab7792eedd4ca209cabba
Date: 2022-08-16T05:18:32.502Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

 - extension version: 1.18.6

**Comment by rangav** [comment]
Thanks @Tyriar for reporting the issue, will look into it.

**Comment by rangav** [comment]
@Tyriar seems to be fixed with recent updates, let me know if you still having this issue.

**Comment by Tyriar** [comment]
I probably won't use the extension for a while, feel free to close if you think it's fixed

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.15.0`

See all features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.
