### ISSUE TITLE
Support large fonts presentation mode

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#727]
Hi, I'm using Thunder Client a lot in presentations that I do and meetups that I present in.

I use very large fonts, and have a very small screen to use :)

![image](https://user-images.githubusercontent.com/16635859/185114437-bad34d11-a8c1-4c54-807d-181c805900fe.png)

I would love it if there was an option to hide the tabs, or condense them in some way - so that I'll have more room for the request info:

In my case the important things are:
1. Method + url
2. The Body
3. Response
4. Status

I can think of a few ways, for example take the Body type tabs, and hide them in a drop down that'll replace the JSON Content text.
In small screens, maybe merge the status with the Response (Response 403) and give the response a color.

What ever you think is right.

Thanks

That would help my presentations a lot.

**Comment by rangav** [comment]
Thanks @noam-honig for the feedback, will look into it.

One question: what kind of presentations you do? Is it related to YouTube or others?

**Comment by noam-honig** [comment]
I present at meetups and record you tube videos

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.7`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.7

Please let me know your feedback.

**Comment by noam-honig** [comment]
Hi, thanks for working on it - I really appreciate it. 

It's already better, and I noted a few things:

1. There's an unused black rectangle below the response (I highlighted it in red in the next picture:
![image](https://user-images.githubusercontent.com/16635859/186078483-32d6e26a-7dd4-4824-994d-75baeb4a52cf.png)

2. In a small screen, how can I reach the response headers & cookies if I need to (I don't need it often, but still it would be nice to have a way)

3. I a small screen, I would also move the Body format tabs to replace the text JSON Content - giving more vertical space:
![image](https://user-images.githubusercontent.com/16635859/186078899-767e343a-70b8-458d-ac3c-92b4cb87d0e1.png)

Thanks so much

**Comment by noam-honig** [comment]
Cool - I'm happy :) 👍
