### ISSUE TITLE
Json format at Response

### ISSUE THREAD

**Issue by rudra319** [rangav/thunder-client-support#73]
**Describe the bug**
The response comes in plain text instead of json format.
**To Reproduce**
Just run a plain payload.

eg: I was using this in local system
'http://192.168.103.229/sociomatic4/api/consoleServices' POST

**Expected behavior**

**Platform:** 
 - OS: Ubuntu18.4
 - Vscode 1.55

**Solution:**
NA

![Screenshot from 2021-04-27 12-48-08](https://user-images.githubusercontent.com/59408986/116201705-6d23fb00-a757-11eb-891a-bf1bd50d30f8.jpg)

**Comment by rangav** [comment]
Hi @rudra319 what is the content type value the request is returning?

**Comment by rudra319** [comment]
> Hi @rudra319 what is the content type value the request is returning?

JSON type
eg:" echo json_encode(array('status' => 200, 'error_msg' => '', 'total_count' => $totalCount, 'action_taken_detail' => $pageArr));"

**Comment by rangav** [comment]
dont think you are returning json content type, can you post a screenshot of response headers tab?

**Comment by rudra319** [comment]
> dont think you are returning json content type, can you post a screenshot of response headers tab?

content-type
text/html; charset=UTF-8

**Comment by rangav** [comment]
The formatting is based on content-type, thats why it is not formatted, can you return content-type application/json.

**Comment by rudra319** [comment]
> The formatting is based on content-type, thats why it is not formatted, can you return content-type application/json.

Its already "content-type application/json"  at headers while requesting. Like I said , it works in Postman.
Or am I missing something ?

**Comment by rangav** [comment]
The response header content-type should be `application/json`, not request header.

Run the link https://www.thunderclient.io/welcome and see the response headers

**Comment by rangav** [comment]
see the image
![image](https://user-images.githubusercontent.com/8637550/116353704-2eda1a80-a7ef-11eb-9158-cf781b443a01.png)

**Comment by rangav** [comment]
Hi @rudra319  i am closing this issue, feel free to re-open if needed.
