### ISSUE TITLE
Option for a stable request list

### ISSUE THREAD

**Issue by Tyriar** [rangav/thunder-client-support#730]
**Is your feature request related to a problem? Please describe.**

I'd like the ability to choose the order in which the request list is sorted, instead of just more recent. I find not having similar requests grouped for my service makes it hard to find what I'm after in the list.

**Describe the solution you'd like**

Whether that's done by ordering it manually (which I do currently) or by some UI gesture I don't mind.

**Comment by Tyriar** [comment]
I see `sortNum` in `thunderActivity.json` but it doesn't seem to do anything after I set it, save the file and click refresh.

**Comment by Tyriar** [comment]
It occurs to me that collections probably solve this, it's not clear how to create a request in a collection without editing the JSON though. The new request button here just adds to activity:

![image](https://user-images.githubusercontent.com/2193314/185492200-89a1c0eb-b63e-4a9b-b78b-cd8b9012f31e.png)

**Comment by Tyriar** [comment]
Closing as this is already done with collections, though I had some issues discovering how to use it

**Comment by rangav** [comment]
Hi @Tyriar 

Better not to modify json files directly, please use UI to create requests. Use the `…` to see all options available

**Comment by Tyriar** [comment]
@rangav modifying through the UI is very slow for me compared to text, I ended up getting it all working, it just took a little time to figure out how collections worked.

**Comment by rangav** [comment]
@Tyriar you will get used to the UI after using it couple of times.
