### ISSUE TITLE
Improve multi-root support

### ISSUE THREAD

**Issue by Tyriar** [rangav/thunder-client-support#731]
**Is your feature request related to a problem? Please describe.**

My setup is:

1. One window with the folder of the service I'm working on open, this folder contains the `thunder-tests` folder
2. One window that has a _workspace_ open with the same folder open such that I can have thunder client on a dedicated second monitor

Currently this doesn't work immediately, I can workaround this by changing _workspace_ settings (not _folder_) and set the thunder-tests folder directly. This is a pain and I typically don't save workspaces so I have to fiddle with this whenever I work on the API.

**Describe the solution you'd like**

IMO the most correct behavior here is to parse out all `thunder-tests` folders in all workspace roots and present them in some ordered fashion, that could be as simple as a dropdown to filter between workspaces or more complex like having a tree in the list.

**Comment by rangav** [comment]
@Tyriar thanks for the feedback, will review it.

**Comment by rangav** [comment]
related to #731

**Comment by rangav** [comment]
You can use the `Workspace Relative Path` setting to configure where you want to save the `thunder-tests` folder

https://github.com/rangav/thunder-client-support#git-sync

**Comment by rangav** [comment]
In the next update, we will add support for Multi-root workspaces.

As an alternative solution till then, you can use this setting
https://github.com/rangav/thunder-client-support/blob/master/README.md#2-custom-location

**Comment by rangav** [comment]
`Multi-root workspaces` are now supported, please update to v2.9.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

Please test and let me know your feedback.

**Comment by rangav** [comment]
- You can load request data from different workspace easily.

<img width="621" alt="Screenshot 2023-07-07 at 17 38 01" src="https://github.com/rangav/thunder-client-support/assets/8637550/b359bd26-8206-47c4-bde2-58de0104d204">
