### ISSUE TITLE
The 3 line icon have a misleading meaning and doesn't follow VS Code conventions

### ISSUE THREAD

**Issue by Tyriar** [rangav/thunder-client-support#733]
**Describe the bug**

This icon means find in selection:

![image](https://user-images.githubusercontent.com/2193314/185493127-7ef56414-baee-4e13-9c78-a6050fd55bed.png)

I was assuming this was to do with filtering or sorting so I didn't click it to discover features.

The ellipsis would be more appropriate here, for example as used in the editor actions:

![image](https://user-images.githubusercontent.com/2193314/185493317-c9b77313-9f09-40fc-81b3-a247ed759cf2.png)

**Comment by rangav** [comment]
This bug is fixed now and published to the marketplace, please update to `v2.15.3`

https://github.com/rangav/thunder-client-support/releases/tag/v2.15.3

Please test and let me know your feedback.
