### ISSUE TITLE
"Not valid Thunder Client file" when exporting to Postman collection

### ISSUE THREAD

**Issue by eichelkrauta** [rangav/thunder-client-support#734]
**Describe the bug**
My goal is to export a locally sync'd `thunderclient.json` to a Postman collection in order to run them via a headless `newman` cli during integration testing. However, I'm seeing that the locally sync'd `thunderclient.json` files are throwing a "Not valid Thunder Client file" error when I try to export them.

**To Reproduce**
Here's an example `thunderclient.json` file that is was produced when locally sync'd that's causing the error for me:
```json
[
  {
    "_id": "f302c464-2909-4fdd-b4cf-a211faaaddb4",
    "colId": "a177c8dc-32ef-42d6-b5f7-aa79ce672f01",
    "containerId": "",
    "name": "/",
    "url": "{{url}}",
    "method": "GET",
    "sortNum": 10000,
    "created": "2022-08-18T23:15:27.618Z",
    "modified": "2022-08-18T23:19:56.940Z",
    "headers": [],
    "params": [],
    "tests": [
      {
        "type": "res-body",
        "custom": "",
        "action": "contains",
        "value": "hello world!"
      }
    ]
  }
]
```

**Expected behavior**
I should be able to export to a Postman JSON file

**Platform:** 
 - OS: WSL2 Ubuntu 20.04
 - vscode version: 1.70.2
 - extension version: 1.18.6

**Solution:**
Not sure! But I'm very down to help figure it out together!

**Comment by rangav** [comment]
Hi @eichelkrauta 

please follow steps here
https://github.com/rangav/thunder-client-support#how-to-convert-to-postman-format

**Comment by eichelkrauta** [comment]
Hmm, I guess I'm not sure why this was closed, since I was in theory using those steps.

Maybe I am not exporting to .json correctly?

Does this method not apply to files that were created from "Save to Workspace"?

**Comment by rangav** [comment]
@eichelkrauta it will not work with thunder client default json files. You need to export the thunder client collection and then convert to postman.

Hope its clear now

**Comment by eichelkrauta** [comment]
I gotcha! I took another look at it and I think I understand it a bit better. 

I'll reopen with a feature request instead :)

Thanks!
