### ISSUE TITLE
Support Json comment at body request

### ISSUE THREAD

**Issue by dodicandra** [rangav/thunder-client-support#737]
**Is your feature request related to a problem? Please describe.**

I hope there is a comment json feature in the request body.

at the moment
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/48325708/185569695-b2defcb2-09ee-4161-a7af-8ba6a9e4ae5a.png">

**Describe the solution you'd like**

I hope body requests will ignore comments

**Implementation:**

i think it could implement parsing before request, or discard comments

**Comment by rangav** [comment]
duplicate of #584
