### ISSUE TITLE
Local "Save To Workspace" json files can be exported to Postman

### ISSUE THREAD

**Issue by eichelkrauta** [rangav/thunder-client-support#738]
**Is your feature request related to a problem? Please describe.**
I realize now from the bug I created that the format for the saved `thunder-collection_api.json` when exporting a collection to `json` is _slightly different_ from the `json` format of a `thunderclient.json` file created when doing the "Save to Workspace" functionality :)

**Describe the solution you'd like**
It would be great to cut down the steps of the workflow so I didn't have to export a collection to `thunder-collection_api.json` before converting to Postman. Or, maybe even the "Save To Workspace" feature could give us the option to save as a Postman format for the collections / environments / etc?

Look forward to collaborating on ideas here!

**Comment by eichelkrauta** [comment]
as a side anecdote, the goal here is to be able to use something akin to `newman` CLI to run integration tests in my CI, but create collections through Thunder Client in order to arrange / organize them

**Comment by rangav** [comment]
@eichelkrauta thanks for the feedback, will review it.

currently no plans to convert default json files to postman

**Comment by eichelkrauta** [comment]
No problem, nice work with this repository I'm really looking forward to seeing how I can get involved -- as I'm fairly invested at this point on migrating away from Postman :)

**Comment by rangav** [comment]
We have plans to release own cli feature in near future.

**Comment by TroyWitthoeft** [comment]
I am following this post for the exact same reason.  We currently have some automatic integration tests running in our CI/CD pipelines via newman.   Would love for thunderclient to have a cli as well.

**Comment by rangav** [comment]
Related to #98

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.0`

Now you don't need to export to json file 

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.0

Please let me know your feedback.
