### ISSUE TITLE
The welcome to thunder client text is selectable

### ISSUE THREAD

**Issue by Tyriar** [rangav/thunder-client-support#739]
**Describe the bug**
![Recording 2022-08-19 at 08 36 13](https://user-images.githubusercontent.com/2193314/185655291-c9a5a137-07a4-4e9d-83f6-05c2bf32c481.gif)

I suggest adding `user-select: none` and `pointer: default` here as there is no reason to allow selection.

**Comment by rangav** [comment]
Thanks @Tyriar for the feedback, will fix in the next update

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.18.7`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.7

Please let me know your feedback.
