### ISSUE TITLE
Set variable based on test result (or) if header/body property exists?

### ISSUE THREAD

**Issue by ryanjoachim** [rangav/thunder-client-support#740]
Example:

I want to set a variable `{{isVoidable}}` or `{{isRefundable}}` based on the data in the response body.
![image](https://user-images.githubusercontent.com/20692061/185659766-ef66b97f-364d-4e1c-add2-3e8e2b89cd00.png)

So something like:
`json.voidable -> equals -> true` - if this passes, the immediate next test is run to set the variable.
If it fails, that next test (to set the variable) is skipped.

Is this kind of functionality already possible?

**Comment by rangav** [comment]
Hi @ryanjoachim no currently its not possible, but I like your idea of the condition to set variable. 

Thanks for the suggestion, will add to roadmap.

**Comment by rangav** [comment]
@ryanjoachim we launched custom scripting filters in `v2.0.0`, 

To control the setting of env variable

1.  If the custom function returns undefined, the env variable is not
2. if the custom filter returns any other value, then sets the variable.

the syntax is
`json.voidable | customFilter`

See details here
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

**Comment by rangav** [comment]
Hi @ryanjoachim we also launched Post request scripting where you can conditionally run requests 

https://github.com/rangav/thunder-client-support/releases/tag/v2.9.0

**Comment by rangav** [comment]
I am closing this issue, feel free to reopen it if needed
