### ISSUE TITLE
Collection Settings: Base URL Prepend

### ISSUE THREAD

**Issue by bensonrlee** [rangav/thunder-client-support#741]
**Is your feature request related to a problem? Please describe.**
Thunder Client version 1.18.6 supports the capability to prepend base URL to requests.  This is based on the collection settings.  This feature currently does not discern if a base URL is already included in the request URI. 

**Describe the solution you'd like**
Before prepending the base URL, it can check first if a base URL is already included in the request's address.  For example, if the target already begins with https:// or http:// then it should not prepend the base URL anymore.

**Describe alternatives you've considered**
One can use environment variables instead to prepend the base URL.  Now, take for example you have a collection of 100 requests, and only one of which should not have the base URL prepended because it does not adhere to the strict pattern of the base URL.  What happens is that you have to manually prepend the base URL for the 99 requests, which is a little counter-intuitive.

If you do not prepend the base URL to the other requests then it will fail during the "Run All" operation of the collection.

For example:
Base URL for all: https://api.example.com/latest 
Isolated request (outlier): GET https://api.example.com/username

**Implementation:**

None yet.

**Comment by rangav** [comment]
Thanks @bensonrlee for the feedback, will fix in the next update.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.7`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.7

Please let me know your feedback.

**Comment by bensonrlee** [comment]
@rangav  - thanks a lot for the quick fix!  I just tried and it worked perfectly.

**Comment by rangav** [comment]
Thanks @bensonrlee for confirmation 👍
