### ISSUE TITLE
format JSON erros & validation messages

### ISSUE THREAD

**Issue by MahendraBishnoi29** [rangav/thunder-client-support#742]
**while testing my API i was using Express-Validator for route validation but the Error wasn't formated in Thunder Client**

Thunder Client Response :
<img width="549" alt="error" src="https://user-images.githubusercontent.com/74294202/185882363-f127b543-db01-446c-85e3-75ab9c0b1a50.png">

Expected Response :
<img width="361" alt="postman" src="https://user-images.githubusercontent.com/74294202/185882616-89caab21-cadf-45f6-bf33-2c910090d61a.png">

**Comment by rangav** [comment]
Hi @MahendraBishnoi29 thanks for creating issue.

looks your server is throwing error while executing the api request.

if your api returns json then the extension will format automatically.

can you please check your server logs or see html response and click `preview`

**Comment by MahendraBishnoi29** [comment]
yupp that works fine thank you 🙌🏻😃

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed.
