### ISSUE TITLE
Headers being sent in lower case.

### ISSUE THREAD

**Issue by bkervaski** [rangav/thunder-client-support#744]
**Describe the bug**
Headers being sent in lowercase ... so "Authorization" ends up at the server as "authorization"

**To Reproduce**
Send any headers

**Expected behavior**
Honor whatever casing I apply

**Platform:** 
 - OS: macOS
 - vscode version: 1.70.2
 - extension version: 1.18.7

**Solution:**

**Comment by rangav** [comment]
Hi @bkervaski 

we have vscode setting `Headers Case Sensitive` Please enable it.

**Comment by bkervaski** [comment]
@rangav thank you! missed that :) Great extension!
