### ISSUE TITLE
Adding a button for JSON to interface or class converted in the response section

### ISSUE THREAD

**Issue by Samuele-Barbiera** [rangav/thunder-client-support#748]
**Is your feature request related to a problem? Please describe.**
i have every time to go on the web and search a json to interface or class converter for my code

**Describe the solution you'd like**
Having the ability to add a button to copy the conversion of the JSON response of the API in an interface for typescript or a class for dart, c#, etc..., it would be great to put it beside the button for the code snippet on the top-right side

**Describe alternatives you've considered**
it's the same idea implemented in the rapidAPI extension

**Implementation:**
not yet

**Comment by rangav** [comment]
Thanks @Samuele-Barbiera for creating feature request, will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.3

Please let me know your feedback.
