### ISSUE TITLE
Show sent request

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#752]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I would like a way to see the request that was made after it was made. I would like to know the values that the variables like `{{#number}}` were 

**Describe alternatives you've considered**

Maybe a new tab on the response side with request information

**Implementation:**

**Comment by rangav** [comment]
@andresatierf 

Enable advanced logging in vscode setting `Request Log`

And you will see the all the request details in output window.

**Comment by andresatierf** [comment]
Thanks, that will do.

**Comment by rangav** [comment]
@zengemvisor-gb by default now we show advanced log, so no setting is needed.

<img width="1403" alt="Screenshot 2022-11-04 at 13 55 48" src="https://user-images.githubusercontent.com/8637550/199989993-ccda4db9-847a-4c2b-834c-b37e601cfc94.png">
