### ISSUE TITLE
Autocompetions hover/selection effect

### ISSUE THREAD

**Issue by malad1** [rangav/thunder-client-support#753]
**Problem**
Can't see focus/hover effect of currently selected autocompletion item
![image](https://user-images.githubusercontent.com/74474615/187658076-1d1d23c1-2836-430b-876f-68130bd75ca8.png)

**Describe the solution you'd like**
Currently selected/hovered autocompletion item has different color

**Comment by rangav** [comment]
Thanks @ILScc for the feedback, will add to roadmap.

**Comment by rangav** [comment]
@malad1 I think this is fixed in current update `v1.18.7`, please test and let me know.

**Comment by malad1** [comment]
I don't see any changes :) Current ext version is `v1.18.7`
(On attached video I'm going through options with keyboard in first case, select needed header with mouse in second)


https://user-images.githubusercontent.com/74474615/190392751-0e5efa65-281c-4b21-b1a4-e25da94d5152.mp4

**Comment by rangav** [comment]
can you share your theme name?

**Comment by malad1** [comment]
[Night Owl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl)

**Comment by malad1** [comment]
Thanks a lot! Resolved in v1.19.0. Closing as completed
