### ISSUE TITLE
Save generated value

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#755]
Is it possible to generate a value inside the body (eg. {{#number}}) and save it to an environment variable in the same request?

**Comment by rangav** [comment]
@andresatierf yes you can do it. please test and let me know if any questions.

**Comment by andresatierf** [comment]
@rangav how can I achieve this?

**Comment by rangav** [comment]
<img width="941" alt="Screenshot 2022-08-31 at 22 40 23" src="https://user-images.githubusercontent.com/8637550/187739219-8459f641-8ee3-48a4-9fbc-f38a097220bf.png">


<img width="978" alt="Screenshot 2022-08-31 at 22 41 34" src="https://user-images.githubusercontent.com/8637550/187739126-24997fdc-50ca-47e8-93f2-1b81a86dc9cc.png">

**Comment by andresatierf** [comment]
I have explained myself poorly.
I have this service that does not respond with anything to a specific request. But I still wanted to save the value that was generated in the body of the request, for use with subsequent requests. Is there any way to achieve this?

**Comment by rangav** [comment]
currently not possible, 

alternative solutions:
- you have create a env variable and manually enter the number.
- or create a additional request that will output the number in the response and save to env variable and then use that value in subsequent requests

**Comment by rangav** [comment]
will review and add to roadmap on how to implement for this use-case.

**Comment by andresatierf** [comment]
thank you, will close this now
