### ISSUE TITLE
Number generation

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#756]
**Describe the bug**

Using `{{#number, 100, 999}}` twice in a row, generates the same number

**To Reproduce**

body: `{"number": "{{#number, 100, 999}} {{#number, 100, 999}}"}`

**Expected behavior**

Different numbers

**Platform:** 
 - OS: Manjaro
 - vscode version: 1.70.2
 - extension version: 1.18.7

**Solution:**

**Comment by rangav** [comment]
Thanks @andresatierf for reporting the bug, will look into it.

**Comment by rangav** [comment]
This Bug is now fixed and published to marketplace, please update to `v1.19.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.0

Please let me know your feedback.

**Comment by andresatierf** [comment]
Seems to be fixed, thanks
