### ISSUE TITLE
Base url

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#757]
**Describe the bug**

using a variable with the full url, the base url is still appended

**To Reproduce**

Collection base url: `https://www.facebook.com`
Env variable: url: `https://www.google.com`
Request url: `{{url}}`

**Expected behavior**

The request should go to `https://www.google.com` instead of `https://www.facebook.comhttps://www.google.com`

**Platform:** 
 - OS: Manjaro
 - vscode version: 1.70.2
 - extension version: 1.18.7

**Solution:**

**Comment by rangav** [comment]
Thanks @andresatierf for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is now fixed and published to marketplace, please update to `v1.19.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.0

Please let me know your feedback.

**Comment by andresatierf** [comment]
This seems to be fixed, thanks

**Comment by rangav** [comment]
Thanks for confirmation.

**Comment by yusufumac** [comment]
@rangav This change probably broke something else. When collection base url has an environment variable, it won't get taken into account.

**Comment by rangav** [comment]
@yusufumac will verify and get back to you

**Comment by rangav** [comment]
@yusufumac I can re-produce the error, will fix in the next update asap.

**Comment by yusufumac** [comment]
Thanks @rangav !

**Comment by rangav** [comment]
@yusufumac 

This bug is fixed now and published to marketplace, please update to v1.19.2

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.2

Please let me know your feedback.
