### ISSUE TITLE
Share collections by team

### ISSUE THREAD

**Issue by marcosmariano** [rangav/thunder-client-support#76]
**Is your feature request related to a problem? Please describe.**
I need to share my collections to another people

**Describe the solution you'd like**
Allow to share collections by team using maybe a login or something like this

**Describe alternatives you've considered**

**Implementation:**

**Comment by renarsvilnis-ui** [comment]
My team is looking to find a free alternative to the postman with the ability to share the collection with the team easily.
For us, the killer feature we are looking for would be to have the collection stored within git repo in a file or folder and we can version control it.

**Comment by rangav** [comment]
Hi @marcosmariano and @renarsvilnis-ui please see next update details  #14

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14 - see documentation Team Features Section
