### ISSUE TITLE
Receiving an png image using a GET request will error with ENOENT

### ISSUE THREAD

**Issue by Ivanmatthew** [rangav/thunder-client-support#760]
**Describe the bug**
![Image Context](https://user-images.githubusercontent.com/76107136/188586659-16b96286-8270-4424-b841-42e36187e40f.png)
When requesting from an API endpoint where the return is a media type (in this case png), it will try to (I think?) create a cache location for the sent media, store it at that location and display it in vscode. However, it does not create any of the folders it is supposed to, resulting in an error (as seen in the image).

**To Reproduce**
1) Create or get your hands on an API endpoint which returns a png image
2) Using thunder client, request the api endpoint and try to receive the png image

**Expected behavior**
A new tab showing the image, or showing the image inline where the response body should usually be

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.71.0
 - extension version: 1.18.7

**Solution:**
Create a folder (see image, in this case "files") in directory: "rangav.vscode-thunder-client"

**Comment by rangav** [comment]
Thanks @Ivanmatthew for reporting the bug, will look into it.

**Comment by rangav** [comment]
Hi @Ivanmatthew did not fully understand your question, can you please share a screenshot.

The image should be accessible through a web server.
![image](https://user-images.githubusercontent.com/8637550/190271220-fd35ffb5-8481-453a-bb6d-022c6fa11b05.png)

**Comment by Ivanmatthew** [comment]
I tested it on my other device and it works. Basically what I think went wrong is that vscode improperly installed all folders for thunderclient, as it was missing the "files" folder on only one device of mine, while the other device just had it.

To my understanding, for a pc to view an image, albeit temporarily, it should temporarily download and store it somewhere, which I think was directed to the "files" folder which was missing on one of my devices.

I think the issue will not arise for anyone else for 99%, but if somebody also had issues with vscode installing it improperly, this issue can be used to solve theirs.
