### ISSUE TITLE
Search Json 

### ISSUE THREAD

**Issue by Rar9** [rangav/thunder-client-support#761]
Its would be nice to be able to search the outputed Json request like we can in browser

**Comment by rangav** [comment]
Hi @Rar9 thanks for the feedback, can you please share screenshot of where you like search json functionality?

**Comment by Rar9** [comment]
Once the jsonapi request was send

The given results should be search able and results perhaps scrollable

**Comment by rangav** [comment]
you can use `ctrl + F` to find text in the response, or are you looking for something else?

**Comment by Reid00** [comment]
@rangav could you provide some theme, I find the search result is not friendly with my vscode theme `one dark pro`
![image](https://github.com/rangav/thunder-client-support/assets/38450639/b81a71f3-d4a2-42a6-933c-01641d7a636c)

**Comment by rangav** [comment]
Hi @Reid00 I just now tested with one dark pro theme, it's working for me

<img width="758" alt="Screenshot 2023-07-04 at 09 32 40" src="https://github.com/rangav/thunder-client-support/assets/8637550/2917363a-4786-4078-b229-3c2013332fb9">

Can you use this sample URL and test it and let me know again?
https://jsonplaceholder.typicode.com/posts

**Comment by Reid00** [comment]
the same issue, the difference is i use it in Remote-SSH. seem to related with Remote. i use in local work fine.
![image](https://github.com/rangav/thunder-client-support/assets/38450639/b26c8a55-167f-40c3-802d-f5e1ba379498)

**Comment by Reid00** [comment]
@rangav pls see my attached file.

**Comment by rangav** [comment]
@Reid00 oh ok, will verify and get back to you

**Comment by Reid00** [comment]
@rangav  is there any update?

**Comment by rangav** [comment]
I haven't looked into it yet, will verify this week. Was busy with other things

**Comment by rangav** [comment]
Hi @Reid00 did you change font settings in remote vscode setup? Are you using default font?

**Comment by Reid00** [comment]
no,  ssh remote share the same config in vscode.
