### ISSUE TITLE
Command Run collection panel not Work

### ISSUE THREAD

**Issue by valentino-90** [rangav/thunder-client-support#762]
**Describe the bug**
Command "thunder-client.run-collection-panel" show an empty tab

**To Reproduce**
Assign key shortcut to command "thunder-client.run-collection-panel" 

**Platform:** 
 - OS: Windows 11
 - vscode version:1.71.0
 - extension version: 1.18.7

**Comment by rangav** [comment]
Hi @valentino-90 thanks for the feedback.

did not fully understood your suggestion, can you please share a screenshots

**Comment by valentino-90** [comment]
Yes, i attach 2 screens: 
screen1 (command list and key combination)
screen2 (after command launched)

![screen1](https://user-images.githubusercontent.com/9696655/189115542-84f22327-779d-4ca3-8cbf-f26db1496269.png)
![screen2](https://user-images.githubusercontent.com/9696655/189115547-23b3c4c1-c568-4fbf-ada9-d9e7596e1216.png)

**Comment by rangav** [comment]
Hi @valentino-90 currently you cannot assign a shortcut to run collection view.

**Comment by valentino-90** [comment]
Ok, Sorry. 

Thanks
