### ISSUE TITLE
Improve code snipper HTTP

### ISSUE THREAD

**Issue by jaroga86** [rangav/thunder-client-support#763]
**Describe the bug**

When the HTTP code snippet is generated, it is generated with the first letter in uppercase and the format should be the same as in the header. A difference if the type CURL is selected maintains the correct format.

**To Reproduce**
Execute a example of request.
Clic in code snipper {}.
In code select HTTP.

**Expected behavior**
The expected behavior is to keep the same format as the header, as is done in the CURL.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.66.2
 - extension version: 1.18.7

**Comment by rangav** [comment]
Hi @jaroga86 did not fully understood your question, can you please share a screenshot?

**Comment by jaroga86** [comment]
Hi rangav,

Sreenshot type http:
![image](https://user-images.githubusercontent.com/20051737/189095269-1513472e-7247-4ea7-9c91-62d32697adba.png)

Sreenshot type curl:

![image](https://user-images.githubusercontent.com/20051737/189095650-b3192d4b-aa93-44e7-b646-ae0d10403d64.png)

In the screenshot you can see the difference.

**Comment by rangav** [comment]
Thanks got it

**Comment by rangav** [comment]
Hi @jaroga86 the code snippet is provided by the library [http](https://github.com/Kong/httpsnippet)

can you report the issue in their github page?

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open it if needed.
