### ISSUE TITLE
Stop collection on fail

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#768]
**Is your feature request related to a problem? Please describe.**

Sometimes it would be nice to stop a collection from running if a request fails

**Describe the solution you'd like**

I would like an option in the `Run Collection` advanced menu to stop running the collection if a request fails. Something like a checkbox:
- [ ] Stop running on request fail

**Describe alternatives you've considered**

Also, maybe it would be nice to specify this for a single request in the folder
For example, a new column of checkboxes, `Stop collection if failed`

**Implementation:**

**Comment by rangav** [comment]
Thanks @andresatierf for the feedback, will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.2`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.4.2

Please let me know your feedback.

**Comment by andresatierf** [comment]
This is amazing, exactly what I wanted @rangav. Great job!

Just have a follow up question. 
> Also, maybe it would be nice to specify this for a single request in the folder
> For example, a new column of checkboxes, `Stop collection if failed`

Is this something that could come in the future or are there no plans to add it to tc?

Also went and read the blog post linked in the release. Had no idea there was a new cli. Already installed it!

**Comment by rangav** [comment]
Glad you like it.

At the request level may be overkill. But will see if anyone else might want this feature. So will review again in the future.


CLI is launched last week, you should have got release notes window opened. May be you might have missed it.

there are lot of new ways you can interact with APIs from CLI, that is not possible with UI.

Please try and let me know your feedback.

**Comment by andresatierf** [comment]
I tried it for a little bit and had some trouble given my setup.
I have several collection for different projects which contain same name folders, eg. login.

I tried to run `tc --col="colname" --fol="folname"` but that just ran the whole collection.

Also with a structure like this:
```
- Collection: test
  - Folder: login
    - Folder: dev
    - Folder: staging
  - Folder: logout
    - Folder: dev
    - Folder: staging
```
would be nice to be able to run the command `tc --fol="login/dev"` or something similar to differentiate same name folders

**Comment by rangav** [comment]
Thanks for feedback, will look into it. 

Alternatively you can also use folder id

to run folder
- `tc —fol 'FolderNameOrId'`

to run collection 
- `tc —col 'ColNameOrId'`

**Comment by rangav** [comment]
you can use list command to see all folder ids in collection - `tc list 'colNameOrId'`

<img width="541" alt="Screenshot 2023-02-17 at 21 33 37" src="https://user-images.githubusercontent.com/8637550/219798157-0de8e79e-5a11-4407-8a8b-1dcac8421b87.png">

**Comment by andresatierf** [comment]
Thanks, apparently I wasn't updated to most recent release, my output didn't have ids on folders
![image](https://user-images.githubusercontent.com/29847057/219879756-7a5630a2-e193-482a-9010-ae2fdef343b5.png)

**Comment by rangav** [comment]
Please update CLI to `v1.0.6`

To Update

- `npm i -g @thunderclient/cli`
