### ISSUE TITLE
Editing issue

### ISSUE THREAD

**Issue by rtarling** [rangav/thunder-client-support#769]
Editing caret "|" is sometimes in the incorrect position - not at side of letter but in middle - see attached image.  Don't get this issue in other VSC windows.

![image](https://user-images.githubusercontent.com/51115354/190561285-0ad6c3c8-9319-495d-aed4-6f4102530fa9.png)

**Comment by rangav** [comment]
Thanks @rtarling for reporting the issue will look into it. 

Did it happen in previous version of extension?

Can you please sample json body to testing which can reproduce the issue

**Comment by rangav** [comment]
@rtarling can you share the following

- Extension version?
- OS version?

**Comment by rtarling** [comment]
Yes it did do it in the previous version too.  The JSON is not exotic, but I can take a look on Monday when I am back at work.

**Comment by rangav** [comment]
> @rtarling can you share the following
> 
> * Extension version?
> * OS platform?
> * Vscode version?

Can you please share above values

**Comment by rtarling** [comment]
Can't replicate at moment, however version shown below.  Will let you know if issue comes back.

Yours ever / Mit freundlichen Gruessen
Roland

________________________________

**Comment by rangav** [comment]
@rtarling Thanks for confirmation, I am closing issue, feel free to re-open if needed.
