### ISSUE TITLE
Can't Import Postman Collection for no reason

### ISSUE THREAD

**Issue by EltonAlvess** [rangav/thunder-client-support#77]
I have exported a collection from Postman (**collection v2.1**) and after that I tried to Import to thunder-client I receive a error "Import failed".

**To Reproduce**
thunder-client > import > select the attached file here.

**Expected behavior**
It should import the collection

**Platform:** 
 - OS: windows 10.

**file to reproduce the error**
[example-data.zip](https://github.com/rangav/thunder-client-support/files/6385449/example-data.zip)

**Comment by rangav** [comment]
Hi @EltonAlvess I will test and get back to you

**Comment by rangav** [comment]
Hi @EltonAlvess there is bug, i just now fixed it, will release with update #14

**Comment by rangav** [comment]
see #14

**Comment by khaledOghli** [comment]
I can't import the postman collection ! is there any solution!

**Comment by khaledOghli** [comment]
The should be json foramt ,it's work now
