### ISSUE TITLE
can't rename new request

### ISSUE THREAD

**Issue by muhammedfurkan** [rangav/thunder-client-support#770]
**Is your feature request related to a problem? Please describe.**
I can't rename request name, like a postman.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/9547040/190631680-23ff110c-b18e-497c-880c-8dc34b6724ec.png)
Rename field should be added to this field.

**Comment by rangav** [comment]
Hi @muhammedfurkan click on `…` icon and you will find option to rename

**Comment by muhammedfurkan** [comment]
> 

still I cant find

**Comment by rangav** [comment]
There is bug related to this which is fixed now, please update to `v1.19.1`.

<img width="261" alt="Screenshot 2022-09-16 at 22 00 39" src="https://user-images.githubusercontent.com/8637550/190735710-d57e0a0c-6f7f-4304-b9a0-c9896e6c3080.png">
