### ISSUE TITLE
Request menu not working

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#771]
**Describe the bug**

The three dot menu on requests is not working since 1.19.0 update. Folder and collection menus still work.
![image](https://user-images.githubusercontent.com/29847057/190681095-fe8041a6-24bc-49bf-bc09-35c9fbe336ef.png)

**To Reproduce**

Try to press the three dot menu on a request.

**Expected behavior**

The request menu to open

**Platform:** 
 - OS: Manjaro
 - vscode version: 1.71.1
 - extension version: 1.19.0

**Solution:**

**Comment by rangav** [comment]
Thanks @andresatierf for reporting the issue, will fix it asap

**Comment by rangav** [comment]
This bug is fixed now, please update to `v1.19.1`
