### ISSUE TITLE
Store data in project

### ISSUE THREAD

**Issue by cumminsd** [rangav/thunder-client-support#772]
I work on a lot of different projects, all of which have a lot of API's. It would be amazing if Thunder Client could save it's data to the local project in a JSON file (or set of files in a folder maybe) that can then be committed with the rest of the code for the project.

This is the one big thing I don't like about Postman (there are a lot of smaller things too :-) ). Exporting and then importing to accomplish this is painful.

The API changes and tests usually coincide with code changes and it would be great to keep them together.

**Comment by rangav** [comment]
@cumminsd this feature is already available from 1 year. You can save data to git.

details here
https://github.com/rangav/thunder-client-support#team

**Comment by cumminsd** [comment]
Gotcha! Sorry I missed that!
