### ISSUE TITLE
Collection Base URL is not parsed correctly after the new update

### ISSUE THREAD

**Issue by deanrih** [rangav/thunder-client-support#775]
**Describe the bug**
After the update, the request that uses the collection settings' base url with a variable doesn't work anymore and parsed incorrectly.

I have an env that contains `api_url_content`, and I set it on one of my collection's base url as `{{api_url_content}}`, previously it worked and translated into `localhost:3000/`, however after the new update it is instead parsed into `%7B%7Bapi_url_content%7D%7D` and thus the entire collection doesn't work anymore.

**To Reproduce**
- Create some variable on the env, let's say `localhost` and have a value of `localhost:3000/`
- Choose some collection and go to settings, set the base url to `{{localhost}}`
- Now choose or create new request that hitting certain endpoint, e.g `api/v1/test-api`
- Send the request
- Request failed to be sent and the client can't resolve the url, the url is translated as `%7B%7Blocalhost%7D%7Dapi/v1/test-api`

**Expected behavior**
The URL should be translated into `http://localhost:3000/api/v1/test-api` and the API can be executed

**Platform:** 
 - OS: macOS 12.4 & Manjaro
 - vscode version: 1.71.2
 - extension version: 1.19.1

**Solution:**
Fetch the variable value first then parse?

**Comment by rangav** [comment]
Thanks @deanrih for reporting the bug, will fix it asap.

**Comment by deanrih** [comment]
> Thanks @deanrih for reporting the bug, will fix it asap.
> 
> Alternatively, You can install previous version until it's fixed.

No, problem.

Understood.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to v1.19.2

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.2

Please let me know your feedback.
