### ISSUE TITLE
Add description filed to saved API requests

### ISSUE THREAD

**Issue by schallm** [rangav/thunder-client-support#777]
**Is your feature request related to a problem? Please describe.**
When sharing API requests with my team, I get questions on what an API call does or if any setup (i.e. specific auth, dependent calls, ....)  is required.  It would be great to have a markdown description field available that could show details about a saved request.

**Describe the solution you'd like**
Add markdown description field to saved requests that would display somewhere (above method/URL?) on the request tab.

**Describe alternatives you've considered**
If the API supports OpenAPI, the initial description could be pulled from there.

**Comment by schallm** [comment]
That works!  Thanks

**Comment by pfaustinopt** [comment]
@rangav is it possible to add documentation to a folder instead of a request?

**Comment by rangav** [comment]
@pfaustinopt currently you can add documentation to collection only.

<img width="1294" alt="Screenshot 2023-02-06 at 18 28 18" src="https://user-images.githubusercontent.com/8637550/217055114-a85810de-caf4-4155-811c-ca0414d075c7.png">

**Comment by pfaustinopt** [comment]
I was creating folders to represent different test cases (each folder containing multiple API calls) and was attempting to find a way to write a summary of that use case.

Do you have any alternatives for this use case?

**Comment by rangav** [comment]
@pfaustinopt for now you can use the collection level documentation facility. 

In future will review the folder level docs

**Comment by pfaustinopt** [comment]
Ok, I will do it.
