### ISSUE TITLE
Create nested folders for collections

### ISSUE THREAD

**Issue by EltonAlvess** [rangav/thunder-client-support#78]
I was thinking if it's possible enable to create nested folder inside the collection. Like the image below

![nestedfolders](https://user-images.githubusercontent.com/1638045/116263057-7315de00-a74f-11eb-8856-48f834949815.png)

**Comment by rangav** [comment]
Hi @EltonAlvess this feature is already request here - #8, I am closing this one, you can add comments in that existing issue,

This feature will be released this week part of next update details here - #14

**Comment by EltonAlvess** [comment]
Thank you @rangav ! I'm sorry about to duplicate the issue. 

You are doing well with this tool man. Congrats!

**Comment by rangav** [comment]
Thanks @EltonAlvess, nested folder feature is now released with v1.1.0.
