### ISSUE TITLE
Importing Postman collection does not populate URLs

### ISSUE THREAD

**Issue by theJsTsGuy** [rangav/thunder-client-support#780]
**Describe the bug**
I have a postman collection JSON, when I import it in thunder client, it seems to fill the URL in the tabs, but when opening one of them, the URL doesn't get populated in the URL bar. 
![image](https://user-images.githubusercontent.com/40920737/191184220-e8d0c7c9-5cb5-4104-a0c3-77870986039c.png)

It does work on postman:
![image](https://user-images.githubusercontent.com/40920737/191184417-bb09f3cd-1a92-4c52-a8bc-4dbcb2f83bd6.png)

**To Reproduce**
Import the collection in thunder client
```json
{
  "variables": [],
  "info": {
    "name": "test collection",
    "description": "",
    "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
  },
  "item": [
    {
      "name": "Google",
      "request": {
        "url": "https://www.google.com/",
        "method": "POST",
        "header": [
          {
            "key": "Accept",
            "value": "application/json",
            "description": ""
          },
          {
            "key": "Content-Type",
            "value": "application/x-www-form-urlencoded",
            "description": ""
          }
        ],
        "body": {
          "mode": "urlencoded",
          "urlencoded": [
            {
              "key": "api_key",
              "value": "Some KEY",
              "type": "text",
              "description": ""
            }
          ]
        },
        "description": ""
      },
      "response": []
    }
  ]
}

```
**Expected behavior**
It should fill out the URL bar.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.71
 - extension version: v1.19.0

**Solution:**
N/A

**Comment by rangav** [comment]
Thanks @theJsTsGuy for reporting the issue, will verify and get back to you.

**Comment by rangav** [comment]
Hi @theJsTsGuy you exported from postman in older format. 2.0.0.

Please export json file in `2.1.0` format, then it will work.

**Comment by theJsTsGuy** [comment]
The version of this JSON isn't something I can change, I guess thunder client will not work with v2.0.0

**Comment by rangav** [comment]
currently we only support `2.1.0` format postman files.

**Comment by rangav** [comment]
its easy to convert 2.0.0 format file to 2.1.0

- Import the 2.0.0 format json file to postman
- Export to 2.1.0 format, this will create new json file

<img width="470" alt="Screenshot 2022-09-20 at 09 59 00" src="https://user-images.githubusercontent.com/8637550/191215620-11a0eaa1-baeb-489e-841f-8a4015979f80.png">

**Comment by theJsTsGuy** [comment]
Thanks for your support, this works perfectly! Although I wished `v2.0.0` was implemented in thunder client too. Have a good day!
