### ISSUE TITLE
Thunder Client stuck at "Processing" stage

### ISSUE THREAD

**Issue by ATLAS-B28** [rangav/thunder-client-support#783]
![Screenshot 2022-09-20 190802](https://user-images.githubusercontent.com/79972089/191272721-1a6a0298-1412-4da5-8edc-e92b23f6ee23.png)
 The testing is stuck at processing stage only is there anything that can be done?

**Comment by ATLAS-B28** [comment]
Sorry to bother I think the there was problem on my machine or network

**Comment by Kumod04** [comment]
bro how can you know that it was machine or network problem can you tell me also i am also facing the same problem

**Comment by rangav** [comment]
@Kumod04 try restarting vscode
