### ISSUE TITLE
single quote issue

### ISSUE THREAD

**Issue by muhammedfurkan** [rangav/thunder-client-support#784]
**Describe the bug**
json only accepts double quotes.

![image](https://user-images.githubusercontent.com/9547040/191278495-f87ee499-add4-4b28-9b25-93678d49e447.png)

**To Reproduce**

**Expected behavior**
Double quotes and single quotes should be accepted. like a postman

**Platform:** 
 - OS: Windows 
 - vscode version: 1.70.0
 - extension version: v1.19.1

**Solution:**
Double quotes and single quotes should be accepted.

**Comment by muhammedfurkan** [comment]
will be added soon ?

**Comment by rangav** [comment]
I am using Ace editor, don't know whether they support single quotes.

https://github.com/ajaxorg/ace

**Comment by rangav** [comment]
@muhammedfurkan if you click `format` It should fix the issue automatically convert single quote to double quote 

you can also use `alt + sht + f` Shortcut 

I am closing this issue, feel free to reopen if needed
