### ISSUE TITLE
Add ability to extract interface and types from the JSON response for TypeScript.

### ISSUE THREAD

**Issue by tankmohit** [rangav/thunder-client-support#785]
**Describe the solution you'd like**
- RapidAPI Client (Another VSC extension similar to ThunderClient) has this feature, in which it can extract types and interface from the JSON response and can save it as a typescript file. RapiAPI client isn't as snappy as ThunderClient, but it has a nice DX for typescript developers which can be replicated in TC.

**Comment by rangav** [comment]
Thanks @tankmohit for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.3

Please let me know your feedback.
