### ISSUE TITLE
Reorder tests similar to environment variables

### ISSUE THREAD

**Issue by shawnpyle** [rangav/thunder-client-support#787]
**Is your feature request related to a problem? Please describe.**
Not a problem, but would love the ability to reorder tests
<img width="607" alt="image" src="https://user-images.githubusercontent.com/48266/191586901-6c1dde91-2948-4816-9b03-96823884b147.png">

like [environment variables do](https://github.com/rangav/thunder-client-support/issues/414).
<img width="342" alt="image" src="https://user-images.githubusercontent.com/48266/191586848-6b2baa94-b41a-4381-858f-93206d46256d.png">

**Describe the solution you'd like**
Provide the up-down-arrow icon in the Tests screen for requests to allow us to order tests as desired.

**Describe alternatives you've considered**
The current work around is to delete the tests that we want moved up and then recreate them in the order desired.

**Implementation:**
Seems similar to the ordering implemented in https://github.com/rangav/thunder-client-support/issues/414

**Comment by rangav** [comment]
@shawnpyle tests reorder is already possible, just hold and input field with mouse and drag over.

will provide up/down arrow icon in the next update

**Comment by shawnpyle** [comment]
So it is! Adding this gif for clarity. Thanks!
![Sep-21-2022 14-04-07](https://user-images.githubusercontent.com/48266/191600038-3be255f0-23b7-4d4a-96e1-7dfe50d4846d.gif)

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
