### ISSUE TITLE
Provide an Insomnia-like Timeline output for the request

### ISSUE THREAD

**Issue by shawnpyle** [rangav/thunder-client-support#788]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
I really like the Timeline feature inside Insomnia. It outputs all the request details as well as the response details in a single screen. This is great for debugging communication with the server. 

![image](https://user-images.githubusercontent.com/48266/191594209-2fe36c6c-6b82-4b79-95bc-98cb2ecc6523.png)

**Describe alternatives you've considered**
I do not know _how_ to do this but if curl is used under the hood, outputting the full log of the session, could be useful.

**Implementation:**

**Comment by rangav** [comment]
@shawnpyle there is vscode setting called `Request Log` change to advanced, you will see request details in output window

**Comment by shawnpyle** [comment]
Interesting. I rarely use the Output window but there it is. 

To get to the output, I had to 
1. View menu
2. Output option
3. Select `Thunder Client` in the dropdown
4. Run a request.

It should look something like
```

Environment Used: <environment-name> (Active)
Request Url: <requested-url>
Method: POST
Request Headers:
{
  "accept": "*/*",
  "user-agent": "Thunder Client (https://www.thunderclient.com)",
  "content-type": "application/json",
  "Authorization": "Basic <auth>"
}
Request Body:
"{\n  \"page_size\": 10,\n  \"search\": {\n      \"email\": \"foo\"\n  }\n}"
```

**Comment by svipas** [comment]
@rangav @shawnpyle This doesn't work, even though it does 2 redirect I always get the same output and even if I remove `User-Agent` from headers it's still sent, this is a bug.

```
---------------- Running Request: ----------------
Request Url: https://share.podimo.com/play/episode/2cbbd315-d9a7-4f78-acdf-6b7939d85893?creatorId=[%E2%80%A6]e30-99e4-bd6e85919108&key=ooWDKBekt3gC&source=un&from=mobile
Method: GET
Request Headers:
{
  "Accept": "*/*",
  "User-Agent": "Thunder Client (https://www.thunderclient.com)"
}
```

**Comment by svipas** [comment]
@rangav @shawnpyle This doesn't work, even though it does 2 redirect I always get the same output and even if I remove `User-Agent` from headers it's still sent, this is a bug.

```
---------------- Running Request: ----------------
Request Url: URL WITH REDIRECTS
Method: GET
Request Headers:
{
  "Accept": "*/*",
  "User-Agent": "Thunder Client (https://www.thunderclient.com)"
}
```

**Comment by rangav** [comment]
@svipas  if you disable the user-agent, then it should work

<img width="801" alt="Screenshot 2023-01-24 at 21 04 01" src="https://user-images.githubusercontent.com/8637550/214414963-294c62bf-2828-4d79-9648-d719c68a8501.png">

**Comment by svipas** [comment]
@rangav Yeah that's true for `User-Agent`, but still there's no output for redirects, is this a bug or I need to enable some sort of setting?

**Comment by rangav** [comment]
It's not a bug I think, the redirect is handled by `axios/got` library automatically, 
don't know if I can get additional details about redirect to log. Will verify it, when I get time.

**Comment by svipas** [comment]
@rangav You could use this link as an e.g. [bit.ly/Qddl](http://bit.ly/Qddl) which should redirect and you will see that output is this:

```
---------------- Running Request: ----------------
Request Url: http://bit.ly/Qddl
Method: GET
Request Headers:
{
  "Accept": "*/*",
  "User-Agent": "Thunder Client (https://www.thunderclient.com)"
}
```

Without any redirect log

**Comment by rangav** [comment]
Thanks @svipas for sharing, will look into it.

**Comment by rangav** [comment]
@svipas I have made the changes, is that good enough?

[https://t.co/7WdtUTEchB](https://t.co/7WdtUTEchB)

<img width="807" alt="Screenshot 2023-01-27 at 16 32 26" src="https://user-images.githubusercontent.com/8637550/215141425-1c570cfd-caae-4665-9c99-5ec5226ed214.png">

**Comment by svipas** [comment]
@rangav yeah that is awesome! What about multiple redirects? For e.g. A -> B -> C, does it work too?

**Comment by rangav** [comment]
@svipas yes will display all redirect chain.

**Comment by svipas** [comment]
@rangav Amazing! When I could test it? Do you plan to release it?

**Comment by rangav** [comment]
@svipas planning to release next week ( may be by Wednesday )

**Comment by rangav** [comment]
@svipas  This feature is now implemented and published to marketplace, please update to `v2.4.0`

### Thunder Client CLI
- https://github.com/rangav/thunder-client-support/releases/tag/v2.4.0

### Documentation
- For documentation read our blog post on [medium.com](https://rangav.medium.com/d91eb5c71d8e)

### Product Hunt
- We are launching today on [Product Hunt](https://www.producthunt.com/posts/thunder-client-cli), Please **upvote** and let us know any feedback.

**Comment by svipas** [comment]
@rangav Thanks a lot it now works properly and I get all redirects in Output! 🎊

**Comment by rangav** [comment]
@svipas thanks for confirmation 👍
