### ISSUE TITLE
git sync not working

### ISSUE THREAD

**Issue by cyrfer** [rangav/thunder-client-support#789]
**Describe the bug**

[git sync](https://github.com/rangav/thunder-client-support#git-sync) is not working. I see no folder named "thunder-tests" or any other folder created.

**To Reproduce**

1. install extension
2. open "workspace" settings (I also tried "user", but that is not recommended)
3. enable "Save to Workspace"

**Expected behavior**

A folder called "thunder-tests" will exist.

**Platform:** 
 - OS: macos 12.6
 - vscode version: 1.71.2
 - extension version: see below

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

**Solution:**
No idea.

**Comment by rangav** [comment]
@cyrfer you need to create a new request and then you will see `thunder-tests` folder

**Comment by danielnsilva** [comment]
Same happened to me, even creating a new request. I had to reopen the project folder to get ```thunder-tests``` created. However, previous activities data where gone.

**Comment by rangav** [comment]
@danielnsilva I just now tested again, working for me. open any empty folder or project folder in vscode and click new request button, then it should create `thunder-tests` folder.

<img width="288" alt="Screenshot 2022-09-22 at 16 44 49" src="https://user-images.githubusercontent.com/8637550/191792876-57249089-30c2-42b1-8608-467a6b323021.png">

**Comment by danielnsilva** [comment]
Actually, README says "Please restart VS Code after updating settings". I missed this step.

**Comment by cyrfer** [comment]
I have restarted VS Code many times after changing the setting and before making this post. I just restarted again and I see no folder.

**Comment by cyrfer** [comment]
@rangav I am trying to save an existing request, so that is not intuitive.
I just tried your recommendation and it works. Adding a request after changing VSCode settings makes the `thunder-tests` folder appear in my workspace.
Thank you!
