### ISSUE TITLE
How to exclude secrets from source control?

### ISSUE THREAD

**Issue by duyn9uyen** [rangav/thunder-client-support#79]
Hi. Loving your extension and the ability to export the collection and environment json into source control. Do you have any future plans to be able to exclude secrets from getting into source control?

**Comment by rangav** [comment]
Hi @duyn9uyen good question, I will think of this how we can implement.

**Comment by wekempf** [comment]
Honestly, I dislike the import/export, hide the files, behavior of Postman and was severely disappointed that this extension behaves the same way. I'd much prefer if the persistence were to a text file that can be saved and opened directly from a workspace/repo directory, making sharing with a team as simple as it can get.

In any case, secrets can be managed by reading them from environment variables (or even .env files). Using a secrets manager of some sort would be better, and more secure, but the simple solution would work for most folks.

**Comment by rangav** [comment]
Hi @wekempf the extension already supports reading data from repo/workspace  folder for requests/collections, please see Team features section.

I am also planning to integrate with .env files to read environment variables

**Comment by rangav** [comment]
Now you can **Link .env file** to environment feature is now implemented in v1.8.0

see all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.8.0

**Comment by bdharrington7** [comment]
Hi @rangav I'm finding this extension to be a true game changer in terms of being able to version and share my project's internal API endpoint calls! I have a couple environments (deployment phases, dev, prod, etc) that I _want_ to share with the team, but it looks like *all* environments (including local) are also saved in the `thunderEnvironment.db` file.

I was hoping that some calls (e.g. a login call) could set a value in an environment variable, but I don't want those committed to the `thunderEnvironment.db` file. Is there a way to do this?
