### ISSUE TITLE
collection

### ISSUE THREAD

**Issue by onlyhasbi** [rangav/thunder-client-support#792]
**Describe the bug**

collection can't delete

**Expected behavior**

collection should be deleted

**Platform:** 
 - OS:  windows
 - vscode version: latest
 - extension version: v1.19.2

**Comment by rangav** [comment]
@onlyhasbi I just now tested its working for me. Can you please share a screenshot

**Comment by rangav** [comment]
Are you using WSL? Or connected to remote?

**Comment by onlyhasbi** [comment]
no, sir

**Comment by rangav** [comment]
Can you able to delete environment or request?

**Comment by onlyhasbi** [comment]
Yes, I can.

**Comment by rangav** [comment]
Thanks, can you share a screenshot or video
What happens when you click delete collection?

**Comment by onlyhasbi** [comment]
I can't send you a short video via email. if you have WhatsApp or another
social media

**Comment by rangav** [comment]
Some users have issue with delete , So we provided the below setting, please enable it, then delete will work.

<img width="997" alt="Screenshot 2022-12-05 at 05 54 30" src="https://user-images.githubusercontent.com/8637550/205559721-0ef46220-1bdb-4b82-9856-7ed21d05319d.png">

**Comment by onlyhasbi** [comment]
ok. thank, rangav
