### ISSUE TITLE
I use uppercase letters in headers, but they sent in lowercase

### ISSUE THREAD

**Issue by nour95** [rangav/thunder-client-support#793]
**Describe the bug**

I have some own defined headers that should have some uppercase letters, say: TestMeA. here both T, M and A should be in uppercase when the request is sent. However, it seems that Thunder client is sending them all in lowercase. 

so e.g. when I send this request with TestMeA header:
![image](https://user-images.githubusercontent.com/24523161/191946492-cf351135-947a-4b25-bd2b-546842109fe4.png)

The request arrive the system (or my IDE) like this:
![image](https://user-images.githubusercontent.com/24523161/191946330-1d12981b-754f-4a84-b986-32912e5e8d2b.png)

or 
in a local sandbox: 
![image](https://user-images.githubusercontent.com/24523161/191945019-f0e8d84f-8f26-47bf-b000-f87c929a32cc.png)

**Expected behavior**

Send the headers as they are without lowercasing them.

**Platform:** 
 - OS: windows 10 & 11
 - vscode version: 1.71.2
 - extension version: latest

**Comment by rangav** [comment]
Hi @nour95 there is vscode setting `Headers Case-Sensitive` please enable it, then it will work.

**Comment by rangav** [comment]
Headers are case-sensitive by default in new version `v1.19.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.3

Please let me know your feedback.

**Comment by nour95** [comment]
@rangav, I am sorry but I couldn't find this setting 'Headers Case-Sensitive' under the extension settings:
![image](https://user-images.githubusercontent.com/24523161/192247134-46b5f9cc-79f2-47ef-aa4f-5338010ebca3.png)

or in the vs settings: 
![image](https://user-images.githubusercontent.com/24523161/192248169-c547fde0-04ad-4e0f-b857-f89447122fcf.png)

So, I am not sure where should I find it. 

I have tried to update the extension to the latest version:
![image](https://user-images.githubusercontent.com/24523161/192248521-4900e7a3-fd70-45c8-9341-c255c6e61e50.png)

But, I still get the header in lower case, even after the update:
![image](https://user-images.githubusercontent.com/24523161/192248844-bc37515f-f303-4b01-9329-589300f92d61.png)

**Comment by rangav** [comment]
Will verify and get back to you

**Comment by nour95** [comment]
Hi @rangav I am sorry but it seems that the problem has been solved after the update. I have checked the header in another mock program and in my real code and it seems that the header is sent now in the correct format. 
Thank you very much and sorry for bothering you!

**Comment by rangav** [comment]
@nour95 no problem, thanks for confirmation 👍 .
