### ISSUE TITLE
Export Collection to Local

### ISSUE THREAD

**Issue by st11x** [rangav/thunder-client-support#797]
Hi, 

I am using VSCode with WSL2, so Thunder Client is installed inside Ubuntu. 

When exporting a collection, if I chose a directory in Linux, it works. If I chose a local directory by clicking on this

![image](https://user-images.githubusercontent.com/7398499/192161934-2aca7bbe-e442-485c-bd1e-12b81fdc01c1.png)

It lets me choose a Windows folder but the export fails without any errors in the console. Do I have to make any config changes for this to work?

thanks.
  Matt

**Comment by rangav** [comment]
@st11x try this setting as mentioned in the below comment

https://github.com/rangav/thunder-client-support/issues/158#issuecomment-851058322

**Comment by st11x** [comment]
@rangav Thanks for the link. That works. 

That setting forces VSCode to run the extension locally which in this case is what is needed. 

Will have to switch back if the collection is stored within the projects in WSL2.
