### ISSUE TITLE
JSON Query not working with special characters

### ISSUE THREAD

**Issue by dome313** [rangav/thunder-client-support#798]
**Describe the bug**
Selecting with JSON Query does not work if value contains special characters

**To Reproduce**
json response:
```
{
  "domain": [
    {
      "name": "google.com",
      "ip": 123.123.123.123
    }
  ]
}
```
JSON `query json.domain[name=google.com].ip`

**Expected behavior**
selection `json.domain[name=google.com].ip` to work

**Platform:** 
 - vscode version:
 - extension version: v1.19.2

**Comment by rangav** [comment]
@dome313 thanks for reporting the issue, will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by surfmuggle** [comment]
I updated to 
 - thunder-client 1.20.1
 - Visual Studio Code Version: 1.71.2 (system setup)

In my case i have this json response


``` 
{
  "status": "ok",
  "featuresSelected": [
    {  "feature": "x1", "price": "1.23" },
    {  "feature": "u7", "price": "4.56"},
    ... many more 
   ]
}
```
I want to check if the price of u7 is 4.56. This is my line `json.featuresSelected[feature=u7].price equal 4.56`

But i get: `Query: json.featuresSelected[feature=u7].price equal to 4.56 => Actual: undefined.

Any ideas what i am doing wrong?

**Comment by rangav** [comment]
Can you try double quotes around `u7`

**Comment by surfmuggle** [comment]
You mean like this?

`json.featuresSelected[feature="u7"].price`

The same result

`.price equal to "4.56" => Actual: undefined`

**Comment by rangav** [comment]
Ok will verify and get back to you later

**Comment by rangav** [comment]
@surfmuggle  

its working for me
<img width="1229" alt="Screenshot 2022-11-12 at 04 57 42" src="https://user-images.githubusercontent.com/8637550/201457910-e682add0-9ee7-42e1-b3c1-2d4c0809219d.png">

Sample request used
<img width="1003" alt="Screenshot 2022-11-12 at 05 01 32" src="https://user-images.githubusercontent.com/8637550/201458031-dc62822a-8044-4b91-ae6b-29e99e45328c.png">


you can test yourself here with this url 
https://www.thunderclient.com/t/echo

**Comment by surfmuggle** [comment]
I called https://www.thunderclient.com/t/echo using this

```
curl -X GET \
  'https://www.thunderclient.com/t/echo' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)'
```

But it returns no result for me:

![thunderclient call to echo](https://user-images.githubusercontent.com/1271555/201480329-190560f4-b66b-4349-ad81-88b22bbabec1.png)

What do i need to get a result from the echo?


I also tested a public api 

```
curl -X GET \
  'https://api.predic8.de/shop/products/' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)'
```

This returns a json like this

```
{
  "meta": { "count": 32, "limit": 10, "page": 1
                  , "next_url": "/shop/products/?page=2&limit=10" }
  , "products": [
    { "name": "Oranges", "product_url": "/shop/products/10" },
    { "name": "Pineapples", "product_url": "/shop/products/33" }
 ]}
```

It seems to work but i do not understand why one test results in `=> Actual: undefined`

### Expected:

```
// returns pass 
json.products[name=Apple].product_url equals /shop/products/18

// returns false
json.products[name=Apple].product_url equals /shop/products/7

```
###  Actual
```
// returns pass
json.products[name=Apple].product_url equals /shop/products/18

// returns false and Actual undefined <-- Why?
json.products[name=Apple].product_url equals /shop/products/7

```

### Screen of using the same query two times

![image](https://user-images.githubusercontent.com/1271555/201480677-2bb09d05-7792-47a2-a965-1d387171f179.png)


Why returns one query `=> Actual: undefined`?

**Comment by surfmuggle** [comment]
I had a typo two dots `..` in one query

**Comment by surfmuggle** [comment]
Is count working?

- Expected: count = 1 should pass because only 1 product has the name Cranberries
- Actual: fail count returns 2 despite that there is only 1 product named Cranberries

Testcases

```
// fails - but should pass
Query: json.products[name=Cranberries] property count is 1 => Actual: count is 2

// pass - but should fail
Query: json.products[name=Cranberries] property count is 2 
```

This is the tested response

```
{
  "meta": { "count": 32, "limit": 10, "page": 1,
    "next_url": "/shop/products/?page=2&limit=10"
  },
  "products": [
    {  "name": "Oranges", "product_url": "/shop/products/10" },
    {  "name": "Pineapples", "product_url": "/shop/products/33" },
    {  "name": "Dried Pineapples", "product_url": "/shop/products/42"  },
    {  "name": "Cranberries", "product_url": "/shop/products/57" },
    {  "name": "Mango fresh", "product_url": "/shop/products/62" },
    {  "name": "Raspberries", "product_url": "/shop/products/90" },
    {  "name": "Cherries", "product_url": "/shop/products/7" },
    {  "name": "Apple", "product_url": "/shop/products/18" },
    {  "name": "Green Grapes", "product_url": "/shop/products/11" },
    {  "name": "Apples", "product_url": "/shop/products/50" }
  ]
}

```

Same problem with oranges

![image](https://user-images.githubusercontent.com/1271555/201482402-2cf6d0e6-bcf8-4d28-9c53-53a65958a057.png)
