### ISSUE TITLE
Support Folders inside collection

### ISSUE THREAD

**Issue by JamesWatling** [rangav/thunder-client-support#8]
**Is your feature request related to a problem? Please describe.**
Just as postman allows it would be very helpful to be able to organize requests into folders inside of a collection

**Describe the solution you'd like**
A way to organize into folders (even nicer if they can be infinite levels deep).

**Describe alternatives you've considered**
Can be very similar to how Postman has nested folders inside a collection

**Comment by rangav** [comment]
Hi @JamesWatling Sure will look into this. if you want to contribute to his feature let me know.

**Comment by rangav** [comment]
v1.1.0 is now published
