### ISSUE TITLE
New Request tab is shown empty on M1

### ISSUE THREAD

**Issue by aistis** [rangav/thunder-client-support#80]
**Description**
When I click on the 'New Request' button, the new tab is opened, but it stays empty (without UI) and there is no way how can I enter data and send a request.

**To Reproduce**
Since it works on the prev gen Mackbook I think it's related to M1 Mackbook.
- Go to the 'Thunder Client' app by clicking on an icon on the VS Code side bar
- Click the button 'New request'
- You should see an empty tab with the 'New Request' title

**Expected behavior**

- In the new tab I expect to see UI (input field for the API endpoint, 'Send' button, response view, etc.)

**Platform:** 
 - OS: macOS 11.3

**Solution:**

**Comment by rangav** [comment]
Hi @aistis please follow details here to fix

https://github.com/rangav/thunder-client-support/issues/48

**Comment by aistis** [comment]
@rangav thanks. Can confirm that it works on VSC Insiders.

**Comment by rangav** [comment]
👍
