### ISSUE TITLE
Allow Local Environment to Link with .env file

### ISSUE THREAD

**Issue by nanaasumadu** [rangav/thunder-client-support#800]
**Is your feature request related to a problem? Please describe.**
The ability to link .env file is useful but that means that for service accounts from domain, .env file has to be linked to each environment e.g. dev test.  Is it possible to allow linking Local Environment with a .env file?  In this case, the service account can be stored in a .env file. 

**Describe the solution you'd like**
Allow linking .env files to Local Environment as shown below.  This will provide some privacy when demonstrating API calls to other teams in that I don't have to display user credentials on the Local Environment tab.

<img width="726" alt="local_environment" src="https://user-images.githubusercontent.com/29611833/192383359-44f8d4e8-49a9-49a0-a662-f7198d89b290.png">

**Describe alternatives you've considered**
It will be good to be able to reference app or user credentials saved in MacOS keychain or equivalent for windows.

**Implementation:**
<img width="726" alt="local_environment" src="https://user-images.githubusercontent.com/29611833/192383707-03650f74-5458-41c2-b517-70ff8967cc65.png">

**Comment by rangav** [comment]
Thanks @nanaasumadu for the feedback, will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by nanaasumadu** [comment]
Thank you so much @rangav.  I have tested the new implementation and it works great 👍 

Thanks once again.  Very much appreciative.

**Comment by rangav** [comment]
Glad you like it 🙂, thanks for confirmation.
