### ISSUE TITLE
Collections' Environment setting does not work as expected

### ISSUE THREAD

**Issue by deanrih** [rangav/thunder-client-support#802]
**Describe the bug**
The Collection's Environment setting and it's environment variables doesn't work as expected.

Scenario:

I have 2 environments, let's say V1 and V2, I mostly working on V2 project so I set V2 as Active Environment, however from time to time I work on V1, in the Collection's setting, specifically on Environment Tab, it says that the selected Environment will take precedence over the Active Environment, so I did set the Environment for my V1 collection to V1 Environment, however when I tried to execute the request, it fail to parse the variable, let's say `{{localhost}}`, instead of `http://localhost:8000/` I got `http://%7B%7Blocalhost%7D%7D` instead

**To Reproduce**
1. Create 2 environments, lets name it A and B
2. Fill A and B with the same variables but different value,
2.1. example: A: `localhost` => `localhost:3000`, B: `localhost` => `localhost:8000`
3. Set Environment A as Active Environment
4. Create 2 collections alongside the appropriate requests, lets name them ColA, and ColB
5. Go to each collection's setting and set each environment to their environment counterpart, also set their 'Base Url' on the Options tab to use the `{{localhost}}` variable
5.1. example: ColA => Environment 'A', ColB => Environment 'B'
6. Execute requests in ColA
7. Request executed successfully
8. Execute requests in ColB **without** changing the Active Environment
9. Request failed to be executed due to can't resolve the host name and failed to parse the variable

**Expected behavior**
Request should be executed successfully because the variable from the Environment B in the Collection ColB is successfully parsed and do take precedence over the Active Environment

**Platform:** 
 - OS: macOS 12.4 & Manjaro
 - vscode version: 1.71.2
 - extension version: 1.19.2, 1.19.3

**Solution:**
Parse every variable from the Active Environment first and then parse every variable from the assigned Environment and replaces any Active Environment variable with the same name

**Comment by rangav** [comment]
Thanks @deanrih will verify and get back to you asap.

**Comment by rangav** [comment]
Thanks I can re-produce the bug, will fix in the next update.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by deanrih** [comment]
Yes, it is fixed, however now I found weird behaviour of the new hover feature, I'll try to make a new issue about this.

Thank you for the fix.
