### ISSUE TITLE
Importing OpenAPI v3 spec adds baseUrl variable

### ISSUE THREAD

**Issue by jerr0328** [rangav/thunder-client-support#803]
**Describe the bug**

When I import an OpenAPI v3 spec (e.g. from a FastAPI server's openapi.json endpoint), all the URLs in the collection have `{{baseUrl}}` prefixed. I would expect that either this isn't included (and just use the Base URL setting on the collection) or that it's included but the `{{baseUrl}}` will be set from the "Base URL" setting from the Collection.

**To Reproduce**

1. Go to Collections
2. Import from URL and use, for instance: `https://httpbin.dmuth.org/openapi.json`
3. Open the first request and check the URL, it will have `{{baseUrl}}/get` (for instance).
4. In the collection Settings, go to Options and put in a Base URL (e.g. `https://httpbin.org`)
5. Run the first request now, and it will give an error that the hostname could not be found, the `{{baseUrl}}` will be included there URL-encoded

**Expected behavior**

Expected results are either:
- Not have `{{baseUrl}}` in the URL when importing OpenAPI specs. OR
- Have the "Base URL" option in the collection Settings set this variable instead of prefixing the URLs.

**Platform:** 
 - OS: macOS 12.6
 - vscode version: 1.71.2
 - extension version: v1.19.3

**Comment by rangav** [comment]
Thanks @jerr0328 for the feedback, will review it.

some users prefer this, so they can set `baseUrl` `env `variable with `https://httpbin.org`

**Comment by jerr0328** [comment]
I think then the default should be to have it unset, but the collection should have Base URL filled with `{{baseUrl}}` variable then. In my case, I want to have several collections in the same environment with different base URLs for each collection, so I want the base URL to be pulled from another variable.

**Comment by rangav** [comment]
ok got it. thanks for the feedback. will make changes in the next update.

**Comment by rangav** [comment]
one more question, most users like to use the BaseUrl feature in collection setting. Should make it as the first tab ( default tab )

![image](https://user-images.githubusercontent.com/8637550/192534706-8cfc7958-6d1f-40ff-b91e-cd16ef65c9f5.png)

**Comment by jerr0328** [comment]
My vote would be yes for having options be the default 👍, at least it would make it very obvious when first setting up the collection that the Base URL can be set. Thanks for the quick response! 😄

**Comment by rangav** [comment]
thanks for confirmation. 👍

**Comment by rangav** [comment]
as an alternative you can replace `{{baseUrl}}` with empty in `thunderclient.json` file and click `refresh `icon in the sidebar.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by jerr0328** [comment]
Sorry for the delay in responding, I just tried it and it works perfectly! ✨ Thanks!

**Comment by rangav** [comment]
Super, thanks for confirmation 👍
