### ISSUE TITLE
Tree Indentation Setting

### ISSUE THREAD

**Issue by st11x** [rangav/thunder-client-support#807]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add an option in the settings to allow the control of the indentation of the tree, See https://github.com/rangav/thunder-client-support/discussions/805

**Describe alternatives you've considered**
No.

**Implementation:**
No.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by st11x** [comment]
@rangav  Thank you, that's great! I like the 10 option, I guess I have old eyes.

**Comment by rangav** [comment]
Glad to know, you like the feature 👍

**Comment by rangav** [comment]
The tree indent setting is renamed with `sidebar` prefix in `v2.0.1`, please re-select the padding again.

<img width="787" alt="Screenshot 2022-11-24 at 23 36 02" src="https://user-images.githubusercontent.com/8637550/203874763-04337923-0837-4fe1-9d31-fdbbbe71f7a5.png">
