### ISSUE TITLE
Env variable value gets corrupted when it has multiple `$` symbols in it

### ISSUE THREAD

**Issue by gloomybrain** [rangav/thunder-client-support#808]
**Describe the bug**
Environment variable value gets corrupted in request body when it has multiple `$` symbols back to back in it.

**To Reproduce**
- create a new environment
- add variable named `EMAIL` and set it to a proper email address e.g. `root@domain.com`
- add variable named `PASSWORD` and set it to Pa$$w0rd
- create a new http request with the following JSON body:
  ` { "email": "{{EMAIL}}", "password": "{{PASSWORD}}" }`
- execute http request from the step above

**Expected behavior**
No interpretation has been made to the value of the variable so the actual request body looks like (notice two **$**s):
`{ "email": "root@domain.com", "password": "Pa$$w0rd" }`

**Actual behavior**
The `$$` gets converted to just `$` so the actual request body looks like (please notice that there is **just one $**):
`{ "email": "root@domain.com", "password": "Pa$w0rd" }`

**Platform:** 
 - OS: MacOS Monterey 12.6
 - vscode version: 1.71.2 (Universal)
 - extension version: v1.19.3

**Solution:**
Supposedly there is some kind of interpretation taking place (I'm sorry, I haven't had time to dig into the sources just yet). Considering the example request above one can safely set the PASSWORD variable to `Pa$$$w0rd` (3 times `$`) or even `Pa$$$$w0rd` (4 times `$`) and it would be "successfully" converted to `Pa$$w0rd`(2 times `$`). Having 5 `$` in a row however makes the value being converted to `Pa$$$w0rd` (3 times `$`).

**Comment by rangav** [comment]
Thanks @gloomybrain for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v1.19.4`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.19.4

Please let me know your feedback.

**Comment by gloomybrain** [comment]
@rangav thanks a lot! My case works as expected, everything's good.

**Comment by rangav** [comment]
Great, Thanks for confirmation 👍
