### ISSUE TITLE
Can't save more than one environment variable from response

### ISSUE THREAD

**Issue by www-chique** [rangav/thunder-client-support#81]
**Describe the bug**
I am trying to set 2 environment variables from a response json. Only the last one in the list gets saved. I have swapped the "setTo" order to come to this conclusion. 

**To Reproduce**
1. A new request which returns json data in response
2. From the json response, set 2 values into 2 environment variables (declared in an Environment)
3. Notice only the last one gets saved

**Expected behavior**
Both (or all) the environment variables to get saved from the response json.

**Platform:** 
 - OS: Windows 10

**Picture:**
1. Here is the request, which returns accessToken and refreshToken, these 2 values are what I am interested in saving.
![image](https://user-images.githubusercontent.com/29447216/116429133-389d6580-a863-11eb-8328-cc6b91d36eb6.png)

2. Here in the environment only the "last" one from the list gets saved always.
![image](https://user-images.githubusercontent.com/29447216/116429228-523ead00-a863-11eb-92fc-fb9b87bc467f.png)

**Comment by rangav** [comment]
v1.1.0 is now published - details here #14
