### ISSUE TITLE
JSON body cursor in wrong position

### ISSUE THREAD

**Issue by jdhawks2132** [rangav/thunder-client-support#815]
Cursor is in the wrong position in when creating JSON object in body.

**Platform:** 
 - OS: Mac 12.6
 - vscode version: 1.71.2
 - extension version: v1.19.4

**Solution:**
I tried some of the older solutions I found online (adjusting the css.min) but nothing has seemed to work as of yet.

<img width="758" alt="Screen Shot 2022-10-03 at 1 16 42 PM" src="https://user-images.githubusercontent.com/90884050/193649381-0026cb97-f84b-4b3f-b7b0-1b5b3b4c0516.png">

**Comment by rangav** [comment]
Hi @jdhawks2132 thanks for reporting, is it happening only with this version? 

Did you try installing previous version and see which one is working?

**Comment by rangav** [comment]
Ok will investigate and get back to you, if I found a solution

**Comment by rangav** [comment]
One question 

did you change vscode default font settings? Or any font changes?

**Comment by jdhawks2132** [comment]
I did just set up my dev environment on a new computer and my default font setting was cascadia code carried over from settings sync. I had not installed that font on the new mac - that fixed it: 

<img width="614" alt="Screen Shot 2022-10-03 at 4 49 23 PM" src="https://user-images.githubusercontent.com/90884050/193692174-5d9484bc-4e85-4a41-a614-6f18611e9c1a.png">

**Comment by rangav** [comment]
Super thanks for confirmation 👍

If it's resolved you can close the issue

**Comment by rangav** [comment]
@leorochael 

did you change vscode default font settings? Or any font changes?

**Comment by leorochael** [comment]
A long time ago I, changed the "Editor: Font Family" settings in a Linux machine. More recently, I had Settings Sync enabled. 

The value that was synced was:

* `'Ubuntu Mono Regular', 'Droid Sans Mono', 'monospace', 'Droid Sans Fallback'`

When I opened vs.code on a mac with Setting Sync enabled, the ThunderClient payload editor was using a variable-width font and manifesting the OP issue of lack of sync between visible cursor position and text insertion point.

Turning off Sync for the setting "Editor: Font Family" and resetting it to its original value on the mac made the font be mono-spaced and fixed the OP issue.

For the record, the reset "Editor: Font Family" setting on macos is:

* `Menlo, Monaco, 'Courier New', monospace`

**Comment by rangav** [comment]
Most users requested to use vscode editor font in Thunder Client response editor. so we made that as default option.

Good that you fixed the issue now.
