### ISSUE TITLE
Add support for path variables like in postman

### ISSUE THREAD

**Issue by SciSaif** [rangav/thunder-client-support#816]
**Describe the solution you'd like**
Add support for path variables like in postman.
so that we can have urls like 
{{proxy}}/users/:id 
and then set the id in path variable

**Comment by rangav** [comment]
@SciSaif 

see details here
https://github.com/rangav/thunder-client-support#path

**Comment by SciSaif** [comment]
> @SciSaif
> 
> see details here https://github.com/rangav/thunder-client-support#path

oh sorry about that, thanks :)
