### ISSUE TITLE
ENV Variable Hover feature incorrectly showing RAW variable for 'nested variable'

### ISSUE THREAD

**Issue by deanrih** [rangav/thunder-client-support#817]
**Describe the bug**
The new ENV Variable Hover feature is neat, but it has some quirk with my use case, namely 'nested' variable.

For example, I have variable named `host` and `port`, which contains `localhost` and `3000` respectively, I also have a variable named `base_url` which contains `{{host}}:{{port}}/`, in practical use, the `base_url` or `{{base_url}}` is correctly parsed as `localhost:3000/`, but on the hover feature I was expecting it to display the fully parsed text, but instead it displays `{{host}}:{{port}}/`, see screenshot below.

![Screen Shot 2022-10-04 at 11 02 15 AM](https://user-images.githubusercontent.com/16235605/193734234-648266e3-2617-4596-9eda-59f8aa6455e9.png)

If this is more appropriate to be labeled as Feature Request, then feel free to change the label.

**To Reproduce**
1. Go to ENV
2. Create 2 variable
2.1 `host` => `localhost`
2.2 `url` => `{{host}}/`
3. On the regular request or collection use the `{{url}}` variable for the base path
4. Hover the variable with the mouse
5. It shows `{{host}}/` instead of `localhost/`

**Expected behavior**
The displayed text should be the fully parsed one.

**Platform:** 
 - OS: macOS 12.4 & Manjaro
 - vscode version: 1.71.2
 - extension version: 1.19.4

**Solution:**
Use the same behaviour as the request/collection which parse the variable and it's 'nested' variable as well before being shown.

**Comment by rangav** [comment]
Thanks @deanrih, for reporting the error.

Forgot to test for nesting variables, will fix in the next update

**Comment by rangav** [comment]
This bug is fixed now, Please update to` v1.19.5`
