### ISSUE TITLE
Oauth 2 refresh token not working for Grant Type: Client Credentials

### ISSUE THREAD

**Issue by Dragod** [rangav/thunder-client-support#818]
**Describe the bug**
OAuth 2  grant type Client credentials do not refresh the token

I have tried both "SendAuth": 
- As Auth Header
- As Request Body

If I click "Generate token" button it does refresh but it's not automatic :)

**To Reproduce**
Enter all the details for OAuth 2  Authentication 

Granty Type: Client credentials

**Expected behavior**
When the token expire should be renewed
![Code_AwNCMZvCOE](https://user-images.githubusercontent.com/4368630/193792519-f442d76c-a975-40dd-95dc-71a266240e1e.png)

**Platform:** 
 - OS: Windows10
 - vscode version: 1.71.2
 - extension version: 1.19.4

**Solution:**
When the token expire should be refreshed.

**Comment by rangav** [comment]
@Dragod thanks for reporting the error, will look into it.

**Comment by rangav** [comment]
@Dragod I have fixed the bug, would you like to test and confirm its working or not?

I dont have client_credential api to test.

I will upload `vsix` file here, let me know

**Comment by Dragod** [comment]
> @Dragod thanks for reporting the error, will look into it.



> @Dragod I have fixed the bug, would you like to test and confirm its working or not?
> 
> I dont have client_credential api to test.
> 
> I will upload `vsix` file here, let me know

Thanks will do

**Comment by rangav** [comment]
This bug is fixed now, Please update to` v1.19.5`

**Comment by Dragod** [comment]
It's fixed thank you for your work, appreciate

**Comment by rangav** [comment]
Thanks for confirmation 👍
