### ISSUE TITLE
A specific string of Query Parameters is changed to a special character.

### ISSUE THREAD

**Issue by anjunsik** [rangav/thunder-client-support#819]
**Describe the bug**

If "sect" is entered from the second item of Query Parameters, "sect" is automatically changed to "§" special character in the URL input window.

As of v1.19.4, that bug does not occur.

![image](https://user-images.githubusercontent.com/66097508/193982231-3938410e-a150-49d6-b753-4496a0bade9c.png)

**To Reproduce**

Query Parameters The first item has any value, and sect is input from the second item.

**Expected behavior**

URL: sect -> §

**Platform:** 
 - OS: macOS Monterey 12.6
 - vscode version: 1.71.2
 - extension version: 1.19.5

**Comment by rangav** [comment]
Thanks @anjunsik for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
@anjunsik I did a quick release to fix this bug, please update to `v1.19.6`

**Comment by anjunsik** [comment]
It works fine~ Thank you!
