### ISSUE TITLE
Can we have a cUrl import feature?

### ISSUE THREAD

**Issue by jitendrakumarr** [rangav/thunder-client-support#82]
**Is your feature request related to a problem? Please describe.**

When you have a curl and you want it to import as a request, there is no feature available. It is a very useful feature and most commonly used in other tools like postman.

**Describe the solution you'd like**

A simple multiline text box where we can paste the curl and one button to import/crate request should work.

**Describe alternatives you've considered**

No alternatives as of now.

**Implementation:**

A simple multiline text box where we can paste the curl and one button to import/crate request should work.

**Comment by rangav** [comment]
Hi @jitendrakumarr there is an exiting issue you can add your comments there - https://github.com/rangav/thunder-client-support/issues/11
