### ISSUE TITLE
XSS in Activity tab

### ISSUE THREAD

**Issue by icetroll** [rangav/thunder-client-support#820]
It's possible to self xss by adding a html scape `"\>` can easily be fixed by html encoding the symbols

![bild](https://user-images.githubusercontent.com/14633666/194063626-27c751d8-1ee7-4e98-bd10-3e4513d35f39.png)

**Comment by rangav** [comment]
@icetroll thanks for reporting the issue, will fix it asap.

**Comment by rangav** [comment]
This is fixed now, please update to `v1.19.7`
