### ISSUE TITLE
Support for variable types/secret variables

### ISSUE THREAD

**Issue by DanSkow1234** [rangav/thunder-client-support#824]
**Describe the solution you'd like**
In Postman when creating environment variables, you're able to select a variable type, with the options being "default" and "secret." If you select "secret," the variable value is masked instead of being shown on the screen and saved in plain text. This option would be ideal for storing sensitive data like passwords.

**Comment by rangav** [comment]
Hi @DanSkow1234 thanks for creating feature request 

One clarification:
Masking secret should on UI only right? In the db json file the secrets will still in plain text.

**Comment by DanSkow1234** [comment]
Yeah. My goal is to have a more secure way to do basic authentication. Entering the username and password in the Basic Auth fields sync's the username and password to the repo in the Collection json in plain text. 
What I've been doing is putting a {{username}} and {{password}} variable in the basic auth section, then I have the username and password variables defined in a Local Environment so it doesn't sync to the Repo, but the variable value is plain text. 
I'm open to other ideas for making basic auth more secure. 
Another thought I had was to have a pop-up option for basic auth, so it never saves creds and you have to enter the creds manually when you run things in that collection, but I'm guessing that would be a lot harder to implement.

**Comment by rangav** [comment]
Saving secrets not to be synced in local environment is the best option, and then use that values in basic auth and other areas of request.

you can `link to .env` files if you prefer that.

Lets keep things simple for now.

Will provide option to mask secrets on the UI.

**Comment by jensklose** [comment]
... but if I get these secrets from a response (e.g. login) then I'm lost.
Thunder-Client only support setting of PUBLIC (git shared) env variables. What about a "setLocalEnv" test feature?

**Comment by rangav** [comment]
@jensklose its already supported. use set env variable and use the variable with scope format `{{variable, local}}`

see docs here
https://github.com/rangav/thunder-client-support#set-env-with-scope

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.3`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.4.3

Please let me know your feedback.
