### ISSUE TITLE
Variable has # no longer work

### ISSUE THREAD

**Issue by jimmy-vo-librestream** [rangav/thunder-client-support#825]
**Describe the bug**
for example if I have an env var saved in .env
```
password=qwe!@#QWE
```

**To Reproduce**
password is read as `qwe!@`. The part after # was cut off

**Expected behavior**
password should be read as `qwe!@#QWE`

**Platform:** 
 - OS: Windows
 - vscode version: 1.71.2
 - extension version: 1.19.4

**Solution:**
add unit test to cover this?

**Comment by rangav** [comment]
I just now tested, its working for me. 

Not sure where you are referring to? Can you share a screenshot

<img width="1099" alt="Screenshot 2022-10-06 at 21 12 49" src="https://user-images.githubusercontent.com/8637550/194409529-d80c096c-c31a-4dc4-b24e-7715044a46f3.png">

**Comment by jimmy-vo-librestream** [comment]
I reversed to v1.19.0 to get it working![image](https://user-images.githubusercontent.com/73655109/194411537-dcacb6c9-d0d9-4994-a555-8fae6febec2d.png)

**Comment by jimmy-vo-librestream** [comment]
maybe because it's in the body?

**Comment by rangav** [comment]
thanks let me verify it.

**Comment by rangav** [comment]
in .env files `#` is considered as comment. so you need to put the value in `double quotes`, then it will work

In version `v1.19.3` we are reading .env file using standard [dotenv](https://github.com/motdotla/dotenv) npm library

ref - https://stackoverflow.com/a/56688763/4035948

<img width="347" alt="Screenshot 2022-10-06 at 21 39 33" src="https://user-images.githubusercontent.com/8637550/194414285-f3373723-596e-4286-973b-ccc71263d39d.png">

**Comment by jimmy-vo-librestream** [comment]
thanks, the workaround's good enough for me

**Comment by rangav** [comment]
Thanks, I am closing the issue, feel free to re-open if needed.
