### ISSUE TITLE
VSCode config backup

### ISSUE THREAD

**Issue by hyoretsu** [rangav/thunder-client-support#828]
Let us include requests, environments, collections, etc in the backup made by VSCode. #826

Especially because having all your collections as part of a tool is (sometimes) better than having a collection saved in Git for each repository.

**Comment by rangav** [comment]
Hi @hyoretsu 

You can save all tests data in single separate repository and use that repository path in thunder client setting and then you dont have to save the data in each repository.

See custom location setting below
<img width="1050" alt="Screenshot 2022-10-08 at 19 06 23" src="https://user-images.githubusercontent.com/8637550/194721463-ba7d79f0-81fa-4a12-a0ac-9b2b9040abd2.png">

**Comment by hyoretsu** [comment]
Having VSCode manage backup would be better than committing to a dummy repository at every change in requests. (Which is a workaround of sorts)

**Comment by rangav** [comment]
Ok got it, thanks for feedback, will review it.

**Comment by rangav** [comment]
Looks like there is limit of size for using build-in vscode sync - might not be good solution
https://github.com/microsoft/vscode/issues/86178#issuecomment-578294231

**Comment by rangav** [comment]
Will give a try and see if we can use settings sync to sync request data,  when I got time and update here.
