### ISSUE TITLE
Form Post Request Not Working (Fields are required)

### ISSUE THREAD

**Issue by YoussefZidan** [rangav/thunder-client-support#83]
Trying to make a **POST** request (login) with **Form** type
- email
- password

Backend response with validation errors like I'm sending an **empty** form (all fiends are required)

but when I try the same thing with **JSON** format it works fine.

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/q9hwe3fctaj83a7w1rpr.JPG)

![Alt Text](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/riqyslahapcttisj40aq.JPG)

**Comment by rangav** [comment]
Hi @YoussefZidan i think you back end is expecting json body?

**Comment by YoussefZidan** [comment]
> Hi @YoussefZidan i think you back end is expecting json body?

Hello @rangav, In Postman it works fine with any type.

**Comment by YoussefZidan** [comment]
I tried to remove the **Content-Type: application/json** in **headers** and it worked fine.
Still don't know why it's working fine in **Postman** with **Content-Type: application/json** and not working with **Thunder Client**

**Comment by rangav** [comment]
hi @rangav when you posting body, thunder client will set the proper content-type header based on the format selected, you dont have set anything, 

when you manually set it or set wrong header, it wont update it.

So you are setting the wrong content-type header and using the form fields. 

Hope you got the point?

**Comment by YoussefZidan** [comment]
> when you posting body, thunder client will set the proper content-type header based on the format selected, you dont have set anything,
> 
> when you manually set it or set wrong header, it wont update it.
> 
> So you are setting the wrong content-type header and using the form fields.
> 
> Hope you got the point?

Yes, Thanks.
