### ISSUE TITLE
Merge conflict every single time I try to pull. 

### ISSUE THREAD

**Issue by SciSaif** [rangav/thunder-client-support#830]
We are a team of 3, we are working on the same branch and everytime we try to git pull, there is a merge conflict in thunder files. 
how can I solve this?

**Comment by rangav** [comment]
Hi @SciSaif, Open the merge editor in vscode and choose what changes you like and accept merge.

It is same as your normal git projects.

**Comment by SciSaif** [comment]
oh, thanks
