### ISSUE TITLE
Auth header is not added using OAuth2 client credentials

### ISSUE THREAD

**Issue by loic-simon** [rangav/thunder-client-support#831]
**Describe the bug**

When generating an access tokent using the Auth / OAuth2 tab, then sending a request, the `Authorization: Bearer <token>` is not added by the client.

There is my configuration:

![image](https://user-images.githubusercontent.com/62268282/195310039-a33e7e69-ccbb-46cf-887c-0695f24d9b88.png)

You can see the headers sent on the left panel. The "grant" part works fine, and the generated token is correct, but not sent with the request.

I suspect it can be due to either
* requesting a non-HTTPS API (local Flask server) or a custom port?
* using Client Credentials grant type?
* using a cusom audience ("backend")?

**To Reproduce**

Configure OAuth2 options as in the screen, get a access token, and send a request

**Expected behavior**

The client should add a header `Authorization: Bearer <token>` 

**Platform:** 
 - OS: macOS 12.4 (M1 chip)
 - vscode version: 1.71.2 (Universal)
 - extension version: 1.19.7

**Solution:**

As a workaround, copy-pasting the generated token in the "Bearer" tab (or even manually in the "Headers" tab).

**Comment by rangav** [comment]
Hi @loic-simon thanks for reporting the issue,

When I test it it is working fine for me. see logs screenshot.

<img width="1468" alt="Screenshot 2022-10-12 at 11 05 43" src="https://user-images.githubusercontent.com/8637550/195314745-de407d31-572a-4671-8457-146d26c9336d.png">

Can you share your logs screenshot in `output` window?

**Comment by loic-simon** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/62268282/195315680-16fd4246-5e60-4ae2-8b8a-d53ec1a1fd2a.png)

I tried re-generating token, saving it, no change :(

Tanks for investigating!

**Comment by loic-simon** [comment]
Yes, I was on this tab.

Opening a fresh window indeed woked, thanks! I should have tried it in the first time. I suppose it's an issue when you just installed the extension or similar?

Anyway, thanks a lot and thanks for this extension, I'm just beginning with it but looks really great!

**Comment by rangav** [comment]
Super thanks for confirmation 👍 .

Dont know exactly the issue, sometimes these things happen, re-starting vscode might solve most of the issues.

**Comment by rangav** [comment]
and also happy to hear that you like to extension, let me know any feedback to improve the product further.

**Comment by lgall3t** [comment]
Hello.

I have the same problem describe in this issue: the access token is generated (and valid) but it is never passed in HTTP header  (confirmed in the "watch" tab).
I used equivalent settings seen in loic-simon's capture.

Restarting Visual Studio Code don't solve the issue in my environment (VSCode 1.92.2, user setup + ThunderClient v2.24.13).

I have to use the workaround "copy-pasting the generated token in the Bearer tab" systematically.
