### ISSUE TITLE
a way to import a cUrl request into a new request

### ISSUE THREAD

**Issue by gabrielsantosblanchet** [rangav/thunder-client-support#832]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
an import button so i can paste a curl request and i will be able to do the request with ThunderClient

**Describe alternatives you've considered**
using the postman import request feature to generate the request

**Comment by rangav** [comment]
It’s already possible 

see this comment
https://github.com/rangav/thunder-client-support/issues/11#issuecomment-1201189065
