### ISSUE TITLE
Environment Variables with integer names are passed as the variable name

### ISSUE THREAD

**Issue by spg-iwilson** [rangav/thunder-client-support#833]
**Describe the bug**
If you create an environment variable with the name 1234, it will be passed as the value {{1234}}

**To Reproduce**
Create an environment variable called 1234
Use the environment variable in a REST call, e.g. {{1234}}
The variable is shown in green
The REST endpoint receives the value {{1234}} instead of the value of the variable

**Expected behavior**
The REST endpoint should receive the value of the variable

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.72.1
 - extension version:1.19.7

**Solution:**

**Comment by rangav** [comment]
This bug is fixed now, please update to `v1.20.1`

See release notes here
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.1
