### ISSUE TITLE
ThunderClient showing blank screen with a clock icon

### ISSUE THREAD

**Issue by Kaushik2629** [rangav/thunder-client-support#834]
**Describe the bug**
Thunder Client perhaps in the process of loading previous requests , isn't showing anything but a black screen

**To Reproduce**
Not sure how to reproduce this

**Expected behavior**
Expected to load the window where I can create a new API request.

![image](https://user-images.githubusercontent.com/64730453/195507334-9116007e-fa7c-48e3-b228-b731c9b7a99f.png)

Tried re-installing the extension, also re-installed VS Code several times, seems like the extension has got crashed.

**Platform:** 
 - OS: Windows 10
 - vscode version: 1.72.1
 - extension version: 1.20.0

**Comment by rangav** [comment]
Thanks @Kaushik2629 for reporting the issue, will look into it.

Please install previous version of extension.

**Comment by rangav** [comment]
Thanks for finding the issue. Sometimes strange things happen with latest version of vscode. Maybe it will be fixed in the next update.

**Comment by rangav** [comment]
I am closing the issue, feel free to re-open if needed
