### ISSUE TITLE
Add Drag & Drop sorting for Forms ?

### ISSUE THREAD

**Issue by AliSentice2022** [rangav/thunder-client-support#835]
On your latest release you added drag and drop feature for sorting the query parameters can you do the same with the body forms ?

**Comment by rangav** [comment]
Thanks @AliSentice2022 for feedback, will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.20.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.1

Please let me know your feedback.

**Comment by AliSentice2022** [comment]
Just Tested and it works perfectly , 

Good job 👍

**Comment by rangav** [comment]
Thanks @AliSentice2022 for the confirmation 👍
