### ISSUE TITLE
Circular dependency when pre-running

### ISSUE THREAD

**Issue by hyoretsu** [rangav/thunder-client-support#837]
If we set a pre-run collection-wide to /login, when running a request to /login it'll throw up an error
`Circular Dependency detected in Pre Requests, Please fix it.`

**Comment by rangav** [comment]
The error means login request cannot call login as pre request.

Move login to separate collection and then link to it.

**Comment by hyoretsu** [comment]
The error is understandable, but it shouldn't happen. Otherwise we're gonna have a collection for all the pre-run requests and another for the rest of the requests. `/login` is a request in the project which I'm using the collection for, not another one.

**Comment by rangav** [comment]
Ok got your point, what it should do when it detects circular dependency? Just stop executing pre requests for it.

Another option is to add `login` as pre-request for `first request` in the collection

**Comment by hyoretsu** [comment]
Simply ignore the pre-request when it's the same as the request being executed. Not a circular dependency, just a useless extra.

**Comment by rangav** [comment]
Ok, will ignore pre-requests in the next release

**Comment by rangav** [comment]
This bug is fixed now, please update to `v1.20.1`

See release notes here
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.1
