### ISSUE TITLE
Use Ctrl+Z for undo last changes in URL Field

### ISSUE THREAD

**Issue by M97Chahboun** [rangav/thunder-client-support#838]
**Allow user to use ctrl+z in URL Field for undo last url modification**
Thank you.

**Comment by rangav** [comment]
Thanks @M97Chahboun for feedback, Will look into it.

**Comment by M97Chahboun** [comment]
@rangav Good luck 🔥

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.15.0`

See all features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.15.0

Please test and let me know your feedback.

**Comment by M97Chahboun** [comment]
@rangav Tested & working as expected Thanks

**Comment by rangav** [comment]
Thanks @M97Chahboun for confirmation

**Comment by M97Chahboun** [comment]
You are welcome, Good lusk
