### ISSUE TITLE
Cannot import `swagger.json` / OpenAPI

### ISSUE THREAD

**Issue by chriszo111** [rangav/thunder-client-support#84]
**Describe the bug**
I tried importing `swagger.json` which is an auto-generated file if you are using https://swagger.io/ and describes the API in a single `JSON` file. I get a generic error:

> Failed to import

**To Reproduce**
1. Download a sample `swagger.json` here: https://petstore.swagger.io/v2/swagger.json (or generate one yourself)
2. Import the file using ThunderClient in VSCode
3. See the generic error at the bottom left

![image](https://user-images.githubusercontent.com/7249742/116537164-29abc700-a8e6-11eb-8b1f-3d4aed0860e7.png)

**Expected behavior**
The `swagger.json` is successfully imported and the described API available as a Collection in VSCode/ThunderClient

**Platform:** 
 - OS: macOS Big Sur 11.3

**Solution:**

**Comment by rangav** [comment]
Hi @chriszo111 not supported yet, 

Here is the project if you like submit PR, https://github.com/rangav/thunder-imports

**Comment by rangav** [comment]
Hi @RensBoeser, sorry missed your message, if you are still interested in contributing to import of openAPI, let me know.

I am also started looking into this feature

**Comment by jleemur** [comment]
Hi @rangav I'd like to help as well, importing a swagger into thunder client is a feature I'd love!

**Comment by rangav** [comment]
Hi @jleemur thanks, add your username to thunder-imports module project.

**Comment by EltonAlvess** [comment]
i would like to help also

**Comment by rangav** [comment]
Thanks @EltonAlvess, added your username to the `thunder-imports` project

**Comment by rangav** [comment]
Hi all,

I have finished this feature, may not have covered all edge cases, 

I have published to **marketplace** as `pre-release` version `v1.13.4`, for testing. 

Please test and let me know if key details are not importing.

How to install pre-release version
![Screenshot 2022-03-02 at 15 14 35](https://user-images.githubusercontent.com/8637550/156390587-b6be1a85-92c4-4ba5-9592-62827ae24621.png)

**Comment by ruckc** [comment]
@rangav - with the pre-release version... how do you import a swagger/openapi document?  I can't find the right button

**Comment by rangav** [comment]
Can anyone confirm Import OpenAPI is working or not?

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace as release version `v1.14.0`

See all features and bugs fixed here
https://github.com/rangav/thunder-client-support/releases/tag/v1.14.0

**Comment by monim67** [comment]
Our backend provides a url for swagger.json file which updates regularly as development progresses. Is there any plan of importing swagger from URL? which can be reloaded if there's any update to swagger.json?

**Comment by rangav** [comment]
@monim67 thanks for feedback, can you please create a new feature for this.

**Comment by rangav** [comment]
Hi All, We implemented Import `Collection / Environment` from Url in v1.17.0

  <img width="289" alt="Screenshot 2022-08-01 at 14 25 54" src="https://user-images.githubusercontent.com/8637550/182158459-46e9806d-a732-480f-92e0-6d51162de5ff.png">
  
  See all features released here
https://github.com/rangav/thunder-client-support/releases/tag/v1.17.0
