### ISSUE TITLE
"Couldn't resolve the hostname to an IP address. Please check the URL." error for requests against .vijay domains

### ISSUE THREAD

**Issue by Vijay-Vaghela** [rangav/thunder-client-support#840]
Describe the bug

.vijay host in local server

I connect to them using the SSH client in VS Code.
They are set in my hosts file and accessible via browser

But Thunder issues the warning "Couldn't resolve the hostname to an IP address. Please check the URL." with them.

Platform:

    OS: Ubuntu 22.04
    vscode 1.72.0
    extension version: 1.20.0

Solution:

**Comment by rangav** [comment]
@Vijay-Vaghela Where is the extension installed?
Is it on local pc or remote server?

**Comment by Vijay-Vaghela** [comment]
> Where is the extension installed?
Remote - SSH VS Code Extension 
> Is it on local pc or remote server?
Local pc
> and can you access the url in browser from your local pc?
Yes

**Comment by rangav** [comment]
Can you share a screenshot of the request window and error.

**Comment by Vijay-Vaghela** [comment]
The thunder client extension reinstalled and works great.

Thank you for your valuable time.

**Comment by rangav** [comment]
Good to know, it’s working for you now 👍
