### ISSUE TITLE
Pre Run and empty variables

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#841]
**Describe the bug**

Pre Run  with the condition `When variable Is Empty` does not work if the variable does not exist.
This is a problem because when setting an environment variable in the Tests tab to an empty value, the variable is deleted instead of being empty

**To Reproduce**

- Create an environment variable with a value
- Create 2 requests:
  - First request: 
    - Set the environment variable to an empty value in the tests tab
  - Second Request:
    - Pre Run a request with the condition `When Variable Is Empty`

**Expected behavior**

The Pre Run of the second request should be run but is not happening

**Platform:** 
 - OS: Manjaro
 - vscode version: 1.72.2
 - extension version: 1.20.0

**Solution:**

I can see two ways of fixing it. The pre run condition `When Variable Is Empty` should run if the variable does not exist or setting an environment variable to an empty value should not delete the variable.

**Comment by rangav** [comment]
Thanks @andresatierf for reporting the issue, will look into it.

**Comment by rangav** [comment]
@andresatierf 

I have just now tested the following below and its working for me

1. Set value value to empty (see below image)
2. Pre-request is working when the variable is empty ( from the logs in output window)
3. Pre-request is working when the variable doest not exist ( from the logs in output window)

<img width="1593" alt="Screenshot 2022-10-16 at 12 49 55" src="https://user-images.githubusercontent.com/8637550/196033838-7a1abb7d-30bc-4258-a182-a310731a757e.png">

**Comment by rangav** [comment]
which one is added as pre-request (is it first or 2nd ) and which is main request?

**Comment by andresatierf** [comment]
I set the variable with the response of the request, not with null directly.


I have a login and a logout request.

The login returns a cookie, which I set to the variable.
The logout does the same but returns the empty cookie.


Later today I will screenshot the requests to be more clear.

**Comment by andresatierf** [comment]
These are my 2 requests

![Screenshot from 2022-10-16 19-32-33](https://user-images.githubusercontent.com/29847057/196052029-f58c15a2-ed7e-4c6b-972d-e41ce3084fc7.png)
![Screenshot from 2022-10-16 19-28-55](https://user-images.githubusercontent.com/29847057/196052044-1e7f2eae-23ee-4a7f-a6de-1aeb8bac2eda.png)
![Screenshot from 2022-10-16 19-34-15](https://user-images.githubusercontent.com/29847057/196052104-7a62c021-380e-4658-b733-e696b86a4359.png)

Running in the order: Login, Logout, Logout 
The last request will not run the pre run test

**Comment by rangav** [comment]
Thanks for sharing screenshots, when you say last request did not run.

Are you running a collection or folder?

can you share screenshot of run collection view?

**Comment by andresatierf** [comment]
Apologies, I was not clear. I meant the pre run is not executed. I ran the requests manually

**Comment by andresatierf** [comment]
After further testing, I realized the `{{sid}}` variable is not being cleared on the logout request despite being assigned an empty value (second screenshot). I think this is what's causing my problems.
Is this intended or a bug?

The original problem seems to not be a problem, my bad. Sorry about that

**Comment by rangav** [comment]
Could be a bug, Will verify and get back to you

**Comment by rangav** [comment]
@andresatierf I can confirm its a bug, will update in the next release

**Comment by rangav** [comment]
This bug is fixed now, please update to `v1.20.1`

See release notes here
https://github.com/rangav/thunder-client-support/releases/tag/v1.20.1
