### ISSUE TITLE
Thunder Client - possible to change json value using a GET to PUT using a Runner?

### ISSUE THREAD

**Issue by engineerpatrickedward** [rangav/thunder-client-support#842]
Hello,

is it possible to, change json value without having to hard-code it to json body? - wanted to see if its possible to do a GET then change a certain VALUE of a key,  right after do a PUT... all in a runner?

**Comment by rangav** [comment]
Hi @engineerpatrickedward 

currently not possible to manipulate, we have pre-request scripting in roadmap https://github.com/rangav/thunder-client-support/issues/16

We have dynamic variables, see if it's any useful 
https://github.com/rangav/thunder-client-support#variables
