### ISSUE TITLE
Collections sync across multiple devices

### ISSUE THREAD

**Issue by kagarlickij** [rangav/thunder-client-support#843]
I'm using VSCode with GitHub account to sync settings across multiple computers,
I've enabled `Thunder-client: Save To Workspace` option but it doesn't upload collections to other devices
How should I properly sync across multiple devices?
Thanks in advance!

**Comment by rangav** [comment]
Hi @kagarlickij 

When you enable `Thunder-client: Save To Workspace` setting, the extension will save the requests data in current workspace. Then you can checkin into git.

Your team members will pull the changes from git, to see the requests data.

**Comment by kagarlickij** [comment]
@rangav thanks for your answer,
but is there some way to sync collections automatically (without manual git actions)?

**Comment by rangav** [comment]
Currently we have only saving to git project option.

Later we plan to add sync using `Settings sync`

Alternatively you can also manually export and import collections

**Comment by kagarlickij** [comment]
@rangav it would be great to see it in `Settings sync`, will be waiting for that feature, thanks!

**Comment by rangav** [comment]
May try this extension to sync files

https://github.com/zokugun/vscode-sync-settings#external-files
