### ISSUE TITLE
Generate random names

### ISSUE THREAD

**Issue by chm10** [rangav/thunder-client-support#844]
Postman has a feature to generate random names and surnames.

```
{{:randomFullName}}
```

I checked you added a feature to generate random data. But I cannot find a possible way to generate a random name.
https://github.com/rangav/thunder-client-support/issues/136

**Comment by rangav** [comment]
Hi @chm10 

Please find docs here 
https://github.com/rangav/thunder-client-support#variables

**Comment by chm10** [comment]
Thank you for referencing the docs. I tested something like that. 
```
"customerName": "{{#string}} {{#string}}"
```

Resulting

```
"customerName": "Dach 2760530ccece Douglas db4ee32597e5"
```

I can get only the names.

**Comment by rangav** [comment]
Will update in the next release
