### ISSUE TITLE
Set default values for headers

### ISSUE THREAD

**Issue by JeffersonBledsoe** [rangav/thunder-client-support#845]
**Is your feature request related to a problem? Please describe.**

The majority of my requests I often use the same Http Headers. It would be nice to be able to configure the default settings for these

**Comment by JeffersonBledsoe** [comment]
Hey @rangav, thanks for the quick response! The collections work well, but I often use the command palette to launch Thunder. Is there a way to set a collection as the default to use for thunder maybe?

**Comment by rangav** [comment]
What you meant by default collection? is it making `collection tab` active by default?

Alternatively you can `save to collection` from activity
<img width="263" alt="Screenshot 2022-10-17 at 17 30 47" src="https://user-images.githubusercontent.com/8637550/196232987-25a8171d-9b88-4d67-9d57-9375cce82617.png">

Or Create a new request from collection tab
<img width="263" alt="Screenshot 2022-10-17 at 17 30 47" src="https://user-images.githubusercontent.com/8637550/196233523-1b957785-12dc-4e0e-ba0d-cb99d1fc04d9.png">

**Comment by JeffersonBledsoe** [comment]
@rangav These work great :) This feature request is for making it possible to change the default for ALL new requests, regardless of if they are part of a collection. Here's some idea for how this could be done:

- VS Code settings for 'default headers' that is a key/ pair setting
- VS Code setting for choosing a 'default collection' so that whenever I start a request without being on a collection, it can still inherit the settings from a collection I choose. This would be optional.

**Comment by rangav** [comment]
Thanks for the feedback, will add to roadmap

**Comment by frankshrestha** [comment]
Now that we have a Default Url setting, Default Headers would be awesome. Really appreciate the work.

**Comment by willwillman-kr** [comment]
I came up with a partial temporary solve by updating the extension.js file so i could use 2 _different_ headers in there... but would be awesome to have this as more extensible and permanent feature!

**Comment by rangav** [comment]
Will add to roadmap.

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.17.0`

See all features in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.17.0

Please test and let me know your feedback.
