### ISSUE TITLE
The Ctrl U shortcut to run CURL conflicts with the very useful Ctrl U shortcut (that is the opposite of Ctrl D)

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#848]
**Describe the bug**
The Ctrl U shortcut to CURL conflicts with the handy Ctrl U shortcut (that is the opposite of Ctrl D)

**To Reproduce**
Without Thunder client, mark a text in your document and click Ctrl D to mark the next appearance of the same text - now click Ctrl U and it'll unmark the next occurrence.

With thunder client, it'll ask for a curl

**Solution:**
think of a different shortcut :)

**Comment by rangav** [comment]
Hi @noam-honig 

After git fetch or sync you can click this reload icon 

<img width="269" alt="Screenshot 2022-10-19 at 16 17 34" src="https://user-images.githubusercontent.com/8637550/196733671-72b910d2-5854-4173-a7e6-419f1c048c3c.png">

**Comment by rangav** [comment]
Hi @noam-honig thanks for the feedback.

I am sure if I change to different shortcut, it will conflict with something else. and so far others seems to be ok with this shortcut.

So I would recommend you to change the shortcut in keyboard settings, to a different shortcut that suits you.

<img width="1011" alt="Screenshot 2022-10-19 at 16 22 02" src="https://user-images.githubusercontent.com/8637550/196735069-046f2a91-3b13-41f2-9173-f7a2838bc106.png">

**Comment by noam-honig** [comment]
Hi @rangav/thunder-client-support
***@***.***> ,

Thanks for your reply. I've done as you suggested.

I think that capturing an already-used, core vs code studio editor shortcut
is less than ideal, and I was surprised to see that this shortcut didn't
work.

I'm not sure that the copy CURL command is essential enough to have a
default shortcut that works across all of vs code.

When I need it, I don't remember it's shortcut - I just type it in the
vscode command bar.

That's just my opinion :)

Thanks

**Comment by rangav** [comment]
Thanks for feedback, will remove the shortcut.
