### ISSUE TITLE
Collection doesn't refresh after git fetch/sync

### ISSUE THREAD

**Issue by angar4ik** [rangav/thunder-client-support#849]
Description: Collection doesn't refresh after git fetch/sync. The only way to resolve is to restart vs code or close open request tab.

Steps:
Start vs code. Changes on the git branch should wait. Fetch last collection from git repo.

Expected:
Collection updates according to current version automatically or by clicking refresh button (icon)

Platform:
 - OS: Windows 10
 - vscode version: 1.72.2
 - extension version: 1.20.1

**Comment by rangav** [comment]
Hi @angar4ik 

After git fetch or sync you can click this reload icon 

<img width="269" alt="Screenshot 2022-10-19 at 16 17 34" src="https://user-images.githubusercontent.com/8637550/196733671-72b910d2-5854-4173-a7e6-419f1c048c3c.png">

**Comment by angar4ik** [comment]
@rangav it was my first step. Doesn't do the job

Thanks for the product btw.

**Comment by rangav** [comment]
that wont refresh the request windows, that are already open. you need to close and re-open request windows.

**Comment by angar4ik** [comment]
Got it. So close it.
