### ISSUE TITLE
'Failed to import' error message after cancelling Collections import

### ISSUE THREAD

**Issue by lisadean** [rangav/thunder-client-support#85]
**Describe the bug**
Displays `Failed to import` error message after cancelling out of file selection prompt.

**To Reproduce**
1. Choose `import` under the Collections tab
2. Cancel out of the file selection prompt

**Expected behavior**
No error should be displayed

**Platform:** 
 - OS: Mac 10.15.7

**Solution:**

**Comment by rangav** [comment]
This is now fixed in v1.2.0, please update. 

Release details here 
https://github.com/rangav/thunder-client-support/releases/tag/1.2.0
