### ISSUE TITLE
Unable to set env variable from xml response

### ISSUE THREAD

**Issue by kasiraam** [rangav/thunder-client-support#850]
**Expected behavior**
Hi Team - First of all, Thanks for this great tool..!!

Issue:
Unable to set env variable from xml response

Steps to Reproduce:
1) For a XML response - try to "Set Env Variable" in TEST section.

Surfed for any article related to this . Unable to find any.
It would be great if we have article on it.

How similar scenario is handled in POSTMAN.
convert xml to json using xml2json and save the json response in a variable
And then use the json variable to point it to the variable we need to save
https://www.youtube.com/watch?v=UjQpUNPCvy4

Kindly let me know for any queries/ concerns.

**Platform:** 
 - Windows VS code 

**Solution:**

**Comment by rangav** [comment]
Hi @kasiraam,

- First step is to have a sample `Set Env Variable` in Tests and execute the request
- You will see the `xml to json` converted text in `output` window (see screenshot)

<img width="973" alt="Screenshot 2022-10-21 at 06 51 10" src="https://user-images.githubusercontent.com/8637550/197123314-726ef7ef-5457-4279-a689-3454f2c64ac9.png">

Now you can use actual properties from json displayed in Set Env Variable in Tests ( see screenshot below)
<img width="1488" alt="Screenshot 2022-10-21 at 06 56 38" src="https://user-images.githubusercontent.com/8637550/197123616-616fe74f-13c0-4169-b0a7-313584e51dde.png">

**Comment by rangav** [comment]
It is not the most intuitive way, will improve the workflow in the next update and also update documentation

**Comment by kasiraam** [comment]
Thanks Ranga. It worked 
By anyway I can use JSmethods on the saved data response (environment variable values) like

Last4ssn = ssn.**substring**(ssn.length-4)

**Comment by rangav** [comment]
Not possible now, in the next release we are planning to do that.

**Comment by kasiraam** [comment]
@rangav - Thanks for keeping us posted..!!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please let me know your feedback.

### Xml to Json
- For xml response you will see `Convert To Json` menu option
<img width="1333" alt="Screenshot 2022-11-17 at 11 53 11" src="https://user-images.githubusercontent.com/8637550/202439501-29f207f6-e48c-4292-9329-a75f5daff64a.png">

### Substring
- You can use substring filter `{{ssn | substring(-4)}}`
