### ISSUE TITLE
License and Pricing 

### ISSUE THREAD

**Issue by aman2k47** [rangav/thunder-client-support#856]
Is there any license version of Thunder client available . If yes what is the cost at an enterprise level . 
Also is there a way to generate reports from Thunder client to share across teams

**Comment by rangav** [comment]
We are planning to charge users in the next 3-4 weeks. Haven't decided to the pricing yet. could be $20-$30/user for enterprise customers.

You can export the report from `Run Collection` view
<img width="1196" alt="Screenshot 2022-10-28 at 14 21 31" src="https://user-images.githubusercontent.com/8637550/198606613-1c1535fa-2ece-4fe8-a7e8-431e9446a621.png">

Sharing:

- You can save the reports in git and share the link
- You can also upload the reports into your document management system like google drive etc

I like to know your thoughts / feedback about the pricing and sharing?

**Comment by msellers30** [comment]
Hi. I work for a company that is evaluating API clients and we are liking Thunder Client. Are you thinking that the $20-$30/user you mentioned above would be a yearly rate or monthly?

**Comment by rangav** [comment]
That’s per user per month for large enterprises.

if you are a medium scale business we are planning to charge around $10 dollars per month user.

As I said we haven’t finalised the pricing yet. Happy to get your feedback.

How big is your team size?

**Comment by rangav** [comment]
closing this issue, feel free to re-open if needed

**Comment by aman2k47** [comment]
> We are planning to charge users in the next 3-4 weeks. Haven't decided to the pricing yet. could be per user for enterprise customers.
> 
> You can export the report from `Run Collection` view <img alt="Screenshot 2022-10-28 at 14 21 31" width="1196" src="https://user-images.githubusercontent.com/8637550/198606613-1c1535fa-2ece-4fe8-a7e8-431e9446a621.png">
> 
> ### Sharing:
> * You can save the reports in git and share the link
> * You can also upload the reports into your document management system like google drive etc
> 
> I like to know your thoughts / feedback about the pricing and sharing?

Hi 
We could move forward once you finalise your pricing . We have a team of around (60) . There is two thing I wanted to make 
to know .
1 . Is is possible to integrated it in a pipeline ? so that the collections could automatically run on an env using the pipeline 
2 . what kind of support we could expect after Licensing . is there a community support as well ?

**Comment by rangav** [comment]
@aman2k47 if you don't mind, can you share your company name?

**Comment by aman2k47** [comment]
> @aman2k47 if you don't mind, can you share your company name?

I work in S&P Global
