### ISSUE TITLE
like postman add websocket api test

### ISSUE THREAD

**Issue by wandergis** [rangav/thunder-client-support#857]
![image](https://user-images.githubusercontent.com/5799374/199169463-5607369f-e8ef-4eb4-a228-a40d20d02c91.png)

**Comment by rangav** [comment]
Thanks @wandergis for feedback, we already have request for this #3. can you please add your feedback there.

**Comment by rangav** [comment]
This feature has been implemented and published to the marketplace. Please update to `v2.19.0`.

You can see all the features released in this update
https://github.com/rangav/thunder-client-support/releases/tag/v2.19.0

Please test it and let me know your feedback
