### ISSUE TITLE
[Critical] No Auto Reload

### ISSUE THREAD

**Issue by bombillazo** [rangav/thunder-client-support#858]
**Describe the bug**
Currently, Thunder Client does not automatically update the collections it shows in the extension GUI based on what is present in the `thunder-tests`. It seems to be caching the collections in VS Code. If the repo has any updates to the collections, one must *manually* reload the extension so that the new incoming changes are read.

This poses a potentially dangerous scenario where different users (and even the same user on different branches) using the client do not have the same latest version even when they have the same pulled branches/updates. If they forget to manually update the collections with the incoming new changes they can effectively overwrite the latest changes with their old stale collection version.

**To Reproduce**
- Make changes to thunder client collection, commit changes to a branch
- Switch branches make different changes to the thunder client collection
- Merge branches, resolve conflicts if any
- Open thunder client, do not reload, open a collection request and save it
- All changes merged into the client from the other branch are lost and the client data is reverted to the original pre-merge version

**Expected behavior**
- Any time thunder client opens, it loads the latest, current client data found in the repo
- If there are conflicts, simply notify the user which requests have conflict and let the user fix them.

**Platform:** 
 - OS: All
 - vscode version: Version: 1.72.2 (Universal)
 - extension version: v1.20.1

**Solution:**
Implement auto-reloading so Thunder Client can detect if there are changes to the collection/client files, and if so read them automatically. Or always reload when the user opens the thunder client extension (less performant, more wasteful)

**Comment by rangav** [comment]
Thanks @bombillazo for feedback, Will look into it.

**Comment by rangav** [comment]
you can manually reload until we have auto-reload option
<img width="283" alt="Screenshot 2022-11-01 at 19 34 44" src="https://user-images.githubusercontent.com/8637550/199323166-85f7091f-28a4-4e3a-92f6-c91de9407407.png">

**Comment by bombillazo** [comment]
Thanks @rangav , I'm aware of that as explained in the OP. That's how we're doing it so far but we've caught some near misses during our PR reviews.

**Comment by rangav** [comment]
@bombillazo I have finished implementing Auto Reload will be part of next update

**Comment by bombillazo** [comment]
That sounds great! Thanks

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please Test and let me know your feedback.

**Comment by bombillazo** [comment]
Thanks! Will do

**Comment by rangav** [comment]
That’s good, let us know if you find any issues In future.
