### ISSUE TITLE
Please add Console

### ISSUE THREAD

**Issue by TestUser013** [rangav/thunder-client-support#86]
**Describe the solution you'd like**
I would like to have console like in Postman app. There is a list with all requests. There is an option to collapse/expand requests and request parts (request headers, response headers, body, etc.). There is an option to define log level. Here is a screenshot from Postman:
![зображення](https://user-images.githubusercontent.com/13693660/116574199-292b2480-a916-11eb-8553-88494a94bd0f.png)

**Comment by rangav** [comment]
Hi @TestUser013 will add to roadmap

**Comment by rangav** [comment]
The logs are shown in Output window, unfortunately vscode does not have this feature
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

**Comment by m3dbedb** [comment]
to see output you have to select source
![Сниок](https://github.com/rangav/thunder-client-support/assets/25632818/8443e897-e6e4-4cf9-bf7a-373f552e833b)
