### ISSUE TITLE
Automatically refresh of auth doesn't work (anymore?)

### ISSUE THREAD

**Issue by jensklose** [rangav/thunder-client-support#863]
**Describe the bug**
I implemented an OAuth2 within a collection. 
- worked and got token
- requests within the collection were running

Time passed and the token expired.

From then on all requests failed with Status: 401 Unauthorized

**To Reproduce**
see description

**Expected behavior**
The promise that it will be renewed should be fulfilled.

**Platform:** 
 - OS: Win
 - vscode version: 1.72.2
 - extension version: 1.20.1

**Solution:**
Open. 
I worked around this with "Pre Run" but that pollutes the git repo with tokens. *Security Issue*

**Comment by rangav** [comment]
@jensklose thanks for reporting, will test and get back to you.

regarding the Pre-Run you can save tokens in local env.

**Comment by rangav** [comment]
one question did it work earlier? or it never worked before?

**Comment by jensklose** [comment]
I don't have experiences with previous versions, but I saw the same behavior on another machine.

**Comment by rangav** [comment]
I have testing now, its working.

If you manually input token, then auto-refresh will not work.
if there is any problem, please click `Generate Token` button again, the refresh should work again.

<img width="1058" alt="Screenshot 2022-11-04 at 17 27 28" src="https://user-images.githubusercontent.com/8637550/200047897-1f679449-c37c-4834-98ce-eafb3240ad68.png">

**Comment by jensklose** [comment]
Thanks! It works.
Yes of course I tested the entries for the passwords manually and tested again after a 401. I acted intuitively and that did not match the promise of the doc. ;)

**Comment by rangav** [comment]
good to know its working for you now.
