### ISSUE TITLE
Please add the ability to designate CUSTOM http request methods.

### ISSUE THREAD

**Issue by smallandsimple** [rangav/thunder-client-support#866]
**Is your feature request related to a problem? Please describe.**
In Postman and Hopscotch.io it is possible to use a custom http request method, such as SEARCH, however ThunderClient lacks this option.

**Describe the solution you'd like**
Please add in the ability to create/use custom http request methods.

**Describe alternatives you've considered**
This could be done in the dropdown where GET, POST, etc, are listed, you could add CUSTOM.
Or perhaps, you could have a config option where custom methods could be set and the user could add them in and they would show up in the dropdown.
Or you could add all of the routing methods similar to [how Express.js does it](https://expressjs.com/en/4x/api.html#routing-methods).

**Implementation:**
Up to you.

Thank you!

**Comment by rangav** [comment]
@smallandsimple Thanks for the feedback, Will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please let me know your feedback.
