### ISSUE TITLE
VS Code Insiders - Extension doesn't show up in the Action Bar

### ISSUE THREAD

**Issue by tzaffi** [rangav/thunder-client-support#868]
**Describe the bug**

**Thunder Client** is not showing up in my VS Code Insiders. Even after I disabled, re-enabled and reloaded, it's still not showing.

**To Reproduce**
Update VS Code Insider's to edition below.

**Expected behavior**

**Platform:** 
 - OS: Mac Os Ventura
 - vscode version: 1.74.0-insider
 - extension version: v1.20.1

More platform details:
```
Version: 1.74.0-insider
Commit: e764c5b816a99eb8673b2fc4fc028827f202872f
Date: 2022-11-04T05:19:54.097Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: Yes
```

**Comment by rangav** [comment]
Thanks @tzaffi for reporting.

can you please try this solution
https://github.com/rangav/thunder-client-support/issues/617#issuecomment-1188744182

**Comment by tzaffi** [comment]
Thanks @rangav. I am closing the current issue as the work around described in #617 did indeed fix the issue. Of course, if you determine that it is a separate issue, you can always re-open it.
