### ISSUE TITLE
Where collections are stored?

### ISSUE THREAD

**Issue by YakovL** [rangav/thunder-client-support#869]
Haven't found anything in docs, so I wonder if they get to some sort of cloud. Specifically, I'm trying to understand whether I have to avoid any tokens getting into a collection request. I've noticed that saving to a collection is done via some sort of request, although I haven't registered anywhere; this also makes me wonder if they work offline.

**Comment by rangav** [comment]
Hi @YakovL 

request files are stored here
https://github.com/rangav/thunder-client-support#storage

you can also save to git
https://github.com/rangav/thunder-client-support#team

You can save token to local Env
https://github.com/rangav/thunder-client-support#set-env-with-scope

let me know if you have further questions

**Comment by YakovL** [comment]
Great, thanks, this is totally clear
