### ISSUE TITLE
Cookie is not sent along with request

### ISSUE THREAD

**Issue by MasterIfeanyi** [rangav/thunder-client-support#872]
**Cookie is not sent along with request**
I have a REST API, when I log-in I get an accessToken and a cookie, but I need to pass the cookie along on refresh endpoint to get a refreshToken.

The cookie is not showing in Thunder Client.

Watching [this Youtube tutorial](https://www.youtube.com/watch?v=f2EqECiTBL8&t=18366s)

**To Reproduce**
Try to send a cookie to refresh endpoint to get a new refreshToken

**Expected behavior**
The cookie is supposed to be automatically sent along on every request to the refresh endpoint

**Platform:** 
 - OS: WIndows 10
 - vscode version: 1.73.1
 - extension version: v1.20.1 - (2022-10-19)

**Comment by MasterIfeanyi** [comment]
I get this error `Set Env Failed: Unable to parse left input query - cookie.jwt` after following [the docs](https://github.com/rangav/thunder-client-support#setenv)

**Comment by rangav** [comment]
@MasterIfeanyi 

Can you share your response cookie tab screenshot

**Comment by MasterIfeanyi** [comment]
![Screenshot 2022-11-11 141123](https://user-images.githubusercontent.com/48832130/201347479-e5e800f0-3fb8-4df0-b47d-9fd041fc03f7.png)

**Comment by MasterIfeanyi** [comment]
Please, look at this [question](https://stackoverflow.com/questions/74402197/cookie-in-thunder-client-vs-code-extension)

**Comment by rangav** [comment]
Can you share `cookie` tab screenshot not Result tab

**Comment by MasterIfeanyi** [comment]
![Screenshot 2022-11-11 142058](https://user-images.githubusercontent.com/48832130/201348928-c7fab032-22fd-433f-8475-a94be14f64fd.png)

Here you go, please look at my [question](https://stackoverflow.com/questions/74402197/cookie-in-thunder-client-vs-code-extension)

**Comment by rangav** [comment]
your request does not return any cookies? so you cannot save the cookie.

if you want to manually create cookie and add to request, follow below
https://github.com/rangav/thunder-client-support#cookies

**Comment by rangav** [comment]
@MasterIfeanyi you are doing it wrong, you need to use `Set Env Variable` in `login` request not refresh refresh

Use this in login request
![201328902-f1b1e01f-30da-4938-95ac-087f0280ab75](https://user-images.githubusercontent.com/8637550/201355660-caf83e75-285e-4f7f-a905-14037383cacc.png)

**Comment by MasterIfeanyi** [comment]
@rangav  I just want to send the cookie to the `/refresh` endpoint to get a new `refreshToken`. 

The cookie should be sent along every time just like a browser does automatically.

I have tried your solution, it failed. Please, help me.

**Comment by rangav** [comment]
can you share your login request `cookies` tab and `Tests` tab screenshots

**Comment by MasterIfeanyi** [comment]
This is my **login request cookies tab**

![login-cookies](https://user-images.githubusercontent.com/48832130/201360962-44aac33a-84d0-459f-8480-5f58cef1eb89.png)

This is my **login request Tests tab**

![login-tests](https://user-images.githubusercontent.com/48832130/201361122-9e298692-dc9f-490c-bf49-329ac38eca6b.png)

**Comment by rangav** [comment]
thanks

- how you need to send `cookie` to `refresh` request?
- how you need to send `token` to `refresh` request?

**Comment by MasterIfeanyi** [comment]
I will send `cookies` to the `refresh` endpoint using the `req.cookies` header.

**Comment by rangav** [comment]
> 

the cookie is automatically sent to next request if they both belong to same domain, you don't have to do anything. 

Do you need to send login `token` as well to `refresh` request?

**Comment by MasterIfeanyi** [comment]
> > 
> 
> the cookie is automatically sent to next request if they both belong to same domain, you don't have to do anything.
> 
> Do you need to send login `token` as well to `refresh` request?

I know the cookie is automatically sent to next request if they both belong to the same domain. 

But, I keep get an error `UnAuthorized` or `Forbidden`.

I don't know why, I have increased the time of expiration for the `cookies` and `token`.

**Comment by rangav** [comment]
i think you need to send `access token` (got from login request) to `refresh` endpoint

**Comment by MasterIfeanyi** [comment]
No, I do not have to send `access Token` (got from login request) to the `refresh` endpoint.

According to video instructor.

**Comment by rangav** [comment]
ok I saw the video, are you running the same code?

**Comment by MasterIfeanyi** [comment]
Yes, I am. Every time, I hit the `refresh` endpoint I get 

```javascript

401 unAuthorized

```

**Comment by rangav** [comment]
I dont know the reason, should be something in your code.

Put a break point in refresh end point and debug.

**Comment by rangav** [comment]
> Maybe have a look at this [issue](https://github.com/postmanlabs/postman-app-support/issues/8057#issuecomment-1264687321)

but the instructor video was able to sent cookies in localhost in Thunder Client

**Comment by rangav** [comment]
I am closing this issue, feel free re-open if needed

**Comment by MasterIfeanyi** [comment]
Hey rangav. 

I solved the error. If you are working with Node.js on your backend server.

When creating your cookie, you should add the option `secure: false` this makes the cookie accessible to the client (browser) on the frontend.

`res.cookie("jwt", refreshToken, {httpOnly: true, secure: false, maxAge: 24*60*60*1000})`

>Thunder client extension in VS code does not recognise localhost development server urls as protected routes (https or http secure) (for example http://localhost:3500/refresh and http://localhost:3500/auth), hence it will not make the token available for requests. So the only option is to set the secure option to "false" to allow it to pass.

To learn more: https://stackoverflow.com/questions/74402197/cookie-in-thunder-client-vs-code-extension

**Comment by rangav** [comment]
Thanks for sharing solution, will be useful for users
