### ISSUE TITLE
File Form Checkbox disappear (UI)

### ISSUE THREAD

**Issue by reisman234** [rangav/thunder-client-support#875]
**Describe the bug**
File Checkbox for Forms is not visible when the request editor is too narrow and the response view goes underneath.

**Visible**
![image](https://user-images.githubusercontent.com/44891585/201894128-ff603fc9-ca1c-433a-9fd3-adb92c7cb68a.png)

**HIDDEN**
![image](https://user-images.githubusercontent.com/44891585/201894544-80554dd8-bdd9-4ff5-92e4-fc6b4b5ee4dc.png)

**Expected behavior**
checkbox should be visible

**Platform:** 
 - OS: Linux Mint
 - vscode version: 1.68.0
 - extension version: v1.20.1

**Solution:**
Remove that checkbox and let there be a first default unselected file form input, similar to field-name-values

**Comment by rangav** [comment]
This Bug is fixed is now and published to marketplace, please update to `v2.0.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.0

Please let me know your feedback.
