### ISSUE TITLE
Environment Variables and Proxy with password fails - connect EACCES ip-of-our.proxy:8080

### ISSUE THREAD

**Issue by surfmuggle** [rangav/thunder-client-support#879]
Recently i made some changes on the windows proxy settings and upgraded to VSCode 1.71.2 and also upgraded to thunder client v1.20.1 - (2022-10-19).

If i try to call  `GET https://www.thunderclient.com/t/echo` i get this error

```
connect EACCES 1.. our ip .. :ourPort
```

![Thunder_Connect_fails](https://user-images.githubusercontent.com/1271555/202222767-66405a6c-4f2a-4216-a0ef-1ddc4a21576a.png)

To my understanding VS Code is able to read proxy settings from the environment variables. But [for extensions](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support) this is likely not the case (see [Legacy proxy server support](https://code.visualstudio.com/docs/setup/network#_legacy-proxy-server-support)). 

To my understanding of [specify password for proxy in code](https://stackoverflow.com/questions/37730040/how-to-specify-a-user-id-and-password-for-visual-studio-code-with-an-authenticat) the visual studio code settings.file `%appdata%\Code\User\setting.json` must have this entry

    "https.proxy": "https://internal-proxy.corp.net:8080",
    "http.proxyStrictSSL": false ,  
    "http.proxyAuthorization": "Authorization: Basic RE9NQUlOXHVzZXI6cGFzcw=="

I added the lines above with `our proxy` and my `<username>:<password>` as a base-64 encoded string. But i still get the same error. 

### Questions

- What do i have to do to connect to the internet via a proxy that requires authentification?
- Are there other setting files i may have to edit?
- How does thunder-client connect to the internet?
- Where can i find a log with more details why the connection failed?

### Visual Code Version Details

```
Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
```

**Comment by rangav** [comment]
@surfmuggle

proxy format should be - `http://username:password@host:port`

see docs here
https://github.com/rangav/thunder-client-support#proxy

**Comment by surfmuggle** [comment]
I changed `%appdata%\Code\User\setting.json` to include these settings for http.proxy*

```
    "http.proxy" : "http://<myuser>:<myp@ssword>@111.11.11.1:8080",     
    "http.proxyStrictSSL": false ,  

```    
This did not change anything. The `@` in `<myp@ssword>` is an actual character in my password.

**Comment by surfmuggle** [comment]
The cause is likely that our admins added a firwall roule for the new visual studio code version that block all outgoing requests.
