### ISSUE TITLE
Large numbers are truncated

### ISSUE THREAD

**Issue by BenSegal855** [rangav/thunder-client-support#88]
**Describe the bug**

Large numbers sent as a response are truncated. Below is a section of a response from hitting the same API endpoint with the same payload in both Thunder Client and Postman. As you can see, the last three digits are lost in the result displayed by the Thunder Client and the forth lest significate digit is rounded up.

Thunder
![image](https://user-images.githubusercontent.com/34194692/116611717-b06f9c80-a904-11eb-91e1-2e24f027457b.png)

Postman
![image](https://user-images.githubusercontent.com/34194692/116611648-9df56300-a904-11eb-890a-8e95cbc02771.png)

**To Reproduce**

Use the Thunder Client to make a post request to https://echo.amy.gg/ with the following payload
```json
{ "number": 6395775853609427517 }
```
Observe how the response truncates the number.
Repeat the process in Postman and observe the correct number in the response.

**Expected behavior**

Large number should be displayed properly. 

**Platform:** 
 - OS: Windows

**Solution:**

Id guess this occurs because the number is larger than the max safe integer. If this is the case, BigInts are probably a solution.

**Comment by rangav** [comment]
Hi @BenSegal855 i will verify and fix it asap.

**Comment by nicksama88** [comment]
I just ran into this long number truncation issue today, caused a good deal of confusion on my part for a bit.

**Comment by Paritoshyadav** [comment]
![client response](https://user-images.githubusercontent.com/20665510/152400980-ca670948-2edc-4c3d-9da0-87f0b98ea755.PNG)
![actuall response](https://user-images.githubusercontent.com/20665510/152401007-b55f5675-9292-4b15-af24-70c3be448b22.PNG)

**Comment by rangav** [comment]
Hi All, default JSON can’t handle large numbers, have to find a separate library to handle this.

 If possible will fix this in the next update

**Comment by rangav** [comment]
Hi all, This issue is now fixed, will be part of next update v1.12.0

**Comment by rangav** [comment]
This bug is now fixed in v1.12.0

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.12.0

please let me know if any feedback
