### ISSUE TITLE
How to run by shortcut key or from menu?

### ISSUE THREAD

**Issue by ducwp** [rangav/thunder-client-support#882]
P/S: I hidden the action bar

**Comment by ducwp** [comment]
Usage: 
Install the Extension, Click Thunder Client icon on the Action Bar

--> I have hidden the action bar, how do I run it?

**Comment by rangav** [comment]
the shortcut is `Ctrl/Cmd +Shft + r`, if you mouse hover on the icon it will also show you the shortcut key

**Comment by rangav** [comment]
From the command palette also you select `Show Thunder Client`
<img width="647" alt="Screenshot 2022-11-17 at 14 23 58" src="https://user-images.githubusercontent.com/8637550/202471848-41a14707-39db-401e-b597-f0ba9e3e4957.png">
