### ISSUE TITLE
Using Correclty Custom Script

### ISSUE THREAD

**Issue by mauriliofilho** [rangav/thunder-client-support#883]
Hello, i have try using new function of Custom script, but i`m not uderstand bether how to this work, you help please!

**Comment by rangav** [comment]
1. First you need to create js file, see sample here https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js
2. Attach that file to Collection using Collection Settings
3. Use the filter name in env variable {{variable | customFilter}}


Which part is not clear?

**Comment by rangav** [comment]
fyi - The `tc` object types file [tc-types.d.ts](https://github.com/rangav/thunder-client-support/blob/master/docs/tc-types.d.ts)

**Comment by mauriliofilho** [comment]
> 1. First you need to create js file, see sample here https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js
> 2. Attach that file to Collection using Collection Settings
> 3. Use the filter name in env variable {{variable | customFilter}}
> 
> Which part is not clear?

Yes this parts is clear, but i`m not see result of js file with funcion i create!
Ex: i can use this function of custom script in Body request?

**Comment by mauriliofilho** [comment]
> fyi - The `tc` object types file [tc-types.d.ts](https://github.com/rangav/thunder-client-support/blob/master/docs/tc-types.d.ts)

This files need put together with all script i create?

**Comment by rangav** [comment]
No you dont need to combine them, the types file is only for reference.

You can also use filters in body, will share an example in a minute

**Comment by rangav** [comment]
you can use the sample script file and the sample url - https://httpbin.org/anything

<img width="1589" alt="Screenshot 2022-11-17 at 20 59 24" src="https://user-images.githubusercontent.com/8637550/202558848-0730495b-4a57-4732-b60f-05b08cd6abe3.png">

**Comment by mauriliofilho** [comment]
I can use variables of to pass in params to custom script?

**Comment by mauriliofilho** [comment]
> * syntax highlighting did not work for custom filters in body, will fix in next update.

OK

**Comment by rangav** [comment]
you can use the filters anywhere in the request.

**Comment by mauriliofilho** [comment]
Ok, i can't using my script i create, an can't using this sample in site, i try reproduce this with tab test to sabe one value of appedString but sabe value with erro.

**Comment by rangav** [comment]
can you share screenshots?

**Comment by mauriliofilho** [comment]
I Will send, github is can't upload images here!

**Comment by rangav** [comment]
You can use this sample https://httpbin.org/anything and use sample custom filters for testing. 
and you can share these screenshots if possible. So I can reproduce the the issue

**Comment by mauriliofilho** [comment]
![image](https://user-images.githubusercontent.com/1377303/203467023-d06d057f-b5ad-4b86-a9bd-9ac6bef00969.png)

**Comment by mauriliofilho** [comment]
I can`t using script same as sample, not function here for me.

**Comment by rangav** [comment]
`hello` Env variable is created in environment?

**Comment by mauriliofilho** [comment]
> `hello` Env variable is created in environment?

No.
This value is where store the value of result of scritos?

**Comment by rangav** [comment]
No it will not save, You need to create the variable first.

The modified value is not stored to variable, it will be dynamically replaced in request.

I will add a new function for `tc` object to save env variable .e.g: `tc.setVar(name, value)` in next update later this week.

**Comment by mauriliofilho** [comment]
> No it will not save, You need to create the variable first.
> 
> The modified value is not stored to variable, it will be dynamically replaced in request.
> 
> I will add a new function for `tc` object to save env variable .e.g: `tc.setVar(name, value)` in next update later this week.

Work now parcialy, i receive value of constant in my js file, but not append the value i have send in parameter. You

**Comment by rangav** [comment]
https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js

https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by rangav** [comment]
can you share screenshot?

**Comment by mauriliofilho** [comment]
I check that and see, i create var hello in global variable, but with value empty, when i add vallue of that, this represent, o param input of function appendString, and value i pass togather appendScrit is param1.

I modify the script of sample skiping of code of value the param1 in function, by this not function!
I have general idea of how to function the scrits e i used with my own script and see results!
Thanks for the time being.

**Comment by mauriliofilho** [comment]
I Guess to problem i have is in my enviorment, I reproduce the same values in my personal machine e the value is work correcly, with my own custom script, but in my machine of enterprise not work, seems of script is not working.
