### ISSUE TITLE
Export postman format lacks description field

### ISSUE THREAD

**Issue by SpiffGreen** [rangav/thunder-client-support#884]
**Is your feature request related to a problem? Please describe.**
Yes, it's related to a problem. I discovered after exporting a collection in postman format, the documentation wasn't exported too.

**Describe the solution you'd like**
Add a describe field to the postman info with the set documentation for each collection item.

**Describe alternatives you've considered**
Haven't considered any alternatives

**Implementation:**
See [Postman Schema Documentation](https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html)

**Comment by SpiffGreen** [comment]
I'd love to work it though

**Comment by rangav** [comment]
Hi @SpiffGreen We don't have description field, that's why it's not in exported file.

**Comment by SpiffGreen** [comment]
Hi, thanks for the fast reply. I am actually referring to the documentation. It can be found when viewing the settings page of a collection.

**Comment by rangav** [comment]
Sorry now I got it. Will update in the next release

**Comment by SpiffGreen** [comment]
Thanks, I'm looking forward to it.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.1

Please let me know your feedback.
