### ISSUE TITLE
eating ram

### ISSUE THREAD

**Issue by tsivickas** [rangav/thunder-client-support#887]
Type: <b>Bug</b>

node process growing cpu and ram till it eats all possible ram, and then crash server.  Ram is 16GB

Extension version: 2.0.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Connection to 'ssh-remote+(hidden).dedikuoti.lt' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  J3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.67GB free)|
|Process Argv|--crash-reporter-id 18df8350-3293-4dc1-9031-038f36b263cf|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+mpff.c.dedikuoti.lt' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by rangav** [comment]
@tsivickas thanks for reporting

can you let me know how to reproduce this?

**Comment by rangav** [comment]
Can you also test by installing previous version and see you are facing same issue?

**Comment by rangav** [comment]
Closing this issue, as steps to re-produce the bug is not provided.

feel free to re-open if needed.
