### ISSUE TITLE
CURSOR ISSUE IN THE REQ BODY JSON FORMAT

### ISSUE THREAD

**Issue by ashwin-seshadree** [rangav/thunder-client-support#888]
[Screencast from 21-11-22 01:19:31 PM IST.webm](https://user-images.githubusercontent.com/108737954/202994375-a977dc95-fb89-483f-8c38-679ba8ce3060.webm)

**Describe the bug**
While inserting the request body as JSON content, the cursor is visible at one place and actual cursor (which is invisible) is before the visible cursor.

**To Reproduce**
Please check the video that I have uploaded along 

**Expected behavior**
The cursor should be the place where the letter input starts 

**Platform:** 
 - OS: UBUNTU
 - vscode version:
 - extension version:
VSCode Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic
Sandboxed: No

**Solution:**

**Comment by rangav** [comment]
Hi @ashwin-seshadree thanks for reporting the issue 

did you change any font settings in vscode?

**Comment by ashwin-seshadree** [comment]
Hi Team,

Thanks for the quick reply. I have not changed any settings in vscode. Not that I am aware of.

Regards,
Ashwin S

Kind Regards,

Ashwin Seshadreeswaran
Full Stack Developer - Development
+91 977 806 8690 / +91 989 554 7190

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rangav** [comment]
Can you share your `Editor - font family` setting value

<img width="535" alt="Screenshot 2022-11-21 at 10 07 25" src="https://user-images.githubusercontent.com/8637550/203023743-53383e35-8987-4e62-8de3-365a6d5526db.png">

**Comment by rangav** [comment]
Looks like you have correct settings. 

similar issue here
https://github.com/rangav/thunder-client-support/issues/450

Did it work in previous version of the extension?

**Comment by ashwin-seshadree** [comment]
> Looks like you have correct settings.
> 
> similar issue here #450
> 
> Did it work in previous version of the extension?

Yes It worked previously fine. Suddenly this issue came.

**Comment by rangav** [comment]
may be uninstall the extension and re-install it.

or try installing previous version.

**Comment by rangav** [comment]
Don't know what is the fix for this yet. will look into it.

**Comment by ashwin-seshadree** [comment]
sure thanks. And thank you for the wonderful extension. Makes my work more easier and fast. All the best

**Comment by rangav** [comment]
thanks for sharing.

can toy try this value in font family in settings
`'Ubuntu Mono Regular', 'Droid Sans Mono', 'monospace', 'Droid Sans Fallback'`

you can play around with above values and see if its fixed

**Comment by ashwin-seshadree** [comment]
Yes this did work fine. So i guess the font which I used wasn't supporting. This one is working good 

[Screencast from 21-11-22 05:48:29 PM IST.webm](https://user-images.githubusercontent.com/108737954/203053019-82f95fd1-6a0e-4c27-b521-fa9fd834e93e.webm)

**Comment by rangav** [comment]
super. glad it's working for you now.

**Comment by rangav** [comment]
Note - if you sync this setting to another pc or mac, then you may encounter similar issue. 

I am closing this issue, feel free to re-open if needed

**Comment by ashwin-seshadree** [comment]
sure, will keep it in mind. Thanks for the prompt reply and fix. Glad
