### ISSUE TITLE
Possibility to store 'runtime' generated variables

### ISSUE THREAD

**Issue by m00dsw1ng** [rangav/thunder-client-support#891]
Hi,

I'm currently starting to use Thunderclient instead of Postman, like it!

Have a question though, In our current Postman tests we use an endpoint to generate an account. The body is a payload with username, firstname, lastname. The username is randomly generated in the Postman pre-request script of the test and assigned to a collection variable. This is done so we can use this generated username in the tests to follow.

Is it correct to say that currently this is not possible via ThunderClient?

Thanks You

**Comment by rangav** [comment]
Hi @m00dsw1ng, you can use custom filters to generate random username and use in the request.

https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md

Currently you cannot save to generated random username to a variable. but will in the next update later this week.

**Comment by m00dsw1ng** [comment]
Hi rangav,

Random generator works perfectly thanks.

Looking forward to the update thank you very much

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.1

See example here to `setVar` from scripts
https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js

Please let me know your feedback.

**Comment by m00dsw1ng** [comment]
Hi rangav,

Thank you. I've created a custom-script.js file which I've attached to my Collection Settings.

I'm trying to invoke that in the body of a request like below:
`{
    "username": {{createRandomUsername}},
    "firstName": "firstName",
    "lastName": "lastName"
}`

But I guess that's not possible that way?

Thank You

**Comment by m00dsw1ng** [comment]
Sorry, I've managed to do it.

I forgot to export the module / function in my custom-script.js and I can invoke it in the Header of a request to use it as a pre-request right?

**Comment by rangav** [comment]
yes thats right, you can use it in headers/body as pre-request
