### ISSUE TITLE
Add Accept header to OAuth token request

### ISSUE THREAD

**Issue by macarpen** [rangav/thunder-client-support#892]
**Is your feature request related to a problem? Please describe.**

The default token response for the GitHub OAuth implementation is formatted as `application/x-www-form-urlencoded`, whereas Thunder Client is expecting an `application/json` response. This causes an error while parsing the response:
> Error: Unexpected token a in JSON at position 0

https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#response
https://darutk.medium.com/spec-violations-in-github-oauth-implementation-and-security-considerations-48a7f8dfa335

**Describe the solution you'd like**

By explicitly setting the `Accept` header to `application/json` in the token request GitHub will return the expected format. This could be done unconditionally or as an advanced option.

**Describe alternatives you've considered**

Convince GitHub to change the default response format to be compliant with the spec.

**Implementation:**

Add `Accept: application/json` header to OAuth token request.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.0.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.0.1

Please let me know your feedback.

**Comment by macarpen** [comment]
I've confirmed that GitHub OAuth is now working with `v2.0.1`, thanks @rangav !

**Comment by rangav** [comment]
Thanks @macarpen for confirmation 👍
