### ISSUE TITLE
Change location and folder name for thunder-client configuration

### ISSUE THREAD

**Issue by jeandat** [rangav/thunder-client-support#896]
I have seen [this section](https://github.com/rangav/thunder-client-support#git-sync) in the doc but I can't make it work.

I want to save all my work in the extension in a folder inside the project so I can share it with my colleagues. I checked `Save to workspace` for the project in vscode settings. No folder is created. 

I also renamed it by configuring `Custom Location` as ".thunder".

Whenever I create a new request, nothing is saved on file. 
What am I missing?

**Comment by rangav** [comment]
Remove `custom location` value

And start creating requests and the necessary folders and files will be created automatically

**Comment by jeandat** [comment]
So you can't choose the folder name, right?

**Comment by jeandat** [comment]
Also it works if I change my workspace settings. But not with my project settings.

**Comment by rangav** [comment]
You can’t change folder name but you can change path by using `Workspace Relative Path` setting
