### ISSUE TITLE
Allow define env variables with other env variables.

### ISSUE THREAD

**Issue by ejmarino** [rangav/thunder-client-support#897]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to define a environment variable with another environment variable inside.
For example: 
realm = "myRealm"
backend-url = "/realms/{{realm}}/protocol-openidc/token"

**Describe alternatives you've considered**
I thought using replace filter as an alternative like:
realm = "myRealm"
backend-url = "/realms/#realm##/protocol-openidc/token"
and then use {{backend-url | replace("#realm#","{{realm}}"}} in the url of the request.
BUT filters are not evaluated on the url field. 😞

Thanks!

**Comment by rangav** [comment]
Hi @ejmarino 

`/realms/{{realm}}/protocol-openidc/token` 

this should work, did you run and test it?

**Comment by ejmarino** [comment]
if I define `backend-url = /realms/{{realm}}/protocol-openidc/token`
and set {{backend-url}} in the url field (or in Token Url field inside OAUTH2 tab). It doesn`t resolve the internal variable {{realm}}.

**Comment by ejmarino** [comment]
Your solution works and I use it as a workaround, But this url may change per environment and that's because I wanted it as a variable.

**Comment by rangav** [comment]
You can define this variable in Global Env `backend-url` = `"/realms/{{realm}}/protocol-openidc/token"`

**Env A**
Create variable `realm = valueA`

**Env B**
Create variable `realm = valueB`

Now when you switch set `EnvA` as active, then `realm` value will be `valueA`

Now when you switch set `EnvB` as active, then `realm` value will be `valueB`

Hope its clear

**Comment by ejmarino** [comment]
Hey thanks! Declaring `backend-url ` it in the **Global Env** did the trick I think. It worked! Thanks!
