### ISSUE TITLE
Lack of feedback around undefined custom filters 

### ISSUE THREAD

**Issue by shawnferry** [rangav/thunder-client-support#899]
Invalid or ineffectual custom filters do not indicate any problems during invocation.

* Write a custom filter and forget to export it (or typo your invocation)
* Define a filter invocation like `text | nonExistentFilter`
* Send Request 
* *expect some sort of output or error*

**Describe the solution you'd like**

Attempts to invoke filters that do not exist should not silently fail.
* Test results could/should show errors
* Output window should show an error

Possibly like 
`Error in Custom Script: function is not defined - (nonExistentFilter)`

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.1.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.1.0

Please let me know your feedback.
