### ISSUE TITLE
Customizable location for settings file

### ISSUE THREAD

**Issue by JamesWatling** [rangav/thunder-client-support#9]
**Is your feature request related to a problem? Please describe.**
Would be great to either list the location the settings are saved, so that we can share with others easily

**Describe the solution you'd like**
If the collections were saved to a specific file, and updated on any changes so we can share it with others without having to export manually. If you could also customise the location for any collection so you can sync to dropbox, add to a git repo or something would be great

**Comment by rangav** [comment]
This feature is already suggested in #2 by @pikant, So I will close this.
