### ISSUE TITLE
Action do not operate as expected when response is an JSON array

### ISSUE THREAD

**Issue by Pascal62223** [rangav/thunder-client-support#90]
**Describe the bug**
GET request returning an array of object as response.
Use the 'Tests'  tab, to filter the response content based on a property value.
Filtering selection do not apply to the entire array being returned.

Details of the issue has been discussed before and detail can be found in below reference link.

Reference : https://github.com/rangav/thunder-client-support/issues/14#issuecomment-829823658 

**To Reproduce**

1.  Need a GET API request that returns an array of json objects such as : 
![image](https://user-images.githubusercontent.com/77442348/116653014-ef5f2a00-a9b8-11eb-9b84-292535cc9558.png)

2.  Create a 'Tests' to return only the array records where property 'XyZ' value is equals to 'value'

     below syntax (in the tab 'Tests' have been used without success : 
     json.XyZ equals  value     ---> Result empty
     json[0].XyZ equals value  ---> Criteria is applied only to the first record
     json[].XyZ equals value  ---> Error : Query: json[].uuid contains c93fbd6e => Actual: Error parsing json query

**Expected behavior**
The response will only contains teh records where property 'XyZ' is equals to 'value'

**Platform:** 
 - OS:  Windows
 - Application : VS Code

**Solution:**

**Comment by rangav** [comment]
Thanks @Pascal62223 i will get back to you on this.

**Comment by dancaires** [comment]
> **Describe the bug**
> GET request returning an array of object as response.
> Use the 'Tests' tab, to filter the response content based on a property value.
> Filtering selection do not apply to the entire array being returned.
> 
> Details of the issue has been discussed before and detail can be found in below reference link.
> 
> Reference : [#14 (comment)](https://github.com/rangav/thunder-client-support/issues/14#issuecomment-829823658)
> 
> **To Reproduce**
> 
> 1. Need a GET API request that returns an array of json objects such as :
>    ![image](https://user-images.githubusercontent.com/77442348/116653014-ef5f2a00-a9b8-11eb-9b84-292535cc9558.png)
> 2. Create a 'Tests' to return only the array records where property 'XyZ' value is equals to 'value'
>    below syntax (in the tab 'Tests' have been used without success :
>    json.XyZ equals  value     ---> Result empty
>    json[0].XyZ equals value  ---> Criteria is applied only to the first record
>    json[].XyZ equals value  ---> Error : Query: json[].uuid contains c93fbd6e => Actual: Error parsing json query
> 
> **Expected behavior**
> The response will only contains teh records where property 'XyZ' is equals to 'value'
> 
> **Platform:**
> 
> * OS:  Windows
> * Application : VS Code
> 
> **Solution:**

Hi @rangav, first of all, congrats for your nice job!!

I have this same issue pointed by @Pascal62223

**Comment by rangav** [comment]
Thanks @dancaires - I am verifying the issue now.

**Comment by rangav** [comment]
Hi @Pascal62223 and @dancaires , its working for me

I just tested with array json response from https://www.thunderclient.io/array

```json
[
{
"id": "56de66ec-c1ea-439a-a10a-3bddbef9e5a8",
"message": "Welcome to Thunder Client",
"about": "Thunder Client is a hand-crafted lightweight Rest API Client extension for VS Code.",
"createdBy": "Ranga Vadhineni",
"github": "github.com/rangav/thunder-client-support",
"twitter": "twitter.com/thunder_client",
"auth": "Supported Authentication methods Basic Auth, Bearer Token & OAuth 2.0",
"graphql": "The client supports Graphql Query & Variables",
"testing": "Welcome url can be used for testing json or xml format, for xml response send Accept header with application/xml",
"support": "For Bugs & Feature requests please submit on github",
"share": "Please spread the word about Thunder Client"
},
{
"id": "d0933646-5013-487f-9e84-f3f30f4ab1a3",
"message": "Welcome to Thunder Client",
"about": "Thunder Client is a hand-crafted lightweight Rest API Client extension for VS Code.",
"createdBy": "Ranga Vadhineni",
"github": "github.com/rangav/thunder-client-support",
"twitter": "twitter.com/thunder_client",
"auth": "Supported Authentication methods Basic Auth, Bearer Token & OAuth 2.0",
"graphql": "The client supports Graphql Query & Variables",
"testing": "Welcome url can be used for testing json or xml format, for xml response send Accept header with application/xml",
"support": "For Bugs & Feature requests please submit on github",
"share": "Please spread the word about Thunder Client"
},
{
"id": "7f47a439-263a-4703-83d4-4566f5a817bf",
"message": "Welcome to Thunder Client",
"about": "Thunder Client is a hand-crafted lightweight Rest API Client extension for VS Code.",
"createdBy": "Ranga Vadhineni",
"github": "github.com/rangav/thunder-client-support",
"twitter": "twitter.com/thunder_client",
"auth": "Supported Authentication methods Basic Auth, Bearer Token & OAuth 2.0",
"graphql": "The client supports Graphql Query & Variables",
"testing": "Welcome url can be used for testing json or xml format, for xml response send Accept header with application/xml",
"support": "For Bugs & Feature requests please submit on github",
"share": "Please spread the word about Thunder Client"
}
]
```


Please see the test screenshot
![image](https://user-images.githubusercontent.com/8637550/116801900-1a0ac900-ab06-11eb-8b33-8ad512242b4f.png)

**Comment by Pascal62223** [comment]
@rangav 
I think it might be due to miss-understanding.
For me, the criteria specified in the Tests tab is about the filtering conditions to be applied.  The response woudl only include teh records that match the specified condition.

However, that is not what 'Tests' is about. This is a wrong understanding from my side.
'Tests' conditions are used like integration tests, to verify that the response content match the test criteria. If all tests are 'pass' this do indicate the response match teh expected results.

Please close that defect entry.  It's clear for me now where the issue was ... in my brain :-D
