### ISSUE TITLE
Cannot delete environments and collections

### ISSUE THREAD

**Issue by xilopaint** [rangav/thunder-client-support#901]
**Describe the bug**
Cannot delete environments and collections. The only way to get them deleted is by deleting the json file in the storage location.

**To Reproduce**
Right-click on the environment/collection and select delete in the contextual menu.

**Expected behavior**
Environment/collection being deleted.

**Platform:** 
 - OS: macoS 13.0.1
 - vscode version: 1.73.1
 - extension version: 2.0.2

**Comment by rangav** [comment]
Hi @xilopaint thanks for reporting the problem. 

Did it happed in previous version? 
Are you noticing this first time?

**Comment by xilopaint** [comment]
I haven't used the extension for a while but I don't remember to face the issue before. I got a new Mac recently btw and it has ARM architecture but I don't know if it's relevant for the issue.

**Comment by rangav** [comment]
this could be vscode issue.

try the below

- Restart vscode and try delete again.
- Try installing previous version of extension, see if that works
- Next try installing previous version of VSCode and see if that works.

**Comment by xilopaint** [comment]
Restarting vscode doesn't work. How do I install a previous version of the extension and what version do you recommend me to install?

**Comment by rangav** [comment]
Go to extensions tab, search for thunder client. then see below image, try any previous version
<img width="294" alt="Screenshot 2022-11-30 at 12 47 07" src="https://user-images.githubusercontent.com/8637550/204800279-5a23ff21-4876-4224-a2f0-107af828f0f3.png">

**Comment by rangav** [comment]
One more question 

Are you able to delete request?

**Comment by xilopaint** [comment]
> Are you able to delete request?

Yes.

**Comment by rangav** [comment]
When deleting collection, the extension will ask for prompt: `Do you want to delete collection?`

May the issue is with vscode prompt api.

will provide an new vscode setting like `Delete Without Prompt` might address this issue as an alternative solution

**Comment by xilopaint** [comment]
> will provide an new vscode setting like `Delete Without Prompt` might address this issue as an alternative solution

Can we expect a quick release with this feature?

**Comment by rangav** [comment]
Sure I can do a pre-release version now to fix this or do a release version later today? let me know which one you prefer?

**Comment by xilopaint** [comment]
> Sure I can do a pre-release version now to fix this or do a release version later today? let me know which one you prefer?

Well, I'm facing another problem.

I'm trying to use [this Postman collection](https://github.com/binance/binance-api-postman). It works good in Postman but in Thunder Client I get this response for a request:

```json
{
  "code": -1105,
  "msg": "Parameter 'signature' was empty."
}
```

The signature parameter is an environment variable. In Postman we can leave it empty as well as the timestamp variable and they are filled in automatically (you just need to fill your API key and secret), but the same doesn't seem to work in Thunder Client.

I didn't create a new issue because I'm not sure if I'm missing something.

**Comment by rangav** [comment]
Yeah, please create a new issue for this

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.1.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.1.0

Please let me know your feedback.

<img width="997" alt="Screenshot 2022-12-05 at 05 54 30" src="https://user-images.githubusercontent.com/8637550/205559721-0ef46220-1bdb-4b82-9856-7ed21d05319d.png">

**Comment by xilopaint** [comment]
> Please let me know your feedback.

It works as expected. Thanks!

**Comment by rangav** [comment]
Thanks for confirmation 👍
