### ISSUE TITLE
How to import Node module in custom filters?

### ISSUE THREAD

**Issue by LesterLian** [rangav/thunder-client-support#903]
The new filter feature is exciting. It's essential for many API tasks such as authentication flows. Thank you!

My question is:
What is the best way to import Node or CommonJS module in custom filter? The example imports some node modules, which seem to be dependencies of Thunder Client. Is it the only place Thunder Client loads modules from? I notice that importing Node's built-in module process `require('process')` also returns `undefined`.

I have also tried to dynamically import the module from a single bundle file. It returns **Dynamic Import not supported**.

Can you please suggest a way to import Node module?

**Comment by rangav** [comment]
@LesterLian The execution happens in sandbox environment, not all features of node are enabled.

What module are you tying to use?

**Comment by rangav** [comment]
I am using this node library for sandbox execution
https://github.com/patriksimek/vm2

Let me know if there is any additional features that can be enabled.

**Comment by LesterLian** [comment]
> @LesterLian The execution happens in sandbox environment, not all features of node are enabled.
> 
> What module are you tying to use?
> 
> I am also trying get feedback to improve this feature and also understand all the use-cases.

Thank you! It's good to know you will keep improving it!

I'm trying to use Forge [(node-forge)](https://github.com/digitalbazaar/forge) in my filter because one of the authentication API uses RSAES-PKCS1-V1_5.

If full Node functionality is a problem, can you maybe enable dynamical import ability in the future? Otherwise, I can see only one workaround which is to build single bundle file for each filter with its dependency embedded.

**Comment by rangav** [comment]
Thanks for sharing the node module name

Will research and see if it's possible to integrate external node modules.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.1.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.1.0

Please let me know your feedback.
