### ISSUE TITLE
Collection and request names variables

### ISSUE THREAD

**Issue by cezaryece** [rangav/thunder-client-support#904]
It would be very useful for me if there will be a way to get names from collection tree items as variable.
For example {{collection}}, {{request}}, {{folder}} names, so it will be possible to have request addresses like (_host_ is variable from environment)
{{host}}/{{request}}
{{host}}/{{collection}}/{{request}}
etc.

**Comment by rangav** [comment]
Thanks @cezaryece for the feedback, Will add to roadmap.

what is `{{request}}` variable?
And what happens when there is nested folders for `{{folder}}`

**Comment by cezaryece** [comment]
{{request}} is name of item in collection (besides of folders), where request is defined
nested folders can be numerated if anybody want it, but for me {{folder}} can give name of folder which holds request
-collection_name
  - folder1
      - folder2
          -requestA
          -requestB

**Comment by rangav** [comment]
**for example**
- col1
  - folder1
    - folder1-1
      - request1
    

Then the `{{host}}/{{collection}}/{folder}}/{request}}`
will resolve to `http://example.com/col1/folder1-1/request1` right?

**Comment by cezaryece** [comment]
right

**Comment by rangav** [comment]
Thanks, will add to roadmap.

**Comment by rangav** [comment]
Is it possible to know your team size? will be helpful to improve the product

**Comment by Hyperclaw79** [comment]
Hello Ranga @rangav, any ETA on this? It's a really useful feature, especially since NoSQL DBs have the same structure of Collections and Records. It could help automate things when there are many collections and requests.

Would've tried to come up with a PR for this if TC was open source.

While you're at it, would it be possible to further extend this concept to something like Request Templates where new requests can all be based on a template? And just by changing the Request name, we can have an automation with minimal manual changes.

**Comment by rangav** [comment]
@Hyperclaw79 This feature is not in immediate priority list, but will implement when I got time.

We launched Thunder client CLI, where you can use CURL command to create request, May you can use Curl command as template.
https://rangav.medium.com/thunder-client-cli-a-new-way-to-test-apis-inside-vscode-d91eb5c71d8e

Please try and let me know any feedback.

**Comment by cw1934** [comment]
We're also interested in this feature being added, subscribing.

**Comment by rangav** [comment]
Hi All, planning to implement this soon.

Variables Name format question?
1. req_name, col_name and fol_name
2. request_name, collection_name and folder_name
3. requestName, collectionName, folderName

 Please let me know in comments which format you prefer?

**Comment by cw1934** [comment]
Preference: #2 or #3
Third place: #1
Last place: #4

**Comment by rangav** [comment]
This feature is implemented and published to the marketplace, please update to `v2.13.5`

- Now you can use variables `{{request_name}}`, `{{collection_name}}` and `{{folder_name}}`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.13.5

Please test let me know your feedback.

**Comment by mrmaramreddy** [comment]
@rangav  is there a way to access request/collection/folder names from the inline scripting introduced in ```v2.14.0``` ??? or would that be a future enhancement?
