### ISSUE TITLE
Git sync dissables pre run scripts

### ISSUE THREAD

**Issue by Nol-go** [rangav/thunder-client-support#905]
**Describe the bug**
When I copied my thunderclient files from my user data to my workspace and activated the gitsync setting it disabled my pre run requests. I also tried to remove the pre run requests, save, put it back and save again but it still didn't work

**To Reproduce**
1. make requests
2. link them, with pre run requests
3. activate git sync
4. copy the `thunder*.json` from `Code\User\globalStorage\rangav.vscode-thunder-client` to your workspace's `thunder-test` folder
5. run the last script of the chain
6. constat that it fails because the "get token" that needed to run before didn't

**Expected behavior**
"get token" should have ran

**Platform:** 
 - OS: windows in a node:19-bullseye dev container
 - vscode version: 1.73.1
 - extension version: 2.0.2

**Your Team Size:**
1 and a half person

**Comment by Nol-go** [comment]
![image](https://user-images.githubusercontent.com/90242082/205105395-33185d10-3787-4d4f-8ca1-a4dea592b4ff.png)
- 4 has 3 in Pre Run
- 3 has 2
- CARL has 1 in collection settings' Pre Run
![image](https://user-images.githubusercontent.com/90242082/205106807-97e6e3c0-ad85-4233-b283-6a109e65c45b.png)

**Comment by rangav** [comment]
`get auth token` is it oauth2 request?

**Comment by Nol-go** [comment]
No it's a custom call to the api with a body containing a login/password, the token type is X-CS-Access-Token

**Comment by rangav** [comment]
How you get token in `get auth token` in Request?

is it

**Comment by rangav** [comment]
Ok Just run that request and see if its still working.

Also the you see the logs in `Output` window, whether pre-request running or not

**Comment by Nol-go** [comment]
The get token isn't the only one failing, i need to manually run the first 3 requests before number 4 works, but before i activated git sync and copied the files it work fine without having to run all the requests manually

**Comment by Nol-go** [comment]
My work day ended so I'll come back with the output logs tomorrow

**Comment by rangav** [comment]
Do you still have this problem? closing this issue, feel free to re-open if needed
