### ISSUE TITLE
When importing via URL and using the file thunderclient.json, it fails to import

### ISSUE THREAD

**Issue by joshuarossi** [rangav/thunder-client-support#906]
**Describe the bug**
When trying to import via a URL, it fails with the error "Failed to import 1 files - thunderclient.json

**To Reproduce**
Create a collection using thunderclient, 
then with the file generated in the thunder-tests
in a new environment try to import the file thunderclient.json

**Expected behavior**
Because the docs say that you can import from POSTMAN, Insomnia, thunder client and open API, I expected to be able to either host a file or send a file and be able to share the collection I created.

It would be easier and better if I didn't have to convert it to a postman collection so I can import it back into thunder client.

**Platform:** 
 - OS: MacOS
 - vscode version:  1.73.1
 - extension version: 2.0.2

**Your Team Size:**
I am just experimenting on my own, but my team is probably around 40 people if we choose to use this more broadly
![SCR-20221201-v3u](https://user-images.githubusercontent.com/3466175/205214423-d515e48a-c677-4261-9ef3-7b9b856d006b.png)

**Comment by rangav** [comment]
Hi @joshuarossi you need export the collection or environment first, then you can import again.

the thunderclient.json is raw db file.

**Comment by rangav** [comment]
To share requests data with you save them in your git project 

details here
https://github.com/rangav/thunder-client-support#team

**Comment by joshuarossi** [comment]
thanks so much for the help

**Comment by rangav** [comment]
You are welcome, let me know if you have any further questions
