### ISSUE TITLE
Automatically generated Content-Type even thought not defined

### ISSUE THREAD

**Issue by jimmy-vo-librestream** [rangav/thunder-client-support#908]
It automatically generated Content-Type even thought not defined. Not a big deal to most of the services but one of our backends doesn't like this. 

![image](https://user-images.githubusercontent.com/73655109/205735705-331d3fcb-2933-4387-a56d-5450059e9276.png)
There is no work around to remove Content-Type from the headers?

**Comment by rangav** [comment]
@jimmy-vo-librestream when you select body, the extension will auto generate the content type.

But you can also send your own content-type using the header

**Comment by jimmy-vo-librestream** [comment]
I am testing with Postman and it doesn't have this behavior. The legacy backend I talking about doesn't accept any request with Content-Type, unless I removed `--header 'Content-Type: application/json' ` manually from the curl command

**Comment by rangav** [comment]
You can remove that content type line in curl, if that works for you.

We dont match with postman all the features.

or you can set empty content type, see if that works
<img width="1124" alt="Screenshot 2022-12-05 at 20 57 12" src="https://user-images.githubusercontent.com/8637550/205741321-adbdb3c2-05f9-47b3-b6c3-bee00938b05b.png">

**Comment by rangav** [comment]
I can remove content-type header in extension, when you set `content-type` is empty, if that helps?

**Comment by jimmy-vo-librestream** [comment]
Yeah, For me, the problem of setting content type to empty is it's still in the header. I need it to be completely remove. 
So removing it when you set it to empty works for me. But I am not sure if it would cause a problem for someone else. Honestly the postman behavior makes more sense to me. I would let you decide!

**Comment by rangav** [comment]
Thanks for feedback, will review it.

**Comment by rangav** [comment]
Hi @jimmy-vo-librestream 

We added new vscode setting to disable auto generating content-type
<img width="966" alt="Screenshot 2022-12-06 at 16 04 51" src="https://user-images.githubusercontent.com/8637550/205962457-755698f1-efaa-4860-9858-61186219847e.png">

**Comment by rangav** [comment]
Let me know if you above solution resolves this issue?

**Comment by jimmy-vo-librestream** [comment]
thanks for the quick fix @rangav

**Comment by rangav** [comment]
You are welcome. Shall I close this issue then?
