### ISSUE TITLE
Can't load npm modules

### ISSUE THREAD

**Issue by MitkoTschimev** [rangav/thunder-client-support#909]
**Describe the bug**
I try to implement a custom filter but it can't load the npm modules.

```
Running Request: ----------------
Environment Used: ****
Error loading node package: axios
Error loading node package: axios-cookiejar-support
Error loading node package: tough-cookie
Error loading node package: assert
...
```

**To Reproduce**

```javascript
async function getAccessTokenForUser(userString) {
  const user = JSON.parse(userString);

  // load modules
  const axios = await tc.loadModule('axios');
  const axiosCookieJarSupport = await tc.loadModule('axios-cookiejar-support');
  const toughCookie = await tc.loadModule('tough-cookie');
  const assert = await tc.loadModule('assert');

  const jar = new toughCookie.CookieJar();
  const client = axiosCookieJarSupport.wrapper(axios.create({ jar }));

  return 'token';
}

module.exports = [getAccessTokenForUser];

```

**Expected behavior**
modules can be loaded

**Platform:** 
 - OS: Mac OS
 - vscode version: Version: 1.73.1 (Universal)
 - extension version: v2.1.0

**Your Team Size:**
5

**Comment by rangav** [comment]
One more question - trying to understand your use-case why are loading axios and so many other libraries?

**Comment by rangav** [comment]
Looks like modules with dependencies are not working, will look into it.

**Comment by rangav** [comment]
@MitkoTschimev `axios` module is using ES6 import, which is not supported in Dynamic Loading of modules.

**Comment by MitkoTschimev** [comment]
Hi @rangav,

thanks for the update ;)
I wanted to automate the way how we load the access key. All other integrations are not working for us that easy.

**Comment by rangav** [comment]
Request chaining will do the same and easy way. Please try out this and let me know where you got struck? I can help you on this

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.2.1`

We have now enabled to use `axios, tough-cookie & assert` in [Scripts](https://github.com/rangav/thunder-client-support/blob/master/docs/custom-filters.js)

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.

**Comment by MitkoTschimev** [comment]
works great!

**Comment by rangav** [comment]
Thanks @MitkoTschimev for confirmation.
