### ISSUE TITLE
Share collections with the team

### ISSUE THREAD

**Issue by exhuma** [rangav/thunder-client-support#91]
**Problem Description**
When one developer in the team creates a thunder-client collection, there is no *automatic* way for other developers to benefit from that collection.

**Describe the solution you'd like**
The vs-code `settings.json` should contain a file-name for the project which points to a collection/environment file. Then, on load/reload, thunder-client should import that collection (and environment).

**Describe alternatives you've considered**
thunder-client already provides import/export functionality. But that is a manual task and it's cumbersome to communicate to the whole team to re-import the file whenever something has changed.

**Comment by rangav** [comment]
Hi @exhuma this is already implemented in v1.1.0 with support for custom storage location, see documentation - Team features section

For all the features release in v1.1.0 details here #14
