### ISSUE TITLE
Sidebar Load Error: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by isaacrlevin** [rangav/thunder-client-support#912]
**Describe the bug**
Activity is not persistened between VS Code Sessions

I see this error in the Output pane for Thunder Client

> Sidebar Load Error: Cannot read properties of undefined (reading 'data')

**To Reproduce**
VS Code Insiders install extension, try to create a request

**Expected behavior**
Requests are persisted
**Platform:** 
 - OS: Windows 11
 - vscode version: 1.75.0-insiders
 - extension version: 2.1.2

**Your Team Size:**
Just me

**Comment by rangav** [comment]
@isaacrlevin thanks for reporting 

does it work on stable vocoder version (not insiders )?

**Comment by isaacrlevin** [comment]
Just tested and it does work on Stable VS Code

**Comment by rangav** [comment]
Could be vscode insiders issue then?

**Comment by isaacrlevin** [comment]
It more than likely is but since I don't know what your code does, I am not going to get far opening an issue in the code repo. No issue doing so, just thought I would let you know that folks using Code Insiders have a bad experience with your extension

**Comment by rangav** [comment]
Ok got it, will install insiders version and test it, see if I can reproduce this issue

**Comment by rangav** [comment]
I have tested using VSCode insiders on both` Windows & Mac`, I did not have any problems

Can you try below

1. Restart Vscode and try again
2. Reinstall the extension

**Comment by isaacrlevin** [comment]
I tried on a new VS Code Insiders instance and the issue did not persist. We can close this issue.

**Comment by enricodias** [comment]
I have the exact same issue on both Linux and Windows. Vscode v1.74.2. Reinstalling the extension didn't work.

Saving new requests work, but they are lost after restarting vscode.

**Comment by rangav** [comment]
@enricodias what extension version are you using? please update to latest.

**Comment by enricodias** [comment]
@rangav 2.2.4

I just noticed that clicking in the reload button in the top right do work and previous saved requests are shown.
