### ISSUE TITLE
Thunder Client doesn't load it's screen 

### ISSUE THREAD

**Issue by EttisafRup** [rangav/thunder-client-support#915]
I'm facing this from a month. Thunderclient keeps loading and loading but the interfaces are not shown to me. I tried to reinstall it but it doesn't help. Help me out!

**Comment by EttisafRup** [comment]
> @EttisafRup thanks for reporting the bug, will look into it.
> 
> can you share screenshot of loading page?
> 
> also share below info
> 
> * your OS
> * vscode version
> * extension version

Thanks for the response, rangav! I've noticed that it was fixed while I installed it from the direct link (marketplace,vsc). I'll surely let you know if it occurs again!

**Comment by rangav** [comment]
Good to know it’s working for you now, sure let me know if you have any questions or issues
