### ISSUE TITLE
Resolve/Render nested .env variables (when linking to .env)

### ISSUE THREAD

**Issue by dfidler** [rangav/thunder-client-support#916]
### Problem Statement:

It's not uncommon for .env files to use variables inside of variables which means that thunderclient can't render those variables when linked from the .env file

Consider the following .env file:
```
HTTP=http
DOMAIN_APP=my.app.com
DOMAIN_API=api.app.com
PORT_APP=8000
PORT_API=8001

APP_URL=${HTTP}://${DOMAIN_APP}:${PORT_APP}
VUE_APP_API_BASE=${HTTP}://${DOMAIN_API}/api:${PORT_API}
SESSION_DOMAIN=${DOMAIN_APP}
```

If we're going to share the collections amongs the team members (and comit them in the project repo), the URLs need to be transportable across development environments.  Being able to "render" the variables in the above example could mean that request could simply use **_{{ VUE_APP_API_BASE }}_** (which is constructed by the other  as the base for all API URLs and no changes would be required to get the collection working in the environment.

**Describe the solution you'd like**

Render the variables in .env; this is easy in linux but I don't know how this could be resolved in windows short of some kind of rendering code (which is not low-hanging fruit).

**Describe alternatives you've considered**
Make the .env file more complex/less general for different environments by adding a dedicated variable for referencing the API.  However, it's not uncommon for me to checkout several branches on the same system (to test different use cases amongst them) so the above 5 variable setup in the .env is ideal for rapidly setting up new development environments.

**Your Team Size:**
Three

**Comment by rangav** [comment]
Hi @dfidler, you can reference other variables using same format `{{variable}}`

If you use below format then it should work

```
HTTP=http
DOMAIN_APP=my.app.com
DOMAIN_API=api.app.com
PORT_APP=8000
PORT_API=8001

APP_URL={{HTTP}}://{{DOMAIN_APP}}:{{PORT_APP}}
VUE_APP_API_BASE={{HTTP}}://{{DOMAIN_API}}/api:{{PORT_API}}
SESSION_DOMAIN={{DOMAIN_APP}}
```

**Comment by joaonunogomes** [comment]
Hi :) I have a similar suggestion. When creating a variable from another variable, the ThunderClient UI can successfully resolve the reference variable, but it doesn't highlight as done in other scenarios, when using variables.
For Example, here I've created a new var on `Local Env`:
![image](https://user-images.githubusercontent.com/49573678/223418366-9bdff56c-0bb5-428f-88f1-a50994eb5b81.png)

In the following image, I use the `Local env` variable on my custom environment:
![image](https://user-images.githubusercontent.com/49573678/223418977-861fcea2-c3bc-48ea-9472-70c7e0bb9a02.png)

And here you can see that ThunderClient can resolve and highlight the custom variable:

![image](https://user-images.githubusercontent.com/49573678/223419175-84c0ce9e-4508-42f4-8acf-ecc944bb79e6.png)


My question/request is:
Can environments highlight variables such as done on request?

**Comment by rangav** [comment]
Hi @joaonunogomes can you create new feature request for this?

**Comment by joaonunogomes** [comment]
Yes :) Will do @rangav . Thanks

**Comment by rangav** [comment]
Closing this issue, feel free to re-open if needed

**Comment by dfidler** [comment]
> 

Thanks. I'll give that a try but I don't see that syntax anywhere in the dotenv or dotenv-expand documentation.  In fact, if I look at the [test code](https://github.com/motdotla/dotenv-expand/blob/master/tests/.env) for dotenv-expand, that syntax isn't tested.

**Comment by rangav** [comment]
@dfidler will review again when I got time. I will reopen issue.

please share documentation links for nested variables in .env

**Comment by dfidler** [comment]
@rangav - re: documentaiton:

I'm using js dotenv/dotenv-expand and phpdotenv in my project.

* [js dotenv](https://github.com/motdotla/dotenv) - says variable [expansion must be done with](https://github.com/motdotla/dotenv#variable-expansion) [dotenv-expand](https://github.com/motdotla/dotenv-expand) and links to it
* [dotenv-expand](https://github.com/motdotla/dotenv-expand) - defines [the rules that dotenv-expand follows](https://github.com/motdotla/dotenv-expand#faq) and the expansion test are in the [test code](https://github.com/motdotla/dotenv-expand/blob/master/tests/.env) that I linked to above
* [phpdotenv](https://github.com/vlucas/phpdotenv) - only uses ${ } syntax for [nesting variables](https://github.com/vlucas/phpdotenv#nesting-variables) but what isn't documented ([but does appear to be tested](https://github.com/vlucas/phpdotenv/blob/master/tests/fixtures/env/nested.env)) is ${ ${x} }, which is not supported in dotenv-expand.  :/

The double-moustache syntax {{ }} is most familiar to me in jinja or blade so I'm guessing you're using some kind of templating library to parse the file.  Depending on the language that you're writing the extension in (I know nothing about vscode extension writing, or I would have just checked your code), perhaps there is a dotenv(-expand) package that you could use to render the .env file before running it through your templating code?

**Comment by rangav** [comment]
Thanks for sharing docs.

I am using `{{varaible}}` syntax for Environment variables internally. so it will also work for nested variables with that format.

I will try to use `dotenv-expand` library and test it when I got time.

**Comment by rangav** [comment]
Hi @dfidler finished implementation, looks easy using dotenv-expand library.

Would you like to test and confirm?. I will upload `VSIX` file here

**Comment by rangav** [comment]
Please find the VSIX file for testing.

[vscode-thunder-client-2.5.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/10948916/vscode-thunder-client-2.5.2.vsix.zip)

**Comment by dfidler** [comment]
@rangav - using this version, I was able to use {{VUE_APP_API_BASE}} in both thunderclient environment variables and request urls/endpoints.  Obviously the tests I've done are not comprehensive but it sure looks like it works, to me.  Nice one!  :)

**Comment by rangav** [comment]
you can use `${nestedVar}` this format or any of the formats specified below in .env files

https://github.com/motdotla/dotenv-expand#faq

What format you like to use to reference nested variables in .env ?
1. {{nested}}
2. ${nested}

**Comment by dfidler** [comment]
@rangav - perhaps I am not being clear, your change in 2.5.2 vsix (above) worked.  My .env file looks like this:

```
HTTP=http
DOMAIN_APP=my.app.com
DOMAIN_API=api.app.com
PORT_APP=8000
PORT_API=8001

APP_URL=${HTTP}://${DOMAIN_APP}:${PORT_APP}
VUE_APP_API_BASE=${HTTP}://${DOMAIN_API}/api:${PORT_API}
SESSION_DOMAIN=${DOMAIN_APP}
```
And my "environment" variable (in thunderclient) "url" = {{VUE_APP_API_BASE}}

So now all of my requests just have {{url}}/endpoint?params

This seems to work perfectly.

Now we can save/commit our thunderclient requests in a standard format, and the developers can change the behaviour based on where they are developing (http on local laptops, https on test systems, etc) - they just need to change the .env file and never need to change the thunderclient requests (which is what I was hoping for)

**Comment by rangav** [comment]
Thanks @dfidler, for clarification. Sorry for misunderstanding your earlier comment.

Glad it's working now as you expected. 

I will publish `v2.5.2` to marketplace next week.

Let me know if you need any further changes.
