### ISSUE TITLE
Feedback when filters fail

### ISSUE THREAD

**Issue by assensamuelsson** [rangav/thunder-client-support#922]
**Is your feature request related to a problem? Please describe.**
I'm using the `exec(...)` filter in the Auth tab to authenticate to the API I want to call. The API is hosted on GCP and I'm using `{{@ | exec("gcloud auth print-identity-token")}}` as my Bearer token to make sure it is always valid.

This originally worked fine but then stopped working and it took me a while to figure out why. I'm normally using a bash shell from vs code and have setup my PATH in .bashrc so that `gcloud` is found. The exec filter is however executed in a zsh shell that can't find `gcloud`. Thunder-Client however executed the request without any feedback that this filter didn't work and no Authorization header was sent in the request.

**Describe the solution you'd like**
Would like to see some kind of error message somewhere that said `zsh: command not found: gcloud`.

**Describe alternatives you've considered**
When using many filters it would also be useful if all request headers could be visible somewhere. When using the filter above I can't be sure what the value of my Bearer token really is.

**Your Team Size:**
~ 15

**Comment by rangav** [comment]
@assensamuelsson thanks for the feedback.

We display logs in the `Output Window`, where you can find request headers and error logs

**Comment by assensamuelsson** [comment]
Oh my, why didn't I think of this 😓 . Thank you for pointing this out!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.2.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.

----
- Show Logs `shortcut` added to menu list items
<img width="447" alt="Thunder Logs" src="https://user-images.githubusercontent.com/8637550/209186501-a4b3419a-cfab-4c98-adfc-093aa5d73451.png">
