### ISSUE TITLE
Show Request Cookies

### ISSUE THREAD

**Issue by sbscan** [rangav/thunder-client-support#923]
Cookies sent with the request can't be displayed.
Even HttpOnly Secure respond cookies ara automatically sent with each request, but thunder client won'r display the request cookies. Postman does:
![image](https://user-images.githubusercontent.com/18386839/208110218-bf8ca4c1-56d7-4ca1-ac36-4e92de9bd4ca.png)

**Comment by rangav** [comment]
Hi @sbscan 

We have cookie tabs which will display cookies

<img width="778" alt="Screenshot 2022-12-16 at 15 02 44" src="https://user-images.githubusercontent.com/8637550/208127119-c5ad4449-cdb7-4fe4-a690-b57c4575d235.png">

**Comment by sbscan** [comment]
Hi @rangav, this is Response Cookies which thunder gets, I'm looking for Request Cookies which thunder sends. BTW thanks for this great project, I love it 🥰

**Comment by rangav** [comment]
Glad to know you like the extension 👍 

Ok got it, will add to the tab as Request Cookies tab or Logs window

Where does postman show request logs I dont see them?

**Comment by sbscan** [comment]
Bottom line, next to body tab:
![image](https://user-images.githubusercontent.com/18386839/208679721-14c5830c-ec8d-4efb-a0aa-5b93fe34cdd6.png)

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.2.1`

The request cookies will be displayed in `Logs`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.
