### ISSUE TITLE
Can't clear all activities at once, and I can't delete an environment.

### ISSUE THREAD

**Issue by YpsilonTM** [rangav/thunder-client-support#929]
**Describe the bug**
The `Clear Activity` button does nothing for me. Same if I want to delete an environment.

**To Reproduce**
I just launch my vcode and open the thunder client and try to do these actions. I have tried launching vscode as administrator. But no luck there.

**Expected behavior**
Clear Activity: That al activities are removed
Delete Environment: That it actually gets deleted

**Platform:** 
 - OS:  Windows 11
 - vscode version: 1.74.1
 - extension version: V2.2.0

**Comment by rangav** [comment]
@YpsilonTM thanks for reporting the bug, will look into it.

**Comment by rangav** [comment]
Some users have this issue.

- Please enable this setting, you can delete `environment` or `collection`.
- I will add Clear All Activity to this alternative delete option in next update.
<img width="997" alt="Screenshot 2022-12-05 at 05 54 30" src="https://user-images.githubusercontent.com/8637550/205559721-0ef46220-1bdb-4b82-9856-7ed21d05319d.png">

**Comment by YpsilonTM** [comment]
I can delete an environment now. So it looks like indeed for some reason I don't get the prompt.

> I will add Clear All Activity to this alternative delete option in next update.
Ok thank you I guess that is the same problem. Because That is still broken for me.

Greetings Ypsilon, Thank you for the quick response!

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.2.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.
