### ISSUE TITLE
Document OAuth settings

### ISSUE THREAD

**Issue by Dunky13** [rangav/thunder-client-support#93]
**Describe the bug**
If I want to use OAuth I need a Access Token, this is generated by calling `Generate Token`, but what was unclear is that the Callback Url needs to be empty for Thunder client to capture the token. 
As well as the redirect url on the oauth provider needs to be set to `https://www.thunderclient.io/oauth/callback`

**To Reproduce**
Run OAuth `Generate Token` with non-empty callback Url - it will not grab the access token.

**Expected behavior**
Documentation on the fact that the callback Url needs to be empty & oauth provider needs to set the proper redirect url.

**Comment by rangav** [comment]
Hi @Dunky13 if you have your own callback url, you can use it, currently it has a default url for users who dosen't have callback url and use thunder client url. 

Without callback url you will not be able to generate token

**Comment by Dunky13** [comment]
I understand, the issue was suggesting an enhancement of the documentation, not the code. To help new users with setup

**Comment by rangav** [comment]
Sure @Dunky13 will update the documentation.

**Comment by rangav** [comment]
Hi @Dunky13 updated the oauth in the documentation, let me know if anything is not clear.

https://github.com/rangav/thunder-client-support#auth
