### ISSUE TITLE
Ability to Format Graphql Body

### ISSUE THREAD

**Issue by garethredfern** [rangav/thunder-client-support#931]
Could you add the feature to format a Graphql body code snippet, please. That featured is available for JSON and XML.

**Comment by rangav** [comment]
Thanks @garethredfern for the feeback, will add to roadmap

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.5.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.
