### ISSUE TITLE
Ability to load the built-in http module

### ISSUE THREAD

**Issue by detarkende** [rangav/thunder-client-support#932]
**Is your feature request related to a problem? Please describe.**
I'd like to send http requests from my pre-request scripts, but since axios and node-fetch use ES6 modules, they can't be loaded with `tc.loadModule`. So the next best thing would be to use the built in http module of node, but I can't load it with require, and `tc.loadModule` shows a 404 error (I guess it only tries to look up the npm registry).

**Describe the solution you'd like**
Either allow the `require('http')` syntax, or the `tc.loadModule('node:http')` syntax in the VM2 sandbox.

**Describe alternatives you've considered**
Tried using node-fetch, axios, undici, but they all fail to load. When I bundled all of axios or node-fetch into the script, it still failed because they need many built in node modules.

**Your Team Size Using TC:**
I'm currently trying to convert our postman tests to ThunderClient, and this is the last thing that I need to finish the transition.
So at the moment, 0, but if feature gets implemented, then around 7 new people will use TC in our team.

**Comment by rangav** [comment]
Hi @detarkende thanks for the feedback

We are using `axios` internally, I will enable it to use in scripts in the next update

**Comment by rangav** [comment]
We have request chaining, which has easy to use GUI interface to run pre requests, please give a try.

**Comment by detarkende** [comment]
Wow, that `axios` thing is going to be a great addition. Easily overpowering the competition (like postman).

And thanks, I know about the request chaining, that would've been my 2nd option. But we are really used to working with pre-request scripts that fetch some data and we could probably just copy our existing scripts over in a couple of days. I'll wait for the `axios` feature I think :)

Again, thanks for the great support 😄

**Comment by detarkende** [comment]
@rangav , I'm sorry to bother you, but I'd like to ask a question. 
Can we know an estimated date when the next release is happening? 

I'm not trying to hurry you or anything, I'm really grateful for the work you do. But since the project isn't open source, it's not possible to track progress, or contribute.
I'm planning to do a workshop for my team on TC, but I don't know when to schedule it, since I want to wait for the next release.

I hope this doesn't come off the wrong way, I'm just curious 🙂

**Comment by rangav** [comment]
@detarkende let me come back to you by end of the day, see if I can do quick release today to enable this feature.

**Comment by detarkende** [comment]
Yes, absolutely

**Comment by rangav** [comment]
thats good, development done - will upload the `vsix` file here in around 10 mins

**Comment by rangav** [comment]
[vscode-thunder-client-2.2.1.vsix.zip](https://github.com/rangav/thunder-client-support/files/10289023/vscode-thunder-client-2.2.1.vsix.zip)

Please find the vsix file, install it. 

You can load axios using  `var axios = require("axios");` and also you can use `async` calls

Please test and let me know your feedback.

**Comment by detarkende** [comment]
Sorry that it took so long, I had some issues but not with the plugin 😄 
YES, it's working for me perfectly. It's imported (required), it sends requests, the whole deal...

Thank you so much!

**Comment by rangav** [comment]
Thanks @detarkende for confirmation, will publish live later today

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.2.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.
