### ISSUE TITLE
Query parameters disappear when changing url

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#933]
**Describe the bug**

When changing the url, if all query parameters are disabled, they are deleted 

**To Reproduce**

1. Place this url in the url field
`https://www.thunderclient.com/welcome?limit=10`
2. Disable the query param checkbox
3. Change the url

**Expected behavior**

Query parameters do not disappear

**Platform:** 
 - OS: Manjaro
 - vscode version: 1.74.1
 - extension version: 2.2.0

**Your Team Size Using TC:**

I'm the only one in my team, I think

**Comment by rangav** [comment]
Thanks @andresatierf for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.2.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.

**Comment by andresatierf** [comment]
It's fixed

**Comment by rangav** [comment]
Thanks for confirmation 👍
