### ISSUE TITLE
Creating new requests fails silently if using a Workspace Relative Path that doesn't exist

### ISSUE THREAD

**Issue by schallm** [rangav/thunder-client-support#934]
**Describe the bug**
If you have `Save To Workspace` enabled and relative path set to a path (i.e. `test`), but the path does not exist in the current workspace, clicking "New Request" fails silently.

**To Reproduce**
1. Check `Save To Workspace` in settings
2. Set Workspace Relative Path to `test`
3. Open a folder that does not have a subfolder named `test`
4. Click on `New Request` on Thunder Client Side Bar
5. Notice nothing happens

**Expected behavior**
Click on `New Request` and one of the following should happen
  - Create an empty new request.  When saving it should create the `test` folder.
  - Notify the user that the Workspace Relative Path doesn't exist and ask if it should be created
  -  ?

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.74.2
 - extension version: v2.2.0

**Your Team Size Using TC:**
10

**Comment by rangav** [comment]
@schallm thanks for the feedback, Will log error message for this.

Will review it further and see how can we solve this issue better.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.2.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.
