### ISSUE TITLE
wkhtmtopdf PDF with table not treated like other PDFs

### ISSUE THREAD

**Issue by met4000** [rangav/thunder-client-support#935]
**Describe the bug**

Relevant files (generated using wkhtmltopdf):
- [a.pdf](https://github.com/rangav/thunder-client-support/files/10274240/a.pdf) (html source is just "test")
- [b.pdf](https://github.com/rangav/thunder-client-support/files/10274242/b.pdf) (html source contains a table)

When `a.pdf` or `b.pdf` is served and accessed via chrome, firefox, or postman, they 'work fine' (they display the pdf, as expected).
When thunder client accesses `a.pdf`, it treats it as a binary file and gives an option to 'open in code' e.g. using a pdf viewing extension. This works as expected. However for `b.pdf`, it attempts to display the pdf as a text response.

`a.pdf` response:
![image](https://user-images.githubusercontent.com/15624876/208819439-095b393b-60c9-44e0-8d53-b500fe7ef098.png)
`b.pdf` response:
![image](https://user-images.githubusercontent.com/15624876/208819468-1eeb089e-8551-4f7c-b2d0-2232e18809f9.png)

Using the menu to 'save to file' (as `b2.pdf`) yields a pdf file that when opened as a file in chrome does not error but shows a blank pdf. Using `cmp` or `diff` to compare `b.pdf` and `b2.pdf` shows that the content is different - saving `a.pdf` when accessed via thunder client yields a file that does not show any differences to `a.pdf` when compared with `cmp`/`diff`.

**To Reproduce**

- Download the attached pdfs
- Serve the pdfs with a webserver - testing was done using [`http-server`](https://www.npmjs.com/package/http-server)
- View the pdfs via the server (in a browser, postman, or thunder client)

**Expected behavior**

I would expect `b.pdf` to behave the same in thunder client as `a.pdf`; to be treated as a binary file with the prompt to open it as one, and for the saved version of the response to be identical to `b.pdf`.

**Platform:** 
 - OS: Ubuntu (WSL), on Win 11
 - vscode version: 1.74.2
 - extension version: 2.2.0

**Your Team Size Using TC:**

6

**Comment by rangav** [comment]
Thanks @met4000 for reporting the bug, will look into it.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.2.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.2.1

Please let me know your feedback.
