### ISSUE TITLE
json tests fail ("Actual value is too big to display" message)

### ISSUE THREAD

**Issue by rok-bajec-sowa** [rangav/thunder-client-support#937]
**Describe the bug**

When testing responses with test ` json[0].items.length > 100`, I got error `Actual value is too big to display`. Before this test worked.

**To Reproduce**

1. set test on response to  `json[0].items.length > 100`
2. run test
3. check test results

Testing response looks like following:
``` json
[
  {
    "items": [
      {
        "close": 15799.7577477900000000,
        "closeTime": "2022-12-22T07:22:56Z",
        "quoteTime": "2022-12-22T07:22:56Z",
        "volume": 100
      },
      {
        "close": 15799.80348511127025485,
        "closeTime": "2022-12-22T07:23:26Z",
        "quoteTime": "2022-12-22T07:23:26Z",
        "volume": 100
      },
...
```

**Expected behavior**
Test should return true/false

**Platform:** 
 - OS: Windows 11
 - vscode version: 1.74.2
 - extension version: 2.2.0

**Your Team Size Using TC:**
1

**Comment by rangav** [comment]
@rok-bajec-sowa there is not length property, it will not work.

you can use `length` filter for this `json[0].items | length`

filter docs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md
