### ISSUE TITLE
Request name with '<' rendered as &lt;

### ISSUE THREAD

**Issue by darcome** [rangav/thunder-client-support#939]
**Describe the bug**
Request names with special html characters are rendered as encoded. For example '<' is rendered as &lt;.

**To Reproduce**
Just use the '<' character as part of a request name.

**Expected behavior**
Characters to be rendered correctly.

**Platform:** 
 - OS: Window 11
 - vscode version: 1.74.2
 - extension version: 2.2.1

**Your Team Size Using TC:**
1

**Comment by rangav** [comment]
Thanks @darcome for reporting the bug, will fix it asap.

**Comment by rangav** [comment]
This bug is now fixed, please updated to `v2.2.4`
