### ISSUE TITLE
Collections with tests

### ISSUE THREAD

**Issue by sirkkalap** [rangav/thunder-client-support#94]
**Solution proposed**
I would like to have some tests repeated for multiple targets. Targets could be in a collection and the collection could have tests that it would then run for each target in it.

**Alternatives considered**
As an alternative a copy & paste option to add similar set of tests to already existing target could work. Updating and deleting tests would still remain as repetitive work. (This might already exists, sorry I do not have the Visual Studio)

**Comment by rangav** [comment]
Hi @sirkkalap this request is similar to #33, I am closing this issue.

This feature is planned for next update #282
