### ISSUE TITLE
Set command output as variable.

### ISSUE THREAD

**Issue by TECH7Fox** [rangav/thunder-client-support#942]
**Is your feature request related to a problem? Please describe.**

I have a shell command to get a bearer token. I know that in **Insomnia** you can set commands using the shell plugin, but I couldn't find this feature in Thunder Client.

**Describe the solution you'd like**

A way to use shell commands in templates. Something like `{{command: echo test}}` would be `test`.

**Comment by rangav** [comment]
Hi @TECH7Fox 

we have a feature to execute commands using filter, see if that is useful

https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#exec

**Comment by TECH7Fox** [comment]
Thanks @rangav,

For most commands/scripts it seems to work, but not for the one I need. Even if I type something that doesn't exist, I do not get a `Command ... not found...`. Does it filter some output out?

**Comment by rangav** [comment]
What command are you trying to use? let me test here locally

**Comment by rangav** [comment]
> `Command ... not found...`

It will show errors in Logs
https://github.com/rangav/thunder-client-support#logs

**Comment by TECH7Fox** [comment]
> What command are you trying to use? let me test here locally

It's a custom script for our project, but I put some other commands above that also don't show anything when they do in the terminal.

**Comment by TECH7Fox** [comment]
Sorry, misclick.

> It will show errors in Logs

Ah, great. Will look at it tomorrow. Thanks.

**Comment by rangav** [comment]
> It's a custom script for our project, but I put some other commands above that also don't show anything when they do in the terminal.

To use custom scripts you can use `Custom Filters` feature
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by TECH7Fox** [comment]
It isn't a filter script, just a simple shell script.

I found two issues that I found.

If the command returns a error it doesn't return anything. It just says:
```
Error in Filter: exec(alembic) - Command failed: alembic
/bin/sh: 1 [the command output]
```
I expect, and would like it to always return the output. Even if there is a unwanted error.
In other software like Insomnia it does return the whole output.
Is there a reason it is implemented like this?

Also, it's not possible to use `|` in exec. Even in quotes. For example when I do `mycommand | jq . -s` I get this in the logs:
```
Error in Filters: Filter is not defined - jq . -s
```
Is there any way around that? Without making another script for this?

**Comment by rangav** [comment]
Thanks @TECH7Fox for the feedback, will return the error details, when then is exception.

`|` symbol is reserved for [filters](https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md) use in the extension

**Comment by TECH7Fox** [comment]
But the `|` is not being used inside the `exec` right? At least not in quotes I would imagine.

So what if it just uses them for the command? That way people can use more complicated commands and use for example grep or/and jq to filter the output.

**Comment by rangav** [comment]
Let me verify whether it’s possible to escape `|` inside exec and get back to you

**Comment by TECH7Fox** [comment]
Hey @rangav, did you find a solution? Or are there changes needed to support this?

**Comment by rangav** [comment]
Haven’t verified yet, will check later today

**Comment by rangav** [comment]
We can escape the | in exec command, what `escape character` suits you?, as not familiar with grep commands

**Comment by TECH7Fox** [comment]
`\` sounds good to me. :+1:

**Comment by TECH7Fox** [comment]
Just to clarify,

Commands that can contain a error but still go trough will also fail. When I get `base64: invalid input` it fails the entire command and doesn't return anything. Would be great if it just ignores that (like Insomnia). If there actually is a unexpected error, people will probably notice in the request right?

**Comment by rangav** [comment]
Did not fully understood, what is your suggestion above?

**I am already planning to do below**

- When there is error while executing the filter, Currently it will only log to output window, But next update it will return the error to the request and also log, so user knows it clearly

**Comment by TECH7Fox** [comment]
> But next update it will return the error to the request and also log, so user knows it clearly

That's great. But will it just be the same as the output window, or the entire command? The output window only shows the command up until the error. While the command outputs the necessary info after the error message.

So basically be suggestion is to return the entire command output. Even if it contains a error.

**Comment by TECH7Fox** [comment]
Here is a example of what my command returns:

```
INFO: Dumping token...
INFO: Decoded access_token
base64: invalid input                           <- This is the last thing the output window shows
{
    "access_token": "MY_TOKEN"      <- This is what I need.
}
```

With Imsomnia I then use `grep` to remove the other output, and use `jq` to make it a json object and get the "access_token" variable.

**Comment by rangav** [comment]
Don’t know how Insomnia scripting works.

if you can provide example in Thunder Client.
- How it’s working now?
- And What you like to be changed?

then it will be clear to me.

**Comment by TECH7Fox** [comment]
Thanks for the quick reply.

> Don’t know how Insomnia scripting works.

Only a shell command. Acts exactly like a terminal.

> How it's working now?

I tried this:
`{{@ | exec("get_bearer_token --dump-token https://my-api/ | grep -v INFO | jq . -s | jq .[0].access_token") }}`

But it doesn't give anything and the logs say `Error in Filters: Filter is not defined - jq . -s` because of the `|`.

Also, if `\|` gets implemented, it still doesn't return anything.

If I try this:
`{{@ | exec("get_bearer_token --dump-token https://my-api/") }}`

I get nothing and the output window shows:
```
Error in Filter: exec(\"get_bearer_token --dump-token https://my-api/\") - Command failed: get_bearer_token --dump-token https://my-api/
INFO: Dumping token...
INFO: Tokens
INFO: Decoded access_token
base64: invalid input
```
And the rest gets cut of in the output window.

> What you like to be changed?

2 things,

1: To use `|` for the command. Like you said, escaping with `\` would be great.

2: Always return the entire output like what the terminal would give. Correct me if I'm wrong but I think that there is no need for error catching, maybe it's expected by the user to include a error or fail.

So for example, `{{@ | exec("get_bearer_token --dump-token https://my-api/") }}` would return:
```
INFO: Dumping token...
INFO: Tokens
INFO: Decoded access_token
base64: invalid input
{
    "token": "my_token"
}
```

So it doesn't fail and stops at `base64: invalid input`. It returns everything.

Hope this helps. Please let me know if you need any more info.

**Comment by TECH7Fox** [comment]
Here is a screenshot from Insomnia. Notice how `|` works it shows the entire output, including any "errors".

![image](https://user-images.githubusercontent.com/32220029/210780907-25106661-ae8d-430b-9161-118f6d6f501b.png)

**Comment by rangav** [comment]
@TECH7Fox its clear now. I am nearly done with development. 

I can upload the `pre-release` version of `vsix` file here, you can test and let me know your feedback asap. Then I can make any quick last minute changes needed before I publish the update later today.

Let me know if you can do quick testing and feedback?

**Comment by TECH7Fox** [comment]
Sounds good. I can test now.

**Comment by TECH7Fox** [comment]
It works great. I do see that it still stops the command when it detects a error, but I managed to filter that out using `\|`.

Not related, but the bearer token is surrounded by quotes so now it says `"Authorization": "Bearer "TOKEN""`
Any way around that?

**Comment by TECH7Fox** [comment]
Now I can get the bearer token automatically. For me it all looks good now. :+1: Thank you very much for your work.

**Comment by rangav** [comment]
Thanks for confirmation. 

You can also create your own `custom filter` and use `tc.exec` function if needed? do you see this any useful?

**Comment by TECH7Fox** [comment]
> You can also create your own custom filter and use tc.exec function if needed? do you see this any useful?

I never created a custom filter myself, but I can see that being very useful.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.3.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.

**Comment by TECH7Fox** [comment]
Still works great, thanks!

Just one unrelated question, is there a way to use templating in a environment variable? That would be very useful so I don't have to edit all my requests if I need to change the command.

**Comment by rangav** [comment]
Yes you can use templating using env variables

see docs here
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#exec

**Comment by TECH7Fox** [comment]
I mean in here: 
![image](https://user-images.githubusercontent.com/32220029/210976991-7e75cc6a-d3ce-4573-8ab3-e873450c186b.png)
But it just returns the command itself. `{{@ | exec("echo hi")}}`

**Comment by rangav** [comment]
Oh ok got it. I haven’t tried that.

you can try and let me know.

**Comment by TECH7Fox** [comment]
Could be a nice feature perhaps. But also just found that I can set a bearer token in the collection settings, which is even better for my case.

**Comment by rangav** [comment]
You can try `{{@ | exec("{0}", varName)}}`

varName variable value can be changed based on environment

**Comment by TECH7Fox** [comment]
Ah, of course. Thanks.

**Comment by TECH7Fox** [comment]
Sorry to bother you again, but I noticed another thing and I didn't want to make another issue before knowing if there is something I'm missing.

When there is an 500 internal error, the thunder client doesn't show anything. While the request does return a traceback.

I got this:
![image](https://user-images.githubusercontent.com/32220029/211032940-69cb010b-f72e-4749-877e-d3d2cbb6a373.png)

While I expected this (Insomnia):
![image](https://user-images.githubusercontent.com/32220029/211033028-c01f2a31-2741-499a-94fc-b69bdc0fceed.png)

Is this intentional? Would be useful to see what's going wrong with my API when testing.

**Comment by rangav** [comment]
Yes it will only show error message in request. you can see logs for more info

**Comment by TECH7Fox** [comment]
What about a option to display error responses? Or just always show it. Why hide it right?

**Comment by TECH7Fox** [comment]
> You server should show those errors right? Trace logs

Yes it does, but it is in kubernetes so I have to get in the container and keep a terminal open for it which is not desired.
Later I also saw that 404 errors which return a nice json object with the error like `image not found` but thunder client hides it and just says failed with 404.

> Will look into when i got time?

Would be great, thanks. This is currently the only thing stopping me from completely replacing Insomnia and it would be very useful since most people probably use this to test and debug their endpoints.

> do you have any sample error url for testing?

Not really. It's all private for now so I can't share specifics. But it seems like any response that doesn't have a 200 status code.

**Comment by rangav** [comment]
Sure will look into it and will post status update here next week.

Can you please create a new feature request for this, so it will be easy to track?
With details from this comment - https://github.com/rangav/thunder-client-support/issues/942#issuecomment-1373719024
