### ISSUE TITLE
version 2.2.1 is not working.

### ISSUE THREAD

**Issue by TanmayBanerjee-23rd** [rangav/thunder-client-support#945]
**Describe the bug**
on upgrading it on macOS Monterey causes thunder client sidebar not found issue. you see no content on the side bar on navigating to the thunder client extension.

**To Reproduce**
you must have got the update by now ... just try using it.

**Expected behavior**
sidebar pops up as earlier with all the options to manipulate it.

**Platform:** 
 - OS: macOS Monterey
 - vscode version: 1.72.0 universal
 - extension version: 2.2.1

**Your Team Size Using TC:**
not sure.

**Comment by rangav** [comment]
Thanks @TanmayBanerjee-23rd for reporting the bug

Where is your requests data saved? is it in default location?

Try below

- Restart vscode and see if that works
- Re-install the extension and check

**Comment by ogkunald** [comment]
It's not working for me either, I'm using vs-code server, what are the steps to rollback to prev version

**Comment by rangav** [comment]
Go to extensions tab, search for thunder client. then see below image, try any previous version
<img width="294" alt="Screenshot 2022-11-30 at 12 47 07" src="https://user-images.githubusercontent.com/8637550/204800279-5a23ff21-4876-4224-a2f0-107af828f0f3.png">

**Comment by evanawebb** [comment]
I was having the same issue on Ubuntu, rolling back to 2.2.0 worked for me. I first tried uninstalling/reinstall then found this thread.

**Comment by TanmayBanerjee-23rd** [comment]
I never did explicitly select folder for requests data saving. So it's using default location most probably.
Restarting the vscode and reinstalling the extensions were the first workarounds I did try but they didn't fix the issue.
Currently using previous version, which works.

**Comment by rangav** [comment]
I have fixed this and published to marketplace, please update to `v2.2.4`

Let me know if you still have the issue.
