### ISSUE TITLE
command 'thunder-client.open-docs' not found

### ISSUE THREAD

**Issue by spanwair** [rangav/thunder-client-support#946]
**Describe the bug**
new version 2.2.1 only keep loading and whole extension is unable to use

**To Reproduce**
install v.2.2.1

**Expected behavior**
to work :)

**Platform:** 
 - OS: Linux Mint 20.3 Cinnamon
 - vscode version: 1.73.1
x64

**Comment by rangav** [comment]
Hi @spanwair Thanks for reporting the bug.

I have tested on windows its working. can you restart vscode and waiting till sidebar is fully loaded.

**Comment by MuhammadDicky** [comment]
I have similiar problem, all command from thunder-client is not found. Also thunder client is never loaded. this happen on version 2.2.1, but is running fine once i drop to the previous version.

**Comment by rangav** [comment]
Looks like after fixing this issue https://github.com/rangav/thunder-client-support/issues/928, some users are facing the issue.

I updated code to address this issue. I will upload `vsix` file here, can anyone please test and confirm its working or not?

**Comment by Genialngash** [comment]
Parrot os  5.1
Using VsCodium the current version is facing a similar issue.
I had to downgrade

**Comment by rangav** [comment]
I have fixed this and published to marketplace, please update to `v2.2.4`

Let me know if you still have the issue.
