### ISSUE TITLE
export curl

### ISSUE THREAD

**Issue by jeanbrazcosta** [rangav/thunder-client-support#947]
**Is your feature request related to a problem? Please describe.**

I would suggest that you have the option to export a request made to curl, this would be very useful, as inserting a curl in an api bug is very useful.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Your Team Size Using TC:**

**Comment by rangav** [comment]
@jeanbrazcosta its already supported using Code Snippet

details here
https://github.com/rangav/thunder-client-support#codegen

**Comment by cschar** [comment]
above codegen link isnt working...

how do we export to curl?

**Comment by rangav** [comment]
Updated link
