### ISSUE TITLE
Allow multiple iterations in collections runner

### ISSUE THREAD

**Issue by PikaFederation** [rangav/thunder-client-support#95]
**Describe the solution you'd like**
As the title says, I would like to be able to run x times a collection (the same function as postman does!).
It could be awesome! 😁

![](https://assets.postman.com/postman-docs/runner-results-v8.jpg)

**Comment by rangav** [comment]
Hi @PikaFederation is your use-case similar to https://github.com/rangav/thunder-client-support/issues/298#issuecomment-898578218 ?

I can provide the option to run multiple times easily - without the tabs for each iteration, let me know if that will be useful?

**Comment by PikaFederation** [comment]
> Hi @PikaFederation is your use-case similar to [#298 (comment)](https://github.com/rangav/thunder-client-support/issues/298#issuecomment-898578218) ?
> 
> I can provide the option to run multiple times easily - without the tabs for each iteration, let me know if that will be useful?

Hi, yes it'll be!

**Comment by rangav** [comment]
Ok good, will include this feature in next update

**Comment by thisisdev-patrick** [comment]
I run my e2e tests with an iterations file (using 10 different scenario's, vars differ). Will that be supported? Thanks in advance

**Comment by rangav** [comment]
@thisisdev-patrick yes its in roadmap.

**Comment by technoorange514** [comment]
As per rangav request I am adding my test case here. Reference: [https://github.com/rangav/thunder-client-support/discussions/560](url).

I am using Postman collection runner with csv as a source data file to run the same API call with a different value each time based on the values in the csv file. For example, if the API call is defined with a variable (in this case {{user}}), the values for the variable _user_ would be taken from the external data source (csv file) and render the output for each user:

`GET myapi/{{user}}`


Data file (csv example):
user
Adam
Monica
Ranga

The expected outcome would be the following API requests:
GET myapi/Adam
GET myapi/Monica
GET myapi/Ranga

I hope this makes sense.

Thank you.

**Comment by jordanrvillarreal** [comment]
I have the similar use cases as described above, but for `POST`.  I have a very simple API interaction that looks like this:

```
{
  "name": "{{manufacturerName}}",
  "url": "{{manufacturerUrl}}"
}
```

And I would like to be able to use a CSV to run that `POST` multiple times.  CSV would look like this:

```
manufactureName,manufactureSlug
Cisco,www.cisco.com
Juniper,www.juniper.com
Palo Alto,www.paloaltonetworks.com
```

Which would result in (only doing the first one):

```
{
  "name": "Cisco",
  "url": "www.cisco.com"
}
```

Thank you!

**Comment by rangav** [comment]
@PikaFederation thanks for sharing your use-case details, it's in my priority list, will implement asap.

**Comment by rangav** [comment]
Hi All, Started development on this feature. nearly 80% done. Hoping to finish by weekend.

Will share few screenshots and also how it works later. 

Once I finished development, I want you guys to help me in beta testing this feature.

let me know who will be available for testing?

**Comment by rangav** [comment]
Hi All, finished development of this feature. 

Would you like to test? I can upload `vsix `file here for testing

**Comment by rangav** [comment]
Here are screenshots of the feature, Let me know your feedback or any questions

<img width="954" alt="run-1 (1)" src="https://user-images.githubusercontent.com/8637550/183488725-1b271055-c9a2-46a6-8ce8-3b3e6da826b0.png">

<img width="940" alt="run-2" src="https://user-images.githubusercontent.com/8637550/183488844-8cc77aba-859c-469e-96b1-429572889524.png">

<img width="950" alt="run-3" src="https://user-images.githubusercontent.com/8637550/183488897-e17cf5b8-4152-4b9c-abf3-8e87e7b21a27.png">

**Comment by genieai-vikas** [comment]
@rangav I would like to test it. could you share `vsix` file

**Comment by rangav** [comment]
Here is the vsix file, please let me know your feedback.
[vscode-thunder-client-1.17.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/9304090/vscode-thunder-client-1.17.2.vsix.zip)

**Comment by genieai-vikas** [comment]
@rangav Thanks Rangav.
I did quick test. Here is my findings
1. My test ran 174 times but I am not able to find all the results. In below screenshot I can see only current iteration result. I can see all result only when I export it. 
2. I exported result in csv. my test ran 174/10000(I cancelled) but in report I see result `Error` for all iteration after 174. It should be sometime `cancel/not executed/` or just generate report of the ran iteration.

1.
![image](https://user-images.githubusercontent.com/86361824/184025894-56973efe-31c2-42d8-9164-6f06a6279372.png)

2.
![image](https://user-images.githubusercontent.com/86361824/184027286-6a72cc9b-998c-4711-b28e-09ca92ca97f6.png)

**Comment by rangav** [comment]
Hi @genieai-vikas thanks for the feedback. Will fix those issues.

To see results of the other iterations move the slider to the iteration required.
<img width="904" alt="Screenshot 2022-08-10 at 23 09 08" src="https://user-images.githubusercontent.com/8637550/184029162-eb33cb41-f35c-456b-b956-a329bc7c2cea.png">

**Comment by rangav** [comment]
one question: how many max iterations you would run normally?

**Comment by genieai-vikas** [comment]
@rangav Ah! I didn't use the slider. Cool! it's all good now. Also, Can I add one more suggestion.
Can we add column for pass and fail. Suppose I ran my test 1000 times. How can I quickly see how many of it is passed and failed(just the count). I can check on the csv but it's good to have.

`one question: how many max iterations you would run normally?`

Normally 100-200 but when I have to check the performance for long duration. I increase it to 5000-10000

**Comment by rangav** [comment]
@genieai-vikas thats a good suggestion too, will implement that.

#### Auto-Scroll feature
If you run more than 10-20 tests, then there is cool `auto-scroll` feature, the page goes `up-down` automatically. you can test and let me know any feedback on this too.

**Comment by genieai-vikas** [comment]
@rangav Sure! I will test this scenario today

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v1.18.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v1.18.0

Please let me know your feedback.

**Comment by rangav** [comment]
Hi All, hope your guys used the new advanced collection runner.

can you please let me know your feedback?

**Comment by rangav** [comment]
Hi All, can you please let me know any further feedback on this feature?

**Comment by JoelRozencweigPPN** [comment]
Hello, how are you supposed to write the variables in the URL? I've tried with {{variable}} but it doesn't work …

**Comment by rangav** [comment]
`{{variable}}` will work, make variable is present in environment and env is set active

**Comment by JoelRozencweigPPN** [comment]
OK 👍 Some additional feedback, I'm generally using CSV for data files, it would be great if you could support this file type in the future …

**Comment by rangav** [comment]
@JoelRozencweigPPN thanks for feedback, can you please create a new feature request, we can discuss there
