### ISSUE TITLE
tiny typo on the changelog

### ISSUE THREAD

**Issue by ycdtosa** [rangav/thunder-client-support#950]
at https://marketplace.visualstudio.com/items/rangav.vscode-thunder-client/changelog

last release is stated as:

v2.2.4 - (2022-12-226)
---------------------^---
someone did not remove the 2 after C&P

Cheers

**Comment by rangav** [comment]
Thanks for finding the typo mistake, will fix in next update

**Comment by rangav** [comment]
This error is fixed now, please update to `v2.3.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.
