### ISSUE TITLE
Activating git sync does not save existing requests

### ISSUE THREAD

**Issue by sorinluc** [rangav/thunder-client-support#951]
First of all : thanks for the extension, it works and feels really great so far !

**Describe the bug**
I already had a collection of ~10 saved requests and several environments when I saw the "git sync" feature, which looks neat for teamwork !
I activated it from the workspace settings and restarted VSCode.
However, upon restart, none of my requests are visible anymore.
Despite what the docs says, there is no `thunder-tests` folder created. Instead, requests were saved into 2 files named `thunder-collection_<collection-name>.json` and `thunder-environment_<env-name>.json`.
Deactivating the feature makes the requests available again.

However, when I create a request _after_ activating the git sync feature, `thunder-tests` is created and works as expected.

**To Reproduce**
1. Make sure that the git sync setting is disabled
2. Create a collection containing requests
3. Activate the git sync feature from the workspace settings

**Expected behavior**
Existing requests should be saved upon git sync activation.

**Platform:** 
 - OS: Ubuntu 20.04
 - vscode version: 1.74.2
 - extension version: 2.2.4

**Your Team Size Using TC:**
5 happy members !

**Comment by rangav** [comment]
@sorinluc Glad you like the extension.

This is expected behaviour. You need to copy the `4 db files` created earlier to the new location.
 
 Or you can export the collections and environments and import again with git sync enabled.
 
 Let me know if you have any further questions

**Comment by sorinluc** [comment]
Worked like a charm !
Any insight on why this behaviour is intended ?
I can help with updating the README file to clarify this use case if you want !

**Comment by rangav** [comment]
Good you got it working.

The reason the extension does not move the files by default of following reasons.

- Users have option to save data to default location when there is not project is open.
- Users can enable git sync and open different projects so the extension does not know where to move file
- It is difficult to expect what user intends to do, as each user will have different expectations.

So I thought I will leave this to user to manually perform one time operation.

**Comment by sorinluc** [comment]
Makes sense !
I opened a pull request with a proposal for light updates to the documentation, feel free to accept or not :smile:   

Thanks for the **very** quick answers !
