### ISSUE TITLE
Set headers from filter script

### ISSUE THREAD

**Issue by thomasddn** [rangav/thunder-client-support#953]
**Describe the bug**
Request headers added in a pre-run custom filter are not applied to the request.

**To Reproduce**
```js
function addHeaders() {
    tc.request.headers = [
        ...tc.request.headers,
        { name: "Date", value: date }, 
        { name: "Authorization", value: signature }
    ];

    // This logs all headers, including the new ones. It also means that the filter is executed.
    console.log(tc.request.headers);
}
```

**Expected behavior**
Added headers should be included in the request.

**Platform:** 
 - OS: Windows
 - vscode version: 1.74.2
 - extension version: 2.2.4

**Your Team Size Using TC:**
Just testing out TC, so 1.

**Comment by rangav** [comment]
Thanks @thomasddn for the feedback, Will add to roadmap.

it’s not a bug, we have enabled this feature yet.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.3.0`

`{{myTestFilePath | readFile | btoa}}`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.

**Comment by thomasddn** [comment]
Works like a charm! 👌

**Comment by rangav** [comment]
Thanks for confirmation
