### ISSUE TITLE
Request: Extra logging when generating tokens.

### ISSUE THREAD

**Issue by YpsilonTM** [rangav/thunder-client-support#956]
**Is your feature request related to a problem? Please describe.**
No, Its more of an extra logging feature.

**Describe the solution you'd like**
So what I would like to see it when generating an OAuth2 token in the Auth tab. That it will log the responses also in the output tab. At the moment it only logs the request. But for example when I generate my Auth token the response will come with a refresh token and it would be nice to see that token if you want to test something with it.

**Describe alternatives you've considered**
Alternative solution of course is to just do the requests manually. Then you can see the full responses. That is why this is more a quality of life thingy than a real needed feature.

**Comment by rangav** [comment]
Thanks @YpsilonTM  for feedback, Will add to roadmap.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.3.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.
