### ISSUE TITLE
Consider on-boarding to vscode sponsor

### ISSUE THREAD

**Issue by isidorn** [rangav/thunder-client-support#958]
Hi VS Code PM here 👋 

First of all, thanks for your great extension 👏 
I see you have on-boarded to GitHub sponsor for your work.
Consider also doing it for your extension so we render a nice heart in VS Code. More details here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#extension-sponsor

**Comment by rangav** [comment]
Hi @isidorn glad you like the extension 🙂

Thanks for the suggestion, will add `sponsor` option in the next update

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.3.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.

**Comment by isidorn** [comment]
Looks great, thanks!
![Screenshot 2023-01-06 at 10 03 34](https://user-images.githubusercontent.com/1926584/210967895-551f734b-91ed-423e-9886-11b79d9179aa.png)

**Comment by rangav** [comment]
You are welcome 👍

**Comment by rangav** [comment]
@isidorn One question: Since your are PM in VSCode team.

I would like to request for one feature, which is useful extension developers using Webviews.
https://github.com/microsoft/vscode/issues/129822

Let me know if its possible?

**Comment by rangav** [comment]
@isidorn thanks for the reply. 

- Enabling dirty indicator on Webviews gives developers more flexibility, to develop UI based extensions.
- And also Webviews are easier to use than Custom Editors in VSCode.

Sure Will open a new issue for this.

**Comment by rangav** [comment]
@isidorn created new issue
https://github.com/microsoft/vscode/issues/171157
