### ISSUE TITLE
Prioritize .env variables over variables declared in the Env section

### ISSUE THREAD

**Issue by teisnet** [rangav/thunder-client-support#959]
To make it easier to overwrite environment variables in a version-control friendly way, variables defined in .env files should take priority over variables with the same name in the Environment section.
Then, by .gitignoring the .env-files it will be possible to prevent local, possibly sensitive, settings to be checked in to version control. The variables in the Environment section will act as defaults and an easy way to see which variables are needed.

**Comment by rangav** [comment]
Hi @teisnet Thanks for the feedback.

The priority depends upon where the .env file is attached. 
https://github.com/rangav/thunder-client-support#environments

To Ingore sensitive variables you can also use [Local Environment](https://github.com/rangav/thunder-client-support#environments)

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
