### ISSUE TITLE
add extension setting to disable auto sending request on importing curl.

### ISSUE THREAD

**Issue by amiroooo** [rangav/thunder-client-support#960]
sometimes we have to import sensitive request through curl import, but we do not want the request to automatically be called on import. so I suggest giving us the option to only open new request tab with imported curl data without having it run automatically upon import.

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.3.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

Please let me know your feedback.
