### ISSUE TITLE
Nothing Works when Running As Administrator

### ISSUE THREAD

**Issue by RichardMeadowsTC** [rangav/thunder-client-support#965]
**Describe the bug**
Just opens to a blank page.  The 'New Request' button is missing.  I have a refresh/reload button and the ... that opens menu. Can get to the extension settings from there.

**To Reproduce**
Run VSCode as an administrator.  ( Hold Shift + Ctrl when launching it )
Add Thunder Client Extension.

**Expected behavior**
The plugin is functional.

**Platform:** 
 - OS: Windows 11 build 22621.ni_release.220506-1250
 - vscode version: 1.72.1
 - extension version: v2.3.0

**Your Team Size Using TC:**

Unknown : Anywhere from 2 to 100,000

**Comment by rangav** [comment]
Thanks @RichardMeadowsTC for reporting the error.

1. Can you please update `vscode` to latest version and try installing Thunder Client.
2. If the issue still there, please try installing previous version of extension

**Comment by rangav** [comment]
Just now tested on windows with VSCode  Run as Administer mode, all working for me without any issues.

**Comment by RichardMeadowsTC** [comment]
Did you use same version that I am using?

Richard Meadows

**Comment by rangav** [comment]
I am using these versions

- windows 10
- vscode 1.74.2
- extension v2.3.0


Try installing latest version of vscode.

**Comment by RichardMeadowsTC** [comment]
This is not easy to reproduce.  I setup a new machine running Windows 11.  Install VSCode and Thunder Client. Issue didn't reproduce.  I think might need to install Thunder Client while SVCode is running as Admin.  Could be some other thing in my environment contributing to it not working.

**Comment by rangav** [comment]
I dont have windows 11 device with me.  

You can try below if you still have issue.
- Install extension in vscode in normal ( not admin mode)
- Try uninstall and re-install extension
- Try installing `previous` version of extension.
- Sometime `restart` windows  devicecan also work.

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
