### ISSUE TITLE
Always return error response

### ISSUE THREAD

**Issue by TECH7Fox** [rangav/thunder-client-support#969]
**Is your feature request related to a problem? Please describe.**

When I want to test my endpoint, and it returns a error it doesn't show the actual error. Just "request failed...".
For traceback you could look at your application logs (although not so nice as seeing it right in the response), but when you want to test for example a error message, you just can't.

**Describe the solution you'd like**

Always display the response. Instead of showing the error code in the center of where the response should be, I suggest showing it in the top left.

Insomnia shows the error code, and the description of the error code.
![image](https://user-images.githubusercontent.com/32220029/211357831-e02a5c75-6400-428e-bbef-a3e92a367664.png)
I know I keep reffering to Insomnia, but it is and looks very simular to this and it's very polished.

I get this:
![image](https://user-images.githubusercontent.com/32220029/211356628-7963333a-4a6d-4899-8b6b-98ed087f4fc3.png)

While I expect something like this (Insomnia):
![image](https://user-images.githubusercontent.com/32220029/211356543-6d8b0278-fc55-42fe-92f0-c003c2c7e53d.png)

**Comment by rangav** [comment]
@TECH7Fox Are you using `axios` library here? if I use `got` i can see the error details in the extension

<img width="437" alt="Screenshot 2023-01-11 at 17 44 34" src="https://user-images.githubusercontent.com/8637550/211879700-3f7af757-b807-40a6-a292-e5fb41a821f7.png">

**Comment by TECH7Fox** [comment]
Oh wow your right. Indeed when using `got` it works actactly like expected.
This works fine for me then, thanks.

**Comment by rangav** [comment]
Thanks for confirmation, will fix for `axios`  in the next update.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.3.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.1

Please let me know your feedback.

**Comment by TECH7Fox** [comment]
Works great. Thanks!

**Comment by rangav** [comment]
Thanks for confirmation 👍
