### ISSUE TITLE
Feature request: display responses of type images etc.

### ISSUE THREAD

**Issue by fc7** [rangav/thunder-client-support#97]
The Thunder client displays responses as code, which is fine for text responses like JSON, XML, etc.. This is not so good when APIs return binary payload such as images that could be easily displayed in VS Code. Example with an API that returns a PNG:

<img width="635" alt="Screen Shot 2021-04-30 at 22 30 16" src="https://user-images.githubusercontent.com/85877/116751027-b4361880-aa03-11eb-8276-8a3856b0bc23.png">

It would be nice to be able to display media types that are natively supported by VS Code, instead of displaying the binary content.

**Comment by rangav** [comment]
Hi @fc7 will add to roadmap.

**Comment by rangav** [comment]
Hi all, this feature will be part of next update v1.7.0

**Comment by rangav** [comment]
This feature is now implemented in v1.7.0
https://github.com/rangav/thunder-client-support/releases/tag/1.7.0
