### ISSUE TITLE
Authorizations are mutually exclusive

### ISSUE THREAD

**Issue by frob** [rangav/thunder-client-support#970]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to pass compatible multiple authorizations to a request.

I have a service that is behind basic auth on the webserver and the service requires a bearer token. Currently in the Authorization section it will only pass the one selected method of authorization.

**Describe the solution you'd like**
The two smallest fixes is allow for inline basic auth to pass or add a checkbox that toggles basic auth from the Authorization section.

**Describe alternatives you've considered**
I attempted to add the basic auth credentials inline in the url but that didn't work for some reason. I tested it with Curl in my terminal and it works so I know the url works outside of Thunder.

**Your Team Size Using TC:**
1 so far. Department size is 10ish.

**Comment by rangav** [comment]
Hi @frob Thanks for the feedback 

can you share a sample curl command how you sent both basic auth and bearer token

Use this same url: http://httpbin.org/anything
Use dummy auth values

then I can how we can do it in TC.

**Comment by rangav** [comment]
Closing this issue, feel free to continue discussion
