### ISSUE TITLE
Auth: Accept any Auth callback path and support https

### ISSUE THREAD

**Issue by hallzhallz** [rangav/thunder-client-support#971]
**Is your feature request related to a problem? Please describe.**
I cannot easily change the OAuth application allowed Redirect URIs. I would like to be able to do some testing and use a proxy tool like Telerik Fiddler to map a valid Redirect URI host to the Thunder Client localhost auth callback.

This way I can test without changing any configuration of the applications redirect uri's.

eg.
I map `my-domain.com` -> `localhost:6789` in the Telerik Fiddler tool.
specify `https://my-domain.com/app-callbackpath` as callback url in Thunder Client auth config.
Click Generate Token in Thunder Client.
The request gets mapped to the Thunder Client callback by Telerik Fiddler.
Thunder Client consumes the request.

*At the moment this doesn't work as Thunder Client will only respond to path of `/callback` and also does not support https.

**Describe the solution you'd like**
1. Make the Auth callback http listner respond to any path that is supplied rather than just '/callback'
2. Implement https on the callback endpoint. The browser won't go from an https redirect URI to a http one.

**Describe alternatives you've considered**
I have tried calling the callback url myself with Invoke-WebRequest in powershell. This appears to work on the request but then in Thunder Client there is an error obtaining the token.

Update: I managed to get an access token manually. It looks like when Thunder Client requests the token it will also need to set the `Origin` header to be the `Redirect URI` for this to work (I had to do this manually for the access token request to work).

**Your Team Size Using TC:**
1-2 at this stage.

**Comment by rangav** [comment]
Hi @hallzhallz Currently to get token back to extension, we have to use TC provided callback url. As there is integration built into extension to read the token.


Will check if its possible use any custom url for callback, when I got free time.
