### ISSUE TITLE
Folder with endpoints not found when in workspace

### ISSUE THREAD

**Issue by pedro3g** [rangav/thunder-client-support#973]
I recently created a workspace in vscode, however, Thunder was unable to identify the folder containing the endpoints.

Create an endpoint backup folder;
Open a workspace in VSCode.

Correctly list the endpoints contained in the endpoint files.

**Platform:** 
 - OS: Windows
 - vscode version: 1.74.3
 - extension version: 2.3.0

**Comment by rangav** [comment]
HI @pedro3g thanks for reporting the issue. did you enable `save to workspace` setting?

See `Note 3` section in below link
https://github.com/rangav/thunder-client-support/blob/master/README.md#git-sync

**Comment by rangav** [comment]
Do you still have this issue?

**Comment by rangav** [comment]
I am closing this issue, feel free re-open if needed
