### ISSUE TITLE
Import functionality is skipping the preReq information

### ISSUE THREAD

**Issue by m00dsw1ng** [rangav/thunder-client-support#974]
**Describe the bug**
When you export a collection which contains requests which contains PreRun requests. You will notice that the exported .json file contains the preReq property with the runRequests. When you now delete the collection from Thunderclient en try to import the exported collect however, you won't see the 'Pre Run' in your request. 

**To Reproduce**

- Have a collection with a multiple requests, make sure one of the requests has the Pre Run / Pre Requests configured to make sure another request is run first. 
- Now export the collection
- Now delete the collection from your thunderclient
- Now import the exported collection again
- You will notice that the request that previously had a pre-run configured, now there is nothing configured. However if you inspect the exported json file. The information regarding pre-requests is clearly there.

**Expected behavior**
Upon importing the pre-run configuration should be imported correctly.

**Platform:** 
 - OS: Microsoft Windows 10 Enterprise (10.0.19044 N/A Build 19044)
 - vscode version: 1.74.3
 - extension version: 2.3.0 (have tried older versions as well 2.1.0)

**Your Team Size Using TC:**
2

**Comment by rangav** [comment]
Thanks @m00dsw1ng for reporting the bug, will look into it.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.3.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.1

Please let me know your feedback.

**Comment by m00dsw1ng** [comment]
Hi @rangav,

I've updated to 2.3.1 and retested but still upon import the 'Pre Run' on the Collection Settings are missing. They are there in the export json. The referenced Id's are also pointing to the right request to pre-run. 

I've tested version 2.3.1 and 2.3.2 (latest)

Thank you.

**Comment by rangav** [comment]
@m00dsw1ng will verify again later today and get back to you

**Comment by rangav** [comment]
[thunder-collection_Testing3.zip](https://github.com/rangav/thunder-client-support/files/10455345/thunder-collection_Testing3.zip)

I have tested, its working fine for me.

I have attached a sample collection, you can import and test yourself.

Please copy the `filter2.js` file to root of the project.

One issue I can think of is filter javascript file location could be different on the imported machine.

**Comment by rangav** [comment]
Thanks I can re-produce the issue now.

Earlier I missed the step, delete the existing collection before import.

**Comment by rangav** [comment]
@m00dsw1ng I have finished fixing this bug, would you like to test and confirm?

I can upload the `vsix` file here

**Comment by m00dsw1ng** [comment]
Hi @rangav, tested it again and it seems to be working correctly right now. 

Thank you very much!

**Comment by rangav** [comment]
Thank you for confirmation 👍, will publish to marketplace later today

**Comment by rangav** [comment]
This bug is fixed now, Please update to `v2.3.3`

**Comment by m00dsw1ng** [comment]
Thank you @rangav
