### ISSUE TITLE
Variables not uploading in pre run, request body fail.

### ISSUE THREAD

**Issue by Mmartos13** [rangav/thunder-client-support#975]
**Is your feature request related to a problem? Please describe.**

I have configured a custom filter in which I read a .json with a X MB through (screenshot1) , this value is storage on a variable named as body. 
When I try to run a request which use this variable body as body I got the error 400 Bad request due. The problem is that in the pre run where this variable is supposed to be loaded cannot load the content fast enough due to its size I also think that this problem may be causes because the function setEnv is asynchronous and the request is sent before is finished.  If I retry the request it works correctly because the variable body is charged.  
![image](https://user-images.githubusercontent.com/73356168/212839787-6d03c5b4-d7bd-447a-a2c8-df230b568433.png)
![image (1)](https://user-images.githubusercontent.com/73356168/212839809-2ffe33d2-ed3b-40a3-ba08-fc2e51594597.png)

**Describe the solution you'd like**

I would like to be able to attach a body to a request that is precharged from a file, but the great solution It will be to run the pre-run scripts always before request. 

**Describe alternatives you've considered**

If there is possibility of use an async to upload a variable and later call request so it can finish loading the body it would be great.

**Platform:** 
 - OS: Ubuntu 20.04 LTS
 - vscode version:1.72.2
 - extension version:v2.3.0

**Your Team Size Using TC: 8

**Comment by rangav** [comment]
@Mmartos13 Thanks for reporting the bug. Currently modifying the `body` is not yet enabled.

If you are just reading the file, you can use `readFile` filter

details here
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.0

**Comment by Mmartos13** [comment]
Hello, thanks for answering fast, the problem is that I read the file and take part of the information to ensamble the body, the file contains the information raw and every petition must take what it needs in order to make its request, the script flow right now is: readFile, ensamble body, update variable {{body}}, send request

**Comment by rangav** [comment]
thanks got it. Looks like there is a bug, when set the variable in Pre-Filter. Will fix later today.

**Comment by Mmartos13** [comment]
All rigth, thanks you so much. I will test it as soon as it gets fixed.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.3.1`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.3.1

Please let me know your feedback.
