### ISSUE TITLE
URL parsing issue when converting to Postman

### ISSUE THREAD

**Issue by bigmike36c** [rangav/thunder-client-support#976]
**Describe the bug**
Similar to [issue #775](https://github.com/rangav/thunder-client-support/issues/775), any collection that is converted to the Postman format parses parameters such as `{{api_url_content}}` to `%7B%7Bapi_url_content%7D%7D` which causes issues with the collection.

**To Reproduce**

- Create some variable on the env, let's say `test` and have a value of `test`
- Choose some collection and go to settings, set the base url to `http://localhost:3000/{{test}}`
- Convert the collection to postman
- Inspect the URL of exported collection

**Expected behavior**
In the postman collection, the path should be `["{{test}}"]` instead of `["%7B%7Btest%7D%7D"]`

**Platform:** 
 - OS: MacOS 12.6.1
 - vscode version: 1.74.3
 - extension version: 2.3.1

**Comment by rangav** [comment]
Thanks @bigmike36c for reporting the bug, will look into it.

**Comment by rangav** [comment]
I was not able to re-produce this issue, can you make sure the steps are correct?

Thunder Client Collection
[thunder-collection_Testing.json.zip](https://github.com/rangav/thunder-client-support/files/10439274/thunder-collection_Testing.json.zip)

Converted To Postman Collection
[thunder-collection_Testing_postman.json.zip](https://github.com/rangav/thunder-client-support/files/10439273/thunder-collection_Testing_postman.json.zip)

Let me know if I am missing anything

**Comment by bigmike36c** [comment]
I have no issues importing the test collections you shared so it must be something specific to my collections. Let me experiment and get back to you.

**Comment by bigmike36c** [comment]
Hey @rangav, sorry about that. I should have double checked my post. I've updated the steps and the expected behavior. The URL is actually correct but it appears postman actually looks at the `path` key when importing which is where the issue occurs.

**Comment by rangav** [comment]
I still cant reproduce the issue, can you please share TC collection json file ( exported ).

**Comment by bigmike36c** [comment]
Here's a quick example. You should see the issue in the postman file, but let me know if I'm missing something.

Thunder Client Collection
[thunder-collection_Parsing Test.json.zip](https://github.com/rangav/thunder-client-support/files/10448386/thunder-collection_Parsing.Test.json.zip)

Converted To Postman Collection
[thunder-collection_Parsing Test_postman.json.zip](https://github.com/rangav/thunder-client-support/files/10448387/thunder-collection_Parsing.Test_postman.json.zip)

**Comment by rangav** [comment]
Thanks @bigmike36c I can reproduce the issue now. Will fix it later today

**Comment by bigmike36c** [comment]
Awesome! Really appreciate the rapid responses and amazing extension. Just let me know if there is anything else you need from me.

**Comment by rangav** [comment]
Thanks, I finished fixing these bugs, will upload `vsix` file here for you to test? 

Will you able to test quickly and confirm?

**Comment by bigmike36c** [comment]
Absolutely, I can test right now.

**Comment by rangav** [comment]
ok good, will upload in 2 mins

**Comment by rangav** [comment]
[vscode-thunder-client-2.3.2.vsix.zip](https://github.com/rangav/thunder-client-support/files/10449265/vscode-thunder-client-2.3.2.vsix.zip)

Please install the file above and let me know your feedback.

**Comment by bigmike36c** [comment]
Perfect, I can confirm this update has resolved all three of the issues I submitted. Again, really appreciate this awesome level of support!
