### ISSUE TITLE
Collection Auth Settings are not properly converted for postman collection

### ISSUE THREAD

**Issue by bigmike36c** [rangav/thunder-client-support#978]
**Describe the bug**
When converting to a postman collection, the auth settings for the collection are not converted properly. Therefore, the auth settings are simply discarded when importing into postman.

**To Reproduce**

- Create a collection in thunder client
- Add basic auth
- Use thunder client to convert to a postman collection
- Import collection into postman

**Expected behavior**
Auth settings for the collection should be imported into postman. When converting to a postman collection, thunder client stores auth settings in the following format:
`"auth": {
    "type": "basic",
    "basic": {
      "username": "{{username}}",
      "password": "{{password}}"
    }
  }`
But when exporting from postman, auth settings are stored in a different format:
`"auth": {
    "type": "basic",
    "basic": [
      {
        "key": "password",
        "value": "{{password}}",
        "type": "string"
      },
      {
        "key": "username",
        "value": "{{username}}",
        "type": "string"
      },
      {
        "key": "undefined",
        "type": "any"
      }
    ]
  },`

**Platform:** 

- OS: MacOS 12.6.1
- vscode version: 1.74.3
- extension version: 2.3.1

**Comment by rangav** [comment]
@bigmike36c Thanks for reporting the bug, I can re-produce this bug. Will fix it asap.

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.3.2`
