### ISSUE TITLE
Dates in release notes are wrong

### ISSUE THREAD

**Issue by fleed** [rangav/thunder-client-support#980]
**Describe the bug**
The dates for the last two minor releases seem wrong:

<img width="630" alt="CleanShot 2023-01-19 at 13 44 42@2x" src="https://user-images.githubusercontent.com/2131800/213446276-db15e233-9d5b-43b4-8049-68f1677b9afe.png">

**Platform:** 
 - OS: MacOS
 - vscode version: 1.74.3 (universal)
 - extension version: 2.3.2

**Comment by rangav** [comment]
This bug is fixed now, Please update to `v2.3.3`
