### ISSUE TITLE
Adjust order of requests and folders within a collection

### ISSUE THREAD

**Issue by obsidian33** [rangav/thunder-client-support#981]
**Describe the solution you'd like**
I would like to be able to organize requests within a collection and folder in a specific order. Right now you can adjust the ordering of requests in relation to other requests and folders in relation to other folders but if you have a mix of requests and folders at the same level the folders are always at the top with the requests below.

This has direct impact with the 'Run All' feature for a collection. Based on this ordering if I have a request at the collection level with many folders, all of the requests within the folders are set to run before the request at the collection level. I can workaround this by using the 'Pre Run' feature but doing that can be a lot less efficient.

**Your Team Size Using TC:** 24

**Comment by rangav** [comment]
@obsidian33 thanks for the feedback. This could be difficult to change.

alternative solution:

1. you can create new folder at the top of the collection 
2. Then move desired request into that new folder 

the above might solve the issue right?

**Comment by rangav** [comment]
I am closing this issue, As we are not planning to implement this.
