### ISSUE TITLE
Pre Run Request is not populating variable in Tests of said Pre Run Request

### ISSUE THREAD

**Issue by obsidian33** [rangav/thunder-client-support#982]
**Describe the bug**
I have a request that is using an environment variable in the URL, for example: GET {{baseUrl}}strings/manifest.json
This request has a Pre Run Request that has a Test to set the {{baseUrl}} variable value.

Right now I am getting a an ERROR: Couldn't resolve the hostname to an IP address, Verify Url: http://%7B%7BbaseUrl%7D%7Dstrings/manifest.json

The error is clearly indicating that the baseUrl variable was was not injected. When I view the environment variables I see that the baseUrl variable was not set.

**To Reproduce**

1. Setup request 1 with a Test that sets an environment variable, e.g. {{baseUrl}} 
2. Setup request 2 using {{baseUrl}} in the URL and verify that it does not exist yet in the active environment variables
3. In request 2 add a Pre Run Request that calls Request 1
4. Run Request 2 which gives the error.

**Expected behavior**
In the steps to reproduce above it is expect that request 2 would run the Pre Request (request 1) first. This would then create the environment variable {{baseUrl}}. Then request 2 would run and be able to inject the newly created {{baseUrl}} variable value.

**Platform:** 
 - OS: Win 10.0.19044
 - vscode version: 1.74.3
 - extension version: v2.3.3

**Your Team Size Using TC:** 24

**Comment by rangav** [comment]
@obsidian33 thanks for reporting the bug.

can you run request 1 directly and see whether `baseUrl` is set or not?

can you please share screenshot of `Tests` tab of `request 1`?

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed.

**Comment by obsidian33** [comment]
@rangav sorry for the delayed response. I did not see the email with your previous comment.

Here is what you requested:

- Can you run request 1 directly and see whether `baseUrl` is set or not?
Yes when I run request 1 itself the `baseUrl` is set.

- Can you please share screenshot of `Tests` tab of `request 1`?
![image](https://user-images.githubusercontent.com/6493594/221689441-e5ebce08-b84e-4327-bb70-5744f18d8a01.png)

**Comment by rangav** [comment]
Thanks @obsidian33 for sharing info.

Can you open environment view and see the variable value set for `baseUrl`?

**Comment by rangav** [comment]
Also after verifying the env value for `baseUrl`

Please remove pre request for request 2 and run the request 2 and let me know if its working or not?

Also can you request 2 screenshot if possible.

**Comment by rangav** [comment]
I just now tested - its working for me

Request 1
<img width="1018" alt="img-1" src="https://user-images.githubusercontent.com/8637550/221696017-7b9bd906-091e-4bb8-8cf0-6d9ce66f2f23.png">

Request 1 - Tests tab
<img width="1020" alt="img-2" src="https://user-images.githubusercontent.com/8637550/221696037-a1e294f1-cc81-44cf-815c-0e5f81159cad.png">

Request 2
<img width="1275" alt="img-3" src="https://user-images.githubusercontent.com/8637550/221696060-b155edc9-ffc5-48af-b889-319579950df5.png">

Env BaseUrl
<img width="829" alt="img-4" src="https://user-images.githubusercontent.com/8637550/221696130-e56c3a97-e05a-430b-8451-5dfb991b6f55.png">

**Comment by obsidian33** [comment]
With your setup please delete `baseUrl` from the environment variables and now only run Request 2.

**Comment by rangav** [comment]
I did that already - its working for me.

You can try using the above test urls and please share same 4 screenshots as above?

**Comment by obsidian33** [comment]
Request 1
![image](https://user-images.githubusercontent.com/6493594/221702267-fafcacd4-521a-4bd3-9467-f97a3da9f2b9.png)


Request 1 - Test tab
![image](https://user-images.githubusercontent.com/6493594/221702061-e87883dd-7000-4bb0-9a2f-8669c82b791f.png)

**But please note that it is important that the even though I ran Request 1 to verify it worked. I deleted the `baseUrl` from the environment variables before running Request 2.**

Request 2 
![image](https://user-images.githubusercontent.com/6493594/221702335-a0c8e9fe-df0d-468b-85aa-b1c3b07602dc.png)

Environment Variables
![image](https://user-images.githubusercontent.com/6493594/221702430-c66418dd-bb8e-4dc8-a419-876d88450abe.png)

**Comment by rangav** [comment]
Oh good. Let me know if you can reproduce the issue again
