### ISSUE TITLE
Error when sending request: ENOENT: no such file or directory, open 'C:\Users\Noam\.th-client\thunder-cookies.json'

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#983]
**Describe the bug**

When running a request on the latest version (2.3.3) I get this error:
Error when sending request: ENOENT: no such file or directory, open 'C:\Users\Noam\.th-client\thunder-cookies.json'

The error was resolved only once I created a folder called .th-client

**To Reproduce**

deleted the folder .th-client and run a request

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Your Team Size Using TC:**

**Comment by rangav** [comment]
@noam-honig thanks for reporting the bug, will fix it asap.

you can downgrade to previous version till then.

**Comment by noam-honig** [comment]
I created the folder `.th-client` and it works - I prefer that to revert to the previous version.

Thanks for getting back to me so fast

**Comment by rangav** [comment]
This bug is fixed now, please update to `v2.3.4`
