### ISSUE TITLE
Collection export (.json) functionality should export json formatted

### ISSUE THREAD

**Issue by m00dsw1ng** [rangav/thunder-client-support#985]
**Is your feature request related to a problem? Please describe.**
It's not a problem perse, more a nice to have

**Describe the solution you'd like**
Would be nice when you export the collection, or environment json files, that they are acutally json formatted

**Describe alternatives you've considered**
Now we just export, open the exported file in vscode and do a 'format document' and then save again

**Your Team Size Using TC:**
2

**Comment by rangav** [comment]
Thanks @m00dsw1ng for the feedback, will implement in the next release

**Comment by m00dsw1ng** [comment]
Cool, thanks @rangav

**Comment by rangav** [comment]
This feature is now implemented and published to marketplace, please update to `v2.4.0`

### Thunder Client CLI
- https://github.com/rangav/thunder-client-support/releases/tag/v2.4.0

### Documentation
- For documentation read our blog post on [medium.com](https://rangav.medium.com/d91eb5c71d8e)

### Product Hunt
- We are launching today on [Product Hunt](https://www.producthunt.com/posts/thunder-client-cli), Please upvote and let us know any feedback.
