### ISSUE TITLE
useful keyboard shortcuts are hijacked by thunder client - Ctrl p, Ctrl Shift P

### ISSUE THREAD

**Issue by noam-honig** [rangav/thunder-client-support#986]
**Describe the bug**

When focused on a thunder client request, the Ctrl P (open file) and Ctrl Shift P (goto type) VS code shortcuts don't work.

I often use these shortcuts to navigate through files - and they work everywhere. They only don't work when I'm focused on a thunder client window.

I know I can change the keyboard mapping myself - but I believe that this is an inconsistency that is based fixed as the default

**To Reproduce**

**Expected behavior**

**Platform:** 
 - OS: 
 - vscode version:
 - extension version:

**Your Team Size Using TC:**

**Comment by rangav** [comment]
both `Ctrl + P` and `Ctrl Shift P` are working for me. Could be other extension causing the issue.

Open keyboard shortcuts and see if there is any overlapping.

**Comment by noam-honig** [comment]
Please try this while focusing on the Body of a request - on it's JSON
Content

**Comment by rangav** [comment]
are you on mac or windows?

**Comment by noam-honig** [comment]
Windows

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.5.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.

**Comment by noam-honig** [comment]
Look great - thanks
