### ISSUE TITLE
How to get UTC timestamp as a variable?

### ISSUE THREAD

**Issue by LucaPaganin** [rangav/thunder-client-support#988]
**Your Team Size Using TC:**

**Question:**

Hello,

I am using Thunder Client to test a REST API of a service for which it is needed the UTC timestamp of the firing of the request as a querystring parameter. I am using the following syntax for generating a timestamp variable

```
{{#date, 'YYYY-MM-DD'}}T{{#date, 'hh:mm:ss.fff'}}
```

However this gives the current system time in my timezone (GMT+01:00 in my case) and not UTC time, while on the server I need the UTC time of the firing of the request.
Can you give me some advice on how to get UTC time as a variable to be put in querystring?

Thanks in advance

**Comment by LucaPaganin** [comment]
Probably I could manipulate the date using this syntax

`{{#date, 'YYYY-MM-DD'}}T{{#date, 'hh:mm:ss.fff', {hour: -1}}}Z`

However this only solves when Italy's timezone is GMT+01:00, i.e. during winter, while for the rest of the year we adopt GMT+02:00 timezone, so the syntax in that case should change like this

`{{#date, 'YYYY-MM-DD'}}T{{#date, 'hh:mm:ss.fff', {hour: -2}}}Z`

Is there a unique way the get the current UTC time independently of the timezone?

**Comment by rangav** [comment]
Hi @LucaPaganin You can use `custom filter` for Utc time.

<img width="1147" alt="Screenshot 2023-01-25 at 20 27 51" src="https://user-images.githubusercontent.com/8637550/214683086-68c99ed6-0016-4761-8c76-bf21ec08d896.png">

Custom Filter Docs
https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

**Comment by rangav** [comment]
you need create any env variable and use the custom filter
or you can use this format `{{@ | utcTime}}` with out the need for env variable.

**Comment by LucaPaganin** [comment]
Thanks for the quick answer @rangav 

Moreover, what is the correct syntax to format the utcTime in 

YYYY-MM-DDThh:mm:ss

For example I would like to generate the date time in this format

2023-01-26T12:34:56.789Z

**Comment by rangav** [comment]
see this
https://bobbyhadz.com/blog/javascript-get-current-date-and-time-in-utc

**Comment by LucaPaganin** [comment]
Oh sorry, I misunderstood your previous answer, I did not look carefully at your screenshot and I was convinced that the utcTime was a sort of built in function.
Now it is clear, I simply get the date in js custom filter file and I build the UTC string in the format I need directly using JavaScript.

Thank you very much for your support and patience

**Comment by rangav** [comment]
i can add `dateUTC` variable in the next update
https://github.com/rangav/thunder-client-support#variables

**Comment by LucaPaganin** [comment]
Yes, IMHO a way to get the current UTC date as a system variable without the need of creating any custom filter would be of help for future users.
Assuming to have a system variable dateUTC the correct syntax to get the ISO string would be

`{{#dateUTC, 'YYYY-MM-DD'}}T{{#dateUTC, 'hh:mm:ss.fff'}}`

Right?

Also, while we are at it, is there a way to format the #date in one shot, maybe using the full format string? Because when I tried

`{{#dateUTC, 'YYYY-MM-DDThh:mm:ssZ'}}`

I got an error

**Comment by LucaPaganin** [comment]
Sorry, I was using

`{{#date, 'YYYY-MM-DDThh:mm:ssZ'}}`

without UTC

**Comment by rangav** [comment]
T & Z are not supported
you should use below format
`{{#date, 'YYYY-MM-DD'}}`T`{{#date, 'hh:mm:ss'}}`Z

**Comment by rangav** [comment]
actually {{#dateISO}} variable will output date in `2023-01-27T15:20:25.346Z ` which is same as UTC date

you can verify
```
console.log(new Date().toUTCString())
console.log(new Date().toISOString())
```

**Comment by rangav** [comment]
I am closing this issue, feel free to re-open if needed
