### ISSUE TITLE
Clearly denote "save to workspace" and "custom location" incompatibility

### ISSUE THREAD

**Issue by joshpsawyer** [rangav/thunder-client-support#990]
**Is your feature request related to a problem? Please describe.**
I didn't realize that the "save to workspace" and "custom location" settings were incompatible and that "save to workspace" would be preferred. I eventually found this comment in Issue 658, but it's not clearly documented under https://github.com/rangav/thunder-client-support#team

**Describe the solution you'd like**
Updating the documentation would provide clarity for somebody else in the same situation but ideally, the settings would be a radio button so you could choose one option and not check off both. This would clearly indicate that only one setting is allowed at a time without digging through documentation.

**Comment by rangav** [comment]
Hi @joshpsawyer thanks for the feedback. Will update documentation soon..

Feel free to submit PR if you like update it.

**Comment by rangav** [comment]
I have updated the documentation as requested.

https://github.com/rangav/thunder-client-support#git-sync
