### ISSUE TITLE
Disable built-in Thunder Client keyboard shortcuts

### ISSUE THREAD

**Issue by transparentech** [rangav/thunder-client-support#991]
Some of the Thunder Client keyboard shortcuts shadow other general keyboard shortcuts I use. For example, I use "Emacs" keyboard shortcuts everywhere, so `Ctrl+E` should move the cursor to the end of the line/field. However, TC uses `Ctrl+E` to change environment.

I have tried setting a custom keyboard shortcut for TCs "Change Environment" command in VSC's "Keyboard Shortcuts" view. However, this does not remove the built-in keyboard shortcuts. That is, `Ctrl+E` is still activating the "Change Environment" command when I'm in a TC tab. 

Note that VSC's "Keyboard Shortcuts" view does not show the build-in shortcuts for TC commands, so it's not possible to remove/change them via the "Keyboard Shortcuts" view. That view only lets us add additional shortcuts for TC commands.

So this feature request is for one of the following:
1. Have TC's built-in keyboard shortcuts display in VSC's "Keyboard Shortcuts" view so they can be removed/changed there.
2. Add a TC extension setting to remove/disable all built-in TC keyboard shortcuts.

**Comment by rangav** [comment]
Thanks @transparentech for the feedback, will add to roadmap.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.5.0`

See all features released
https://github.com/rangav/thunder-client-support/releases/tag/v2.5.0

Please let me know your feedback.

**Comment by transparentech** [comment]
Looks good. Thank you!!

**Comment by rangav** [comment]
You are welcome 👍
