### ISSUE TITLE
Tests: custom filter for HTML response

### ISSUE THREAD

**Issue by andresatierf** [rangav/thunder-client-support#995]
**Your Team Size Using TC:**

I'm in a team of 7 but I think I'm the only one using it.

**Question:**
How can I pass the response HTML to a custom filter
![image](https://user-images.githubusercontent.com/29847057/216101662-68e7d505-560e-4c15-89e3-1893e2ef058c.png)

**Comment by rangav** [comment]
@andresatierf 
You can use Custom Filter for this, and use any node library needed for this.

https://github.com/rangav/thunder-client-support/blob/master/docs/filters.md#custom-filters

Then use this format.
`text | filterName` in the left input.

**Comment by rangav** [comment]
FYI - Here is `Set Environment` docs
https://github.com/rangav/thunder-client-support#setenv
