### ISSUE TITLE
Invalid URL Error due to baseurl generation with ENV variables. 

### ISSUE THREAD

**Issue by muffinhydra** [rangav/thunder-client-support#999]
**Describe the bug**
When exporting a collection to a Postman format using Convert To Postman an Error: Invalid URL is thrown.
**To Reproduce**
1. Run "Thunder Client: Convert to Postman" from the command pallete
2. Choose a location to save
3. "Invalid URL" notification from Thunder Client

The requests are build with the following scheme: 
{{HOST}}:{{PORT}}/xxx/yyy/zzz

with HOST and PORT making up the base URL in the request itself.

Once HOST and PORT are removed from the request itself the export works. 

The collection was originally made with postman and imported. The collection can be imported and exported in postman. 

Also after some time experimenting it does appear to work as intendent, but I cannot zero in what made it possible. Usually after deleting  HOST and PORT exporting it once and then adding both back in solved the issue. 

**Expected behavior**
Extension should generate a postman format JSON based on the provided thunderclient JSON. If this didn't happen a more informative error message should be displayed.

**Platform:** 
 - OS: Windows
 - vscode version: 1.74.3
 - extension version: v2.3.4

**Solution:**
Let the user manually override the URL check or give a more informative error message.

**Comment by rangav** [comment]
Thanks @muffinhydra for reporting the bug, will look into it.

**Comment by muffinhydra** [comment]
> Thanks @muffinhydra for reporting the bug, will look into it.

I think I managed to zero in on the bug. It's the ":" in the URL. If I change it to a "/" then the postman convert works. It just doesn't work with ":".

**Comment by rangav** [comment]
Super thats great. Postman Url format looks little bit complicated to get it right. 

Will check and fix it asap.

**Comment by rangav** [comment]
This bug is fixed now and published to marketplace, please update to `v2.4.0`

### Thunder Client CLI
- https://github.com/rangav/thunder-client-support/releases/tag/v2.4.0

### Documentation
- For documentation read our blog post on [medium.com](https://rangav.medium.com/d91eb5c71d8e)

### Product Hunt
- We are launching today on [Product Hunt](https://www.producthunt.com/posts/thunder-client-cli), Please **upvote** and let us know any feedback.
